### PR TITLE
project_panel: Fix worktree root rename

### LINKED ISSUE #7923: Renaming of root folder has no effect
Summary:

There is an option to rename the root workspace folder, but submitting doesn't have any effect on the name. I'm not sure if it's supposed to work, or if there just shouldn't be an option.

### Environment

Zed: v0.123.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/0ac7f15c-d014-4f21-89bc-2dedf038dab2

Zed.log:
```shell
2024-02-16T13:31:10-05:00 [ERROR] crates/project_panel/src/project_panel.rs:577: Invalid argument (os error 22)
```

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #7923

This PR fixes root worktree renaming by:  

1. Handling the case where `new_path` is the new root name instead of a relative path from the root.  
2. [#20313](https://github.com/zed-industries/zed/pull/20313) added functionality to watch for root worktree renames made externally, e.g., via Finder. This PR avoids relying on that watcher because, when renaming explicitly from Zed, we can eagerly perform the necessary work (of course after fs rename) instead of waiting for the watcher to detect the rename. This prevents UI glitches during renaming root.

Todo:

- [x] Fix wrong abs paths when root is renamed
- [x] Fix explicit scan entry func to handle renamed root dir
- [x] Tests
- [x] Test on Linux
- [x] Tested with single and multipe worktrees
- [x] Tested when single file is root file

Release Notes:

- Fixed an issue where worktree root name couldn't be renamed in project panel.

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -7280,6 +7280,83 @@ mod tests {
         );
     }
 
+    #[gpui::test]
```
Comment (JunkuiZhang) [inline crates/project_panel/src/project_panel.rs:7283]:
```suggestion
    #[gpui::test]
    #[cfg_attr(target_os = "windows", ignore)]
```
We could add this to skip the test on Windows

**Comment by 0xtimsb** [comment]
For future reference: 

Currently renaming root worktree throws fs error `cannot access the file because it is being used by another process`. After talking with @JunkuiZhang, we decided to disable root rename for Windows. This can be revisited later.

As of writing this, VSCode doesn't allow root worktree rename on any OS.
