### PR TITLE
markdown_preview: Fix release notes title being overridden

### LINKED ISSUE #31701: Markdown Preview - Release notes title is overriden
### Summary

Markdown Preview title is overriden.

Steps to reproduce:
1. Update Zed.
2. Click View Release Notes.

Expected Behavior: The opened tab should show the release's title.
Actual Behavior: The opened tab shows `Preview untitled`

<details><summary>Screenshot</summary>
Image
</details>

### Zed Version and System Specs

Zed: v0.189.1 (Zed Preview) 
OS: macOS 15.3.2
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by simonpham**
Closes: #31701

Screenshot:

image

Release Notes:

- Fixed in-app release notes having an incorrect title

### CODE REVIEW

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 1]
```diff
@@ -343,7 +343,11 @@ impl MarkdownPreviewView {
         );
 
         let tab_content = editor.read(cx).tab_content_text(0, cx);
-        self.tab_content_text = format!("Preview {}", tab_content).into();
+
+        // Only update the tab content if it's not have a default value.
```
Comment (Peiffap) [inline crates/markdown_preview/src/markdown_preview_view.rs:347]:
```suggestion
        // Only update the tab content if it doesn't have a default value.
```

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 2]
```diff
@@ -130,7 +130,7 @@ impl MarkdownPreviewView {
             editor,
             workspace_handle,
             language_registry,
-            "Markdown Preview".into(),
+            "".into(),
```
Comment (SomeoneToIgnore) [inline crates/markdown_preview/src/markdown_preview_view.rs:133]: Let's change this a bit:

* `""` is a bit too magical, what we can do is use `tab_content_text: Option<SharedString>` as a default value.

* then, inside `fn tab_content_text` it would be something like `self.tab_content_text.cloned().unwrap_or_else(|| SharedString::from("Markdown Preview"))`.

* and the `if self.tab_content_text.is_empty()` check will do `is_none` instead.

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you for the catch and fix.

Let's avoid magical constants and merge this.

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, almost there: one small NIT fixed and we're ready to merge.
(and the formatting fixes for the CI, of course)

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you.
