### PR TITLE
git: Don't show binary files in past commit view

### LINKED ISSUE #45735: Zed crashes when viewing git diffs that includes images
### Reproduction steps

1. Open a git project with zed
2. Commit a few images (i did around 7 webp files)
3. Click on commit to see change
4. Zed shows the images as binary, and hangs, and then shortly after crashes

### Zed version and system specs

Zed: v0.217.3+stable (Zed) 
OS: Linux Wayland arch unknown
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon HD 7900 Series (RADV TAHITI) || radv || Mesa 25.3.2-arch1.1

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2025-12-27T13:34:21+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:21+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:29+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:34:29+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:29+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:29+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:34:29+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:29+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:36+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:34:36+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:36+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:36+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:34:36+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:34:36+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:21+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:21+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:21+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:21+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:21+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:21+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:22+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:22+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:22+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:25+03:00 ERROR [crates/gpui/src/window.rs:1127] window not found
2025-12-27T13:35:25+03:00 ERROR [crates/gpui/src/window.rs:1139] window not found
2025-12-27T13:35:25+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:35:25+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:35:27+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-12-27T13:35:27+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:35:27+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-12-27T13:35:30+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:35:55+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-site", args: ["/home/zor/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2025-12-27T13:35:55+03:00 INFO  [project::prettier_store] Initializing default prettier with plugins {"prettier-plugin-astro"}
2025-12-27T13:35:55+03:00 INFO  [lsp] Language server with id 124 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Setting up server…"
}
2025-12-27T13:35:55+03:00 INFO  [lsp] Language server with id 124 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Listening for messages…"
}
2025-12-27T13:35:56+03:00 INFO  [project::prettier_store] Installing default prettier and plugins: [("prettier-plugin-astro", "0.14.1"), ("prettier", "3.7.4")]
2025-12-27T13:35:57+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-site", args: ["/home/zor/.local/share/zed/extensions/work/astro/node_modules/@astrojs/language-server/bin/nodeServer.js", "--stdio"]
2025-12-27T13:35:58+03:00 WARN  [project::lsp_store] unhandled capability registration: Registration { id: "c32040e5-7739-40da-b339-5c63dfe5bf4e", method: "workspace/willRenameFiles", register_options: Some(Object {"filters": Array [Object {"pattern": Object {"glob": String("**/*.{js,cjs,mjs,ts,cts,mts,jsx,tsx,json,astro,vue,svelte}")}}]}) }
2025-12-27T13:35:58+03:00 INFO  [lsp] Language server with id 124 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2025-12-27T13:35:58+03:00 INFO  [project::prettier_store] Initialized default prettier with plugins: {"prettier-plugin-astro"}
2025-12-27T13:35:59+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:35:59+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:35:59+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:02+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:02+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:11+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:11+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:11+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:11+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:12+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:12+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:12+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:24+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:24+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:36:24+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:36:24+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:08+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:08+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:08+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:08+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:08+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:08+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:11+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:11+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:11+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:11+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:11+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:11+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:12+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:12+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:12+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:12+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:12+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:12+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:40+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:40+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:40+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:40+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:53+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:53+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:53+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:37:53+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:37:53+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:38:05+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:38:05+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:38:05+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [lsp] failed to deserialize response from language server: invalid type: null, expected a sequence at line 1 column 4. response from language server: "null"
2025-12-27T13:38:05+03:00 WARN  [project::lsp_store] Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:05+03:00 ERROR [project::lsp_store] Error handling response for request GetDocumentColor: Document color via astro-language-server failed: failed to deserialize response
2025-12-27T13:38:25+03:00 INFO  [project::git_store] head branch after scan is Some(Branch { is_head: true, ref_name: "refs/heads/main", upstream: Some(Upstream { ref_name: "refs/remotes/origin/main", tracking: Tracked(UpstreamTrackingStatus { ahead: 0, behind: 0 }) }), most_recent_commit: Some(CommitSummary { sha: "6c068065c4ae38703adbd05e412a1ec1ea6dfafe", subject: "replace images with webp", commit_timestamp: 1766831899, author_name: "zorvi", has_parent: true }) })
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1132] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1139] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:38:33+03:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-27T13:39:29+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-12-27T13:39:29+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:39:29+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-12-27T13:39:34+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:39:38+03:00 ERROR [crashes] thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cosmic-text-0.14.2/src/shape.rs:895:13:
assertion `left == right` failed
  left: true
 right: false...
2025-12-27T13:39:38+03:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-12-27T13:42:38+03:00 INFO  [zed] ========== starting zed version 0.217.3+stable, sha unknown ==========
2025-12-27T13:42:38+03:00 INFO  [crashes] spawning crash handler process
2025-12-27T13:42:38+03:00 WARN  [zed::reliability] Minidump endpoint not set
2025-12-27T13:42:38+03:00 INFO  [extension_host] extensions updated. loading 7, reloading 0, unloading 0
2025-12-27T13:42:38+03:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-12-27T13:42:38+03:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/zor/.local/share/mise/installs/bun/1.3.2/bin:/home/zor/.local/share/mise/installs/node/24.11.1/bin:/home/zor/.local/share/mise/installs/ruby/3.4.7/bin:/home/zor/.cargo/bin:/home/zor/.local/share/mise/installs/zig/0.15.2/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/zor/.spicetify:/home/zor/.spicetify:/home/zor/.spicetify:/home/zor/.local/share/JetBrains/Toolbox/scripts
2025-12-27T13:42:38+03:00 INFO  [client] set status on client 0: Authenticating
2025-12-27T13:42:38+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-12-27T13:42:38+03:00 INFO  [workspace] Rendered first frame
2025-12-27T13:42:38+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:42:38+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-12-27T13:42:38+03:00 INFO  [crashes] connected to crash handler process after 100ms
2025-12-27T13:42:38+03:00 INFO  [crashes] crash handler registered
2025-12-27T13:42:39+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-12-27T13:42:39+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:42:39+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-12-27T13:42:39+03:00 INFO  [node_runtime] using Node.js found on PATH: SystemNodeRuntime { node: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", npm: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/npm", global_node_modules: "/home/zor/.local/share/mise/installs/node/24.11.1/lib/node_modules\n", scratch_dir: "/home/zor/.local/share/zed/node" }
2025-12-27T13:42:39+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["--max-old-space-size=8192", "/home/zor/.local/share/zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2025-12-27T13:42:39+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-12-27T13:42:39+03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon HD 7900 Series (RADV TAHITI)", driver_name: "radv", driver_info: "Mesa 25.3.2-arch1.1" }
2025-12-27T13:42:39+03:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-12-27T13:42:39+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/grid", args: ["--max-old-space-size=8192", "/home/zor/.local/share/zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v24.11.1"
}
2025-12-27T13:42:39+03:00 INFO  [project::prettier_store] Initializing default prettier with plugins {"prettier-plugin-svelte"}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:39+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["/home/zor/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/.config/zed", args: ["/home/zor/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2025-12-27T13:42:40+03:00 INFO  [client] set status on client 480929: Authenticated
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/zed/languages/package-version-server/package-version-server-v0.0.10", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: []
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["/home/zor/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/grid", args: ["/home/zor/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2025-12-27T13:42:40+03:00 INFO  [lsp] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Setting up server…"
}
2025-12-27T13:42:40+03:00 INFO  [lsp] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Listening for messages…"
}
2025-12-27T13:42:40+03:00 INFO  [lsp] Language server with id 10 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Setting up server…"
}
2025-12-27T13:42:40+03:00 INFO  [lsp] Language server with id 10 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Listening for messages…"
}
2025-12-27T13:42:40+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["/home/zor/.local/share/zed/extensions/work/html/node_modules/@zed-industries/vscode-langservers-extracted/bin/vscode-html-language-server", "--stdio"]
2025-12-27T13:42:40+03:00 INFO  [project::prettier_store] Installing default prettier and plugins: [("prettier-plugin-svelte", "3.4.1"), ("prettier", "3.7.4")]
2025-12-27T13:42:41+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["/home/zor/.local/share/zed/extensions/work/svelte/node_modules/svelte-language-server/bin/server.js", "--stdio"]
2025-12-27T13:42:41+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/grid", args: ["/home/zor/.local/share/zed/extensions/work/svelte/node_modules/svelte-language-server/bin/server.js", "--stdio"]
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/portal/src/routes/app/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/api/src/internals.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/portal/src/routes/app/users/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/portal/src/routes/app/app-sidebar.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/api/src/db/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/api/src/auth.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/portal/src/routes/app/users/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/portal/src/routes/app/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 11 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/grid/apps/api/src/db/index.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/signup-form.svelte"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/utils/fetchCleanSVG.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.server.ts"
  }
}
2025-12-27T13:42:41+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/+layout.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/login/+page.server.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.server.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/verify/otp-form.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/components/ui/button/button.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/schema.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.server.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/+layout.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/login/login-form.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/hooks.server.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/+page.server.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/course/%5Blecture%5D/+page.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/lib/napi.ts"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] Language server with id 2 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/zor/Projects/neuroalabs/neuroa-lms-template/src/routes/auth/signup/+page.svelte"
  }
}
2025-12-27T13:42:42+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/neuroa-lms-template", args: ["/home/zor/.local/share/zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2025-12-27T13:42:42+03:00 INFO  [lsp] starting language server process. binary path: "/home/zor/.local/share/mise/installs/node/24.11.1/bin/node", working directory: "/home/zor/Projects/neuroalabs/grid", args: ["/home/zor/.local/share/zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2025-12-27T13:42:42+03:00 INFO  [project::prettier_store] Initialized default prettier with plugins: {"prettier-plugin-svelte"}
2025-12-27T13:42:43+03:00 INFO  [lsp] Language server with id 1 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2025-12-27T13:42:43+03:00 INFO  [lsp] Language server with id 10 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]

```

</details>

### PR DESCRIPTION
**Pull request by cole-miller**
Also improves the commit view to use the same status-based buffer header visual overrides as the project diff as a driveby.

Fixes https://github.com/zed-industries/zed/issues/45735

Release Notes:

- git: Binary files are no longer shown in garbled form when viewing an old commit.

### CODE REVIEW

File: crates/git/src/repository.rs [hunk 1]
```diff
@@ -256,6 +257,13 @@ impl CommitDetails {
     }
 }
 
+/// Detects if content is binary by checking for NUL bytes in the first 8000 bytes.
+/// This matches git's binary detection heuristic.
+pub fn is_binary_content(content: &[u8]) -> bool {
```
Comment (SomeoneToIgnore) [inline crates/git/src/repository.rs:262]: Wanted to mention https://github.com/zed-industries/zed/blob/42af91ddeedd7b41ad8b63b9eb01ea734ab2ff6f/crates/worktree/src/worktree.rs#L6012 as an alternative.

Would be great to unify the code if this bit gets to evolve some day.
