### PR TITLE
terminal_view: Fix focusing of center-pane terminals

### LINKED ISSUE #35908: Task spawned in re-used center terminal doesn't gain focus
### Description
These configuration options for a task don't work as expected when spawning a task in center terminal and re-using tab:
```
"hide": "never",
"reveal_target": "center",
"allow_concurrent_runs": false,
"use_new_terminal": false
```
The tab reveals but don't gain focus – so it's not possible to make a keyboard input (like choosing espflash port to upload, etc.) without manually activating desired center terminal tab.

<details><summary>Screen recording (click to expand)</summary>

https://github.com/user-attachments/assets/522ae518-9c6d-4f82-a4d9-1b20fa01eec5

</details>

Steps to reproduce:
1. Run a task (configured as shown above) from editor (it should open new tab on the top of the active pane, gaining focus - this is expected behaviour).
2. Move the tab to other pane or split current one. 
3. Go back to the editor.
4. Run same task again.

**Expected Behavior**: Spawning task again should bring focus to the re-used tab on the center terminal.

**Actual Behavior**: Focus doesn't change.

Also, I've checked that when the task is confgured to open in terminal panel (not center terminal) it gains focus as expected. The issue exists only for center terminal tasks.

No errors in Zed.log are shown for this.

### Zed Version and System Specs

Zed: v0.198.1 (Zed Preview) 
OS: macOS 15.5.0
Memory: 64 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by the-kenny**
With `reveal_stragegy=always` + `reveal_target=center`, `TerminalPanel::spawn_task` activates & focuses the pane of the task. This works fine in the terminal pane but doesn't for `reveal_target=center`.

Please note: I'm not verified familiar with the architecture and internal APIs of zed. If there's a better way or if this fix is a bad idea, I'm fine with adapting this 😃 

Closes #35908

Release Notes:

- Fixed task focus when re-spawning a task with `reveal_target=center`

### CODE REVIEW

File: crates/tasks_ui/src/tasks_ui.rs [hunk 1]
```diff
@@ -249,6 +249,7 @@ where
                 if tasks.is_empty() { None } else { Some(()) }
             })?
             .is_some();
+
```
Comment (maxdeviant) [inline crates/tasks_ui/src/tasks_ui.rs]:
```suggestion
```

File: crates/terminal_view/src/terminal_panel.rs [hunk 2]
```diff
@@ -905,11 +905,18 @@ impl TerminalPanel {
...
-                                .focus(window);
+                            let did_activate = workspace.activate_item(
+                                &terminal_to_replace,
+                                true,
+                                true,
+                                window,
+                                cx,
+                            );
+
+                            if !did_activate {
```
Comment (SomeoneToIgnore) [inline crates/terminal_view/src/terminal_panel.rs]: Let's use `anyhow::ensure!(did_activate, "...");` form instead.

**Review by SomeoneToIgnore — COMMENTED** [review]
Nice, works for me, thank you for finding a fix.
Let's adjust the style and merge.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!
