### PR TITLE
markdown: Fix rendering of inline HTML <code> tags

### LINKED ISSUE #43166: `<code>` html tags are not parced on LSP markdown hover responses
### Summary

When LSP responds with a markdown that contains `<code>foo</code>`, Zed doesn't parse this and we see the literal `<code>foo<code/>` string instead of a `foo`

### Description

Steps to reproduce:
1. Generate some sample code with docs comments, in Rust:
```rs
/// This is a <code>foo</code> function
fn foo() {
    println!("Hello, World!");
}
```
2. Hover over it
3. See the literal "`<code>foo</code>`" being shown on the LSP popup

**Expected Behavior**: This should be parsed into a code styled string
**Actual Behavior**: This isn't styled

In zed: 

Image

In VsCode:

Image

### Zed Version and System Specs

Zed: v0.215.0 (Zed Nightly 66382acd52905527e38d7d15d04018febc960d53) 
OS: Linux Wayland arch unknown
Memory: 62.2 GiB
Architecture: x86_64
GPU: Intel(R) Arc(tm) Graphics (MTL) || Intel open-source Mesa driver || Mesa 25.2.7-arch1.1

### If applicable, attach your `Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log

```

</details>

### PR DESCRIPTION
**Pull request by artschur**
Added support for rendering HTML `<code> `tags inside Markdown content. Previously, these tags were ignored by the renderer and displayed as raw text (inside LSP hover documentation).

Closes: #43166 

Release Notes:
- Fixed styling of `<code>` HTML tags in Markdown popovers.

Before:
image
After:
image

### CODE REVIEW

**Review by 6639835 — APPROVED** [review]
Nice job

File: crates/markdown/src/markdown.rs [hunk 1]
```diff
@@ -1202,6 +1202,15 @@ impl Element for MarkdownElement {
...
                 MarkdownEvent::InlineHtml => {
+                    let html = &parsed_markdown.source[range.clone()];
+                    if html.eq_ignore_ascii_case("<code>") {
+                        builder.push_text_style(self.style.inline_code.clone());
+                        continue;
+                    }
+                    if html.eq_ignore_ascii_case("</code>") {
+                        builder.pop_text_style();
+                        continue;
+                    }
```
Comment (huacnlee) [inline crates/markdown/src/markdown.rs:1213]: Here at least to use `start_with` and `end_with`, like the above HTML comment check.

**Comment by Angelk90** [comment]
@artschur: You could also adjust the styling, add some space to the sides and round the edges.

| Zed | Github |
|--------|--------|
| Screenshot 2025-11-26 alle 09 46 44 |  <code>html stylish</code> |

File: crates/markdown/src/markdown.rs (hunk 1 above)
Comment (artschur) [reply crates/markdown/src/markdown.rs:1213]: good notice. Fixed that!

**Review by bennetbo — APPROVED** [review]
Thank you!
