### PR TITLE
Only count existing branches in picker search

### LINKED ISSUE #22905: Searching for nonexistent branches indicates a match
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When searching for local branches in the branch picker dropdown, a "create new branch" option is helpfully provided if the search yields no results. However, the picker will indicate that a single match is found, presumably counting this "create new branch" option as a match.

### Zed Version and System Specs

Zed: v0.169.0 (Zed Preview)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

Screenshot 2025-01-09 at 10 53 04

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by AaronFeickert**
When displaying the number of matches in the branch picker during a search, don't count the "create new branch" option as a match, since it only appears when _no_ existing branches are found.

Screenshot 2025-01-09 at 12 17 30

Closes #22905.

Release Notes:

- Fixed result count in branch picker searches.

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
I can't push to this branch, as you haven't enabled the option to allow repository maintainers to push to PRs from a fork: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

Here's a patch with some changes we should make prior to merging:

```
From 92878426a70b4c52020d360633121fc0c39aacd5 Mon Sep 17 00:00:00 2001
From: Marshall Bowers <elliott.codes@gmail.com>
Date: Thu, 9 Jan 2025 13:28:42 -0500
Subject: [PATCH] Simplify

---
 crates/vcs_menu/src/lib.rs | 14 +++-----------
 1 file changed, 3 insertions(+), 11 deletions(-)

diff --git a/crates/vcs_menu/src/lib.rs b/crates/vcs_menu/src/lib.rs
index 0820b01c25..d66628c2d1 100644
--- a/crates/vcs_menu/src/lib.rs
+++ b/crates/vcs_menu/src/lib.rs
@@ -129,9 +129,7 @@ impl BranchListDelegate {
         })
     }

-    /// Get the number of matches that should be included in displayed counts
-    fn displayed_match_count(&self) -> usize {
-        // We only care about existing branches
+    fn branch_count(&self) -> usize {
         self.matches
             .iter()
             .filter(|item| matches!(item, BranchEntry::Branch(_)))
@@ -316,15 +314,9 @@ impl PickerDelegate for BranchListDelegate {
                 .ml_3()
                 .into_any_element()
         } else {
-            // We use the "nominal" match count (which includes the new branch option) to determine if any label should be shown
             let match_label = self.matches.is_empty().not().then(|| {
-                // We use the displayed match count (which excludes the new branch option) to determine the suffix and number
-                let suffix = if self.displayed_match_count() == 1 {
-                    ""
-                } else {
-                    "es"
-                };
-                Label::new(format!("{} match{}", self.displayed_match_count(), suffix))
+                let suffix = if self.branch_count() == 1 { "" } else { "es" };
+                Label::new(format!("{} match{}", self.branch_count(), suffix))
                     .color(Color::Muted)
                     .size(LabelSize::Small)
             });
--
2.46.0
```

**Comment by AaronFeickert** [comment]
@maxdeviant: Sorry about that! You should be able to push changes now.

**Comment by maxdeviant** [comment]
> @maxdeviant: Sorry about that! You should be able to push changes now.

Thank you! And thank you for the fix.

**Review by maxdeviant — APPROVED** [review]

**Comment by AaronFeickert** [comment]
@maxdeviant: Any particular reason not to include explanatory comments?

File: crates/vcs_menu/src/lib.rs [hunk 1]
```diff
@@ -128,6 +128,13 @@ impl BranchListDelegate {
             branch_name_trailoff_after,
         })
     }
+
+    fn branch_count(&self) -> usize {
```
Comment (AaronFeickert) [inline crates/vcs_menu/src/lib.rs:132]: This is much better naming than what I originally used!

**Comment by maxdeviant** [comment]
> @maxdeviant: Any particular reason not to include explanatory comments?

We're generally pretty conservative when it comes to comments. They really need to pull their weight in order to be worth having around (and risk them becoming outdated as the code changes). In this case, I felt that with the renamed `branch_count` method the code was sufficiently self-explanatory (especially when coupled with `git blame`, which would point back to this PR for some added context).
