### PR TITLE
http_client: Support `GITHUB_TOKEN` env to auth GitHub requests

### LINKED ISSUE #33903: Debugger: API rate limiting exceeded
### Summary

Hello 
I am using zed for development in golang but may be this happens also with other programming languages. Often, when I want to launch the debug on my golang code I have the following message
````
error: status error 403, response: "{\"message\":\"API rate limit exceeded for xxxx (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}
````

### Description

Steps to trigger the problem:
1. on the main function, just click on the player 
2.chose `debug: go run <target folder>`

**Expected Behavior**:
the debug session should start
**Actual Behavior**:
I have the following error: 
````
error: status error 403, response: "{\"message\":\"API rate limit exceeded for xxxx (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}
````

Thank you for your help and keep up the good work 

### Zed Version and System Specs

Zed 0.193.3 
98d232261d4248c462da68791708c0d7378e8901

### PR DESCRIPTION
**Pull request by Binlogo**
Closes #33903

Release Notes:

- Ensured Zed reuses `GITHUB_TOKEN` env variable when querying GitHub

---

Before fixing:

-  The `crates-lsp` extension request captured:
```
curl 'https://api.github.com/repos/MathiasPius/crates-lsp/releases' \
-H 'accept: */*' \
-H 'user-agent: Zed/0.212.3 (macos; aarch64)' \
-H 'host: api.github.com' \
```

-  `crates-lsp` extension error: 
```
Language server crates-lsp:

from extension "Crates LSP" version 0.2.0: status error 403, response: "{\"message\":\"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
```

After fixing:

```
export GITHUB_TOKEN=$(gh auth token)
cargo run
```

-  The `crates-lsp` extension request captured:
```
curl 'https://api.github.com/repos/MathiasPius/crates-lsp/releases' \
-H 'authorization: Bearer gho_Nt*****************2KXLw2' \
-H 'accept: */*' \
-H 'user-agent: Zed/0.214.0 (macos; aarch64)' \
-H 'host: api.github.com' \
```

The API rate limitation is resolved.

---

This isn't a perfect solution, but it enables users to avoid the noise.

### CODE REVIEW

**Comment by Binlogo** [comment]
@cla-bot check

**Comment by Binlogo** [comment]
@cla-bot check

File: crates/http_client/src/github.rs [hunk 1]
```diff
@@ -34,12 +37,16 @@ pub async fn latest_github_release(
     pre_release: bool,
     http: Arc<dyn HttpClient>,
 ) -> anyhow::Result<GithubRelease> {
+    let url = format!("{GITHUB_API_URL}/repos/{repo_name_with_owner}/releases");
+
+    let mut request = Request::get(&url).follow_redirects(crate::RedirectPolicy::FollowAll);
```
Comment (tidely) [inline crates/http_client/src/github.rs]: Mostly a style thing, but the `HttpRequestExt` trait provides a builder method called `.when_some`. It could allow building the request a little more compact and gets rid of the `mut` from the request. Something like this

```rust
let request = Request::get(url)
    .follow_redirects(crate::RedirectPolicy::FollowAll)
    .when_some(std::env::var("GITHUB_TOKEN").ok(), |builder, token| {
        builder.header("Authorization", format!("Bearer {}", token))
    })
    .body(Default::default());

let mut response = http.send(request).await.context("error fetching latest release");
```

Can be applied to the other function aswell

Comment (Binlogo) [reply crates/http_client/src/github.rs]: Thank you for the suggestion; it looks better.

**Review by tidely — APPROVED** [review]
Looks good now!

**Comment by Binlogo** [comment]
@tidely Hi, do you have any concerns about this PR? Can we proceed with merging it?

**Comment by tidely** [comment]
Hi! I'm just a frequent contributor and I figured I'd give my suggestion to the PR. I don't actually work at Zed and can't merge it myself. The Zed team will look at it when they find the time.

**Comment by Binlogo** [comment]
Okay, thanks.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks a lot!

**Comment by Binlogo** [comment]
Thanks for merging. This GitHub error with plugins is annoying. Expect the next release soon.
