### PR TITLE
markdown: Restore horizontal scrollbars for codeblocks

### LINKED ISSUE #34224: Code snippet in the chat bar is not scaling responsively.
### Description

Steps to reproduce:
1. Just have a chat in the agent panel and have it generate code there.
2. You can't see the code fully or scroll to read the rest,  because there is no scrollbar underneath.

**Expected Behavior**:  Should either have a scrollbar or span the whole code to fill the given space.
**Actual Behavior**:  Is not responsive, I had to drag the agent panel window to view or copy the code
 and paste it into another file to fully view it.

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: Linux Wayland endeavouros unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 520 (SKL GT2) || Intel open-source Mesa driver || Mesa 25.1.5-arch1.1

### PR DESCRIPTION
**Pull request by xipeng-jin**
### Summary

Restore the agent pane’s code-block horizontal scrollbar for easier scrolling without trackpad and preserve individual scroll state across multiple code blocks.

### Motivation

Addresses https://github.com/zed-industries/zed/issues/34224, where agent responses with wide code snippets couldn’t be scrolled horizontally in the panel. Previously there is no visual effect for scrollbar to let the user move the code snippet and it was not obviously to use trackpad or hold down `shift` while scrolling. This PR will ensure the user being able to only use their mouse to drag the horizontal scrollbar to show the complete line when the code overflow the width of code block.

### Changes

- Support auto-hide horizontal scrollbar for rendering code block in agent panel by adding scrollbar support in markdown.rs
- Add `code_block_scroll_handles` cache in _crates/markdown/src/markdown.rs_ to give each code block a persistent `ScrollHandle`.
- Wrap rendered code blocks with custom horizontal scrollbars that match the vertical scrollbar styling and track hover visibility.
- Retain or clear scroll handles based on whether horizontal overflow is enabled, preventing leaks when the markdown re-renders.

### How to Test

1. Open the agent panel, request code generation, and ensure wide snippets show a horizontal scrollbar on hover.
3. Scroll horizontally, navigate away (e.g., change tabs or trigger a re-render), and confirm the scroll position sticks when returning.
5. Toggle horizontal overflow styling off/on (if applicable) and verify scrollbars appear or disappear appropriately.

### Screenshots / Demos (if UI change)

https://github.com/user-attachments/assets/e23f94d9-8fe3-42f5-8f77-81b1005a14c8

### Notes for Reviewers

- This is my first time contribution for `zed`, sorry for any code patten inconsistency. So please let me know if you have any comments and suggestions to make the code pattern consistent and easy to maintain.
- For now, the horizontal scrollbar is not configurable from the setting and the style is fixed with the same design as the vertical one. I am happy to readjust this setting to fit the needs.
- Please let me know if you think any behaviors or designs need to be changed for the scrollbar.
- All changes live inside _crates/markdown/src/markdown.rs_; no API surface changes.

Closes #34224 

### Release Notes:

- AI: Show horizontal scroll-bars in wide markdown elements

### CODE REVIEW

**Comment by xipeng-jin** [comment]
@cla-bot check

File: crates/markdown/src/markdown.rs [hunk 1]
```diff
@@ -884,33 +938,53 @@ impl Element for MarkdownElement {
...
                                         kind,
-                                        parsed_markdown,
+                                        &parsed_markdown,
                                         range.clone(),
                                         metadata.clone(),
                                         window,
                                         cx,
                                     );
 
+                                    let mut parent_container: AnyDiv = if let Some(scroll_handle) =
```
Comment (xipeng-jin) [inline crates/markdown/src/markdown.rs:948]: I am not sure this is the desire way to give the default horizontal scrollbar option with `CodeBlockRenderer::Custom` type. This will add the scrollbar on top of the `parent_container` on default, so the following transform function might not work as previous design. I am happy to hear any opinions on this. Thanks

**Comment by ConradIrwin** [comment]
Thanks for this!

Looks like we can/should get rid of the Custom markdown code block renderer, but that can be a separate PR.

**Comment by xipeng-jin** [comment]
Thank you very much for helping me fix the CI tests issue and merged this PR. As @ConradIrwin mentioned, we can probably get rid of the `CodeBlockRenderer::Custom` option since there is no usage of it. I will create a separate PR to follow up on this. Thanks again.
