### PR TITLE
Fix F10 and Alt+F handling on Windows

### LINKED ISSUE #17819: Keybind to open context menu at text cursor?
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can right click the text area to show a context menu.
However, when I press the menu key on my keyboard (or Shift+F10 on a compact keyboard, I tried both), nothing happens and the context menu does not show in zed.
I think the menu key should work the same way as in Firefox, where it opens a context menu at the text cursor or on the focused object.

### Environment

Zed: v0.154.0 (Zed Dev fac9ee5f861b501b4ca79ab04d410eeb49d9ec5e)
OS: Windows 10.0.22631
Memory: 13.8 GiB
Architecture: x86_64
GPU: AMD Radeon 780M Graphics || AMD proprietary driver || 24.2.1 (LLPC)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

(a: start) image
(b: action) press menu key on keyboard
(c.1 actual result) image
(c.2 desired result) image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

none of the actions I mentioned in this bug report produce any output on the log.
</pre></details>

### LINKED ISSUE #24744: F10 and few other combinations is not properly handled on Windows
### Summary

1. F10 is not handled correctly, this might be the reason, why it's not working in #17819
2. Alt+Fn are not handled correctly (although combinations like Ctrl+Alt+Fn should be fine)

The way I've found it, is following:
1. Inside built-in terminal I've fired `event-read` example from [crossterm](https://github.com/crossterm-rs/crossterm)
2. Then I've pressed in order: F8, F9, F10,  Ctrl+F8, Ctrl+F9, Ctrl+F10,  Alt+F8, Alt+F9, Alt+F10

Actual Behavior:
```
crossterm> cargo run --example event-read
Blocking read()
 - Keyboard, mouse, focus and terminal resize events enabled
 - Hit "c" to print current cursor position
 - Use Esc to quit

Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(0x0), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(0x0), kind: Release, state: KeyEventState(0x0) })
(F10 output completely missing)
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(CONTROL), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(CONTROL), kind: Release, state: KeyEventState(0x0) })
(Ctrl + F10 output completely missing)
(Alt + F8, Alt + F9, Alt + F10 completely missing)
```

Expected Behavior:
```
crossterm> cargo run --example event-read
Blocking read()
 - Keyboard, mouse, focus and terminal resize events enabled
 - Hit "c" to print current cursor position
 - Use Esc to quit

Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(0x0), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(0x0), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(0x0), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(0x0), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(CONTROL), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(CONTROL), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(CONTROL), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(ALT), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(8), modifiers: KeyModifiers(ALT), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(ALT), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(9), modifiers: KeyModifiers(ALT), kind: Release, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(ALT), kind: Press, state: KeyEventState(0x0) })
Event: Key(KeyEvent { code: F(10), modifiers: KeyModifiers(ALT), kind: Release, state: KeyEventState(0x0) })
```

### Zed Version and System Specs

Zed: v0.172.0 (Zed Dev 2f7499fbfc1067bd8860050d57e8c6bf08dcfc33) 
OS: Windows 10.0.22631
Memory: 127.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3070 || NVIDIA || 560.94

### PR DESCRIPTION
**Pull request by gim913**
Closes #24744
and should also fix #17819 

The change is split into two commits, first one adds F10 handling (it needs to be handled inside `parse_syskeydown_msg_keystroke`, the second one properly handles `Alt+Fn` combinations, this also needs to happen in `parse_syskeydown_msg_keystroke` and is similar to a fragment inside `parse_keydown_msg_keystroke`

Release Notes:

- Fixes F10 and Alt+Fn handling on windows

### CODE REVIEW

**Comment by gim913** [comment]
@cla-bot check

File: crates/gpui/src/platform/windows/events.rs [hunk 1]
```diff
@@ -1265,6 +1290,7 @@ fn parse_keydown_msg_keystroke(wparam: WPARAM) -> Option<KeystrokeOrModifier> {
         VK_INSERT => "insert",
         VK_DELETE => "delete",
         _ => {
+            let vk_code = wparam.loword();
```
Comment (mgsloan) [inline crates/gpui/src/platform/windows/events.rs:1293]: Is this needed?

**Comment by mgsloan** [comment]
This looks good to me, thank you!  Not merging as I can't try it out (no windows machine).  So makes sense to have @JunkuiZhang take a look

File: crates/gpui/src/platform/windows/events.rs (hunk 1 above)
Comment (gim913) [reply crates/gpui/src/platform/windows/events.rs]: forgot to drop it

**Comment by JunkuiZhang** [comment]
Thank you very much! LGTM. I feel like this part of the code may need some refactoring, but that’s probably something for a separate PR.
