### PR TITLE
vim: Fix space forward bug with non-ASCII characters at EOL

### LINKED ISSUE #27619: vim: `space` doesn't move to next line on non-ASCII characters
### Summary

Continues issue https://github.com/zed-industries/zed/issues/26806 (solved by https://github.com/zed-industries/zed/pull/27053).

If a line ends with a non-ASCII symbol, the `vim::Space` motion can’t move past it.

### Zed Version and System Specs

Zed: v0.179.2 (Zed) 
OS: Linux Wayland arch unknown
Memory: 13.3 GiB
Architecture: x86_64
GPU: AMD Radeon 680M (RADV REMBRANDT) || radv || Mesa 25.0.2-arch1.2

### PR DESCRIPTION
**Pull request by mastion**
Closes https://github.com/zed-industries/zed/issues/27619

Fixes issue with right wrapped movement when a multi-byte character is at the end of the line. This is done by grabbing the last character on the current row and using that characters size to calculate the `max_column` variable, which is used to decide if the next right movement should move down the line or not.

We did notice a bit of code that could be an issue that we wanted to call out. [Here](https://github.com/zed-industries/zed/blob/main/crates/editor/src/display_map.rs#L1070) inside of `clip_at_line_end` it also does a saturating_sub(1), assuming a single byte character. We didn't run into any issues due to this line but felt like a similar bug. We can apply a similar fix if wanted, but wanted to pose the question first.

Test case: Moving to next line when eol is a multi-byte character

https://github.com/user-attachments/assets/1021ab1f-f49d-4986-8f9a-8cfc7e5c91bc

Release Notes:

- vim: Fixed `space` on a multibyte characters at end of line

### CODE REVIEW

File: crates/vim/src/motion.rs [hunk 1]
```diff
@@ -1274,7 +1274,16 @@ fn wrapping_right(map: &DisplaySnapshot, mut point: DisplayPoint, times: usize)
...
+    let eol_point = map.clip_point(
+        DisplayPoint::new(point.row(), map.line_len(point.row())),
+        Bias::Left,
+    );
+    let mut eol_chars = map.buffer_chars_at(eol_point.to_offset(map, Bias::Left));
+    let eol_char_len = match eol_chars.next() {
+        Some((ch, _)) => ch.len_utf8() as u32,
+        None => 1,
+    };
+    let max_column = map.line_len(point.row()).saturating_sub(eol_char_len);
```
Comment (ConradIrwin) [inline crates/vim/src/motion.rs:1286]: @mastion Thanks! I think this could probably be done without reading the buffer text

Does it work to move the point forward and clip it unconditionally. We know that in the case that +1 clip::right returns ourselves, we're at the end of the line: 
```
let next_point = point;
  *next_point.column_mut() += 1;
    next_point = map.clip_point(next_point, Bias::Right);
if next_point == point {
  if next_point.row == map.max_point() {
    return next_point
  } else {
     return Point::new(next_point.row + 1, 0)
  }     
}
```

If not, we can use your technique; but I think `max_column` is just `eol_point.column` (or maybe `movement::left(eol_point).column`?)

**Comment by ConradIrwin** [comment]
Nice, thanks!
