### PR TITLE
Handle soft wrap modes when computing wrap width

### LINKED ISSUE #44748: Git commit hard and soft wrap not respected
### Reproduction steps

There are two closely related issues here regarding hard and soft wrapping in the editor and the git panel that do not behave [as documented](https://zed.dev/docs/git#configuration)

### preferred_line_length not respected in the editor

When using the editor to edit a commit message, the text soft wraps at the correct number of characters, but once I save the commit and check my git log, I can see that it did not hard wrap at that character count. The docs state
> You can configure how Zed hard wraps commit messages with the preferred-line-length setting of the "Git Commit" language. The default is 72

##### Reproduction

- Make a change to a file and `run git commit -a` in your terminal. Zed opens with the ability to edit the commit message
- Type more that 72 characters. Zed correctly soft wraps at 72 characters
- Save and exit and run `git log` in your terminal and you'll see that the commit message is not hard wrapped at 72 chars. 

### soft_wrap not respected in the git panel

The docs state
> The Git Panel also allows configuring the soft_wrap setting to adjust how commit messages display while you are typing them in the Git Panel. The default setting is editor_width, however, none, preferred_line_length, and bounded are also options.

But when set to `preferred_line_length`, it still wraps to `editor_width`

##### Reproduction

- Make a change to a file and open the git panel
- Make the panel very wider (wider than 72 chars)
- Type a commit message in the panel that's longer than 72 chars. It does not soft wrap at 72 chars. 

### Editor soft wraps correctly at 72 chars:

Image

### Actual commit message is not hard wrapped:

Image

### Sidebar Panel editor does not soft wrap:

Image

### But commit is correctly hard wrapped

Image

### Floating panel correctly soft wraps

Image

### Zed version and system specs

Zed: v0.211.6 (Zed) 
OS: macOS 15.7.2
Memory: 64 GiB
Architecture: aarch64

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
  "languages": {
    "Git Commit": {
      "soft_wrap": "preferred_line_length",
      "preferred_line_length": 72
    },
    ...
  }

```

</details>

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by mchisolm0**
Partially closes #44748 

Release Notes:

- git: Fixed the git panel commit editor not respecting soft wrap settings

### CODE REVIEW

**Comment by mchisolm0** [comment]
I believe this is almost identical to the logic in `prepaint`. Would it be worth pulling out the logic in case soft wrap options change? [link to prepaint version of the logic](https://github.com/mchisolm0/zed/blob/5c49186ca0cbd1c6425319fba6f1d2f67e8427a7/crates/editor/src/element.rs#L9332-L9342)

Also, I believe the areas this change could impact already override soft wrap behavior. For example, the AutoHeight Editors I saw for the agent UI seem to use MessageEditor [link to soft wrap override](https://github.com/mchisolm0/zed/blob/5c49186ca0cbd1c6425319fba6f1d2f67e8427a7/crates/agent_ui/src/acp/message_editor.rs#L129-L130).

I have tested the prompt message editor and the inline message editor to make sure even with the below settings, the text still wraps to the editor width.
```json
{
  "soft_wrap": "preferred_line_length",
  "preferred_line_length": 72,
}
```

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -11748,6 +11743,23 @@ pub fn register_action<T: Action>(
...
+fn calculate_wrap_width(
+    soft_wrap: SoftWrap,
+    editor_width: Pixels,
+    em_width: Pixels,
+) -> Option<Pixels> {
+    let wrap_width_for = |column: u32| (column as f32 * em_width).ceil();
+
+    match soft_wrap {
+        SoftWrap::GitDiff => None,
+        SoftWrap::None => Some(wrap_width_for(MAX_LINE_LEN as u32 / 2)),
```
Comment (mchisolm0) [inline crates/editor/src/element.rs:12090]: I overlooked handling `SoftWrap::None` initially in the first commit.

The goal is to have the the git panel commit message editor, the main editor, and any other `AutoHeight` editors match soft wrap behavior, right?

**Comment by mchisolm0** [comment]
Hi @cole-miller thanks! 😁 I have tested the change with each soft wrap setting in multiple places I expected it to affect.

Is it expected behavior that this change would impact anything in the agent thread view?

I thought my previous testing showed it did not. This time I noticed on Nightly with opencode ACP, a code block in the agent thread seemed to be soft wrapping to my preferred line length but the dev build did not. I think it is unrelated and I can not reproduce it. I just wanted to mention it and ask.
