### PR TITLE
Don't suggest assistant code actions if it's disabled

### LINKED ISSUE #19155: Fix with assistant should not be shown when assistant is disabled
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Disable assistant:
```json
"assistant": {
  "enabled": false,
  "version": "2"
},
```
Write code with an error:
```python
print("Hello, world"
```

Press `Cmd+.`. `Fix with assistant` shows, but pressing it does nothing

### Environment

Zed: v0.158.0 (Zed Nightly c85a3cc117db760586c2f830e9e8b8a7a7f03a48)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by rtfeldman**
Closes #19155

Release Notes:

- Fixed code action for "Fix with assistant" appearing when assistant was disabled.

### CODE REVIEW

File: crates/assistant/src/inline_assistant.rs [hunk 1]
```diff
@@ -3277,6 +3277,11 @@ impl CodeActionProvider for AssistantCodeActionProvider {
         range: Range<text::Anchor>,
         cx: &mut WindowContext,
     ) -> Task<Result<Vec<CodeAction>>> {
+        // Don't suggest assistant code actions if the assistant is disabled in settings.
```
Comment (maxdeviant) [inline crates/assistant/src/inline_assistant.rs:3280]: Can we nix this comment? It seems to be repeating what the code is doing below it.
