### PR TITLE
windows: Fix ssh reporting wrong password even it's actually correct

### LINKED ISSUE #34393: Windows SSH: Password works only on the third attempt
### Summary

Zed is only able to login after the third password prompt when using SSH from Windows to Linux

### Description

With the latest nightly release, zed seems to have issues connecting the ssh remote from Windows to Linux. When I input the password in the prompt it consistently works only at the third attempt, all others fail like I typed the wrong password. With previous builds (mainly the windows SSH PR built from source) I needed 6 attempts (3->retry->3 more), so it has somehow gotten better.

I must say, once I am able to login, it works flawlessly.

Steps to reproduce:
1. Try to remote to a Linux host from Windows
2. Type the password and press enter
3. It will only work on the 3rd attempt

**Expected Behavior**: Zed is able to login after I type my password correctly
**Actual Behavior**: I need to type it 3 consecutive times.

### Zed Version and System Specs

Zed: v0.196.0 (Zed Nightly 51df8a17ef32196acac6e3125c0f2d6297300e63) 
OS: Windows 10.0.26100
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #34393

Currently, we’re using `zed.exe --askpass` kind of like an `nc` substitute, it prints out the SSH password to stdout with something like `println!("user-pwd")`. `ssh.exe` then reads the password from stdout so it can establish the connection.

The problem is that in release builds we set `subsystem=windows` to avoid Windows spawning a black console window by default. The side effect is that `zed.exe` no longer has a stdout, so `ssh.exe` can’t read the password.

Through testing, I confirmed that neither allocating a new console for `zed.exe` nor attaching it to the parent process’s stdout resolves the issue. As a result, this PR updates the implementation to use `cli.exe --askpass` instead.

TODO:

- [ ] Check that the `cli` path is correct on macOS
- [ ] Check that the `cli` path is correct on Linux

Release Notes:

- N/A

### CODE REVIEW

**Comment by osiewicz** [comment]
@JunkuiZhang  Just wanted to let you know that thanks to this patch I can successfully SSH into my Mac on a LAN (whereas I can't do that on main), good job 👍 
/cc @maxbrunsfeld

File: crates/util/src/util.rs [hunk 1]
```diff
@@ -306,6 +304,102 @@ pub fn get_shell_safe_zed_path() -> anyhow::Result<String> {
...
+                parent
+                    .join(p)
+                    .canonicalize()
+                    .ok()
+                    .filter(|path| path != &zed_path)
+            })
+            .with_context(|| format!("could not find any of: {}", possible_locations.join(", ")))?
+            .to_string_lossy()
+            .to_string()
+    };
```
Comment (osiewicz) [inline crates/util/src/util.rs]: Tbh this code could be simplified by just doing `if cfg!(target_os = ...) else ...` since none of the branches use any custom dependencies.

Comment (JunkuiZhang) [reply crates/util/src/util.rs]: Does `if cfg!(windows) else ...` just turn into `if true else ...` on Windows? If so, that still hits branch prediction I think? Personally, I prefer using `#[cfg(windows)]` since it’s compile-time only. Not totally sure if I’ve got that right though.

Comment (osiewicz) [reply crates/util/src/util.rs]: Yes, `cfg!(windows)` will turn into `true` or `false`, but any decent compiler should optimize that away. Besides, this function shouldn't be perf sensitive anyways.

I see where you're coming from with `#[cfg(..)]` preference, but I do believe it would make it significantly easier to read if we went with a macro instead.

Comment (JunkuiZhang) [reply crates/util/src/util.rs]: That makes a lot of sense, thank you!

**Comment by JunkuiZhang** [comment]
In this [commit ](https://github.com/zed-industries/zed/pull/38263/commits/474b567465b2adc2c9c230fe75719e5c34fbd106), I simplified the macOS handling. I noticed that in both development builds and the app bundle, `zed-cli` and `zed` live in the same folder. And we don’t need any plist info here, so there’s no need to use the `locate_bundle` function.

File: crates/util/src/util.rs [hunk 2]
```diff
@@ -306,6 +304,57 @@ pub fn get_shell_safe_zed_path() -> anyhow::Result<String> {
...
+    let zed_cli_path = possible_locations
+        .iter()
+        .find_map(|p| {
+            parent
+                .join(p)
+                .canonicalize()
+                .ok()
+                .filter(|p| p != &zed_path)
+        })
+        .context(format!(
```
Comment (osiewicz) [inline crates/util/src/util.rs]:
```suggestion
        .with_context(|| format!(
```
`.context` is eager whereas `with_context` is not.

File: crates/util/src/util.rs [hunk 3]
```diff
@@ -306,6 +304,59 @@ pub fn get_shell_safe_zed_path() -> anyhow::Result<String> {
     Ok(zed_path_escaped.to_string())
 }
 
+/// Returns a shell escaped path for the zed cli executable, this function
+/// should be called from the zed executable, not zed-cli.
+pub fn get_shell_safe_zed_cli_path() -> Result<String> {
+    let zed_path =
+        std::env::current_exe().context("Failed to determine current zed executable path.")?;
```
Comment (maxbrunsfeld) [inline crates/util/src/util.rs:312]: The function above, `get_shell_safe_zed_path` has to trim off the string ` (deleted)` from the output of `current_exe()`. Should we be doing that here also?

Comment (JunkuiZhang) [reply crates/util/src/util.rs:312]: The reason `get_shell_safe_zed_path` trims off `(deleted)` is because after an update we need to use the latest binary. But in `get_shell_safe_zed_cli_path`, first we get the zed binary path, this path may have a `(deleted)` suffix, we just take its parent directory and look for the `zed-cli` there. So no extra trim step is needed.

- Find zed path: `/path/to/zed (deleted)`
- Find its parent: `/path/to/`
- Find zed cli: `/path/to/zed-cli`

**Comment by osiewicz** [comment]
Connecting to Linux box with a password fails for me with:
> 2025-09-29T17:03:37+02:00 ERROR [workspace::notifications] failed to connect: Connection closed by 46.101.206.69 port 22

**Review by osiewicz — APPROVED** [review]

**Comment by ConradIrwin** [comment]
I ran into a problem locally because it couldn't find the cli path when I was running a dev build (fixed by `cargo build -p cli`), but I think this will also cause problems for linux packagers who ship the CLI as `zed-editor` to avoid conflict with the `zed` binary shipped by the ZFS project.

Is it possible to make this change only on windows? Or solve it a different way that doesn't require being able to find the CLI?

**Comment by maxbrunsfeld** [comment]
We could move `--askpass` to the CLI for windows only. But if possible, it'd be nice for it to work the same way on all platforms. Is it not possible for us to reliably find the CLI on Linux systems?

**Comment by maxbrunsfeld** [comment]
We could also fall back on using `nc(1)` in dev mode, since it is usually available.

**Comment by ConradIrwin** [comment]
I don't think it's possible on Linux unless people use our linux install script 

For example Arch does this:  https://archlinux.org/packages/extra/x86_64/zed/

Screenshot 2025-09-30 at 15 47 45

So, we could hard code that, but Nix does this: https://search.nixos.org/packages?channel=25.05&show=zed-editor&query=zed-editor

Screenshot 2025-09-30 at 15 48 52

And we could hard-code that, but...

It doesn't seem like the end of the world to have both the CLI and the main binary support `--askpass` though (a small amount of extra code size). Or we could make it so it's only cli on Windows and only main binary on macOS 

It would be really nice if we could just use `nc` but depending on your distribution it may not support unix domain sockets.

**Comment by maxbrunsfeld** [comment]
@osiewicz or @JunkuiZhang - Can you do the follow-up here? I'm ok with having `--askpass` in both the editor and the CLI, or making it depend on the platform. On macOS, either one would work, since we *can* get the path to the CLI reliably. On Windows, it needs to be the CLI, obviously, and on Linux, I guess it is most straightforward to put it back in the editor.

**Comment by osiewicz** [comment]
We could also expose another knob for packaging Zed; we already have `ZED_UPDATE_EXPLANATION`, so `ZED_CLI_FILENAME` doesn't seem too far-fetched IMHO.

**Comment by maxbrunsfeld** [comment]
That works too; we'd just need to communicate that to the Arch package maintainer.

**Comment by JunkuiZhang** [comment]
I’m fine with either solution, but on Linux using `zed --askpass` instead of `cli --askpass` seems like the simpler option.
