### PR TITLE
linux: Show warning if file picker portal is missing

### LINKED ISSUE #9209: linux: Open a Project and CTRL + O not functional
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After building on NixOS Wayland and running everything works with no issues (currently) except that I cannot use CTRL + O or the button to Open a Project. Nothing happens when I do so and there are no error or console logs.

### Environment

Zed: v1.0.0 (Zed Dev)
OS: NixOS (24.05)
Memory: 31.2 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### LINKED ISSUE #11089: Cannot open new project from Zed
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I run "workspace: open" (Ctrl + O) nothing happens. The only way I found to open a project is to cd into it and launch Zed from the terminal.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

I looked at the log but there is no entry related to this, when I do "workspace: open" nothing pops up in the log.

### LINKED ISSUE #13753: [Linux] File manager won't show up.
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hello! Love this IDE and recently started using Debian Linux on X11 with the DWM window manager. I can only open files directly through the command line. When I use Control+O, or any other way to open files/folders, my file manager will not show up.

### Environment

Zed: v0.142.3 (Zed Preview)
OS: Linux X11 debian 12
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### LINKED ISSUE #13766: cannot open project on linux
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

after opening zed, I am trying to open a project with ctrl + o or with the bottom in the top left corner. both do nothing. 

### Environment

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### LINKED ISSUE #14353: [File explorer] [Linux] Can't open thunar in hyprland
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I can't open the file explorer, i have thunar and hyprland, i have to install a precise file explorer ?

### Environment

Archlinux, Hyprland, AMD 7840u, Thunar.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

When i click open folder is not work 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### LINKED ISSUE #14384: Open a project in Wayland is not working
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hi,

I am trying zed to see if it can replace Vs Code and Neovim but cannot get folder picker to open but I am assuming its a dbus error in wayland but perhaps people will know.

### Environment

Zed: v0.144.2 (Zed)
Kernal: Linux 6.9.7-arch1-1
OS: Arch Linux x86_64
WM: Hyprland (Wayland)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16201171/Zed.log)

</pre></details>

### PR DESCRIPTION
**Pull request by apricotbucket28**
This PR adds a warning when the file chooser couldn't be opened on Linux

It's quite confusing when trying to open a file and apparently nothing happens: 

- fixes https://github.com/zed-industries/zed/issues/11089
- fixes https://github.com/zed-industries/zed/issues/14328
- fixes https://github.com/zed-industries/zed/issues/13753#issuecomment-2225812703
- fixes https://github.com/zed-industries/zed/issues/13766
- fixes https://github.com/zed-industries/zed/issues/14384
- fixes https://github.com/zed-industries/zed/issues/14353
- fixes https://github.com/zed-industries/zed/issues/9209

image

Release Notes:

- N/A

### CODE REVIEW

File: crates/workspace/src/workspace.rs [hunk 1]
```diff
@@ -305,13 +305,31 @@ pub fn init(app_state: Arc<AppState>, cx: &mut AppContext) {
 
             if let Some(app_state) = app_state.upgrade() {
```
Comment (apricotbucket28) [inline crates/workspace/src/workspace.rs:306]: By the way, I'd like to know if this [action handler](https://github.com/zed-industries/zed/blob/09e7b481b8bed10deaca023d5ede81d738c102a9/crates/workspace/src/workspace.rs#L299) is dead code? I never saw it get called in my testing since there's already [a listener](https://github.com/zed-industries/zed/blob/f67e87057e4872353007be93fd238f68eecdf9e3/crates/workspace/src/workspace.rs#L1601) which is set in the root view of the workspace.

Comment (mikayla-maki) [reply crates/workspace/src/workspace.rs:306]: It’s the backup for when no windows are open, which I think is only possible on macOS.

File: crates/gpui/src/platform/linux/platform.rs [hunk 2]
```diff
@@ -282,23 +285,23 @@ impl<P: LinuxClient + 'static> Platform for P {
...
+                    .map(|request| {
+                        request.response().ok().and_then(|response| {
+                            response
+                                .uris()
+                                .iter()
+                                .map(|uri| uri.to_file_path().ok())
+                                .collect()
+                        })
+                    })
+                    .map_err(|_| anyhow!(FILE_PICKER_PORTAL_MISSING));
```
Comment (bilelmoussaoui) [inline crates/gpui/src/platform/linux/platform.rs:297]: This is actually not correct, we would need https://github.com/bilelmoussaoui/ashpd/issues/209 first. As with your current approach, cancelling the dialog by the user (closing it) would show the same error message as well

Comment (bilelmoussaoui) [reply crates/gpui/src/platform/linux/platform.rs:297]: Made a new release that covers this & a backport of your last patch, thanks!

Comment (apricotbucket28) [reply crates/gpui/src/platform/linux/platform.rs]: Thanks a lot! I didn't notice originally since I had also coded other part of the logic incorrectly and the cancellation error didn't show up, it should be fixed now.
