### PR TITLE
Fix macros on x11 sometimes resulting in incorrect input

### LINKED ISSUE #40678: Shift key ignored in keyboard macros
### Summary

On a keyboard with macros, keypresses that are surrounded with emulated shift key are treated as if the shift key was not engaged.

### Description

I have a ZMK-based keyboard which I've been using for about 2 years. One of the layers will send symbols by quickly sending `shift on -> keypress -> shift off`. I've never seen this fail in other settings than in Zed; but on Zed the keypress is instead interpreted as the digit the symbol is on instead (most frustratingly, I get `9` instead of `(`, and `[` instead of `{`).

Steps to reproduce:
1. Use a ZMK-based keyboard
2. Configure it to use `&kp LEFT_PARENTHESIS`
3. ???
4. Find `9` in the buffer instead of the expected `(`

**Expected Behavior**:
**Actual Behavior**:

I suspect this is caused by the keypresses sent by ZMK being to close to each other in time, but it might be something else entirely.

Thanks for all your work :)

### Zed Version and System Specs

Zed: v0.208.5 (Zed) 
OS: Linux X11 ubuntu 24.04
Memory: 62 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XTX (RADV NAVI31) || radv || Mesa 25.0.7-0ubuntu0.24.04.1

### PR DESCRIPTION
**Pull request by AndreRoelofs**
Closes #40678

The python file below simulates the macros at various timings and can be run by running:
1. `sudo python3 -m pip install evdev --break-system-packages`
2. `sudo python3 zed_shift_brace_replayer.py`

Checked timings for hold=0.1, =0.01 and =0.001 with the latter two no longer causing incorrect inputs. 

[zed_shift_brace_replayer.py](https://github.com/user-attachments/files/23560570/zed_shift_brace_replayer.py)

Release Notes:

- linux: fixed a race condition where the macros containing modifier + key would sometimes be processed without the modifier

### CODE REVIEW

**Comment by AndreRoelofs** [comment]
Created a new PR with the experimental changes as discussed with @probably-neb

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 1]
```diff
@@ -5,6 +5,7 @@ use calloop::{
     EventLoop, LoopHandle, RegistrationToken,
     generic::{FdWrapper, Generic},
 };
+
```
Comment (aqrln) [inline crates/gpui/src/platform/linux/x11/client.rs]: Unintentional change?

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 2]
```diff
@@ -1018,6 +1019,25 @@ impl X11Client {
...
+                let locked_layout = state.xkb.serialize_layout(xkbc::STATE_LAYOUT_LOCKED);
+                state.xkb.update_mask(
+                    depressed_mods,
+                    latched_mods,
+                    locked_mods,
+                    0,
+                    0,
+                    locked_layout,
+                );
+
```
Comment (aqrln) [inline crates/gpui/src/platform/linux/x11/client.rs:1026]: This code looks duplicated and should be extracted (e.g. as a method in `X11ClientState`)

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 3]
```diff
@@ -1083,6 +1103,24 @@ impl X11Client {
...
+                // the modifiers missing from the event.
+                // We therefore update the mask from the global state.
+                let locked_mods_mask = (ModMask::LOCK | ModMask::M2).bits() as u32;
+                let event_state_bits = u32::from(event.state.bits());
+                let depressed_mods = event_state_bits & !locked_mods_mask;
+                let latched_mods = state.xkb.serialize_mods(xkbc::STATE_MODS_LATCHED);
+                let locked_mods = state.xkb.serialize_mods(xkbc::STATE_MODS_LOCKED);
+                let locked_layout = state.xkb.serialize_layout(xkbc::STATE_LAYOUT_LOCKED);
+                state.xkb.update_mask(
+                    depressed_mods,
```
Comment (aqrln) [inline crates/gpui/src/platform/linux/x11/client.rs]: This could be simplified

```suggestion
                let depressed_mods = event.state.remove(ModMask::LOCK).remove(ModMask::M2);
                let latched_mods = state.xkb.serialize_mods(xkbc::STATE_MODS_LATCHED);
                let locked_mods = state.xkb.serialize_mods(xkbc::STATE_MODS_LOCKED);
                let locked_layout = state.xkb.serialize_layout(xkbc::STATE_LAYOUT_LOCKED);
                state.xkb.update_mask(
                    depressed_mods.into(),
```

Even without using the `remove` method, converting u16 to u32 until we pass it to `update_mask` later and converting `event.state` to bits isn't necessary, it would've been sufficient to do
```rust
                let locked_mods_mask = ModMask::LOCK | ModMask::M2;
                let depressed_mods = event.state & !locked_mods_mask.bits();
```

**Comment by aqrln** [comment]
(disclaimer that I'm not from Zed team and know nothing about the code, just randomly opened the PR, I can't help with any follow up questions 😄)

**Comment by AndreRoelofs** [comment]
Thanks a lot @aqrln. I made the fixes.

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 1 above)
Comment (AndreRoelofs) [reply crates/gpui/src/platform/linux/x11/client.rs]: I was testing the input on that line haha good catch.

**Comment by AndreRoelofs** [comment]
I've been using this for almost 2 weeks now. I haven't run into a single issue. I used mostly ZMK and a little bit of regular. Everything works perfectly.

Is there anything I can do to help merge it?

**Comment by probably-neb** [comment]
Tests seem to be flaking. Will merge once they pass.

Thanks for the great work @AndreRoelofs!
