### PR TITLE
macOS: Enumerate GPUs first; prefer low-power non-removable; fall back to system default

### LINKED ISSUE #37689: zed 0.202.7 crash on start up on macbook m1
### Summary

zed 0.202.7 crash on start up on macbook m1

### Description

Steps to trigger the problem:
1. download latest zed for apple silicon 
2. run with right click - open

Actual Behavior: not running, see following logs in console app
Expected Behavior: app running

### Zed Version and System Specs

zed cannot run, Graphics/Display info
```
Apple M1:

  Chipset Model:	Apple M1
  Type:	GPU
  Bus:	Built-In
  Total Number of Cores:	8
  Vendor:	Apple (0x106b)
  Metal:	Supported
  Displays:
DELL U2723QE:
  Resolution:	3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
  UI Looks like:	1920 x 1080 @ 60.00Hz
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log
2025-09-06T17:44:15+08:00 INFO  [zed] ========== starting zed version 0.202.7, sha cd9b0b5 ==========
2025-09-06T17:44:15+08:00 INFO  [crashes] spawning crash handler process
2025-09-06T17:44:15+08:00 INFO  [zed] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2025-09-06T17:44:15+08:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-06T17:44:15+08:00 INFO  [crashes] crash handler registered
2025-09-06T17:44:15+08:00 INFO  [extension_host] extensions updated. loading 1, reloading 0, unloading 0
2025-09-06T17:44:15+08:00 ERROR [gpui::platform::mac::metal_renderer] unable to access a compatible graphics device
```

</details>

### PR DESCRIPTION
**Pull request by cacaosteve**
Problem: Some macOS environments report no devices via MTLCopyAllDevices, causing startup failure with “unable to access a compatible graphics device,” especially on Apple Silicon.
Change: Prefer MTLCreateSystemDefaultDevice (metal::Device::system_default()) first. If None, enumerate devices and select a non‑removable, low‑power device by preference.
Why this works: On Apple Silicon the system default is the unified GPU; on Intel, the fallback keeps a stable policy and avoids accidentally picking removable/high‑power devices.
Impact: Fixes startup on affected ASi systems; improves selection consistency on Intel multi‑GPU. Behavior unchanged where system_default() succeeds.
Risk: Low. Aligns with Apple’s recommended selection path. Still fails early with a clearer message if no Metal devices exist.

Closes #37689.

Release Notes:
- Fixed: Startup failure on some Apple Silicon machines when Metal device enumeration returned no devices by falling back to the system default device.

### CODE REVIEW

**Comment by cacaosteve** [comment]
recheck

File: crates/gpui/src/platform/mac/metal_renderer.rs [hunk 1]
```diff
@@ -132,11 +132,18 @@ impl MetalRenderer {
...
+        let device = if let Some(device) = metal::Device::system_default() {
+            device
+        } else {
+            let mut devices = metal::Device::all();
+            if devices.is_empty() {
+                log::error!("unable to access a compatible graphics device (no Metal devices found)");
+                std::process::exit(1);
+            }
+            // When multiple devices exist (e.g., Intel iGPU + dGPU or eGPU), prefer low-power, non-removable.
+            devices.sort_by_key(|d| (d.is_removable(), !d.is_low_power()));
```
Comment (filipwiech) [inline crates/gpui/src/platform/mac/metal_renderer.rs]: The original code sorted by `(is_removable(), is_low_power())`, while this new one sorts by `(is_removable(), !is_low_power())`: was there a bug before? :thinking:

Comment (cacaosteve) [reply crates/gpui/src/platform/mac/metal_renderer.rs]: I have a MacBook with M1 Max and it works for me before and after the change. Hopefully I'm on the right track here so we can get some momentum for a fix. Definitely open to suggestions.

**Comment by JunkuiZhang** [comment]
From my perspective, this PR has two issues:

- When enumerating GPUs, low-power ones should come first. That way on Intel Macs we’ll use the iGPU instead of the dGPU.

- On Intel Macs, `metal::Device::system_default()` actually always returns the dGPU, which means the code for selecting another GPU is never reached, so this PR will instroduce a regression.

**Comment by cacaosteve** [comment]
@JunkuiZhang thank you, I have fixed the issues. is there a way for people who have the issue to try a build?

**Comment by JunkuiZhang** [comment]
I think your changes make things a bit more complicated than they need to be. If I understand correctly, the issue on your machine is that `devices.pop()` returns `None`, which leads to an error being logged and then an immediate exit. A better approach, in my opinion, would be to log the error but not exit right away. Instead, fall back to `metal::Device::system_default()`.

**Comment by cacaosteve** [comment]
thank you. updated.

**Comment by cacaosteve** [comment]
recheck

**Comment by JunkuiZhang** [comment]
I pushed a few changes to your PR, could you check if everything still runs fine on your machine?

**Comment by cacaosteve** [comment]
thank you! yes it still works for me on MacBook Pro M1 Max. I've never been able to reproduce the original issue. your change is good, but sorting with (is_removable(), is_low_power()) then pop() still risks picking a removable eGPU when present.

proposed change:
let mut devices = metal::Device::all();
let device = if devices.is_empty() {
    log::error!("unable to enumerate Metal devices; attempting to use system default device");
    metal::Device::system_default().unwrap_or_else(|| {
        log::error!("unable to access a compatible graphics device");
        std::process::exit(1);
    })
} else {
    // Prefer iGPU by default; avoid eGPU unless it’s the only device
    devices.sort_by_key(|d| (d.is_removable(), !d.is_low_power()));
    devices.remove(0)
};

Why:
Prefer non-removable, low-power (iGPU) on Intel for stability/power.
Avoid eGPU by default; use dGPU/iGPU first.
If enumeration is empty (seen in some environments), log and fall back to system_default().
Exit only if both enumeration and system_default() fail.

**Comment by JunkuiZhang** [comment]
The change you suggested seems logically the same as mine, the only difference is that you’re using `!d.is_low_power()` while I’m using `d.is_low_power()`. From my testing, `d.is_low_power()` seems to be the correct one. But maybe I misunderstood your point, happy to adjust if that’s the case.

**Comment by cacaosteve** [comment]
I cleaned it up a bit more, I hope that's okay. My testing on MacBook Pro M1 Max always works, I was not able to reproduce the original issue.

Prefer non-removable, low-power GPU (iGPU) by ordering with min_by_key(|d| (d.is_removable(), !d.is_low_power())), yielding iGPU → dGPU → eGPU.
If enumeration returns empty (as seen in #37689), log and fall back to metal::Device::system_default(); exit only if both paths fail.
Fixes the prior sort+pop behavior, which could select an eGPU/dGPU unintentionally and is harder to reason about.
Avoids Intel regression where system_default() often picks the dGPU; Apple Silicon (single GPU) behavior is unchanged.

**Review by localcc — APPROVED** [review]
