### PR TITLE
language_models: Fix beta_headers for Anthropic custom models

### LINKED ISSUE #37289: AI: Anthropic `extra_beta_headers` is ignored for `claude-sonnet-4*`
### Summary

The `extra_beta_headers` option is completely ignored when using `Claude-sonnet-4`

### Description
Steps to trigger the problem:
1.  Add the following example config:
```
  "language_models": {
    "anthropic": {
      "available_models": [
        {
          "name": "claude-sonnet-4-0",
          "display_name": "Claude Sonnet 4 Broken",
          "extra_beta_headers": ["an-obviously-fake-header"],
          "max_tokens": 200000,
          "max_output_tokens": 8192,
          "cache_configuration": {
            "max_cache_anchors": 10,
            "min_total_token": 10000,
            "should_speculate": false
          },
          "mode": {
            "type": "thinking",
            "budget_tokens": 4096
          }
        }
      ]
    }
  }
```

2. Open a chat with the model.

**Expected Behavior**:
In the above case it should return an error saying "an-obviously-fake-header" isn't supported.

**Actual Behavior**:
The header is ignored. So it works.

### Model Provider Details
- Provider: Anthropic
- Model Name: claude-sonnet-4-0/claude-sonnet-4-20250514
- Mode: Any
- Other Details (MCPs, other settings, etc):

The reason why this is needed - to setup a version of Claude Sonnet 4 that can exceed the 200k max tokens.
To accomplish this you need to be able to add the "context-1m-2025-08-07" beta header:

```
  "language_models": {
    "anthropic": {
      "available_models": [
        {
          "name": "claude-sonnet-4-0",
          "display_name": "Claude Sonnet 4 Thinking (1M)",
          "extra_beta_headers": ["context-1m-2025-08-07"],
          "max_tokens": 1000000,
          "max_output_tokens": 8192,
          "cache_configuration": {
            "max_cache_anchors": 10,
            "min_total_token": 10000,
            "should_speculate": false
          },
          "mode": {
            "type": "thinking",
            "budget_tokens": 4096
          }
        }
      ]
    }
  }
```

### Zed Version and System Specs

Zed: v0.202.4 (Zed Preview) 
OS: macOS 15.6.1
Memory: 128 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by imumesh18**
Closes #37289

The current implementation has a problem. The **`from_id` method** in the Anthropic crate works well for predefined models, but not for custom models that are defined in the settings. This is because it fallbacks to using default beta headers, which are incorrect for custom models.

The issue is that the model instance for custom models lives within the `language_models` provider, so I've updated the **`stream_completion`** method to explicitly accept beta headers from its caller. Now, the beta headers are passed from the `language_models` provider all the way to `anthropic.stream_completion`, which resolves the issue.

Release Notes:

- Fixed a bug where extra_beta_headers defined in settings for Anthropic custom models were being ignored.

### CODE REVIEW

**Comment by idyll** [comment]
THANK YOU!

**Comment by crayment** [comment]
Really wanting this!!

**Comment by rafaelsimonmaia** [comment]
Can we get this reviewed and merged asap please.

File: crates/anthropic/src/anthropic.rs [hunk 1]
```diff
@@ -518,9 +520,7 @@ pub async fn stream_completion_with_rate_limit_info(
         stream: true,
     };
     let uri = format!("{api_url}/v1/messages");
-    let beta_headers = Model::from_id(&request.base.model)
-        .map(|model| model.beta_headers())
-        .unwrap_or_else(|_| Model::DEFAULT_BETA_HEADERS.join(","));
```
Comment (benbrandt) [inline crates/anthropic/src/anthropic.rs:523]: Are we sure that we don't need this prompt caching header anymore?

Comment (benbrandt) [reply crates/anthropic/src/anthropic.rs:523]: It seems like it isn't needed as of a few weeks ago, but isn't well documented: https://docs.anthropic.com/en/release-notes/api#august-13%2C-2025

Comment (idyll) [reply crates/anthropic/src/anthropic.rs:523]: AFAIK the header isn't needed... it looks like caching is working for me.

Also I can verify the fixes the referenced issue.

FAKE HEADER:
Screenshot 2025-09-02 at 7 30 32 PM

REAL HEADER:
Screenshot 2025-09-02 at 7 30 53 PM

Comment (imumesh18) [reply crates/anthropic/src/anthropic.rs:523]: Hey @benbrandt we haven't changed the behaviour of default headers.
If you see this line: https://github.com/zed-industries/zed/pull/37306/files#diff-ac515a3aa204ad384a8fca4cb357a45b9617f1afdece143be057c36d44a8faf1R427 from anthropic provider it uses this method: https://github.com/zed-industries/zed/blob/main/crates/anthropic/src/anthropic.rs#L320 which constructs the headers properly appending the default header. Prompt caching header is getting appended for all models including the custom one like previous behaviour.

Comment (benbrandt) [reply crates/anthropic/src/anthropic.rs:523]: Thanks for double checking for me!
