### PR TITLE
Compute scrollbar markers asynchronously

### LINKED ISSUE #9792: UI "vanishing" on search
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This never happened to me before but today suddenly when searching for a string in regex mode the entire text vanished from the ui:
Screenshot 2024-03-25 at 21 47 46

This weirdly enough only happens after a pretty big window size (good chunk bigger than 14" mac book screen)

This is what it looks like in test search mode:
Screenshot 2024-03-25 at 21 50 26

And this on a smaller screen size with regex mode (text mode also works fine):
Screenshot 2024-03-25 at 21 49 37

### Environment

Zed: v0.127.4 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14749405/Zed.log)

### PR DESCRIPTION
**Pull request by mrnugget**
Refs #9647
Fixes https://github.com/zed-industries/zed/issues/9792

This pull request moves the computation of scrollbar markers off the main thread, to prevent them from grinding the editor to a halt when we have a lot of them (e.g., when there are lots of search results on a large file). With these changes we also avoid generating multiple quads for adjacent markers, thus fixing an issue where we stop drawing other primitives because we've drawn too many quads in the scrollbar.

Release Notes:

- Improved editor performance when displaying lots of search results, diagnostics, or symbol highlights in the scrollbar ([#9792](https://github.com/zed-industries/zed/issues/9792)).

### CODE REVIEW

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -2620,6 +2485,156 @@ impl EditorElement {
...
+                                );
+                            }
+
+                            for (background_highlight_id, (_, background_ranges)) in
+                                background_highlights.iter()
+                            {
+                                if (*background_highlight_id
+                                    == TypeId::of::<BufferSearchHighlights>()
+                                    && scrollbar_settings.selections)
+                                    || scrollbar_settings.symbols_selections
```
Comment (alygin) [inline crates/editor/src/element.rs:2558]: @mrnugget, is this expression correct? It means that `symbols_selections = true` forces search highlight markers to be painted even if `selections = false`.

I know that it copies the logic of the previous implementation, but it looked like an error there too becaused it caused search-markers duplication. I always thought that the `selection` setting is for search highlights, and `symbols_selection` is for the `DocumentHighlightRead/Write` highlights.

Am I mistaken?

Comment (mrnugget) [reply crates/editor/src/element.rs:2558]: Yeah, we weren't sure about that either. We also suspected that one was a superset of the other and that we did the work twice, but weren't sure what the desired behavior is. You were more involved, I guess, so if you say that this is not correct, then you're probably right.
