### PR TITLE
supermaven_api: Ensure downloaded Supermaven binary has executable permissions set

### LINKED ISSUE #32068: Edit Predictions: Supermaven binary not marked as executable after download
### Summary

Supermaven `sm-agent-26` binary is downloaded but has incorrect permissions to execute. Fix is to just set it as executable; `chmod +x ~/.local/share/zed/supermaven/sm-agent-86`

Linux related complaints in https://github.com/zed-industries/zed/issues/15653 are most likely related.

### Description
Steps to trigger the problem:
1. Enable Supermaven for Edit Predictions
2. Watch `Supermaven initializing` forever

Actual Behavior: Supermaven's `sm-agent-26` is never executed
Expected Behavior: Supermaven Edit Predictions working

### Zed Version and System Specs

Zed: v0.188.6 (Zed) 
OS: Linux Wayland arch unknown
Memory: 14.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4070 Laptop GPU || NVIDIA || 570.153.02

### PR DESCRIPTION
**Pull request by MrSubidubi**
Closes #32068
Closes #15653

Not entirely sure that it fixes the latter issue, but I am fairly certain given the comments in #32068 and the available logs in the issue.

This PR fixes an issue where the Supermaven provider would not leave the "Initializing" stage. This happened due to the downloaded binary missing executable permissions. The change here ensures that freshly downloaded binaries as well as existing binaries downloaded by Zed have executable permissions set. I decided on also adding this for the latter since existing downloads would continue to be broken and Supermaven does not seem to change versions often given the logs provided by users.

While I was at it, I also added a `make_file_executable` to the util crate mirroring the method of the `zed_extensions_api` and refactored existing usages where possible to use that method instead. This makes the code slightly more readable in my opinion, yet adds a method to non-unix systems that practically does nothing. I can revert this should that be preferred.

Release Notes:

- Fixed an issue where the Supermaven completion provider would not leave the "Initializing" stage.

### CODE REVIEW

File: crates/language_extension/src/extension_lsp_adapter.rs [hunk 1]
```diff
@@ -134,26 +134,6 @@ impl LspAdapter for ExtensionLspAdapter {
...
-                #[cfg(not(windows))]
-                {
-                    use std::fs::{self, Permissions};
-                    use std::os::unix::fs::PermissionsExt;
-
-                    fs::set_permissions(&path, Permissions::from_mode(0o755))
-                        .context("failed to set file permissions")?;
-                }
-            }
-
```
Comment (MrSubidubi) [inline crates/language_extension/src/extension_lsp_adapter.rs]: Given the comment and the fact that both extensions are far beyond the specified versions here, I decided on removing this in 1adf9750f1b5cdcb6a3825889b0d0903754a8537. I stumbled on this whist refactoring the existing usages. Can revert this should this be preferred.

Comment (maxdeviant) [reply crates/language_extension/src/extension_lsp_adapter.rs]: Let’s leave it in, for now. Not related to the rest of this PR.

**Review by bennetbo — APPROVED** [review]
Thanks for fixing this!
