### PR TITLE
gpui: Disable rounding in the layout engine

### LINKED ISSUE #13993: 1px black border appear on Windows in sometimes
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When we resize window on Windows, it will appear 1px black border in right, bottom on window border in some window size.

This issue should be caused by GPUI, not just Zed, I also saw this in other GPUI examples.
## Have a black border

屏幕截图 2024-07-09 214518

## Sometimes not appear

屏幕截图 2024-07-09 214616

### Environment

Zed version: main branch, last commit: https://github.com/zed-industries/zed/commit/9b688655a823fd6fdc8e036af3ca80fcc99b838b
OS: Windows 11

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Rounding broke (among other things, probably) pixel-perfect image rendering with non-power-of-two scaling factor.

An example which reproduces the problem can be found [here](https://github.com/WaffleLapkin/gpui_taffy_rounding_whyyyyy).

How it looks with `gpui` from `main`:
2025-05-31 11:34:25+CEST

How it looks with this patch:
2025-05-31 11:35:28+CEST

Both screenshots are made on kde+wayland with magnification using kde's built-in magnification (`Meta`+`+`, `Meta`+`-`). Note that screenshot apps have a high chance of lying 🙃 

The image itself is 400 by 300 pixels of red/green checkerboard pattern made specifically to exaggerate scaling issues.

fixes #13993

Release Notes:

- N/A

### CODE REVIEW

**Review by mikayla-maki — APPROVED** [review]
Let's try it :D

**Comment by P1n3appl3** [comment]
So it turns out that test wasn't actually flaking, and somehow disabling rounding has slightly changed which completion items show up in the list in that case. I'll dig a bit more.

File: crates/gpui/src/taffy.rs [hunk 1]
```diff
@@ -28,8 +28,10 @@ const EXPECT_MESSAGE: &str = "we should avoid taffy layout errors by constructio
 
 impl TaffyLayoutEngine {
     pub fn new() -> Self {
+        let mut taffy = TaffyTree::new();
+        taffy.disable_rounding();
         TaffyLayoutEngine {
-            taffy: TaffyTree::new(),
+            taffy,
```
Comment (shujaatak) [inline crates/gpui/src/taffy.rs:34]: @mikayla-maki  @WaffleLapkin @JunkuiZhang @MatinAniss  Change `taffy,` to `taffy: taffy,` with that, Zed compiles successfully and the rounding issue is resolved. I also noticed that this change fixes https://github.com/zed-industries/zed/issues/13993 as well.

**Review by shujaatak — DISMISSED** [review]
~~Change `taffy,` to `taffy: taffy,` as otherwise zed doesn't compile.~~
Zed compiles perfectly, the issue was an oversight on my part.

File: crates/gpui/src/taffy.rs (hunk 1 above)
Comment (WaffleLapkin) [reply crates/gpui/src/taffy.rs:34]: These two syntactic forms have literally the same meaning, so they can't affect how the code behaves. The only way this would change things is if the tests use this file as input perhaps, but I'd consider this a problem with the test...

You also say that `zed` doesn't compile, but it does compile, right? The problem is failing tests, not compilation.

Comment (shujaatak) [reply crates/gpui/src/taffy.rs:34]: Zed compiles perfectly, the issue was an oversight on my part.

**Comment by P1n3appl3** [comment]
I was hoping that this fix would also resolve an issue with 1px overflow of horizontal lines that we were seeing in the `debugger: start` modal:
Screenshot 2025-06-24 at 11 52 10 AM

Unfortunately that seems to still happen with this change. I think it's still worth merging for the pixel-perfect image rendering as well as maybe fixing #13993, so I'll go update the failing test and land this.

**Comment by WaffleLapkin** [comment]
for future reference: if the rounding from taffy is desired for one reason or another, a different way to (most likely) fix the issues mentioned above would be to pass physical pixel lengths to taffy, so it rounds to physical pixels (can be reasonable) instead of logical ones (broken with some scaling factors)
