### PR TITLE
Properly load environment variables from the login shell

### LINKED ISSUE #11647: gopls: packages.load error: JSON decoding failed : invalid character 'x' in string escape code
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I input command `brew upgrade zed` and zed version from 0.132.2 to 0.134.4.
this is error "gopls: packages.load error: JSON decoding failed : invalid character 'x' in string escape code " when I open exist go project in zed.

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 13.0.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-05-10T14:34:48+08:00 [ERROR] crates/gpui/src/elements/img.rs:344: Client(Error { kind: Timeout, context: None, source: Some(Error { description: "Timeout was reached", code: 28, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None })
2024-05-10T14:34:48+08:00 [ERROR] crates/gpui/src/elements/img.rs:344: Client(Error { kind: Timeout, context: None, source: Some(Error { description: "Timeout was reached", code: 28, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None })
2024-05-10T14:35:06+08:00 [ERROR] crates/gpui/src/elements/img.rs:344: Client(Error { kind: Timeout, context: None, source: Some(Error { description: "Timeout was reached", code: 28, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None })
2024-05-10T14:35:07+08:00 [WARN] Generic lsp request to gopls failed: no package metadata for file file:///Users/xsh/fm/fm-suggest/internal/data/suggest.go
2024-05-10T14:35:07+08:00 [ERROR] crates/project/src/project.rs:7009: no package metadata for file file:///Users/xsh/fm/fm-suggest/internal/data/suggest.go
2024-05-10T14:35:07+08:00 [ERROR] crates/gpui/src/elements/img.rs:344: Client(Error { kind: Timeout, context: None, source: Some(Error { description: "Timeout was reached", code: 28, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None })
2024-05-10T14:35:07+08:00 [ERROR] crates/gpui/src/elements/img.rs:344: Client(Error { kind: Timeout, context: None, source: Some(Error { description: "Timeout was reached", code: 28, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None })

### LINKED ISSUE #13888: Opening a project with zed cli has go list: initialization failed error
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have been using Zed for a few days. So far I love it. I mostly use Go, Vue and Tailwind. It works with all of these out of the box. However, when opening one of my [projects](https://github.com/amir20/dozzle), with `zed .` I see an error: 

> go list: initialization failed: packages.Load error: err: exit status 1: stderr: failed to initialize build cache at /Users/amirraminfar

Going to `go.mod` I see: 

Screenshot 2024-07-05 at 7 47 18 PM

However, if I close Zed and open it using the regular launcher then it all works. 

I have tried: 
- Deleting `.cache`
- Deleting `/Users/amirraminfar/Library/Caches/go-build`
- Confirmed `go list` works fine 
- Dozzle project builds just fine in Github Actions

When I open a different project, it seems to work just fine with `zed` cli. I am not sure what is different about Dozzle 

Steps to produce: 

- cd to dozzle project 
- zed . 
- Go to `go.mod` file and notice the error

Opening same project with Mac Launcher works just fine. 

### Environment

Zed: v0.142.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-07-05 at 7 47 18 PM
Screenshot 2024-07-05 at 7 50 36 PM

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/16114734/Zed.log)

### LINKED ISSUE #18771: rust-analyzer fails to load workspaces when using fish-shell
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On recent Zed releases, rust-analyzer stopped working for me on macOS.

I've tried 0.152.4, and there the issue is not present.
I believe it is related to the new environment loading from #17717 (or adjacent changes).

This happens only when using fish as a login shell (no issue when switching to zsh).
This does not happen when launching from the cli.
This does not happen on Linux (with an up-to-date Zed version and also using fish).

As you can see in my logs, the character `[?2004l` appears, which is related to bracketed-paste mode in fish.
#13888 might be related, however that issue seems to be fixed after 0.153.x, and this issue starts at that version.

Apparently if you set the `FISH_UNIT_TESTS_RUNNING`, bracketed-paste mode is not active in fish.
After setting it using `launchctl setenv FISH_UNIT_TESTS_RUNNING 1`, rust-analyzer starts correctly.

My guess: now that a login shell is spawned to determine the environment variables,
it doesn't interact correctly with what fish does (printing those `[?2004l` characters to enable bracketed-paste mode).
I *think* this is part of the fish prompt, which gets [added as additional command](https://github.com/zed-industries/zed/blob/main/crates/project/src/environment.rs#L252) (for a good reason presumably).

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-06T08:16:08.729056+02:00 [INFO] ========== starting zed ==========
2024-10-06T08:16:08.732795+02:00 [INFO] Opening main db
2024-10-06T08:16:08.734907+02:00 [INFO] Opening main db
2024-10-06T08:16:08.749771+02:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-10-06T08:16:08.778106+02:00 [INFO] set environment variables from shell:/opt/homebrew/bin/fish, path:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/jonas/.cargo/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public
2024-10-06T08:16:08.863912+02:00 [INFO] initializing context server client
2024-10-06T08:16:08.864206+02:00 [INFO] Registering built-in prompt template: content_prompt
2024-10-06T08:16:08.864588+02:00 [INFO] Registering built-in prompt template: edit_workflow
2024-10-06T08:16:08.864735+02:00 [INFO] Registering built-in prompt template: project_slash_command
2024-10-06T08:16:08.864792+02:00 [INFO] Registering built-in prompt template: step_resolution
2024-10-06T08:16:08.865032+02:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-10-06T08:16:08.865172+02:00 [INFO] No prompt template overrides directory found at /Users/jonas/.config/zed/prompt_overrides. Using built-in prompts.
2024-10-06T08:16:08.866206+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-10-06T08:16:08.904847+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-06T08:16:08.905843+02:00 [INFO] Opening main db
2024-10-06T08:16:08.905913+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-06T08:16:08.910852+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-06T08:16:08.939053+02:00 [INFO] Opening main db
2024-10-06T08:16:08.940258+02:00 [INFO] Opening main db
2024-10-06T08:16:08.940748+02:00 [INFO] set status on client 0: Authenticating
2024-10-06T08:16:08.943483+02:00 [INFO] set status on client 113263: Connecting
2024-10-06T08:16:08.947711+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-06T08:16:09.021693+02:00 [INFO] attempting to start language server "rust-analyzer", path: "/Users/jonas/some/project", id: 1
2024-10-06T08:16:09.021781+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-06T08:16:09.022511+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-06T08:16:09.022648+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-06T08:16:09.033175+02:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2024-10-06T08:16:09.034252+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-06T08:16:09.036362+02:00 [INFO] found user-installed language server for rust-analyzer. path: "/opt/homebrew/bin/rust-analyzer", arguments: []
2024-10-06T08:16:09.036462+02:00 [INFO] starting language server process. binary path: "/opt/homebrew/bin/rust-analyzer", working directory: "/Users/jonas/some/project", args: []
2024-10-06T08:16:09.075398+02:00 [ERROR] Language server rust-analyzer (id 1) status update: Failed to load workspaces.
2024-10-06T08:16:09.083956+02:00 [ERROR] Language server rust-analyzer (id 1) status update: Failed to load workspaces.
</pre></details>

<details><summary>rust-analyzer.log</summary><pre>
stderr: 2024-10-06T06:21:17.477594Z  INFO Using sysroot workspace=/Users/jonas/some/project/Cargo.toml src_root=None root=None
stderr: 2024-10-06T06:21:17.482699Z  INFO did fetch workspaces workspaces=[Err(Failed to load the project at /Users/jonas/some/project/Cargo.toml
stderr:
stderr: Caused by:
stderr: 0: Failed to query rust toolchain version at /Users/jonas/some/project, is your toolchain setup correctly?
stderr: 1: cd "/Users/jonas/some/project" && "/Users/jonas/.cargo/bin/cargo" "--version" failed, exit status: 1
stderr: stderr:
stderr: error: could not create home directory: '/Users/jonas
stderr: [?2004l/.rustup': Permission denied (os error 13)
stderr:
stderr:
stderr: Stack backtrace:
stderr: 0: std::backtrace::Backtrace::create
stderr: 1: anyhow::error::<impl anyhow::Error>::msg
stderr: 2: project_model::utf8_stdout
stderr: 3: project_model::workspace::get_toolchain_version
stderr: 4: project_model::workspace::ProjectWorkspace::load
stderr: 5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
stderr: 6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 7: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: 8: std::sys::backtrace::__rust_begin_short_backtrace
stderr: 9: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: 10: std::sys::pal::unix::thread::Thread::new::thread_start
stderr: 11: __pthread_deallocate)]
stderr: 2024-10-06T06:21:17.486702Z ERROR GlobalState::handle_event{event=Event::Task}:GlobalState::handle_event/task: FetchWorkspaceError: rust-analyzer failed to load workspace: Failed to load the project at /Users/jonas/some/project/Cargo.toml: Failed to query rust toolchain version at /Users/jonas/some/project, is your toolchain setup correctly?: cd "/Users/jonas/some/project" && "/Users/jonas/.cargo/bin/cargo" "--version" failed, exit status: 1
stderr: stderr:
stderr: error: could not create home directory: '/Users/jonas
stderr: [?2004l/.rustup': Permission denied (os error 13)
</pre></details>

### LINKED ISSUE #19779: $PATH is not loaded Correctly on first Launch
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using Zed Flatpak, Immutable Distro.

Please Change the title if its not good, I have No idea what would be the best Title.

Zed when Launched Fresh after Boot or Lauched after closing will not load $PATH correctly.
Well it initially does but then disregard it and loads $PATH again but without added $PATH in .bashrc
seen in Zed-Fresh-Launch.log It initially get the $PATH with `:/home/deck/Py-V-Env/bin` then uses the PATH without the above mentioned location. which cause the pylsp to not work and provide this output
```
Language server error: pylsp

Unable to find pylsp from worktree
-- stderr--

```

funny enough, if i use the option "Open New Project" and Load the same Project Folder It correctly Works and Starts the pylsp from the `:/home/deck/Py-V-Env/bin` location.

I'm not sure if this issue is just happening to me or anyone else.

this isnt a big deal but having to open project every time when opening Zed will get tiresome.

Any guidence on if its unique to me on how to resolve it.

I have already Tried re-installing Zed, happy to provide any other info if needed.

Thanks for Making Zed, i Really enjoy it.

### Environment

Zed: v0.158.2 (Zed)
OS: Linux X11 steamos 3.5.19
Memory: 14.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV VANGOGH) || radv || Mesa 23.3.0-devel (git-4870e346ff)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed-Fresh-Launch.log</summary><pre>

2024-10-26T00:56:58.324123383-05:00 [INFO] ========== starting zed ==========
2024-10-26T00:56:58.347851378-05:00 [WARN] failed to load font 'Twemoji'
2024-10-26T00:56:58.348684253-05:00 [WARN] failed to load font 'Twemoji'
2024-10-26T00:56:58.369629323-05:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-10-26T00:56:58.3697252-05:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-10-26T00:56:58.381468409-05:00 [INFO] Opening main db
2024-10-26T00:56:58.381552275-05:00 [INFO] perform;
2024-10-26T00:56:58.381618539-05:00 [INFO] authenticate;
2024-10-26T00:56:58.381696874-05:00 [INFO] read_command;
2024-10-26T00:56:58.382770145-05:00 [INFO] new;
2024-10-26T00:56:58.382850451-05:00 [INFO] socket reader;
2024-10-26T00:56:58.383030573-05:00 [INFO] Opening main db
2024-10-26T00:56:58.385465134-05:00 [INFO] Using git binary path: None
2024-10-26T00:56:58.402332273-05:00 [INFO] no tokio runtime found, creating one for Reqwest...
2024-10-26T00:56:58.446287081-05:00 [INFO] set environment variables from shell:/bin/bash, path:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/deck/.local/bin:/home/deck/Py-V-Env/bin
2024-10-26T00:56:58.471379036-05:00 [ERROR] No such file or directory (os error 2) about ["/home/deck/.config/github-copilot"]
2024-10-26T00:56:58.471545597-05:00 [INFO] initializing context server client
2024-10-26T00:56:58.471712488-05:00 [INFO] Registering built-in prompt template: content_prompt
2024-10-26T00:56:58.472434346-05:00 [INFO] Registering built-in prompt template: edit_workflow
2024-10-26T00:56:58.472956031-05:00 [INFO] Registering built-in prompt template: project_slash_command
2024-10-26T00:56:58.473049117-05:00 [INFO] Registering built-in prompt template: step_resolution
2024-10-26T00:56:58.473924425-05:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-10-26T00:56:58.474319121-05:00 [INFO] No prompt template overrides directory found at /home/deck/.var/app/dev.zed.Zed/data/zed/prompt_overrides. Using built-in prompts.
2024-10-26T00:56:58.474766591-05:00 [INFO] extensions updated. loading 3, reloading 0, unloading 0
2024-10-26T00:56:58.480397775-05:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-10-26T00:56:58.480552855-05:00 [INFO] Opening main db
2024-10-26T00:56:58.501768843-05:00 [INFO] perform;
2024-10-26T00:56:58.50187369-05:00 [INFO] authenticate;
2024-10-26T00:56:58.501963776-05:00 [INFO] read_command;
2024-10-26T00:56:58.5033912-05:00 [INFO] socket reader;
2024-10-26T00:56:58.503462665-05:00 [INFO] Using Visual { id: 135, colormap: 0, depth: 32 }
2024-10-26T00:56:58.503555721-05:00 [INFO] Creating colormap 41943043
2024-10-26T00:56:58.532190182-05:00 [INFO] Enabling Vulkan Portability
2024-10-26T00:56:58.532255676-05:00 [INFO] Enabling color space support
2024-10-26T00:56:58.536183037-05:00 [INFO] Adapter: "AMD Radeon Graphics (RADV VANGOGH)"
2024-10-26T00:56:58.536876833-05:00 [INFO] Ray tracing is supported
2024-10-26T00:56:58.5514609-05:00 [INFO] Using surface present mode MAILBOX
2024-10-26T00:56:58.55160012-05:00 [WARN] Unable to forbid exclusive full screen
2024-10-26T00:56:58.555268283-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T00:56:58.55536583-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T00:56:58.555442225-05:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-10-26T00:56:58.582983552-05:00 [INFO] Refreshing at 16667 micros
2024-10-26T00:56:58.584586699-05:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV VANGOGH)", driver_name: "radv", driver_info: "Mesa 23.3.0-devel (git-4870e346ff)" }
2024-10-26T00:56:58.59892364-05:00 [INFO] Using surface present mode MAILBOX
2024-10-26T00:56:58.599118033-05:00 [WARN] Unable to forbid exclusive full screen
2024-10-26T00:56:58.610061919-05:00 [INFO] Opening main db
2024-10-26T00:56:58.625108898-05:00 [INFO] Opening main db
2024-10-26T00:56:58.639210424-05:00 [INFO] using project environment variables from CLI. PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
2024-10-26T00:56:58.640999703-05:00 [ERROR] No path or contents found for buffer
2024-10-26T00:56:58.713082227-05:00 [WARN] no language server found matching 'pylsp'
2024-10-26T00:56:58.713575329-05:00 [WARN] no language server found matching 'pylsp'
2024-10-26T00:56:59.096546417-05:00 [INFO] Node runtime install_if_needed
2024-10-26T00:56:59.230397978-05:00 [INFO] starting language server process. binary path: "/home/deck/.var/app/dev.zed.Zed/data/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/deck/.var/app/dev.zed.Zed/data/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-10-26T00:56:59.491281109-05:00 [INFO] attempting to start language server "pylsp", path: "/home/deck/Documents/Code/FFmpeg-py", id: 1
2024-10-26T00:56:59.492875335-05:00 [ERROR] Failed to start language server "pylsp": Unable to find pylsp from worktree
2024-10-26T00:56:59.492930518-05:00 [ERROR] server stderr: ""
2024-10-26T00:56:59.700051116-05:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-26T05:56:59.694Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-10-26T05:56:59.694Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-10-26T00:56:59.70328338-05:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "0fdf1dc9-39d3-4663-be21-493210fde4e2",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-10-26T00:56:59.74537867-05:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-26T05:56:59.710Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-10-26T05:56:59.710Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-10-26T00:57:03.85566838-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T00:57:03.866712368-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T00:57:03.883476264-05:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-10-26T00:57:03.90009544-05:00 [INFO] Creating a descriptor pool for at most 256 sets
</pre></details>

<details><summary>Zed-same-Project-Launched-using-open-new-project.log</summary><pre>

2024-10-26T01:08:56.569374047-05:00 [INFO] new;
2024-10-26T01:08:56.571157865-05:00 [INFO] keep_updated;
2024-10-26T01:08:56.5712877-05:00 [INFO] new;
2024-10-26T01:09:01.979583882-05:00 [INFO] Using Visual { id: 135, colormap: 0, depth: 32 }
2024-10-26T01:09:01.979682655-05:00 [INFO] Creating colormap 41943096
2024-10-26T01:09:01.984200064-05:00 [INFO] Enabling Vulkan Portability
2024-10-26T01:09:01.984269316-05:00 [INFO] Enabling color space support
2024-10-26T01:09:01.987969037-05:00 [INFO] Adapter: "AMD Radeon Graphics (RADV VANGOGH)"
2024-10-26T01:09:01.988380321-05:00 [INFO] Ray tracing is supported
2024-10-26T01:09:02.001932655-05:00 [INFO] Using surface present mode MAILBOX
2024-10-26T01:09:02.002889237-05:00 [WARN] Unable to forbid exclusive full screen
2024-10-26T01:09:02.006563368-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T01:09:02.006689102-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T01:09:02.006785665-05:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-10-26T01:09:02.031720452-05:00 [INFO] Refreshing at 16667 micros
2024-10-26T01:09:02.032638102-05:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV VANGOGH)", driver_name: "radv", driver_info: "Mesa 23.3.0-devel (git-4870e346ff)" }
2024-10-26T01:09:02.045651509-05:00 [INFO] Using surface present mode MAILBOX
2024-10-26T01:09:02.045825025-05:00 [WARN] Unable to forbid exclusive full screen
2024-10-26T01:09:02.073283765-05:00 [INFO] attempting to start language server "pylsp", path: "/home/deck/Documents/Code/FFmpeg-py", id: 2
2024-10-26T01:09:02.140539081-05:00 [INFO] using project environment variables shell launched in "/home/deck/Documents/Code/FFmpeg-py". PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/deck/.local/bin:/home/deck/Py-V-Env/bin:/home/deck/.local/bin:/home/deck/Py-V-Env/bin"
2024-10-26T01:09:02.141222513-05:00 [INFO] starting language server process. binary path: "/home/deck/Py-V-Env/bin/pylsp", working directory: "/home/deck/Documents/Code/FFmpeg-py", args: ["-v"]
2024-10-26T01:09:06.559304882-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T01:09:06.57271786-05:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-26T01:09:06.582118178-05:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-10-26T01:09:06.598789803-05:00 [INFO] Creating a descriptor pool for at most 256 sets
</pre></details>

### LINKED ISSUE #22437: Escape Sequence Issue in Zed Terminal with JetBrains Mono Nerd Font
### Check for existing issues

- [X] Completed

### Description

Using JetBrains Mono Nerd Font causes an issue when running Rust programs. The terminal seems to have a problem with an invalid escape sequence related to `conda` configurations:
```
CustomValidationError: Parameter auto_activate_base = 'false\n\x1b[?2004l' declared in <<merged>> is invalid.
The value 'false\n\x1b[?2004l' cannot be boolified.
```

### Details

Here are my `conda` configurations:
- `set -Ux CONDA_AUTO_ACTIVATE_BASE false` in fish shell (my default shell)
- `auto_activate_base: false` in `.condarc`

The issue is specific to Zed terminal when running Rust programs. Normal Zed terminal sessions and my system terminals such as COSMIC Terminal and Konsole with JetBrains Mono ***Nerd*** Font (set in Zed as well) work fine. I use Conda for other Python projects without issues.

### Workaround

Switching to the normal JetBrains Mono ~~Nerd~~ font in Zed Settings

### Zed Version and System Specs

```
Zed: v0.166.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 38.9 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.3.2-arch1.1
```

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### LINKED ISSUE #23649: Issue with cargo run and a corrupted $HOME variable
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I have just installed zed. I'm attempt to run my project via `cargo run` in the actions panel, and I immediately get this error:

```shell
error: can not save history
warning-path: Unable to locate data directory derived from $HOME: '/Users/tom
/.local/share/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

source: Error encountered while sourcing file '/Users/tom\n\e\[\?2004l/.config/fish/history.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/tom\n\e\[\?2004l/.config/fish/pure.fish':
source: No such file or directory
```

It seems that, somehow, `$HOME` contains a newline? I've never seen this before and it's never been an issue anywhere else. `$HOME` doesn't have a newline in any other shell.

This then causes a cascade of other errors as all my shell config fails to execute.

### Zed Version and System Specs

Zed: v0.170.2 (Zed)
OS: macOS 15.2.0
Memory: 96 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

Image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

[Zed.log](https://github.com/user-attachments/files/18546115/Zed.log)

```
</details>

### LINKED ISSUE #24200: Rust-Analyzer: failed to load workspaces after MacOS update
### Summary

Rust-analyzer shows the error: "Failed to load workspaces." after starting.

I don't know if my system has some weirdness but here are the steps for me:
Steps to trigger the problem:
1. Open zed to a rust project
2. the bottom right will have a notification that rust-analyzer failed to start: "Failed to load workspaces."

Actual Behavior:
rust-analyzer crashes.

Expected Behavior:
rust-analyzer should work.

# Some more info
Below I have the lsp debug log. I tried running the commands that log said rust-analyzer failed on, but they seem to work.
- ```cd "/Users/USERNAME/code/project" && /run/current-system/sw/bin/cargo --version``` outputs ```cargo 1.84.1 (66221abde 2024-11-19)``` as expected. 
- ```cd "/Users/USERNAME/code/project" && RUSTC_BOOTSTRAP="1" /run/current-system/sw/bin/rustc -Z unstable-options "--print" "target-spec-json"``` outputs <details> <summary> print target spec output </summary> {
  "abi-return-struct-as-int": true,
  "arch": "aarch64",
  "archive-format": "darwin",
  "cpu": "apple-m1",
  "crt-objects-fallback": "false",
  "data-layout": "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32",
  "debuginfo-kind": "dwarf-dsym",
  "dll-suffix": ".dylib",
  "dynamic-linking": true,
  "eh-frame-header": false,
  "emit-debug-gdb-scripts": false,
  "frame-pointer": "non-leaf",
  "function-sections": false,
  "has-rpath": true,
  "has-thread-local": true,
  "is-like-osx": true,
  "link-env": [
    "ZERO_AR_DATE=1"
  ],
  "link-env-remove": [
    "IPHONEOS_DEPLOYMENT_TARGET",
    "TVOS_DEPLOYMENT_TARGET",
    "XROS_DEPLOYMENT_TARGET"
  ],
  "linker-flavor": "darwin-cc",
  "linker-is-gnu": false,
  "lld-flavor": "darwin",
  "llvm-target": "arm64-apple-macosx",
  "max-atomic-width": 128,
  "metadata": {
    "description": "ARM64 Apple macOS (11.0+, Big Sur+)",
    "host_tools": true,
    "std": true,
    "tier": 1
  },
  "os": "macos",
  "split-debuginfo": "packed",
  "stack-probes": {
    "kind": "inline"
  },
  "supported-sanitizers": [
    "address",
    "thread",
    "cfi"
  ],
  "supported-split-debuginfo": [
    "packed",
    "unpacked",
    "off"
  ],
  "target-family": [
    "unix"
  ],
  "target-mcount": "\u0001mcount",
  "target-pointer-width": "64",
  "vendor": "apple"
}</details>

Something curious is that ```/Users/USERNAME/Library/Application Support/Zed/languages/rust-analyzer/rust-analyzer-2025-02-03``` still runs after the lsp crashes, and this is not the rust analyzer that is run in zed. although i dont know a lot about how zed handles LSPs under the hood.

I also tried running vscode, which works without issue.

# OS
I am running the latest version of MacOS, which i just upgraded today, which might or might not have something to do with my issue.
I also run nix-darwin through which I installed rustup and my rust toolchain is fully managed by rustup, but i doubt that has too much to do with the issue.

# Some more things i tried
- Restarting the language server
- Since there is a ```Permission denied (os error 13)``` at the bottom of the lsp server logs i gave zed full disk access under Settings -> security and privacy -> Full Disk Access

# LSP debug log
<details>
<summary>
LSP logs
</summary>
```
stderr: 2025-02-04T16:55:22.842424+01:00 ERROR failed fetching toolchain version for ManifestPath { file: AbsPathBuf("/Users/USERNAME/code/project/Cargo.toml") } workspace e=Failed to query rust toolchain version via `cd "/Users/USERNAME/code/project" && "/run/current-system/sw/bin/cargo" "--version"`, is your toolchain setup correctly?
stderr: 2025-02-04T16:55:22.915355+01:00 ERROR failed fetching data layout for ManifestPath { file: AbsPathBuf("/Users/USERNAME/code/project/Cargo.toml") } workspace e=unable to fetch target-data-layout via `cd "/Users/USERNAME/code/project" && RUSTC_BOOTSTRAP="1" "/run/current-system/sw/bin/rustc" "-Z" "unstable-options" "--print" "target-spec-json"`
stderr: 2025-02-04T16:55:23.025305+01:00 ERROR FetchWorkspaceError: rust-analyzer failed to load workspace: Failed to load the project at /Users/USERNAME/code/project/Cargo.toml: Failed to read Cargo metadata from Cargo.toml file /Users/USERNAME/code/project/Cargo.toml, None: Failed to run `cd "/Users/USERNAME/code/project" && "/run/current-system/sw/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" "/Users/USERNAME/code/project/Cargo.toml"`: `cargo metadata` exited with an error: error: could not create home directory: '/Users/USERNAME
stderr: [?2004l/.rustup': Permission denied (os error 13)
stderr:
stderr:
```
</details>

### Zed Version and System Specs

Zed: v0.171.6 (Zed)
OS: macOS 15.3.0
Memory: 16 GiB
Architecture: aarch64

### LINKED ISSUE #27601: Terminal spits out a bunch of errors on startup and on bash script run
### Summary

Whenever I turn on the provided terminal within Zed, I get the following messages:
```
bash: _module_raw: line 1: syntax error: unexpected end of file
bash: error importing function definition for `_module_raw'
bash: module: line 2: syntax error: unexpected end of file
bash: error importing function definition for `module'
/usr/bin/sh: module: line 2: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `module'
/usr/bin/sh: _module_raw: line 1: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `_module_raw'
/usr/bin/sh: module: line 2: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `module'
/usr/bin/sh: _module_raw: line 1: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `_module_raw'
/usr/bin/sh: module: line 2: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `module'
/usr/bin/sh: _module_raw: line 1: syntax error: unexpected end of file
/usr/bin/sh: error importing function definition for `_module_raw'
```

Also, whenever I run a bash script, I get similar errors:
```
bash: module: line 2: syntax error: unexpected end of file
bash: error importing function definition for `module'
bash: _module_raw: line 1: syntax error: unexpected end of file
bash: error importing function definition for `_module_raw'
```

### Zed Version and System Specs

Zed: v0.178.5 (Zed) 
OS: Linux X11 fedora 41
Memory: 31.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 580 Series (RADV POLARIS10) || radv || Mesa 25.0.1

### PR DESCRIPTION
**Pull request by haruleekim**
Fixes #11647
Fixes #13888
Fixes #18771
Fixes #19779
Fixes #22437
Fixes #23649
Fixes #24200
Fixes #27601

Zed’s current method of loading environment variables from the login shell has two issues:
1. Some shells—​fish in particular—​​write specific escape characters to `stdout` right before they exit. When this happens, the tail end of the last environment variable printed by `/usr/bin/env` becomes corrupted.
2. If a multi-line value contains an equals sign, that line is mis-parsed as a separate name-value pair.

This PR addresses those problems by:
1. Redirecting the shell command's `stdout` directly to a temporary file, eliminating any side effects caused by the shell itself.
2. Replacing `/usr/bin/env` with `sh -c 'export -p'`, which removes ambiguity when handling multi-line values.

Additional changes:
- Correctly set the arguments used to launch a login shell under `csh` or `tcsh`.
- Deduplicate code by sharing the implementation that loads environment variables on first run with the logic that reloads them for a project.

Release Notes:

- Improved Zed inheriting environment variables from user shells.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Nice! Thank you for this.

It looks like all callers read $SHELL, filter out None values in the environment, and immediately pass the output of capture into parse, and do the same thing with all errors.

Can you please simplify the API to:

```
fn capture(path) -> anyhow::Result<HashMap<String,String>>
```

Happy to take a pass later in the week if you don't have time.

**Comment by haruleekim** [comment]
How about this approach? Since the `project::environment` module requires context-specific error messages to be shown to the user, I defined a custom error enum instead of using anyhow

**Comment by ConradIrwin** [comment]
Thanks for the update, and sorry for not being clear enough! 

I don't think the context is useful to show, I think we can simplify the error reporting to "Failed to load environment variables. See log for details" in all cases. Some we really never expect (like SHELL missing, because we load the shell explicitly) whereas others are pretty indistinguishable (spawning the shell failed vs it exited with an invalid status code) unless you're debugging, in which case you need the log anyway.

The error handling in this part of the code is already a bit weird, but I'd like to make it consistent with everywhere else and just use anyhow::Result.

**Comment by haruleekim** [comment]
I understand and I agree with your thoughts. I'll update it!

File: crates/util/src/util.rs [hunk 1]
```diff
@@ -313,26 +310,19 @@ fn load_shell_from_passwd() -> Result<()> {
...
     // into shell's `cd` command (and hooks) to manipulate env.
     // We do this so that we get the env a user would have when spawning a shell
     // in home directory.
-    let output = shell_env::capture(&shell, env::var_os("HOME"))??;
-
-    for (key, value) in shell_env::parse(&output)? {
-        if let Some(value) = value {
-            unsafe { env::set_var(key.as_ref(), value.as_ref()) };
-        }
+    for (name, value) in shell_env::capture(env::var_os("HOME"))? {
```
Comment (ConradIrwin) [inline crates/util/src/util.rs]: @haruleekim  You can also use `paths::home_dir()` here to get a non-optional version.

Comment (haruleekim) [reply crates/util/src/util.rs]: Thank you! Then would it be better to change the `change_dir` parameter from `Option<impl AsRef<Path>>` to just `impl AsRef<Path>`?

**Comment by ConradIrwin** [comment]
Thanks!

File: crates/util/src/util.rs (hunk 1 above)
Comment (ConradIrwin) [reply crates/util/src/util.rs]: Oh, I missed this. Yes, that would be better (or just an `&Path` as I think the callers have the correct concrete types already).

**Comment by SirensOfTitan** [comment]
I'm not certain, but I think this update may have broken reading environment variables:
```zsh
2025-06-05T08:42:24-04:00 WARN  [Users] login shell exited with exit status: 1. stdout: "", stderr: "zsh:1: file exists: /var/folders/z2/bnh3pbb10dv5_88dy_9dnsw40000gn/T/.tmpUkPubr\n"
2025-06-05T08:42:24-04:00 ERROR [project::environment] Failed to load environment variables. See log for details
```

**Comment by mcginleyr1** [comment]
> I'm not certain, but I think this update may have broken reading environment variables:
> 
> ```shell
> 2025-06-05T08:42:24-04:00 WARN  [Users] login shell exited with exit status: 1. stdout: "", stderr: "zsh:1: file exists: /var/folders/z2/bnh3pbb10dv5_88dy_9dnsw40000gn/T/.tmpUkPubr\n"
> 2025-06-05T08:42:24-04:00 ERROR [project::environment] Failed to load environment variables. See log for details
> ```

I'm seeing the exact same thing with a different .tmp*** obviously.

**Comment by ConradIrwin** [comment]
Sorry about that, fix in progress at #32136
