### PR TITLE
git: Fix staging file hunks on Windows

### LINKED ISSUE #26458: Git Beta: Cannot stage file hunks
### Summary

When staging hunks in the file or in "Uncommited Changes" tab.

Steps to trigger the problem:
1. Open file with changings
2. Stage the hunk
3. The error will appears

Actual Behavior:

https://github.com/user-attachments/assets/c13f6b58-e635-45e1-a760-b421fd53646a

Expected Behavior:

Hunk must be staged.

### Zed Version and System Specs

Zed: v0.178.0 (Zed Dev ed6bf7f161c6af6e10354faacb8b643a55c80b27) 
OS: Windows 10.0.26100
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by CharlesChen0823**
Closes #26458 

I had checked, and also reference the implementation in vscode.

Release Notes:

- N/A

### CODE REVIEW

File: crates/git/src/repository.rs [hunk 1]
```diff
@@ -1373,6 +1373,17 @@ impl RepoPath {
 
         RepoPath(path.into())
     }
+
+    pub fn normalize(&self) -> String {
```
Comment (JunkuiZhang) [inline crates/git/src/repository.rs:1377]: Could we change the function name here? Rust itself already has a `normalize()` method for the path struct.

Comment (CharlesChen0823) [reply crates/git/src/repository.rs:1377]: I think this name should changed,but I cannot find a better name,do you have any suggestions?

Comment (JunkuiZhang) [reply crates/git/src/repository.rs:1377]: I'm gonna leave the naming to native English speakers—I’m not great at coming up with names.

Comment (niklaswimmer) [reply crates/git/src/repository.rs:1377]: For the name: maybe `to_unix_string` or `to_forward_slashes`.
Also not really a necessity, but maybe we can avoid the clone on not windows systems by returning a `Cow<OsStr>` here. The not windows branch could just be `Cow::Borrowed(self.0)`. For the windows branch it is unfortunate that we need to convert into a lossy string first only to perform the replace, but I guess without bringing in `bstr` or something else (which should be avoided just for this I think) it would be to complicated - so you will have to `.into` it back to make it work with the `Cow`.

Comment (CharlesChen0823) [reply crates/git/src/repository.rs]: rename to `to_unix_style`

**Comment by JunkuiZhang** [comment]
Thank you @CharlesChen0823 @niklaswimmer
