### PR TITLE
editor: Fix inlay hint navigation for WSL/remote file paths

### LINKED ISSUE #46113: WSL: ctrl-click  on inlay hints leads to unexpected file location
### Reproduction steps

I wasn't able to find any similar issues, hopefully this is easy enough to reproduce (it's 100% for me):

1. Enable inlay hints with rust-analyzer and configure Zed to show type hints.
2. Open a remote project to actually show inlay hints. For example I used a very simple Cargo project:
   `src/main.rs`:
    ```rs
    mod foo;
    
    fn main() {
        let f = foo::new();
    }
    ```
    `src/foo.rs`:
    ```rs
    /// some doc
    pub struct Foo;
    
    pub fn new() -> Foo {
        Foo
    }
    ```

3. Hover over `Foo` in the inlay hint for `f: Foo`. As I understand no popover appears and this is expected for now due to #33715
4. Ctrl-click `Foo`.

### Current vs. Expected behavior

Current behavior: minibuffer appears with `References to f`, as if the variable name was clicked.

Note that `editor: go to type definition` still works as expected, so it seems to be something specific about the hover link / inlay hint.

Image

Expected behavior: Jump to the definition of `Foo`. This appears to work when I tested on macOS and Windows native, so there must be something specific about either remotes in general or WSL that's different here:

Image

### Zed version and system specs

Zed: v0.218.3+preview.104.4adf4c6c1dc3cad2cb35273ee707812c6874ac3b (Zed Preview) 
OS: Windows 10.0.22631
Memory: 63.6 GiB
Architecture: x86_64
GPU: NVIDIA RTX 5000 Ada Generation Laptop GPU || NVIDIA Corporation || 573.42 r570_00

### Attach Zed log file

There is an error in the logs which seems like it very well might be related? Looking at the relevant code, I'm guessing it's just falling back to "find references" because the definition fails to be revealed...

<details><summary>Zed.log</summary>

```log
2026-01-05T13:59:03-08:00 INFO  [crashes] (remote server) crash handler registered
2026-01-05T13:59:03-08:00 INFO  [project::lsp_store] (remote server) Waiting for worktree "/home/ian/Documents/Development/rs-sandbox" to be trusted, before starting language server rust-analyzer
2026-01-05T13:59:04-08:00 INFO  [util] (remote server) set environment variables from shell:/run/current-system/sw/bin/fish, <redacted>
2026-01-05T13:59:04-08:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: color-highlight, No extension manifest found for extension color-highlight
2026-01-05T13:59:04-08:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: html, No extension manifest found for extension html
2026-01-05T13:59:04-08:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: nix, mismatched versions: (0.1.2) != (0.1.3)
2026-01-05T13:59:04-08:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: powershell, mismatched versions: (0.3.0) != (0.4.0)
2026-01-05T13:59:04-08:00 INFO  [extension_host] Uploading extension color-highlight to RemotePathBuf { style: Posix, string: "/home/ian/.local/share/zed/remote_extensions/uploads/color-highlight" }
2026-01-05T13:59:04-08:00 ERROR [crates/extension_host/src/extension_host.rs:1835] failed to upload directory <redacted> -> /home/ian/.local/share/zed/remote_extensions/uploads/color-highlight: Command '"wsl.exe" "--user" "ian" "--distribution" "NixOS" "--cd" "~" "--exec" "cp" "-r" "<redacted>/AppData/Local/Temp/.tmpYcqkzl" "/home/ian/.local/share/zed/remote_extensions/uploads/color-highlight"' failed: <3>WSL (12799 - Relay) ERROR: CreateProcessCommon:800: execvpe(cp) failed: No such file or directory
2026-01-05T13:59:07-08:00 INFO  [project::lsp_store] (remote server) Worktree "/home/ian/Documents/Development/rs-sandbox" is trusted, starting language server rust-analyzer
2026-01-05T13:59:09-08:00 INFO  [lsp] (remote server) starting language server process. binary path: "/home/ian/.local/share/zed/languages/rust-analyzer/rust-analyzer-2026-01-05", working directory: "/home/ian/Documents/Development/rs-sandbox", args: []
2026-01-05T13:59:21-08:00 WARN  [project::lsp_store] (remote server) Get diagnostics via rust-analyzer failed: server cancelled the request
2026-01-05T13:59:21-08:00 ERROR [project::lsp_store] (remote server) Failed to pull diagnostics: pulling diagnostics: Get diagnostics via rust-analyzer failed: server cancelled the request
2026-01-05T13:59:23-08:00 ERROR [crates/editor/src/hover_links.rs:164] location tasks

Caused by:
    0: open local buffer
    1: can't convert URI to path
2026-01-05T13:59:25-08:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA RTX 5000 Ada Generation Laptop GPU", driver_name: "NVIDIA Corporation", driver_info: "573.42 r570_00" }
```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```jsonc
{
  "inlay_hints": {
    "show_parameter_hints": true,
    "show_type_hints": true,
    "enabled": true,
    "show_background": true,
    "toggle_on_modifiers_press": {
      "control": true,
      "alt": true,
    },
  },
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "targetDir": true,
        },
      },
    },
  }
}
```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```jsonc
[
  {
    "context": "Workspace",
    "bindings": {
      "ctrl-p": "outline::Toggle",
      "ctrl-t": "file_finder::Toggle",
      "ctrl-alt-win-left": [
        "workspace::MoveItemToPaneInDirection",
        { "direction": "left" },
      ],
      "ctrl-alt-win-right": [
        "workspace::MoveItemToPaneInDirection",
        { "direction": "right" },
      ],
      // weirdness here https://github.com/zed-industries/zed/issues/21358
      // these vim binds seem to work vs panel::NextPanelTab though
      "ctrl-tab": "vim::GoToTab",
      "ctrl-shift-tab": "vim::GoToPreviousTab",
      "ctrl-alt-w": "workspace::CloseActiveDock",
      "ctrl-win-shift-f": "pane::DeploySearch",
      "ctrl-alt-l": "language_selector::Toggle",
      "ctrl-alt-shift-w": "workspace::CloseWindow",
      "alt-shift-d": ["git::BranchDiff", { "show_picker": true }],
      "ctrl-alt-left": "workspace::ActivatePaneLeft",
      "ctrl-alt-right": "workspace::ActivatePaneRight",
      "ctrl-alt-up": "workspace::ActivatePaneUp",
      "ctrl-alt-down": "workspace::ActivatePaneDown",
    },
  },
  {
    "context": "Editor && os == windows",
    "bindings": {
      "win-alt-v": "editor::Paste",
      "win-alt-c": "editor::Copy",
    },
  },
  {
    "context": "Editor",
    "bindings": {
      "alt-z": "editor::ToggleSoftWrap",
      "ctrl-[": "editor::Fold",
      "ctrl-]": "editor::UnfoldRecursive",
      "ctrl-s": "workspace::Save",
      "alt-b": "git::Blame",
      "alt-h": "git::FileHistory",
      "alt-d": [
        "action::Sequence",
        [
          "editor::CollapseAllDiffHunks",
          "editor::GoToHunk",
          "editor::ToggleSelectedDiffHunks",
        ],
      ],
      "shift-alt-d": [
        "action::Sequence",
        [
          "editor::CollapseAllDiffHunks",
          "editor::GoToPreviousHunk",
          "editor::ToggleSelectedDiffHunks",
        ],
      ],
      "ctrl-alt-left": "workspace::ActivatePaneLeft",
      "ctrl-alt-right": "workspace::ActivatePaneRight",
      "ctrl-alt-up": "workspace::ActivatePaneUp",
      "ctrl-alt-down": "workspace::ActivatePaneDown",
    },
  },
  {
    "context": "VimControl && !menu",
    "bindings": {
      "g H": "editor::FindAllReferences",
      "ctrl-b": "workspace::ToggleLeftDock",
      "ctrl-o": "workspace::Open",
    },
  },
  {
    "context": "Editor && renaming",
    "bindings": {
      "escape": "vim::SwitchToNormalMode",
    },
  },
  {
    "context": "bottom_dock == TerminalPanel > vim_mode == normal",
    "bindings": {
      "escape": [
        "action::Sequence",
        ["terminal_panel::Toggle", "terminal_panel::Toggle"],
      ],
    },
  },
  {
    "context": "vim_operator == a || vim_operator == i || vim_operator == cs || vim_operator == ys",
    "bindings": {
      "q": "vim::MiniQuotes",
      "b": "vim::MiniBrackets",
      "Q": "vim::AnyQuotes",
      "B": "vim::AnyBrackets",
    },
  },
  {
    "bindings": {
      "ctrl-alt-,": "zed::OpenSettings",
      "ctrl-,": "zed::OpenSettingsFile",
      "ctrl-shift-enter": "workspace::ToggleZoom",
      "ctrl-tab": "panel::NextPanelTab",
    },
  },
  {
    "context": "Terminal",
    "bindings": {
      "alt-win-v": "terminal::Paste",
      "ctrl-\\": "pane::SplitRight",
      "ctrl-|": "pane::SplitDown",
      "ctrl-b": "workspace::ToggleLeftDock",
    },
  },
  {
    "context": "Pane",
    "bindings": {
      "ctrl-alt-w": ["pane::CloseActiveItem", { "close_pinned": false }],
    },
  },
  {
    "context": "RulesLibrary",
    "bindings": {
      "ctrl-alt-w": "workspace::CloseWindow",
    },
  },
  {
    "context": "SettingsWindow",
    "bindings": {
      "ctrl-alt-w": "workspace::CloseWindow",
    },
  },
  {
    "context": "!ContextEditor > (Editor && mode == full)",
    "bindings": {
      "ctrl-win-r": "pane::RevealInProjectPanel",
    },
  },
  {
    "context": "VimControl && vim_mode != insert",
    "bindings": {
      "g m": "editor::ExpandMacroRecursively",
    },
  },
  {
    "context": "Terminal || Editor && os == windows",
    "bindings": {
      "ctrl-win-f": "buffer_search::Deploy",
    },
  },
  {
    // It would be nice to include something about "Terminal" here but doesn't seem
    // like there's a context key for it... this will do for now
    "context": "Dock > BufferSearchBar",
    "bindings": {
      "enter": "search::SelectNextMatch",
    },
  },
]
```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

NixOS

### PR DESCRIPTION
**Pull request by lingyaochu**
Closes #46113

This issue occurs during remote development due to filesystem inconsistencies between the local and remote environments. The full code analysis is as follows:

The issue manifests with the following error:

```
2026-01-05T13:59:23-08:00 ERROR [crates/editor/src/hover_links.rs:164] location tasks

Caused by:
    0: open local buffer
    1: can't convert URI to path
```

#### 1. Click Handler Entry Point

The error originates from `handle_click_hovered_link()` in `crates/editor/src/hover_links.rs`:

```rust
pub(crate) fn handle_click_hovered_link(
    &mut self,
    point: PointForPosition,
    modifiers: Modifiers,
    window: &mut Window,
    cx: &mut Context<Editor>,
) {
    let reveal_task = self.cmd_click_reveal_task(point, modifiers, window, cx);
    cx.spawn_in(window, async move |editor, cx| {
        let definition_revealed = reveal_task.await.log_err().unwrap_or(Navigated::No);
        let find_references = editor
            .update_in(cx, |editor, window, cx| {
                if definition_revealed == Navigated::Yes {
                    return None;
                }
                match EditorSettings::get_global(cx).go_to_definition_fallback {
                    GoToDefinitionFallback::None => None,
                    GoToDefinitionFallback::FindAllReferences => {
                        editor.find_all_references(&FindAllReferences::default(), window, cx)
                    }
                }
            })
            .ok()
            .flatten();
        if let Some(find_references) = find_references {
            find_references.await.log_err();
        }
    })
    .detach();
}
```

When `reveal_task` fails, `definition_revealed` becomes `Navigated::No`, triggering the fallback mechanism. Since the default `go_to_definition_fallback` setting is `FindAllReferences`, the code falls back to finding references instead of the intended type definition. This explains why users observe navigation to variable references.

#### 2. Navigation Chain

The `reveal_task` is created by `cmd_click_reveal_task()` (line 210 in `hover_links.rs`), which:
1. Reads the `hovered_link_state`
2. Transforms it into `links`
3. Calls `navigate_to_hover_links(None, links, split, window, cx)`

In `navigate_to_hover_links()` (line 17392 in `crates/editor/src/editor.rs`), the `HoverLink::InlayHint` branch is executed:

```rust
pub(crate) fn navigate_to_hover_links(
    &mut self,
    kind: Option<GotoDefinitionKind>,
    definitions: Vec<HoverLink>,
    split: bool,
    window: &mut Window,
    cx: &mut Context<Editor>,
) -> Task<Result<Navigated>> {
    let mut first_url_or_file = None;
    let definitions: Vec<_> = definitions
        .into_iter()
        .filter_map(|def| match def {
            HoverLink::Text(link) => Some(Task::ready(anyhow::Ok(Some(link.target)))),
            HoverLink::InlayHint(lsp_location, server_id) => {
                let computation =
                    self.compute_target_location(lsp_location, server_id, window, cx);
                Some(cx.background_spawn(computation))
            }
            // ...
```

#### 3. Failure Point

The code then calls `compute_target_location()` (line 17588 in `editor.rs`), which invokes `open_local_buffer_via_lsp()` to resolve `lsp_location.uri`. 

The actual failure occurs in `open_local_buffer_via_lsp()` (line 8674 in `crates/project/src/lsp_store.rs`):

```rust
pub(crate) fn open_local_buffer_via_lsp(
    &mut self,
    abs_path: lsp::Uri,
    language_server_id: LanguageServerId,
    cx: &mut Context<Self>,
) -> Task<Result<Entity<Buffer>>> {
    cx.spawn(async move |lsp_store, cx| {
        let current_scheme = abs_path.scheme().to_owned();

        let abs_path = abs_path
            .to_file_path()
            .map_err(|()| anyhow!("can't convert URI to path"))?;  // Error occurs here
        // ...
```

### Root Cause

The fundamental issue is that `abs_path.to_file_path()` fails to convert the URI to a file path. This occurs because:

1. In remote development scenarios, the LSP server runs on the remote host (e.g., WSL/Linux)
2. The LSP server returns URIs using the remote system's path format (e.g., `file:///home/user/project/file.rs` on Linux)
3. When the Windows client receives this URI, `to_file_path()` cannot parse the Linux-style path, as it expects Windows-format URIs.

The `open_local_buffer_via_lsp()` function does not account for cross-platform path format differences in remote development scenarios, resulting in URI conversion failure and triggering the incorrect fallback behavior.

Release Notes:

- N/A *or* Added/Fixed/Improved ...

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you for a stab at it.

Given that the fix is in the `lsp_store` layer, we should be able to write a test in `crates/collab/src/tests/editor_tests.rs` for that?

File: crates/collab/src/tests/editor_tests.rs [hunk 1]
```diff
@@ -2392,6 +2392,244 @@ async fn test_inlay_hint_refresh_is_forwarded(
     });
 }
 
+#[gpui::test]
+async fn test_inlay_hint_type_navigation(cx_a: &mut TestAppContext, cx_b: &mut TestAppContext) {
```
Comment (Veykril) [inline crates/collab/src/tests/editor_tests.rs]: This doesn't actually test the interesting case of where we have a windows host connecting to a posix remote project, so this doesn't test what we want

File: crates/collab/src/tests/editor_tests.rs [hunk 2]
```diff
@@ -2392,6 +2392,244 @@ async fn test_inlay_hint_refresh_is_forwarded(
...
+        .await
+        .unwrap()
+        .downcast::<Editor>()
+        .unwrap();
+
+    let fake_server = fake_servers.next().await.unwrap();
+
+    fake_server
+        .set_request_handler::<lsp::request::InlayHintRequest, _, _>(move |_params, _| {
+            let types_uri = lsp::Uri::from_file_path(path!("/a/types.rs")).unwrap();
```
Comment (Veykril) [inline crates/collab/src/tests/editor_tests.rs]: Notably this creates a `C:\\path` on windows, but the handler should return a posix style path here after all for us to hit the interesting case

**Review by Veykril — COMMENTED** [review]
.

**Review by Veykril — APPROVED** [review]
Thanks!
