### PR TITLE
Fix deprecation warning text being covered by right dock

### LINKED ISSUE #30378: Settings Deprecation warning text can be covered by Right Dock
### Summary

Zed's settings.json Deprecation Text could be covered by Right Dock

### Description

Steps to reproduce:
1. Open Settings (where `settings.json` contains outdated configuration)
2. Open right dock
3. Dragging the right sidebar to the left, where the deprecation text could be covered by the dock

From my experiment, the right "sidebar" could be either Notifications or Zed 

Expected Behavior:

The text should be auto wrapped correctly by the width of main tab

Actual Behavior:

Image

<details><summary>Here's the deprecated part in `settings.json` from my configuration, that result in the deprecation warning (though it's not relative to this Issue, just for demo)</summary>

```json
"assistant": {
    "default_profile": "write",
    "profiles": {
      "write": {
        "name": "Write",
        "tools": {
          "batch_tool": false,
          "code_actions": false,
          "code_symbols": false,
          "contents": true,
          "copy_path": false,
          "create_file": true,
          "delete_path": false,
          "diagnostics": true,
          "edit_file": true,
          "fetch": true,
          "list_directory": true,
          "move_path": false,
          "now": false,
          "find_path": true,
          "read_file": true,
          "grep": true,
          "rename": false,
          "symbol_info": false,
          "terminal": true,
          "thinking": true,
          "web_search": true
        },
        "enable_all_context_servers": true,
        "context_servers": {}
      }
    },
    "always_allow_tool_actions": true,
    "default_model": {
      "provider": "zed.dev",
      "model": "claude-3-7-sonnet-latest"
    },
    "version": "2"
  }
```
</details>

### Zed Version and System Specs

Zed: v0.186.4 (Zed Preview) 
OS: macOS 15.3.2
Memory: 24 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by kmpeeduwee**
Closes [#30378](https://github.com/zed-industries/zed/issues/30378)

Release Notes:

- Fixed deprecation warning text being covered by right dock

### CODE REVIEW

**Comment by kmpeeduwee** [comment]
@cla-bot check

**Comment by smitbarmase** [comment]
Thank you, but I also noticed `settings_backup.json` isn't in line with the above text. I think this is because we are using two Label components which don't nicely fit into each other. Maybe we should use a Markdown component?

image

**Comment by eyesaider** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by fivemeyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by fivemserverhostings** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by eyestorefivem** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by eyesgodcode** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by kmpeeduwee** [comment]
> Thank you, but I also noticed `settings_backup.json` isn't in line with the above text. I think this is because we are using two Label components which don't nicely fit into each other. Maybe we should use a Markdown component?
> image


Yes, thanks for the suggestion! It turned out much better this way! I've pushed the changes. Issues:

- I couldn't find how to change the background for settings_backup.json, it's now slightly different from the original
- My fix in the code seems a bit cumbersome

**Comment by smitbarmase** [comment]
It works as intended. Nice work, thanks for picking it up. I think for the issues you mentioned:

- We should use `Markdown::new` and `MarkdownElement::new` to render, it will make it less cumbersome.
- If the default code style doesn't match what we need, you can use the `code_block_renderer` method on it. Maybe take a look at the styling used in other parts for consistency.

**Comment by kmpeeduwee** [comment]
> It works as intended. Nice work, thanks for picking it up. I think for the issues you mentioned:
> 
>     * We should use `Markdown::new` and `MarkdownElement::new` to render, it will make it less cumbersome.
> 
>     * If the default code style doesn't match what we need, you can use the `code_block_renderer` method on it. Maybe take a look at the styling used in other parts for consistency.

Thank you so much for your help! It really is much better now. I've pushed the changes :)

File: crates/zed/src/zed/migrate.rs [hunk 1]
```diff
@@ -122,6 +147,7 @@ impl ToolbarItemView for MigrationBanner {
 
         if &target == paths::keymap_file() {
             self.migration_type = Some(MigrationType::Keymap);
+            self.update_banner_text(cx);
```
Comment (smitbarmase) [inline crates/zed/src/zed/migrate.rs:150]: Do we need to update the banner text before the `should_migrate.await` check? I think this should be done later when the `ChangeLocation` event is emitted.

File: crates/zed/src/zed/migrate.rs [hunk 2]
```diff
@@ -159,54 +186,51 @@ impl ToolbarItemView for MigrationBanner {
...
-                                    .child(
-                                        Label::new(backup_file_name)
-                                            .buffer_font(cx)
-                                            .size(LabelSize::Small),
-                                    ),
-                            ),
+                        div()
+                            .overflow_hidden()
+                            .text_size(TextSize::Default.rems(cx))
+                            .child(if let Some(markdown_entity) = &self.markdown_entity {
```
Comment (smitbarmase) [inline crates/zed/src/zed/migrate.rs:214]: We can use the method `.when_some` instead of an if-else statement. That way, you don't have to specify an else block, and it's cleaner.

File: crates/zed/src/zed/migrate.rs [hunk 3]
```diff
@@ -100,6 +104,27 @@ impl MigrationBanner {
...
+            Some(MigrationType::Settings) => "settings",
+            None => return,
+        };
+
+        let backup_file_name = self.backup_file_name();
+        let migration_text = format!(
+            "Your {} file uses deprecated settings which can be \
+            automatically updated. A backup will be saved to `{}`",
+            file_type,
+            format!("\u{00A0}{}\u{00A0}", backup_file_name)
```
Comment (smitbarmase) [inline crates/zed/src/zed/migrate.rs:120]: I suppose you added this to prevent whitespace wrapping, but it looks like it's still happening for end whitespace at `settings.json`. This seems like a GPUI bug, but for now I think it's okay to have no whitespace at all in the codeblock. That's what we do in other places.

```suggestion
            backup_file_name)
```

**Review by smitbarmase — CHANGES_REQUESTED** [review]
Thanks, this looks far better. I just added a few nitpicks.

But before that, I'm worried about the case where the pane width is extremely low and the banner seems to take all the height of the pane. I suppose this can be fixed by implementing `Element` and adding some conditional logic at paint stage by checking layout to hide this banner based on height. 

Ref: https://github.com/zed-industries/zed/blob/e9026d6a933db29c50548f540b07166d400b2b5f/crates/editor/src/element.rs#L6991

Not sure if you are willing to do that, as it seems like a lot of work. Let me know if you'd like me to pick up from here. I would be happy to do so.

**Comment by kmpeeduwee** [comment]
@smitbarmase Thanks a lot for the helpful review — it really helped me!

I agree that implementing the Element logic sounds like a bigger change, and I’m probably not ready to tackle that at the moment. I’ve addressed all the other comments you left and pushed the fixes. Let me know if there’s anything else I should look into!

**Comment by smitbarmase** [comment]
Thank you so much for your work @kmpeeduwee, I'm gonna take it from here.

**Review by smitbarmase — APPROVED** [review]
I found a simpler fix to handle that case than what I suggested earlier.
