### PR TITLE
util: Fix `failed to load env variables` on Windows when users have custom terminal shell args 

### LINKED ISSUE #46933: Zed update broke my Go, then my D
### Reproduction steps

Original message:
I just updated to 0.218.6 yesterday and it immediately broke my GO environment by no longer loading my envs and tlling me it cannot find Go (see attached photo). Reverting back to the last version fixesthe issue. I already gave it permission to all my  projects and tried adding the session:worktrees trust setting but to no avail. Anyone else had to deal with this?
Update: 1:
Latest version that doesn't have the issue is 0.217.4. I've recently moved on from Go to D. On that version there's not issue with D.  I just ran the Check for Updates.  It just updated to 0.218.7.  Immediately said Could not load environment variables. Attached is a .jpg of the error and a truncated version of my Zed.log after I restarted Zed (and erased the previous log). I have to downgrade again now.

Image
Update 2:
 I just tried Zed-x86_64-0.219.0.exe - same error (see attached log `Update 2`)
Update 3:
Ok, final test, I just tried the latest 0.219.4 - same error, only difference is the last line (see attached `log update 3`)

### Current vs. Expected behavior

Image

Image

Expected Behavior: is I should see neither the popup or that entry in my log file

The fact that everything works perfectly in the 0.217.4 version leads to be believe there's been a change that's cascading into the new versions that's causing the issue, something changed between 217.4 and the later versions causing this.

### Zed version and system specs

Zed: v0.217.4+stable.106.39c2ebc0db1d1436f3e77090261c77bd66056291 (Zed) 
OS: Windows 10.0.26200
Memory: 15.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1060 6GB || NVIDIA Corporation || 581.29 r581_07

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
(Original)
2026-01-08T10:15:07-05:00 ERROR [crates/languages/src/go.rs:437] no cached binary
2026-01-08T10:15:07-05:00 ERROR [crates/languages/src/go.rs:437] no cached binary
2026-01-08T10:15:07-05:00 ERROR [project::lsp_store] Failed to start language server "gopls": Could not install the Go language server `gopls`, because `go` was not found.

(Update 1)
2026-01-12T22:03:55-05:00 INFO  [zed] ========== starting zed version 0.218.7+stable.118.41bab92dac34777ae4256e5041f7b7236fd16cdd, sha 41bab92 ==========
2026-01-12T22:03:55-05:00 INFO  [gpui::platform::windows::directx_devices] Using GPU: NVIDIA GeForce GTX 1060 6GB
2026-01-12T22:03:55-05:00 INFO  [gpui::platform::windows::directx_devices] Created device with Direct3D 11.1 feature level.
2026-01-12T22:03:55-05:00 INFO  [gpui::platform::windows::direct_write] Use Segoe UI as UI font.
2026-01-12T22:03:55-05:00 INFO  [crashes] spawning crash handler process
2026-01-12T22:03:55-05:00 INFO  [crashes] connected to crash handler process after 100ms
2026-01-12T22:03:55-05:00 INFO  [extension_host] extensions updated. loading 8, reloading 0, unloading 0
2026-01-12T22:03:55-05:00 INFO  [crashes] crash handler registered
2026-01-12T22:03:55-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:03:55-05:00 INFO  [client] set status on client 0: Authenticating
2026-01-12T22:03:55-05:00 INFO  [workspace] Rendered first frame
2026-01-12T22:03:55-05:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1060 6GB", driver_name: "NVIDIA Corporation", driver_info: "581.29 r581_07" }
2026-01-12T22:03:55-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:03:55-05:00 INFO  [util::shell] Found powershell in: C:\Program Files\PowerShell\7\pwsh.exe
2026-01-12T22:03:55-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:03:56-05:00 INFO  [alacritty_terminal::tty::windows::conpty] Using conpty.dll for pseudoconsole
2026-01-12T22:03:56-05:00 WARN  [language] unrecognized capture name 'test.inside' in D textobjects TreeSitter query
2026-01-12T22:03:56-05:00 WARN  [language] unrecognized capture name 'test.around' in D textobjects TreeSitter query
2026-01-12T22:03:56-05:00 WARN  [language] unrecognized capture name 'parameter.inside' in D textobjects TreeSitter query
2026-01-12T22:03:56-05:00 INFO  [client] set status on client 320221: Authenticated
2026-01-12T22:03:57-05:00 ERROR [project::environment] Failed to load shell environment for directory "C:\\Users\\virgil\\Documents\\Syncs\\D": capturing shell environment with "C:\\Windows\\System32\\cmd.exe": Failed to deserialize environment variables from json: {
  <here it showsthe current contentsof my $PATH...cut out for brevity>
}

C:\Users\virgil\AppData\Local\Programs\Zed>: trailing characters at line 112 column 1
(Update 2)
2026-01-12T22:09:57-05:00 INFO  [zed] ========== starting zed version 0.219.0+preview.111.0b9c12581f0f06d266dbe1a3703e954662bd03e4, sha 0b9c125 ==========
2026-01-12T22:09:57-05:00 INFO  [gpui::platform::windows::directx_devices] Using GPU: NVIDIA GeForce GTX 1060 6GB
2026-01-12T22:09:58-05:00 INFO  [gpui::platform::windows::directx_devices] Created device with Direct3D 11.1 feature level.
2026-01-12T22:09:58-05:00 INFO  [gpui::platform::windows::direct_write] Use Segoe UI as UI font.
2026-01-12T22:09:58-05:00 INFO  [crashes] spawning crash handler process
2026-01-12T22:09:58-05:00 INFO  [sqlez::migrations] Found 9 foreign key relationships to check
2026-01-12T22:09:58-05:00 INFO  [crashes] connected to crash handler process after 100ms
2026-01-12T22:09:58-05:00 INFO  [crashes] crash handler registered
2026-01-12T22:09:58-05:00 INFO  [extension_host] extensions updated. loading 8, reloading 0, unloading 0
2026-01-12T22:09:58-05:00 INFO  [client] set status on client 0: Authenticating
2026-01-12T22:09:58-05:00 INFO  [crates/workspace/src/workspace.rs:3167] Couldn't find any enabled panel for the Left dock.
2026-01-12T22:09:58-05:00 INFO  [workspace] Rendered first frame
2026-01-12T22:09:58-05:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1060 6GB", driver_name: "NVIDIA Corporation", driver_info: "581.29 r581_07" }
2026-01-12T22:09:58-05:00 INFO  [sqlez::migrations] Found 10 foreign key relationships to check
2026-01-12T22:09:58-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:09:58-05:00 INFO  [sqlez::migrations] Found 10 foreign key relationships to check
2026-01-12T22:09:58-05:00 INFO  [sqlez::migrations] Found 11 foreign key relationships to check
2026-01-12T22:09:58-05:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 64 to 256
2026-01-12T22:09:59-05:00 INFO  [client] set status on client 320221: Authenticated
2026-01-12T22:10:02-05:00 INFO  [sqlez::migrations] Found 12 foreign key relationships to check
2026-01-12T22:10:11-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:10:11-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:10:11-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:10:11-05:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2026-01-12T22:10:11-05:00 INFO  [project::lsp_store] Waiting for worktree "C:\\Users\\virgil\\AppData\\Roaming\\Zed\\settings.json" to be trusted, before starting language server json-language-server
2026-01-12T22:10:11-05:00 INFO  [sqlez::migrations] Found 17 foreign key relationships to check
2026-01-12T22:10:11-05:00 INFO  [gpui::platform::windows::directx_renderer] Updating subpixel_sprite_pipeline buffer size from 512 to 1024
2026-01-12T22:10:11-05:00 INFO  [gpui::platform::windows::directx_renderer] Updating subpixel_sprite_pipeline buffer size from 1024 to 4096
2026-01-12T22:10:12-05:00 ERROR [project::environment] Failed to load shell environment for directory "C:\\Users\\virgil\\AppData\\Roaming\\Zed": capturing shell environment with "C:\\Windows\\System32\\cmd.exe": Failed to deserialize environment variables from json: {
  <my $PATH statements>
}

C:\Users\virgil\AppData\Local\Programs\Zed Preview>: trailing characters at line 111 column 1
(Update 3)
C:\Users\virgil\AppData\Local\Programs\Zed Preview>: trailing characters at line 112 column 1
```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by AmaanBilwar**
Closes #46933 

Before you mark this PR as ready for review, make sure that you have:
- [x] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [x] NO UI CHANGES

Release Notes:
- Fixed `Failed to load shell environment` errors on Windows when users have custom terminal shell arguments configured (e.g., cmd.exe with `/k echo Hello` or similar startup commands)

### CODE REVIEW

File: crates/util/src/shell_env.rs [hunk 1]
```diff
@@ -199,14 +257,10 @@ async fn capture_windows(
...
-            "/c",
-            "cd",
-            &directory_string,
-            "&&",
-            &zed_path_string,
-            "--printenv",
-        ]),
+        ShellKind::Cmd => {
+            let dir = directory_string.trim_end_matches('\\');
+            cmd.args(["/d", "/c", "cd", dir, "&&", &zed_path_string, "--printenv"])
```
Comment (Veykril) [inline crates/util/src/shell_env.rs:229]: Why the change to use `/d`?

**Review by Veykril — COMMENTED** [review]
This seems to be a lot of complexity for a weird problem to solve. It would be fine to imo to scan through the string until the first opening brace and start parsing from there but anything else we shouldn't really bother with here. Unconditionally printing to the terminal on startup can break a bunch of stuff anyways (an example being connecting to a remote host).

File: crates/util/src/shell_env.rs (hunk 1 above)
Comment (AmaanBilwar) [reply crates/util/src/shell_env.rs:229]: `/d` disables AutoRun commands from executing.

these autorun commands execute every time cmd starts and they say `hello` in our case. by passing `/d` cmd runs ina  clean stat without any side effects during env capture

File: crates/util/src/shell_env.rs [hunk 2]
```diff
@@ -164,7 +173,7 @@ async fn capture_windows(
             .unwrap_or_else(|| value.to_owned())
     };
     let mut cmd = crate::command::new_command(shell_path);
-    cmd.args(args);
+    // Ignore user-provided shell args - use our own commands for env capture.
```
Comment (Veykril) [inline crates/util/src/shell_env.rs]: not sure if i missed this in my first review but I am not sure we can do this, some user setups might be relying on this?

**Review by Veykril — APPROVED** [review]
Thanks!
