### PR TITLE
Fix project symbol picker UTF-8 highlight panic

### LINKED ISSUE #53479: Crash while searching for project symbol(cmd+t) when typing Korean
[crash-report.txt](https://github.com/user-attachments/files/26588553/crash-report.txt)

### Reproduction steps

1. Start Zed
2. Cmd+T to find project symbols
3. Type any korean letter(ex) 안녕)

### Zed version and system specs

Zed version
- Zed 0.231.1 
- e71b6aa44ffaac9bdaf986288289359e6f1b3572
- 0.231.1+stable.213.e71b6aa44ffaac9bdaf986288289359e6f1b3572

OS
- MacOS Sequoia 1.56(beta, 24G5074c) 

Memory
- 36GB

Architecture
- Apple Silicon (arm64)

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2026-04-09T12:55:58+09:00 INFO  [lsp] Language server with id 5 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "basedpyright language server 1.39.0 starting"
}
2026-04-09T12:55:58+09:00 INFO  [lsp] Language server with id 5 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/bluesignum/Library/Application%20Support/Zed/languages/basedpyright/node_modules/basedpyright/dist"
}
2026-04-09T12:55:58+09:00 INFO  [lsp] starting language server process. binary path: "/Users/bluesignum/Library/Application Support/Zed/node/node-v24.11.0-darwin-arm64/bin/node", working directory: "/Users/bluesignum/Desktop/development/lime-ai-backend", args: ["/Users/bluesignum/Library/Application Support/Zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2026-04-09T12:55:58+09:00 INFO  [lsp] Language server with id 9 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "basedpyright language server 1.38.2 starting"
}
2026-04-09T12:55:58+09:00 INFO  [lsp] Language server with id 9 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/bluesignum/Desktop/development/panora_backend/.venv/lib/python3.12/site-packages/basedpyright/dist"
}
2026-04-09T12:55:59+09:00 INFO  [lsp] Language server with id 7 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Setting up server…"
}
2026-04-09T12:55:59+09:00 INFO  [lsp] Language server with id 7 sent unhandled notification window/logMessage:
{
  "type": 4,
  "message": "Listening for messages…"
}
2026-04-09T12:55:59+09:00 INFO  [lsp] starting language server process. binary path: "/Users/bluesignum/Library/Application Support/Zed/extensions/work/proto/buf-v1.67.0/buf", working directory: "/Users/bluesignum/Desktop/development/lime-ai-backend", args: ["lsp", "serve"]
2026-04-09T12:55:59+09:00 ERROR [lsp] error deserializing workspace/configuration request: Error("relative URL without a base", line: 0, column: 0)
2026-04-09T12:55:59+09:00 ERROR [lsp] error deserializing workspace/configuration request: Error("relative URL without a base", line: 0, column: 0)
2026-04-09T12:56:02+09:00 INFO  [project::lsp_store] language server 9: unregistered workspace/DidChangeWatchedFiles capability with id 9a2337cb-2c5d-428a-82a2-8876405eafcb
2026-04-09T12:56:04+09:00 INFO  [project::lsp_store] language server 5: unregistered workspace/DidChangeWatchedFiles capability with id 23e18b70-3d28-4d81-8033-25d0669e5585
2026-04-09T12:57:59+09:00 ERROR [lsp] Cancelled LSP request task for "initialize" id 0 which took over 120s
2026-04-09T12:57:59+09:00 ERROR [lsp] Cancelled LSP request task for "initialize" id 0 which took over 120s
2026-04-09T12:57:59+09:00 ERROR [project::lsp_store] Failed to start language server "typos": initializing server typos, id 16

Caused by:
    Request timed out
2026-04-09T12:57:59+09:00 ERROR [project::lsp_store] server stderr: 
thread 'main' (44834381) panicked at crates/typos-lsp/src/config.rs:7:5:
Expected a directory that might contain a configuration file, got "/Users/bluesignum/.config/zed/settings.json"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2026-04-09T12:57:59+09:00 ERROR [project::lsp_store] Failed to start language server "typos": initializing server typos, id 18

Caused by:
    Request timed out
2026-04-09T12:57:59+09:00 ERROR [project::lsp_store] server stderr: 
thread 'main' (44834391) panicked at crates/typos-lsp/src/config.rs:7:5:
Expected a directory that might contain a configuration file, got "/Users/bluesignum/.config/zed/settings.json"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2026-04-09T12:57:59+09:00 ERROR [crates/lsp/src/lsp.rs:531] cannot read LSP message headers
2026-04-09T12:57:59+09:00 ERROR [lsp] Server reset connection for a request "shutdown" id 1
2026-04-09T12:57:59+09:00 WARN  [lsp] language server typos (id 16) closed the shutdown request connection
2026-04-09T12:57:59+09:00 ERROR [crates/lsp/src/lsp.rs:558] Broken pipe (os error 32)
2026-04-09T12:57:59+09:00 ERROR [crates/lsp/src/lsp.rs:531] cannot read LSP message headers
2026-04-09T12:57:59+09:00 ERROR [lsp] Server reset connection for a request "shutdown" id 1
2026-04-09T12:57:59+09:00 WARN  [lsp] language server typos (id 18) closed the shutdown request connection
2026-04-09T12:57:59+09:00 ERROR [crates/lsp/src/lsp.rs:558] Broken pipe (os error 32)
```

</details>

### PR DESCRIPTION
**Pull request by Anthony-Eid**
This panic was caused because we incorrectly assumed that each character was one byte when converting character indices to highlight range byte indices.

Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #53479

Release Notes:

- Fix a panic that could occur in the project symbol search picker

### CODE REVIEW

File: crates/project_symbols/src/project_symbols.rs [hunk 1]
```diff
@@ -288,7 +288,14 @@ impl PickerDelegate for ProjectSymbolsDelegate {
...
             .iter()
-            .map(|pos| (*pos..pos + 1, highlight_style));
+            .filter_map(|position| {
+                label.get(*position..).and_then(|suffix| {
+                    suffix.chars().next().map(|character| {
+                        (*position..*position + character.len_utf8(), highlight_style)
+                    })
+                })
+            })
+            .collect::<Vec<_>>();
```
Comment (Veykril) [inline crates/project_symbols/src/project_symbols.rs]:
```suggestion
            .map(|pos| (*pos..label.ceil_char_boundary(pos + 1), highlight_style))
```
should do the trick I think?

**Review by Veykril — APPROVED** [review]
