### PR TITLE
assistant: Fix `"New Context"` behavior when focused in editor

### LINKED ISSUE #16676: Assistant New Context button / new file mixed behavior depending on area focus
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

# Issue

When the Assistant panel is not focused, and the + (New Context) button is pressed at the top right of the assistant panel, instead of opening a new context, a new untitled file is opened in the file editor area. Also, If the assistant panel is focused, using the new file command opens a new context. This seems confusing and there should maybe be a separate command for new context / new file. It seems currently adding a new context uses the same command as adding a new file and the area focus decides if it creates a new file / new context.

 ## To Reproduce

- Click somewhere out of the assistant panel such as the text editor area or file tree area, then click the + (New Context) button in the assistant panel. A new file opens when you would expect a new Assistant Context to open. (See first screen recording below)
- Click to focus the Assistant Panel, then run the new file command. A new Assistant Context opens when you would expect a new untitled file to be created. (See second screen recording below)

## Fix

I think it would make sense to separate the new context and new file functionalities into unique commands. This would involve adding a new command for the new context, as there doesn't seem to be one now.

I have been wanting to start contributing, this seems like it could be a good first issue for me if help is wanted here.

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/2d3db351-ca82-48ce-b6d0-e7f407a52300

https://github.com/user-attachments/assets/82be8fa9-cbaa-46aa-a06b-19f74ae1f127

> 

> 

### If applicable, attach your Zed.log file to this issue.

N/A

### PR DESCRIPTION
**Pull request by ramipellumbi**
Closes #16676

Release Notes:

- assistant: fix `New Context` opening a new file when focused in the editor pane.

### CODE REVIEW

**Comment by ramipellumbi** [comment]
@cla-bot check

File: crates/assistant/src/assistant_panel.rs [hunk 1]
```diff
@@ -79,6 +80,34 @@ use workspace::{
 use workspace::{searchable::SearchableItemHandle, NewFile};
 use zed_actions::InlineAssist;
 
+pub struct NewContext;
+
+impl Action for NewContext {
```
Comment (maxdeviant) [inline crates/assistant/src/assistant_panel.rs:85]: We'll want to use the `gpui::actions!` macro to define the `Action` instead of writing out an `impl` by hand.

Comment (ramipellumbi) [reply crates/assistant/src/assistant_panel.rs]: I implemented this -- but noticed the only place that macro is uses is in the `actions.rs` of `Editor`. What is the best place for this?

File: crates/assistant/src/assistant_panel.rs [hunk 2]
```diff
@@ -911,6 +926,12 @@ impl AssistantPanel {
             });
 
             self.show_context(editor.clone(), cx);
+            self.pane.update(cx, |pane, cx| {
```
Comment (ramipellumbi) [inline crates/assistant/src/assistant_panel.rs:929]: This allows us to focus the cursor on the new context when opened while focused in the editor. Depending on desired behavior, we can omit this.

As it is now, new contexts will always open on the far right most tab.

1. If focused in editor, and new context is opened, open the new context with cursor focused in it.
2. If focused in context, open a new context and focus on it.

Without this line, new contexts open to the immediate right of the current context:

1. If focused in editor, and new context is opened, open the new context with cursor remaining focused in editor.
2. If focused in context, open a new context to the immediate right and focus on it.

File: crates/assistant/src/assistant_panel.rs (hunk 1 above)
Comment (maxdeviant) [reply crates/assistant/src/assistant_panel.rs]: It should probably go with the rest of the assistant actions:

https://github.com/zed-industries/zed/blob/89487772b021d31e49a608934bff226b631d5870/crates/assistant/src/assistant.rs#L53-L68

Comment (ramipellumbi) [reply crates/assistant/src/assistant_panel.rs]: Missed this, thank you!

File: crates/assistant/src/assistant_panel.rs [hunk 3]
```diff
@@ -911,6 +924,15 @@ impl AssistantPanel {
...
             self.show_context(editor.clone(), cx);
+            let workspace = self.workspace.clone();
+            cx.spawn(move |_, mut cx| async move {
+                workspace
+                    .update(&mut cx, |workspace, cx| {
+                        workspace.focus_panel::<AssistantPanel>(cx);
+                    })
+                    .ok();
+            })
+            .detach();
```
Comment (ramipellumbi) [inline crates/assistant/src/assistant_panel.rs:935]: This allows us to: 
1. keep the current new tab behavior (new tab is to the immediate right of the current open context)
2. move the cursor focus to the new context

**Comment by ramipellumbi** [comment]
Ok -- done making commits. Juxtaposing the diff against the codebase as I looked further into it inspired some more changes as to how this should be completed. Let me know if anything else remains!

**Comment by osiewicz** [comment]
Thank you so much!
