### PR TITLE
Fix panic dragging tabs multiple positions to the right

### LINKED ISSUE #32303: dragging tabs around crashes Zed
### Summary

Dragging tabs to the right and left several times crashes Zed

### Description

Steps to trigger the problem:
1. Grab a tab and drag to the right
2. Gragb another tab and drag to the left
3. Repeat 1-2 times and Zed crashes

Actual Behavior:
Expected Behavior:
Tabs drag without crashing

### Zed Version and System Specs

Zed: v0.190.2 (Zed Preview) 
OS: macOS 15.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log

[crash-report.txt](https://github.com/user-attachments/files/20639221/crash-report.txt)

```

</details>

### PR DESCRIPTION
**Pull request by JosephTLyons**
Closes https://github.com/zed-industries/zed/issues/32303

Release Notes:

- Fixed a panic that occurred when dragging tabs multiple positions to the right (preview only)

### CODE REVIEW

File: crates/workspace/src/pane.rs [hunk 1]
```diff
@@ -2924,12 +2924,9 @@ impl Pane {
...
                             let ix = if moved_right { ix - 1 } else { ix };
                             let is_pinned_in_to_pane = this.is_tab_pinned(ix);
-                            let is_at_same_position = ix == from_ix;
 
-                            if is_at_same_position
-                                || (moved_right && is_pinned_in_to_pane)
-                                || (!moved_right && !is_pinned_in_to_pane)
-                                || (!moved_right && was_pinned_in_from_pane)
+                            if (was_pinned_in_from_pane && is_pinned_in_to_pane)
+                                || (!was_pinned_in_from_pane && !is_pinned_in_to_pane)
```
Comment (JosephTLyons) [inline crates/workspace/src/pane.rs:2929]: I generalized the logic around skipping updating the pinned tab count when moving tabs within the same pane. This feels more sound than what I had last.
