### PR TITLE
deepseek: Fix API URL

### LINKED ISSUE #33904: AI: deepseek custom api_url is not work when use other provider
### Summary

deekseek custom is not work

### Description

Steps to trigger the problem:
1. open setttings.json, add deepseek to language_models
2. api_url is privide from volcengine, like: https://ark.cn-beijing.volces.com/api/v3
3. at text thread, write any prompt, click send

**Expected Behavior**:
request model successfully
**Actual Behavior**:
Failed to connect to DeepSeek API: 404 Not Found

### Model Provider Details
- Provider:DeepSeek via custom
- Model Name: any
- Mode: any
- Other Details (MCPs, other settings, etc):

Image

I found that this issue is due to the fact that v1 in v1/chat/completions is not a convention of the OpenAI compatible interface, so removing v1 should be ok.

Image

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by Justyer**
Closes #33904 

Release Notes:

- Add support for custom API Urls for DeepSeek Provider

### CODE REVIEW

**Comment by Justyer** [comment]
@cla-bot check

File: crates/deepseek/src/deepseek.rs [hunk 1]
```diff
@@ -263,7 +263,7 @@ pub async fn stream_completion(
     api_key: &str,
     request: Request,
 ) -> Result<BoxStream<'static, Result<StreamResponse>>> {
-    let uri = format!("{api_url}/v1/chat/completions");
+    let uri = format!("{api_url}/chat/completions");
```
Comment (imumesh18) [inline crates/deepseek/src/deepseek.rs:266]: can we change the `pub const DEEPSEEK_API_URL: &str = "https://api.deepseek.com/v1";` as well. Not sure changing the default is ideally what you want to do here. That way custom url is also resolved and we wouldn't have changed the default url.

Comment (Justyer) [reply crates/deepseek/src/deepseek.rs:266]: image
The official documentation states that both https://api.deepseek.com/v1 and https://api.deepseek.com/ are valid.

Comment (imumesh18) [reply crates/deepseek/src/deepseek.rs:266]: But the code which is there in deepseek is based upon the openai compatible api request and response. So technically we should be using the [api.deepseek.com/v1](https://api.deepseek.com/v1) api as default.

Comment (Justyer) [reply crates/deepseek/src/deepseek.rs:266]: Alright, I've already updated it.

**Comment by bennetbo** [comment]
@Justyer We should also update the api_url here: https://github.com/zed-industries/zed/blob/955580dae6f8e9faf8a64d145f287d3710c08c11/assets/settings/default.json#L1679

(GitHub won't let me push to your branch)

**Review by bennetbo — APPROVED** [review]

**Comment by bennetbo** [comment]
Thanks!
