### PR TITLE
x11: Differentiate between mouse and keyboard focus

### LINKED ISSUE #13897: linux/x11: Cursor style doesn't update when application not focused
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Have Zed and another application open beside each other.
2. Click on Zed to focus it.
3. Hover over the border of Zed, so that the icon changes to the resize icon.
4. Click on the other app to focus it.
5. Hover over Zed without focusing it.
6. The icon will still be the resize icon and not update until you focus Zed.

**OR**:

1. Have Zed and another application open beside each other.
2. Click on Zed to focus to.
3. Hover over an element with a unique icon.
4. Alt-tab to the other application.
5. Now the cursor will not update (while hovering over Zed) until you re-focus Zed.

@mrnugget  I haven't bisected it, but it smells a lot like something from https://github.com/zed-industries/zed/pull/13646.

### Environment

Gnome native X11. Kernel: 6.6.37

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by apricotbucket28**
Fixes https://github.com/zed-industries/zed/issues/13897

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 1]
```diff
@@ -558,19 +565,19 @@ impl X11Client {
                 let window = self.get_window(event.window)?;
                 window.refresh();
             }
-            Event::FocusIn(event) => {
+            Event::FocusIn(event) if event.mode == xproto::NotifyMode::NORMAL => {
```
Comment (apricotbucket28) [inline crates/gpui/src/platform/linux/x11/client.rs:568]: I added these `if`s since the XinputLeave handler did the same, and from what I've read it seems like a good idea to do so.

**Comment by ConradIrwin** [comment]
Thanks!
