### PR TITLE
editor: Support rewrap in block comments

### LINKED ISSUE #18221: Rewrap doesn't work on multi-line comments in C files
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Thanks for adding the new re-wrap command! I tried it out on a C file, but it only seems to work on single-line comments, e.g.
```
// we can triangulate any convex polygon by picking a vertex and connecting it to the next two vertices; we first read two vertices, and then, for every subsequent vertex, we can form a triangle by connecting it to the first and previous vertex
```
For multi-line comments, such as the following, no wrapping is performed:
```
/* we can triangulate any convex polygon by picking a vertex and connecting it to the next two vertices; we first read two vertices, and then, for every subsequent vertex, we can form a triangle by connecting it to the first and previous vertex */
```

### Environment

Zed: v0.155.0 (Zed Dev 05d18321db59539b56520d25f2ee95850ad911fd)
OS: Windows 10.0.19045
Memory: 15.9 GiB
Architecture: x86_64
GPU: Radeon Pro 555X || AMD proprietary driver || 21.30.45.18

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### LINKED ISSUE #19794: Rewrap not working with multi-line comment blocks in TypeScript
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In TypeScript, the `Editor::Rewrap` command works with single-line comments grouped together, but not with multi-line comment blocks.

```ts
/**
 * Multi-line comment block that should be split into two lines when Editor::Rewrap is used.
 */

// Single-line comments grouped together are properly split when Editor::Rewrap is used.
// Give it a try.
```

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.4.1
Memory: 20 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by claytonrcarter**
This updates `editor: rewrap` to work within doc comments, based on the code that extends such comments on newline. I added some tests, and I've tested it out in JS, C and PHP. (Though PHP depends on https://github.com/zed-extensions/php/pull/40) 

Closes #19794
Closes #18221

**Caveat:**
~~This will not rewrap an existing single-line block comment, such as the one provided in #18221:~~ this will now rewrap as expected
```c
/* we can triangulate any convex polygon by picking a vertex and connecting it to the next two vertices; we first read two vertices, and then, for every subsequent vertex, we can form a triangle by connecting it to the first and previous vertex */
```
However, it will rewrap a similar comment if it is shaped like a doc comment. In other words, this will rewrap as expected:
```c
/* 
 * we can triangulate any convex polygon by picking a vertex and connecting it to the next two vertices; we first read two vertices, and then, for every subsequent vertex, we can form a triangle by connecting it to the first and previous vertex 
 */
```

This seems like a reasonable improvement and limitation to me, especially as a first step.

cc @smitbarmase because I think that you've been making a lot of the `newline` and `rewrap` changes recently. (Thank you for those, by the way!)

Release Notes:

- Added support for rewrap in block comments.

### CODE REVIEW

File: crates/editor/src/editor_tests.rs [hunk 1]
```diff
@@ -5667,6 +5667,118 @@ async fn test_rewrap(cx: &mut TestAppContext) {
...
+            LanguageConfig {
+                name: "Rust".into(),
+                line_comments: vec!["// ".into()],
+                block_comment: Some(("/*".into(), "*/".into())),
+                documentation: Some(DocumentationConfig {
+                    start: "/**".into(),
+                    end: "*/".into(),
+                    prefix: "* ".into(),
+                    tab_size: NonZeroU32::new(1).unwrap(),
+                }),
```
Comment (claytonrcarter) [inline crates/editor/src/editor_tests.rs]: This test fn could easily be inclined into the other `test_rewrap` fn, but I kept it separate here because I had to add this `documentation` config, which is only relevant to these test cases.

File: crates/editor/src/editor.rs [hunk 2]
```diff
@@ -11614,11 +11614,23 @@ impl Editor {
...
                         if let Some(language_scope) = &language_scope {
                             let indent_end = Point::new(row, indent.len);
-                            let comment_prefix = language_scope
-                                .line_comment_prefixes()
-                                .iter()
-                                .find(|prefix| buffer.contains_str_at(indent_end, prefix))
-                                .map(|prefix| prefix.to_string());
+
+                            let start_point = selection.start.to_point(&buffer);
+                            let is_within_block_comment = buffer
```
Comment (smitbarmase) [inline crates/editor/src/editor.rs]: We might not this check here, simply checking for three type of prefixes (start of doc block, middle prefix, end of doc block) should be fine, along with existing line comment prefix we are checking.

File: crates/editor/src/editor_tests.rs [hunk 3]
```diff
@@ -5667,6 +5667,118 @@ async fn test_rewrap(cx: &mut TestAppContext) {
...
+            Some(tree_sitter_rust::LANGUAGE.into()),
+        )
+        .with_override_query("[(block_comment)] @comment.inclusive")
+        .unwrap(),
+    );
+
+    // regular block comment
+    assert_rewrap(
+        indoc! {"
+            /*
```
Comment (smitbarmase) [inline crates/editor/src/editor_tests.rs:5935]: I believe we should also cover the single-line case. Additionally, when the text spans multiple lines, we should be able to rewrap even when the selection includes the start and end delimiters.

**Review by smitbarmase — CHANGES_REQUESTED** [review]

File: crates/editor/src/editor.rs (hunk 2 above)
Comment (claytonrcarter) [reply crates/editor/src/editor.rs]: This is a little tricky because the current code only looks at the current line, but a line that looks like `* foo` may not be part of a comment, so we would have to expand our search to previous lines to confirm that it comes after an opening `/*`. Also, it would introduce some ambiguity about precedence of what type of line/comment we're on because for example `// foo */` would need to treated differently than `* foo */`. So, I'm inclined to keep the `if is_within_block_comment`.

Comment (smitbarmase) [reply crates/editor/src/editor.rs]: I understand. In that case, I wonder if instead of checking `is_within_block_comment` for `selection.start`, we should check it per line basis? For instance, let’s consider the current code and see what happens when you have something like this selected:

```
/**
 *
 */
 //
 //  <-- even for this row, it would detect `comment_prefix` as `doc_config.prefix`?
```

However, even before that, I believe we should make a clear distinction between doc comment blocks and regular comment blocks so that they can be categorized into two ranges in the above case for the `wrap_ranges`.

This would also take care of my second comment about selection including the start and end delimiters of the block comment block.

Comment (claytonrcarter) [reply crates/editor/src/editor.rs]: > something like this selected

I'll look into this and add a test for it.

> make a clear distinction between doc comment blocks and regular comment blocks

I was going to mention this. `block_comment` in lang settings currently doesn't record a comment `prefix`, while `documentation` does. I was going to suggest that we combine these settings somehow, but I didn't want to do so w/o understanding how they're used (I haven't looked at that yet). I was thinking of
```diff
- block_comment = ["/*", "*/"]
- documentation = { start = "/**", end = "*/", prefix = "* ", tab_size = 1 }
+ block_comment = { start = ["/*", "/**"], end = "*/", prefix = "* ", tab_size = 1 }
```
or 
```diff
+ block_comments = [
+   { start = "/*", end = "*/", prefix = "* ", tab_size = 1 },
+   { start = "/**", end = "*/", prefix = "* ", tab_size = 1 }
+ ]
```
Do you think that either of those are worth pursuing?

I have also been thinking about changing this to work on tree-sitter `comment` syntax node ranges when there is no selection, which may help us to differentiate between `/*\n* foo` and `/**\n* foo` if we are only examining line by line (because we may have go back track to find out which leading delimiter is in use). I had tried this in an earlier implementation, and it worked well as I recall, but the changes you've made since then made it unnecessary for the current implementation here.

Comment (smitbarmase) [reply crates/editor/src/editor.rs]: Yes, that config seems like it’s worth pursuing before we start to work on this PR. Because, in the absence of that prefix, we might end up rewrapping `*` in text itself, which might still be happening but now that we are supporting block/doc comments might as well do it properly. 

I think you will have to make changes only in `editor.rs` where we handle using it in `newline` and `toggle_comments`, but it doesn't necessarily mean you have to use "prefix" there as well for now. It can be simple syntax changes. And, later most of the work will be to update extensions to use that new config. Note, because this will be a breaking language config change, extensions need to specify schema_version so we don't end up breaking it by updating extensions for users who are on an old version of Zed https://github.com/zed-industries/zed/blob/c0261a1ea9c380b59c914c7dc6304add40496e24/crates/extension_host/src/extension_host.rs#L76

Comment (claytonrcarter) [reply crates/editor/src/editor.rs]: OK, I have these changes to working locally. I did not go w/ the vec syntax because in all cases that we know about at this time, languages have only a single `block_comment` and `documentation_comment`, so the ability to list an arbitrary number of comments felt like overkill.

Should I push the changes to extension config to a separate PR, or is it OK to bundle with this one?

I have also expanded the tests for `rewrap` and that is working with the new block/doc comment config. I have some more cleanup left to do, but this is feeling good.

Comment (smitbarmase) [reply crates/editor/src/editor.rs]: Let's make it different PR, so that we can merge it right away and make the required extension changes. We can rebase the updated main on this one afterwards.

Comment (claytonrcarter) [reply crates/editor/src/editor.rs]: OK, that's in #34861. I'll mark this as draft while that is settled.

File: crates/editor/src/editor_tests.rs (hunk 3 above)
Comment (claytonrcarter) [reply crates/editor/src/editor_tests.rs:5935]: > also cover the single-line case.

This is now working...

> when the text spans multiple lines, we should be able to rewrap even when the selection includes the start and end delimiters

... but this is not (yet). I have some tests in place, but no code yet.

Comment (smitbarmase) [reply crates/editor/src/editor_tests.rs:5935]: If you want, I can take a look at handling those edge cases. Not sure when, maybe end of this week or next week. Let me know if you want to tackle it yourself instead.

Comment (claytonrcarter) [reply crates/editor/src/editor_tests.rs:5935]: > handling those edge cases

The more I work on this, the more edge cases I find. They're everywhere! 😆 

The previous implementation was using this snippet:
```rs
let is_within_block_comment = buffer
    .language_scope_at(indent_end)
    .is_some_and(|scope| scope.override_name() == Some("comment"));
```
And it turns out that this is not doing what I thought it was: it is more correctly named `is_within_comment_override` because it's not checking if we are in a block comment, but if we are in a syntax node that the lang scope has overridden as "comment". This depends on each lang and many seem to override all comments as "comment", not just block comments. I found this because this branch seemed to be rewrapping correctly in block/doc comments, but it had stopped working on line comments.

I've fixed this, but things are starting to feel messy:
- if the lang has overrides for comments (eg Rust, C, C++, PHP, Python), we have to check for block, doc *and* line comment formats
- if the lang doesn't have overrides for comments (eg Bash, YAML, JSON), we can't check for block and doc comments (because we maybe can't trust that `* foo` is part of a comment), but we still have to check for line comments

This is not a huge deal, but – since we still work line by line – it leaves us w/ some edge cases like these:
```
/*
 //ˇ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mollis elit purus, a ornare lacus gravida vitae.
 */
/*
 //ˇ Lorem ipsum dolor sit amet, consectetur adipiscing elit. */
```
being rewrapped to these:
```
/*
 //ˇ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mollis elit
 // purus, a ornare lacus gravida vitae.
*/
/*
 * //ˇ Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 */
```
Again, edge-case-y but perhaps not not even a big deal.

One way to resolve this may be to inspect the actual tree-sitter syntax nodes. That may take some of the guess-work out of this, especially when working with block comments because it's trivial to get the contents of the entire node, and just that node.

Anyway, I'll push what I have for now and start looking at formatting selections that include the delimiters.

Comment (claytonrcarter) [reply crates/editor/src/editor_tests.rs:5935]: I looks like selections aren't *not* working. Selecting comments including the delimiters will rewrap correctly if the comments are somewhat separated. It's just when a selection contains multiple, abutting block comments that's failing. I've pushed some tests and I'll leave it there for the night.

Do you have any thoughts on how deep we should get into edge cases like this failing FIXME test I just pushed?

Comment (smitbarmase) [reply crates/editor/src/editor_tests.rs:5935]: Okay, so tree sitter doesn't give us type of comment, it simply treat all type of comments as same type of nodes. So, for given JavaScript code:

```js
// line comment

/** 
 * doc comment
 */
 
/*
 * block comment
 */

/** also doc comment */

/* also block comment */
```

It would simply give us this parse tree:

```
(program [0, 0] - [13, 0]
  (comment [0, 0] - [0, 15])
  (comment [2, 0] - [4, 3])
  (comment [6, 0] - [8, 3])
  (comment [10, 0] - [10, 23])
  (comment [12, 0] - [12, 24]))
```

But, we can retrieve ranges of these nodes and simply peek at the prefix to determine the type of comment. I think this will significantly simplify it. I pushed rough way to do it, feel free to mess around with that.

File: crates/editor/src/editor.rs [hunk 4]
```diff
@@ -11678,6 +11678,41 @@ impl Editor {
                         let is_within_comment_override = buffer
                             .language_scope_at(indent_end)
                             .is_some_and(|scope| scope.override_name() == Some("comment"));
+
+                        if let Some((_, range)) = buffer.syntax_ancestor(indent_end..indent_end) {
+                            let text_range = match range {
+                                MultiOrSingleBufferOffsetRange::Multi(r) => Some(r),
+                                MultiOrSingleBufferOffsetRange::Single(_) => None,
+                            };
+                            if let Some(range) = text_range {
```
Comment (smitbarmase) [inline crates/editor/src/editor.rs]: Maybe we don't even need to get buffer line, simply get text iter from this range, and check prefix directly. Because this range will always start with comment prefix (i.e. no whitespace in between).

File: crates/editor/src/editor_tests.rs (hunk 3 above)
Comment (claytonrcarter) [reply crates/editor/src/editor_tests.rs:5935]: > retrieve ranges of these nodes and simply peek at the prefix to determine the type of comment

In a previous iteration of this change – before I pushed this PR – I had been using tree-sitter syntax nodes, so I'll look at how I had been doing it before, too. As I recall, we can't even rely on just the current syntax node (ie the node in the current syntax layer) because of injected languages. For example, PHP and (I think) JS inject PHPDoc and JSDoc (resp) into doc comments, so the current node w/i that layer may not be the entire comment, but just a portion of it. But it wasn't difficult to examine all layers.

> treat all type of comments as same type of nodes

Mostly, yes, but not all. The Rust grammar, for example, differentiates between `line_comment`, `block_comment` and `doc_comment` nodes. 🙃 

> I pushed rough way to do it, feel free to mess around with that.

Thank you, will do!

Comment (smitbarmase) [reply crates/editor/src/editor_tests.rs:5935]: Nice catch about syntax layer, which should verify that. 

Nit: Could we extract the entire comment type detection logic into a separate method? It seems like we’d want to use `line_comment`, `block_comment`, and `doc_comment` nodes whenever available, otherwise, we should fall back to our syntax layer approach, which is quite a lot of code to be part of the rewrap impl.

**Comment by claytonrcarter** [comment]
Hi, I'm still working on this, chipping away slowly. There is a significant about of refactoring included now, because I'm currently thinking that we may be able to use the `range` of the syntax node in some way to optimize something, but I haven't gotten that far yet. If that optimization doesn't pan out, I think that some (maybe all) of the refactorings can be reverted. Anyway, just a quick status update.

**Comment by smitbarmase** [comment]
Hey, wonder if we should dial the scope so that we don't cover nested languages like Rust in Markdown just yet for rewrap. I'm not sure if it's even working in the current main, but it seems less of a priority or at least can be decoupled from this PR.

I haven't looked at the code changes for this yet, but I think it can be a separate PR where we explicitly test those cases with not just block comments, but other pieces that touch it.

**Comment by claytonrcarter** [comment]
OK great. I think that the non-tree-sitter version of this was working pretty well (well enough for others to try out on main, imo) except for some edge cases. 

I’ll be able to look at this again and revert the tree sitter changes next week.

**Comment by claytonrcarter** [comment]
OK, I think that I've probably taken this about as far as I can at this point. As far as I can tell, this seems to be working fine in day-to-day use. The places where it is still failing feel like edge cases that will involve additional parsing and/or some sort of tree-sitter/syntax node approach so that we can do a better job to of acting on single/specific block comments. I have added several tests that are producing undesirable output for these cases, all labeled with `FIXME` comments and a comment indicating their desired output, vs their actual output.

> dial the scope

Can you review the failing tests and see if these cases are reasonable "known issues" for a first pass? If so, I'll take one more glance at my diff to make sure I'm happy with it, clean up the lints, and we can maybe be ready to merge. If you think that these edge cases need to be fixed, then I think I should hand off the rest of this to you, because my free time for contributions has become restricted as of late.

Thank you for your patience on this!

File: crates/editor/src/editor_tests.rs [hunk 5]
```diff
@@ -5759,6 +5763,412 @@ async fn test_rewrap(cx: &mut TestAppContext) {
...
+             * consectetur adipiscing elit.
+             */
+            /*
+             *ˇ Lorem ipsum dolor sit amet */ /*
+             * consectetur adipiscing elit.
+             */
+        "},
+        rust_lang.clone(),
+        &mut cx,
+    );
```
Comment (claytonrcarter) [inline crates/editor/src/editor_tests.rs]: These are the "failing" tests that I mentioned in my other comment.

**Comment by smitbarmase** [comment]
Thanks for all the work you’ve put into this. I’ll review it as soon as I get the chance. Sorry for holding back on pushing it forward as is. I just wanted to cover those edge cases now, since once we ship, we might see a bunch of issues that we could have fixed upfront, and do think we should cover them. I understand you can’t take it further right now due to time commitments, and I really appreciate you letting me know. You’ve done a lot to move this forward, and it’s in a great place because of your work. I’ll carry it to completion when I get some time.

**Review by smitbarmase — APPROVED** [review]

**Comment by smitbarmase** [comment]
This looks great! In my last message, I thought the TODO case we were talking about was “This will not rewrap an existing single-line block comment,” which I wanted to cover. Today, while taking a look, I realized you already covered it. That was poor reading on my part, sorry about that. This already looks great to ship, and we can iterate on the remaining cases later. Merging this as is. Thanks for your patience. I wish I had reviewed this earlier.

**Comment by claytonrcarter** [comment]
OK great! Thank you for the merge, but sorry I wasn’t clearer about the unhandled edge cases.
