### PR TITLE
Preserve selected entry in file_finder

### LINKED ISSUE #11737: Project search jumps to first result
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I'm searching for a file with cmd+P, and then use the arrows to select a file a couple lines lower, I need to press enter within a couple ms otherwise the selection jumps back to the first line, that way I keep selecting the wrong file because of the jumpy selection.

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by kshokhin**
Closes #11737

If the query has not changed and entry is still in the matches list keep it selected

Release Notes:

- Fixes #11737

### CODE REVIEW

**Comment by kshokhin** [comment]
Hi @SomeoneToIgnore !

Here's the raw sketch of the solution we've discussed in the related issue

This fixes the problem I've faced during my work

However, if new entries appear above the selected one, it results into some kind of "jumping" anyway(please, see the attached video), which can be quite annoying. Does it look like an issue to you and is it worth to put effort into fixing it if so?

https://github.com/zed-industries/zed/assets/29820589/0cd22d95-9e80-4796-92fd-a4f690fb4aeb

Apart from that, I'm thinking of moving "selected_*" stuff inside the `Matches`, probably that would allow to keep track of the selected entry during the sorting and some other simplifications, like do not reassign the `selected_path` if it hasn't changed

**Review by SomeoneToIgnore — COMMENTED** [review]
Hey, thank you, the finder looks much more usable at this state already!

I agree that some further refactoring might help, as right now `position` does not take into account that the elements are sorted + that `self.update_selected_index(self.calculate_selected_index(!self.query_changed(&query)));` looks somewhat fragile.

Jumping is indeed odd, but I think that's relatively simple to fix, as on every selection we can remember the scroll position and maintain it after external changes are added?

Also curious how many events were captured in the video — seemed like there were a couple of files added and if it was so, maybe worth checking what happens after some directory got copied into the project, or a large git branch switch.
That will make more obvious whether jumping is an issue and also help to test thing at some scale.

**Comment by kshokhin** [comment]
I have a simple script that `touch`es new files either in the root directory or in the sub-folder(the simplest way I've found to play with entries' scores) every second. I'll try branch switching and folder copying as well.

> every selection we can remember the scroll position 

No idea how do it at the moment, to be honest :)
But I'll have a look what can be done in that regards.

**Comment by SomeoneToIgnore** [comment]
If that helps, the scrolling part could be approached via `UniformListScrollHandle` that has to be somewhere in the picker too:

https://github.com/zed-industries/zed/blob/d50d1611b91481008fbfb9d3b15886a3aa0956bb/crates/language_tools/src/syntax_tree_view.rs#L200

and that can get/set the item index scrolled to/to scroll to.

**Comment by kshokhin** [comment]
Hey, @SomeoneToIgnore !

I've tackled the scrolling part for some time, but still no good solution, yet. I've ended up trying to update the `UniformList` prepaint logic to keep the relative position of the selected element stable. E.g. if we have 2nd element of the list selected, then a bunch of entries added before it, so it becomes 10th, then render entries starting with the 9th element, so that the selected element still rendered as the 2nd.

Currently I'm thinking of storing the relative index of the selected entry in `file_finder`, and update `UniformListScrollHandle::scroll_to_item` method to store the requested relative position as well, then use it in the prepaint logic to calculate the correct scroll offset.

I've also tried adding and removing folder with git during the file search, and the jumping becomes even more obvious. The usecase  seems to be rather exaggerated, though, behaviour when copying large folder to the project should be pretty similar

https://github.com/user-attachments/assets/964ddd74-9dd0-48af-93fa-14d2c5c73caf

**Review by SomeoneToIgnore — COMMENTED** [review]
That video looks really good, actually!
Looks ready unless there are some corner-cases, and for sure better than we have now, so why not make a first iteration?

**Comment by SomeoneToIgnore** [comment]
Let me know when I should go and check this all, presumably this PR is no longer a draft then?

**Comment by kshokhin** [comment]
I agree, we could get this part merged first if you find it sufficient, and then work on the scrolling. Marked as ready for review.

I have a version that works like this with the same git switches in the background:

https://github.com/user-attachments/assets/b9000533-dc02-42b0-86f0-74e8ceb16e6a


Which to me looks even better.

 I've had to modify the UniformList, though, and I think it's worth to be a separate PR to review the whole approach and decide whether it's necessary at all.

**Comment by SomeoneToIgnore** [comment]
Sorry, I still have to make another review pass on top and find time for this — I expect to do this early next week.

File: crates/file_finder/src/file_finder.rs [hunk 1]
```diff
@@ -522,84 +556,100 @@ impl FileFinderDelegate {
...
+
             cx.notify();
         }
     }
 
+    fn query_changed(&self, new_query: &PathLikeWithPosition<FileSearchQuery>) -> bool {
+        return self
+            .latest_search_query
+            .as_ref()
+            .map(|q| q.path_like.raw_query != new_query.path_like.raw_query)
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:585]: NIT: could be just `map_or`

File: crates/file_finder/src/file_finder.rs [hunk 2]
```diff
@@ -522,84 +556,100 @@ impl FileFinderDelegate {
...
+            .unwrap_or(true);
+    }
+
+    fn update_selected_index(&mut self, selected_index: usize) {
+        self.selected_index = selected_index;
+        self.selected_match = self.matches.get(self.selected_index).map(|m| m.clone());
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:591]: NIT

```suggestion
        self.selected_match = self.matches.get(self.selected_index).cloned();
```

**Review by SomeoneToIgnore — COMMENTED** [review]
Sorry, I've finally made it here and loaded the PR into my head — hopefully next iterations should be faster.

This looks ok generally, one large note I have is a somewhat confusing naming.
If I understand it right after a while since discussing this, we try to capture a nuanced difference between the fact that we can select a certain item, and while that might have a selected index, both things can diverge due to certain events?

The code is somewhat hard for me to read, as there's many paths we can update either.

Should we add a test?
https://github.com/zed-industries/zed/blob/7f3caed6f00a7dae54e1dadfa7902d162caa1731/crates/file_finder/src/file_finder_tests.rs#L1414 
is a good example of a background FS change during the file finder being open.

We can add a few files that shift away the view and ensure our list still shows the file selected, even after N shifts that should've pushed it away entirely.

Also, I wonder if the readability could be helped by renaming `selected_` into something else, or adding more details.
It's very tempting to say that both `selected_match` and `selected_index` are the same, but they change differently somehow? That's what's nice to capture in the name, if possible.

----------------

Let's either add the test or make the code more clear and merge this.
Doing both things would be superb.

File: crates/file_finder/src/file_finder.rs (hunk 2 above)
Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs:591]: Thank you for the review, both points make sense to me.

It's definitely worth to add a test, thanks for the reference.

In regards the readability - what I'm thinking of is moving `selected_index` and `selected_match` to the dedicated struct like `SelectedEntry`, since what we're trying to do here is to keep particular entry in the list selected even if it's index changes due to some events. Does it make sense to you?

I also wonder, if there's any particular reason for passing `selected` flag to `file_finder::render_match` instead of comparing `ix` to the `selected_index` stored inside the `file_finder`?

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs:591]: > to the dedicated struct

I think that alone is not convincing, as leaves the same "why do we need to store both if matches[selected_index] is an O(1) access" question when reading, and current names do not help.
Ad-hoc weird options: `selected_by_user`, `selection_index_in_picker`.

Maybe it's not two fields but an enum that we need (weird ad-hoc ideas again)?
```rust
enum SelectedItem {
    UserSelected { i: usize } ,
    ReorderedAfterBackgroundUpdate { user_selected: usize, reordered_to: usize },
    SomethingElse,
}
```

I feel like there's a case where things have not diverged at all and there we can avoid any binary searches, etc.; and the other case, even if diverged, that could be expressed more explicitly.
I could be wrong though.


> any particular reason for passing selected flag to file_finder::render_match instead of comparing ix to the selected_index stored inside the file_finder

We kind of do that but compare with the delegate data: https://github.com/zed-industries/zed/blob/b6e28702520b0e4477de450052a48b0b1c625715/crates/picker/src/picker.rs#L499

The main reason for split is the fact that `FileFinder` encapsulates its render state inside and does not expose it — so various "go up" and other things change indices without forcing the user to write all that code.
While the `*Delegate` is where the real logic is, and changing the index there might influence whatever generic purpose, maybe even selecting multiple items or jumping to something that's not in `FileFinder`'s selection area.

Apart from that, I am not aware of any good reason for this besides an attempt to have a relatively low-level API for any kinds of use cases.

Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs:591]: I get the point, need to think a bit more about how to express the intent better.

Hopefully I'll revert with some updates during the week, but realistically, I'll get to it during the weekend, please, bear with me.

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs:591]: No rush at all, I am not the fastest to reply here either. 
We might eventually come and close the PR if it's ~1 month or so but even that means nothing in the context of this PR — it's just a few more things we need to think on, nothing fundamentally wrong.

Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs]: Pushed some updates here - added a couple of tests, applied NITs.

The answer to the question "why do we need to store both if matches[selected_index] is an O(1) access" is that we actually don't need to. Reverted back to storing just the selected index, seems to still work ok. The question I have here: is it true, that if the match stays in the matches list, it still has the same score as before the update? Otherwise, it's quite complicated to apply binary search to check if the match is still present.

Please, let me know if the code now makes more sense to you.

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs]: > The question I have here: is it true, that if the match stays in the matches list, it still has the same score as before the update? 

Depends on the score.

The `history_score` is derived from the order 

https://github.com/zed-industries/zed/blob/d93891ba630345d7e28b324aa027e650f4e7832f/crates/file_finder/src/file_finder.rs#L259

as we push the newly opened file on top constantly.

The regular score is derived once per `update_matches` call, when search matches are returned back in the `spawn_search` call.

File: crates/file_finder/src/file_finder.rs [hunk 3]
```diff
@@ -204,15 +204,22 @@ impl PartialOrd for ProjectPanelOrdMatch {
...
-enum Match {
+enum MatchData {
     History(FoundPath, Option<ProjectPanelOrdMatch>),
     Search(ProjectPanelOrdMatch),
 }
 
+#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
+struct Match {
+    data: MatchData,
+    history_score: usize,
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:220]: I see that all `MatchData::Search` get `no_history_score` here, similar to what the old code did.
Does it really make sense to have an extra struct here, or should we rather move the `history_score` into `MatchData::Search`?

If something needs to access this and it's not very convenient to always match this enum to get the number, we can extract it into a function, that will return a `no_history_score` (`0`) for the `Search` variant.

If we are able to do the latter, we can remove `struct Match` entirely and keep the old name for `enum MatchData` -> `enum Match`.

File: crates/file_finder/src/file_finder.rs [hunk 4]
```diff
@@ -256,48 +277,59 @@ impl Matches {
...
                     query_match.flatten()
                 };
-                Some((i + 1, Match::History(history_item.clone(), query_match)))
+                Some(Match {
+                    history_score: i + 1,
+                    data: MatchData::History(history_item.clone(), query_match),
+                })
             });
 
+        self.opened_path = currently_opened.map(|p| p.clone());
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:286]:
```suggestion
        self.opened_path = currently_opened.cloned();
```

File: crates/file_finder/src/file_finder.rs [hunk 5]
```diff
@@ -522,84 +554,100 @@ impl FileFinderDelegate {
...
             self.latest_search_query = Some(query);
             self.latest_search_did_cancel = did_cancel;
-            self.selected_index = self.calculate_selected_index();
+
             cx.notify();
         }
     }
 
+    fn query_changed(&self, new_query: &PathLikeWithPosition<FileSearchQuery>) -> bool {
+        return self.latest_search_query.as_ref().map_or(true, |q| {
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:587]: > `return`

Interesting, that Clippy does not complain about this, usually it asks to remove it and `;` and use the expression.
Let's do that at least, but we can go even further and inline the whole method as it's used only once.

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, this is so much simpler now.

I think we can reduce the diff even more if `MatchData` becomes `Match` again and related changes are "reverted".

I've left some nits but everything looks good conceptually — let's fix those and get the PR merged.

File: crates/file_finder/src/file_finder.rs (hunk 3 above)
Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs]: Reverted `struct MatchData` -> `enum Match`, and merged history score into the `History` variant.

`HistoryEntry` struct is there just to simplify `PartialOrd`, `Ord` and `PartialEq` implementations.

The fact that along with the `Ord` implementation there's also a `Matches::cmp_matches` is somewhat confusing, but seems ok to me, since it's different kinds of order defined for the same entity.

Regarding the tests, I still haven't figured out how to check that the selected entry is indeed visible after modifications of the matches list. I've looked into `Picker::logical_scroll_top_index`, but in my tests it returned different indexes from what I've expected, though `UniformList::prepaint` calculated correct visible entries range. Even having the top visible index in place it's not clear to me, how to check that the required index is visible. Any guidance would be highly appreciated.

Looking forward to your feedback.

**Comment by SomeoneToIgnore** [comment]
Sorry, I am away for this week also, and expect to look at the PR early next week.
Please ping anybody else if you want the review faster.

**Comment by kshokhin** [comment]
Hey, @SomeoneToIgnore !

Hope you're doing well

Any chance that you've had an opportunity to take a look at the PR?

File: crates/file_finder/src/file_finder.rs [hunk 6]
```diff
@@ -715,14 +788,17 @@ impl FileFinderDelegate {
 
     /// Skips first history match (that is displayed topmost) if it's currently opened.
     fn calculate_selected_index(&self) -> usize {
-        if let Some(Match::History(path, _)) = self.matches.get(0) {
-            if Some(path) == self.currently_opened_path.as_ref() {
-                let elements_after_first = self.matches.len() - 1;
-                if elements_after_first > 0 {
-                    return 1;
+        if let Some(m) = self.matches.get(0) {
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:791]: NIT: we can do `if let Some(Match::History(entry, _)) = ...` and reduce the level of nesting.

File: crates/file_finder/src/file_finder_tests.rs [hunk 7]
```diff
@@ -1541,6 +1541,107 @@ async fn test_search_results_refreshed_on_adding_and_removing_worktrees(
...
+        let filename = format!("/src/file_{}.txt", 20 + i);
+        app_state
+            .fs
+            .create_file(Path::new(&filename), Default::default())
+            .await
+            .expect("unable to create file");
+    }
+    cx.executor().advance_clock(FS_WATCH_LATENCY);
+
+    // file_13.txt is still selected
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder_tests.rs:1596]: Can we ensure that something had changed after entries were added? 
Because, if nothing was added then of course the selection did not change too.

File: crates/file_finder/src/file_finder_tests.rs [hunk 8]
```diff
@@ -1541,6 +1541,107 @@ async fn test_search_results_refreshed_on_adding_and_removing_worktrees(
...
+    let project = Project::test(app_state.fs.clone(), ["/src".as_ref()], cx).await;
+    let (workspace, cx) = cx.add_window_view(|cx| Workspace::test_new(project.clone(), cx));
+
+    // Initial state
+    let picker = open_file_picker(&workspace, cx);
+    cx.simulate_input("file");
+    // Select even/file_2.txt
+    cx.dispatch_action(SelectNext);
+
+    // Add more matches to the search results
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder_tests.rs:1631]: This is not right, as we remove matches?

**Review by SomeoneToIgnore — COMMENTED** [review]
Sorry for not coming earlier — we've had a release yesterday and quite many concentration was required on that front for some time.

I'm back now and plan to work on community issues and PRs more now, hopefully.

This PR looks very good after the changes — since the last time, you seem to have removed all expensive calculations even, so now the core change of this PR is somewhere around the

```rust
let selected_match = if query_changed {
    None
} else {
    self.matches.get(self.selected_index).cloned()
};
```
lines which is pure logic.
Quite a difference from the initial state 🙂 

I've found the `Ord` the most confusing part of the current state, otherwise it seems to be ready.

File: crates/file_finder/src/file_finder.rs (hunk 3 above)
Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs]: I was indeed, confused by the `Ord` as not sure why it is needed besides deduplication — the comment above does not explain this and by looking at the diff, I've mentioned the only usage but I might be wrong.
If it's indeed about the deduplication only, let's not use any `BTreeSet` at all and do direct binary search and remove `Ord` and anything extra.

I am not certain about testing such things myself, as there's indeed a very `render`-specific code we have to test which might not be even rendering properly as we're testing headless.

So let's keep testing the selections only, I think it's good enough as long as you manually test it to ensure that it works.

File: crates/file_finder/src/file_finder_tests.rs (hunk 7 above)
Comment (kshokhin) [reply crates/file_finder/src/file_finder_tests.rs:1596]: I believe, there's an implicit check in the way how we assert that the same entry is selected, since the expected index is increased by the number of added entries. If nothing has changed, then the index should stay the same as well, thus failing the assert.
https://github.com/zed-industries/zed/blob/4c5208059b31e5493843cafcd0f5e3ddb21d4f20/crates/file_finder/src/file_finder_tests.rs#L1598

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder_tests.rs:1596]: Sure, we can use that, never mind me then.

File: crates/file_finder/src/file_finder.rs [hunk 9]
```diff
@@ -256,47 +289,66 @@ impl Matches {
...
-                    (Match::Search(_), Match::History(_, _)) if self.separate_history => {
-                        cmp::Ordering::Greater
-                    }
+    fn cmp_matches(
+        separate_history: bool,
+        currently_opened: Option<&FoundPath>,
+        a: &Match,
+        b: &Match,
+    ) -> cmp::Ordering {
+        if a.eq(b) {
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:324]: Is it really needed? If we remove that, are those new `PartialEq` + `Eq` impls needed?
The `match` below seems to handle all that except `currently_opened` case.

**Review by SomeoneToIgnore — APPROVED** [review]
Yay, I think we've made it through!
Some nits are nice to fix, but no really confusing/bad things left! (that `a.eq(b)` is sort of, though)

File: crates/assistant/src/slash_command/file_command.rs [hunk 10]
```diff
@@ -512,10 +512,6 @@ mod custom_path_matcher {
             })
         }
 
-        pub fn sources(&self) -> &[String] {
```
[the remark this answers is not in the document]
Comment (kshokhin) [reply crates/assistant/src/slash_command/file_command.rs:515]: Clippy reported it as an unused function, not sure, though that it should be deleted

[the remark this answers is not in the document]
Comment (SomeoneToIgnore) [reply crates/assistant/src/slash_command/file_command.rs:515]: Oh, what is super weird given that you have not changed it, but sure.

File: crates/file_finder/src/file_finder.rs (hunk 9 above)
Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs:324]: It seems like the confusion around all this comparison stuff for matches rised after we've merged history score into the match. And it's a bit confusing, since we want to compare for equality(i.e. when finding duplicate matches) without history score, but when we order the set of unique matches, we need the history score.

So this eq just compares matches without taking the history scores into account.

File: crates/assistant/src/slash_command/file_command.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (kshokhin) [reply crates/assistant/src/slash_command/file_command.rs:515]: It appeared after I pulled the fresh main, not sure, why the CI checks passed, though.

File: crates/file_finder/src/file_finder.rs (hunk 9 above)
Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs:324]: Yes, looks a bit weird but at least more clear now.

It seems that CI fails and requires `itertools` to be removed from `file_finder/Cargo.toml` as we do not use it now, so we can add a brief commend and maybe just do `a == b` check instead?

Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs:324]: Now I think, maybe we do not need to store the history score with the match at all?


The reason why I've added it to the Match is to use the binary search to find the previously selected match in the new matches set. But since we want to find the particular match, it seems, that we should be able to do it passing 0 as a history score, having this check for equality in place.

If my understanding is correct, this would allow us to use the derived implementation for PartialEq.

Does it make sense?

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs:324]: Less syntaxic noise seems always interesting to try.

I would say, we can even go and first binary_search inside of a new `Vec` where we insert `(Match, score)`, and then do `self.search_matches = that_new_vec.into_iter().map(..).collect()` later.

All those custom comparisons are quite confusing in that, already bloated, comparison logic.

Comment (kshokhin) [reply crates/file_finder/src/file_finder.rs:324]: > I would say, we can even go and first binary_search inside of a new Vec where we insert (Match, score), and then do self.search_matches = that_new_vec.into_iter().map(..).collect() later.

This idea is not quite clear to me, could you please elaborate?

As of now we have retained old matches in `self.search_matches` and a couple of iterators over the new (unsorted AFAIU) matches collections. And then we add new matches to the `self.search_matches` keeping it sorted according to `cmp_matches`. Then, when we have sorted matches collection, we search for the previously selected match, since we want not only to check if it's still present, but also get it's new index to make it visible during the rendering.

Perhaps we could collect new matches in a vector, eliminating duplicates, then merge this new vector with the old matches. Though I'm not sure that creating this temporary vector is worth the effort, while we can do pretty much the same thing, but without extra copying.

Comment (SomeoneToIgnore) [reply crates/file_finder/src/file_finder.rs:324]: I think we are overthinking it, given how close are we to merge this 🙂 

Whatever way we can find to remove `eq` is nice, I think that's achieved by moving away the `usize`/history_score out of the struct (as you've noted well too).

I've tried to propose a way for doing that, as to first create an intermediate `Vec<(usize, Match)>` with whatever sorting/deduplication done that needs to know about `usize`, and then convert that into whatever `self.matches: Vec<Match>` type is by that time.
Then, presumably, we can remove the wrapper struct that was created for storing that `usize` only (as you were noting), and the diff will be even smaller.

But I do not insist on that way, if any other helps us to remove the odd `eq`.
I guess I can even live with that after some convincing, but feels quite easy to fix?

**Comment by kshokhin** [comment]
> I think we are overthinking it, given how close are we to merge this

Maybe, but during this overthinking, it seems like I've finally(after two months, yikes!) understood how this `Matches::push_new_matches` thing works, and made some refactoring according to this understanding.
I've left a bunch of comments, hope they'll be useful.

To sum up:
1. History score is still there, but it's required to binary search work in `Matches::position`. Given that we use history score only if we have no query to score by and if that's the case the list of matches should not change, so we do not need to search for previously selected entry, the history score can be removed. Probably, we could add a separate code path for empty query case to make it more obvious. However, it seems somewhat fragile to me, since it's based on some assumptions made on how the code works, which may not be true in the future.
2. Building separate collections for new history matches and new search matches, then merge them with the retained old matches.
3. Duplicates in history and search matches are eliminated using the HashMap of history matches. Duplicate in new and old search matches eliminated during the merge.
4. `Matches::cmp_matches` results are now aligned with the ordering of `ProjectPanelOrdMatch`
5. No need for custom PartialEq and weird comparisons anymore, though not sure that the diff is now smaller, seems quite the opposite :)

It's definitely worth to review the last three commits before merging.

File: crates/file_finder/src/file_finder.rs [hunk 11]
```diff
@@ -230,88 +274,104 @@ impl Matches {
...
+
+            _ => a.panel_match().cmp(&b.panel_match()),
+        }
     }
 }
 
-fn matching_history_item_paths<'a>(
+/// Produces a HashMap of history entries matching the query.
+/// `currently_opened` also treated as a history entry.
+/// HashMap is used because it's convenient for eliminating duplicate
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:366]: Here and below comes something quite implementation-specific, let's remove it before it gets obsolete.

File: crates/file_finder/src/file_finder.rs [hunk 12]
```diff
@@ -777,26 +862,34 @@ impl PickerDelegate for FileFinderDelegate {
...
-                        || (project.is_local_or_ssh() && history_item.absolute.is_some())
-                }),
-                self.currently_opened_path.as_ref(),
-                None,
-                None.into_iter(),
-                false,
-            );
-
-            self.selected_index = 0;
+            //NOTE: if there was no query before, and we already have some (history) matches
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:865]: Let's remove all those `NOTE:` as `//` in this form is a note per se.

File: crates/file_finder/src/file_finder.rs [hunk 13]
```diff
@@ -204,15 +204,35 @@ impl PartialOrd for ProjectPanelOrdMatch {
 #[derive(Debug, Default)]
 struct Matches {
     separate_history: bool,
+    opened_path: Option<FoundPath>,
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:207]: I wonder if we really need to store this path?
It seems to be the same as `currently_opened_path` which could be used directly after this change, as we pass it as a parameter.

File: crates/file_finder/src/file_finder.rs [hunk 14]
```diff
@@ -222,6 +242,30 @@ impl Matches {
...
 
+    fn position(&self, entry: &Match) -> Result<usize, usize> {
+        if let Match::History {
+            path,
+            panel_match: None,
+        } = entry
+        {
+            //NOTE: Slow case: linear search by path. Should not happen actually,
+            // since we call `position` only if matches set changed, but the query has not changed.
+            // And History entries do not have panel_match iff query is empty, so there's no
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:253]:
```suggestion
            // And History entries do not have panel_match if query is empty, so there's no
```

File: crates/file_finder/src/file_finder.rs [hunk 15]
```diff
@@ -230,88 +274,104 @@ impl Matches {
...
+        self.opened_path = currently_opened.cloned();
+
+        let Some(query) = query else {
+            //NOTE: assuming that if there's no query, then there's no search matches.
+            self.matches.clear();
+            let path_to_entry = |found_path: &FoundPath| Match::History {
+                path: found_path.clone(),
+                panel_match: None,
+            };
+            //NOTE: add currently_opened first, if anything is opened
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:286]: This and the next note seems quite obviously written in the code already, let's remove them.

File: crates/file_finder/src/file_finder.rs [hunk 16]
```diff
@@ -230,88 +274,104 @@ impl Matches {
...
+    }
+
+    /// If a < b, then a is a worse match, aligning with the `ProjectPanelOrdMatch` ordering.
+    fn cmp_matches(
+        separate_history: bool,
+        currently_opened: Option<&FoundPath>,
+        a: &Match,
+        b: &Match,
+    ) -> cmp::Ordering {
+        assert!(a.panel_match().is_some() && b.panel_match().is_some());
```
Comment (SomeoneToIgnore) [inline crates/file_finder/src/file_finder.rs:345]:
```suggestion
        debug_assert!(a.panel_match().is_some() && b.panel_match().is_some());
```

I'm a bit weary of panics in production and trying not to introduce more potential ones.

**Review by SomeoneToIgnore — COMMENTED** [review]
Looks reasonable to me, I have only some stylistic NITs to mention.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you, we made it! 🎉
Sorry for dragging that for longer than needed, but hopefully we've managed to create something solid for this case.
