### PR TITLE
vim: Fix regression in surround behavior

### LINKED ISSUE #38169: [Regression] Vim: surround always insert spaces, regardless of whether the brace is open or closed
### Description

Steps to reproduce:
1. Create a new file, with content `"foobar"`
2. Place the cursor at `"foo|bar"`
3. Enter the normal mode by pressing <kbd>Esc</kbd>
4. Type `cs"}`

**Expected Behavior**: `{foobar}`
**Actual Behavior**: `{ foobar }`

This issue also occurs with `cs"'` and `cs'"`, which should not insert spaces anyway.

> Good version: 0.202.8
> Bad version: 0.203.4

### Zed Version and System Specs

Zed: v0.203.1 (Zed Preview) 
OS: macOS 15.6.1
Memory: 48 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by dinocosta**
Fix an issue introduced in https://github.com/zed-industries/zed/pull/37321 where vim's surround wouldn't work as expected when replacing quotes with non-quotes, with whitespace always being added, regardless of whether the opening or closing bracket was used. This is not the intended, or previous, behavior, where only the opening bracket would trigger whitespace to be added.

Closes #38169 

Release Notes:

- Fixed regression in vim's surround plugin that ignored whether the opening or closing bracket was being used when replacing quotes, so space would always be added

### CODE REVIEW

File: crates/vim/src/surrounds.rs [hunk 1]
```diff
@@ -241,21 +241,15 @@ impl Vim {
...
-                    let surround = match target {
-                        Object::Quotes
-                        | Object::BackQuotes
-                        | Object::AnyQuotes
-                        | Object::MiniQuotes
-                        | Object::DoubleQuotes => true,
-                        _ => pair.end != surround_alias((*text).as_ref()),
+                    // Space is only added in the following cases:
+                    // - new surround is not quote and is opening bracket (({[<)
+                    // - new surround is quote and original was also quote
```
Comment (afgomez) [inline crates/vim/src/surrounds.rs:248]: Is this comment correct? If the original surround is a quote (i.e. `'`) and the new surround is also a quote (i.e. `"`) it should _not_ add space, right?

Comment (dinocosta) [reply crates/vim/src/surrounds.rs:248]: I was struggling to write a comment that clearly explained how the `surround` variable impacts the result when set to `true`. 

When it's set to `true` it'll either add a new space:

`'a'` → `cs'{` → `{ a }`

Or it'll preserve the existing space:

`' a '` → `cs'"` → `" a "`

So I guess a better comment would clarify that "Space is only added or preserved...". I'll be updating the change surround commands to more closely match [tpope/vim-surround](https://github.com/tpope/vim-surround), as discussed [here](https://github.com/zed-industries/zed/issues/38169#issuecomment-3304129461), and will review this comment as part of that work. Thanks for pointing it out! 🙇

**Comment by notpeter** [comment]
@ConradIrwin Could you review if you have a moment. Additional context here:
- https://github.com/zed-industries/zed/issues/38169#issuecomment-3309120792

**Comment by ConradIrwin** [comment]
THanks!
