### PR TITLE
gpui: Fix window cursor style flickering

### LINKED ISSUE #32592: Cursor is flickering
### Description

Steps to reproduce:
Simply typing in the editor causes the cursor to flicker continuously. This behavior did not occur before the Zed Preview 0.191.0.

**Expected Behavior**:

The mouse cursor should not flicker

**Actual Behavior**:
<details>
<summary>Cursor is flickering</summary>
<video src="https://github.com/user-attachments/assets/757e772e-47c9-4a39-a25b-4845cb0b719b"></video>
</details>

### Zed Version and System Specs

Zed: v0.191.0 (Zed Preview) 
OS: Linux Wayland arch unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1050 || NVIDIA || 575.57.08

### PR DESCRIPTION
**Pull request by MrSubidubi**
Closes #32592
Follow-up to #31965 

This PR fixes the cursor style flickering on Linux systems. The issue arose since the window cursor style was not reused anymore for subsequent frames after the changes in #31965. This works on MacOS for hiding cursors, since they are hidden until the next mouse movement occurs, which is not the case for other systems.

This PR re-adds this whilst keeping the fixes applied in #31965. We now determine the first cursor style that is hovered and continue searching for a cursor style that should be applied globally. If one to apply for the whole window is found, we return that cursor style early instead.

Alternatively, we could store window cursor style request in a vector similar to normal cursor styles. That would require more memory in exchange for fewer checks which cursor style to apply. I preferred the approach here, though, but can change this should the other method be preferred.

CC @smitbarmase since you assigned yourself that issue.

Release Notes:

- Fixed an issue where the cursor would flicker whilst typing.

### CODE REVIEW

File: crates/gpui/src/window.rs [hunk 1]
```diff
@@ -2185,7 +2186,10 @@ impl Window {
     /// phase of element drawing.
```
Comment (smitbarmase) [inline crates/gpui/src/window.rs:2186]: I wonder if this comment still holds, now that we are simply pushing its existing `cursor_styles`? After these changes, `set_window_cursor_style` is not anything special (i.e. works exactly same as `set_cursor_style` except `hitbox` is `None`) but precedence part is not true anymore.

I assume the API distinction was made on purpose for window cursor to take precedence, which won't be happening now, so it might be simpler to merge back like it was, i.e. `Option<&Hitbox>`, to prevent confusion on which API to use, as it serves the same purpose now?

**Review by smitbarmase — CHANGES_REQUESTED** [review]

File: crates/gpui/src/window.rs (hunk 1 above)
Comment (MrSubidubi) [reply crates/gpui/src/window.rs:2186]: The comment does still hold - `set_window_cursor_style` does take precedence whenever it is used. Earlier, we would use the cursor style for the first hovered hitbox. Now, we still search for such a style, but also search in the entire Vec for a cursor style that should be applied for the whole window. If we find one, we apply that for the whole window. Thus, cursor styles applied using that method still take precedence in a similar fashion as before but now guaranteed for all cases. What I noticed in https://github.com/zed-industries/zed/pull/31965#issuecomment-2936832536 will continue to be fixed with these changes.

Comment (smitbarmase) [reply crates/gpui/src/window.rs:2186]: Oh, missed it's using `fold_while` and not previous `find_map`. This looks right, thank you!

**Review by smitbarmase — APPROVED** [review]

**Comment by smitbarmase** [comment]
@MrSubidubi just flagging this, folks have started to see occasional cursor flickering on macOS as well even after this fix. I don't have the right way to reproduce this (_**mostly happens for me after editing some text, and then moving mouse**_). But, just letting you know since you have been looking into that and have broader context.

**Comment by MrSubidubi** [comment]
@smitbarmase Thanks for letting me know. I have to say that, with this PR in, I am fairly certain the issue occurs with something else and would even happen if we were to use `set_cursor_style(CursorStyle::None, &editor_hitbox)`.

I am fairly certain that the issue occurs due to #32408 and will also happen if none of these two PRs were in. I was able to reproduce this locally once, but have been unsuccessful after. But I believe due to the buffer not always being redrawn now, we hit a case where we hide the mouse cursor again on every cursor blink due to a missing invalidation. That invalidation probably happened before #32408 due to checking on every mouse move, which now does not happen anymore. 

The only slight difference these changes here make is that we see the issue slightly more often, but I believe the issue would be present either way and occurs due to the optimizations made in #32408.

**Comment by smitbarmase** [comment]
Thanks for letting me know. I just wanted to get your perspective on it. 

It's happening for me once in a while, so maybe I can pinpoint the exact commit that might be causing it. The PR you mentioned does sound like a culprit, but I will do some git bisecting just to be sure so that we don’t wander into a different route.

**Comment by MrSubidubi** [comment]
Alright, sounds good. I do want to mention that the biscect might lead to different commits depending on the OS you are on: The slightly different semantics of `CursorStyle::None` on MacOS and Linux led to the linked issue in the first place, since MacOS hides the cursor until the next move while Linux doesn't. That is why my changes initially worked for me on my Mac and that is why bisecting on Mac would probably lead to this PR. I am quite certain though that if you are bisecting on Linux, you should be able to find a different commit that might have caused the underlying issue to occur.

In any case, feel free to let me know if you need anything else from me.
