### PR TITLE
collab: Make unsupported for MinGW toolchain

### LINKED ISSUE #23451: Editor is not buildable on MinGW after latest changes
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

previously opened in #23450, but I accidently closed it. this is a regression from https://github.com/zed-industries/zed/pull/23117
1. try to compile Zed with cargo build --release -p zed
2. then cargo will build webrtc-sys, but webrtc itself supports MSVC only
3. get an error because cc is run with MSVC compile flags (e.g. /EHsc)

### Zed Version and System Specs

the same as

Zed: v0.169.2 (Zed)
OS: Windows 10.0.26100
Memory: 15.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU || NVIDIA || 566.36

but compiled for latest commit

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by ognevny**
Closes #23451

reverts #23117 for MinGW. collab can't be compiled for MinGW because webrtc itself doesn't support MinGW compilers

Release Notes:

- N/A

### CODE REVIEW

**Comment by maxdeviant** [comment]
Just leaving my two cents here that I'm not sure that this is worth it.

It adds a lot of noise to the code with all of the conditional compilation, and I don't think we've ever explicitly stated that supporting MinGW for our Windows builds.

Is there any particular reason we would _need_ to support MinGW over MSVC on Windows?

**Comment by ognevny** [comment]
> Is there any particular reason we would _need_ to support MinGW over MSVC on Windows?

I don't see a problem if community will support this (https://github.com/zed-industries/zed/issues/23451#issuecomment-2606461190)

**Comment by maxdeviant** [comment]
> > Is there any particular reason we would _need_ to support MinGW over MSVC on Windows?
> 
> I don't see a problem if community will support this ([#23451 (comment)](https://github.com/zed-industries/zed/issues/23451#issuecomment-2606461190))

The problem is that it adds additional complexity to the codebase that Zed engineers have to deal with, for a platform toolchain that we don't use ourselves.

Additionally, I don't think that long-term we want to support a build of Zed that purposefully doesn't include core Zed features (like collaboration).

In the original issue (#23451) the problem was identified as:

> then cargo will build webrtc-sys, but webrtc itself supports MSVC only

So I think the path forward here would be to add support for building the crates required to support collaboration on MinGW.

**Comment by ognevny** [comment]
> errors I get from compiling https://github.com/desktop-app/tg_owt, which uses webrtc code

forgot to add link to a [patch file](https://github.com/msys2/MINGW-packages/blob/5b603a025619ff28cf5cbf149c2535503a09ce66/mingw-w64-libtg_owt/libtg_owt_mingw_build.patch) that I used for it so you can reproduce issue yourselves

**Review by SomeoneToIgnore — APPROVED** [review]
I am not fond of the bloated code, but:

* I think Zed should work on more platforms if it can
* people, who care and do something enough to compose normal PRs, should be valued

Our Windows people seem to silently agree, hence merging.

**Comment by ognevny** [comment]
thank you!

File: crates/call/src/cross_platform/room.rs [hunk 1]
```diff
@@ -1288,6 +1317,12 @@ impl Room {
         }
     }
 
+    #[cfg(all(target_os = "windows", target_env = "gnu"))]
+    pub fn share_microphone(&mut self, cx: &mut ModelContext<Self>) -> Task<Result<()>> {
```
Comment (xdBronch) [inline crates/call/src/cross_platform/room.rs:1321]: shouldnt this be `Context` not `ModelContext`?

File: crates/call/src/cross_platform/room.rs [hunk 2]
```diff
@@ -1573,6 +1623,14 @@ impl Room {
     }
 }
 
+#[cfg(all(target_os = "windows", target_env = "gnu"))]
+fn spawn_room_connection(
+    livekit_connection_info: Option<proto::LiveKitConnectionInfo>,
+    cx: &mut ModelContext<'_, Room>,
```
Comment (xdBronch) [inline crates/call/src/cross_platform/room.rs:1629]: same here

**Comment by ognevny** [comment]
about reviews: yes, they should be. I somehow missed it while rebasing
