### PR TITLE
Use /usr/bin/env to run bash restart script

### LINKED ISSUE #33935: Zed preview fails to restart on auto update on NixOS
### Summary

Zed preview fails to restart on auto update on NixOS

### Description

Zed fails to restart on auto update on NixOS, the `workspace: reload` command also fails.

Steps to reproduce:
1. Install Zed via the install script on zed.dev on NixOS
2. Launch zed
3. Execute the `workspace: reload` command. 

**Expected Behavior**: Zed restarts
**Actual Behavior**: Zed doesn't restarts 

Zed logs: 
```
2025-07-04T17:53:41-04:00 INFO  [gpui::platform::linux::platform] Restarting process, using app path: "/home/parker/.local/zed-preview.app/libexec/zed-editor"
2025-07-04T17:53:41-04:00 ERROR [gpui::platform::linux::platform] failed to spawn restart script: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

### Zed Version and System Specs

Zed: v0.194.3 (Zed Preview) 
OS: Linux Wayland nixos 25.05
Memory: 62.2 GiB
Architecture: x86_64
GPU: Intel(R) Arc(tm) Graphics (MTL) || Intel open-source Mesa driver || Mesa 25.0.7

### PR DESCRIPTION
**Pull request by AlvaroParker**
Closes #33935

Release Notes:

- Use `/usr/bin/env` to launch the bash restart script

### CODE REVIEW

File: crates/gpui/src/platform/linux/platform.rs [hunk 1]
```diff
@@ -201,7 +201,8 @@ impl<P: LinuxClient + 'static> Platform for P {
         );
 
         // execute the script using /bin/bash
```
Comment (SomeoneToIgnore) [inline crates/gpui/src/platform/linux/platform.rs]: Let's remove the obsolete/obvious comment.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you.
