### PR TITLE
Fix terminal doesn't switch to project directory when opening remote project on Windows

### LINKED ISSUE #45253: windows: Terminal doesn't switch to project directory when opening remote project
### Reproduction steps

When opening a remote project in Zed editor and then launching the terminal, the working directory remains at ~ instead of automatically switching to the project directory. This requires manual navigation to the project folder each time.

Steps to Reproduce:
- Open a remote project in Zed
- Open the terminal
- Observe that the current directory is still ~ instead of the project directory

### Current vs. Expected behavior

Expected Behavior: The terminal should automatically switch to the project directory when opened in a remote project, similar to how local projects behave.
Actual Behavior: The terminal opens in the home directory (~) regardless of which remote project is currently open.
Impact:
This creates inconvenience and reduces workflow efficiency, as users need to manually navigate to their project directory every time they open a terminal in a remote project.

### Zed version and system specs

Zed: v0.219.0+nightly.2021.af3902a33f86d6d7d030a1167f6151912a697c11 (Zed Nightly af3902a33f86d6d7d030a1167f6151912a697c11) 
OS: Windows 10.0.26200
Memory: 31.4 GiB
Architecture: x86_64
GPU: Intel(R) Arc(TM) 140T GPU (16GB) || Intel Corporation || 32.0.101.7026

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by feeiyu**
Closes #45253

Release Notes:

- Fixed terminal doesn't switch to project directory when opening remote project on Windows

### CODE REVIEW

File: crates/remote/src/transport/ssh.rs [hunk 1]
```diff
@@ -1544,8 +1544,14 @@ fn build_command(
     } else {
         write!(exec, "{ssh_shell} -l")?;
     };
+
+    // The command needs to be executed in a new shell, so it requires quoting again
+    let exec_after_quote = ssh_shell_kind
+        .try_quote(&exec)
+        .context("shell quoting")?
+        .into();
```
Comment (Veykril) [inline crates/remote/src/transport/ssh.rs]: ~~This doesn't seem right, the shell builder should already be taking care of this~~ See my comment below

**Review by Veykril — APPROVED** [review]

**Comment by baldwindavid** [comment]
Probably you know now that this is not specific to Windows. I'm on Mac and had the same issue SSH'd into a local Docker container. This fixes it. Thanks!

**Comment by mbratch** [comment]
Is this fix in the 1.17.2 release? I'm using 1.17.2 and am still experiencing this issue.
