### PR TITLE
vim: Add some forced motion support

### LINKED ISSUE #20971: vim mode delete inclusive motion
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When deleting in front of the cursor, for example with `d0`, the `0` motion is exclusive, and hence will not delete the character the cursor is on. This can be fixed with the `v` modifier to make the deletion inclusive in vim, but is not currently supported in zed. Using `dv0` will ignore the `d` action and just select with `v0`.

### Environment

Zed: v0.162.3 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by mastion**
Closes https://github.com/zed-industries/zed/issues/20971

Added `v` input to yank and delete to override default motion. The global vim state tracking if the forced motion flag was passed handled the same way that the count is. [The main chunk of code maps the motion kind from the default to the overridden kind](https://github.com/zed-industries/zed/pull/27991/files#diff-2dca6b7d1673c912d14e4edc74e415abbe3a4e6d6b37e0e2006d30828bf4bb9cR1249-R1254). To handle the case of deleting a single character (dv0) at the start of a row I had to modify the control flow [here](https://github.com/zed-industries/zed/pull/27991/files#diff-2dca6b7d1673c912d14e4edc74e415abbe3a4e6d6b37e0e2006d30828bf4bb9cR1240-R1244). Then to handle an exclusive delete till the end of the row (dv$) I [saturated the endpoint with a left bias](https://github.com/zed-industries/zed/pull/27991/files#diff-2dca6b7d1673c912d14e4edc74e415abbe3a4e6d6b37e0e2006d30828bf4bb9cR1281-R1286).

Test case: dv0

https://github.com/user-attachments/assets/613cf9fb-9732-425c-9179-025f3e107584

Test case: yvjp

https://github.com/user-attachments/assets/550b7c77-1eb8-41c3-894b-117eb50b7a5d

Release Notes:

- Added some forced motion support for delete and yank

### CODE REVIEW

**Comment by mastion** [comment]
A note about implementation -
My first thought when working on this was to set the `MotionKind` to `Inclusive` up at the `PushDeleteInclusive` function ( or somewhere near that ) but as I dug through the code I noticed inside of the [range](https://github.com/zed-industries/zed/blob/main/crates/vim/src/motion.rs#L1143) function in `motion.rs` is defaults to `Exclusive`. 
I didn't feel like I had the context for changing that, so I just passed in a bool.

File: crates/vim/src/state.rs [hunk 1]
```diff
@@ -78,7 +78,11 @@ impl Default for Mode {
 #[derive(Clone, Debug, PartialEq)]
 pub enum Operator {
     Change,
-    Delete,
+    //Delete,
```
Comment (KyleBarton) [inline crates/vim/src/state.rs:81]: Should delete these comments

File: crates/vim/src/normal/delete.rs [hunk 2]
```diff
@@ -33,12 +34,20 @@ impl Vim {
...
                         let original_head = selection.head();
                         original_columns.insert(selection.id, original_head.column());
-                        let kind =
+                        let mut kind =
                             motion.expand_selection(map, selection, times, &text_layout_details);
 
                         ranges_to_copy
                             .push(selection.start.to_point(map)..selection.end.to_point(map));
 
+                        if inclusive {
```
Comment (KyleBarton) [inline crates/vim/src/normal/delete.rs:43]: any reason this needs to go below `ranges_to_copy`? If not, I think you could avoid `mut` with:

```
let kind = match motion.expand_selection(...) {
  Some(x) => Some(x)
  None => {
     if (inclusive) {
       {selection mutating code}
       Some(MotionKind::Inclusive)
     } else {
        None
     }
  }
}
```

But no strong opinion on that, depending on if you think that reads worse.

File: crates/vim/src/state.rs [hunk 3]
```diff
@@ -933,7 +937,8 @@ impl Operator {
             Operator::Object { around: false } => "i",
             Operator::Object { around: true } => "a",
             Operator::Change => "c",
-            Operator::Delete => "d",
+            Operator::Delete { inclusive: false } => "d",
+            Operator::Delete { inclusive: true } => "v",
```
Comment (KyleBarton) [inline crates/vim/src/state.rs:941]: I'm lower context on this - it seems fine? My only question would be, could future edits to `vim.json` spuriously allow a user to directly access the `PushDeleteInclusive` operator, rather than traveling first through the `PushDelete` operator? And if so, is that bad?

File: crates/vim/src/normal/delete.rs (hunk 2 above)
Comment (mastion) [reply crates/vim/src/normal/delete.rs:51]: To do it that way the code would look closer to 
```
let kind = match motion.expand_selection(...) {
  Some(x) if inclusive => {
    {selection mutation code}
    Some(x)
  },
  None if inclusive => {
       {selection mutating code}
       Some(MotionKind::Inclusive)
  },
  Some(x) => Some(x),
  None => None
}
```
I split the difference and was able to keep the kind from being a `mut` but the mutation code happens after the fact.

File: crates/vim/src/state.rs (hunk 3 above)
Comment (mastion) [reply crates/vim/src/state.rs:939]: If i'm understanding the question correctly then yeah I think so. 
Someone would just need to move the [pushdeleteinclusive mapping](https://github.com/zed-industries/zed/pull/27991/files/8cc430f023f18a2e68e6cc8404faee8fc72cf8b4#diff-7b7dabbece7a54e041c4b6ab8f69afbe994d301dbded14921a31598d7f6de287R456) out from under the [d operator context](https://github.com/zed-industries/zed/pull/27991/files/8cc430f023f18a2e68e6cc8404faee8fc72cf8b4#diff-7b7dabbece7a54e041c4b6ab8f69afbe994d301dbded14921a31598d7f6de287L452).
But that is true for anything in that section so I don't think it is concern.

**Comment by ConradIrwin** [comment]
@mastion Thanks for this! 

The `v` affects any motion, not just delete; so I think we should treat `v` (and `shift-v`) in the same way we treat the count. `PushInclusive` would set a field on the vim state, which we'd take and pass down into `motion.expand_selection` and `motion.range`  alongside `count`. We'd use that to modify the kind returned from `default_kind()`, and (hopefully) hit our existing inclusive/exclusive code handling (which was tidied up a bunch in #27786).

In particular I would like to make `y v j` (linewise copy becomes exclusive) and `d v e` (inclusive delete becomes exclusive) work in addition to `d v 0` as part of this change.

That said, I don't know if the theory actually works in practice, so happy to pair on this if you want: https://cal.com/conradirwin/pairing

```
v               When used after an operator, before the motion command: Force
                the operator to work charwise, also when the motion is
                linewise.  If the motion was linewise, it will become
                exclusive.
                If the motion already was charwise, toggle
                inclusive/exclusive.  This can be used to make an exclusive
                motion inclusive and an inclusive motion exclusive.
```

**Comment by mastion** [comment]
@ConradIrwin Awesome. That is what I expected, but wasn't sure how to structure it.
I'll take a crack at it and schedule some time with you next week in case it doesn't work out as hoped.

**Comment by ConradIrwin** [comment]
Thanks for this!
