### PR TITLE
linux: Fix wrong names reported by `all_font_names`

### LINKED ISSUE #14096: Unable to set "Iosevka Extended" as my editor font
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In VSCode, I have the following font configuration:

```
"editor.fontFamily": "'Iosevka Extended', 'monospace', monospace, 'Iosevka Extended Fallback'",
```

I tried to copy it to Zed, which suggested:

```
"buffer_font_family": "Iosevka-Extended",
```

But this setting is ignored, and the default font is used instead.

What works is:

```
"buffer_font_family": "Iosevka",
```
— but I don't like it :)

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland opensuse-tumbleweed 20240705
Memory: 62.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### LINKED ISSUE #14854: Unable to use fonts with hyphens in their name
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello!  On a recent Linux build, I attempted to set the `buffer_font_family` to a font name that has a ~~dash~~ hyphen-minus in it; while the autocompletion and validation works, there's no actual change in the font used, instead reverting to what is the default font.  Using another font without a hyphen (even one with a space) seems to work fine.

Please let me know if I can provide any more details or help!

EDIT: It's not _super_ easy to tell the fonts are different in the screenshots, so I added a non mono font to really make it clear.

EDIT2: based on a little trial+error/searching, it looks like the actual character is the "hyphen-minus", not one of the various flavors of dash: https://www.compart.com/en/unicode/U+002D

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland fedora 40
Memory: 62.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Default (I think) font:
image

Font with dash with no change in appearance:
image

Font without dash, with expected changes:
image

Non monospaced font without dash (to emphasize the visual difference):
image

Non monospaced font with dash (Inter-Bold is not a fixed width font) to help show that it is not working as expected:
image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
The names suggested by `buffer_font_family` are reported by `all_font_names`. Therefore, `all_font_names` should report family names rather than postscript names.

close #14854 

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/cosmic_text/text_system.rs [hunk 1]
```diff
@@ -69,8 +69,10 @@ impl PlatformTextSystem for CosmicTextSystem {
             .font_system
             .db()
             .faces()
-            .map(|face| face.post_script_name.clone())
-            .collect()
+            .filter_map(|face| face.families.first().map(|family| family.0.clone()))
+            .collect::<BTreeSet<String>>()
```
Comment (mikayla-maki) [inline crates/gpui/src/platform/cosmic_text/text_system.rs:73]: Rather than collecting into a BTreeSet, and allocating the whole thing twice, could we use a `Vec::sort` and `Vec::dedup`?

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

File: crates/gpui/src/platform/cosmic_text/text_system.rs (hunk 1 above)
Comment (JunkuiZhang) [reply crates/gpui/src/platform/cosmic_text/text_system.rs]: On macOS, BTreeSet was used, so I followed suit and used BTreeSet as well. However, your suggestion is correct; we should avoid multiple memory allocations.

Comment (mikayla-maki) [reply crates/gpui/src/platform/cosmic_text/text_system.rs]: Oh, good to know!

**Comment by mikayla-maki** [comment]
Thank you!
