### PR TITLE
Fix zed irresponsive on symlinked directory events outside the editor

### LINKED ISSUE #27263: Failure to detect file system changes with symlinks targeting other workspace folders
### Summary

Zed has problems detecting file system changes(i.e. files/folders creation/deletion/rename etc.) in symlinked folders on Linux Mint 22.1 with btrfs file system.

Steps to trigger the problem:
1. Create folder structure:
```
test-dir/
|- some-dir/
|- shared-dir/
```
```shell
mkdir -p test-dir/{some-dir,shared-dir}
```
2. Open ```test-dir``` in Zed
```shell
cd your-path/test-dir && zed .
```
3. Open Project pane in Zed
4. Create sym-link for ```shared-dir``` in ```some-dir```
```shell
ln -sf $(pwd)/shared-dir $(pwd)/some-dir/shared-dir
```
5. Create file ```file.txt``` in ```shared-dir``` through terminal
```shell
touch ./shared-dir/file.txt
```
6. Look at Project pane.
Zed will detect changes in sym-link ```some-dir/shared-dir``` and ```file.txt``` will be displayed there, but nothing will be shown for main folder ```shared-dir```.

7. Create a file ```file-2.txt``` through Zed in sym-link ```some-dir/shared-dir```.
8. Look at Project pane.
Zed will detect changes in sym-link ```some-dir/shared-dir``` and ```file,txt``` and ```file-2.txt``` will be displayed there,  but nothing will be shown for main folder ```shared-dir```.
9. Create a ```file-3.txt``` through Zed in main folder ```shared-dir```.
10. Look at Project pane.
Zed will detect changes in sym-link ```some-dir/shared-dir``` and all 3 files will be displayed there,  but only file ```file-3.txt``` will be shown in main folder ```shared-dir```.
11. Restart Zed
12. After restart, Zed will correctly display file structure for main ```shared-dir```, but listed above behavior doesn't change.
13.  Same behavior applies for folders and rename, delete etc. operations

Actual Behavior:
Zed doesn't detect file system changes (files/folders creation, deletion, rename etc.) for sym-linked(main) folder if changes are made in folder sym-link. Zed detects only sym-linked(main) folder file system changes if changes are made there.

Restart of Zed doesn't change listed above behavior.

Expected Behavior:
Zed detects file system changes for sym-linked(main) folder regardless of where changes were made(in main folder or sym-link) and displays them correctly.

<details>
<summary>
Zed log before restart
</summary>

```
2025-03-21T17:03:22.186703122+02:00 [INFO] ========== starting zed ==========
2025-03-21T17:03:22.199261748+02:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2025-03-21T17:03:22.19935392+02:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2025-03-21T17:03:22.231693825+02:00 [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-03-21T17:03:22.231762005+02:00 [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-03-21T17:03:22.231807715+02:00 [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-03-21T17:03:22.231853771+02:00 [INFO] Enabling Vulkan Portability
2025-03-21T17:03:22.231894147+02:00 [INFO] Enabling color space support
2025-03-21T17:03:22.243937204+02:00 [INFO] Adapter: "NVIDIA GeForce GT 1030"
2025-03-21T17:03:22.244028709+02:00 [INFO] No ray tracing extensions are supported
2025-03-21T17:03:22.26750275+02:00 [INFO] perform;
2025-03-21T17:03:22.267595707+02:00 [INFO] authenticate;
2025-03-21T17:03:22.267679361+02:00 [INFO] read_command;
2025-03-21T17:03:22.267763586+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:22.267816698+02:00 [INFO] Opening main db
2025-03-21T17:03:22.268481275+02:00 [INFO] new;
2025-03-21T17:03:22.268563256+02:00 [INFO] socket reader;
2025-03-21T17:03:22.268624164+02:00 [INFO] read_socket;
2025-03-21T17:03:22.268694917+02:00 [INFO] read_socket;
2025-03-21T17:03:22.268847186+02:00 [INFO] Opening main db
2025-03-21T17:03:22.268916538+02:00 [INFO] read_socket;
2025-03-21T17:03:22.269037962+02:00 [INFO] read_socket;
2025-03-21T17:03:22.269144263+02:00 [INFO] read_socket;
2025-03-21T17:03:22.269415792+02:00 [INFO] read_socket;
2025-03-21T17:03:22.269486234+02:00 [INFO] keep_updated;
2025-03-21T17:03:22.270154757+02:00 [INFO] Using git binary path: None
2025-03-21T17:03:22.270236223+02:00 [INFO] read_socket;
2025-03-21T17:03:22.271010858+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272242739+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272387295+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272516972+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272762076+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272850929+02:00 [INFO] read_socket;
2025-03-21T17:03:22.272939281+02:00 [INFO] read_socket;
2025-03-21T17:03:22.273012681+02:00 [INFO] read_socket;
2025-03-21T17:03:22.298548413+02:00 [INFO] No prompt template overrides directory found at /home/user/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-03-21T17:03:22.299242505+02:00 [INFO] extensions updated. loading 17, reloading 0, unloading 0
2025-03-21T17:03:22.301078178+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-03-21T17:03:22.304425477+02:00 [INFO] Opening main db
2025-03-21T17:03:22.304802807+02:00 [INFO] perform;
2025-03-21T17:03:22.304865412+02:00 [INFO] authenticate;
2025-03-21T17:03:22.304922764+02:00 [INFO] read_command;
2025-03-21T17:03:22.304988208+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:22.305935732+02:00 [INFO] socket reader;
2025-03-21T17:03:22.306016731+02:00 [INFO] read_socket;
2025-03-21T17:03:22.306096836+02:00 [INFO] read_socket;
2025-03-21T17:03:22.310474148+02:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2025-03-21T17:03:22.310602844+02:00 [INFO] Creating colormap 85983235
2025-03-21T17:03:22.310673997+02:00 [INFO] read_socket;
2025-03-21T17:03:22.311746174+02:00 [INFO] read_socket;
2025-03-21T17:03:22.312022324+02:00 [INFO] read_socket;
2025-03-21T17:03:22.312331576+02:00 [INFO] read_socket;
2025-03-21T17:03:22.315561368+02:00 [INFO] Using surface present mode FIFO_RELAXED
2025-03-21T17:03:22.366099855+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:03:22.366196837+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:03:22.366268957+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-03-21T17:03:22.441908281+02:00 [INFO] Refreshing at 16666 micros
2025-03-21T17:03:22.443147146+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GT 1030", driver_name: "NVIDIA", driver_info: "550.120" }
2025-03-21T17:03:22.464297964+02:00 [INFO] Opening main db
2025-03-21T17:03:22.495194451+02:00 [INFO] Opening main db
2025-03-21T17:03:22.701702425+02:00 [INFO] set environment variables from shell:/usr/bin/zsh, path:/home/user/.local/zls/zig-out/bin:/home/user/.local/zig:/home/user/go/bin:/home/user/.local/go/bin:/home/user/.nvm/versions/node/v22.14.0/bin:/home/user/.local/share/zinit/polaris/bin:/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.fzf/bin
2025-03-21T17:03:27.464270208+02:00 [INFO] perform;
2025-03-21T17:03:27.464382833+02:00 [INFO] authenticate;
2025-03-21T17:03:27.464459535+02:00 [INFO] perform;
2025-03-21T17:03:27.464534048+02:00 [INFO] authenticate;
2025-03-21T17:03:27.464604246+02:00 [INFO] perform;
2025-03-21T17:03:27.464656696+02:00 [INFO] authenticate;
2025-03-21T17:03:27.464706114+02:00 [INFO] read_command;
2025-03-21T17:03:27.464782006+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.464864922+02:00 [INFO] perform;
2025-03-21T17:03:27.464932098+02:00 [INFO] authenticate;
2025-03-21T17:03:27.464988494+02:00 [INFO] read_command;
2025-03-21T17:03:27.46507793+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.465187075+02:00 [INFO] perform;
2025-03-21T17:03:27.46526072+02:00 [INFO] authenticate;
2025-03-21T17:03:27.465344096+02:00 [INFO] read_command;
2025-03-21T17:03:27.46572355+02:00 [INFO] read_command;
2025-03-21T17:03:27.465826742+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.46661457+02:00 [INFO] perform;
2025-03-21T17:03:27.466717441+02:00 [INFO] authenticate;
2025-03-21T17:03:27.466800403+02:00 [INFO] read_command;
2025-03-21T17:03:27.466882231+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.466959687+02:00 [INFO] socket reader;
2025-03-21T17:03:27.46705131+02:00 [INFO] read_socket;
2025-03-21T17:03:27.467140305+02:00 [INFO] socket reader;
2025-03-21T17:03:27.467219022+02:00 [INFO] read_socket;
2025-03-21T17:03:27.467314584+02:00 [INFO] read_socket;
2025-03-21T17:03:27.467401175+02:00 [INFO] read_socket;
2025-03-21T17:03:27.467968257+02:00 [INFO] socket reader;
2025-03-21T17:03:27.468062993+02:00 [INFO] read_socket;
2025-03-21T17:03:27.468167665+02:00 [INFO] read_socket;
2025-03-21T17:03:27.468264324+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.469452657+02:00 [INFO] socket reader;
2025-03-21T17:03:27.469555585+02:00 [INFO] read_socket;
2025-03-21T17:03:27.469657125+02:00 [INFO] read_socket;
2025-03-21T17:03:27.469752409+02:00 [INFO] socket reader;
2025-03-21T17:03:27.469843635+02:00 [INFO] read_command;
2025-03-21T17:03:27.469934892+02:00 [INFO] send_secondary_commands;
2025-03-21T17:03:27.470053114+02:00 [INFO] read_socket;
2025-03-21T17:03:27.470173072+02:00 [INFO] read_socket;
2025-03-21T17:03:27.470899132+02:00 [INFO] socket reader;
2025-03-21T17:03:27.470963207+02:00 [INFO] read_socket;
2025-03-21T17:03:27.471028605+02:00 [INFO] read_socket;
2025-03-21T17:03:27.472908817+02:00 [INFO] read_socket;
2025-03-21T17:03:27.475951427+02:00 [INFO] read_socket;
2025-03-21T17:03:27.478909996+02:00 [INFO] read_socket;
2025-03-21T17:03:27.482675999+02:00 [INFO] read_socket;
2025-03-21T17:03:27.486218947+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489000131+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489118089+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489188219+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489271728+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489329238+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489412743+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489493262+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489551125+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489613168+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489694495+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489780142+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489859403+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489916521+02:00 [INFO] read_socket;
2025-03-21T17:03:27.489985482+02:00 [INFO] read_socket;
2025-03-21T17:03:27.490299746+02:00 [INFO] read_socket;
2025-03-21T17:03:27.490381398+02:00 [INFO] read_socket;
2025-03-21T17:03:27.490460831+02:00 [INFO] read_socket;
2025-03-21T17:03:27.491357736+02:00 [INFO] read_socket;
2025-03-21T17:03:27.491619398+02:00 [INFO] read_socket;
2025-03-21T17:20:21.785145333+02:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2025-03-21T17:20:21.785265911+02:00 [INFO] Creating colormap 85983262
2025-03-21T17:20:21.785318939+02:00 [INFO] considering ancestor: "/home/user/Documents/zed-test-folder/.git"
2025-03-21T17:20:21.785455098+02:00 [INFO] considering ancestor: "/home/user/Documents/.git"
2025-03-21T17:20:21.785552612+02:00 [INFO] containing git repository: None
2025-03-21T17:20:21.785841446+02:00 [INFO] scanning directory ""
2025-03-21T17:20:21.786145989+02:00 [INFO] scanning directory "some-dir"
2025-03-21T17:20:21.786224157+02:00 [INFO] Using surface present mode FIFO_RELAXED
2025-03-21T17:20:21.786286539+02:00 [INFO] scanning directory "shared-dir"
2025-03-21T17:20:21.852753758+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:20:21.852819684+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:20:21.852863556+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-03-21T17:20:21.928119751+02:00 [INFO] Refreshing at 16666 micros
2025-03-21T17:20:21.929052332+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GT 1030", driver_name: "NVIDIA", driver_info: "550.120" }
2025-03-21T17:20:21.937779134+02:00 [INFO] background scanner removing path "shared-dir/file-3.txt"
2025-03-21T17:20:21.937924152+02:00 [INFO] background scanner removing path "shared-dir/file-4.txt"
2025-03-21T17:20:21.949648612+02:00 [INFO] Using surface present mode FIFO_RELAXED
2025-03-21T17:20:21.949728557+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-03-21T17:20:21.982327489+02:00 [INFO] attempting to start language server "cspell", path: "/home/user/Documents/zed-test-folder", id: 1
2025-03-21T17:20:21.983208923+02:00 [INFO] using project environment variables from CLI. PATH="/home/user/.local/zls/zig-out/bin:/home/user/.local/zig:/home/user/go/bin:/home/user/.local/go/bin:/home/user/.nvm/versions/node/v22.14.0/bin:/home/user/.local/share/zinit/polaris/bin:/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.fzf/bin"
2025-03-21T17:20:21.983598616+02:00 [ERROR] No path or contents found for buffer
2025-03-21T17:20:23.343196503+02:00 [INFO] starting language server process. binary path: "/home/user/.nvm/versions/node/v22.14.0/bin/node", working directory: "/home/user/Documents/zed-test-folder", args: ["/home/user/.local/share/zed/extensions/work/cspell/node_modules/.bin/cspell-lsp", "--stdio"]
2025-03-21T17:20:26.938758269+02:00 [INFO] using project environment variables from CLI. PATH="/home/user/.local/zls/zig-out/bin:/home/user/.local/zig:/home/user/go/bin:/home/user/.local/go/bin:/home/user/.nvm/versions/node/v22.14.0/bin:/home/user/.local/share/zinit/polaris/bin:/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.fzf/bin"
2025-03-21T17:20:26.939018521+02:00 [INFO] perform;
2025-03-21T17:20:26.939098019+02:00 [INFO] authenticate;
2025-03-21T17:20:26.939177554+02:00 [INFO] perform;
2025-03-21T17:20:26.939249898+02:00 [INFO] authenticate;
2025-03-21T17:20:26.93931604+02:00 [INFO] perform;
2025-03-21T17:20:26.939378091+02:00 [INFO] authenticate;
2025-03-21T17:20:26.939425994+02:00 [INFO] perform;
2025-03-21T17:20:26.939479465+02:00 [INFO] authenticate;
2025-03-21T17:20:26.939531285+02:00 [INFO] perform;
2025-03-21T17:20:26.939608719+02:00 [INFO] authenticate;
2025-03-21T17:20:26.93968457+02:00 [INFO] read_command;
2025-03-21T17:20:26.939737861+02:00 [INFO] read_command;
2025-03-21T17:20:26.93980984+02:00 [INFO] perform;
2025-03-21T17:20:26.939869633+02:00 [INFO] authenticate;
2025-03-21T17:20:26.939921851+02:00 [INFO] read_command;
2025-03-21T17:20:26.939976926+02:00 [INFO] read_command;
2025-03-21T17:20:26.940060368+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.940113297+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.940169223+02:00 [INFO] read_command;
2025-03-21T17:20:26.940221353+02:00 [INFO] read_command;
2025-03-21T17:20:26.940273382+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.940336038+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.940429035+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.940482011+02:00 [INFO] send_secondary_commands;
2025-03-21T17:20:26.941027396+02:00 [INFO] socket reader;
2025-03-21T17:20:26.941084475+02:00 [INFO] read_socket;
2025-03-21T17:20:26.941170122+02:00 [INFO] read_socket;
2025-03-21T17:20:26.941312343+02:00 [INFO] socket reader;
2025-03-21T17:20:26.941396171+02:00 [INFO] read_socket;
2025-03-21T17:20:26.94147522+02:00 [INFO] read_socket;
2025-03-21T17:20:26.941781749+02:00 [INFO] socket reader;
2025-03-21T17:20:26.942374083+02:00 [INFO] read_socket;
2025-03-21T17:20:26.942592981+02:00 [INFO] socket reader;
2025-03-21T17:20:26.942677948+02:00 [INFO] read_socket;
2025-03-21T17:20:26.942753637+02:00 [INFO] socket reader;
2025-03-21T17:20:26.942971448+02:00 [INFO] read_socket;
2025-03-21T17:20:26.94307355+02:00 [INFO] read_socket;
2025-03-21T17:20:26.943163797+02:00 [INFO] read_socket;
2025-03-21T17:20:26.943250155+02:00 [INFO] read_socket;
2025-03-21T17:20:26.943374004+02:00 [INFO] socket reader;
2025-03-21T17:20:26.943448847+02:00 [INFO] read_socket;
2025-03-21T17:20:26.9435378+02:00 [INFO] read_socket;
2025-03-21T17:20:26.945826743+02:00 [INFO] read_socket;
2025-03-21T17:20:26.948754506+02:00 [INFO] read_socket;
2025-03-21T17:20:26.951867176+02:00 [INFO] read_socket;
2025-03-21T17:20:26.955225645+02:00 [INFO] read_socket;
2025-03-21T17:20:26.958217273+02:00 [INFO] read_socket;
2025-03-21T17:20:26.96115852+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961252628+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961341634+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961420976+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961495067+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961575762+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961669558+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961760767+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961880217+02:00 [INFO] read_socket;
2025-03-21T17:20:26.961979567+02:00 [INFO] read_socket;
2025-03-21T17:20:26.962058656+02:00 [INFO] read_socket;
2025-03-21T17:20:26.962209977+02:00 [INFO] read_socket;
2025-03-21T17:20:26.962282854+02:00 [INFO] read_socket;
2025-03-21T17:20:26.963341345+02:00 [INFO] read_socket;
2025-03-21T17:20:26.963424566+02:00 [INFO] read_socket;
2025-03-21T17:20:26.963496141+02:00 [INFO] read_socket;
2025-03-21T17:20:26.963579339+02:00 [INFO] read_socket;
2025-03-21T17:20:26.964639621+02:00 [INFO] read_socket;
2025-03-21T17:20:26.964993946+02:00 [INFO] read_socket;
2025-03-21T17:20:43.571028497+02:00 [INFO] background scanner removing path "some-dir/shared-dir"
2025-03-21T17:20:43.571233897+02:00 [INFO] scanning directory "some-dir/shared-dir"
2025-03-21T17:21:04.827144737+02:00 [INFO] background scanner removing path "some-dir/shared-dir/file.txt"
2025-03-21T17:21:53.44796932+02:00 [INFO] background scanner removing path "some-dir/shared-dir/file-2.txt"
2025-03-21T17:23:04.731484007+02:00 [INFO] background scanner removing path "some-dir/shared-dir/file-3.txt"
2025-03-21T17:24:10.441661633+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:24:10.455923423+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:24:10.469179743+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2025-03-21T17:24:10.485737349+02:00 [INFO] Creating a descriptor pool for at most 256 sets
```

</details>
<details>
<summary>
Zed log after restart
</summary>

```
2025-03-21T17:53:47.467692929+02:00 [INFO] ========== starting zed ==========
2025-03-21T17:53:47.478356746+02:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2025-03-21T17:53:47.478433376+02:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2025-03-21T17:53:47.521513674+02:00 [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-03-21T17:53:47.521580256+02:00 [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-03-21T17:53:47.521623381+02:00 [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-03-21T17:53:47.521667709+02:00 [INFO] Enabling Vulkan Portability
2025-03-21T17:53:47.521719666+02:00 [INFO] Enabling color space support
2025-03-21T17:53:47.541969246+02:00 [INFO] Adapter: "NVIDIA GeForce GT 1030"
2025-03-21T17:53:47.542078447+02:00 [INFO] No ray tracing extensions are supported
2025-03-21T17:53:47.567231797+02:00 [INFO] perform;
2025-03-21T17:53:47.567299594+02:00 [INFO] authenticate;
2025-03-21T17:53:47.567366974+02:00 [INFO] read_command;
2025-03-21T17:53:47.567422012+02:00 [INFO] send_secondary_commands;
2025-03-21T17:53:47.567480025+02:00 [INFO] Opening main db
2025-03-21T17:53:47.56808043+02:00 [INFO] new;
2025-03-21T17:53:47.568155462+02:00 [INFO] socket reader;
2025-03-21T17:53:47.568218565+02:00 [INFO] read_socket;
2025-03-21T17:53:47.568286593+02:00 [INFO] read_socket;
2025-03-21T17:53:47.568441841+02:00 [INFO] Opening main db
2025-03-21T17:53:47.568493177+02:00 [INFO] read_socket;
2025-03-21T17:53:47.568633396+02:00 [INFO] read_socket;
2025-03-21T17:53:47.568749124+02:00 [INFO] read_socket;
2025-03-21T17:53:47.568993373+02:00 [INFO] read_socket;
2025-03-21T17:53:47.56905929+02:00 [INFO] keep_updated;
2025-03-21T17:53:47.569700378+02:00 [INFO] read_socket;
2025-03-21T17:53:47.570406514+02:00 [INFO] read_socket;
2025-03-21T17:53:47.570661898+02:00 [INFO] Using git binary path: None
2025-03-21T17:53:47.571226261+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571321099+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571397846+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571465686+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571529229+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571598988+02:00 [INFO] read_socket;
2025-03-21T17:53:47.571652704+02:00 [INFO] read_socket;
2025-03-21T17:53:47.592264665+02:00 [INFO] No prompt template overrides directory found at /home/user/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-03-21T17:53:47.593030027+02:00 [INFO] extensions updated. loading 17, reloading 0, unloading 0
2025-03-21T17:53:47.594995095+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-03-21T17:53:47.597959254+02:00 [INFO] Opening main db
2025-03-21T17:53:47.598159655+02:00 [INFO] perform;
2025-03-21T17:53:47.598230503+02:00 [INFO] authenticate;
2025-03-21T17:53:47.598315113+02:00 [INFO] read_command;
2025-03-21T17:53:47.598406351+02:00 [INFO] send_secondary_commands;
2025-03-21T17:53:47.59935201+02:00 [INFO] socket reader;
2025-03-21T17:53:47.599445067+02:00 [INFO] read_socket;
2025-03-21T17:53:47.599544272+02:00 [INFO] read_socket;
2025-03-21T17:53:47.604999144+02:00 [INFO] read_socket;
2025-03-21T17:53:47.606436357+02:00 [INFO] read_socket;
2025-03-21T17:53:47.606701842+02:00 [INFO] read_socket;
2025-03-21T17:53:47.606936686+02:00 [INFO] read_socket;
2025-03-21T17:53:47.61203528+02:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2025-03-21T17:53:47.612109356+02:00 [INFO] Creating colormap 85983235
2025-03-21T17:53:47.61215267+02:00 [INFO] considering ancestor: "/home/user/Documents/zed-test-folder/.git"
2025-03-21T17:53:47.612239888+02:00 [INFO] considering ancestor: "/home/user/Documents/.git"
2025-03-21T17:53:47.61232741+02:00 [INFO] containing git repository: None
2025-03-21T17:53:47.612543072+02:00 [INFO] scanning directory ""
2025-03-21T17:53:47.612837694+02:00 [INFO] scanning directory "some-dir"
2025-03-21T17:53:47.612912244+02:00 [INFO] scanning directory "shared-dir"
2025-03-21T17:53:47.613178791+02:00 [INFO] scanning directory "some-dir/shared-dir"
2025-03-21T17:53:47.613306591+02:00 [INFO] scanning directory "shared-dir/nested-dir-2"
2025-03-21T17:53:47.613393833+02:00 [INFO] scanning directory "shared-dir/nested-dir"
2025-03-21T17:53:47.613528567+02:00 [INFO] scanning directory "some-dir/shared-dir/nested-dir-2"
2025-03-21T17:53:47.613613297+02:00 [INFO] scanning directory "some-dir/shared-dir/nested-dir"
2025-03-21T17:53:47.615836717+02:00 [INFO] Using surface present mode FIFO_RELAXED
2025-03-21T17:53:47.648927617+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:53:47.649037747+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:53:47.649113915+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-03-21T17:53:47.674329955+02:00 [INFO] Refreshing at 16666 micros
2025-03-21T17:53:47.675691111+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GT 1030", driver_name: "NVIDIA", driver_info: "550.120" }
2025-03-21T17:53:47.687978155+02:00 [INFO] Using surface present mode FIFO_RELAXED
2025-03-21T17:53:47.68804215+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-03-21T17:53:47.764460103+02:00 [INFO] Opening main db
2025-03-21T17:53:47.944570509+02:00 [INFO] set environment variables from shell:/usr/bin/zsh, path:/home/user/.local/zls/zig-out/bin:/home/user/.local/zig:/home/user/go/bin:/home/user/.local/go/bin:/home/user/.local/bin:/home/user/.local/zls/zig-out/bin:/home/user/.local/zig:/home/user/go/bin:/home/user/.local/go/bin:/home/user/.nvm/versions/node/v22.14.0/bin:/home/user/.local/share/zinit/polaris/bin:/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.fzf/bin
2025-03-21T17:53:50.444561768+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:53:50.459633932+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-03-21T17:53:50.474367375+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2025-03-21T17:53:50.490982732+02:00 [INFO] Creating a descriptor pool for at most 256 sets
```

</details>

<details>
<summary>
System info
</summary>

```
System:
  Kernel: 6.8.0-55-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: PRIME H410M-K v: Rev 1.xx serial: <superuser required> part-nu: SKU
    uuid: <superuser required> UEFI: American Megatrends v: 1631 date: 12/14/2023
CPU:
  Info: quad core model: Intel Core i3-10105F bits: 64 type: MT MCP smt: enabled arch: Comet Lake
    rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3843 high: 4201 min/max: 800/4400 cores: 1: 4200 2: 1348 3: 4200 4: 4200
    5: 4200 6: 4200 7: 4200 8: 4201 bogomips: 59197
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] vendor: Micro-Star MSI driver: nvidia v: 550.120
    arch: Pascal pcie: speed: 8 GT/s lanes: 4 ports: active: none off: DVI-D-1 empty: HDMI-A-1
    bus-ID: 01:00.0 chip-ID: 10de:1d01 class-ID: 0300
  Device-2: Logitech Webcam C170 driver: snd-usb-audio,uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 1-7:3 chip-ID: 046d:082b class-ID: 0102
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia,nvidia-nvswitch display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 101 s-size: 483x272mm (19.02x10.71") s-diag: 554mm (21.82")
  Monitor-1: DVI-D-0 res: 1920x1080 hz: 60 dpi: 102 size: 477x268mm (18.78x10.55")
    diag: 547mm (21.54") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia platforms: device: 0 drv: nvidia device: 2 drv: swrast gbm:
    drv: nvidia surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.120 glx-v: 1.4 direct-render: yes
    renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
Audio:
  Device-1: Intel Comet Lake PCH-V cAVS vendor: ASUSTeK driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:a3f0 class-ID: 0403
  Device-2: NVIDIA GP108 High Definition Audio vendor: Micro-Star MSI driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 4 bus-ID: 01:00.1 chip-ID: 10de:0fb8 class-ID: 0403
  Device-3: Logitech Webcam C170 driver: snd-usb-audio,uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 1-7:3 chip-ID: 046d:082b class-ID: 0102
  API: ALSA v: k6.8.0-55-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK RTL8111H
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 03:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: docker0 state: down mac: <filter>
Drives:
  Local Storage: total: 700.51 GiB used: 82.56 GiB (11.8%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB speed: 6.0 Gb/s tech: SSD
    serial: <filter> fw-rev: 0101 scheme: GPT
  ID-2: /dev/sdb vendor: GOODRAM model: SSDPR-CX400-512-G2 size: 476.94 GiB speed: 6.0 Gb/s
    tech: SSD serial: <filter> fw-rev: 181 scheme: GPT
Partition:
  ID-1: / size: 220.71 GiB used: 61.43 GiB (27.8%) fs: btrfs dev: /dev/sda3
  ID-2: /boot size: 1.91 GiB used: 203.6 MiB (10.4%) fs: btrfs dev: /dev/sda2
  ID-3: /boot/efi size: 975.1 MiB used: 6.1 MiB (0.6%) fs: vfat dev: /dev/sda1
  ID-4: /home size: 476.94 GiB used: 20.92 GiB (4.4%) fs: btrfs dev: /dev/sdb1
Swap:
  ID-1: swap-1 type: file size: 31.25 GiB used: 0 KiB (0.0%) priority: -2 file: /swap/swapfile
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 10 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Kingston HX-KB4BL1-US [HYPERX Alloy FPS Pro] type: keyboard,mouse,HID
    driver: hid-generic,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 480mA
    chip-ID: 0951:16d2 class-ID: 0300
  Device-2: 1-7:3 info: Logitech Webcam C170 type: video,audio driver: snd-usb-audio,uvcvideo
    interfaces: 4 rev: 2.0 speed: 480 Mb/s lanes: 1 power: 500mA chip-ID: 046d:082b class-ID: 0102
  Device-3: 1-9:4 info: Trust GXT 117 STRIKE type: mouse driver: hid-generic,usbhid interfaces: 1
    rev: 1.1 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 145f:022b class-ID: 0301
  Hub-2: 2-0:1 info: super-speed hub ports: 4 rev: 3.0 speed: 5 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 48.0 C mobo: N/A gpu: nvidia temp: 34 C
  Fan Speeds (rpm): N/A gpu: nvidia fan: 35%
Repos:
  Packages: 2174 pm: dpkg pkgs: 2160 pm: flatpak pkgs: 14
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/docker.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https: //download.docker.com/linux/ubuntu noble stable
  Active apt repos in: /etc/apt/sources.list.d/git-core-ppa-noble.list
    1: deb [signed-by=/etc/apt/keyrings/git-core-ppa-noble.gpg] https: //ppa.launchpadcontent.net/git-core/ppa/ubuntu noble main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/hluk-copyq-noble.list
    1: deb [signed-by=/etc/apt/keyrings/hluk-copyq-noble.gpg] https: //ppa.launchpadcontent.net/hluk/copyq/ubuntu noble main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com xia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/extrepo_librewolf.sources
    1: deb [arch=amd64 arm64] https: //repo.librewolf.net librewolf main
Info:
  Memory: total: 16 GiB available: 15.54 GiB used: 4.79 GiB (30.8%)
  Processes: 348 Power: uptime: 4h 3m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.3.0 Client: Cinnamon v: 6.4.8 inxi: 3.3.34
```

</details>

<details>
<summary>
Screencast (Zed left, VS Code right):
</summary>

https://github.com/user-attachments/assets/3b66805c-c3ce-4ad0-9479-5cc22cdb5643

</details>

### Zed Version and System Specs

Zed: v0.178.5 (Zed) 
OS: Linux X11 linuxmint 22.1
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GT 1030 || NVIDIA || 550.120

### LINKED ISSUE #45954: Symlinked directory does not update with changes made outside the editor
### Reproduction steps

1. On MacOS, symlink any directory under the project tree.
2. Add a file in the symlinked directory with a terminal
3. File does not appear in the editor file tree

### Current vs. Expected behavior

All files are always synced.

### Zed version and system specs

Zed: v0.217.3+stable.105.80433cb239e868271457ac376673a5f75bc4adb1 (Zed) 
OS: macOS 15.7.3
Memory: 24 GiB
Architecture: aarch64

### Attach Zed log file

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### LINKED ISSUE #48729: A Zed config in a symlinked directory is not applied when I change it
### Reproduction steps

1. Move `~/.config/zed` to another place, i.e. `~/my_dotfiles/zed`
2. Link zed directory `ln -s ~/my_dotfiles/zed ~/.config/zed`
3. Open Editor and `cmd-p` -> `open keymap file` and modify any keybinding or open Zed  Settings (`cmd-,`) and change any setting.
4. Observe that config changes are not applied.
5. Reopen the editor or just `cmd-p` -> `workspace reload`, verify that changes are applied.

The issue can be observed in `Zed Preview v0.223.x`
No issue in `Zed: v0.222.4+stable.147.b385025df963c9e8c3f74cc4dadb1c4b29b3c6f0 (Zed)`

### Current vs. Expected behavior

Current: changes in config are not applied until the workspace is reloaded or the editor is restarted
Expected: changes in config are applied immediately, without reloading the workspace or restarting the editor

### Zed version and system specs

Zed: v0.223.2+preview.146.16e7dc6cfdc74af3d80fab913a694b757c3a3349 (Zed Preview) 
OS: macOS 26.2
Memory: 32 GiB
Architecture: aarch64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by prayanshchh**
Closes #48729, closes #27263, closes #45954

This PR aims to make zed responsive on symlinked directory events outside the editor.

Before you mark this PR as ready for review, make sure that you have:
- [ ] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [ ] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

new-linked-folder is inside /zed-test/zed-project

output of ls -ld new-linked-folder 
`lrwxr-xr-x  1 prayanshchhablani  staff  42 28 Mar 23:20 new-linked-folder -> /Users/prayanshchhablani/new-target-folder`

this shows new-linked-folder is a symlink folder whose target is new-target-folder which is outside the root dir of the project opened in zed.

https://github.com/user-attachments/assets/ffebafc3-2fc4-4293-bdbf-3a894a45e276

Release Notes:

- Fixed file watching of symlinks that point outside of the project/watched directory. Zed should now properly respond to changes in files in symlinked directories

### CODE REVIEW

**Comment by yeskunall** [comment]
@prayanshchh I think the bigger issue is #45954, which would also handle https://github.com/zed-industries/zed/issues/48729. Have you taken a look at #45954? Wdyt?

File: crates/worktree/src/worktree.rs [hunk 1]
```diff
@@ -4662,8 +4737,19 @@ impl BackgroundScanner {
...
+                        .external_symlink_paths_by_target
+                        .entry(Arc::from(canonical_path.clone()))
+                        .or_default();
+                    if !paths.iter().any(|path| path == &child_path) {
+                        paths.push(child_path.clone());
+                    }
+                }
+                // recurse into the real target path when scanning children.
+                if child_metadata.is_dir {
+                    child_scan_abs_path = Arc::from(canonical_path.clone());
```
[the remark this answers is not in the document]
Comment (prayanshchh) [reply crates/worktree/src/worktree.rs]: thanks for this

**Comment by prayanshchh** [comment]
just checking, I am seeing more users facing the symlink issue can we get this reviewed?

**Comment by auwi-nordic** [comment]
This PR may address the same issue as my PR here?
https://github.com/zed-industries/zed/pull/46338

No opinion about which one is better, just thought I'd mention it

**Comment by auwi-nordic** [comment]
This PR may also relate to issue #27263 ?

**Comment by prayanshchh** [comment]
> This PR may address the same issue as my PR here? #46338
> 
> No opinion about which one is better, just thought I'd mention it

no worries lemme just push tests for this and lets review each other's PR just for fun..if u are down

**Comment by prayanshchh** [comment]
> This PR may also relate to issue #27263 ?

yes

File: crates/settings/src/settings_file.rs [hunk 2]
```diff
@@ -58,6 +58,43 @@ mod tests {
...
+            })
+        )
+        .await;
+
+        fs.create_symlink(
+            Path::new("/root/.config/zed"),
+            PathBuf::from("/root/dotfiles/zed"),
+        )
+        .await
+        .unwrap();
```
Comment (probably-neb) [inline crates/settings/src/settings_file.rs:87]: I think we should have some tests coverage for the one to many (i.e. when there are multiple paths under a single entry in `symlink_paths_by_target: HashMap<Arc<Path>, SmallVec<[Arc<RelPath>; 1]>>,`) and longest prefix matching logic. If you want to make this test more comprehensive, or add more tests, I'm ok with either.

File: crates/worktree/src/worktree.rs [hunk 3]
```diff
@@ -4075,6 +4084,63 @@ impl BackgroundScanner {
...
+    fn normalized_events_for_worktree(
+        state: &BackgroundScannerState,
+        root_canonical_path: &SanitizedPath,
+        events: Vec<PathEvent>,
+    ) -> Vec<PathEvent> {
+        let mut normalized_events = Vec::new();
+
+        for event in events {
+            let abs_path = SanitizedPath::new(&event.path);
+            normalized_events.push(event.clone());
```
Comment (probably-neb) [inline crates/worktree/src/worktree.rs]: I think we should prefer mutating `events` here by inserting, rather than duplicating the full Vec in the common case.
The overwhelmingly common case is that there are no symlink path events, so I think we should avoid the allocation, and any symlink related work when there are no symlink events.

I also don't understand why we add the original event, and the new events with the mapped paths.

**Review by probably-neb — CHANGES_REQUESTED** [review]

**Comment by probably-neb** [comment]
sorry for the delay on the follow up review! I got this one and #46338 mixed up

**Comment by auwi-nordic** [comment]
@prayanshchh FYI, probably-ned mentioned he'll be merging this PR rather than mine, as the solution here is better, which I agree with. You don't have to review the implementation in my PR, but you can check if there are tests you want to bring over.

**Comment by prayanshchh** [comment]
will do!

**Comment by prayanshchh** [comment]
> sorry for the delay on the follow up review! I got this one and #46338 mixed up

np!

File: crates/worktree/src/worktree.rs (hunk 3 above)
Comment (prayanshchh) [reply crates/worktree/src/worktree.rs]: I have updated the code, we only keep both when the symlink target is inside the worktree. When the target is outside the worktree, we remove the original event (that has target outside the project) and create a new event with mapped path which gets added to events.

**Comment by prayanshchh** [comment]
lmk if something more is needed from this.

**Comment by Malix-Labs** [comment]
Could ~~"Closes #48729 #27263 #45954"~~ be written in the description instead?

### Edit

Sorry, it needs to be :
> Closes #48729, closes #27263, closes #45954

**Review by probably-neb — APPROVED** [review]

**Comment by probably-neb** [comment]
Great work. Thanks!
