### PR TITLE
Fix clipping at end of line in vim mode with inlay hints

### LINKED ISSUE #23877: Vim normal mode cursor behaves differently when inlay hints are enabled
### Summary

With an inlay hint at the end of a line, pressing `$` to navigate to the end of the line causes the cursor to be placed one column to the right of where it would usually be placed.  This causes things like `a` to start inserting at the beginning of the next line instead of at the end of the current line:

https://github.com/user-attachments/assets/3b7587fd-e72d-4071-8d4e-356cbcf04ae8

### Zed Version and System Specs

Zed: v0.172.0 (Zed Dev)
OS: Linux X11 ubuntu 24.04
Memory: 125.4 GiB
Architecture: x86_64
GPU: NVIDIA RTX 5000 Ada Generation Laptop GPU || NVIDIA || 550.120

### PR DESCRIPTION
**Pull request by ConradIrwin**
Closes #23877

Co-Authored-By: Ben <ben@zed.dev>
Co-Authored-By: Michael <michael@zed.dev>

Release Notes:

- vim: Fix navigating to end of line with inlay hints

### CODE REVIEW

File: crates/editor/src/display_map.rs [hunk 1]
```diff
@@ -1069,12 +1069,9 @@ impl DisplaySnapshot {
...
 
     pub fn clip_at_line_end(&self, point: DisplayPoint) -> DisplayPoint {
-        let mut point = point.0;
-        if point.column == self.line_len(DisplayRow(point.row)) {
-            point.column = point.column.saturating_sub(1);
-            point = self.block_snapshot.clip_point(point, Bias::Left);
-        }
-        DisplayPoint(point)
+        let mut point = self.display_point_to_point(point, Bias::Left);
+        point.column = point.column.saturating_sub(1);
```
Comment (SomeoneToIgnore) [inline crates/editor/src/display_map.rs:1073]: You need clipping after this, in general case, don't you?

Comment (ConradIrwin) [reply crates/editor/src/display_map.rs:1077]: Ugh, thank you!

Time to bring back `Unclipped<>` :D
