### PR TITLE
project_panel: Fix selection not updating for already-visible gitignored files

### LINKED ISSUE #49515: Relocating to a git ignored file doesn't mark the file as selected in the project panel
### Reproduction steps

1. Start Zed
2. Open a file
3. Open another file which is included in `.gitignore`
4. Move between those two files  with `ctrl-tab`
5. Ignored file doesn't get marked as selected in the project panel

## Current behavior

When moving between two files with `ctrl-tab` where one of the file is included in `.gitignore`, the ignored file doesn't get the background color as it normally does when moving to an excluded file. Even moving between the two ignored files the same thing happens.

## Expected behavior

Even though the file is git ignored moving there with `ctrl-tab`, the file should be separated from others as it normally does when using mouse click to open it.

### Zed version and system specs

Zed: 0.220.7 (e5b3d51046a85424108f41c3fc6e5e4da68ea706)
OS: Arch Linux
Memory: 16GiB
Architecture: x86-64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by skyline69**
## Summary
- Keep auto-reveal behavior for ignored files unchanged (no implicit reveal).
- When an ignored file is already visible in the project panel, mark it as selected on `ActiveEntryChanged`.
- Add regression coverage for switching back to a visible gitignored file.

## Testing
- `project_panel_tests::test_autoreveal_and_gitignored_files`
- `project_panel_tests::test_gitignored_and_always_included`
- `project_panel_tests::test_explicit_reveal`

Closes #49515

Release Notes:

- Fixed project panel not updating selection when switching to a gitignored file that was already visible.

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -5966,12 +5966,26 @@ impl ProjectPanel {
...
+
+            self.selection = Some(SelectedEntry {
+                worktree_id,
+                entry_id,
+            });
+            self.marked_entries.clear();
+            self.marked_entries.push(SelectedEntry {
+                worktree_id,
+                entry_id,
+            });
```
Comment (smitbarmase) [inline crates/project_panel/src/project_panel.rs:5986]: Can we add `self.autoscroll(cx);` here too?

File: crates/project_panel/src/project_panel_tests.rs [hunk 2]
```diff
@@ -4843,6 +4843,43 @@ async fn test_autoreveal_and_gitignored_files(cx: &mut gpui::TestAppContext) {
...
         "When a gitignored entry is explicitly revealed, it should be shown in the project tree"
     );
+
+    panel.update(cx, |panel, cx| {
+        panel.project.update(cx, |_, cx| {
+            cx.emit(project::Event::ActiveEntryChanged(Some(dir_2_file)))
+        })
+    });
+    cx.run_until_parked();
+
```
Comment (smitbarmase) [inline crates/project_panel/src/project_panel_tests.rs:4874]: I think we should assert the immediate state here. It would be more thorough to assert that `dir_2_file` is selected and marked. That way we can confirm that switch actually happened.

**Review by smitbarmase — CHANGES_REQUESTED** [review]

File: crates/project_panel/src/project_panel.rs [hunk 3]
```diff
@@ -5983,14 +5998,14 @@ impl ProjectPanel {
...
 
-        let worktree_id = worktree.id();
         self.expand_entry(worktree_id, entry_id, cx);
         self.update_visible_entries(Some((worktree_id, entry_id)), false, true, window, cx);
         self.marked_entries.clear();
         self.marked_entries.push(SelectedEntry {
             worktree_id,
             entry_id,
         });
+        self.autoscroll(cx);
```
Comment (smitbarmase) [inline crates/project_panel/src/project_panel.rs]: Actually, we don't need auto scroll here because `self.update_visible_entries` handles that for us internally. It calls `auto scroll` since we pass `true`.

The reason we don't use `update_visible_entries` in our code path is because there we are not changing anything about entries visually, which, in this case, `expand_entry` does.

**Review by smitbarmase — CHANGES_REQUESTED** [review]
Rest looks good to me, just a minor nit.

**Review by smitbarmase — APPROVED** [review]
Thanks!

**Comment by skyline69** [comment]
> Thanks!

You're welcome!
