### PR TITLE
picker: Prevent clicking non-selectable entries from confirming selection

### LINKED ISSUE #50627: "Recent Projects" picker title is weird
### Reproduction steps

1. Press cmd-opt-o (`projects::OpenRecent`)

### Current vs. Expected behavior

Image

There are a few things wrong here:

- The "Recent Projects" title is almost the _smallest_ UI element, so it looks off
- Clicking the title counts as clicking the first item in the list

I'm confused why the design differs from the other pickers (e.g. the command palette and file finder). Just mention "recent projects" in the placeholder text and get rid of the title entirely.

### Zed version and system specs

Zed: v0.225.12+stable.191.8f51e075bdf969725ce8fa2a032a19cdb821b9fb (Zed) 
OS: macOS 15.7.4
Memory: 16 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by Dnreikronos**
Closes #50627

Before you mark this PR as ready for review, make sure that you have:
- [x] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [ ] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

### Videos:
Before:
https://drive.google.com/file/d/1PahGhfx-wq9cyNqqMlctb9Np7M1Meo71/view?usp=sharing
After:
https://drive.google.com/file/d/135W6MQ9hKBurw5Z7YpHQQhoQwkh1NvUb/view?usp=sharing

Release Notes:

- Fixed clicking on non-selectable picker entries (e.g. section headers) confirming the currently selected item.

### CODE REVIEW

**Review by MrSubidubi — APPROVED** [review]
Thanks, this looks like a good fix for the issue at hand. 

I'd like if we could add a test for this behavior to ensure that this does not regress. Could you look into that? 

Also, one thing that popped up while I looked at this is that we actually show a pointer cursor when hovering the element despite it not being clickable. Could I interest you into looking to fix that as well perhaps? Not insisting, just curious.

Edit: Hiding because wrong button.

**Review by MrSubidubi — CHANGES_REQUESTED** [review]
Thanks, this looks like a good fix for the issue at hand.

I'd like if we could add a test for this behavior to ensure that this does not regress. Could you look into that?

Also, one thing that popped up while I looked at this is that we actually show a pointer cursor when hovering the element despite it not being clickable. Could I interest you into looking to fix that as well perhaps? Not insisting, just curious.

File: crates/picker/src/picker.rs [hunk 1]
```diff
@@ -747,16 +750,17 @@ impl<D: PickerDelegate> Picker<D> {
     }
 
     fn render_element(
-        &self,
+        &mut self,
```
Comment (MrSubidubi) [inline crates/picker/src/picker.rs]: Not your fault here, but let's revert this and change the `can_select` method on the trait to only take `&self` instead of the mutable reference

File: crates/picker/src/picker.rs [hunk 2]
```diff
@@ -850,6 +854,184 @@ impl<D: PickerDelegate> Picker<D> {
...
+    }
+
+    fn init_test(cx: &mut TestAppContext) {
+        cx.update(|cx| {
+            let store = settings::SettingsStore::test(cx);
+            cx.set_global(store);
+            theme::init(theme::LoadThemes::JustBase, cx);
+            editor::init(cx);
+        });
+    }
```
Comment (MrSubidubi) [inline crates/picker/src/picker.rs:955]: Have you checked whether we actually need all of this? I'd suspect we might actually not, but might be proven wrong (and happy to). Would like to avoid pulling in the new dependency if we can.

**Review by MrSubidubi — CHANGES_REQUESTED** [review]
Very very nice, thanks for looking into this and the quick follow-up!

Two minor comments and we can 🚢

File: crates/picker/src/picker.rs (hunk 1 above)
Comment (Dnreikronos) [reply crates/picker/src/picker.rs]: Done! Changed **can_select** on the **PickerDelegate** trait to take **&self** instead of **&mut self**, and updated all 9 implementations across the codebase to match. This lets **render_element** stay as **&self** since **can_select** no longer requires a mutable borrow. Since **can_select** is defined on the trait, changing its signature requires updating every implementation, otherwise the compiler rejects the mismatch. This affected 8 other files across **agent_ui, rules_library, recent_projects, and sidebar**. None of them actually needed **&mut self**, they were just following the original trait signature.

File: crates/picker/src/picker.rs (hunk 2 above)
Comment (Dnreikronos) [reply crates/picker/src/picker.rs:955]: Checked and removed ctor, env_logger, and serde_json from dev-dependencies — none were actually needed. ctor and env_logger were only used for an init_logger helper which isn't required for the tests to run. serde_json wasn't used at all. The remaining dev-dependencies (editor, gpui, settings) are necessary since editor::init registers the ErasedEditor factory that the picker needs, and settings/theme::init are required by the editor.

**Review by MrSubidubi — APPROVED** [review]
Awesome work here and very much appreciate the work that went into the test. Thank you!
