### PR TITLE
Unify selection directions when performing `editor: select all matches`

### LINKED ISSUE #19569: editor::SelectAllMatches cursor is inconsistent with origin match
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in the multi-buffer, if i see

```
foo bar baz
foo bar baz
foo bar baz
```

and select the first bar from right to left so the cursor is here

```
foo |bar baz
foo bar baz
foo bar baz
```

then choose `editor::SelectAllMatches`, the other cursors appear here

```
foo |bar baz
foo bar| baz
foo bar| baz
```

i'd expect them to appear here

```
foo |bar baz
foo |bar baz
foo |bar baz
```

### Environment

Zed: v0.157.5 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by JosephTLyons**
Closes https://github.com/zed-industries/zed/issues/19569

Current behavior:

https://github.com/user-attachments/assets/1de764c9-7c62-49ad-b24b-6e85760857db

After PR:

https://github.com/user-attachments/assets/651d8e50-95e2-4513-852b-9557d00d2b62

Release Notes:

- Unified selection directions when performing `editor: select all matches`.

### CODE REVIEW

File: crates/editor/src/editor_tests.rs [hunk 1]
```diff
@@ -5236,11 +5236,27 @@ async fn test_select_all_matches(cx: &mut gpui::TestAppContext) {
     init_test(cx, |_| {});
 
     let mut cx = EditorTestContext::new(cx).await;
+
+    // Test carrot-only selections
```
Comment (maxdeviant) [inline crates/editor/src/editor_tests.rs:5240]: Should this be "caret"? Or does "carrot" have a meaning here that I'm not aware of? 😄 

```suggestion
    // Test caret-only selections
```

Comment (JosephTLyons) [reply crates/editor/src/editor_tests.rs:5240]: 🥕 .... 💀
