### PR TITLE
tasks: Use environment variables from project

### LINKED ISSUE #12125: Running tests by UI button does not read environment variables
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running tests by UI button does not read environment variables

### Environment

Zed: v0.136.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

## By `cargo test`
Screenshot 2024-05-22 at 21 18 51

## By the UI button

Screenshot 2024-05-22 at 21 19 00

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #12125 and addresses what's described in here:

- https://github.com/zed-industries/zed/issues/4977#issuecomment-2162094388

Before the changes in this PR, when running tasks, they inherited the Zed process environment, but that might not be the process environment that you'd get if you `cd` into a project directory.

We already ran into that problem with language servers and we fixed it by loading the shell environment in the context of a projects root directory and then passing that to the language servers when starting them (or when looking for their binaries).

What the change here does is to add the behavior for tasks too: we use the project-environment as the base environment with which to spawn tasks. Everything else still works the same, except that the base env is different.

TODOs:

- [x] Add tests
- [x] Get it working over collab
- [x] See if the environment loading can be consolidated and/or cached on the project, so that we don't have to pay that cost every time we launch a task.

Release Notes:

- Improved the environment-variable detection when running tasks so that tasks can now access environment variables as if the task had been spawned in a terminal that `cd`ed into a project directory. That means environment variables set by `direnv`/`asdf`/`mise` and other tools are now picked up. ([#12125](https://github.com/zed-industries/zed/issues/12125)).

Demo:

https://github.com/user-attachments/assets/8bfcc98f-0f9b-4439-b0d9-298aef1a3efe

### CODE REVIEW

File: crates/task/src/task_template.rs [hunk 1]
```diff
@@ -184,8 +184,12 @@ impl TaskTemplate {
             .context("hashing task variables")
             .log_err()?;
         let id = TaskId(format!("{id_base}_{task_hash}_{variables_hash}"));
+
+        let mut env = cx.project_env.clone();
+        env.extend(self.env.iter().map(|(k, v)| (k.to_owned(), v.to_owned())));
```
Comment (osiewicz) [inline crates/task/src/task_template.rs:189]: I wonder if 
```suggestion
        env.extend(self.env.clone().into_iter());
```
could work too.

Comment (mrnugget) [reply crates/task/src/task_template.rs]: Works!
