### PR TITLE
Fix project_panel::NewSearchInDirectory to work on files

### LINKED ISSUE #23383: project_panel::NewSearchInDirectory should work on files not just folders
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:
1. Click on a file in the project panel.
2. Trigger the `project_panel::NewSearchInDirectory` action (`cmd-shift-f`)
3. Note nothing happens.

Expected: Search all files is spawned with `include` set to the parent directory of the current file.

### Zed Version and System Specs

Zed: v0.171.0 (Zed Nightly 7302be8ebdb6869a98c91ebaa1f50e1f01078d02)
OS: macOS 15.2.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

N/A

### PR DESCRIPTION
**Pull request by wblazer**
Closes #23383

This PR changes `project_panel::NewSearchInDirectory` to open project search filtered by the parent directory when triggered on a file, rather than doing nothing.

Release Notes:

- Improved `project_panel::NewSearchInDirectory` to search the parent directory when triggered on a file

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -2119,24 +2119,28 @@ impl ProjectPanel {
...
-                    let mut full_path = PathBuf::from(worktree.read(cx).root_name());
-                    full_path.push(&entry.path);
-                    Arc::from(full_path)
-                } else {
-                    entry.path.clone()
-                };
+            let dir_path = if entry.is_dir() {
+                entry.path.clone()
+            } else {
+                Arc::from(entry.path.parent().unwrap_or_else(|| Path::new("")))
```
Comment (SomeoneToIgnore) [inline crates/project_panel/src/project_panel.rs:2125]: > .unwrap_or_else(|| Path::new("")))

What are we trying to search in here?
Would it be better to exit prematurely instead or follow `include_root = true` branch?

Comment (wblazer) [reply crates/project_panel/src/project_panel.rs:2125]: My intention was to have it still open search with no include filter if there is no parent. I wasn't sure when this case would come up, but I see now that this fallback is used if you use `workspace: add folder to project`, select a file, then trigger a new search in directory on that file. Currently, it results in an include filter of "file_at_root/", which is not what we want.

So, the choice is to exit prematurely or open up a search without following the include_root path. I'm leaning towards exiting prematurely as I'm not sure the added complexity is worth it for this edge case. What do you think?

Potential approach if we want to still open up search in this case:
```rs
            let mut include_root = self.project.read(cx).visible_worktrees(cx).count() > 1;

            let dir_path = if entry.is_dir() {
                entry.path.clone()
            } else {
                match entry.path.parent() {
                    Some(parent) => Arc::from(parent),
                    None => {
                        include_root = false;
                        Arc::from(Path::new(""))
                    }
                }
            };

            let dir_path = if include_root {
            ...
```

Comment (wblazer) [reply crates/project_panel/src/project_panel.rs:2125]: Yeah I'd be fine with explicitly opening the project search rather than using include_root as a mutable flag. More verbose but probably easier to follow.

If I'm understanding you right, your suggestion is to use `ProjectSearchView::new_search()` rather than `ProjectSearchView::new_search_in_directory()`? If so, one thing to consider is that using `new_search()` will open a search with filters disabled. This is different than `new_search_in_directory()` called with an empty path, which opens with the filters enabled.
result of just search
result of search in directory

I think it would be better to continue using `new_search_in_directory()` with an empty path for more consistent behavior. I can also add a couple comments to make it easier to understand at a glance. So we would have:

```rs
  let dir_path = if entry.is_dir() {
      entry.path.clone()
  } else {
      // entry is a file, search its parent directory
      match entry.path.parent() {
          Some(parent) => Arc::from(parent),
          None => {
              // File at root, open search with empty filter
              self.workspace
                  .update(cx, |workspace, cx| {
                      search::ProjectSearchView::new_search_in_directory(
                          workspace, Path::new(""), window, cx
                      );
                  })
                  .ok();
              return;
          }
      }
  };
...
```

Thoughts?

Comment (SomeoneToIgnore) [reply crates/project_panel/src/project_panel.rs:2125]: Sure, let's follow that way, as overcomplicating this task is also not very good.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!
