### PR TITLE
gpui: Fix bottom-aligned scroll bar disappearing

### LINKED ISSUE #51198: gpui: bottom-aligned ListState scrollbar thumb disappears at the end
### Reproduction steps
1. Build any GPUI app that uses `gpui::list::ListState` with `ListAlignment::Bottom` and renders a vertical scrollbar via `gpui_component::scroll::ScrollableElement::vertical_scrollbar(&list_state)`.
2. Populate the list with enough variable-height items to overflow the viewport.
3. Scroll the list all the way to the bottom, or drag the scrollbar thumb to the bottom.
4. Observe the scrollbar thumb/state at the bottom edge.

### Current vs. Expected behavior
Current behavior: when a bottom-aligned `ListState` reaches the end, the scrollbar thumb can disappear or render as if the list has scrolled past the valid range. This looks like the scrollbar offset is being computed outside the legal `0..max_offset` range when `ListAlignment::Bottom` collapses the end position into `logical_scroll_top = None`.

Expected behavior: the scrollbar thumb should remain visible and stay pinned at the bottom of the track when the list is at its end.

Relevant source in the current `main` checkout (`f18567c1f0a4d2db2dd121202d4a4d84a2d9d02d`):
- `crates/gpui/src/elements/list.rs:506-519` (`scroll_px_offset_for_scrollbar`)
- `crates/gpui/src/elements/list.rs:593-603` (`logical_scroll_top` for `ListAlignment::Bottom`)
- `crates/gpui/src/elements/list.rs:940-955` (`set_offset_from_scrollbar`)

The implementation still represents the bottom-most position as `item_ix = items.count, offset_in_item = 0`, and `scroll_px_offset_for_scrollbar()` then turns that into an offset derived from full content height instead of `content_height - viewport_height`.

### Zed version and system specs
Zed source checkout: `f18567c1f0a4d2db2dd121202d4a4d84a2d9d02d`
OS: Windows 11
Architecture: x86_64

I have not yet confirmed whether this is reachable from a stock clean Zed workflow, but the bug is still present in the current `crates/gpui` implementation and is reproducible in a GPUI app that uses bottom-aligned lists with a scrollbar.

### Attach Zed log file
Not applicable; this appears to be a deterministic UI logic bug in `crates/gpui` rather than a runtime crash/logging issue.

### Relevant Zed settings
Not applicable.

### Relevant Keymap
Not applicable.

### (for AI issues) Model provider details
Not applicable.

### PR DESCRIPTION
**Pull request by feitreim**
Closes #51198

This actually doesn't effect any of the scrollbars in Zed, as they have a separate handler that prevents this issue from occurring 
in `crates/ui/src/components/scrollbar.rs`, line 856
```rust
let current_offset = current_offset
      .along(axis)
      .clamp(-max_offset, Pixels::ZERO)
      .abs();
```

so it is gpui specific. I still added a test case and I have a manual test script:
<details><summary>Details</summary>
<p>

```rust
//! Reproduction of the scrollbar-offset bug in bottom-aligned `ListState`.
//!
//! Run with: cargo run -p gpui --example list_bottom_scrollbar_bug
//!
//! The list starts pinned to the bottom. Before the fix, the red scrollbar
//! thumb was pushed off the bottom of the track (invisible).
use gpui::{
    App, Bounds, Context, ListAlignment, ListState, Window, WindowBounds, WindowOptions, div, list,
    prelude::*, px, rgb, size,
};
use gpui_platform::application;

const ITEM_COUNT: usize = 40;
const COLORS: [u32; 4] = [0xE8F0FE, 0xFCE8E6, 0xE6F4EA, 0xFEF7E0];

struct BugRepro {
    list_state: ListState,
}

impl BugRepro {
    fn new() -> Self {
        let list_state = ListState::new(ITEM_COUNT, ListAlignment::Bottom, px(5000.));
        Self { list_state }
    }
}

impl Render for BugRepro {
    fn render(&mut self, _window: &mut Window, _cx: &mut Context<Self>) -> impl IntoElement {
        let state = &self.list_state;

        let max_offset = state.max_offset_for_scrollbar().y;
        let raw_offset = -state.scroll_px_offset_for_scrollbar().y;
        let viewport_h = state.viewport_bounds().size.height;
        let content_h = max_offset + viewport_h;

        let thumb_h = if content_h > px(0.) {
            ((viewport_h / content_h) * viewport_h).max(px(20.))
        } else {
            viewport_h
        };

        let thumb_top = if max_offset > px(0.) {
            (raw_offset / max_offset) * (viewport_h - thumb_h)
        } else {
            px(0.)
        };

        div()
            .size_full()
            .flex()
            .flex_row()
            .bg(rgb(0xffffff))
            .text_color(rgb(0x333333))
            .text_xl()
            .child(
                div().flex_1().h_full().child(
                    list(state.clone(), |ix, _window, _cx| {
                        let height = if ix % 4 == 0 { px(70.) } else { px(40.) };
                        let bg = COLORS[ix % COLORS.len()];
                        div()
                            .h(height)
                            .w_full()
                            .bg(rgb(bg))
                            .border_b_1()
                            .border_color(rgb(0xcccccc))
                            .px_2()
                            .flex()
                            .items_center()
                            .child(format!("Item {ix}"))
                            .into_any()
                    })
                    .h_full()
                    .w_full(),
                ),
            )
            .child(
                div()
                    .w(px(14.))
                    .h_full()
                    .bg(rgb(0xe0e0e0))
                    .relative()
                    .child(
                        div()
                            .absolute()
                            .right(px(0.))
                            .top(thumb_top)
                            .h(thumb_h)
                            .w(px(14.))
                            .rounded_sm()
                            .bg(rgb(0xff3333)),
                    ),
            )
    }
}

fn main() {
    application().run(|cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(400.), px(500.)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |_, cx| cx.new(|_| BugRepro::new()),
        )
        .unwrap();
        cx.activate(true);
    });
}
```

</p>
</details> 

where I was able to test it out, here is a video of the new working behavior.

https://github.com/user-attachments/assets/02e26308-da18-418b-97fc-dd52a3325dab

Release Notes:

- gpui: fixed a bug where the scollbar would disappear when using a bottom aligned list.

### CODE REVIEW

File: crates/gpui/src/elements/list.rs [hunk 1]
```diff
@@ -493,18 +493,21 @@ impl ListState {
...
     }
 
     /// Returns the current scroll offset adjusted for the scrollbar
     pub fn scroll_px_offset_for_scrollbar(&self) -> Point<Pixels> {
         let state = &self.0.borrow();
+
+        // Bottom-aligned lists use `None` as a sentinel meaning "pinned to the
+        // end." `logical_scroll_top()` resolves that to `item_ix = items.count`,
+        // which makes the cursor overshoot to the full content height. Return
+        // the max offset directly for this case.
```
Comment (mikayla-maki) [inline crates/gpui/src/elements/list.rs]: Let's clean up or remove this comment, doesn't seem like it applies to the current code?

File: crates/gpui/src/elements/list.rs [hunk 2]
```diff
@@ -1449,4 +1460,41 @@ mod test {
...
+                .h_full()
+            }
+        }
+
+        cx.draw(point(px(0.), px(0.)), size(px(100.), px(100.)), |_, cx| {
+            cx.new(|_| TestView(state.clone())).into_any_element()
+        });
+
+        // Bottom-aligned lists start pinned to the end: logical_scroll_top returns
+        // item_ix == item_count, meaning no explicit scroll position has been set.
```
Comment (mikayla-maki) [inline crates/gpui/src/elements/list.rs:1489]: This comment seems a little unneeded?

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Review by mikayla-maki — APPROVED** [review]
