### PR TITLE
Set window icon on X11

### LINKED ISSUE #30644: [Linux] Broken desktop file on MX Linux XFCE via standard install
### Summary

There is no active window icon when launching zed installed the standard way on MX Linux XFCE.

### Description

Steps to reproduce:
1. Install Zed via script
2. Launch Zed
3. No icon on panel 

Expected Behavior:

Display the Zed Icon

Actual Behavior:

Whsiker menu presumably falls back to the default generic window icon

Image

Zed is the one left of Discord.

OS details:

MX Linux, XFCE Desktop environment, fish shell

### Zed Version and System Specs

Zed: v0.185.16 (Zed) 
OS: Linux X11 debian 12
Memory: 13.5 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.8-1mx23ahs

### LINKED ISSUE #37961: Missing Application Icon in KDE Task Switcher
### Summary

Zed application icon is missing in the task switcher due a missing field in the provided `zed.desktop` file template

### Description

When using the task switching (alt + tab) on KDE (and possibly other environments), Zed windows are missing the Zed icon and instead show a placeholder X11 icon

**Steps to reproduce:**
1. Install zed through the system package manager
2. alt + tab while zed is open
3. notice that the application icon is the placeholder X11 icon

Expected:

Image

Actual: 

Image

### Root cause

This is due to a missing `StartupWMClass` field in the provided `zed.desktop` file template.

This is very likely the cause of issue #30644 as well

### Zed Version and System Specs

Zed: v0.198.5 (Zed) 
OS: Linux X11 manjaro unknown
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 25.1.7-arch1.1

### PR DESCRIPTION
**Pull request by kitt-cat**
Closes #30644

Many X11 environments expect a window icon to be supplied [as pixel data on a window property `_NET_WM_ICON`](https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html#id-1.6.13).

I confirmed this change fixes the icon in xfce4 for me, I think its likely it also fixes https://github.com/zed-industries/zed/issues/37961 but I haven't tested it.

## Questions
* [`image::RgbaImage` is exposed to the public API of gpui](https://github.com/zed-industries/zed/pull/40096/files#diff-318f166d72ad9476bd0a116446f5db3897fc1a4eb1d49aaf8105608bcf49ea53R1136). I would guess this is undesirable, but I wasn't sure of the best way to use gpui's native `Image` type..
* Currently [the icon is embedded into the binary](https://github.com/zed-industries/zed/pull/40096/files#diff-89af0b4072205c53b518aa977d6be48997e1a51fa4dbf06c7ddd1fec99fc510eR101). If this is undesirable, zed could alternatively implement [icon lookup](https://specifications.freedesktop.org/icon-theme-spec/latest/#icon_lookup) and try and find its icon from the system at runtime.

## Future work
* It might be nice to expose a `set_window_icon` method also (it could be used for example to show dirty state in the icon somehow), but I'm unfamiliar with what other platforms support and if this could be beyond X11 (there is a [wayland protocol](https://wayland.app/protocols/xdg-toplevel-icon-v1) though!).

Release Notes:

- Fixed missing window icon on X11

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks for working on this!  It does seem good to set NET_WM_ICON.  I pushed a few misc fixes / improvements.

Is it necessary to resize the icons to 256x256?  I think I'd prefer to just leave them as 512x512 and leave it up to the DE to resize as needed.  Then the changes to `build.rs` could be skipped and this could be used:

```
            const BYTES: &[u8] = {
                let release_channel = option_env!("RELEASE_CHANNEL");
                match release_channel {
                    Some(release_channel) => match release_channel.as_bytes() {
                        b"stable" => include_bytes!("../resources/app-icon.png"),
                        b"preview" => include_bytes!("../resources/app-icon-preview.png"),
                        b"nightly" => include_bytes!("../resources/app-icon-nightly.png"),
                        _ => include_bytes!("../resources/app-icon-dev.png"),
                    },
                    _ => include_bytes!("../resources/app-icon-dev.png"),
                }
            };
```

Alternatively, if it is important to use that size, could add files like `app-icon@0.5x.png`.

> [image::RgbaImage is exposed to the public API of gpui](https://github.com/zed-industries/zed/pull/40096/files#diff-318f166d72ad9476bd0a116446f5db3897fc1a4eb1d49aaf8105608bcf49ea53R1136). I would guess this is undesirable, but I wasn't sure of the best way to use gpui's native Image type..

I think that's fine, `image::Frame` is already involved in gpui's public API.

> Zed could alternatively implement [icon lookup](https://specifications.freedesktop.org/icon-theme-spec/latest/#icon_lookup) and try and find its icon from the system at runtime.

Would this allow GPUI apps to always set their NET_WM_ICON to the same icon as their desktop file?  Would be quite cool if so - such a mechanism would need to do its work on the background thread.  However, this approach seems fine for now.

**Comment by kitt-cat** [comment]
> Is it necessary to resize the icons to 256x256?

Not really! Though 512x512 feels a little on the big side in my environment. I took an informal poll of applications on my computer, all stayed at 256 or below.. that is all but one, vscode puts a whole entire 1024x1024 icon there :joy_cat: 

Resizing aside, I thought the build script was a nice way to catch any issues with the decoding at build time.

> Would this allow GPUI apps to always set their NET_WM_ICON to the same icon as their desktop file

*Always* might be a stretch, there's the assumption the app is packaged in a way where its able to read the right paths, (and the icon lookup implementation is [well tested](https://redirect.github.com/zeroeightysix/icon/pull/2) on common edge cases) but... my gut feeling is its a reasonable expectation for most packaging systems (I checked [flatpak and it seems fine](https://docs.flatpak.org/en/latest/conventions.html?highlight=icons))

**Comment by smitbarmase** [comment]
I tried MX Linux (XFCE) using the install script to reproduce this so I could verify whether this PR fixes it, but I wasn’t able to reproduce the issue. Which distro are you using?

**Comment by kitt-cat** [comment]
I'm on archlinux
- `xfce4-session 4.20.3 (Xfce 4.20)`
- `Zed: v0.219.0+dev.1c33dbcb667e6c019408b165740aef4008bbceb8` (latest `main` built with `--release`)

Here's the commands I'm running:
```zsh
Xephyr -screen 900x700 :1 &
DISPLAY=:1 xfce4-session &
DISPLAY=:1 zed
```

There is a zed icon in the application menu (it reads the `.desktop` file for that); but in the taskbar and window switcher UI (<kbd>alt</kbd>+<kbd>tab</kbd>) there are generic icons:

screenshot of an xfce4 desktop with zed running, showing generic icons in the taskbar and alt tab menu

File: crates/zed/build.rs [hunk 1]
```diff
@@ -79,4 +79,49 @@ fn main() {
             std::process::exit(1);
         }
     }
+
+    #[cfg(target_os = "linux")]
+    {
```
Comment (yara-blue) [inline crates/zed/build.rs]: could you extract this into a function? Main is getting kinda long.

**Review by yara-blue — DISMISSED** [review]
Please resolve the conflicts, extract a function in build.rs and then we can merge :)

if you want too feel free to include the change mentioned by @mizhka as well. But that can be a separate PR too.

**Comment by kitt-cat** [comment]
Hello again, happy to!

When I was resolving conflicts I noticed the `image` crate was made an optional dependency in 8c0b088366545e5050711066a4be666266f28110). This PR currently makes it a non-optional runtime dependency, but I think it could be made conditional on linux/freebsd only, if you think that would be worthwhile?

I'd be happy to squash the commits as well if that would be helpful.

**Comment by yara-blue** [comment]
> I think it could be made conditional on linux/freebsd only,

I dont think its worth it for zed, given we use the image crate in a bunch of other places. Feel free to make it unconditional again!


> I'd be happy to squash the commits as well if that would be helpful.

no need, we always squash merge.

**Review by cameron1024 — APPROVED** [review]
Thanks for the contribution 😁 

Looks good
