### PR TITLE
client: Implement Socks identification and authorization

### LINKED ISSUE #28792: Support Authentication for SOCKS5 Proxy
### Summary

It seems like Sign-in of Zed ignores the username/password of SOCKS5 "proxy" provided in the configuration. Assistant, though, works correctly.

### Description

Steps to reproduce:
1. Have a SOCKS5 proxy that requires authorization.
2. Type `"proxy": "socks5://USERNAME:PASSWORD@HOSTNAME:PORT",` in the settings.
3. Restart Zed

Expected Behavior:
For the sign-in to work properly.

Actual Behavior:
Sign-in fails with an error:
```
[2025-04-15T19:02:09+03:00 ERROR zed] error connecting to socks Connection not allowed by ruleset

Caused by:
    error connecting to socks Connection not allowed by ruleset
```

However, remote AI assistant works just fine, successfully connecting over authorized SOCKS5.

Using non-SOCKS5 completely mitigates the issue.

### Zed Version and System Specs

Zed: v0.179.4 (Zed) 
OS: Linux Wayland nixos 25.05
Memory: 15.4 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 25.0.3

### PR DESCRIPTION
**Pull request by tidely**
Closes #28792 

supersedes #28854 

- Adds support for Socks V4 Identification using a userid, and Authorization using a username and password on Socks V5.
- Added tests for parsing various Socks proxy urls.
- Added a test for making sure a misconfigured socks proxy url doesn't expose the user by connecting directly as a fallback.

Release Notes:

- Added support for identification and authorization when using a sock proxy
- breaking change: Unsupported proxies now throw an error instead of silently connecting directly

### CODE REVIEW

File: crates/client/src/socks.rs [hunk 1]
```diff
@@ -66,3 +109,67 @@ impl<T: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static> A
...
+    assert!(port == 1080);
+    assert!(matches!(version, SocksVersion::V5(None)))
+}
+
+#[test]
+fn parse_socks5_with_authorization() {
+    let proxy = Url::parse("socks5://username:password@proxy.example.com:1080").unwrap();
+
+    let ((host, port), version) = parse_socks_proxy(&proxy).unwrap();
+    assert!(host == "proxy.example.com");
```
[the remark this answers is not in the document]
Comment (tidely) [reply crates/client/src/socks.rs]: Applied the change to all the tests!

File: crates/client/src/socks.rs [hunk 2]
```diff
@@ -66,3 +109,67 @@ impl<T: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static> A
     for T
 {
 }
+
+#[test]
```
[the remark this answers is not in the document]
Comment (tidely) [reply crates/client/src/socks.rs]: done!

File: crates/client/src/socks.rs [hunk 3]
```diff
@@ -3,59 +3,102 @@ use anyhow::{Result, anyhow};
...
-            )
-            .await
-            .map_err(|err| anyhow!("error connecting to socks {}", err))?;
-            Box::new(stream) as Box<dyn AsyncReadWrite>
+    // Connect directly when there is no proxy
+    let Some(proxy) = proxy else {
+        return Ok(Box::new(tokio::net::TcpStream::connect(rpc_host).await?));
+    };
+
+    let Some((socks_proxy, version)) = parse_socks_proxy(proxy) else {
```
Comment (SomeoneToIgnore) [inline crates/client/src/socks.rs:35]: We can remove this nesting with

```rs
use anyhow::Context as _;

let (socks_proxy, version) = parse_socks_proxy(proxy).with_context(|| format!("Parsing proxy url '{proxy}'"))?;
// or use `.context("parsing proxy url")?` if `url` is not secure to print due to the risk of leaking the credentials.
```

and might be good to do `.context` on more `?` around, such as `TcpStream::connect` or maybe even `.map_err(|err| anyhow!`?

**Review by SomeoneToIgnore — COMMENTED** [review]
Looks good, thank you.

Have left some styling comments, let's fix these and merge.

File: crates/client/src/socks.rs [hunk 4]
```diff
@@ -3,59 +3,102 @@ use anyhow::{Result, anyhow};
...
-    let stream = match parse_socks_proxy(proxy) {
-        Some((socks_proxy, SocksVersion::V4)) => {
-            let stream = Socks4Stream::connect_with_socket(
-                tokio::net::TcpStream::connect(socks_proxy).await?,
-                rpc_host,
-            )
-            .await
-            .map_err(|err| anyhow!("error connecting to socks {}", err))?;
-            Box::new(stream) as Box<dyn AsyncReadWrite>
+    // Connect directly when there is no proxy
```
[the remark this answers is not in the document]
Comment (tidely) [reply crates/client/src/socks.rs:30]: Yeah sounds good, I tried keeping this PR pretty concentrated, but changing from `Option<&Url>` to `&Url` does seem more natural. I'll send in a commit shortly

File: crates/client/src/socks.rs (hunk 3 above)
Comment (tidely) [reply crates/client/src/socks.rs:35]: Mostly a stylistic choice, but I prefer the explicitness of the return when parsing the proxy url, since it's quite critical that we don't use a fallback. However if context adheres better to Zed coding styles I'll gladly change it!

I'll add a `.map_err` to the `TcpStream::connect`, not sure why I didn't in the first place :)

Comment (SomeoneToIgnore) [reply crates/client/src/socks.rs:30]: I would prefer `.context`/`.with_context` over `.map_err` and `?` usage anyway as indeed, mostly the Zed "code style" and the type system being rather explicit itself already.

File: crates/client/src/socks.rs [hunk 5]
```diff
@@ -3,59 +3,99 @@ use anyhow::{Result, anyhow};
...
-            .map_err(|err| anyhow!("error connecting to socks {}", err))?;
-            Box::new(stream) as Box<dyn AsyncReadWrite>
+    let Some((socks_proxy, version)) = parse_socks_proxy(proxy) else {
+        // If parsing the proxy URL fails, we must avoid falling back to an insecure connection.
+        // SOCKS proxies are often used in contexts where security and privacy are critical,
+        // so any fallback could expose users to significant risks.
+        return Err(anyhow!("Parsing proxy url failed"));
+    };
+
+    // Connect to proxy and wrap protocol later
```
Comment (SomeoneToIgnore) [inline crates/client/src/socks.rs:37]: Oh, another obvious comment, can we have less of these?

File: crates/client/src/socks.rs (hunk 3 above)
Comment (tidely) [reply crates/client/src/socks.rs:30]: I left this block intact for now, would you like me to replace it with a `map_err` ?

```rust
let Some((socks_proxy, version)) = parse_socks_proxy(proxy) else {
    // If parsing the proxy URL fails, we must avoid falling back to an insecure connection.
    // SOCKS proxies are often used in contexts where security and privacy are critical,
    // so any fallback could expose users to significant risks.
    return Err(anyhow!("Parsing proxy url failed"));
};
```

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you.

File: crates/client/src/socks.rs (hunk 3 above)
Comment (SomeoneToIgnore) [reply crates/client/src/socks.rs:30]: I think it's fine, thank you for the rest of the fixes.

**Comment by ZegWe** [comment]
Sorry for the interruption, could you explain why this PR deprecates HTTP protocol support for the proxy?
If this deprecation is necessary, I believe it is important to include this `breaking change` in the PR/changelog description.
thx very much

**Comment by tidely** [comment]
> Sorry for the interruption, could you explain why this PR deprecates HTTP protocol support for the proxy?

The code path affected by this change only considered proxies with the scheme starting with "socks4" or "socks" to be valid. When this was not the case, it would always silently connect to the rpc host directly. Meaning HTTP is also considered an invalid proxy and would fallback to the direct connection, with this PR we instead throw an error instead. I'm certain that falling back to a direct connection was not intended, especially even when using proxy addresses that are as common as HTTP proxies.

> If this deprecation is necessary, I believe it is important to include this `breaking change` in the PR/changelog description. thx very much

You're absolutely right, I'll edit it into the description now, but I'm not it will show up in change notes anymore if this has already been shipped to stable.

**Comment by tidely** [comment]
> Sorry for the interruption, could you explain why this PR deprecates HTTP protocol support for the proxy?

The code path affected by this change only considered proxies with the scheme starting with "socks4" or "socks" to be valid. When this was not the case, it would always silently connect to the rpc host directly. Meaning HTTP is also considered an invalid proxy and would fallback to the direct connection, with this PR we instead throw an error instead. 

> If this deprecation is necessary, I believe it is important to include this `breaking change` in the PR/changelog description. thx very much

You're absolutely right, I'll edit it into the description now.
