### PR TITLE
multi_buffer: Merge adjacent matches into a single excerpt when separated by only one line

### LINKED ISSUE #31252: Project Search needlessly splits file into 2 sections
### Summary

When using Project Search to find a term that occurs throughout a file, Zed needlessly splits the file.

### Description

Notice where the split occurs: the top section ends at line 33 and the bottom section starts at line 34. This takes up more vertical space than displaying the entire file unsplit.

When you expand the top section downward (or the bottom section upward), the 2 sections merge and end up taking less vertical space.

<details><summary>Screenshots</summary>

Image
Image

</details>

Steps to reproduce:
1. Search for `__abbr_git` in the file

Expected Behavior: Zed only splits the file when it actually saves space
Actual Behavior: Zed splits the file such that a section ends at line X and the next section starts at line X + 1, taking up _more_ vertical space

<details><summary>File contents</summary>

```fish
if not status is-interactive
    exit
end

abbr gad -- git add
__abbr_git ad -- add

abbr gbr -- git branch
__abbr_git br -- branch

abbr gcm -- git commit
__abbr_git cm -- commit

abbr gco -- git checkout
__abbr_git co -- checkout

abbr gcp -- git cherry-pick
__abbr_git cp -- cherry-pick

abbr gdf -- git diff
__abbr_git df -- diff

abbr gdfc -- git diff --cached
__abbr_git dfc -- diff --cached
__abbr_git diffc -- diff --cached

abbr ggr -- git grep --break --heading
__abbr_git gr -- grep --break --heading

abbr glg -- git log
__abbr_git lg -- log

abbr glol -- git lol

abbr glola -- git lol --all
__abbr_git lola -- lol --all

abbr grb -- git rebase
__abbr_git rb -- rebase

abbr grba -- git rebase --abort
__abbr_git rba -- rebase --abort

abbr grbc -- git rebase --continue
__abbr_git rbc -- rebase --continue

abbr grbi -- git rebase --interactive
__abbr_git rbi -- rebase --interactive

abbr gsh -- git show
__abbr_git sh -- show

abbr gst -- git status
__abbr_git st -- status

abbr gsw -- git switch
__abbr_git sw -- switch

functions --erase __abbr_git
```
</details>

### Zed Version and System Specs

Zed: v0.187.6 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by Rogue-striker**
Closes #31252

Release Notes:

- Improved displaying of project search matches or diagnostics when the excerpts are adjacent.

### CODE REVIEW

File: crates/multi_buffer/src/multi_buffer.rs [hunk 1]
```diff
@@ -1575,6 +1575,7 @@ impl MultiBuffer {
         context_line_count: u32,
         cx: &mut Context<Self>,
     ) -> (Vec<Range<Anchor>>, bool) {
+        println!("in 1578");
```
Comment (osiewicz) [inline crates/multi_buffer/src/multi_buffer.rs]:
```suggestion
```

File: crates/multi_buffer/src/multi_buffer.rs [hunk 2]
```diff
@@ -1598,6 +1599,7 @@ impl MultiBuffer {
         excerpt_ranges: Vec<ExcerptRange<Point>>,
         cx: &mut Context<Self>,
     ) -> (Vec<Range<Anchor>>, bool) {
+        println!("in 1603");
```
Comment (osiewicz) [inline crates/multi_buffer/src/multi_buffer.rs]:
```suggestion
```

File: crates/multi_buffer/src/multi_buffer.rs [hunk 3]
```diff
@@ -1618,14 +1620,17 @@ impl MultiBuffer {
         cx: &mut Context<Self>,
     ) -> Task<Vec<Range<Anchor>>> {
         let buffer_snapshot = buffer.read(cx).snapshot();
+
         let path_key = PathKey::for_buffer(&buffer, cx);
+        println!("Setting excerpts for path: {path_key:?}");
```
Comment (osiewicz) [inline crates/multi_buffer/src/multi_buffer.rs]:
```suggestion
```

File: crates/multi_buffer/src/multi_buffer.rs [hunk 4]
```diff
@@ -1618,14 +1620,17 @@ impl MultiBuffer {
         cx: &mut Context<Self>,
     ) -> Task<Vec<Range<Anchor>>> {
         let buffer_snapshot = buffer.read(cx).snapshot();
+
```
Comment (osiewicz) [inline crates/multi_buffer/src/multi_buffer.rs]:
```suggestion
```

File: crates/multi_buffer/src/multi_buffer.rs [hunk 5]
```diff
@@ -1618,14 +1620,17 @@ impl MultiBuffer {
...
         let path_key = PathKey::for_buffer(&buffer, cx);
+        println!("Setting excerpts for path: {path_key:?}");
         cx.spawn(async move |multi_buffer, cx| {
             let snapshot = buffer_snapshot.clone();
             let (excerpt_ranges, new, counts) = cx
                 .background_spawn(async move {
                     let ranges = ranges.into_iter().map(|range| range.to_point(&snapshot));
                     let excerpt_ranges =
                         build_excerpt_ranges(ranges, context_line_count, &snapshot);
+                    print!("{:?}", excerpt_ranges);
```
Comment (osiewicz) [inline crates/multi_buffer/src/multi_buffer.rs]:
```suggestion
```
