### PR TITLE
Fix blurry cursor on Wayland at a scale other than 100%

### LINKED ISSUE #13258: Blurry mouse pointer on Wayland
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have the following setup:
* Ubuntu 24.04 GNOME Wayland
* Main laptop screen, 100% scaling
* External 4K monitor, set to 200% scaling

When I move Zed onto the 4K screen, the window is scaled nicely (correct size and crisp graphics), however whenever I move the mouse pointer over the editor it becomes blurry. It has the correct size, but it's as if the icon used for the rendering came from a lower resolution asset. If I move the pointer outside of the Zed window (for example over the desktop or some other application) then it becomes sharp. Sorry for no images, but unfortunately it doesn't show on screenshots.

### Environment

Zed: v0.141.0 (Zed Nightly d4891a62bb3bd45db713fa576a13f8a5d95ca382)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by senonide**
Closes #13258

Release Notes:

- Fixed blurry mouse cursor on wayland when the screen scale is other than 100%

Before:
Screenshot from 2024-09-06 14-38-30

After:
Screenshot from 2024-09-06 14-38-56

### CODE REVIEW

File: crates/gpui/src/platform/linux/wayland/client.rs [hunk 1]
```diff
@@ -476,7 +476,7 @@ impl WaylandClient {
             .as_ref()
             .map(|primary_selection_manager| primary_selection_manager.get_device(&seat, &qh, ()));
 
-        let mut cursor = Cursor::new(&conn, &globals, 24);
+        let mut cursor = Cursor::new(&conn, &globals, 24, 2);
```
Comment (nt8r) [inline crates/gpui/src/platform/linux/wayland/client.rs:479]: It seems like this number should be dynamically determined by the compositor rather than being hard-coded. A FIXME comment would make it clear that there's still work to do to handle other situations.

**Comment by mikayla-maki** [comment]
Thanks!

**Comment by CharlesChen0823** [comment]
> // FIXME: Determine the scaling factor dynamically by the compositor

this should fix, because when scaling factor is 100%, the display cursor is too big.

**Comment by notpeter** [comment]
@senonide Don't know if you saw this: 
- https://github.com/zed-industries/zed/issues/17771

Likely caused by this:
https://github.com/zed-industries/zed/blob/0d9af4dfe6a97bd0a06b4b0ff9c34031d2be116e/crates/gpui/src/platform/linux/wayland/client.rs#L479-L480

**Comment by apricotbucket28** [comment]
This code in here is wrong, the cursor's scale must be determined by the scale of the current wl_surface. Here's [some code](https://github.com/zed-industries/zed/blob/27c1106fadef97dc56d17d9359fd7514b71c8643/crates/gpui/src/platform/linux/wayland/window.rs#L546) where this is already being done. Basically:

1. Use `PreferredBufferScale` event if available (`surface.version() > wl_surface::EVT_PREFERRED_BUFFER_SCALE_SINCE`)
2. Else, use the scale in `wl_surface::Event::Enter`/`Leave`.

The `PreferredScale` event doesn't work for this since it sends a fractional scale.

Maybe there should be a cursor theme cache like SCTK does, and the current window's scale should passed when calling `cursor.set_icon()`: https://github.com/Smithay/client-toolkit/blob/c583de8dd5651f8168c6513cd282137c42aae049/src/seat/pointer/mod.rs#L612-L635
