### PR TITLE
Hide editor context menu when modal is opened

### LINKED ISSUE #28787: Context menu rendered on top of command menu
### Summary

asked to create a separate issue [here](https://github.com/zed-industries/zed/issues/27024#issuecomment-2802459493), warning popups (from hovering an error) will be rendered on top of the command menu, however as noted below warnings/error popups no longer seem to stay after opening the menu, however the right click context menu does and is arguably worse since its way easier to accidentally do

### Description
can get in the way because it doesnt leave when the command menu is open and it can block a significant portion of the menu (see video)

Steps to reproduce:
1. right click near the middle-top of your screen
2. open command menu

Expected Behavior:
context menu is renderer underneath the command menu or instantly closes when the command menu opens

Actual Behavior:
context menu stays open, and can block the command menu

<details><summary>click to expand</summary>

> After retesting this error popup issue on 0.182.0 it is no longer applicable as error/warning popups now close when command menu is opened

Image

However this is the new issue

https://github.com/user-attachments/assets/c7815bf3-4f07-4c9e-89a5-f8d3ac5dc332

</details>

### Zed Version and System Specs

Zed: v0.182.0 (Zed Dev 128779f6155ed9a48929b6eac23b10327a15fffb) 
OS: Windows 10.0.26100
Memory: 23.9 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 || Intel Corporation || Intel driver

### PR DESCRIPTION
**Pull request by redforks**
Closes #28787 

The context menu appears before the modal because it is a Deferred element, which is always displayed above normal elements.

Release Notes:

Previously, the editor context menu appeared before the Command Palette. This commit ensures the editor context menu is hidden when a modal, including the Command Palette, is opened.

### CODE REVIEW

File: crates/editor/src/items.rs [hunk 1]
```diff
@@ -928,9 +928,18 @@ impl Item for Editor {
         &mut self,
         workspace: &mut Workspace,
         _window: &mut Window,
-        _: &mut Context<Self>,
+        cx: &mut Context<Self>,
     ) {
         self.workspace = Some((workspace.weak_handle(), workspace.database_id()));
+        cx.subscribe(
+            &workspace.weak_handle().upgrade().unwrap(),
```
Comment (smitbarmase) [inline crates/editor/src/items.rs:935]: We should not use `unwrap` here, as it might panic if the workspace has been dropped. Instead, you can do something like this:

```rs  
        let weak_handle = workspace.weak_handle();
        self.workspace = Some((weak_handle, workspace.database_id()));
        if let Some(workspace) = weak_handle.upgrade() {
            cx.subscribe(&workspace, |editor, _, event: &workspace::Event, _cx| {
                if matches!(event, workspace::Event::ModalOpened) {
                    editor.mouse_context_menu.take();
                }
            })
            .detach();
        };
```

**Review by smitbarmase — CHANGES_REQUESTED** [review]
This looks great! Added just one comment which I think is important.

**Comment by redforks** [comment]
Updates:

1. Changed ModalLayer Event to a zero-sized struct.
1. Added a unit test.
1. Removed usage of unwrap() to prevent potential panics.

**Review by smitbarmase — APPROVED** [review]
