### PR TITLE
Take local project settings into account when launching terminals

### LINKED ISSUE #7599: Per project terminal.shell not working as documented
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is my first time trying zed, if I'm out of place let me know :)

I checked all the open issues and couldn't find anything directly related, #5320 seems a little bit related but is about a different symptom, so I decided continue with this issue.

---

I was trying to get tmux to open as zeds integrated terminal, (similar to this [article for vscode](https://dev.to/techspresso/tmux-and-vscode-persist-terminals-for-productivity-and-profit-2nd1#:~:text=terminal.integrated.profiles.osx)).
With this I followed the zed's [docs for configuring the terminal](https://zed.dev/docs/configuring-zed#terminal).

Configuring `tmux` worked at the user config level `~/.config/zed/settings.json`, but not on a project level.

But with this I discovered that Zed isn't respecting the `.zed/settings.json` file created by the `Zed > Settings > Open Local Settings` command.

I wished to be able to set this on a per project level, because I couldn't get a dynamic name for the workspace (as the article for vscode suggests), this would be nice to have on Zed too, but of course is out of scope for this issue.

`~/.config/zed/settings.json`:
```json
{
  "project_panel": {
    "dock": "right"
  },
  "theme": "Ayu Dark",
  "ui_font_size": 16,
  "buffer_font_size": 13
}
```
`~/project_dir/.zed/settings.json`:
```json
{
  "terminal": {
    "shell": {
      "with_arguments": {
        "program": "tmux",
        "args": [
          "new",
          "-As",
          "zed"
        ]
      }
    }
  }
}
```

I've restarted the editor presuming a reload would fix, but no luck.
I've attached a recording of the process, but I reiterate that I'm newbie when it comes to zed config.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/22945955/788982a4-0daf-43bc-8e75-5a1ad51b89cc

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

`Zed.log` file was too big for github to accept it inline (or inside a details tag), so i created a gist for it:
https://gist.githubusercontent.com/wesleycoder/f99800a8be42059c2a0a4501355c52fa/raw/6294e69dae943a0f6d8c180adb0a415275434df9/Zed.log

### PR DESCRIPTION
**Pull request by LoganDark**
Allows you to define per-project shells, for example.

Fixes #7599

Release Notes:

- Fixed terminals always using the global shell even when local settings specified a different shell.

### CODE REVIEW

File: crates/terminal_view/src/terminal_view.rs [hunk 1]
```diff
@@ -117,11 +117,26 @@ impl TerminalView {
         let working_directory =
             get_working_directory(workspace, cx, strategy.working_directory.clone());
 
+        let found_local_worktree = if let Some(working_directory) = working_directory.as_ref() {
```
Comment (SomeoneToIgnore) [inline crates/terminal_view/src/terminal_view.rs:120]: All four large changes in the PR seem to be the same functionality, slightly reworded every time?
Let's create a common method that does all the logic in one place, something like:

```rust
fn create_terminal(
    project: &Model<Project>,
    working_directory: &Path,
    cx: &mut WindowContext,
) -> Result<Model<Terminal>> {
    let local_worktree = project.read(cx).find_local_worktree(working_directory, cx);
    let settings_location = local_worktree
        .as_ref()
        .map(|(worktree, path)| SettingsLocation {
            worktree_id: worktree.read(cx).id().to_usize(),
            path,
        });

    let window = cx.window_handle();
    project.update(cx, |project, cx| {
        project.create_terminal(settings_location, working_directory, None, window, cx)
    })
}
```

it seems that the new function has to be adjusted a bit more to include the `spawn_task` though.

**Review by SomeoneToIgnore — COMMENTED** [review]
Nice idea, let's refactor it a bit and merge.

File: crates/terminal_view/src/terminal_view.rs (hunk 1 above)
Comment (LoganDark) [reply crates/terminal_view/src/terminal_view.rs:120]: I was considering pulling it out into a function but I wasn't sure where to put it or what to name it.

For `spawn_task`, I'm not entirely sure if what I settled on is necessarily the best way to do it. It didn't seem like it's possible to do differently, though.

Comment (SomeoneToIgnore) [reply crates/terminal_view/src/terminal_view.rs:120]: If placing and naming are the only concerns, let's place it in `terminal_view` as the root of the crate and keep the name from my example (or any other one you find more suitable).

**Comment by LoganDark** [comment]
I ran into a little annoyance where when I start Zed and open the terminal (after having to delete the `zed` project and re-add my actual test directory after my other instance of Zed keeps overwriting the projects list), it'll use the shell from my last open project until I close the tab and restart the terminal. I *think* this is because I had a terminal tab open on the other instance, and that tab got saved with an explicit "use powershell" rather than "no changes from default".

So in `SpawnInTerminal` I might want to move `command` and `args` into an enum so that a lack of *explicit* command can be remembered and then the restore process can pick up the correct shell when the terminal is re-opened?

**Comment by SomeoneToIgnore** [comment]
Thank you for unifying the logic, now it looks much nicer.
Let's fix the `cargo fmt` issues, it's the 2nd time CI fails on these so I wonder if you don't have the rust autoformat on save enabled.

The other bug seems nasty too, thank you for finding that.
If you think the fix is small, let's do that here, otherwise let's make a separate PR indeed — terminal functionality barely has any test (as the most of its logic is visual, transforming the alacritty terminal which is hard to test), so if something's broken and gets reverted, it better be small.

**Comment by LoganDark** [comment]
> I wonder if you don't have the rust autoformat on save enabled

I do not. Zed has it enabled as a global default, but I changed that global setting and this repo doesn't have an override. I can open a PR to add that as a local setting if you'd like.

**Comment by SomeoneToIgnore** [comment]
I do not think the override belongs here, as we expect certain things to be the default currently and CI backs us up on this, thank you.

**Comment by LoganDark** [comment]
> I do not think the override belongs here, as we expect certain things to be the default currently and CI backs us up on this, thank you.

In general I don't agree that everyone who works on Zed is going to be using the default settings, but in this case all I needed to do was run `cargo fmt` so a local override is not necessary.

> If you think the fix is small, let's do that here

Indeed, it's very related. I'll look into it.

**Review by SomeoneToIgnore — APPROVED** [review]

File: crates/project/src/terminals.rs [hunk 2]
```diff
@@ -31,8 +31,21 @@ impl Project {
             "creating terminals as a guest is not supported yet"
         );
 
+        let cwd = working_directory.as_deref().or_else(|| {
```
Comment (SomeoneToIgnore) [inline crates/project/src/terminals.rs:34]: Sorry, I have confused this part with the https://github.com/zed-industries/zed/pull/11526#issuecomment-2100016642 one, but seems that I've misunderstood that a bit.

This `cwd` is possible to set in the task template, and the user who set the task, might expect the task to run in the specific override, not in the working directory we've derived out of the current project data for regular terminal tab.
Does it make sense? What were the issues causing this change?

Comment (LoganDark) [reply crates/project/src/terminals.rs:34]: > This `cwd` is possible to set in the task template, and the user who set the task, might expect the task to run in the specific override, not in the working directory we've derived out of the current project data for regular terminal tab.

This `cwd` is only for locating the worktree that the task is to run in. If there's no working directory from the project, is it not OK to try to find one from the cwd set in the task? If there's none there either, then it'll just end up `None` and using the global terminal settings.

**Comment by LoganDark** [comment]
Probably the easiest / most flexible way to fix the restoring-old-terminal-in-new-project issue may actually just be to add a couple new variables for default shell name and args, that can be used instead of snapshotting the current shell (because then it will no longer follow configuration changes).

(Alternatively the variables could be for generic command name and command args, and then the shell could be in there by default but also have them be usable for things like wrapping arbitrary other commands... for example [teaching Zed how to execute commands in a remote context](https://github.com/zed-industries/zed/issues/5347) such as WSL... but I'm getting ahead of myself)

This would require variables in the args array to be able to expand to multiple elements. I'm fine to implement this, though there are certainly a few ways to make it behave:

- `[.., "$SHELL_ARGS", ..]` element obviously expands to `[.., "one", "two", ..]`
- `[.., "1${SHELL_ARGS}2", ..]` may expand to any of:

  1. `[.., "1one", "two2", ..]`
  2. `[.., "1one2", "1two2", ..]`
  3. `[.., "1", "one", "two", "2", ..]`

  I'm personally in favor of the first one, but the first two are roughly equal in terms of "potential correctness" (the third one looks slightly less correct to me).

File: crates/project/src/terminals.rs (hunk 2 above)
Comment (SomeoneToIgnore) [reply crates/project/src/terminals.rs:34]: I see, good point on the 

> for locating the worktree

I've overlooked it — in that case, should we even consider task's `cwd` for such resolutions then?
I do not have a good answer and maybe it's fine, but indeed seems more logical to prefer the overridden config first with this set-up?
I would entirely ignore task's cwd when looking for the settings, but not certain.

One thing I'm certain about with the current model: we want to find the `SettingsLocation` for both paths, just in case there's an odd situation when we might find no settings for the first path, bit find something for the 2nd one.
And if, on practice, this does not matter much with the current code, it starts to matter if we inverse the precedence.

Whatever approach we take, it might be good to emphasize it by extracting into a method with a good name, or at least leave the comment that task's cwd in this context is used a bit differently (as when spawning the tasks, this `cwd` always overrides other values)

**Comment by SomeoneToIgnore** [comment]
I like the idea with more variables, if I am getting it right.
It should allow people with https://github.com/zed-industries/zed/issues/10998 issues to add another line into their task config to force a non-default shell for a task, isn't it?

If so, sounds good — but let's create a separate PR for that and tag @\osiewicz there when ready, as it's quite a big change semantically.

For this PR, let's understand what do we want from the worktree settings resolution and merge it.

File: crates/project/src/terminals.rs (hunk 2 above)
Comment (LoganDark) [reply crates/project/src/terminals.rs:34]: > should we even consider task's `cwd` for such resolutions then?

I think if a task is executing with a CWD that resides within a particular worktree you probably want to use that worktree's shell. In general I'd prefer that assumption over failing to find the right shell even if the task runs with a CWD that certainly has an override.

> indeed seems more logical to prefer the overridden config first with this set-up

> One thing I'm certain about with the current model: we want to find the SettingsLocation for both paths, just in case there's an odd situation when we might find no settings for the first path, bit find something for the 2nd one.

Interesting. So if the terminal's working directory doesn't have an override but the task's set to spawn with a CWD that does have an override, you want to use the override anyway? I can certainly do that.

> it starts to matter if we inverse the precedence

+1

> Whatever approach we take, it might be good to emphasize it by extracting into a method with a good name, or at least leave the comment that task's cwd in this context is used a bit differently (as when spawning the tasks, this `cwd` always overrides other values)

Will make sure to throw this change in at some point.

**Comment by LoganDark** [comment]
> It should allow people with #10998 issues to add another line into their task config to force a non-default shell for a task, isn't it?

I don't think so, all it would do is allow a task to always execute the current shell even if it's changed since the task's creation. Right now a copy of the shell command is saved into the task, so if the shell command changes before the task is executed, the task will use the old shell. IMHO, if I open a tab on the terminal without specifying anything explicitly, then it shouldn't store a copy of the shell inside it, it should defer to whatever the shell currently is at the time of execution.

> I like the idea with more variables, if I am getting it right.

By more variables I am talking about:

https://github.com/zed-industries/zed/blob/63a5f46df4a694cf5ccfea43628a2ac8a4f053da/crates/task/src/lib.rs#L92-L110

**Comment by SomeoneToIgnore** [comment]
I think we're talking about the same thing in the end: we might be able to set custom overrides of those variables in task definitions already through env vars (but the override precedence is wrong now, maybe) and use a different shell.

Anyway, that looks interesting to try and discuss in a separate PR.

**Comment by LoganDark** [comment]
> Anyway, that looks interesting to try and discuss in a separate PR.

agreed, I was going to ask for a merge before I remembered to go add the comment you requested first.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks again for working on these issues.

File: crates/project/src/terminals.rs (hunk 2 above)
Comment (LoganDark) [reply crates/project/src/terminals.rs]: The cwd stuff is now inside of a block expression which should make it abundantly clear where they stop being used. Hopefully that will prevent any potential confusion :)

**Comment by LoganDark** [comment]
CI passed, and I fixed the release notes since this is a user-facing improvement. ready to merge

**Comment by LoganDark** [comment]
It's worth noting that other properties such as font, color, copy on select, etc. are still not supported in local settings. This is purely for interactive launches, which practically means interactive shell. I believe even background task launches still use the global settings.
