### PR TITLE
Include `font_features` in cache key for fonts

### LINKED ISSUE #4313: Font Ligature Setting does not work as intended / disable Font Ligatures
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening zed's settings and disabling font ligatures does not in fact disable font ligatures. This is the configuration entered in the settings.json:

"buffer_font_features": {
    "liga": false
  }

Yet as shown in this screenshot the ligature remain, even after re-launching Zed. (The Font used in this screenshot is JetBrains Mono, but this also happens with other fonts supporting Ligatures.)
Screenshot 2023-12-06 at 11 05 09

### Environment

Zed: v0.114.4 (stable)
OS: macOS 14.1.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by Yesterday17**
## Release Notes

- Fixed font ligatures not always respecting the setting ([#4313](https://github.com/zed-industries/zed/issues/4313)).

## Preview

20240306133121_rec_-convert

### CODE REVIEW

File: crates/gpui/src/platform/mac/text_system.rs [hunk 1]
```diff
@@ -51,13 +51,15 @@ const kCGImageAlphaOnly: u32 = 7;
 
 pub(crate) struct MacTextSystem(RwLock<MacTextSystemState>);
 
+type FontKey = (SharedString /* font_family */, FontFeatures);
```
Comment (maxdeviant) [inline crates/gpui/src/platform/mac/text_system.rs:54]: Seems like we should use a new type here instead of a type alias.
