### PR TITLE
windows: Set `CREATE_NO_WINDOW` for commands

### LINKED ISSUE #18371: [Windows] Multiple open and closed terminals at startup
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open zed, there are multiple open and closed terminals. If the project is large, it can last up to 1-2 minutes

### Environment

WindowsBuildLabEx : 22621.1.amd64fre.ni_release.220506-1250
WindowsProductName : Windows 10 Home Single Language
CsProcessors : {AMD Ryzen 9 7950X 16-Core Processor }
PowerPlatformRole : Desktop

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/4a3160eb-3df7-4028-8ef3-cb95d7a96d1e

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

}
2024-09-26T00:49:31.5700584+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/page.tsx",
  "state": 1,
  "validationTime": 16
}
2024-09-26T00:49:31.6022853+03:00 [INFO] downloading language server "json-language-server"
2024-09-26T00:49:31.6090346+03:00 [INFO] Creating buffer 0x203ea9dc0c0 of size 14560, name 'chunk-12', handle 18
2024-09-26T00:49:31.6402155+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/ModalInventory.tsx",
  "state": 1,
  "validationTime": 67
}
2024-09-26T00:49:31.6574767+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/types/user.ts",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:49:31.8115905+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/fiber/dist/declarations/src/three-types.d.ts",
  "state": 1,
  "validationTime": 148
}
2024-09-26T00:49:31.8293181+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useUser.ts",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:49:31.8632293+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/NftCreationModal.tsx",
  "state": 1,
  "validationTime": 33
}
2024-09-26T00:49:31.9506253+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/core/Object3D.d.ts",
  "state": 1,
  "validationTime": 81
}
2024-09-26T00:49:31.9852238+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/Hero.ts",
  "state": 1,
  "validationTime": 33
}
2024-09-26T00:49:32.0051201+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/MySpriteAnimator.tsx",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:49:32.0253684+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/AttributeCircle.tsx",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:49:32.0395693+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nft-consts.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:49:32.0550574+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useNFTMetadata.ts",
  "state": 1,
  "validationTime": 12
}
2024-09-26T00:49:32.0734244+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/contexts/SelectedPageContext.tsx",
  "state": 1,
  "validationTime": 12
}
2024-09-26T00:49:32.0870362+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/generate.ts",
  "state": 1,
  "validationTime": 10
}
2024-09-26T00:49:32.1045911+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/nft/transfer/route.ts",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:49:32.1254583+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/api.ts",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:49:32.1392658+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/utils.ts",
  "state": 1,
  "validationTime": 8
}
2024-09-26T00:49:32.1565305+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/providers.tsx",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:49:32.1737501+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/lights/Light.d.ts",
  "state": 1,
  "validationTime": 12
}
2024-09-26T00:49:32.1829272+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@tonconnect/ui-react/lib/hooks/useTonAddress.d.ts",
  "state": 1,
  "validationTime": 10
}
2024-09-26T00:49:32.1949976+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/drei/core/OrbitControls.d.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:49:32.2186711+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/next/types/global.d.ts",
  "state": 1,
  "validationTime": 22
}
2024-09-26T00:49:32.2342009+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/User.ts",
  "state": 1,
  "validationTime": 16
}
2024-09-26T00:49:32.2470655+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/LoadingScreen.tsx",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:49:32.264694+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/BatteryProgressBar.tsx",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:49:32.2893312+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nftMetadata.ts",
  "state": 1,
  "validationTime": 24
}
2024-09-26T00:49:32.3215317+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/Hero.tsx",
  "state": 1,
  "validationTime": 32
}
2024-09-26T00:49:32.3268981+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/customization/CharacterCustomization.tsx",
  "state": 1,
  "validationTime": 6
}
2024-09-26T00:49:32.3478803+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/HeroHeader.tsx",
  "state": 1,
  "validationTime": 21
}
2024-09-26T00:49:32.363166+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/contracts/NftItem.ts",
  "state": 1,
  "validationTime": 15
}
2024-09-26T00:49:32.3765896+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/route.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:49:32.3854299+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/image/route.ts",
  "state": 1,
  "validationTime": 9
}
2024-09-26T00:49:32.4096278+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/const.ts",
  "state": 1,
  "validationTime": 24
}
2024-09-26T00:49:32.4488004+03:00 [INFO] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/math/Color.d.ts",
  "state": 1,
  "validationTime": 35
}
2024-09-26T00:49:34.2265257+03:00 [INFO] Creating buffer 0x1f95be847f0 of size 33152, name 'chunk-13', handle 19
2024-09-26T00:49:34.2266006+03:00 [INFO] Creating buffer 0x1f95be84270 of size 7952, name 'chunk-14', handle 20
2024-09-26T00:49:34.2266577+03:00 [INFO] Creating buffer 0x1f95be842f0 of size 15456, name 'chunk-15', handle 21
2024-09-26T00:49:34.8049155+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\vscode-css-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-css-language-server", "--stdio"]
2024-09-26T00:49:34.8829483+03:00 [INFO] Destroying texture 0x1f95b62e830, handle 0
2024-09-26T00:49:34.88301+03:00 [INFO] Destroying texture 0x1f95b7e1ee0, handle 12
2024-09-26T00:49:34.8834695+03:00 [INFO] Destroying texture 0x1f95b7e5810, handle 14
2024-09-26T00:49:34.8838018+03:00 [INFO] Destroying buffer 0x203e97477e0, handle 16
2024-09-26T00:49:34.8838488+03:00 [INFO] Destroying buffer 0x1f9490924b0, handle 1
2024-09-26T00:49:34.8841778+03:00 [INFO] Destroying buffer 0x203e9749160, handle 15
2024-09-26T00:49:34.8844655+03:00 [INFO] Destroying buffer 0x1f95b8d7470, handle 6
2024-09-26T00:49:34.8845125+03:00 [INFO] Destroying buffer 0x1f95b8d77f0, handle 5
2024-09-26T00:49:34.8845531+03:00 [INFO] Destroying buffer 0x1f95b8d7670, handle 7
2024-09-26T00:49:34.8845941+03:00 [INFO] Destroying buffer 0x1f949094c30, handle 2
2024-09-26T00:49:34.8846346+03:00 [INFO] Destroying buffer 0x1f95be84770, handle 4
2024-09-26T00:49:34.8846753+03:00 [INFO] Destroying buffer 0x1f949094cb0, handle 3
2024-09-26T00:49:34.8847156+03:00 [INFO] Destroying buffer 0x1f95be84270, handle 20
2024-09-26T00:49:34.8847562+03:00 [INFO] Destroying buffer 0x1f949094e30, handle 9
2024-09-26T00:49:34.8847969+03:00 [INFO] Destroying buffer 0x203ea9dc0c0, handle 18
2024-09-26T00:49:34.8848375+03:00 [INFO] Destroying buffer 0x1f9490929b0, handle 11
2024-09-26T00:49:34.8848778+03:00 [INFO] Destroying buffer 0x1f949094f30, handle 8
2024-09-26T00:49:34.8849183+03:00 [INFO] Destroying buffer 0x1f95be842f0, handle 21
2024-09-26T00:49:34.8849617+03:00 [INFO] Destroying buffer 0x1f95be847f0, handle 19
2024-09-26T00:49:34.8850032+03:00 [INFO] Destroying buffer 0x203ea9dcbc0, handle 17
2024-09-26T00:49:34.8850437+03:00 [INFO] Destroying buffer 0x1f949091fb0, handle 10
2024-09-26T00:49:34.8850843+03:00 [INFO] Destroying buffer 0x1f95bdc62a0, handle 13
2024-09-26T00:49:34.8901106+03:00 [ERROR] window not found
2024-09-26T00:49:34.8901766+03:00 [ERROR] window not found
2024-09-26T00:49:34.8906281+03:00 [ERROR] Unexpected params: null
2024-09-26T00:49:34.8907046+03:00 [ERROR] oneshot canceled
2024-09-26T00:50:40.4280897+03:00 [INFO] ========== starting zed ==========
2024-09-26T00:50:40.5053403+03:00 [INFO] Use Segoe UI as UI font.
2024-09-26T00:50:40.5066942+03:00 [INFO] Opening main db
2024-09-26T00:50:40.511243+03:00 [INFO] Opening main db
2024-09-26T00:50:40.5168843+03:00 [INFO] Using git binary path: None
2024-09-26T00:50:40.5175476+03:00 [ERROR] SHELL environment variable is not assigned so we can't source login environment variables

Caused by:
    environment variable not found
2024-09-26T00:50:40.5456693+03:00 [INFO] initializing context server client
2024-09-26T00:50:40.5457811+03:00 [INFO] Registering built-in prompt template: content_prompt
2024-09-26T00:50:40.5461316+03:00 [INFO] Registering built-in prompt template: edit_workflow
2024-09-26T00:50:40.5463594+03:00 [INFO] Registering built-in prompt template: project_slash_command
2024-09-26T00:50:40.5464129+03:00 [INFO] Registering built-in prompt template: step_resolution
2024-09-26T00:50:40.5467636+03:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-26T00:50:40.5471565+03:00 [INFO] No prompt template overrides directory found at C:\Users\taima\AppData\Local\Zed\prompt_overrides. Using built-in prompts.
2024-09-26T00:50:40.5476088+03:00 [INFO] extensions updated. loading 12, reloading 0, unloading 0
2024-09-26T00:50:40.5583759+03:00 [INFO] Opening main db
2024-09-26T00:50:40.5601304+03:00 [INFO] set status on client 0: Authenticating
2024-09-26T00:50:40.5604564+03:00 [INFO] set status on client 118327: Connecting
2024-09-26T00:50:40.5612+03:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-09-26T00:50:40.5722516+03:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-09-26T00:50:40.5787865+03:00 [INFO] Enabling Vulkan Portability
2024-09-26T00:50:40.5788412+03:00 [INFO] Enabling color space support
2024-09-26T00:50:40.6261198+03:00 [INFO] Adapter: "AMD Radeon RX 5600 XT"
2024-09-26T00:50:40.6268753+03:00 [INFO] No ray tracing extensions are supported
2024-09-26T00:50:40.6332883+03:00 [WARN] Requested size 1x1 is outside of surface capabilities
2024-09-26T00:50:40.6333547+03:00 [ERROR] No composite alpha flag for transparency: OPAQUE
2024-09-26T00:50:40.6334287+03:00 [INFO] Using surface present mode FIFO_RELAXED
2024-09-26T00:50:40.7116176+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-26T00:50:40.7122865+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-26T00:50:40.7123389+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-09-26T00:50:40.7138374+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7141061+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7145606+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7147928+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7152047+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7153949+03:00 [INFO] Skip function Some("to_device_position_impl")
2024-09-26T00:50:40.7154458+03:00 [INFO] Skip function Some("to_device_position")
2024-09-26T00:50:40.7154944+03:00 [INFO] Skip function Some("to_device_position_transformed")
2024-09-26T00:50:40.715542+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.715656+03:00 [INFO] Skip function Some("blend_color")
2024-09-26T00:50:40.716083+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7163721+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7165742+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7170277+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7174849+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.717789+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7179702+03:00 [INFO] Skip function Some("to_device_position_impl")
2024-09-26T00:50:40.7180147+03:00 [INFO] Skip function Some("to_device_position")
2024-09-26T00:50:40.7180576+03:00 [INFO] Skip function Some("to_device_position_transformed")
2024-09-26T00:50:40.7181061+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.7181874+03:00 [INFO] Skip function Some("blend_color")
2024-09-26T00:50:40.721884+03:00 [ERROR] No composite alpha flag for transparency: OPAQUE
2024-09-26T00:50:40.7219452+03:00 [INFO] Using surface present mode FIFO_RELAXED
2024-09-26T00:50:40.7885889+03:00 [ERROR] No composite alpha flag for transparency: OPAQUE
2024-09-26T00:50:40.7886408+03:00 [INFO] Using surface present mode FIFO_RELAXED
2024-09-26T00:50:40.8712984+03:00 [INFO] Using surface present mode FIFO_RELAXED
2024-09-26T00:50:40.9341016+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-09-26T00:50:40.9352863+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9355073+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.935787+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9359908+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9362358+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9363988+03:00 [INFO] Skip function Some("to_device_position_impl")
2024-09-26T00:50:40.9364422+03:00 [INFO] Skip function Some("to_device_position")
2024-09-26T00:50:40.9364848+03:00 [INFO] Skip function Some("to_device_position_transformed")
2024-09-26T00:50:40.9365273+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9366086+03:00 [INFO] Skip function Some("blend_color")
2024-09-26T00:50:40.9369331+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9371322+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9372969+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9376629+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9379846+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9382116+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9383681+03:00 [INFO] Skip function Some("to_device_position_impl")
2024-09-26T00:50:40.9384127+03:00 [INFO] Skip function Some("to_device_position")
2024-09-26T00:50:40.9384561+03:00 [INFO] Skip function Some("to_device_position_transformed")
2024-09-26T00:50:40.9384992+03:00 [INFO] Skip function Some("to_tile_position")
2024-09-26T00:50:40.9385798+03:00 [INFO] Skip function Some("blend_color")
2024-09-26T00:50:40.9393109+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "AMD Radeon RX 5600 XT", driver_name: "AMD proprietary driver", driver_info: "24.5.1 (AMD proprietary shader compiler)" }
2024-09-26T00:50:40.9418436+03:00 [INFO] Using surface present mode FIFO_RELAXED
2024-09-26T00:50:41.0080612+03:00 [INFO] Creating texture 0x1f5bb00df30 of size 1024x1024x1 and format R8Unorm, name 'atlas', handle 0
2024-09-26T00:50:41.009623+03:00 [INFO] Creating buffer 0x1f5bacbf140 of size 65536, name 'chunk-0', handle 1
2024-09-26T00:50:41.0201468+03:00 [INFO] Creating buffer 0x1f56f54e9c0 of size 4096, name 'chunk-0', handle 2
2024-09-26T00:50:41.0284875+03:00 [INFO] Opening main db
2024-09-26T00:50:41.0373327+03:00 [INFO] Opening main db
2024-09-26T00:50:41.040662+03:00 [INFO] Creating buffer 0x1f5c4e30f40 of size 4096, name 'chunk-1', handle 3
2024-09-26T00:50:41.0412862+03:00 [INFO] Creating buffer 0x1f5c4e31140 of size 4096, name 'chunk-2', handle 4
2024-09-26T00:50:41.0413773+03:00 [INFO] Creating buffer 0x1f5c4e316c0 of size 4096, name 'chunk-3', handle 5
2024-09-26T00:50:41.0420987+03:00 [INFO] Opening main db
2024-09-26T00:50:41.044252+03:00 [INFO] Using Windows API for pseudoconsole
2024-09-26T00:50:41.1284696+03:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-09-26T00:50:41.1665092+03:00 [WARN] unhandled message: Metadata(SupermavenMetadataMessage { dust_strings: None })
2024-09-26T00:50:41.1957304+03:00 [INFO] attempting to start language server "vtsls", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 1
2024-09-26T00:50:41.1959008+03:00 [INFO] attempting to start language server "tailwindcss-language-server", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 2
2024-09-26T00:50:41.196032+03:00 [INFO] attempting to start language server "eslint", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 3
2024-09-26T00:50:41.1962029+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:41.1970102+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:41.1972115+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:41.2010272+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:41.2109922+03:00 [INFO] fetching latest version of language server "vtsls"
2024-09-26T00:50:41.2228396+03:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-09-26T00:50:41.2229271+03:00 [INFO] fetching latest version of language server "eslint"
2024-09-26T00:50:41.2229902+03:00 [INFO] downloading language server "eslint"
2024-09-26T00:50:41.2284587+03:00 [INFO] Creating buffer 0x1f5c4eb9320 of size 6048, name 'chunk-4', handle 6
2024-09-26T00:50:41.2287343+03:00 [INFO] Creating buffer 0x1f5c4eb8aa0 of size 6048, name 'chunk-5', handle 7
2024-09-26T00:50:41.2696849+03:00 [INFO] Creating buffer 0x1f5f0876a90 of size 65536, name 'chunk-1', handle 8
2024-09-26T00:50:41.2773237+03:00 [INFO] Creating buffer 0x1f5f0876110 of size 6832, name 'chunk-6', handle 9
2024-09-26T00:50:41.2773971+03:00 [INFO] Creating buffer 0x1f5f0876410 of size 32592, name 'chunk-7', handle 10
2024-09-26T00:50:41.280006+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:41.3078066+03:00 [INFO] Creating buffer 0x1f5ba5f9720 of size 6832, name 'chunk-8', handle 11
2024-09-26T00:50:41.3078775+03:00 [INFO] Creating buffer 0x1f5ba5f9520 of size 32592, name 'chunk-9', handle 12
2024-09-26T00:50:41.7037957+03:00 [INFO] add connection to peer
2024-09-26T00:50:41.7038421+03:00 [INFO] add_connection;
2024-09-26T00:50:41.703899+03:00 [INFO] waiting for server hello
2024-09-26T00:50:41.7227615+03:00 [INFO] got server hello
2024-09-26T00:50:41.7228194+03:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 544, id: 1124309 })
2024-09-26T00:50:41.7228949+03:00 [INFO] set status on client 118327: Connected { peer_id: PeerId { owner_id: 544, id: 1124309 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-09-26T00:50:41.8205933+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.0030284+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.0581832+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.0650226+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.1272914+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.198413+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.2094812+03:00 [WARN] unhandled message: ActiveRepo(SupermavenActiveRepoMessage { repo_simple_name: Some("sokoinu-kombat") })
2024-09-26T00:50:42.2095621+03:00 [WARN] unhandled message: TaskStatus(SupermavenTaskUpdateMessage { task: "Adapting to 'sokoinu-kombat'", status: Complete, percent_complete: None })
2024-09-26T00:50:42.2413968+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:42.5772033+03:00 [ERROR] failed to fetch cached embeddings via cloud model

Caused by:
    RPC request GetCachedEmbeddings failed: permission denied
2024-09-26T00:50:42.8627665+03:00 [ERROR] failed to fetch cached embeddings via cloud model

Caused by:
    RPC request GetCachedEmbeddings failed: permission denied
2024-09-26T00:50:42.8645656+03:00 [INFO] Creating texture 0x1f5703ecf70 of size 1024x1024x1 and format Bgra8UnormSrgb, name 'atlas', handle 13
2024-09-26T00:50:43.0508906+03:00 [ERROR] failed to fetch cached embeddings via cloud model

Caused by:
    RPC request GetCachedEmbeddings failed: permission denied
2024-09-26T00:50:44.0650803+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["--max-old-space-size=8192", "C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-2.4.4\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-09-26T00:50:44.0895549+03:00 [INFO] Creating buffer 0x1f5f05eea20 of size 10192, name 'chunk-10', handle 14
2024-09-26T00:50:44.0896351+03:00 [INFO] Creating buffer 0x1f5f05eeb20 of size 32592, name 'chunk-11', handle 15
2024-09-26T00:50:44.172535+03:00 [WARN] unhandled capability registration: Registration { id: "2dcc0574-f3a1-456e-9e11-fb6cd9e612d1", method: "workspace/didChangeConfiguration", register_options: Some(Object {}) }
2024-09-26T00:50:44.1726625+03:00 [WARN] unhandled capability registration: Registration { id: "0b284d85-ec27-459a-8a91-c53063d2f390", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-09-26T00:50:44.422402+03:00 [INFO] downloading language server "tailwindcss-language-server"
2024-09-26T00:50:45.1486414+03:00 [INFO] Summarizing updated entries took 6.2µs
2024-09-26T00:50:45.1546688+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.155507+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.156209+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1579152+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1593471+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1598376+03:00 [INFO] attempting to start language server "vscode-css-language-server", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 4
2024-09-26T00:50:45.1600202+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1607792+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1614579+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1628239+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1634899+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1643972+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1649262+03:00 [INFO] attempting to start language server "json-language-server", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 5
2024-09-26T00:50:45.1650948+03:00 [INFO] attempting to start language server "package-version-server", path: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", id: 6
2024-09-26T00:50:45.1652716+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1659479+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1678771+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1687074+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1702704+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1707515+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1713121+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1717699+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1722985+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1727974+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1748771+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.175761+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1776758+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.178267+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1817265+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1819444+03:00 [INFO] fetching latest version of language server "vscode-css-language-server"
2024-09-26T00:50:45.1848293+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.1856889+03:00 [INFO] fetching latest version of language server "json-language-server"
2024-09-26T00:50:45.2087483+03:00 [INFO] fetching latest version of language server "package-version-server"
2024-09-26T00:50:45.210673+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2116748+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2127261+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2142261+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2151626+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2159596+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2166437+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2174438+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2180588+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2184895+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2195828+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2202362+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2207835+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2214194+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2229083+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.223907+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.22442+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2262481+03:00 [INFO] Initializing default prettier with plugins {}
2024-09-26T00:50:45.2458266+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2459075+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2459723+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2460366+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2460992+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2461648+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2462255+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2462883+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2463502+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2464122+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2464813+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2465414+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.246603+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2466667+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2467282+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2467893+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2468554+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2469161+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2580764+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disable_reason", value: String(".gitignore") })
2024-09-26T00:50:45.2581559+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(true) })
2024-09-26T00:50:45.2582166+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-09-26T00:50:45.2850882+03:00 [INFO] Creating texture 0x1f5703ebc60 of size 1200x1200x1 and format Bgra8UnormSrgb, name 'atlas', handle 16
2024-09-26T00:50:45.2876576+03:00 [INFO] Creating buffer 0x1f544cdf9a0 of size 5760000, name 'chunk-2', handle 17
2024-09-26T00:50:45.3272037+03:00 [INFO] Creating buffer 0x1f544cdfb20 of size 33152, name 'chunk-12', handle 18
2024-09-26T00:50:45.3272822+03:00 [INFO] Creating buffer 0x1f544cdeba0 of size 14560, name 'chunk-13', handle 19
2024-09-26T00:50:45.3782948+03:00 [ERROR] Error { code: HRESULT(0x00000000), message: "Операция успешно завершена." }
2024-09-26T00:50:45.4121685+03:00 [INFO] Creating buffer 0x1f5479a7b00 of size 27456, name 'chunk-14', handle 20
2024-09-26T00:50:45.4122582+03:00 [INFO] Creating buffer 0x1f5479a6f80 of size 33152, name 'chunk-15', handle 21
2024-09-26T00:50:45.412328+03:00 [INFO] Creating buffer 0x1f5479a6980 of size 14560, name 'chunk-16', handle 22
2024-09-26T00:50:45.4123863+03:00 [INFO] Creating buffer 0x1f5479a7400 of size 14560, name 'chunk-17', handle 23
2024-09-26T00:50:45.7052052+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/Hero.tsx",
  "state": 1,
  "validationTime": 1339
}
2024-09-26T00:50:45.7247318+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/nft/checkOwner/[address]/route.ts",
  "state": 1,
  "validationTime": 36
}
2024-09-26T00:50:45.8411932+03:00 [INFO] downloading language server "package-version-server"
2024-09-26T00:50:45.8441895+03:00 [INFO] starting language server process. binary path: "C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.4.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: []
2024-09-26T00:50:46.2336316+03:00 [INFO] downloading language server "vtsls"
2024-09-26T00:50:46.2337195+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/Hero.tsx",
  "state": 1,
  "validationTime": 75
}
2024-09-26T00:50:46.7080421+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/MySpriteAnimator.tsx",
  "state": 1,
  "validationTime": 49
}
2024-09-26T00:50:46.7146244+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/MySpriteAnimator.tsx",
  "state": 1,
  "validationTime": 18
}
2024-09-26T00:50:46.7147352+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nft-consts.ts",
  "state": 1,
  "validationTime": 25
}
2024-09-26T00:50:46.7147972+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nft-consts.ts",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:50:46.7201404+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/BatteryProgressBar.tsx",
  "state": 1,
  "validationTime": 44
}
2024-09-26T00:50:46.7207076+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/BatteryProgressBar.tsx",
  "state": 1,
  "validationTime": 21
}
2024-09-26T00:50:46.720895+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/nft/checkOwner/[address]/route.ts",
  "state": 1,
  "validationTime": 20
}
2024-09-26T00:50:46.7213196+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/battle/BattlePage.tsx",
  "state": 1,
  "validationTime": 111
}
2024-09-26T00:50:46.7271829+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/battle/BattlePage.tsx",
  "state": 1,
  "validationTime": 59
}
2024-09-26T00:50:46.7277069+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/LoadingScreen.tsx",
  "state": 1,
  "validationTime": 38
}
2024-09-26T00:50:46.727788+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/LoadingScreen.tsx",
  "state": 1,
  "validationTime": 15
}
2024-09-26T00:50:46.7279609+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/AttributeCircle.tsx",
  "state": 1,
  "validationTime": 36
}
2024-09-26T00:50:46.7280686+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/AttributeCircle.tsx",
  "state": 1,
  "validationTime": 16
}
2024-09-26T00:50:46.7287801+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nftMetadata.ts",
  "state": 1,
  "validationTime": 66
}
2024-09-26T00:50:46.728969+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/nftMetadata.ts",
  "state": 1,
  "validationTime": 35
}
2024-09-26T00:50:46.7290856+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/NftCreationModal.tsx",
  "state": 1,
  "validationTime": 65
}
2024-09-26T00:50:46.729188+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/NftCreationModal.tsx",
  "state": 1,
  "validationTime": 31
}
2024-09-26T00:50:46.7294932+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/lights/Light.d.ts",
  "state": 1,
  "validationTime": 42
}
2024-09-26T00:50:46.7340338+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/lights/Light.d.ts",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:50:46.7342727+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/User.ts",
  "state": 1,
  "validationTime": 39
}
2024-09-26T00:50:46.7343921+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/User.ts",
  "state": 1,
  "validationTime": 19
}
2024-09-26T00:50:46.7345982+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/next/types/global.d.ts",
  "state": 1,
  "validationTime": 28
}
2024-09-26T00:50:46.7347648+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/next/types/global.d.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:50:46.7348919+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/ModalInventory.tsx",
  "state": 1,
  "validationTime": 82
}
2024-09-26T00:50:46.7350102+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/ModalInventory.tsx",
  "state": 1,
  "validationTime": 39
}
2024-09-26T00:50:46.7687278+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/AnimatedModel.tsx",
  "state": 1,
  "validationTime": 49
}
2024-09-26T00:50:46.7689499+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/AnimatedModel.tsx",
  "state": 1,
  "validationTime": 22
}
2024-09-26T00:50:46.8105072+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/drei/core/OrbitControls.d.ts",
  "state": 1,
  "validationTime": 36
}
2024-09-26T00:50:46.8107629+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/drei/core/OrbitControls.d.ts",
  "state": 1,
  "validationTime": 19
}
2024-09-26T00:50:46.8398778+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/contexts/UserContext.tsx",
  "state": 1,
  "validationTime": 26
}
2024-09-26T00:50:46.8399813+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/contexts/UserContext.tsx",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:50:46.9012791+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/types/index.ts",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:50:46.9013809+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/types/index.ts",
  "state": 1,
  "validationTime": 6
}
2024-09-26T00:50:46.9014631+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@tonconnect/ui-react/lib/hooks/useTonAddress.d.ts",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:50:46.9017185+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@tonconnect/ui-react/lib/hooks/useTonAddress.d.ts",
  "state": 1,
  "validationTime": 7
}
2024-09-26T00:50:46.9719481+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/bars/DynamicNavbar.tsx",
  "state": 1,
  "validationTime": 49
}
2024-09-26T00:50:46.9786815+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/bars/DynamicNavbar.tsx",
  "state": 1,
  "validationTime": 24
}
2024-09-26T00:50:46.9922034+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/types/user.ts",
  "state": 1,
  "validationTime": 20
}
2024-09-26T00:50:47.0016763+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/types/user.ts",
  "state": 1,
  "validationTime": 9
}
2024-09-26T00:50:47.3466654+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/math/Color.d.ts",
  "state": 1,
  "validationTime": 98
}
2024-09-26T00:50:47.3480918+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/math/Color.d.ts",
  "state": 1,
  "validationTime": 33
}
2024-09-26T00:50:47.3483825+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/customization/CharacterCustomization.tsx",
  "state": 1,
  "validationTime": 9
}
2024-09-26T00:50:47.3486696+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/customization/CharacterCustomization.tsx",
  "state": 1,
  "validationTime": 4
}
2024-09-26T00:50:47.3489973+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/providers.tsx",
  "state": 1,
  "validationTime": 26
}
2024-09-26T00:50:47.3491387+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/providers.tsx",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:50:47.3492881+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/const.ts",
  "state": 1,
  "validationTime": 44
}
2024-09-26T00:50:47.3494171+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/const.ts",
  "state": 1,
  "validationTime": 23
}
2024-09-26T00:50:47.3507261+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/fiber/dist/declarations/src/three-types.d.ts",
  "state": 1,
  "validationTime": 166
}
2024-09-26T00:50:47.3543354+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@react-three/fiber/dist/declarations/src/three-types.d.ts",
  "state": 1,
  "validationTime": 85
}
2024-09-26T00:50:47.3545594+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/image/route.ts",
  "state": 1,
  "validationTime": 20
}
2024-09-26T00:50:47.3546792+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/image/route.ts",
  "state": 1,
  "validationTime": 8
}
2024-09-26T00:50:47.401164+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useUser.ts",
  "state": 1,
  "validationTime": 23
}
2024-09-26T00:50:47.4130041+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useUser.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:50:47.4288355+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/route.ts",
  "state": 1,
  "validationTime": 31
}
2024-09-26T00:50:47.4294849+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/[id]/route.ts",
  "state": 1,
  "validationTime": 15
}
2024-09-26T00:50:47.5347109+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/api.ts",
  "state": 1,
  "validationTime": 31
}
2024-09-26T00:50:47.5365923+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/api.ts",
  "state": 1,
  "validationTime": 16
}
2024-09-26T00:50:47.5368824+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/redis.ts",
  "state": 1,
  "validationTime": 32
}
2024-09-26T00:50:47.537114+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/redis.ts",
  "state": 1,
  "validationTime": 16
}
2024-09-26T00:50:47.5373917+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/nft/transfer/route.ts",
  "state": 1,
  "validationTime": 26
}
2024-09-26T00:50:47.537614+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/nft/transfer/route.ts",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:50:47.8878292+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/contracts/NftItem.ts",
  "state": 1,
  "validationTime": 34
}
2024-09-26T00:50:47.8941625+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/nft/contracts/NftItem.ts",
  "state": 1,
  "validationTime": 14
}
2024-09-26T00:50:47.8944406+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/route.ts",
  "state": 1,
  "validationTime": 18
}
2024-09-26T00:50:47.8945854+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/api/user/route.ts",
  "state": 1,
  "validationTime": 8
}
2024-09-26T00:50:47.8947479+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/generate.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:50:47.8948814+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/HeroHeader.tsx",
  "state": 1,
  "validationTime": 36
}
2024-09-26T00:50:47.8950074+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/HeroHeader.tsx",
  "state": 1,
  "validationTime": 18
}
2024-09-26T00:50:47.8951677+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/generate.ts",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:50:47.8953252+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/page.tsx",
  "state": 1,
  "validationTime": 23
}
2024-09-26T00:50:47.8954724+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/app/page.tsx",
  "state": 1,
  "validationTime": 13
}
2024-09-26T00:50:47.8955941+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/contexts/SelectedPageContext.tsx",
  "state": 1,
  "validationTime": 22
}
2024-09-26T00:50:47.8957663+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/contexts/SelectedPageContext.tsx",
  "state": 1,
  "validationTime": 12
}
2024-09-26T00:50:47.9009577+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/Hero.ts",
  "state": 1,
  "validationTime": 50
}
2024-09-26T00:50:47.9012376+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/models/Hero.ts",
  "state": 1,
  "validationTime": 24
}
2024-09-26T00:50:47.9294085+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useNFTMetadata.ts",
  "state": 1,
  "validationTime": 26
}
2024-09-26T00:50:47.9296293+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/hooks/useNFTMetadata.ts",
  "state": 1,
  "validationTime": 11
}
2024-09-26T00:50:47.929799+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/CreateNftButton.tsx",
  "state": 1,
  "validationTime": 35
}
2024-09-26T00:50:47.9299313+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/components/pages/hero/CreateNftButton.tsx",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:50:47.9299981+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/utils.ts",
  "state": 1,
  "validationTime": 17
}
2024-09-26T00:50:47.9300566+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/src/services/utils.ts",
  "state": 1,
  "validationTime": 7
}
2024-09-26T00:50:47.9357761+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/core/Object3D.d.ts",
  "state": 1,
  "validationTime": 83
}
2024-09-26T00:50:47.9382722+03:00 [INFO] Language server with id 3 sent unhandled notification eslint/status:
{
  "uri": "file:///G:/CodeProjects/WebstormProjects/sokoinu-kombat/node_modules/@types/three/src/core/Object3D.d.ts",
  "state": 1,
  "validationTime": 42
}
2024-09-26T00:50:48.2637913+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server", "--stdio"]
2024-09-26T00:50:48.2681538+03:00 [INFO] downloading language server "vscode-css-language-server"
2024-09-26T00:50:49.8052836+03:00 [INFO] Language server with id 2 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2024-09-26T00:50:49.8053912+03:00 [WARN] unhandled capability registration: Registration { id: "3b4e599d-cfed-4906-997b-7620a8601338", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-09-26T00:50:51.1930144+03:00 [INFO] downloading language server "json-language-server"
2024-09-26T00:50:51.9399966+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\vtsls\\node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2024-09-26T00:50:52.8797866+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\vscode-css-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-css-language-server", "--stdio"]
2024-09-26T00:50:55.1014425+03:00 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "G:\\CodeProjects\\WebstormProjects\\sokoinu-kombat", args: ["C:\\Users\\taima\\AppData\\Local\\Zed\\languages\\json-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-09-26T00:54:53.2104305+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-26T00:54:53.2128643+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-26T00:54:53.215858+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-09-26T00:54:53.221006+03:00 [INFO] Creating a descriptor pool for at most 256 sets

</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
- Closes: #18371

Release Notes:

- N/A

### CODE REVIEW

**Comment by CharlesChen0823** [comment]
I think the best method should be introduce an `crate` name `command`, in here, create `new_std_command` and `new_smol_command` with set `CREATE_NO_WINDOW`. we can use the two function everywhere, don't need hacky everywhere.

**Comment by JunkuiZhang** [comment]
> I think the best method should be introduce an file name `command` in `util` crate, in here, create `new_std_command` and `new_smol_command` with set `CREATE_NO_WINDOW`. we can use the two function everywhere, don't need hacky everywhere.

That's my next move. The idea of this *draft* PR is that making a quick demo to see if it could fix the issue. If so, then I'm gonna refactor the codes.

**Comment by SomeoneToIgnore** [comment]
Is it really the only way we can enable window-less command invocations in Windows?
Feels very fragine, as every other plugin that forgets about Windows and this behavior, will bring pop-ups back.

**Comment by CharlesChen0823** [comment]
> Is it really the only way we can enable window-less command invocations in Windows? Feels very fragile, as every other plugin that forgets about Windows and this behavior, will bring the pop-ups back.

I think this is only way

**Comment by SomeoneToIgnore** [comment]
This is very very odd, but then I think https://github.com/zed-industries/zed/pull/19018 is not that bad if it's a documented single entry for all such plugin invocations.

I'll leave the review (and the choice) to the person who knows things better than me though.

**Comment by JunkuiZhang** [comment]
> Is it really the only way we can enable window-less command invocations in Windows? Feels very fragile, as every other plugin that forgets about Windows and this behavior, will bring the pop-ups back.


I'm afraid this is indeed the case. `std::process::Command::new(...).spawn()` internally calls `CreateProcess`, as seen [here](https://github.com/rust-lang/rust/blob/ecf2d1fa4bd8166c696883b10f483122b1fe98a3/library/std/src/sys/pal/windows/process.rs#L378-L388):

```rust
cvt(c::CreateProcessW(
    program.as_ptr(),
    cmd_str.as_mut_ptr(),
    ptr::null_mut(),
    ptr::null_mut(),
    c::TRUE,
    flags,
    envp,
    dirp,
    si_ptr,
    &mut pi,
))
```

According to Microsoft's [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw), if you don't want the window to appear, you can set `dwCreationFlags` to include `CREATE_NO_WINDOW`, or configure other settings. But in any case, we always need to set some variables.

Moreover, in Windows programming, whether a window is displayed when calling `CreateProcess` depends on the parent process. If the parent process already has a console window, then the call to `CreateProcess` will not create a new window but will reuse the existing one. This explains the behavior when compiling Zed in `debug` mode—Zed is treated as a console app and thus has a console window. As a result, `std::process::Command` does not create a new window. In `release` mode, however, Zed doesn't have a console window, so `std::process::Command` always creates a new one.

**Comment by JunkuiZhang** [comment]
I referenced VSCode's code [here](https://github.com/microsoft/vscode/blob/main/cli/src/util/command.rs) to introduce `util::command::new_std_command` and `util::command::new_smol_command`. If we decide not to proceed with this approach, we can easily revert to the previous commit.

Additionally, since VSCode's code is under the MIT license and the crate `util` uses the APACHE license, would there be any issue?

File: crates/util/src/command.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+use std::ffi::OsStr;
+
+#[cfg(target_os = "windows")]
+const CREATE_NO_WINDOW: u32 = 134217728u32;
```
Comment (MrSubidubi) [inline crates/util/src/command.rs:4]:
```suggestion
const CREATE_NO_WINDOW: u32 = 0x08000000;
```

Small nitpick, but I believe this to be the more readable and understandable representation for the flag.

Comment (JunkuiZhang) [reply crates/util/src/command.rs:4]: Thx!

Comment (MrSubidubi) [reply crates/util/src/command.rs]: No worries, thank you for all your awesome contributions for the community!

**Comment by ddanielsantos** [comment]
> Can we have this merged please, so annoying to have those terminal popups exploding like fireworks on my face every time I use Zed

i dont think thats how open source works

**Comment by kelvinchin12070811** [comment]
Just let them do their work, seems like they are too busy at ssh remote dev and no time for other issues.  JunkuiZhang seems to be the only Windows dev that they have which is currently active and he's human too, and there's still a lot of issues for him to fix.

**Comment by eternalphane** [comment]
> Can we have this merged please, so annoying to have those terminal popups exploding like fireworks on my face every time I use Zed

@teknalb You can cherry-pick this PR and build it by yourself if you're really concerned

**Comment by shenjackyuanjie** [comment]
It looks like we need `tokio::process::Command` wrapper @JunkuiZhang

**Comment by shenjackyuanjie** [comment]
for anyone who want to use this branch's work, check out https://github.com/shenjackyuanjie/zed-win-build/releases
and I am maintaining a temporary branch https://github.com/shenjackyuanjie/zed/tree/temp/cmdfix

**Comment by xgfone** [comment]
May this RP be merged into the main branch?

**Review by codecooker1 — COMMENTED** [review]
Seems cool. There doesn't seems to be any malicious code hidden (I think) :P

File: crates/util/src/command.rs [hunk 2]
```diff
@@ -0,0 +1,32 @@
+use std::ffi::OsStr;
+
+#[cfg(target_os = "windows")]
+const CREATE_NO_WINDOW: u32 = 0x0800_0000_u32;
+
+#[cfg(target_os = "windows")]
+pub fn new_std_command(program: impl AsRef<OsStr>) -> std::process::Command {
+    use std::os::windows::process::CommandExt;
+
+    let mut command = std::process::Command::new(program);
```
Comment (mikayla-maki) [inline crates/util/src/command.rs:10]: Can we reformat these to use `#[allow(unused_mut)]`, and then move the compile flag into the function body?

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by mikayla-maki** [comment]
Thank you!
