### PR TITLE
project_panel: Fixed open in split not working in project panel

### LINKED ISSUE #14465: Open file in split from Project Panel on Linux
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"Open to the side" as described in #10549 does not work on linux, I have tried Ctrl, Alt, and Super keys, nothing works and I am unable to open a file from Project Panel into a new split.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.6 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by CharlesChen0823**
close: #14465 

Release Notes:

- N/A

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -2171,24 +2171,24 @@ impl ProjectPanel {
                                     });
                                 }
                             } else if event.down.modifiers.secondary() {
-                                if !this.marked_entries.insert(selection) {
-                                    this.marked_entries.remove(&selection);
+                                if event.down.click_count > 1 {
+                                    this.split_entry(entry_id, cx);
+                                } else {
```
Comment (SomeoneToIgnore) [inline crates/project_panel/src/project_panel.rs:2176]: Let's merge it into `else if`

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you.
Let's fix one small style nit and merge this.

I would add a new context menu item for this feature, but that can be a follow-up.

**Review by SomeoneToIgnore — APPROVED** [review]
