### PR TITLE
Fix micromamba not initializing shell

### LINKED ISSUE #44645: Libmamba not working
### Reproduction steps

When micromamba is used it needs to be initialized in that terminal which is different to how conda/mamba operates/

### Zed version and system specs

Zed preview 0.216.0 e55a8c9cb1756058e653b3c2f65863dd10c46b58  – /usr/lib/zed/zed-editor
OS: arch

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### PR DESCRIPTION
**Pull request by cvanelteren**
Closes #44645

This is a continuation of #40577

Release Notes:
- initializes micromamba based on the shell

### CODE REVIEW

**Comment by cvanelteren** [comment]
I branched from my previous commit, but I am seeing that they are not merged on main yet which is why the history is there. You can ignore it and just focus on the latest commit.

**Comment by Veykril** [comment]
You'll need to rebase this onto main, we use a squash workflow so the history changes after a merge

**Comment by cvanelteren** [comment]
I made a big mess but restored it now I think. Changes are minor.

**Comment by cvanelteren** [comment]
I will rebase -- one moment please.

**Comment by cvanelteren** [comment]
Sorry for the mess the changes are clean now -- need to get some coffee -_-

File: crates/languages/src/python.rs [hunk 1]
```diff
@@ -1297,24 +1309,29 @@ impl ToolchainLister for PythonToolchainProvider {
...
+                    let shell = micromamba_shell_name(shell);
+                    activation_script
+                        .push(format!(r#"eval "$({manager} shell hook --shell {shell})""#));
+                }
+
+                let env_name = toolchain.environment.name.as_deref().unwrap_or("base");
+                activation_script.push(format!("{manager} activate {env_name}"));
+
                 if let Some(name) = &toolchain.environment.name {
                     activation_script.push(format!("{manager} activate {name}"));
```
Comment (Veykril) [inline crates/languages/src/python.rs]: That change looks unnecessary, we already push that activate invocation here after all

Comment (cvanelteren) [reply crates/languages/src/python.rs]: You are right -- think this is a remnant of the rebase shenaningans. Will fix

Comment (cvanelteren) [reply crates/languages/src/python.rs]: Should be good @Veykril

**Review by Veykril — APPROVED** [review]
Thanks!

**Comment by rgbkrk** [comment]
@Klaim - might want to check this out for micromamba and conda support in Zed
