### PR TITLE
remote: Check if remote can --exec, fall back to spawning shell otherwise

### LINKED ISSUE #39710: Windows Beta: unable to connect to WSL2 distro (NixOS)
### Summary

I've just installed Zed for Windows and am trying to connect to my WSL disto (NixOS), where I do all my dev work. Unfortunately, I'm greeted with a critical error from the very beginning.

### Description

Steps to trigger the problem:
1. File -> Open Remote -> Add WSL Distro
2. Choose NixOS

**Expected Behavior**:

A successful connection to WSL.

**Actual Behavior**:

A critical error shows up:
```
Failed to connect

Command 'uname' failed: <3>WSL (17615 - Relay) ERROR: CreateProcessCommon:798: execvpe(uname) failed: No such file or directory. Please try again.
```

The log is 
```
2025-10-07T21:02:12+02:00 WARN  [fs] Failed to watch /etc/ssh/ssh_config and its parent directory /etc/ssh:
Input watch path is neither a file nor a directory.
Input watch path is neither a file nor a directory.
2025-10-07T21:02:15+02:00 INFO  [remote::transport::wsl] Connecting to WSL distro NixOS with user None
2025-10-07T21:02:15+02:00 ERROR [workspace::notifications] Command 'uname' failed: <3>WSL (19472 - Relay) ERROR: CreateProcessCommon:798: execvpe(uname) failed: No such file or directory
2025-10-07T21:02:27+02:00 ERROR [editor] oneshot canceled
```

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly 41ac6a87641b7d2a7c2b1261ebe5fe06e82a2c40) 
OS: Windows 10.0.22631
Memory: 63.4 GiB
Architecture: x86_64
GPU: Intel(R) Arc(TM) Pro Graphics || Intel Corporation || 32.0.101.6637

### PR DESCRIPTION
**Pull request by kubkon**
Bonus: fix passing env vars to the proxy server in WSL setting.

Closes #39710
Supersedes #39893

Release Notes:

- N/A

### CODE REVIEW

File: crates/remote/src/transport/wsl.rs [hunk 1]
```diff
@@ -71,18 +73,48 @@ impl WslRemoteConnection {
...
         this.remote_binary_path = Some(
             this.ensure_server_binary(&delegate, release_channel, version, commit, cx)
                 .await?,
         );
+        log::debug!("Detected WSL environment: {this:#?}");
 
         Ok(this)
     }
 
+    async fn detect_can_exec(&self) -> Result<bool> {
```
Comment (Veykril) [inline crates/remote/src/transport/wsl.rs:91]: I do wonder if we still want to land https://github.com/zed-industries/zed/pull/40084 though, `nu` itself shouldn't really prevent us from using `exec` after all, aside from it not allowing us to exec uname.

**Review by Veykril — APPROVED** [review]
Generally looks good to me

File: crates/remote/src/transport/wsl.rs (hunk 1 above)
Comment (kubkon) [reply crates/remote/src/transport/wsl.rs:91]: Good point, lemme check if this fix works for nu as well.

Comment (kubkon) [reply crates/remote/src/transport/wsl.rs:91]: Just double checked by switching default shells in NixoS in WSL to nushell that your PR is still required.
