### PR TITLE
terminal: Fix detection of ignored python venv

### LINKED ISSUE #19227: Autodetecting virtual environment randomly works
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My current setting for terminal is

```
"terminal": {
    "font_family": "MesloLGS NF",
    "detect_venv": {
      "on": {
        // Default directories to search for virtual environments, relative
        // to the current working directory. We recommend overriding this
        // in your project's settings, rather than globally.
        "directories": [".venv", ".env", "env", "venv"],
        // Can also be `csh`, `fish`, and `nushell`
        "activate_script": "default"
      }
    }
  },
```

When I open a project and open a terminal it generaly does not load in the virtual environment. Sometimes, closing and reopening the terminal is enough to load the virtual environment.

Sometimes not. If I activate manually, and close/open the terminal, is sometimes load at root (`/`) instead of current directory

```
❯ pwd
/
```

Maybe it is somehow related.

I am not sure what can I provide to help with this issue. Virtual environment detection used to work as expected previously. Did something break in last verions ?

### Environment

Zed: v0.156.2 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by SirSilver**
Closes #19227

Since items listed in `.gitignore` file are not included in a worktree, python virtual environment cannot be detected until venv directory is unfolded from project panel and forcefully added into worktree. I didn't come up with anything better than scanning fs directly. I'm not sure how it will affect remote development. if at all.

Release Notes:

- Fixed detection of `detect_venv.directories` ignored by a worktree

### CODE REVIEW

**Comment by SirSilver** [comment]
@cli-bot check

**Comment by SirSilver** [comment]
@cla-bot check

File: crates/project/src/terminals.rs [hunk 1]
```diff
@@ -290,6 +302,32 @@ impl Project {
...
+        cx: &AppContext,
+    ) -> Option<PathBuf> {
+        let (worktree, _) = self.find_worktree(abs_path, cx)?;
+        let fs = worktree.read(cx).as_local()?.fs();
+        let bin_dir_name = match std::env::consts::OS {
+            "windows" => "Scripts",
+            _ => "bin",
+        };
+        venv_settings
+            .directories
```
Comment (osiewicz) [inline crates/project/src/terminals.rs:318]: We could probably spawn off multiple checks in parallel here via `cx.scope`.
