### PR TITLE
Unmount the auto-update disk image regardless of the auto-update status

### LINKED ISSUE #10782: Zed putting volume drive shortcuts on desktop MacOS
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After a few hours of working in Zed I will find that my desktop is suddenly riddled with several weird ejectable drive shortcuts titled `Zed` and untitled folders. 
example

I suspect I am accidentally causing this through some keyboard shortcut that I am not aware of. I have the vscode keymap turned on.

To get rid of them, I have to option click on each of the icons and press `Eject`. But more show up again every day.

What is causing this and how can I disable it?

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by vitallium**
Closes #10782

In some cases, during the auto-update process,
the update can fail and leave a dangling disk image in macOS. If the auto-update fails again, a new dangling mounted volume will be left behind. To avoid polluting the system with these dangling mounted disk images,
implement [the `Drop` trait](https://doc.rust-lang.org/std/ops/trait.Drop.html) for the `MacOSUnmounter` struct. This will ensure that the disk image
is unmounted when the `install_release_macos` function exits regardless of its result.

## How to test this locally

Unfortunately, I was a bit too lazy to find a smarter way to test this, so I simply commented out a bunch of lines to emulate the auto-update process. To replicate the linked issue (#10782), you can apply the attached patch. Build the Zed binary and run it. The auto-update should fail, leaving the dangling mounted disk image in the system:

```shell
>diskutil list
/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +220.6 MB   disk5
                                 Physical Store disk4s1
   1:                APFS Volume Zed                     190.6 MB   disk5s1
```

Run the Zed binary again to create another mounted disk image:

```shell
>diskutil list
/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +220.6 MB   disk5
                                 Physical Store disk4s1
   1:                APFS Volume Zed                     190.6 MB   disk5s1

/dev/disk7 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +220.6 MB   disk7
                                 Physical Store disk6s1
   1:                APFS Volume Zed                     190.6 MB   disk7s1
```

[simulate_zed_autoupdate.patch](https://github.com/user-attachments/files/16787955/simulate_zed_autoupdate.patch)

Please let me know if the fix is good; otherwise, I am happy to implement it differently. Thanks!

Release Notes:

- Fixed #10782

### CODE REVIEW

File: crates/auto_update/src/auto_update.rs [hunk 1]
```diff
@@ -88,6 +88,34 @@ struct JsonRelease {
     url: String,
 }
 
+struct MacOSUnmounter {
```
Comment (maxdeviant) [inline crates/auto_update/src/auto_update.rs:91]: Can we follow [Rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html) here?

```suggestion
struct MacOsUnmounter {
```

**Comment by mikayla-maki** [comment]
Thanks!
