### PR TITLE
Check if virtual environment is in worktree root

### LINKED ISSUE #37509: Local python venv not prioritized
### Summary

When working on a python project, if you have a virtual environment located in the project root, it does not get selected as the default toolchain in Zed when it should.

### Description

I have some virtual environments for other projects created via `pipenv` that are located in the default `pipenv` location, not in the project. But for more recent projects I put the virtual environment in the project in a `.venv` directory and just create it via `poetry` or `python -m venv .venv`. Even though none of the `pipenv` environments are for the current project, they get prioritized over the virtual environment that is in the project.

Steps to reproduce:
1. Make a `pipenv` virtual environment for `OtherProject` in the default `pipenv` location for storing virtual environments.
2. Make a virtual environment for `CurrentProject` in the root of the project via `python -m venv .venv`.
3. Zed by default will select `OtherProject`'s virtual environment for `CurrentProject`.

**Expected Behavior**:
The virtual environment in the project root should be the first choice when there are no other virtual environments found for it.

**Actual Behavior**:
Because `pipenv` environments have priority over `venv` environments, they are prioritized and get selected as the default when opening a project.

### Zed Version and System Specs

Zed: v0.202.5 (Zed) 
OS: macOS 15.6.1
Memory: 16 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by dunkmann00**
The problem from issue #37509 comes from local virtual environments created with certain approaches (including the 'simple' way of `python -m venv`) not having a `.project` file with the path to the project's root directory. When the toolchains are sorted, a virtual environment in the project is not treated as being for that project and therefore is not prioritized.

With this change, if a toolchain does not have a `project` associated with it, we check to see if it is a virtual environment, and if it is we use its parent directory as the `project`. This will make it the top priority (i.e. the default) if there are no other virtual environments for a project, which is what should be expected.

Closes #37509

Release Notes:

- Improved python toolchain prioritization of local virtual environments.

### CODE REVIEW

**Comment by dunkmann00** [comment]
@cla-bot check

File: crates/languages/src/python.rs [hunk 1]
```diff
@@ -732,6 +748,31 @@ async fn get_worktree_venv_declaration(worktree_root: &Path) -> Option<String> {
...
+
+    // Check to be sure we are a virtual environment using pet's most generic
+    // virtual environment type, VirtualEnv
+    if let Some(venv) = venv
+        && is_virtualenv_dir(venv)
+    {
+        venv.parent().map(|parent| parent.to_path_buf())
+    } else {
+        None
+    }
```
Comment (osiewicz) [inline crates/languages/src/python.rs]:
```suggestion
    // Check to be sure we are a virtual environment using pet's most generic
    // virtual environment type, VirtualEnv
    let venv = env
        .executable
        .as_ref()
        .and_then(|p| p.parent())
        .and_then(|p| p.parent())
        .filter(is_virtualenv_dir)?;

    venv.parent().map(|parent| parent.to_path_buf())
```

File: crates/languages/src/python.rs [hunk 2]
```diff
@@ -791,11 +832,23 @@ impl ToolchainLister for PythonToolchainProvider {
...
+                    .as_ref()
+                    .or(get_venv_parent_dir(lhs).as_ref())
+                    .map(|p| p.to_path_buf());
+                let rhs_project = rhs
+                    .project
+                    .as_ref()
+                    .or(get_venv_parent_dir(rhs).as_ref())
+                    .map(|p| p.to_path_buf());
+                match (&lhs_project, &rhs_project) {
+                    (Some(l), Some(r)) => (r == &wr).cmp(&(l == &wr)),
```
Comment (osiewicz) [inline crates/languages/src/python.rs:834]: To be fair we should probably be checking whether the worktree root is a prefix of a candidate venv. That's obviously not a regression from your PR or anything, but maybe it'd be worthwhile to do that here?

File: crates/languages/src/python.rs [hunk 3]
```diff
@@ -791,11 +832,23 @@ impl ToolchainLister for PythonToolchainProvider {
...
-            let proj_ordering = || match (&lhs.project, &rhs.project) {
-                (Some(l), Some(r)) => (r == &wr).cmp(&(l == &wr)),
-                (Some(l), None) if l == &wr => Ordering::Less,
-                (None, Some(r)) if r == &wr => Ordering::Greater,
-                _ => Ordering::Equal,
+            let proj_ordering = || {
+                let lhs_project = lhs
+                    .project
+                    .as_ref()
+                    .or(get_venv_parent_dir(lhs).as_ref())
```
Comment (osiewicz) [inline crates/languages/src/python.rs]: `or` is eager (you'll always run `get_venv_parent_dir`, even if `project` is some.

You should use `or_else`.

File: crates/languages/src/python.rs [hunk 4]
```diff
@@ -791,11 +832,23 @@ impl ToolchainLister for PythonToolchainProvider {
...
+                    .map(|p| p.to_path_buf());
+                let rhs_project = rhs
+                    .project
+                    .as_ref()
+                    .or(get_venv_parent_dir(rhs).as_ref())
```
Comment (osiewicz) [inline crates/languages/src/python.rs]: https://github.com/zed-industries/zed/pull/37510/files#r2332618621

File: crates/languages/src/python.rs (hunk 1 above)
Comment (dunkmann00) [reply crates/languages/src/python.rs]: I'm getting a type mismatch on the filter when I do it this way, `&&Path` instead of `&Path`. I'll do it with a closure instead?

File: crates/languages/src/python.rs (hunk 3 above)
Comment (dunkmann00) [reply crates/languages/src/python.rs]: I'm getting this error with `or_else`:
```
cannot return value referencing temporary value
returns a value referencing data owned by the current function (rustc E0515)
```

I'll add a map before `or_else`?

File: crates/languages/src/python.rs (hunk 2 above)
Comment (dunkmann00) [reply crates/languages/src/python.rs:834]: Would that check go in this match? Also, are you saying we shouldn't show any toolchains where the worktree root is not a prefix?

File: crates/languages/src/python.rs (hunk 3 above)
Comment (dunkmann00) [reply crates/languages/src/python.rs]: I just used `clone`. You can see the change in the new commits.

File: crates/languages/src/python.rs (hunk 1 above)
Comment (osiewicz) [reply crates/languages/src/python.rs]: Yep, sure. I wrote this patch directly within GitHub interface, so there may be problems like such.

File: crates/languages/src/python.rs (hunk 2 above)
Comment (osiewicz) [reply crates/languages/src/python.rs:834]: That check would probably go in this match, yes.
I'm not saying we should not show venvs outside of current worktree - we should just prioritize ones for which the worktree root is a parent. We could even go an extra mile and sort based on distance from worktree root. 

Either way, maybe we could do that in separate PR on a second thought.

File: crates/languages/src/python.rs (hunk 3 above)
Comment (osiewicz) [reply crates/languages/src/python.rs]: Oh yeah, you've probably ran into that borrowck error because of `.as_ref()` at the end.

File: crates/languages/src/python.rs (hunk 2 above)
Comment (dunkmann00) [reply crates/languages/src/python.rs:834]: I see, that does seem useful. I would be happy to try to put a PR together for that if that is okay with you?

**Comment by dunkmann00** [comment]
Fixed clippy errors.

File: crates/languages/src/python.rs (hunk 2 above)
Comment (osiewicz) [reply crates/languages/src/python.rs:834]: Yep.

**Comment by osiewicz** [comment]
Thanks!

**Comment by dunkmann00** [comment]
Thank you! My first Rust PR! 🎉
