### PR TITLE
wayland: Fix window close

### LINKED ISSUE #10483: infinite error loop when trying to close window (`workspace::CloseWindow`)
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

_Warning: don't know if this issue fits on "Crash report" or "Bug report" because the program freezes / crashes, even though it keeps running._

First of all, I followed all the steps for building Zed on Linux following this [document](https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md).

Steps to reproduce the crash:

1. Open the editor (does not matter if it is on a file or not).
2. Press `ctrl+shift+w` for triggering `workspace::CloseWindow` event.

After doing it, the editor freezes and, if we see the terminal logs, here is what we got:

image

It only stops if `^C`

### Environment

Zed: `v0.132.0`

By running `uname -a`:

`Linux hicaro 6.6.25-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:32:38 UTC 2024 x86_64 GNU/Linux`

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by apricotbucket28**
Partially fixes https://github.com/zed-industries/zed/issues/10483 (X11 still has this issue)

Also adds some missing destroy() calls for some objects.
Thanks @phisch!

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/linux/wayland/window.rs [hunk 1]
```diff
@@ -197,12 +212,14 @@ impl WaylandWindow {
         }
 
         // Attempt to set up window decorations based on the requested configuration
+        let mut decoration = None;
```
Comment (phisch) [inline crates/gpui/src/platform/linux/wayland/window.rs:215]: I'd probably do something like this:

```rs
        let decoration = globals
            .decoration_manager
            .as_ref()
            .map(|decoration_manager| {
                let decoration = decoration_manager.get_toplevel_decoration(
                    &toplevel,
                    &globals.qh,
                    surface.id(),
                );
                decoration.set_mode(zxdg_toplevel_decoration_v1::Mode::ClientSide);
                decoration
            });
```

File: crates/gpui/src/platform/linux/wayland/client.rs [hunk 2]
```diff
@@ -163,6 +163,15 @@ impl WaylandClientStatePtr {
                 state.mouse_focused_window = Some(window);
             }
         }
+        if state.windows.is_empty() {
+            state
+                .common
+                .foreground_executor
+                .spawn(async {
+                    std::process::exit(0);
```
Comment (mikayla-maki) [inline crates/gpui/src/platform/linux/wayland/client.rs:171]: We should use calloop to`LoopSignal::stop()` the main loop, so that the quit handler is fired before process exit.

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

File: crates/gpui/src/platform/linux/wayland/client.rs (hunk 2 above)
Comment (apricotbucket28) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: I tried doing that, but the process would seg fault.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: We should fix that seg fault then, it's important that the quit handler gets called so applications have a chance to clean things up.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: I do know we already have a seg fault on exit, so I don't think you need to fix it in this PR if it's pre-existing :)

Comment (apricotbucket28) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Weird thing is that on X11, `state.common.signal.stop()` is called, and it exits properly.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Yeah, I think we're dropping things in the wrong order.

Comment (apricotbucket28) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: I've debugged the crash and looks like the issue is with the `copypasta` crate, since `smithay-clipboard` (the underlying library which it uses on Wayland) isn't notified that we closed everything, so it crashes.
image
image

Maybe we should switch to using `smithay-clipboard` directly since it basically is the same API? Any way, should I change this PR to stop the event loop and fix that issue in different one?

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Ahhhh, that makes a lot of sense. Yeah, let's fix the clipboard issue in a separate PR.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Can we just drop the clipboard after `quit()` but before `run()` exits? Or do we need to drop them from within the running loop?

Comment (apricotbucket28) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: I get this error when trying to drop it in the `state.windows.is_empty()` check
image

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: I was actually thinking we could drop them in `WaylandClient::run()`

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Or the `platform.rs` run implementation could call a new method on `LinuxClient` after the `quit` callback is run, that gives the wayland platform a chance to drop the clipboards.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:171]: Either way though, you'll need to put them in an option or something so you can take them out.

File: crates/gpui/src/platform/linux/wayland/client.rs [hunk 3]
```diff
@@ -163,6 +163,12 @@ impl WaylandClientStatePtr {
                 state.mouse_focused_window = Some(window);
             }
         }
+        if state.windows.is_empty() {
+            // Drop the clipboard to prevent a seg fault after we've closed all Wayland connections.
+            state.clipboard = None;
```
Comment (mikayla-maki) [inline crates/gpui/src/platform/linux/wayland/client.rs:168]: This should also be done when quitting the application normally, e.g. on `crates/gpui/src/platform/linux/platform.rs:131`

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

File: crates/gpui/src/platform/linux/wayland/client.rs (hunk 3 above)
Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/client.rs:168]: Actually, there's more problems than that, as we don't drop any windows either. Let's fix all of that in a follow up.

**Review by mikayla-maki — APPROVED** [review]
