### PR TITLE
worktree: Fix privacy check for singleton files

### LINKED ISSUE #20676: redact_private_values setting is not always respected
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening `.env` file with this option set to true (it's disabled by default, why?), values are still being shown

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 15.2 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 (WHL GT2) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by cole-miller**
Closes #20676

Release Notes:

- Fixed private files not being redacted when not part of a larger worktree

### CODE REVIEW

File: crates/worktree/src/worktree.rs [hunk 1]
```diff
@@ -445,10 +432,26 @@ impl Worktree {
...
+            let share_private_files = false;
+            if let Some(metadata) = metadata {
+                let mut entry = Entry::new(
+                    Arc::from(Path::new("")),
+                    &metadata,
+                    &next_entry_id,
+                    snapshot.root_char_bag,
+                    None,
+                );
+                if !metadata.is_dir {
```
Comment (cole-miller) [inline crates/worktree/src/worktree.rs:444]: Note to self, this needs adjusting to deal with symlinks

File: crates/worktree/src/worktree_tests.rs [hunk 2]
```diff
@@ -2712,6 +2712,28 @@ async fn test_propagate_git_statuses(cx: &mut TestAppContext) {
     );
 }
 
+#[gpui::test]
+async fn test_privacy(cx: &mut TestAppContext) {
```
Comment (maxbrunsfeld) [inline crates/worktree/src/worktree_tests.rs:2716]: Very minor: I'd give this test a more specific name like `testprivate_single_file_worktree`

File: crates/worktree/src/worktree.rs (hunk 1 above)
Comment (cole-miller) [reply crates/worktree/src/worktree.rs:444]: I don't think this is an issue after all; at least I don't see anywhere else that we take symlink resolution into account is the `is_path_private` calculation
