### PR TITLE
Language independent hotkeys

### LINKED ISSUE #24499: Hotkeys not working on Ubuntu 20.04 when Cyrillic locale is used
### Summary

Steps to trigger the problem:
1. Install latest Zed version on Ubuntu 20.04 with latest updates
2. Have 2 locales in system, e.g. English and Russian
3. Press ctrl+s when Russian locale is on. 

Actual Behavior: file is not saved

Expected Behavior: file is saved

Same problems occurs with all other key bindings.

I tried  to set use_layout_keys: true in my settings.json (btw it did not auto-suggest this key).
I also tried use_key_equivalents in keymap.json under all contexts. Did not helped either.

When I open Debug: open key context window, i press ctrl+s when russian locale is on and I see:
ctrl-cyrillic_yeru

I added "ctrl-cyrillic_yeru": "workspace::Save" to my keymap.json and it solved the problem. Maybe I could event generate all key bindings using Zed assistant and this will work. So this bug has a tricky workaround. 

Still such nasty bugs may push new users away from this great editor.

### Zed Version and System Specs

Zed: v0.172.10 (Zed)
OS: Linux X11 ubuntu 20.04
Memory: 94.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3090 || NVIDIA || 565.57.01

### LINKED ISSUE #24950: Key bindings doesn't run on other keyboard layouts other than English
### Summary

Key bindings works only when keyboard layout is English. Suppose I want to save a file with Ctrl+s but when I change the layout to another language like Persian, I think it's interpreter like Ctrl+س and does not work. (Maybe for some layouts that has common letters with English this isn't a problem)

For vim bindings, this is a reasonable result as vim does the same but for other key bindings other code editors treat all keyboard layouts the same.

Steps to trigger the problem:
1. Change the keyboard layout to Persian or Arabic
2. Trigger a key binding like Ctrl+s

Actual Behavior:
It does not save the file.

### Zed Version and System Specs

Zed: v0.173.10 (Zed) 
OS: Linux Wayland debian 12
Memory: 11.6 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 620 (KBL GT2) || Intel open-source Mesa driver || Mesa 22.3.6

### PR DESCRIPTION
**Pull request by stillonearth**
Addresses #10972 
Closes #24950
Closes #24499

Adds _key_en_  to _Keystroke_ that is derived from key's scan code. This is more lightweight approach than #32529

Currently has been tested on x11 and windows. Mac code hasn't been implemented yet.

Release Notes:

- linux: When typing non-ASCII keys on Linux we will now also match keybindings against the QWERTY-equivalent layout. This should allow most of Zed's builtin shortcuts to work out of the box on most keyboard layouts. **Breaking change**: If you had been using `keysym` names in your keyboard shortcut file (`ctrl-cyrillic_yeru`, etc.) you should now use the QWERTY-equivalent characters instead.

### CODE REVIEW

**Comment by stillonearth** [comment]
@cla-bot check

**Comment by tidely** [comment]
Does key_en need to be represented as a `String`? I think we should use a char instead, which wouldn't need an allocation at all

**Comment by stillonearth** [comment]
That's correct, but then there's an allocation in Keystroke::should_match

**Comment by stillonearth** [comment]
It also seems that hotkeys work on windows without this fix. This also need to be checked on mac.

File: crates/gpui/src/platform/keystroke.rs [hunk 1]
```diff
@@ -73,6 +76,18 @@ impl Keystroke {
...
         }
 
+        #[cfg(not(target_os = "windows"))]
+        if let Some(key_en) = self.key_en.as_ref() {
+            let ime_modifiers = Modifiers {
+                control: self.modifiers.control,
+                platform: self.modifiers.platform,
+                ..Default::default()
+            };
+            if target.key == String::from(*key_en) && target.modifiers == ime_modifiers {
```
Comment (tidely) [inline crates/gpui/src/platform/keystroke.rs]: We can save the `String` allocation by using something like this

```rust
s.len() == c.len_utf8() && s.chars().next() == Some(c)
```

`s` here is `target.key` and `c` is `key_en`. This ensures `target.key` is the same length as the compared `char`, and then uses the first element of the `chars` iterator to compare the value

**Comment by ConradIrwin** [comment]
@stillonearth thanks for this!

To be consistent with how this is handled on macOS, `key` should be set to the ASCII version; and `key_char` to the non-ASCII key when they differ. I don't think we should add `key_en` at all.

**Comment by ConradIrwin** [comment]
To add a bit more color here... on macOS this code should not be needed; but we don't yet (on Linux or Windows) have a good story around international shortcuts.

The way it works on macOS is that we copy the system's shortcut localization. On Linux and Windows, I think the right approach is more like this, where we localize shortcuts without changing which key you need to press to trigger them.

What I would ideally like though is the reverse. Is it possible on Wayland/X11 to look up the key that is generated by a specific scan code?

There are three kinds of keyboard to consider:
1. non-Latin. On macOS we still use keyboard shortcuts in Latin (because the macOS keyboards always use a Latin layout when the cmd- modifier is held down). When the q key is pressed on a Russian keyboard you get a KeyPress with `key: 'q', key_char: 'й'`. This lets you match key-bindings with either `ctrl-q` or `ctrl-й`.
2. extended Latin. On macOS we localize the shortcuts in this case, so that when you press a key it maps uniquely to a shortcut (i.e. in German, which doesn't have a ] key, we change ctrl-] to ctrl-ä when loading the key map).
3. Dvorak/Colemac. These are just the same as QWERTY keyboards but shuffled.

I think a sensible first step for Linux would be:
* When loading the builtin key-maps (with `use_key_equivalents: true`) map backwards through the scan code table; so `ctrl-q` becomes `ctrl-й` on a Russian keyboard. Or `ctrl-]` becomes `ctrl-+` on a German keyboard. We do this when we load the keymap so that we render the shortcut in the UI using the same keys that you have to type to trigger it.
* The exception to that is for `a-z` when the keyboard contains these characters, in which case the shortcut moves with the letter (i.e. ctrl-q on QWERTY is still typed as ctrl-q on AZERTY, not ctrl-a).
* For Dvorak/Colemac, no mapping is needed; and the shortcuts move with the characters.

If we wanted to be more like macOS, then for layouts like Russian that do not let you type ASCII at all, we could keep the shortcut as `ctrl-q` and set `key: q, key_char: й`. The other advantage of this is that it lets you use vim-mode without changing layouts, but it also seems fine to defer til later.

**Comment by stillonearth** [comment]
> @stillonearth thanks for this!
> 
> To be consistent with how this is handled on macOS, `key` should be set to the ASCII version; and `key_char` to the non-ASCII key when they differ. I don't think we should add `key_en` at all.

It's now consistent between windows, x11 and wayland, where key would be a ascii-mapped key from a scan code.

**Comment by stillonearth** [comment]
I've checked hotkeys on different layouts across all platforms and indeed the problem was only with linux implementation that has been addressed. Now it should work across all supported platforms.

**Comment by ConradIrwin** [comment]
@stillonearth I pushed up some tidy-up. In particular the Zed builds we ship always have both X11 and Wayland features enabled (as we don't know which window manager people are using) so I moved that check to runtime. I also noticed (and verified by searching the internet) that the key-codes for Wayland and X11 are just offset by 8, so I merged the lookup tables into one.

I'll plan to merge this soon, but let me know if I've broken something that was working.

**Comment by evtn** [comment]
There's also an important thing to consider apart from the letter block on non-Latin layouts

For example, pressing `Shift+;` on `en-us`-qwerty gives `:`, but `Ж` on `ru`-qwerty. 
I'd argue that while semicolon is ASCII, and can be written in `ru` layout (Shift+4), all shortcuts on non-latin layouts should follow the scan keys and disregard the written characters. 

That is because virtually all non-latin layout users write latin via an extra English layout, and if shortcuts are differently placed on different layouts, that would break the flow completely, because we switch between those layouts countless times and remembering two sets of shortcuts based on that is a mess.

**Comment by ConradIrwin** [comment]
@evtn There are three related issues to untangle:

* What key do you need to press to trigger a shortcut
* What do we show in the UI to tell you which key to press
* What do you put in your keymap file to bind to that key.

Although I like the simplicity of "all keyboard shortcuts are based on scan codes" for the first issue, it leaves issues 2 & 3 confusing. It also does not work well for extended latin keyboards (On a French keyboard ctrl-a is typed using the QWERTY q key, but it should still select all and not quit the app.)

I think this branch is an improvement over the status quo, so I've merged it, but there's more work to do here.

I think the next steps are (probably):

* When reading the keymap, look at the current keyboard layout and adjust keyboard shortcuts using 
* if the current layout is mostly non-ASCII, keep shortcuts in the same place but update the UI to show them using your current layout.
* if the current layout is extended-latin, keep *most* shortcuts along with the named key, and reposition any that are no longer able to be produced (this is similar to how we solve the problem on macOS, and how VSCode attacks the issue)

**Comment by osyvokon** [comment]
Unfortunately, this PR completely broke keyboard input for me. I'm on Wayland, and despite what this [comment](https://github.com/zed-industries/zed/pull/34053/files#diff-042071eb7888220217c4dc120c52bde438493ef5388e17fa8f0a399e6555f0c0R721-R722) says, it gets same keycodes as X11 (i.e., shifted by 8)

**Comment by osyvokon** [comment]
Okay, it seems like we are already converting Wayland keycodes to X11's: https://github.com/zed-industries/zed/blob/f50041779dcfd7a76c8aec293361c60c53f02d51/crates/gpui/src/platform/linux/wayland/client.rs#L1294

https://github.com/zed-industries/zed/pull/34396 fixes the double conversion.

**Comment by RGFTheCoder** [comment]
is there any way to disable this planned? This destroys my muscle memory, and it's not even about relearning since every other program uses the actual c/v keys. Ideally all programs would do this, but I think overriding it on a single program makes things less consistent.

**Comment by evtn** [comment]
@RGFTheCoder as far as I understand, the plan is to enable the scankey-based approach only on non-Latin keyboard layouts, so if you use a latin keyboard layout (e.g. French AZERTY or some non-standard English one), then shortcuts will use letters' "actual" positions. 

It seems that this commit left preview version in a half-baked state, but the next release should be good to go (I hope both for french and non-latin users, Zed and Kitty Terminal are driving me mad with this)

**Comment by ConradIrwin** [comment]
Please update to the latest preview (0.196.4) and let me know if this has broken anything for you. In theory this was supposed to be a purely additive change, but we messed it up in 0.196.0.

**Comment by AlexDaniel** [comment]
This broke arrow key handling for me (and Home/End). Discord context:
* https://discord.com/channels/869392257814519848/1204679850208657418/1396814210561998968
* https://discord.com/channels/869392257814519848/1204679850208657418/1396818679018291290
* Tips on how to reproduce: https://discord.com/channels/869392257814519848/1396837180411875460

**Comment by stillonearth** [comment]
@AlexDaniel #34823 should address this issue.
