### PR TITLE
shell: Load SHELL from passwd entry if launched as desktop app

### LINKED ISSUE #8794: Zed Terminal opens bash with Raycast, but with zsh(default shell) with Spotlight.
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed `settings.json`

```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "theme": {
    "light": "Ayu Light",
    "dark": "Ayu Dark"
  },
  "vim_mode": true,
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "terminal": {
    "blinking": "terminal_controlled",
    "copy_on_select": false,
    "working_directory": "current_project_directory"
  },
  "format_on_save": "on",
  "lsp": {
    "gopls": {
      "initialization_options": {
        "gofumpt": true
      }
    }
  }
}

```

Video:
https://github.com/zed-industries/zed/assets/124118626/78034b9a-25fc-45b5-a60f-69bbc8f224c3

### Environment

MacBook Pro
13-inch, M2, 2022
Chip: M2
Memory: 16 GB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #8794 and other related problems.

The problem, in short, is this: `$SHELL` might be outdated. This code ensures that we update `$SHELL` to what we can deem the newest version, if we're started as a desktop application.

The background is that you can get the user's preferred shell in two ways:

1. Read the `SHELL` env variable
2. Read the `/etc/passwd` file and check which shell is set

Most applications should and do prefer (1) over (2).

Why is it preferred? Reading `SHELL` means that processes can inherit the variable from each other. And you can do something like `SHELL=/bin/cool-shell ./my-cool-app`

But what happens if the application was launched from the desktop? Which SHELL env does it inherit then?

It inherits the env from the process that launched it, which is Finder.app or launchd or GNOME or something else — these are all long-running processes that get their environment when the user logs in.

They do *not* get a new environment unless restarted (either process restarted or computer restarted)

That means the `SHELL` env variable they have might be outdated.

That's a problem if you, for example, change your shell with `chsh` and then launch the app from the desktop.

That change of the default shell is not reflected in the app if the app only reads from SHELL. Because that hasn’t been updated. Instead it should read from passwd file to get the newest value.

Release Notes:

- Fixed SHELL being outdated if Zed was launched via Finder or Raycast or other desktop launchers. ([#8794](https://github.com/zed-industries/zed/issues/8794))

### CODE REVIEW

File: crates/zed/src/main.rs [hunk 1]
```diff
@@ -306,6 +306,10 @@ fn main() {
         Task::ready(())
     } else {
         app.background_executor().spawn(async {
+            #[cfg(not(target_os = "windows"))]
```
Comment (mrnugget) [inline crates/zed/src/main.rs:309]:
```suggestion
            #[cfg(unix))]
```

File: crates/zed/src/main.rs [hunk 2]
```diff
@@ -678,6 +682,48 @@ fn init_stdout_logger() {
         })
         .init();
 }
+
+#[cfg(not(target_os = "windows"))]
```
Comment (mrnugget) [inline crates/zed/src/main.rs:686]:
```suggestion
#[cfg(unix)]
```
