### PR TITLE
open_router: Fix tool_choice getting serialized to null

### LINKED ISSUE #34314: AI: Invalid ToolChoice parameter using Mistral models on OpenRouter
### Summary

Using any Mistral model (specifically I tried the new Devstral Medium and Devstral Small 1.1) through OpenRouter fails to make any changes to files.

### Description

Steps to trigger the problem:
1. Select Devstral Medium through OpenRouter as the model
2. Ask the model to make a change to some file

**Expected Behavior**: The model should actually change the file
**Actual Behavior**: There is an error "Failed to connect to OpenRouter API: 422 Unprocessable Entity"

The detailed error message is the following:
```json
{
  "error": {
    "message": "Provider returned error",
    "code": 422,
    "metadata": {
      "raw": {
        "object": "error",
        "message": {
          "detail": [
            {
              "type": "model_attributes_type",
              "loc": ["body", "tool_choice", "ToolChoice"],
              "msg": "Input should be a valid dictionary or object to extract fields from",
              "input": null
            },
            {
              "type": "enum",
              "loc": [
                "body",
                "tool_choice",
                "function-after[operator.attrgetter('value')(), ...]"
              ],
              "msg": "Input should be 'auto', 'none', 'any' or 'required'",
              "input": null,
              "ctx": { "expected": "'auto', 'none', 'any' or 'required'" }
            }
          ]
        },
        "type": "INVALID_REQUEST_ERROR",
        "param": null,
        "code": null
      },
      "provider_name": "Mistral"
    }
  },
  "user_id": "<some-user-id>"
}
```

My best guess is that Mistral can't handle the `tool_choice` parameter being `null`.
Other models on OpenRouter do not have the same issue (for example DeepSeek V3 0324 works).

### Model Provider Details
- Provider: OpenRouter via API key
- Model Name: Devstral Medium
- Mode: Agent Panel
- Other Details (MCPs, other settings, etc): Defaults

### Zed Version and System Specs

Zed: v0.194.3 (Zed) 
OS: macOS 15.5.0
Memory: 8 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by imumesh18**
Closes #34314

This PR resolves an issue where serde(untagged) caused Rust None values to serialize as null, which OpenRouter's Mistral API (when tool_choice is present) incorrectly interprets as a defined value, leading to a 400 error. By replacing serde(untagged) with serde(snake_case), None values are now correctly omitted from the serialized JSON, fixing the problem. 
P.S. A separate PR will address serde(untagged) usage for other providers, as null is not expected for them either.

Release Notes:

- Fix ToolChoice getting serialized to null on OpenRouter

### CODE REVIEW

**Comment by cole-miller** [comment]
Thanks! Using a [toy example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=c1746b0ed7b33866f2864166d2c6e3af) I can reproduce the behavior you're describing with `ToolChoice::None` getting serialized to JSON `null`. (Seems like a footgun in serde_json!)

I don't think just using `serde(rename_all = snake_case)` here is right though. If we do that then the `Other` variant will start getting serialized as

```
{"other": { /* serialized ToolDefinition */ }}
```

which OpenRouter won't accept. [This](https://openrouter.ai/docs/api-reference/overview#completions-request-format) is the shape that they expect for that field, should be possible to cook up a different enum shape that will work for this.

**Comment by imumesh18** [comment]
Actually for time being we can remove other as it's not getting used anyway because zed agent only support none, any and required(code ref:  https://github.com/zed-industries/zed/blob/875c86e3ef30937f07b2db5324bf16331695f39b/crates/language_models/src/provider/open_router.rs#L549) or we can create a custom serialiser for tool_choice. Let me know which one makes more sense to you.

**Comment by cole-miller** [comment]
@imumesh18 I think the type should mirror the shape that's described in the OpenRouter docs:


```
type ToolChoice =
  | 'none'
  | 'auto'
  | {
      type: 'function';
      function: {
        name: string;
      };
    };
```

It's maybe a bit tricky to get to that with just the serde derive attributes, [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=9eed377365925dc9b514694feeb99da8) is one way, but if you can find something more compact/elegant feel free to use that instead!

**Comment by imumesh18** [comment]
Hey @cole-miller yaa that looks better. Can you take a look at this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=fe63547f6b92aa9a788050a700c432d6 I was able to get the same behaviour as your with just serde attributes. Works fine with minimum code and same implementation.

**Comment by cole-miller** [comment]
@imumesh18 looks great! I didn't realize you could apply `untagged` to just one enum variant, good find.

**Comment by imumesh18** [comment]
Pushed the changes @cole-miller , I also realised it just now while trying it out 😄

File: crates/open_router/src/open_router.rs [hunk 1]
```diff
@@ -153,11 +153,12 @@ pub struct RequestUsage {
 }
 
 #[derive(Debug, Serialize, Deserialize)]
-#[serde(untagged)]
+#[serde(rename_all = "lowercase")]
 pub enum ToolChoice {
     Auto,
     Required,
```
Comment (cole-miller) [inline crates/open_router/src/open_router.rs:159]: Is this variant valid at all? I don't see it mentioned in the OpenRouter docs.

Comment (imumesh18) [reply crates/open_router/src/open_router.rs:159]: Here: https://openrouter.ai/docs/api-reference/parameters#tool-choice. It has all the valid value for Toolchoice. It bit hidden in the docs.

Comment (cole-miller) [reply crates/open_router/src/open_router.rs:159]: Thanks! I was thrown off because they don't mention it [here](https://openrouter.ai/docs/api-reference/overview#completions-request-format) but I guess that's a flaw in their docs.

**Review by cole-miller — APPROVED** [review]
Thanks!
