### PR TITLE
Remove empty line when collapsing diagnostics

### LINKED ISSUE #39028: Diagnostics fold sometimes have a gap
### Summary

Weird gap appears between diagnostic excerpts when folded

### Description

Image

DESCRIPTION_HERE

Steps to reproduce:
1. open diagnostics (when many files have warnings or errors)
2. toggle all folds by alt-clicking the downward facing chevron icon
3. gap appears (sometimes)

**Expected Behavior**: All file groups are spaced equally
**Actual Behavior**: Some file present gaps when folded

### Zed Version and System Specs

Zed: v0.205.5 (Zed) 
OS: Windows 10.0.22631
Memory: 63.2 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || Unknown Driver

### PR DESCRIPTION
**Pull request by vmotta8**
Closes #39028

Fixed empty lines appearing when collapsing files with diagnostic messages in the diagnostics panel.

Added a flag to track when processing a `FoldedBuffer` and skip `Near/Below` blocks (diagnostic messages) that immediately follow it. This prevents diagnostics from rendering as empty lines when their file is collapsed.

Before:
before

After:
after

Release Notes:
- Fixed empty lines when collapsing files with diagnostics in the diagnostics panel

### CODE REVIEW

**Comment by vmotta8** [comment]
@cla-bot check

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, the fix looks valid, but all `*Map` structs are Zed's core and last thing needed here is to regress anything.

Can we add a unit test below (block_map.rs has some examples) to cover this case, please?

**Comment by vmotta8** [comment]
Thanks! Added two tests, one for the single-line bug and one to make sure multi-line files still work correctly.

File: crates/editor/src/display_map/block_map.rs [hunk 1]
```diff
@@ -3566,6 +3572,99 @@ mod tests {
         assert_eq!(blocks_snapshot.text(), "abc\n\ndef\nghi\njkl\nmno");
     }
 
+    #[gpui::test]
+    fn test_folded_multiline_buffer_hides_near_blocks(cx: &mut gpui::TestAppContext) {
```
Comment (SomeoneToIgnore) [inline crates/editor/src/display_map/block_map.rs]: To note, this one passes on main, is this intended?
To me, this looks very strange as all of the diagnostics buffer are multiline due to default context used in https://github.com/zed-industries/zed/blob/94f1faffa73c17d22a949de77309c664918e3547/crates/diagnostics/src/diagnostics.rs#L516

File: crates/editor/src/display_map/block_map.rs [hunk 2]
```diff
@@ -701,8 +702,12 @@ impl BlockMap {
                 match block_placement {
                     BlockPlacement::Above(position) => {
                         rows_before_block = position.0 - new_transforms.summary().input_rows;
+                        just_processed_folded_buffer = false;
                     }
                     BlockPlacement::Near(position) | BlockPlacement::Below(position) => {
```
Comment (SomeoneToIgnore) [inline crates/editor/src/display_map/block_map.rs:707]: Also wondering, we do not need to hide `BlockPlacement::Below` when hiding the diagnostics for folded excerpts, do we?

I see the inline assistant pop-up is placed like this, do I miss something else?
If not, that one is auto hidden already we do not need to include it into the change?

**Review by SomeoneToIgnore — COMMENTED** [review]
Great, that's definitely a step forward, thank you for the tests.

File: crates/editor/src/display_map/block_map.rs (hunk 2 above)
Comment (vmotta8) [reply crates/editor/src/display_map/block_map.rs:707]: You're right, diagnostics only use Near. I included Below because both share the same positioning logic (position.0 + 1) and are already handled together in the code.

Do you see any problem keeping it as is?

File: crates/editor/src/display_map/block_map.rs (hunk 1 above)
Comment (vmotta8) [reply crates/editor/src/display_map/block_map.rs]: Yes, it's intentional. The bug happens when diagnostics are on the last line of the excerpt, not about single-line files. I renamed the tests to make this clearer.

`test_folded_buffer_with_near_blocks` passes on main because it tests the case that already works (Near block NOT on last line). The bug only appears in `test_folded_buffer_with_near_blocks_on_last_line` where the Near block IS on the last line.

Here's a screenshot showing the bug:
Screenshot 2025-10-06 at 18 47 40
Screenshot 2025-10-06 at 18 47 45

File: crates/editor/src/display_map/block_map.rs (hunk 2 above)
Comment (SomeoneToIgnore) [reply crates/editor/src/display_map/block_map.rs:707]: Not much, but neither I saw the reason to change it until your comment, thank you.

**Review by SomeoneToIgnore — APPROVED** [review]
Great, thank you for finding the culprit.

**Comment by SomeoneToIgnore** [comment]
(one last `cargo fmt` is needed, it seems)

**Comment by vmotta8** [comment]
@SomeoneToIgnore Hi! The failing test project_tests::test_ignored_dirs_events seems unrelated to this PR (it's testing project file events, while this PR only changes block_map.rs). Could you rerun the CI?

**Comment by vmotta8** [comment]
@SomeoneToIgnore The previous failing test (`test_ignored_dirs_events`) passed this time, but now two different tests failed on "(macOS) Run Clippy and tests": `test_event_stream_delayed_start` and `test_create_dir_all_on_create_entry`.

I noticed other recent PRs are also failing with these same two tests:
  - https://github.com/zed-industries/zed/actions/runs/18317736660/attempts/1
  - https://github.com/zed-industries/zed/actions/runs/18296585409/attempts/1

Both tests still exist on main. Would it make sense to open an issue to track these flaky macOS tests, or should I just wait for another CI rerun?

**Comment by SomeoneToIgnore** [comment]
Thank you for pointing out, have not seen so many flacks before hence something recent.
Makes sense to open an issue, sure (and maybe, a rebase, as large things like https://github.com/zed-industries/zed/pull/39691 were reverted recently)

**Comment by SomeoneToIgnore** [comment]
To note, I do not see those tests flacking anymore, after one macOS stateless runner got restarted.
Seems that the issue is not with that test's code at least.

**Comment by vmotta8** [comment]
Good to know about it! Thanks for the explanation!
