### PR TITLE
Adjust image viewer tab title font

### LINKED ISSUE #9895: Image Viewer: Incorrect font size in tabs
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The font size of image viewer tabs is too big and inconsistent with other tabs

Bildschirmfoto 2024-03-28 um 02 48 22

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by Kalmaegi**
Fix #9895 

Release notes:

- Changed the tab title of the image preview to be the same as the other tabs ([#9895](https://github.com/zed-industries/zed/issues/9895)).

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
Looks great! But I think you have the wrong issue mentioned inside the release notes.

**Comment by weartist** [comment]
> Looks great! But I think you have the wrong issue mentioned inside the release(释放) notes.

Thanks! XD

File: crates/image_viewer/src/image_viewer.rs [hunk 1]
```diff
@@ -73,15 +73,23 @@ impl Item for ImageView {
...
-        self.path
+        let title = self
+            .path
             .file_name()
             .unwrap_or_else(|| self.path.as_os_str())
             .to_string_lossy()
-            .to_string()
-            .into_any_element()
+            .to_string();
+        h_flex()
```
Comment (maxdeviant) [inline crates/image_viewer/src/image_viewer.rs:85]: We shouldn't need this `h_flex` here. We can just render the `Label` directly.

**Comment by rgbkrk** [comment]
Rad, thanks for fixing this. Ready to merge after addressing @maxdeviant's feedback.

File: crates/image_viewer/src/image_viewer.rs [hunk 2]
```diff
@@ -73,14 +73,21 @@ impl Item for ImageView {
...
             .unwrap_or_else(|| self.path.as_os_str())
             .to_string_lossy()
-            .to_string()
+            .to_string();
+        Label::new(title)
+            .color(if selected {
+                Color::Default
+            } else {
+                Color::Muted
+            })
```
Comment (rgbkrk) [inline crates/image_viewer/src/image_viewer.rs:90]: 👍

**Review by rgbkrk — APPROVED** [review]

File: crates/image_viewer/src/image_viewer.rs (hunk 1 above)
Comment (weartist) [reply crates/image_viewer/src/image_viewer.rs]: Thanks！
