### PR TITLE
git: Unify commit popups

### LINKED ISSUE #26424: commit popover in git panel is inconsistent with the one for git blame
### Summary

Popovers are inconsistent between git panel and editor.

Git panel hover state is broken:
1. Can't click commit link
2. PR link missing
3. No avatars

<details><summary>screenshots</summary>

Actual Behavior:

Image

Expected Behavior:

Image

### Zed Version and System Specs

Zed: v0.178.0 (Zed Dev 1a3597d726c3e37d4e9284ad6a009235df7ae96c) (Taylor's Version)
OS: macOS 15.3.1
Memory: 32 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by LoricAndre**
Closes #26424
Supersedes #35328

Originally, `git::blame` uses its own `ParsedCommitMessage` as the source for the commit information, including the PR section. This changes unifies this with `git::repository` and `git_ui::git_panel` by moving this and some other commit-related structs to `git::commit` instead, and making both `git_ui::blame_ui` and `git_ui::git_panel` pull their information from these structs.

Release notes :

- (Let's Git Together) Fixed the commit tooltip in the git panel not showing information like avatars.

### CODE REVIEW

**Comment by LoricAndre** [comment]
@ConradIrwin I added more context to this PR, please check it if you find the time

File: crates/git/src/repository.rs [hunk 1]
```diff
@@ -1151,10 +1151,8 @@ impl GitRepository for RealGitRepository {
     fn blame(&self, path: RepoPath, content: Rope) -> BoxFuture<'_, Result<crate::blame::Blame>> {
         let working_directory = self.working_directory();
         let git_binary_path = self.git_binary_path.clone();
-
-        let remote_url = self
-            .remote_url("upstream")
-            .or_else(|| self.remote_url("origin"));
+        // WARN: this will check for origin, then upstream. Previously, they were inverted
+        let remote_url = self.default_remote_url();
```
Comment (cole-miller) [inline crates/git/src/repository.rs]: I think checking for upstream first was intentional.

File: crates/git/src/commit.rs
Comment (cole-miller) [inline crates/git/src/commit.rs:1]: According to git this is a binary file--could you figure out what stray bytes got committed and remove them?

**Review by cole-miller — CHANGES_REQUESTED** [review]
Thanks, I like the idea of reducing the duplication here!

This is a bit difficult to review right now because it seems some stray bytes were introduced into commit.rs, causing git to mark that file as binary and preventing it from showing a diff. Could you fix that? Happy to do a more detailed review afterward.

File: crates/git/src/repository.rs (hunk 1 above)
Comment (LoricAndre) [reply crates/git/src/repository.rs]: The code has been reverting, this comment was a leftover, good catch. I'll fix this as I rebase

File: crates/git/src/commit.rs
Comment (LoricAndre) [reply crates/git/src/commit.rs:1]: This should be fixed with a rebase, I'll push one soon for you to review properly

File: crates/git/src/commit.rs [hunk 2]
```diff
@@ -75,6 +80,107 @@ pub fn parse_git_diff_name_status(content: &str) -> impl Iterator<Item = (&str,
...
+    fn eq(&self, other: &Self) -> bool {
+        self.sha == other.sha
+    }
+}
+impl Eq for CommitSummary {}
+impl Hash for CommitSummary {
+    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
+        self.sha.hash(state);
+    }
+}
```
Comment (cole-miller) [inline crates/git/src/commit.rs]: I get what these custom impls are going for, but I'd prefer to use the derived ones that account for all fields (if we need PartialEq/Eq/Hash) at all:
- it's very unlikely we are comparing `CommitSummary` in a real-world context where the savings from just comparing the SHAs matter
- it's much more likely we'd want to compare `CommitSummary` in tests where we want to actually check that all the fields match

File: crates/git/src/commit.rs [hunk 3]
```diff
@@ -75,6 +80,107 @@ pub fn parse_git_diff_name_status(content: &str) -> impl Iterator<Item = (&str,
...
+
+impl PartialEq for CommitDetails {
+    fn eq(&self, other: &Self) -> bool {
+        self.sha == other.sha
+    }
+}
+
+impl Eq for CommitDetails {}
```
Comment (cole-miller) [inline crates/git/src/commit.rs]: Ditto the PartialEq and Eq impls here, and I'd rather not have the Default impl at all because calling `now_utc` in it feels like a footgun

File: crates/git/src/commit.rs [hunk 4]
```diff
@@ -75,6 +80,107 @@ pub fn parse_git_diff_name_status(content: &str) -> impl Iterator<Item = (&str,
...
+        } else {
+            Self::from_message(message)
+        }
+    }
+    pub fn from_message(message: String) -> Self {
+        Self {
+            message: message.into(),
+            ..Default::default()
+        }
+    }
```
Comment (cole-miller) [inline crates/git/src/commit.rs]: Only used once so can be inlined?

File: crates/git/src/repository.rs [hunk 5]
```diff
@@ -360,6 +339,10 @@ pub trait GitRepository: Send + Sync {
 
     /// Returns the URL of the remote with the given name.
     fn remote_url(&self, name: &str) -> Option<String>;
+    fn default_remote_url(&self) -> Option<String> {
+        self.remote_url("upstream")
+            .or_else(|| self.remote_url("origin"))
+    }
```
Comment (cole-miller) [inline crates/git/src/repository.rs]: I don't think this should be a method of the `GitRepository` trait (the point of the trait is to abstract behavior that differs between RealGitRepository and FakeGitRepository, and this isn't in that category)

File: crates/git/src/commit.rs [hunk 6]
```diff
@@ -75,6 +80,107 @@ pub fn parse_git_diff_name_status(content: &str) -> impl Iterator<Item = (&str,
...
+}
+
+#[derive(Clone, Debug)]
+pub struct CommitDetails {
+    pub sha: SharedString,
+    pub author_name: SharedString,
+    pub author_email: SharedString,
+    pub commit_time: OffsetDateTime,
+    pub message: Option<ParsedCommitMessage>,
```
Comment (cole-miller) [inline crates/git/src/commit.rs]: How about continuing to store the unparsed `message: SharedString` on this struct as well, so it's always available? This will save some `.map(...).unwrap_or("")` later on and also seems more correct to me (we always have the raw message available even if we failed to parse it).

**Review by cole-miller — CHANGES_REQUESTED** [review]
Thanks and sorry for the delay in returning to this! I left some feedback about the code style and organization here, just trying to keep the change focused.

File: crates/git/src/commit.rs (hunk 2 above)
Comment (LoricAndre) [reply crates/git/src/commit.rs]: The custom impl then needs to be for GitRemote, but we'll need it for one or the other because of the `Arc<dyn GitHostingProvider + Send + Sync + 'static>` in GitRemote

File: crates/git/src/commit.rs (hunk 6 above)
Comment (LoricAndre) [reply crates/git/src/commit.rs]: Editing this so it makes more sense.

The original message is stored in the ParsedCommitMessage anyway. We could then remove the option and have it available as `self.message.message`, or even a `self.raw_message()` method for simple access, in both case removing the excess syntax due to the Option.

What do you think about this ?

File: crates/git/src/commit.rs (hunk 2 above)
Comment (cole-miller) [reply crates/git/src/commit.rs]: Thanks, good point. I guess if we need PartialEq/Eq/Hash then I'd prefer to have the custom impl on GitRemote and have that one use `Arc::ptr_eq` to compare the two providers.

File: crates/git/src/commit.rs (hunk 6 above)
Comment (cole-miller) [reply crates/git/src/commit.rs]: That makes sense!

**Comment by LoricAndre** [comment]
I don't know the rule about closing comments in Zed, so I'm leaving them open but everything should be done @cole-miller

**Comment by cole-miller** [comment]
Hey @LoricAndre, sorry for the slow turnaround here.

I realized when looking over this again that we can solve the original issue with a simpler approach that's a subset of what you've done here: just move `ParsedCommitMessage` to `commit.rs`, and add a `parse` constructor that takes an `Option<Arc<GitHostingProviderRegistry>>`, then use that from both `blame.rs` and `git_panel.rs`. That way we don't have to make any changes to `CommitDetails`, which I think is probably best left alone for this change. Would you be up for implementing that approach? Also happy to open a PR that implements it and credit you as a coauthor if that's easier.

**Comment by LoricAndre** [comment]
Hi @cole-miller, I was about to ask for some input, so the timing is pretty perfect (I have my hands quite full with my other projects, don't worry about taking some time to review).
I think what I just force-pushed matches your comment, could you take a look ? You're right that this makes this change quite a bit simpler

**Comment by LoricAndre** [comment]
I resolved the previous comments as the changes made them obsolete at this point, feel free to reopen anything that you still deem relevant

**Comment by cole-miller** [comment]
Thanks! I just pushed some small tweaks, this is ready to go now.

**Review by cole-miller — APPROVED** [review]

**Comment by LoricAndre** [comment]
Thank you, I had missed that dead code
