### PR TITLE
Fix Wayland crash on AMD GPUs by updating Blade

### LINKED ISSUE #37448: Crash in Linux Wayland every time
### Summary

I open Zed, it says "Application not Responding" and then crashes

### Description

Steps to trigger the problem:
1. have a endeavouros running on wayland
2. run app
3. not responding then crash

Actual Behavior:
crash
Expected Behavior:
not crash

### Zed Version and System Specs

Zed 0.201.8. i can't really copy system specs from Zed, but here it is.
fastfetch
                     ./o.                   arney1@arney-82kt
                   ./sssso-                 -----------------
                 `:osssssss+-               OS: EndeavourOS x86_64
               `:+sssssssssso/.             Host: 82KT (IdeaPad 3 14ALC6)
             `-/ossssssssssssso/.           Kernel: Linux 6.16.4-zen1-1-zen
           `-/+sssssssssssssssso+:`         Uptime: 8 hours, 34 mins
         `-:/+sssssssssssssssssso+/.        Packages: 1992 (pacman), 7 (flatpak-system), 5 (flatpak-user)
       `.://osssssssssssssssssssso++-       Shell: bash 5.3.3
      .://+ssssssssssssssssssssssso++:      Display (LEN9022): 1920x1080 @ 60 Hz in 14" [Built-in]
    .:///ossssssssssssssssssssssssso++:     DE: LXQt 2.2.0
  `:////ssssssssssssssssssssssssssso+++.    WM: Openbox (Wayland)
`-////+ssssssssssssssssssssssssssso++++-    Theme: catppuccin-mocha-mauve [Qt], Breeze-Dark [GTK2], catppuccin-mocha-mauve-standard+default [GTK3], Adwaita [GTK4]
 `..-+oosssssssssssssssssssssssso+++++/`    Icons: Papirus-Dark [Qt], Papirus-Dark [GTK2/3], Adwaita [GTK4]
   ./++++++++++++++++++++++++++++++/:.      Font: Sans (11pt) [Qt], Sans (11pt) [GTK2/3], Adwaita Sans (11pt) [GTK4]
  `:::::::::::::::::::::::::------``        Cursor: catppuccin-mocha-lavender (22px)
                                            Terminal: ghostty 1.1.3-arch1
                                            Terminal Font: FiraCode Nerd Font (13pt)
                                            CPU: AMD Ryzen 5 5500U (12) @ 4.06 GHz
                                            GPU: AMD Lucienne [Integrated]
                                            Memory: 6.37 GiB / 9.55 GiB (67%)
                                            Swap: 1.10 GiB / 8.00 GiB (14%)
                                            Disk (/): 270.29 GiB / 331.38 GiB (82%) - ext4
                                            Local IP (wlan0): 192.168.1.41/24
                                            Battery (L20L2PF0): 93% [Charging, AC Connected]
                                            Locale: en_US.UTF-8Font: Sans (11pt) [Qt], Sans (11pt) [GTK2/3], Adwaita Sans (11pt) 

i use LXQt's wayland beta as Desktop Environment with Hyprland as wm, i tried opening it in pure Hyprland as well, still crashes

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log
2025-09-01T16:27:41+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-01T16:27:41+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-01T16:27:41+07:00 INFO  [crashes] crash handler registered
2025-09-01T16:27:42+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-01T16:27:42+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-01T16:27:42+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-01T16:27:42+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-01T16:27:42+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-01T16:27:43+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-01T16:27:43+07:00 INFO  [language] downloading language server "pylsp"
2025-09-01T16:27:43+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-01T16:27:44+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-01T16:27:44+07:00 ERROR [project::lsp_store] Failed to start language server "discord_presence": initializing server discord_presence, id 3

Caused by:
    Internal error
2025-09-01T16:27:44+07:00 ERROR [project::lsp_store] server stderr: 2025-09-01T09:27:44.267228Z  INFO Starting Discord Presence LSP server v0.8.3
2025-09-01T09:27:44.268022Z  INFO Backend initialized
2025-09-01T09:27:44.268700Z  INFO LSP service created, starting server
2025-09-01T09:27:44.269530Z  INFO Initializing Discord Presence LSP
2025-09-01T09:27:44.269539Z  INFO Workspace path: /home/arney1/Documents/School/Fall%202025/Linear%20Algebra/Tasks/P_3
2025-09-01T09:27:44.269550Z  INFO Workspace set to: P_3
2025-09-01T09:27:44.269676Z  INFO create_client{application_id="1263505205522337886"}: Creating Discord IPC client with app ID: 1263505205522337886
2025-09-01T09:27:44.270299Z ERROR connect: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket
2025-09-01T09:27:44.270310Z ERROR Failed to initialize Discord: Discord error: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket

2025-09-01T16:27:44+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-01T16:27:44+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-01T16:27:44+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45399323498281"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756718864299,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "6a946d8f-a51d-4bbd-8cf9-3e70255c2c57"
}
2025-09-03T08:21:20+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T08:21:20+07:00 INFO  [zed] Using git binary path: None
2025-09-03T08:21:20+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T08:21:20+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T08:21:20+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T08:21:20+07:00 INFO  [crashes] crash handler registered
2025-09-03T08:21:20+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T08:21:20+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T08:21:20+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T08:21:21+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T08:21:22+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T08:21:22+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T08:21:22+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T08:21:22+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T08:21:23+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T08:21:23+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T08:21:23+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T08:21:24+07:00 INFO  [client] set status on client 304332: Authenticated
2025-09-03T08:21:24+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T08:21:24+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T08:21:24+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T08:21:24+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45343031531305"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756862484299,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "cdace39f-0be3-4249-8cd6-b0ab986e399a"
}
2025-09-03T08:44:57+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T08:44:57+07:00 INFO  [zed] Using git binary path: None
2025-09-03T08:44:57+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T08:44:57+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T08:44:57+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T08:44:57+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T08:44:57+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T08:44:57+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T08:44:57+07:00 INFO  [crashes] crash handler registered
2025-09-03T08:44:58+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T08:44:58+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T08:44:58+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T08:44:58+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T08:44:58+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T08:44:58+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T08:44:58+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T08:44:58+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T08:45:07+07:00 ERROR [client] error sending request for url (https://api.zed.dev/telemetry/events?)

Caused by:
    0: client error (Connect)
    1: operation timed out
2025-09-03T08:45:07+07:00 ERROR [copilot] error sending request for url (https://api.github.com/copilot_internal/v2/token)

Caused by:
    0: client error (Connect)
    1: operation timed out
2025-09-03T08:45:08+07:00 INFO  [client] set status on client 0: AuthenticationError
2025-09-03T08:45:08+07:00 ERROR [zed] failed to validate credentials: error sending request for url (https://cloud.zed.dev/client/users/me?)
2025-09-03T08:45:09+07:00 ERROR [gpui] window not found
2025-09-03T08:45:09+07:00 ERROR [gpui] window not found
2025-09-03T08:45:09+07:00 ERROR [gpui::app] timed out waiting on app_will_quit
2025-09-03T08:52:04+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T08:52:05+07:00 INFO  [zed] Using git binary path: None
2025-09-03T08:52:05+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T08:52:05+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T08:52:05+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T08:52:05+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T08:52:05+07:00 INFO  [crashes] crash handler registered
2025-09-03T08:52:05+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T08:52:05+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T08:52:05+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T08:52:06+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T08:52:06+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T08:52:06+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T08:52:06+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T08:52:06+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T08:52:06+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T08:52:06+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T08:52:15+07:00 ERROR [client] error sending request for url (https://api.zed.dev/telemetry/events?)

Caused by:
    0: client error (Connect)
    1: operation timed out
2025-09-03T08:52:15+07:00 ERROR [copilot] error sending request for url (https://api.github.com/copilot_internal/v2/token)

Caused by:
    0: client error (Connect)
    1: operation timed out
2025-09-03T08:52:16+07:00 INFO  [client] set status on client 0: AuthenticationError
2025-09-03T08:52:16+07:00 ERROR [zed] failed to validate credentials: error sending request for url (https://cloud.zed.dev/client/users/me?)
2025-09-03T08:52:16+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T08:52:16+07:00 ERROR [project::lsp_store] Failed to start language server "discord_presence": initializing server discord_presence, id 3

Caused by:
    Internal error
2025-09-03T08:52:16+07:00 ERROR [project::lsp_store] server stderr: 2025-09-03T01:52:16.963918Z  INFO Starting Discord Presence LSP server v0.8.3
2025-09-03T01:52:16.964402Z  INFO Backend initialized
2025-09-03T01:52:16.964852Z  INFO LSP service created, starting server
2025-09-03T01:52:16.965445Z  INFO Initializing Discord Presence LSP
2025-09-03T01:52:16.965450Z  INFO Workspace path: /home/arney1/Documents/School/Fall%202025/Linear%20Algebra/Tasks/P_3
2025-09-03T01:52:16.965455Z  INFO Workspace set to: P_3
2025-09-03T01:52:16.965519Z  INFO create_client{application_id="1263505205522337886"}: Creating Discord IPC client with app ID: 1263505205522337886
2025-09-03T01:52:16.965837Z ERROR connect: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket
2025-09-03T01:52:16.965844Z ERROR Failed to initialize Discord: Discord error: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket

2025-09-03T08:52:16+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T08:52:16+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T08:52:16+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+46219286763305"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756864336995,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "ef855355-eba6-4a31-b325-5c3db3aa7898"
}
2025-09-03T17:04:52+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T17:04:53+07:00 INFO  [zed] Using git binary path: None
2025-09-03T17:04:53+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T17:04:54+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T17:04:54+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T17:04:54+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T17:04:54+07:00 INFO  [crashes] crash handler registered
2025-09-03T17:04:54+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T17:04:54+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T17:04:54+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T17:04:55+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T17:04:55+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T17:04:55+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T17:04:55+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T17:04:55+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T17:04:55+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T17:04:55+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T17:04:56+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T17:04:56+07:00 ERROR [project::lsp_store] Failed to start language server "discord_presence": initializing server discord_presence, id 3

Caused by:
    Internal error
2025-09-03T17:04:56+07:00 ERROR [project::lsp_store] server stderr: 2025-09-03T10:04:56.801834Z  INFO Starting Discord Presence LSP server v0.8.3
2025-09-03T10:04:56.802584Z  INFO Backend initialized
2025-09-03T10:04:56.803195Z  INFO LSP service created, starting server
2025-09-03T10:04:56.804082Z  INFO Initializing Discord Presence LSP
2025-09-03T10:04:56.804091Z  INFO Workspace path: /home/arney1/Documents/School/Fall%202025/Linear%20Algebra/Tasks/P_3
2025-09-03T10:04:56.804098Z  INFO Workspace set to: P_3
2025-09-03T10:04:56.804229Z  INFO create_client{application_id="1263505205522337886"}: Creating Discord IPC client with app ID: 1263505205522337886
2025-09-03T10:04:56.804850Z ERROR connect: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket
2025-09-03T10:04:56.804861Z ERROR Failed to initialize Discord: Discord error: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket

2025-09-03T17:04:56+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T17:04:56+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T17:04:56+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45967436125993"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756893896842,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "2da1842a-ec7a-4244-b568-910635739853"
}
2025-09-03T17:16:50+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T17:16:50+07:00 INFO  [zed] Using git binary path: None
2025-09-03T17:16:50+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T17:16:50+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T17:16:51+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T17:16:51+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T17:16:51+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T17:16:51+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T17:16:51+07:00 INFO  [crashes] crash handler registered
2025-09-03T17:16:51+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T17:16:51+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T17:16:51+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T17:16:51+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T17:16:52+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T17:16:52+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T17:16:52+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T17:16:52+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T17:16:53+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T17:16:53+07:00 ERROR [project::lsp_store] Failed to start language server "discord_presence": initializing server discord_presence, id 3

Caused by:
    Internal error
2025-09-03T17:16:53+07:00 ERROR [project::lsp_store] server stderr: 2025-09-03T10:16:53.651632Z  INFO Starting Discord Presence LSP server v0.8.3
2025-09-03T10:16:53.651830Z  INFO Backend initialized
2025-09-03T10:16:53.651881Z  INFO LSP service created, starting server
2025-09-03T10:16:53.652393Z  INFO Initializing Discord Presence LSP
2025-09-03T10:16:53.652404Z  INFO Workspace path: /home/arney1/Documents/School/Fall%202025/Linear%20Algebra/Tasks/P_3
2025-09-03T10:16:53.652410Z  INFO Workspace set to: P_3
2025-09-03T10:16:53.652518Z  INFO create_client{application_id="1263505205522337886"}: Creating Discord IPC client with app ID: 1263505205522337886
2025-09-03T10:16:53.653157Z ERROR connect: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket
2025-09-03T10:16:53.653169Z ERROR Failed to initialize Discord: Discord error: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket

2025-09-03T17:16:53+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T17:16:53+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T17:16:53+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45141005358889"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756894613681,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "0bc8d8c0-f4d7-4480-b6cd-ef457523d43e"
}
2025-09-03T17:17:43+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T17:17:43+07:00 INFO  [zed] Using git binary path: None
2025-09-03T17:17:43+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T17:17:43+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T17:17:43+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T17:17:43+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T17:17:43+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T17:17:43+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T17:17:43+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T17:17:43+07:00 INFO  [crashes] crash handler registered
2025-09-03T17:17:44+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T17:17:44+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T17:17:44+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T17:17:44+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T17:17:44+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T17:17:44+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T17:17:44+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T17:17:45+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T17:17:45+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T17:17:45+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T17:17:45+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45900266899241"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756894665820,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "09eadeaf-0270-4b60-9618-3a59c8e27c8b"
}
2025-09-03T17:19:54+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T17:19:54+07:00 INFO  [zed] Using git binary path: None
2025-09-03T17:19:54+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T17:19:54+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T17:19:54+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T17:19:54+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T17:19:54+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T17:19:54+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T17:19:54+07:00 INFO  [crashes] crash handler registered
2025-09-03T17:19:55+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T17:19:55+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T17:19:55+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T17:19:55+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T17:19:56+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T17:19:56+07:00 INFO  [project::environment] using project environment variables shell launched in "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3". PATH="/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin:/home/arney1/.config/.foundry/bin"
2025-09-03T17:19:56+07:00 INFO  [language] downloading language server "pylsp"
2025-09-03T17:19:56+07:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/pyright-langserver", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: ["--stdio"]
2025-09-03T17:19:57+07:00 INFO  [lsp] starting language server process. binary path: "/home/arney1/.local/share/zed/extensions/work/discord-presence/discord-presence-lsp-v0.8.3/discord-presence-lsp-x86_64-unknown-linux-gnu/discord-presence-lsp", working directory: "/home/arney1/Documents/School/Fall 2025/Linear Algebra/Tasks/P_3", args: []
2025-09-03T17:19:57+07:00 ERROR [project::lsp_store] Failed to start language server "discord_presence": initializing server discord_presence, id 3

Caused by:
    Internal error
2025-09-03T17:19:57+07:00 ERROR [project::lsp_store] server stderr: 2025-09-03T10:19:57.582876Z  INFO Starting Discord Presence LSP server v0.8.3
2025-09-03T10:19:57.583135Z  INFO Backend initialized
2025-09-03T10:19:57.583204Z  INFO LSP service created, starting server
2025-09-03T10:19:57.583752Z  INFO Initializing Discord Presence LSP
2025-09-03T10:19:57.583764Z  INFO Workspace path: /home/arney1/Documents/School/Fall%202025/Linear%20Algebra/Tasks/P_3
2025-09-03T10:19:57.583771Z  INFO Workspace set to: P_3
2025-09-03T10:19:57.583889Z  INFO create_client{application_id="1263505205522337886"}: Creating Discord IPC client with app ID: 1263505205522337886
2025-09-03T10:19:57.584728Z ERROR connect: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket
2025-09-03T10:19:57.584748Z ERROR Failed to initialize Discord: Discord error: Failed to connect to Discord IPC: Couldn't connect to the Discord IPC socket

2025-09-03T17:19:57+07:00 ERROR [lsp] Shutdown request failure, server discord_presence (id 3): Server not initialized
2025-09-03T17:19:57+07:00 ERROR [crashes] triggering a crash to generate a minidump...
2025-09-03T17:19:57+07:00 ERROR [zed::reliability] {
  "thread": "main",
  "payload": "GPU has crashed, and no debug information is available.",
  "location_data": {
    "file": "/build/.cargo/git/checkouts/blade-26bd638d88226de3/e0ec4e7/blade-graphics/src/vulkan/command.rs",
    "line": 441
  },
  "backtrace": [
    "__libc_start_main+45765454964521"
  ],
  "app_version": "0.201.8",
  "release_channel": "stable",
  "target": "x86_64-unknown-linux-gnu",
  "os_name": "Linux Wayland",
  "os_version": "endeavouros unknown",
  "architecture": "x86_64",
  "panicked_on": 1756894797609,
  "system_id": "134efd15-2c89-4554-b358-ce7746b0b204",
  "installation_id": "45a948b8-cbb1-452a-88da-48cbfc27c1f5",
  "session_id": "6a406c07-81f0-4bb7-9993-d559e5070d37"
}
2025-09-03T17:22:25+07:00 INFO  [zed] ========== starting zed version 0.201.8, sha unknown ==========
2025-09-03T17:22:25+07:00 INFO  [crashes] spawning crash handler process
2025-09-03T17:22:25+07:00 INFO  [zed] Using git binary path: None
2025-09-03T17:22:25+07:00 WARN  [zed::reliability] Minidump endpoint not set
2025-09-03T17:22:25+07:00 INFO  [extension_host] extensions updated. loading 17, reloading 0, unloading 0
2025-09-03T17:22:25+07:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-09-03T17:22:25+07:00 INFO  [util] set environment variables from shell:/bin/bash, path:/home/arney1/.ghcup/bin:/usr/lib/qt6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/arney1/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/arney1/.config/.foundry/bin
2025-09-03T17:22:25+07:00 INFO  [crashes] connected to crash handler process after 100ms
2025-09-03T17:22:25+07:00 INFO  [crashes] crash handler registered
2025-09-03T17:22:26+07:00 INFO  [client] set status on client 0: Authenticating
2025-09-03T17:22:26+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-09-03T17:22:26+07:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon Graphics (RADV RENOIR)", driver_name: "radv", driver_info: "Mesa 25.2.1-arch1.5" }
2025-09-03T17:22:26+07:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-09-03T17:22:26+07:00 ERROR [agent_ui::language_model_selector] Failed to authenticate provider: Anthropic: credentials not found
2025-09-03T17:22:29+07:00 INFO  [client] set status on client 304332: Authenticated

```

</details>

### PR DESCRIPTION
**Pull request by WERDXZ**
Updates blade-graphics from e0ec4e7 to bfa594e to fix GPU crashes on Wayland with AMD graphics cards.

The crash was caused by incorrect BLAS scratch buffer alignment - the old version hardcoded 256-byte alignment, but AMD GPUs require different alignment values. The newer Blade version uses the GPU's actual alignment requirements instead of hardcoding.

Closes #37448

Release Notes:

- Migrate to newer version of Blade upstream

### CODE REVIEW

**Comment by WERDXZ** [comment]
Might also fixes: #37363

**Comment by WERDXZ** [comment]
Might also fixes: #37363
(

File: crates/gpui/src/platform/blade/blade_renderer.rs [hunk 1]
```diff
@@ -369,9 +369,9 @@ impl BladeRenderer {
             .ok()
             .and_then(|v| v.parse().ok())
             .or_else(|| {
-                [4, 2, 1]
-                    .into_iter()
-                    .find(|count| context.gpu.supports_texture_sample_count(*count))
+                [4, 2, 1].into_iter().find(|count| {
+                    context.gpu.capabilities().sample_count_mask & (1 << (*count - 1)) != 0
```
Comment (huacnlee) [inline crates/gpui/src/platform/blade/blade_renderer.rs]: Why not write like the Blade example:

```rs
let caps = context.capabilities();
let sample_count = [4, 2, 1]
    .into_iter()
    .find(|&n| (caps.sample_count_mask & n) != 0)
```

https://github.com/kvark/blade/blob/bfa594ea697d4b6326ea29f747525c85ecf933b9/examples/particle/main.rs#L133-L137

Comment (WERDXZ) [reply crates/gpui/src/platform/blade/blade_renderer.rs]: Good point lemme fix it real quick

**Comment by yara-blue** [comment]
@WERDXZ Thanks for debugging this and the fix! Looks great. Lets get this merged :tada:

**Comment by WERDXZ** [comment]
@dvdsk 

This is not fixed, crash still happened occasionally:( unfortunately, still working on it lol

**Comment by yara-blue** [comment]
> This is not fixed, crash still happened occasionally:( unfortunately, still working on it lol

In that case let me thank you even more for not only providing this fix but searching on for more!

**Comment by WERDXZ** [comment]
@dvdsk 
after some research here is what I got:

1. Blade Graphics (blade-graphics/src/vulkan/mod.rs:489-512)
    - Passes binary semaphores in timeline value arrays with signal_values_all[1] = 0
    - This is Vulkan spec-compliant
2. AMDVLK Driver (xgl/icd/api/vk_queue.cpp:1943-1979)
    - Bug: Binary semaphores get pointValue = 0 passed to PAL instead of being handled separately
3. PAL Layer (pal/src/core/os/amdgpu/amdgpuQueue.cpp:588)
    - Bug: semaphoreInfo.value = value; stores invalid timeline value 0 for binary semaphores
4. amdgpu Kernel Driver (drivers/gpu/drm/amd/amdgpu/amdgpu_cs.c:469)
    - Calls drm_syncobj_find_fence(p->filp, handle, point, flags, &fence)
5. DRM Syncobj Core (drivers/gpu/drm/drm_syncobj.c:463)
    - Calls dma_fence_chain_find_seqno(fence, point) where point = 0
6. DMA Fence Chain (drivers/dma-buf/dma-fence-chain.c:98)
    - THE KERNEL BUG: Binary semaphores get treated as timeline semaphores
    - When seqno = 0 and fence is not a chain (!chain), returns -EINVAL
7. Error Propagation Back Up:
    - dma_fence_chain_find_seqno() returns -EINVAL
    - drm_syncobj_find_fence() returns -EINVAL
    - amdgpu_syncobj_lookup_and_add() returns -EINVAL
    - PAL converts -EINVAL to Pal::Result::ErrorInvalidValue
8. AMDVLK Error Code Conversion (xgl/icd/api/vk_conv.cpp:1016-1072)
    - THE CONVERSION: Pal::Result::ErrorInvalidValue → VK_ERROR_UNKNOWN
    - Line 1069: case Result::ErrorInvalidValue: return VK_ERROR_UNKNOWN;
9. Blade Graphics Panic (blade-graphics/src/vulkan/command.rs:448)
    - VK_ERROR_UNKNOWN causes: panic!("GPU error {}", other)
    
---

As a conclusion

Uninstall `amdvlk` and install `radv`
