### PR TITLE
lsp: Fix language servers not starting up on save

### LINKED ISSUE #24349: Language servers don't start until new file is reopened
### Summary

Steps to trigger the problem:
1. Set up language servers for your language of choice
2. Create a new file, type some code, and save it
3. Do anything that triggers the language server (e.g. format on save, hover over a variable, type some bad code)
4. Close and reopen

Actual Behavior: Zed behaves as if there is no language server configured until the file is reopened

Expected Behavior: The language server should work normally

There is no relevant output in Zed's logs or the LSP logs.

### Zed Version and System Specs

Zed: v0.172.8 (Zed)
OS: macOS 15.3.0
Memory: 16 GiB
Architecture: x86_64

### PR DESCRIPTION
**Pull request by osiewicz**
Closes #24349

Release Notes:

- Fixed language servers not starting up when a buffer is saved.

### CODE REVIEW

File: crates/project/src/project_tests.rs [hunk 1]
```diff
@@ -3584,6 +3584,86 @@ async fn test_save_file(cx: &mut gpui::TestAppContext) {
...
+    });
+
+    project
+        .update(cx, |this, cx| {
+            let worktree_id = this.worktrees(cx).next().unwrap().read(cx).id();
+            this.save_buffer_as(
+                buffer.clone(),
+                ProjectPath {
+                    worktree_id,
+                    path: Arc::from(path!("file.rs").as_ref()),
```
Comment (JunkuiZhang) [inline crates/project/src/project_tests.rs]:
```suggestion
                    path: Arc::from("file.rs".as_ref()),
```
This is a relative file path right? Then I think no need to wrap with `path!`

Comment (osiewicz) [reply crates/project/src/project_tests.rs]: Yup, thanks!
