### PR TITLE
markdown preview: Handle line breaks in between task list items correctly

### LINKED ISSUE #9783: Markdown preview live update fails in some cases
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The rendered markdown view doesn't always correctly update when adding new tasks.

### Environment

Zed: v0.129.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19867440/2b9ec4d6-160f-4bf1-b89e-f010599f0418

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by bennetbo**
Closes #9783 

Release Notes:

- Fixed task list rendering when there was a line break between two list items ([#9783](https://github.com/zed-industries/zed/issues/9783))

### CODE REVIEW

File: crates/markdown_preview/src/markdown_parser.rs [hunk 1]
```diff
@@ -448,13 +452,20 @@ impl<'a> MarkdownParser<'a> {
...
-                            Event::TaskListMarker(checked) => {
-                                task_item = Some(checked);
-                                self.cursor += 1;
+                    if let Some(event) = self.current_event() {
+                        // If there is a linebreak in between two list items the task list marker will actually be the first element of the paragraph
+                        if event == &Event::Start(Tag::Paragraph) {
+                            self.cursor += 1;
+                        }
+
+                        if let Some(event) = self.current_event() {
```
Comment (SomeoneToIgnore) [inline crates/markdown_preview/src/markdown_parser.rs:461]: NIT: It looks you could do smth. like `if let Some(Event::TaskListMarker(checked)) = self.current_event()` here and reduce the nested things a bit.

**Review by SomeoneToIgnore — APPROVED** [review]
Great to see new tests!
