### PR TITLE
edit_prediction: Fix special token check matching `=======` inside comments

### LINKED ISSUE #52489: Edit Predictions do not work if .rs file contains sequence "// ======="
### Reproduction steps

1. Open any rust project in zed.
2. Open any .rs file.
3. Add a line `// =======` in any place of the buffer (at least 7 `=` characters must be used). For example:

    ```rs
    fn main() {
        greet("Alice");
    }

    // ========================================================

    fn greet(name: &str) {
        println!("Hello, {}!", name);
    }
    ```

5. Try to trigger edit prediction.

### Current vs. Expected behavior

Edit predictions stop working when we have a comment line ending with sequence of 7 ore more `=` characters.

Examples to reproduce the issue:

```
// =======

// =========

// some comment that ends with =======
```

Next lines does not trigger the issue:

```
// this line ends with only 6 = characters ======

// ======= this line does not ends by = characters
```

### Zed version and system specs

Zed: v0.229.0
OS: macOS 26.3.1
Memory: 16 GiB
Architecture: aarch64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2026-03-26T14:51:24+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:24+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:26+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:35+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:37+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:37+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:38+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:39+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
2026-03-26T14:51:43+03:00 ERROR [crates/edit_prediction/src/edit_prediction.rs:2195] prompt contains special tokens
```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `zed: Open Default Settings` command
// from the command palette
{
  "show_edit_predictions": true,
  "edit_predictions": {
    "mode": "eager",
    "provider": "zed"
  },
  "auto_indent": "syntax_aware",
  "agent": {
    "default_profile": "write",
    "default_model": {
      "effort": "high",
      "enable_thinking": true,
      "provider": "zed.dev",
      "model": "claude-sonnet-4-6",
    },
    "favorite_models": [
      {
        "provider": "zed.dev",
        "model": "claude-sonnet-4-6",
        "enable_thinking": false
      },
      {
        "provider": "zed.dev",
        "model": "gemini-3.1-pro-preview",
        "enable_thinking": false
      },
      {
        "provider": "zed.dev",
        "model": "gpt-5.3-codex",
        "enable_thinking": false
      },
      {
        "provider": "zed.dev",
        "model": "gemini-3-flash",
        "enable_thinking": false
      }
    ],
    "model_parameters": [],
  },
  "show_wrap_guides": true,
  "wrap_guides": [80, 100],
  "toolbar": {
    "code_actions": false,
  },
  "minimap": {
    "thumb_border": "left_open",
    "show": "never",
  },
  "icon_theme": {
    "mode": "system",
    "light": "Zed (Default)",
    "dark": "Zed (Default)",
  },
  "disable_ai": false,
  "calls": {
    "mute_on_join": false,
  },
  "audio": {
    "experimental.auto_microphone_volume": true,
    "experimental.rodio_audio": true,
    "experimental.auto_speaker_volume": true,
    "experimental.denoise": true,
    "experimental.legacy_audio_compatible": true,
  },
  "diagnostics": {
    "inline": {
      "enabled": false,
    },
  },
  "features": {},
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark",
  },
  "languages": {
    "JSONC": {
      "tab_size": 4
    },
    "Markdown": {
      "remove_trailing_whitespace_on_save": true,
      "format_on_save": "on",
    },
    "Rust": {
      "inlay_hints": {
        "toggle_on_modifiers_press": {
          "alt": true,
          "control": true,
        },
      },
      "wrap_guides": [80, 100],
    },
  },
}
```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by Shiven0504**
Closes #52489

The special token check in `prompt_input_contains_special_tokens` used `String::contains()` to look for `=======\n` in the buffer. This meant any line containing `=======` (like `// =======` section separators) would cause edit predictions to bail out entirely.

Fixed by only matching when the token appears at the start of a line, since the git merge markers are always placed at line boundaries in the prompt.

Added tests for both the helper function and a regression test for the reported issue.

### CODE REVIEW

File: crates/zeta_prompt/src/zeta_prompt.rs [hunk 1]
```diff
@@ -213,7 +213,24 @@ pub struct RelatedExcerpt {
 pub fn prompt_input_contains_special_tokens(input: &ZetaPromptInput, format: ZetaFormat) -> bool {
     special_tokens_for_format(format)
         .iter()
-        .any(|token| input.cursor_excerpt.contains(token))
```
Comment (osyvokon) [inline crates/zeta_prompt/src/zeta_prompt.rs:216]: Not all special tokens occupy a full line, only the ones ending with `\n`. So we should be able to check it like this:

```rust
pub fn prompt_input_contains_special_tokens(input: &ZetaPromptInput, format: ZetaFormat) -> bool {
    special_tokens_for_format(format)
        .iter()
        .any(|token| {
            if let Some(line_token) = token.strip_suffix('\n') {
                input.cursor_excerpt.lines().any(|line| line == line_token)
            } else {
                input.cursor_excerpt.contains(token)
            }
        })
}
```

Comment (Shiven0504) [reply crates/zeta_prompt/src/zeta_prompt.rs:216]: @osyvokon Fixed in the latest commit, special tokens are now matched as complete lines only. Thanks for the feedback!

File: crates/zeta_prompt/src/zeta_prompt.rs [hunk 2]
```diff
@@ -213,7 +213,32 @@ pub struct RelatedExcerpt {
...
+            }
+        })
+}
+
+/// Checks if `text` contains `token` at the start of a line.
+///
+/// Tokens like `"=======\n"` are used as line-level delimiters in the prompt format,
+/// so they should only be considered a match when they appear at the beginning of a line,
+/// not when they're embedded within a line (e.g. `// =======`).
+fn text_contains_line_start_token(text: &str, token: &str) -> bool {
```
Comment (osyvokon) [inline crates/zeta_prompt/src/zeta_prompt.rs]: This code is unused

File: crates/zeta_prompt/src/zeta_prompt.rs [hunk 3]
```diff
@@ -5287,4 +5312,37 @@ mod tests {
         assert_eq!(apply_edit(excerpt, &output1), apply_edit(excerpt, &output2));
         assert_eq!(apply_edit(excerpt, &output1), "new content\n");
     }
+
+    #[test]
+    fn test_text_contains_line_start_token() {
```
Comment (osyvokon) [inline crates/zeta_prompt/src/zeta_prompt.rs]: This test should be either changed to test `prompt_input_contains_special_tokens()`, or removed
