### PR TITLE
editor: Fix duplicate and copy line newlines

### LINKED ISSUE #34797: line copy on a file with only one line doesn't include a line break after paste
### Summary

copy and paste line without line-break doesn't include a new line

### Description

In a file with a single line, using line copy (cmd-c without range), but doesn't include a newline / doesn't treat the copied text as a single line.

Steps to trigger the problem:

1. open a new file. It should have nothing in it.
2. Put some text on the first line, e.g. "foo bar". Do not end with a newline. The file should still only have one line.
3. Cmd-c without range

**Actual Behavior**:
The line is copied and pasted at the end on line.

Image

-> copy -> paste ->

Image

**Expected Behavior**:
It should copy the full line, including a newline. When pasting, the paste should happen on the next line.

On paste, it should look like this:

Image

### Zed Version and System Specs

Zed: v0.195.5 (Zed) 
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by TomPlanche**
Closes #34797 and its child #39508.

zed-#34797-#39508

Release Notes:

- Fixed `editor::DuplicateLineUp` duplicating the last line onto itself when the line doesn't end with a newline (#39508)
- Fixed line copy not including a newline at end of buffer, causing paste to occur on the same line (#34797)

### CODE REVIEW

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -11687,13 +11687,26 @@ impl Editor {
...
-                    Point::new(rows.end.0, 0)
+                    // When duplicating upward, we need to insert before the current line.
+                    // If we're on the last line and it doesn't end with a newline,
+                    // we need to add a newline before the duplicated content.
+                    let needs_leading_newline = rows.end.0 >= buffer.max_point().row
+                        && buffer.max_point().column > 0
+                        && !text.ends_with('\n');
+
+                    if needs_leading_newline {
+                        text.insert(0, '\n');
```
Comment (SomeoneToIgnore) [inline crates/editor/src/editor.rs:11702]: Here and in all other similar edits: I know there are a lot of places like that around, but thinking of the upcoming Windows build: we should add `\r\n` there for Windows, should not we?

https://github.com/zed-industries/zed/blob/096930817b81282fce639dd642fe72644f72d030/crates/text/src/text.rs#L3256-L3262 has some infra.

File: crates/editor/src/editor_tests.rs [hunk 2]
```diff
@@ -26475,3 +26475,62 @@ fn extract_color_inlays(editor: &Editor, cx: &App) -> Vec<Rgba> {
...
+#[gpui::test]
+fn test_duplicate_line_up_on_last_line_without_newline(cx: &mut TestAppContext) {
+    init_test(cx, |_| {});
+
+    let editor = cx.add_window(|window, cx| {
+        let buffer = MultiBuffer::build_simple("line1\nline2", cx);
+        build_editor(buffer, window, cx)
+    });
+
+    _ = editor.update(cx, |editor, window, cx| {
```
Comment (SomeoneToIgnore) [inline crates/editor/src/editor_tests.rs]: NIT: can we `.unwrap()` instead of `_`, so we do not hide errors accidentally?

**Review by SomeoneToIgnore — COMMENTED** [review]
Nice, thank you for the tests and good comments.

I have a small concern related to Windows side of the deal, otherwise LGTM.

File: crates/editor/src/editor.rs (hunk 1 above)
Comment (SomeoneToIgnore) [reply crates/editor/src/editor.rs:11702]: Actually, I have asked around and maybe it's a false concern, as `Buffer::new` does replace all other line endings.

I might be wrong and would be nice to double check how things are working either way (maybe, in a test?).

Comment (SomeoneToIgnore) [reply crates/editor/src/editor.rs:11702]: Sorry for the confusion: indeed, `\r\n` only appear when writing on disk, whatever we do now was good with `\n`.
Let's roll back to whatever form you like and merge things.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks for not forgetting that `.unwrap()`.
