### PR TITLE
Editor tab bar settings

### LINKED ISSUE #11727: `tabs.git_status` default value inconsistency
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `tabs.git_status` value differs between the default settings and the one shown in the autocomplete hint.

| Default Settings |  ~/.config/zed/settings.json |
| ------ | ------ |
| Default settings | User custom settings |

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by alygin**
This PR is another step to tabless editing (#6424, #4963). It adds support for tab bar settings that allow the user to change its placement or to hide completely.

Configuraton:

```json
"tab_bar": {
  "show": true
}
```

Placemnet options are "top", "bottom" and "no".

This PR intentionally doesn't affect tab bars of other panes (Terminal for instance) to keep code changes small. I guess we'll do the rest in separate PRs.

Release Notes:

- Added support for configuring the editor tab bar (part of #6424, #4963).

### CODE REVIEW

**Comment by osiewicz** [comment]
Hey, we already have a setting section for tabs (see e.g  https://github.com/zed-industries/zed/pull/2739); I think your change would fit in better in that.

**Comment by alygin** [comment]
> Hey, thanks for a PR! we already have a setting section for tabs (see e.g #2739); I think your change would fit in better in that.

Oh, thank you for pointing out! I somehow missed that. I'll move the `placement` setting to the existing `tabs`.

**Comment by JosephTLyons** [comment]
Hey @alygin, we actually had a PR open for this at one time, but it was blocked because the team wanted to ensure there was *some* way to know the state of your editor when tabs are hidden. I'm not sure where everyone stands at the moment, but here is the PR with the additional info:

- https://github.com/zed-industries/zed/pull/2742

Specifically, @maxbrunsfeld's comment:

- https://github.com/zed-industries/zed/pull/2742#issuecomment-1640663137

**Comment by alygin** [comment]
@JosephTLyons, thank you for pointing to the existing discussion on the subject! Unfortunately, I didn't see it before.

I'll get back with my ideas / changes later.

**Comment by alygin** [comment]
Filed a feature request: https://github.com/zed-industries/zed/issues/7653

**Comment by wmstack** [comment]
Also worthwhile to have a "merge" placement where the title bar is merged with the tab bar.
https://github.com/microsoft/vscode/issues/107123

**Comment by ConradIrwin** [comment]
@alygin are you still planning to work on this one? If not, I will close to tidy up our PR queue.

**Comment by alygin** [comment]
@ConradIrwin, yes, I'm absolutely committed to this task. This PR is waiting for the [TapSwitcher](https://github.com/zed-industries/zed/issues/7653) to be implemented. And the tab switcher is pretty close, it's waiting for [a couple](https://github.com/zed-industries/zed/pull/8782) [of other](https://github.com/zed-industries/zed/pull/9099) PR's to be merged.

I started all this TabSwitcher thing just to be able to merge this PR and be able to hide the tab bar :)

Though you can close it if it's a burden to keep it in the queue. I'll reopen as soon as all the prerequisites are ready.

**Comment by ConradIrwin** [comment]
Sounds good! Happy to work with you on any of this (there are some slots at
https://calendly.com/conradirwin/pairint, but if none work for you let me
know ***@***.***)

conrad

**Comment by alygin** [comment]
> Sounds good! Happy to work with you on any of this (there are some slots)

Thanks! I've booked a slot.

**Comment by alygin** [comment]
Given the fact that Zed now has Tab Switcher, what other prerequisites must be met so we could allow the user to hide tabs?

**Comment by maxdeviant** [comment]
In https://github.com/zed-industries/zed/pull/10240 we added a new `tab_bar` field to the settings.

Can we put these settings under that instead of under `tabs`?

**Comment by alygin** [comment]
@maxdeviant, thanks for the info! Done.

**Comment by baldwindavid** [comment]
Would this one be risky getting into Preview? Either way, I'm looking forward to stop seeing tabs. 😃  @alygin , really nice work on all of this and the PRs that blocked it.

**Comment by wmstack** [comment]
It is great work, though again, I hope that the tabs might be moved to the title-bar in the future. This is because the title-bar is always there and is mostly empty anyway.

**Comment by alygin** [comment]
> It is great work, though again, I hope that the tabs might be moved to the title-bar in the future. This is because the title-bar is always there and is mostly empty anyway.

@wmstack, thanks. While I like the idea of occupying empty space by something useful, like moving tabs to the title bar, I think there're some design issues yet to be solved.

For instance, let's assume we have tabs in the title bar. The user splits the window into three panes and the currently active pane is the bottom right. Tabs will look confusing in this configuration. They'll look like relating to the top pane.

изображение

Even just splitting the window into two panes vertically and switching to the right pane will leave us with tabs over the left pane while we're working with the right one.

Do you know editors that solve this problem in a good way?

**Comment by pepehandsjpg** [comment]
I'm looking forward to stop seeing tabs too. Great work! Is there anything blocking this MR from being merged?

File: crates/workspace/src/item.rs [hunk 1]
```diff
@@ -36,7 +36,7 @@ use ui::Element as _;
 pub const LEADER_UPDATE_THROTTLE: Duration = Duration::from_millis(200);
 
 #[derive(Deserialize)]
-pub struct ItemSettings {
```
Comment (mikayla-maki) [inline crates/workspace/src/item.rs:39]: Let's revert this name change. We refer to these as 'Item's throughout the rest of the codebase, and I think consistency is important.

File: crates/workspace/src/item.rs [hunk 2]
```diff
@@ -65,10 +65,10 @@ impl ClosePosition {
 }
 
 #[derive(Clone, Default, Serialize, Deserialize, JsonSchema)]
-pub struct ItemSettingsContent {
+pub struct TabsSettingsContent {
     /// Whether to show the Git file status on a tab item.
     ///
-    /// Default: true
```
Comment (mikayla-maki) [inline crates/workspace/src/item.rs:71]: Nice catch!

File: crates/workspace/src/workspace_settings.rs [hunk 3]
```diff
@@ -58,13 +58,30 @@ pub struct WorkspaceSettingsContent {
     pub drop_target_size: Option<f32>,
 }
 
+/// The tab bar placement in a pane.
+#[derive(Copy, Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
+#[serde(rename_all = "snake_case")]
+pub enum TabBarPlacement {
+    /// Don't show tab bar.
+    No,
```
Comment (mikayla-maki) [inline crates/workspace/src/workspace_settings.rs:66]: Let's change this to 'None'

File: docs/src/configuring_zed.md [hunk 4]
```diff
@@ -304,6 +304,104 @@ List of `string` values
 
 `boolean` values
 
+## Editor Tab Bar
```
Comment (mikayla-maki) [inline docs/src/configuring_zed.md:307]: Thank you for writing this documentation!

**Review by mikayla-maki — DISMISSED** [review]
There's a few naming related nitpicks here, but thank you for this PR! The tab removal is working flawlessly :)

Unfortunately, I think there's still a major feature missing from this PR: a discoverable, mouse-accessible UI for accessing the tab switcher when in tabless editing mode. I've updated [Max's comment](https://github.com/zed-industries/zed/pull/2742#issuecomment-1640663137) to reflect the current state of our UI + current progress towards this feature. There's still a few unchecked by my count :)

If it was just adding the button, I'd implement it myself but I think this feature might need more work. The existing tab switcher relies on 'push-to-show' behavior when using the keyboard shortcuts. But a mouse-based interaction needs more of a toggle based flow. Once the UI is ironed out, we'd be happy to have this feature :D

**Comment by alygin** [comment]
@mikayla-maki, do you think something like Open Editors in VS Code or Open Files in Sublime Text will work?

A toggable view in the Project Panel. In Zed it could look something like this:

изображение

**Comment by mikayla-maki** [comment]
@alygin I think that could work too. We’d need to get a once over from @iamnbutler for such a large addition to our UI.

**Comment by wmstack** [comment]
Well @alygin for your questions, I had some different considerations. But first in your diagram above I think that the title-bar should resemble the concept image in #5066, namely, the tabs should be vertically centred without any margin and unfocused tabs should have the same colour as the title-bar.

The idea that I was initially considering was 

1. when there is a vertical split, it would be a split of the tabs in the title-bar as well, just as if it were a tab bar that is split.

2. For horizontal splits or splits that are not supposed to be on the title-bar there could be a new tab-bar separate from the title-bar, just like if the tabs are not hidden.

However, I do have another suggestion, which is inspired by Vivaldi tiles, all the tabs are in the title-bar to the left, and then when you click on them, the focus moves to the different panes

[Vivaldi Relevant Video](https://help.vivaldi.com/tutorials/create-a-split-screen-view-using-tab-selection/)
[Tab Tiling Vivaldi Article](https://help.vivaldi.com/desktop/tabs/tab-tiling/)

File: crates/workspace/src/item.rs (hunk 1 above)
Comment (alygin) [reply crates/workspace/src/item.rs:39]: No problem, but the idea was that this struct is now fully dedicated to tabs settings, it's even exposed to users as `tabs`. It does not (and I guess it will not) have any non-tab-related settings. If there'll be some other item-, but not tab- related settings, they'll probably go to another struct.

**Comment by iamnbutler** [comment]
Sorry I haven't been around to catch up on this thread. It is pretty unlikely we would consider shipping tabs in the title bar without a really compelling solution to it's issues. 

The above screenshot does not reach that bar, and the reason we didn't ship it in the first place is 1) it doesn't mesh well with splits and 2) the titlebar is important real estate foe collaboration, which is a primary concern for us.

I'm not opposed to exploring an option for hiding tabs, or some sort of collapse UI, that works for tabs in the title bar, but just moving the tabs up there is unlikely to be a solution we ship in my opinion.

As for bottom tabs... I'd like to see some examples of this and proof this is something that a large number of people want before we consider adding it.

As for open editors or open files, I think we could do something like this, but I would want to explore the UI further. It doesn't feel very much like native Zed UI.

File: crates/workspace/src/item.rs (hunk 1 above)
Comment (alygin) [reply crates/workspace/src/item.rs]: Reverted

File: crates/workspace/src/workspace_settings.rs (hunk 3 above)
Comment (alygin) [reply crates/workspace/src/workspace_settings.rs]: Renamed

**Comment by wmstack** [comment]
There is also Jon Gjengset, who puts his Firefox tab and search bars on the bottom. I think it is pretty dope.
image

**Comment by baldwindavid** [comment]
@iamnbutler 

> As for bottom tabs... I'd like to see some examples of this and proof this is something that a large number of people want before we consider adding it.

I can't speak for a large number of people, but would note that I place tabs at the bottom of iTerm which feels more out of the way. That being said, as @alygin mentions, the main goal is an option to remove tabs, so perhaps best to limit the scope to that for this PR.

> I'm not opposed to exploring an option for hiding tabs, or some sort of collapse UI, that works for tabs in the title bar, but just moving the tabs up there is unlikely to be a solution we ship in my opinion.

I am a longtime vim user and use vim mode in Zed. I dislike seeing any UI that is already accessible via keyboard. I see the ability to hide tabs as an important step towards vim parity. A "Zed tab" is like a "vim buffer", and you would not see a vim buffer displayed as a tab. You wouldn't see it at all except via keyboard access, which @alygin so kindly implemented in #7653. Confusingly, vim _does_ have things called "tabs" but they are a completely different beast with no current corollary in Zed; closest would probably be the project switcher (which is not really close at all). Anyway, I'd not want to see the Zed tabs, including any sort of "collapsed" or "sidebar" widget.

Again, I can't speak for others, but my perception is that the vast majority of _want_ for this feature would be keyboard-driven because that's how vim, and other modal editors like Helix, work. I generally understand the principle of supporting mouse-driven workflows, but think it goes a bit far here. The `tab_bar.placement` setting is already an enum which supports the ability to do mouse-driven workflow with "top" or "bottom". Perhaps there could be other options for "collapsed" and/or "sidebar", but then I'm going to want an option to hide those too. And, if in order to do so, there has to be a way to do it mouse-driven, we enter an infinitely recursive situation.

Anyway, my two cents is that it's okay to provide an option to show or hide the tab bar and if you need a way to access tabs, probably don't hide them :)

**Comment by williamdes** [comment]
About the tab bar, if anyone wants to do feature request about the tab bar: https://github.com/zed-industries/zed/issues/5005
Wrapping tabs would be great!

> Again, I can't speak for others, but my perception is that the vast majority of want for this feature would be keyboard-driven because that's how vim, and other modal editors like Helix, work. 

I prefer my tabs up, because all software has them up. So my window manager bar is up. And all the clicks are to be done up. No need to go from up to down between an editor and the browser for example.

**Comment by baldwindavid** [comment]
@williamdes To be clear, that comment of mine you quoted was regarding hiding tabs completely. Whether an option for tabs at the bottom is provided is not something that matters to me. But for vim and other modal editors tabs are not expected to be displayed at all.

@alygin I've been using this PR daily and hiding tabs. It works great mixed with the tab switcher.

> This PR intentionally doesn't affect tab bars of other panes (Terminal for instance) to keep code changes small. I guess we'll do the rest in separate PRs.

I see this note. I'm not so sure I'd even hide tabs in the terminal just because I typically have just a very limited set that I don't mind seeing. Not that they shouldn't be hideable eventually, but it doesn't look surprising to me. The only thing that took me a bit by surprise was that the tabs display in a project search. That might be a good fast follow if this eventually gets in.

**Comment by 0x2CA** [comment]
> Well @alygin for your questions, I had some different considerations. But first in your diagram above I think that the title-bar should resemble the concept image in #5066, namely, the tabs should be vertically centred without any margin and unfocused tabs should have the same colour as the title-bar.
> 
> The idea that I was initially considering was
> 
> 1. When there is a vertical split, it would be a split of the tabs in the title-bar as well, just as if it were a tab bar that is split.
> 2. For horizontal splits or splits that are not supposed to be on the title-bar there could be a new tab-bar separate from the title-bar, just like if the tabs are not hidden.
> 
> In essence this would be like VSCode with APC Customize UI++ where you hide the title-bar.
> 
> However, I do have another suggestion, which is inspired by Vivaldi tiles, all the tabs are in the title-bar to the left, and then when you click on them, the focus moves to the different panes
> 
> [Vivaldi Relevant Video](https://help.vivaldi.com/tutorials/create-a-split-screen-view-using-tab-selection/) [Tab Tiling Vivaldi Article](https://help.vivaldi.com/desktop/tabs/tab-tiling/)

I think it could be very similar to this

https://github.com/zed-industries/zed/issues/8013#issuecomment-1953342850

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
Given the discussion here, and our designer's skepticism, I'm revising my review:

This PR is great as is, let's remove the 'bottom' placement for tabs until we have more data, and then we can merge this :)

Thanks for all the hard work on this one @alygin, I know it's been a long road!

**Comment by alygin** [comment]
@mikayla-maki, since we're removing the `bottom` option, shouldn't we make this setting a simple boolean flag, like `show: true`?

**Comment by alygin** [comment]
> The only thing that took me a bit by surprise was that the tabs display in a project search.

@baldwindavid, fixed

**Comment by mikayla-maki** [comment]
> shouldn't we make this setting a simple boolean flag, like show: true 

Let's do that. Generally, I like to prefer enums to booleans. But also, the phrasing of `placement: none` is a little awkward. `show: true` tells the story well.

**Comment by iamnbutler** [comment]
Thanks – that settings change brings it more in line with other similar settings.

**Review by mikayla-maki — APPROVED** [review]

**Comment by mikayla-maki** [comment]
Thank you!

**Comment by hedefalk** [comment]
Yey! I've been waiting for this!

**Comment by Moshyfawn** [comment]
Closes #11727

**Comment by d1y** [comment]
A great option, closer to zen mode, but can you add a command?
Is it like `editor:: ToggleTabShow` ?
@alygin

**Comment by alygin** [comment]
> can you add a command? Is it like editor:: ToggleTabbarShow ?

@d1y, while adding such a command is technically a simple task, I'm not sure if it can be naturally embedded into the existing UX-patterns.

The state of toggable-by-action elements is stored in the local DB and it may conflict with what `settings.json` contains. For instance, I may have `tab_bar.show=true` in the `settings.json` and then hide it via the toggle-action. What should we do in this case on start? Or what if I have tab bar hidden via the toggle-action and via `tab_bar.show=false`, but then change settings to `tab_bar.show=true`? If we show the tab, it contradicts the toggle-state, if we don't, it confuses the user because the setting change has no effect. Etc.

Do you know other features in Zed that have both the setting in `settings.json` and a corresponding toggle-action?

**Comment by ConradIrwin** [comment]
Vim has both. The toggle command writes to the settings.

**Comment by alygin** [comment]
@ConradIrwin, will it be OK if Zed behaves the same way?

**Comment by baldwindavid** [comment]
@alygin Just in case it's not clear, the actual `workspace::ToggleVimMode` writes to the settings. As does `theme_selector::Toggle`, though with an additional step.
