### PR TITLE
vim: Make `cc` and `S` auto-indent

### LINKED ISSUE #9612: [vim] `cc` or `S` should auto indent
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In practice it is often necessary to insert content on a blank line, but if you use `i` it will be inserted at the beginning of the blank line.

https://github.com/zed-industries/zed/assets/19868292/b6cf58d9-a045-474c-9bad-140fb59eef16

### Environment

Zed: v0.128.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by Kalmaegi**
Fix #9612 

Release notes:

* Changed `cc` and `S` in Vim mode to only change the current line after its indentation. #9612

### CODE REVIEW

File: crates/vim/src/normal/change.rs [hunk 1]
```diff
@@ -53,7 +54,22 @@ pub fn change_motion(vim: &mut Vim, motion: Motion, times: Option<usize>, cx: &m
...
+            let mut edits = Vec::new();
+            for selection in &selections {
+                let mut insert = "".to_string();
+                let offset_range = selection
+                    .map(|p| p.to_offset(&display_map, Bias::Left))
+                    .range();
+
+                if motion == Motion::CurrentLine {
+                    let (indent, _) = display_map.line_indent(selection.start.row());
+                    insert.push_str(&" ".repeat(indent as usize));
```
Comment (mrnugget) [inline crates/vim/src/normal/change.rs:68]: I don't think we can do that, since the file might be use tabs for indentation.

Here's Neovim with a Go file, for example:

https://github.com/zed-industries/zed/assets/1185253/ee2b72af-e080-45ea-9ddd-0ca95e8c7f83


I wonder whether we shouldn't turn this around: instead of deleting and then inserting something, why not first find the first non-space character of the line and change from there to the end?

**Review by mrnugget — COMMENTED** [review]
Thanks for picking this up! Left some comments :)

File: crates/vim/src/normal/change.rs (hunk 1 above)
Comment (weartist) [reply crates/vim/src/normal/change.rs]: Thanks for the reminder! I came up with an easy way to do it with a shorter code

**Comment by mrnugget** [comment]
@weartist can you add `Release Notes` to your PR description?

**Comment by mrnugget** [comment]
I added release notes and tested locally. Thanks!

**Comment by weartist** [comment]
> I added release notes and tested locally. Thanks!

Thanks for your help! I don't have a lot of experience, but next time I'll know that I need to add notes
