### PR TITLE
terminal: Fix unresponsive buttons on load until center pane is clicked + Auto-focus docked terminal on load if no other item is focused

### LINKED ISSUE #23006: Pane buttons and title bar unresponsive until center pane is clicked
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've run into this a few times, mostly when opening a new window or reopening a project. The easiest way to reproduce it is to delete your `~/.local/share/zed` directory and open Zed. You'll see the Welcome Screen. If you try clicking on any elements outside the center pane without interacting with it first, they won't respond.

@SomeoneToIgnore I debugged the issue and found that this bug was introduced in [this](https://github.com/zed-industries/zed/pull/21668) PR, specifically when forcing focus on the new terminal. Removing it fixes the issue, but I’m unsure it might break `"prevent the workspace from getting odd pane events in the background"` thing you specified. I lack context on this, so I'm not confident about what the right solution is.  If you could clarify what it means, I can try to find an alternative solution that solves both the issues.

### Zed Version and System Specs

Zed: v0.169.0 (Zed Preview)
OS: Linux Wayland ubuntu 24.10
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-S) || Intel open-source Mesa driver || Mesa 24.2.3-1ubuntu1

### If applicable, add screenshots or screencasts of the incorrect state / behavior

[click-bug.webm](https://github.com/user-attachments/assets/1c136856-ed43-4e15-b4e7-958f3fd524fb)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #23006

This PR should have been split into two, but since the changes are related, I merged them into one.

1. On load, the title bar actions and bottom bar toggles are unresponsive until the center pane is clicked. This happens because the terminal captures focus (even if it's closed) long after the workspace sets focus to itself during loading.

The issue was in the `focus_view` call used in the `new` method of `TerminalPanel`. Since new terminal views can be created behind the scenes (i.e., without the terminal being visible to the user), we shouldn't handle focus for the terminal in this case. Removing `focus_view` from the `new` method has no impact on the existing terminal focusing logic. I've tested scenarios such as creating new terminals, splitting terminals, zooming, etc., and everything works as expected.

2. Currently, on load, docked terminals do not automatically focus when they are only visible item to the user. This PR implements it.

Before/After:

1. When only the dock terminal is visible on load. Terminal is focused.

image

image

2. When other items are visible along with the dock terminal on load. Editor is focused.

image

image

3. Multiple tabs along with split panes. Last terminal is focused.

image

image

Future:

When a docked terminal is in a zoomed state and Zed is loaded, we should prioritize focusing on the terminal over the active item (e.g., an editor) behind it. This hasn't been implemented in this PR because the zoomed state during the load function is stale. The correct state is received later via the workspace. I'm still investigating where exactly this should be handled, so this will be a separate PR.

cc: @SomeoneToIgnore 

Release Notes:

- Fixed unresponsive buttons on load until the center pane is clicked.  
- Added auto-focus for the docked terminal on load when no other item is focused.

### CODE REVIEW

**Comment by 0xtimsb** [comment]
Initially, I tried to check the dock's open state using `dock.panel::<T>().is_some() && dock.is_open()`, where `T` is `TerminalPane`, but that didn't work. So, I had to check it using the terminal's position: `dock.position() == position && dock.is_open()`.

**Comment by SomeoneToIgnore** [comment]
I also think that case #3 is not correct: we should focus last active item which is not necessary the last created item.
Seems though, it's not working correctly in `main` now, so not requiring it here, but welcome to implement it later.

File: crates/workspace/src/workspace.rs [hunk 1]
```diff
@@ -2302,6 +2302,20 @@ impl Workspace {
         }
     }
 
+    pub fn is_dock_at_position_open(
+        &self,
+        position: DockPosition,
+        cx: &mut ViewContext<Self>,
+    ) -> bool {
+        for dock in [&self.left_dock, &self.bottom_dock, &self.right_dock] {
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/workspace.rs:2310]: Why cannot we use `match position` same as in all other methods in `Workspace`?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thanks, based on https://github.com/zed-industries/zed/issues/23006#issuecomment-2585308263 it is indeed better to introduce conditional focusing instead of all this.

Doing it during `load` seems more logical too indeed, but we definitely should use https://github.com/zed-industries/zed/blob/88fad924ba259dd5a88b52d95afd66f02bc57467/crates/terminal_view/src/persistence.rs#L331 later to ensure we focus a proper terminal item.
That was not done in the original PRs so not asking to do now, but would be good.

**Comment by 0xtimsb** [comment]
Made a fix for focus last active item, now it correctly focuses it. 

There were two tiny bugs in `populate_pane_items`:
```rs
fn populate_pane_items(
    pane: &mut Pane,
    items: Vec<View<TerminalView>>,
    active_item: Option<u64>,
    cx: &mut ViewContext<Pane>,
) {
    let mut item_index = pane.items_len();
    for item in items {
        let activate_item = Some(item.item_id().as_u64()) == active_item;
        
        // 1. `add_item` internally calls `activate_item`, which negates our `activate_item` call
        pane.add_item(Box::new(item), false, false, None, cx);
        
        // 2. if panes already have `i` items, here index to activate should be `i` and not `i + 1`
        item_index += 1;
        if activate_item {
            pane.activate_item(item_index, false, false, cx);
        }
    }
}
```

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!
