### PR TITLE
OSC8-URIs support in terminal

### LINKED ISSUE #39339: Ctrl+Click on terminal `file://` hyperlink works randomly
### Summary

When navigating ripgrep results, Zed won't react to Ctrl+Click reliably.

### Description

Steps to reproduce:
1. Run `rg "--hyperlink-format=file://{path}:{line}:{column}" your_search_term` in Zed's terminal.
2. Ctrl+click on file numbers or file names hyperlinks.

**Expected Behavior**: Zed always navigates to the link.
**Actual Behavior**: Zed navigates to the link randomly.

<details><summary>Video</summary>

In this video I Ctrl+Click once each result hyperlink, in loop. You'll see that Zed opens the result randomly:

https://github.com/user-attachments/assets/0e686251-f762-4019-baa6-3fb4b35ed71c

</details>

@moduon MT-10900

### Zed Version and System Specs

Zed: v0.204.5 (Zed) 
OS: Linux Wayland nixos 25.05
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 25.0.7

### PR DESCRIPTION
**Pull request by yara-blue**
Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #39339 

Release Notes:

- Fixed hyperlinks in the terminal on UNIX

### CODE REVIEW

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 1]
```diff
@@ -47,10 +47,11 @@ impl RegexSearches {
             url_regex: RegexSearch::new(URL_REGEX).unwrap(),
             path_hyperlink_regexes: path_hyperlink_regexes
                 .into_iter()
+                .inspect(|r| log::info!("path regex: {}", r.as_ref()))
```
Comment (Veykril) [inline crates/terminal/src/terminal_hyperlinks.rs]:
```suggestion
```

File: crates/util/src/paths.rs
Comment (Veykril) [inline crates/util/src/paths.rs:1]: I don't know about these changes. These functions are not just used for the terminal after all, so handing OSC 8 here doesn't feel right? Might be better to duplicate for osc 8 functionality instead

File: crates/terminal/src/terminal_hyperlinks.rs (hunk 1 above)
Comment (yara-blue) [reply crates/terminal/src/terminal_hyperlinks.rs]: oops ty

File: crates/util/src/paths.rs
Comment (yara-blue) [reply crates/util/src/paths.rs:1]: ty you are right, makes no sense for "URLs" which is what this function is about.

I'll move it to terminal tomorrow and ping you :+1:

**Review by Veykril — APPROVED** [review]
