### PR TITLE
language_models: Honor images capability for custom OpenAI models

### LINKED ISSUE #50752: Cannot attach images to custom OpenAI models
### Reproduction steps

```
      "available_models": [
        {
          "name": "gpt-5.3-chat-latest",
          "display_name": "GPT-5.3 Chat",
          "max_tokens": 128000,
          "max_completion_tokens": 16384,
          "capabilities": {
            "chat_completions": true,
          },
        },
        {
          "name": "gpt-5.3-codex",
          "display_name": "gpt-5.3-codex (high)",
          "max_tokens": 400000,
          "max_completion_tokens": 128000,
          "reasoning_effort": "high",
          "capabilities": {
            "images": true,
            "chat_completions": false,
          },
        },
      ],
```

Using this in `language_models.openai`.

### Current vs. Expected behavior

With the configuration above, I am unable to attach images to the Agent, unless I switch to a natively added OpenAI models in Zed, attach it, and switch back.

### Zed version and system specs

Zed: v0.225.13+stable.193.fefa719272ae88d310bd645b67e8864789fb68ea (Zed) 
OS: Windows 10.0.26200
Memory: 79.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 5070 Ti || NVIDIA Corporation || 577.0 r576_76

### Attach Zed log file

_No response_

### Relevant Zed settings

_No response_

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Users who add custom OpenAI models under `language_models.openai.available_models` can set `capabilities.images: true` to declare that the endpoint accepts image inputs. Today, that setting is silently ignored: the Agent panel's image-attach button stays disabled regardless, and the only workaround is to switch to a built-in OpenAI model, attach the image, and switch back.

Root cause: `Model::Custom` does not carry a `supports_images` field, and the OpenAI provider's `supports_images()` for the `Custom` arm hardcodes `false`.

## Changes

1. `crates/settings_content/src/language_model.rs`: add `images: bool` to `OpenAiModelCapabilities` with `#[serde(default)]` so existing settings.json files keep working unchanged.
2. `crates/open_ai/src/open_ai.rs`: add `supports_images: bool` to `Model::Custom` with a matching serde default.
3. `crates/language_models/src/provider/open_ai.rs`: pass `model.capabilities.images` into the `Model::Custom` variant in `provided_models`, and return the stored value from `supports_images()` for `Custom`.

Existing `Model::Custom { .. }` match sites (`completion.rs:829`, various in `open_ai.rs`) all use `..` so they continue to compile without change.

## Testing

- `cargo check -p settings_content -p open_ai -p language_models`: clean.
- I was not able to complete `./script/clippy` locally: the build stalled on the first-time `webrtc-sys` download for livekit-rust-sdks (TLS close_notify failure on docs.rs mirror). Happy to rerun once CI has cached artifacts.
- Manually verified the capability plumbing by tracing: settings.json -> `OpenAiModelCapabilities.images` -> `Model::Custom { supports_images }` -> `supports_images()` -> `Thread::prompt_capabilities` -> `SessionCapabilities.supports_images()` -> `build_add_context_menu` gate in `thread_view.rs`.

## Related Issues

Closes #50752

Release Notes:

- Fixed custom OpenAI models ignoring the `capabilities.images` setting in `language_models.openai.available_models`.

This contribution was developed with AI assistance (Codex).

### CODE REVIEW

File: crates/open_ai/src/open_ai.rs [hunk 1]
```diff
@@ -106,6 +106,8 @@ pub enum Model {
         reasoning_effort: Option<ReasoningEffort>,
         #[serde(default = "default_supports_chat_completions")]
         supports_chat_completions: bool,
+        #[serde(default)]
```
Comment (bennetbo) [inline crates/open_ai/src/open_ai.rs]: Let's default to `true`, most models support images these days

File: crates/settings_content/src/language_model.rs [hunk 2]
```diff
@@ -257,12 +257,15 @@ pub struct OpenAiCompatibleSettingsContent {
...
     pub chat_completions: bool,
+    #[serde(default)]
+    pub images: bool,
 }
 
 impl Default for OpenAiModelCapabilities {
     fn default() -> Self {
         Self {
             chat_completions: default_true(),
+            images: false,
```
Comment (bennetbo) [inline crates/settings_content/src/language_model.rs]: Same here

File: crates/settings_content/src/language_model.rs [hunk 3]
```diff
@@ -257,12 +257,15 @@ pub struct OpenAiCompatibleSettingsContent {
 pub struct OpenAiModelCapabilities {
     #[serde(default = "default_true")]
     pub chat_completions: bool,
+    #[serde(default)]
```
Comment (bennetbo) [inline crates/settings_content/src/language_model.rs]: And here

**Review by bennetbo — CHANGES_REQUESTED** [review]

**Comment by bennetbo** [comment]
Looks good. Let's swap the default and we can merge

**Comment by mvanhorn** [comment]
Swapped the default in 5942c666f4, @bennetbo:

- `OpenAiModelCapabilities.images` now defaults to `true` via `#[serde(default = "default_true")]` and in the `Default` impl.
- `Model::Custom.supports_images` gets its own `default_supports_images()` helper returning `true`, matching the `default_supports_chat_completions` pattern already in `open_ai.rs`.

Existing settings.json files keep deserializing; the only behavior change is that an omitted `capabilities.images` resolves to `true` now. `cargo test -p open_ai -p settings_content` passes (14 + 2).

**Review by bennetbo — APPROVED** [review]

**Comment by bennetbo** [comment]
Thank you!

**Comment by mvanhorn** [comment]
Glad the images-capability honoring made it in, @bennetbo.
