### PR TITLE
editor: Fix inline Git blame not visible on long lines due to overflow

### LINKED ISSUE #18702: Git blame not visible if line too long compared to window
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the text cursor is in some line, text appears to the right of the line indicating the last git commit which wrote that line. However, if the line is close to or longer than the visible width of the buffer, that git blame text will appear beyond the visible area, without triggering the creation or expansion of a horizontal scrollbar. This makes it impossible to use that convenient git blame feature for lines that are too long.

<details><summary>Screenshot 1</summary>

Screenshot 2024-10-03 at 11 11 29 AM

</details>

<details><summary>Screenshot 2</summary>

Screenshot 2024-10-03 at 11 11 35 AM

</details>

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 13.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #18702

This is take 2 of [my previous PR](https://github.com/zed-industries/zed/pull/19555), which was closed due to inactivity and merge conflicts.  

**Cause**: 

The editor's horizontal scroll width only considers the longest line in the buffer, using `layout_line` for `longest_row`. The inline blame width isn’t included in it because it is just a decoration on top of the line (think of like CSS absolute) and not part of its actual content. This causes blame to overflow.

**Solution**:

Along with `longest_row` width we also add that line's inline blame width for scroll width calculation. We also have to add some padding that is between inline blame and line's content.

**Alternate Solution**:

In my previous PR, instead of adding the inline blame width of the longest line for scroll width calculation, I used the inline blame of the current line the cursor is on (since we only see the blame for the current line). I added that to the current line's width, giving us the full width of that row. Then, we compare that row's width with the longest row width and use the max of the two for the scroll width calculation.

While this solution seems clever, it's overly complicated and could cause issues, like the scroll width changing every time you move the cursor up or down. I don't think we should go with this, but I'm open to suggestions.

**Preview**:

Before:

https://github.com/user-attachments/assets/01ef90cf-06e7-4ebb-8bd1-637a53e0654e

After:

https://github.com/user-attachments/assets/b13616de-bdea-4da4-b32d-9c4104448166

Release Notes:

- Fixed inline Git blame not visible on long lines due to overflow.

### CODE REVIEW

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -6324,7 +6326,6 @@ impl Element for EditorElement {
                         cx,
                     );
 
-                    let mut max_visible_line_width = Pixels::ZERO;
```
Comment (0xtimsb) [inline crates/editor/src/element.rs:6327]: This variable was not being used anywhere, so removed it.

**Review by SomeoneToIgnore — APPROVED** [review]
Thanks!
