### PR TITLE
Fix/devcontainer compose labels

### LINKED ISSUE #53769: Failed to start Dev Container
### Reproduction steps

Open dev container with the following `devcontainer.json`

```json
{
  "name": "Asterinas",
  "image": "junyangzhang/asterinas:0.17.0-20260114-arm-preview",
  "mounts": ["source=/dev,target=/dev,type=bind"],
  "privileged": true,
  "runArgs": ["--network=host"],
  "workspaceFolder": "/root/asterinas",
  "workspaceMount": "source=${localWorkspaceFolder},target=/root/asterinas,type=bind",
}
```

### Current vs. Expected behavior

Container should be created successfully (it works in previous Zed)

### Zed version and system specs

OS: macOS 26
Zed: 0.231.2+stable.221.cc335b70f85a17974a4c61f852dbebff8c4b1db7

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2026-04-13T13:23:21+08:00 ERROR [dev_container::command_json] Error running command Command { program: "docker", args: ["inspect", "--format={{json . }}", "junyangzhang/asterinas:0.17.0-20260114-arm-preview"], envs: {}, env_clear: false, current_dir: None, stdin_cfg: Some(Null), stdout_cfg: Some(Piped), stderr_cfg: Some(Piped), kill_on_drop: false }: Error deserializing from raw json: missing field `devcontainer.metadata` at line 1 column 925
```

</details>

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by OmChillure**
Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [ ] Unsafe blocks (if any) have justifying comments
- [ ] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #53042
Closes #53482
Closes #53769

Release Notes:

- Fixed dev container failing to open when Docker Compose file contains `labels`

### CODE REVIEW

File: crates/dev_container/src/devcontainer_manifest.rs [hunk 1]
```diff
@@ -2292,23 +2292,21 @@ fn get_remote_user_from_config(
...
-    log::error!("Could not locate the remote user");
-    Err(DevContainerError::ContainerNotValid(
-        docker_config.id.clone(),
-    ))
+    if let Some(image_user) = &docker_config.config.image_user {
+        if !image_user.is_empty() {
+            return Ok(image_user.to_string());
+        }
+    }
+    Ok("root".to_string())
```
Comment (KyleBarton) [inline crates/dev_container/src/devcontainer_manifest.rs]: nice catch addressing this

**Review by KyleBarton — APPROVED** [review]

**Comment by OmChillure** [comment]
> Thanks for the fix! I went ahead and moved the data type for these labels to a Map. If we're going to have to coerce types one way or another, the map seems like a better representation

Yeah, Hashmap would be better
