### PR TITLE
languages: Improve completion sorting for Python-based LSPs

### LINKED ISSUE #47086: Python function autocomplete should prioritize function parameters
### Reproduction steps

1. Start Zed
2. Create a new Python file
3. Add code
```python
def say_hello(recipient: str) -> str:
    return f"Hello, {recipient}"
    

say_hello() # <-- press control-space inside parentheses
``` 
4. Observe when pressing control-space that the function parameter is not shown (see Current below)

### Current vs. Expected behavior

Current: 

Image

Expected:

Image

### Zed version and system specs

Zed: v0.219.4+stable.119.5595f7ce23d51a58eb66dd025a487bbd6c75dad1 (Zed) 
OS: Linux Wayland fedora 43
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 4600 (HSW GT2) || Intel open-source Mesa driver || Mesa 25.2.7

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by lingyaochu**
Closes #47086

This PR detects completion items ending with `=` (which typically represent keyword arguments in function calls provided by `Pyright`/`BasedPyright`/`pylsp`) and assigns them the highest sorting priority.

This ensures that when a user is filling out function arguments, the named parameters appear at the top of the list, rather than being buried mixed with other symbols.

After fix:
image

> **Note on Sorting:** Currently, these named arguments will be sorted alphabetically by label. Preserving the original order of the function definition would be ideal, but it requires information not currently available in this logical block. Insights on how to retrieve the definition order would be appreciated.

> **Note on other LSPs:** 
> * **`ty`**: Already provides well-sorted completions natively, so no intervention is required.

Release Notes:

- Improved completion order for Python-based LSPs

### CODE REVIEW

File: crates/languages/src/python.rs [hunk 1]
```diff
@@ -124,23 +126,36 @@ fn process_pyright_completions(items: &mut [lsp::CompletionItem]) {
...
+            Some(lsp::CompletionItemKind::FIELD) => '2',
+            Some(lsp::CompletionItemKind::PROPERTY) => '3',
+            Some(lsp::CompletionItemKind::VARIABLE) => '4',
+            Some(lsp::CompletionItemKind::CONSTANT) => '5',
+            Some(lsp::CompletionItemKind::METHOD) => '6',
+            Some(lsp::CompletionItemKind::FUNCTION) => '6',
+            Some(lsp::CompletionItemKind::CLASS) => '7',
+            Some(lsp::CompletionItemKind::MODULE) => '8',
+
+            Some(lsp::CompletionItemKind::TEXT) => 'z',
```
Comment (smitbarmase) [inline crates/languages/src/python.rs]: PR looks good. Can we remove this redudant arm? I think then it's good to go. This is much better than what we had previously.

**Review by smitbarmase — CHANGES_REQUESTED** [review]

File: crates/languages/src/python.rs (hunk 1 above)
Comment (lingyaochu) [reply crates/languages/src/python.rs]: Yea, the TEXT branch is removed now.

**Review by smitbarmase — APPROVED** [review]
Thanks!
