### PR TITLE
snippets: Fix snippets for PHP and ERB languages

### LINKED ISSUE #21541: PHP Snippets do not work
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Create a PHP snippets file (i.e. `~/.config/zed/snippets/php.json`) with any snippet. For example...

```javascript
{
  "Opening Tag": {
    "prefix": "php",
    "body": ["<?php", "$0"],
    "description": "PHP opening tag"
  },
  "This": {
      "prefix": "this",
      "body": ["\\$this->${1}"]
  },
}
```

> [!NOTE]
> These are simplified examples. I've tried many different snippets, none of which work.

Open a `.php` file, ensuring the detected language is `PHP`, and start typing the snippet prefix. Observe snippets do not work.

### Environment

```
Zed: v0.163.3 (Zed)
OS: Linux Wayland arch unknown
Memory: 27.2 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.2.7-arch1.1
```

### LINKED ISSUE #22726: ERB snippets are not working
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello,  

First of all, congratulations on the work already done on Zed; it's very pleasant to use.  

However, I have an issue with the snippets. They work for JavaScript but not for ERB files. Initially, I wrote my snippets based on Zed's documentation, but they didn't work. So, I simply copied and pasted my colleague's snippets, which work for him, but they still don't work for me.  

I tried restarting Zed after making my changes. I added the snippets under `ERB`, and my files are `*.html.erb`. I thought this might be the issue, but once again, my colleague doesn’t have this problem.  

I also compared my `settings.json` with his, and there’s nothing unusual.

Here are my snippets in `erb.json`:

```json
{
  "if": {
    "prefix": "if",
    "body": ["<% if ${1:truevalue} %>", "  $2", "<% end %>"],
    "description": "if .. end"
  },
  "else": {
    "prefix": "else",
    "body": ["<% else %>"],
    "description": "else"
  },
  "elsif": {
    "prefix": "elsif",
    "body": ["<% elsif ${1:truevalue} %>"],
    "description": "elsif"
  },
  "end": {
    "prefix": "end",
    "body": ["<% end %>"],
    "description": "end"
  },
  "ife": {
    "prefix": "ife",
    "body": [
      "<% if ${1:truevalue} %>",
      "  $2",
      "<% else %>",
      "  $3",
      "<% end %>"
    ],
    "description": "if .. else .. end"
  },
  "unless": {
    "prefix": "unless",
    "body": ["<% unless ${1:falsevalue} %>", "  $2", "<% end %>"],
    "description": "unless .. end"
  },
  "unlesse": {
    "prefix": "unlesse",
    "body": [
      "<% unless ${1:falsevalue} %>",
      "  $2",
      "<% else %>",
      "  $3",
      "<% end %>"
    ],
    "description": "unless .. end"
  },
  "each": {
    "prefix": "each",
    "body": ["<% ${1:items}.each do |${2:item}| %>", "  $3", "<% end %>"],
    "description": "each do"
  },
  "render": {
    "prefix": ["pe", "="],
    "body": ["<%= $1 %>"],
    "description": "render block pe"
  },
  "exec": {
    "prefix": ["er", "%"],
    "body": ["<% $1 %>"],
    "description": "erb exec block"
  },
  "form_with": {
    "prefix": "form_with",
    "body": ["<%= form_with model: ${1:@model} do |f| %>", "  $2", "<% end %>"],
    "description": "form_with"
  }
}

```

And this is my `settings.json`:

```json
{
  "assistant": {
    "default_model": {
      "provider": "copilot_chat",
      "model": "gpt-4o"
    },
    "version": "2"
  },
  "base_keymap": "VSCode",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark"
  },
  "languages": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "rubocop", "!solargraph", "..."]
    }
  },
  "autosave": "on_focus_change",
  "autoscroll_on_clicks": true,
  "tab_size": 2,
  "show_wrap_guides": true,
  "wrap_guides": [120]
}
```

Do I miss something?

### Zed Version and System Specs

Zed: v0.167.1 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

https://github.com/user-attachments/assets/c981a13b-2a05-485f-85e1-067731855083

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by claytonrcarter**
Closes #21541
Closes #22726

This should fix snippets in languages, like PHP, that are based on the HTML syntax layer. To be honest, I don't totally get where HTML comes into it, but the issues outlined in #21541 and #22726 both boil down to "Zed only shows me HTML snippets in PHP/ERB files; I expected to see PHP/ERB snippets". This solution is based on the comments between @mrnugget and @osiewicz in #22726: resolve/combine snippets for all language layers at the given position, whereas current behavior is to resolve snippets only for the `.last()` language layer at the given position.

- add `Buffer:languages_at()` (note the plural)
- update `snippet_completions()` in `editor.rs` to loop over each language, gathering snippets as it goes
- the primary logic for resolving snippets within a single language has not changed

### Verifying this change

I couldn't find tests related to snippet and currently active languages (CI may show them to me 😆 ) but I can add some if desired and w/ perhaps a little coaching or prompting about another test to look to for inspiration. I have confirmed that this works for PHP, but I have not checked ERB because I'm not familiar with it or set up for it.

To check this manually:
1. install the PHP extension
2. install at least 1 snippet for each of html, php and phpdoc. If you don't have any, these should work:
```sh
# BEWARE these will clobber existing snippets!
echo '{"dddd":{"body":"hello from phpdoc"}}' > ~/.config/zed/snippets/phpdoc.json
echo '{"pppp":{"body":"hello from PHP"}}' > ~/.config/zed/snippets/php.json
echo '{"hhhh":{"body":"hello from HTML"}}' > ~/.config/zed/snippets/html.json
```
3. open any PHP file. If you don't have one, here's one that should work:
```php
<?php

/**
 *
 */
function function_name()
{
}
```
4. Place your cursor in a PHPdoc comment (eg after the `/**` on line 3)
  - you should be able to use the `dddd`, `pppp` and `hhhh` snippets; on `main`, only the `dddd` snippet works here
5. Move your cursor to a non-comment PHP area (eg after the `{` on line 7)
  - you should be able to use the `pppp` and `hhhh` snippets, but not `dddd`; on `main`, only `hhhh` works here

### Performance

This adds 2 separate (not nested) loops to `snippet_completions()`, each of which will iterate over the active language scopes at the given location. I have not looked into the specifics of how many layers most languages have, but I suspect that *most* users will see identical performance as before because there will only be 1 scope active most of the time.

In some cases, though (eg PHP, ERB, maybe template strings in JS), the editor will be looping over more layers, possibly many in some deeply injected/embedded cases (I'm thinking of a regex template string in a JS heredoc string in a PHP script in an HTML file). I don't expect this to be an issue – nor has it been in my usage and testing – but performance of snippets could be affected in pathological cases.

### Alternate solutions

Instead of resolving snippets for *all* layers, we could just change how we pick which language to resolve. Instead of always using `.last()`, perhaps we could do something more clever. This feels like it could be tricky and potentially error prone, though.

Release Notes:

- Snippets are now resolved for all languages active at the cursor location.
- Fixed snippets in PHP, ERB and other languages whose syntax layers are based on HTML

### CODE REVIEW

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -18148,141 +18148,156 @@ fn snippet_completions(
...
 
     cx.background_spawn(async move {
-        let classifier = CharClassifier::new(scope).for_completion(true);
-        let mut last_word = chars
-            .chars()
-            .take_while(|c| classifier.is_word(*c))
-            .collect::<String>();
-        last_word = last_word.chars().rev().collect();
+        let mut all_results: Vec<Completion> = Vec::new();
+        for (scope, snippets) in scopes.into_iter() {
```
Comment (claytonrcarter) [inline crates/editor/src/editor.rs:18180]: The code w/in this for loop should be an "indent only" change, except for 2 lines:
- changed `let result` to `let mut result`
- added last line `all_results.append(&mut result);`

File: crates/editor/src/editor.rs [hunk 2]
```diff
@@ -18148,141 +18148,156 @@ fn snippet_completions(
...
-                        .map(|description| CompletionDocumentation::SingleLine(description.into())),
-                    confirm: None,
+                        confirm: None,
+                    })
                 })
-            })
-            .collect();
+                .collect();
+
+            all_results.append(&mut result);
```
Comment (claytonrcarter) [inline crates/editor/src/editor.rs:18297]: This implementation builds a Vec of snippets and then immediately drains it back into `all_results`. This minimized code changes, but I could also do something like *not* collecting the initial Vec and instead pushing into `all_results` in a `for_each()

**Review by osiewicz — APPROVED** [review]
LGTM, thank you!
