### PR TITLE
Fix bugs around pinned tabs

### LINKED ISSUE #31870: Pinned tabs are closed out when exceeding `max_tabs` count
> May or may not be the most appropriate place to provide some similar feedback, but if a tab is pinned and opening new files would cause you to go over your specified `max_tabs`, the pinned tab will potentially be closed. 

 _Originally posted by @zzzint in [#27904](https://github.com/zed-industries/zed/issues/27904#issuecomment-2831290603)_

### PR DESCRIPTION
**Pull request by JosephTLyons**
Closes https://github.com/zed-industries/zed/issues/31870

Release Notes:

- Allowed opening 1 more item if `n` tabs are pinned, where `n` equals `max_tabs` count.
- Fixed a bug where pinned tabs would eventually be closed out when exceeding the `max_tabs` count.
- Fixed a bug where a tab could be lost when pinning a tab while at the `max_tabs` count.
- Fixed a bug where pinning a tab when already at the `max_tabs` limit could cause other tabs to be incorrectly closed.

### CODE REVIEW

File: crates/workspace/src/pane.rs [hunk 1]
```diff
@@ -2053,13 +2063,15 @@ impl Pane {
...
             }
 
-            self.workspace
-                .update(cx, |_, cx| {
-                    cx.defer_in(window, move |_, window, cx| {
-                        move_item(&pane, &pane, id, destination_index, window, cx)
-                    });
-                })
-                .ok()?;
+            if ix != destination_index {
```
Comment (JosephTLyons) [inline crates/workspace/src/pane.rs:2066]: Don't go through with a move if the destination is the same as its origin location.
