### PR TITLE
Properly calculate expanded git diff hunk highlight ranges

### LINKED ISSUE #11576: Expanded diff hunks cover an extra line
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Git diff indicators next to the line numbers show which lines have been changed as expected, but when expanding the hunk to view the diff the add portions claim the next line even though it's unchanged.

### Environment

Zed: v0.135.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: x86_64

### Closed diff hunks showing the changed lines
Screenshot 2024-05-08 at 21 26 07

### Open diff hunks claiming the extra lines
Screenshot 2024-05-08 at 21 26 28

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes https://github.com/zed-industries/zed/issues/11576

Release Notes:

- Fixed expanded diff hunks highlighting an extra row as added ([11576](https://github.com/zed-industries/zed/issues/11576))

### CODE REVIEW

File: crates/editor/src/hunk_diff.rs [hunk 1]
```diff
@@ -256,21 +263,24 @@ impl Editor {
...
-                    hunk_start..hunk_end,
+                    to_inclusive_row_range(hunk_start..hunk_end, &snapshot),
                     Some(added_hunk_color(cx)),
                     cx,
                 );
                 self.insert_deleted_text_block(diff_base_buffer, deleted_text_lines, &hunk, cx)
             }
         };
+        if hunk_start.cmp(&hunk_end, &multi_buffer_snapshot).is_gt() {
+            eprintln!("@######################!!!!!!!!!!!!!");
```
Comment (osiewicz) [inline crates/editor/src/hunk_diff.rs:282]: What's up?
