### PR TITLE
agent_ui: Clear model selector query on dismiss

### LINKED ISSUE #36756: AI: Model search field not cleared; causes tripping
### Summary

I consider this a bug because it breaks the expected behavior.

When model selection is opened, whether in agentic or assistant mode, any previously entered text is still there. That means every time I open the field and start typing, it is likely to have debris in the field... so the second search almost always fails. Flow is broken. And this is tricky because I have `>10` instances open and cannot remember in real-time which one I used to change the model for all the others, so it is like a multi-dimensional memory game.

1. Enter text, such as `oss` to try to grab a class of model profiles
2. Pick one and forget you had stopped work to tie your shoes
3. Want to use a different model / profile and open the selector again
4. Start typing `coder`, thinking the field is clear to pick a different class
5. Hit head on door frame; get an error, you just searched for `osscoder` 

It needs to clear the search field whenever a model is actually selected, or even when the selector is closed.

Breaks zedi flow because you cannot switch from light saber to blaster at high speed while under attack.

Has always been a problem: but I only use `Ollama` models so I can only speak to that.

I am using `0.11.5` but that is irrelevant.

### Zed Version and System Specs

Zed: v0.199.9 (Zed) 
OS: Linux X11 linuxmint 22
Memory: 58.6 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV PHOENIX) || radv || Mesa 25.0.7-0ubuntu0.24.04.1

### PR DESCRIPTION
**Pull request by imumesh18**
Closes #36756

| Before | After |
|--------|--------|
| <video src ="https://github.com/user-attachments/assets/1d022ac6-0aea-4e98-a717-9988420c9683"/> | <video src="https://github.com/user-attachments/assets/78d19012-1224-4c92-a6c8-47ae4c13ca31"/> | 

Release Notes:

- Clear model selector query on dismiss in agent panel

### CODE REVIEW

File: crates/agent_ui/src/acp/model_selector.rs [hunk 1]
```diff
@@ -192,8 +192,16 @@ impl PickerDelegate for AcpModelPickerDelegate {
...
+    fn dismissed(&mut self, window: &mut Window, cx: &mut Context<Picker<Self>>) {
         cx.emit(DismissEvent);
+        cx.spawn_in(window, async move |handle, cx| {
+            handle
+                .update_in(cx, |picker, window, cx| {
+                    picker.set_query("", window, cx);
+                })
+                .ok();
+        })
+        .detach();
```
Comment (benbrandt) [inline crates/agent_ui/src/acp/model_selector.rs]: Should we also be doing this in the `confirm` method above?

Also, can we do something a little lighter weight here? since we don't need the async


```suggestion
        cx.defer_in(window, |picker, window, cx| {
            picker.set_query("", window, cx);
        });
```

**Review by benbrandt — CHANGES_REQUESTED** [review]

File: crates/agent_ui/src/acp/model_selector.rs (hunk 1 above)
Comment (imumesh18) [reply crates/agent_ui/src/acp/model_selector.rs]: Nice, this code for cleaning up make more sense. TIL didn't know defer_in existed.

For adding this in confirmed: Actually we are raising DismissEvent from it which in turns calls dismissed method.

```
confirmed sends `DismissEvent` → triggers dismissal → triggers `menu::Cancel` action → calls `cancel()` → calls `dismissed()` → clears query.
```

I also one more thing I realised during my testing was that we don't need to raise emit DismissEvent from dismissed it wouldn't do anything as the picker was already dismissed. So I have removed that as well.

ref:

```
pub fn cancel(&mut self, _: &menu::Cancel, window: &mut Window, cx: &mut Context<Self>) {
    if self.delegate.should_dismiss() {
        self.delegate.dismissed(window, cx);  
        cx.emit(DismissEvent);                
    }
}

```

**Review by benbrandt — APPROVED** [review]
Awesome thanks for digging in! Nice and clean

**Comment by digitalextremist** [comment]
SO GRATEFUL @imumesh18 ... woooohoooooooo. 

Excited to see this released and will thank you every time I select a model
