### PR TITLE
gpui: Remove blade, reimplement linux renderer with wgpu

### LINKED ISSUE #2335: Zed Editor is broken in Niri
This may not be a niri bug specifically, but the zed editor is broken in niri.  The reason is that when the application starts up, something invalidates the vulkan surface, and you have to resize the window to get it to work again.

Maybe there is something with the way that niri starts up windows that it's skipping a resize check or something.

### System Information

* niri version: niri 25.08 (01be0e6)

* Distro: Arch

* GPU: Nvidia 3090

* CPU: AMD Ryzen 9 3900XT

### PR DESCRIPTION
**Pull request by zortax**
The blade graphics library is a mess and causes several issues for both Zed users as well as other 3rd party apps using GPUI. This PR removes blade and implements the linux platform using `wgpu` which is the de-facto standard in the rust UI and graphics ecosystem. This will not just fix [issues that Zed users have today](https://github.com/YaLTeR/niri/issues/2335), but also profit from wgpu improvements in the futures, from other projects contributing (such as the bevy game engine, Iced, or pretty much every other relevant project).

This will close several related issues on the zed repo as well. See https://github.com/zed-industries/zed/issues?q=frozen%20nvidia%20linux (probably not all of them, have only tested the freeze on nvidia and Smithay-based wayland compositors).

Some related issues:
https://github.com/zed-industries/zed/issues/44814
https://github.com/zed-industries/zed/issues/40481
https://github.com/YaLTeR/niri/issues/2335
https://github.com/zortax/zlaunch/issues/15

Would appreciate feedback if this is something the zed maintainers would be interested in.

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 1]
```diff
@@ -0,0 +1,1277 @@
...
+
+        let surface_caps = surface.get_capabilities(&context.adapter);
+        // Prefer non-sRGB format to avoid sRGB blending issues
+        // The shader outputs linear values which will be displayed directly
+        let surface_format = surface_caps
+            .formats
+            .iter()
+            .find(|f| !f.is_srgb())
+            .copied()
+            .unwrap_or(surface_caps.formats[0]);
```
Comment (reflectronic) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: Not convinced this is right--I think this should error out instead of picking a format we don't want

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 2]
```diff
@@ -0,0 +1,1277 @@
...
+                .map_err(|e| anyhow::anyhow!("Failed to create surface: {e}"))?
+        };
+
+        let surface_caps = surface.get_capabilities(&context.adapter);
+        // Prefer non-sRGB format to avoid sRGB blending issues
+        // The shader outputs linear values which will be displayed directly
+        let surface_format = surface_caps
+            .formats
+            .iter()
+            .find(|f| !f.is_srgb())
```
Comment (andre-eriksson) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: On my AMD 6800 XT this surface format selection can pick a 16-bit normalized format:
```
surface formats: [Bgra8UnormSrgb, Rgba8UnormSrgb, Rgba16Unorm, Rgb10a2Unorm, Bgra8Unorm, Rgba8Unorm, Rgba16Float]
chosen surface_format: Rgba16Unorm
```
Which causes:
```
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline, label = 'quads'
    Features Features { features_wgpu: FeaturesWGPU(TEXTURE_FORMAT_16BIT_NORM), features_webgpu: FeaturesWebGPU(0x0) } are required but not enabled on the device
```

`Rgba16Unorm` requires `Features::TEXTURE_FORMAT_16BIT_NORM`, but the device is requested without enabling that feature: https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.TEXTURE_FORMAT_16BIT_NORM

Maybe we could prefer `Bgra8Unorm` / `Rgba8Unorm` or conditionally allow `Rgba16Unorm` based on the enabled device features?

Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I tried enabling the feature and conditionally allowing `Rgba16Unorm` if supported. Seems to work on my end, but I only have a nvidia system at hand right now, so I think it currently selects Bgra8Unorm anyway.

**Comment by reflectronic** [comment]
Thank you for the pull request. Yes, we are interested in this approach. From a brief look at the patch, things look good at a high level. I will make time for a deeper review soon.

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs (hunk 2 above)
Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: On a second thought, maybe it would be better to just always use `Bgra8Unorm` / `Rgba8Unorm`...

File: crates/gpui/src/platform/mac.rs [hunk 3]
```diff
@@ -10,18 +10,12 @@ mod pasteboard;
...
 mod metal_atlas;
-#[cfg(not(feature = "macos-blade"))]
 pub mod metal_renderer;
 
 use core_video::image_buffer::CVImageBuffer;
-#[cfg(not(feature = "macos-blade"))]
 use metal_renderer as renderer;
 
-#[cfg(feature = "macos-blade")]
-use crate::platform::blade as renderer;
```
Comment (maddythewisp) [inline crates/gpui/src/platform/mac.rs:23]: Since WGPU is a cross-platform API, I think it would be nice to be able to use it on Mac and Windows builds via a feature flag, similar to how `macos-blade` previously enabled the Blade renderer on Mac.

Comment (zortax) [reply crates/gpui/src/platform/mac.rs:23]: Agreed, but I can't test that, don't have the necessary hardware

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs (hunk 2 above)
Comment (andre-eriksson) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: You can do something like, to avoid `TextureFormat::Rgba16Unorm` it if it isn't enabled:
```rust
let can_16bit_norm = context
            .adapter
            .features()
            .contains(wgpu::Features::TEXTURE_FORMAT_16BIT_NORM);

let surface_caps = surface.get_capabilities(&context.adapter);

let surface_format = surface_caps
            .formats
            .iter()
            .find(|f| !f.is_srgb() && (!can_16bit_norm || **f != wgpu::TextureFormat::Rgba16Unorm))
            .copied()
            .unwrap_or(surface_caps.formats[0]);
```

Output (no validation errors):
```
surface formats: [Bgra8UnormSrgb, Rgba8UnormSrgb, Rgba16Unorm, Rgb10a2Unorm, Bgra8Unorm, Rgba8Unorm, Rgba16Float]
chosen surface_format: Rgb10a2Unorm
```

---

> On a second thought, maybe it would be better to just always use  Bgra8Unorm / Rgba8Unorm

Perhaps, but maybe we should prefer them rather than only using them. I am no expert in wgpu/webgpu or shaders so my input is limited here.

Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I pretty much tried that, but apparently it still panics on AMD: https://github.com/zortax/zlaunch/issues/15#issuecomment-3750880015
I can't really debug that since it doesn't happen on my system.. :/

Comment (andre-eriksson) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I tested the commit [81794ad](https://github.com/zed-industries/zed/pull/46758/commits/81794adeed8fb8938e852991963699c519b0acdf) and it resulted in the same errors as that comment however, adding the `can_16bit_norm` check does make it work for my AMD system on Wayland, since the linked commit [81794ad](https://github.com/zed-industries/zed/pull/46758/commits/81794adeed8fb8938e852991963699c519b0acdf) didn't change what `surface_format` was being selected.

Comment (reflectronic) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I agree that we should avoid the high-precision formats. We are not interested in WCG right now, so these formats will just consume more memory for no benefit.

Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I think you logic is wrong way around, isn't it?
```rs
(!can_16bit_norm || **f != wgpu::TextureFormat::Rgba16Unorm)
```
shouldn't this be
```rs
(can_16bit_norm || **f != wgpu::TextureFormat::Rgba16Unorm)
```
(this is exactly what I pushed in [81794ad](https://github.com/zed-industries/zed/pull/46758/commits/81794adeed8fb8938e852991963699c519b0acdf))

I think with your version it will filter out the 16bit format even though the adapter reports the feature. I thought the point of this is to allow the 16bit format if that feature is available?

Comment (andre-eriksson) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: I think you are right, good catch!

Also the features check is wrong therefore my tests were wrong, correction below:
```rust
let can_16bit_norm = context
            .device // Using device rather than adapter
            .features()
            .contains(wgpu::Features::TEXTURE_FORMAT_16BIT_NORM);
            
let surface_format = surface_caps
            .formats
            .iter()
            .find(|f| !f.is_srgb() && (can_16bit_norm || **f != wgpu::TextureFormat::Rgba16Unorm))
            .copied()
            .unwrap_or(surface_caps.formats[0]);
```

Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: Ah `device` makes sense, thank you. But I guess we'll just prefer 8bit anyway now.

File: crates/gpui/src/platform/wgpu/wgpu_context.rs [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+        if let Some(device_id) = device_id_filter {
+            for adapter in &adapters {
+                let info = adapter.get_info();
+                if info.device == device_id {
+                    log::info!(
+                        "Found GPU matching ZED_DEVICE_ID={:#06x}: {}",
+                        device_id,
+                        info.name
+                    );
+                    return instance
```
Comment (camspiers) [inline crates/gpui/src/platform/wgpu/wgpu_context.rs]: I'm not super familiar with wgpu, but I would have thought that (assuming an adapter for the device exists) this wouldn't guarantee the return of an adapter for the device id specified because the device specified might actually be a different power type to what the request options specified, or the user has more than one discrete/high performance GPU installed.

For example the user specifies a device id in their env that is for an integrated gpu while having a discrete gpu installed (meaning that when we subsequently call `.request_adapter` with `HighPerformance` it's going to select an adapter for the discrete GPU).

Comment (andre-eriksson) [reply crates/gpui/src/platform/wgpu/wgpu_context.rs]: Good point, it could return `Ok(adapter.clone())` instead of `.request_adapter(...)`.

Comment (camspiers) [reply crates/gpui/src/platform/wgpu/wgpu_context.rs]: I managed to get a repo of what I mean. In the following `0x164e` is my integrated GPU on my CPU (AMD 7950x3d), it finds it but ends up selecting the 4080 (discrete GPU).

```bash
~/d/zed (wgpu)> ZED_DEVICE_ID=0x164e cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/zed`
2026-01-15T17:35:26+13:00 INFO  [zed] ========== starting zed version 0.220.0+dev.324945dea43acd3fda7e8ba1f0a7e1f091f658a0, sha 324945d ==========
2026-01-15T17:35:26+13:00 INFO  [gpui::platform::wgpu::wgpu_context] Found GPU matching ZED_DEVICE_ID=0x164e: AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)
2026-01-15T17:35:26+13:00 INFO  [gpui::platform::wgpu::wgpu_context] Selected GPU adapter: "NVIDIA GeForce RTX 4080" (Vulkan)
```

Comment (camspiers) [reply crates/gpui/src/platform/wgpu/wgpu_context.rs]:
```rust
    async fn select_adapter(
        instance: &wgpu::Instance,
        device_id_filter: Option<u32>,
    ) -> anyhow::Result<wgpu::Adapter> {
        if let Some(device_id) = device_id_filter {
            let adapters: Vec<_> = instance.enumerate_adapters(wgpu::Backends::all()).await;

            if adapters.is_empty() {
                anyhow::bail!("No GPU adapters found");
            }

            let mut non_matching_adapter_infos: Vec<wgpu::AdapterInfo> = Vec::new();

            for adapter in adapters.into_iter() {
                let info = adapter.get_info();
                if info.device == device_id {
                    log::info!(
                        "Found GPU matching ZED_DEVICE_ID={:#06x}: {}",
                        device_id,
                        info.name
                    );
                    return Ok(adapter);
                } else {
                    non_matching_adapter_infos.push(info);
                }
            }

            log::warn!(
                "No GPU found matching ZED_DEVICE_ID={:#06x}. Available devices:",
                device_id
            );

            for info in &non_matching_adapter_infos {
                log::warn!(
                    "  - {} (device_id={:#06x}, backend={})",
                    info.name,
                    info.device,
                    info.backend
                );
            }
        }

        instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                compatible_surface: None,
                force_fallback_adapter: false,
            })
            .await
            .map_err(|e| anyhow::anyhow!("Failed to request GPU adapter: {e}"))
    }
```

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 5]
```diff
@@ -0,0 +1,1282 @@
...
+
+        let target = wgpu::SurfaceTargetUnsafe::RawHandle {
+            raw_display_handle: display_handle.as_raw(),
+            raw_window_handle: window_handle.as_raw(),
+        };
+
+        // Safety: The caller guarantees that the window handle is valid for the
+        // lifetime of this renderer. In practice, the RawWindow struct is created
+        // from the native window handles and the surface is dropped before the window.
+        let surface = unsafe {
```
Comment (camspiers) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs:146]: Is it worth using `SurfaceTargetUnsafe::from_window`?

```rust
        let surface = unsafe {
            context
                .instance
                .create_surface_unsafe(
                    wgpu::SurfaceTargetUnsafe::from_window(window)
                        .map_err(|e| anyhow::anyhow!("Failed to create surface target: {e}"))?,
                )
                .map_err(|e| anyhow::anyhow!("Failed to create surface: {e}"))?
        };
```

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 6]
```diff
@@ -0,0 +1,1282 @@
...
+    }
+
+    pub fn gpu_specs(&self) -> GpuSpecs {
+        GpuSpecs {
+            is_software_emulated: false,
+            device_name: "wgpu".to_string(),
+            driver_name: "wgpu".to_string(),
+            driver_info: "wgpu renderer".to_string(),
+        }
+    }
```
Comment (probably-neb) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs:823]: Low priority issue, but it would be great if we could wire `wgpu::Adapter` through to this point and have accurate info here. We use this as metadata in crash dumps, so important for fixing any future issues :)

File: crates/gpui/src/platform/wgpu/wgpu_context.rs (hunk 4 above)
Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_context.rs]: yeah that didn't make a lot of sense, don't know what I thought when writing this here

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs (hunk 6 above)
Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs:823]: fair enough, skipped that in the beginning to get stuff working, kinda forgot about it

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs (hunk 5 above)
Comment (zortax) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs:146]: To be honest I think this is "unnecessary complexity", since, as far as I understand, in the current implementation we would still wrap the underlying error. The only difference with this is the separate wrapper message, but the underlying error should make it very clear which error path was hit anyway, but please correct me if I'm wrong.

Comment (camspiers) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs:146]: We wouldn't gain much by using their function over manually doing it ourselves, and it's a fair argument that the error messages in the more manual case are less layered. It's probably not important in practice to see directly in the error that we failed to get a window or display handle while creating a surface target, because you are going to see that context by virtue of where the error occurs (in the creation of the renderer).

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs (hunk 6 above)
Comment (probably-neb) [reply crates/gpui/src/platform/wgpu/wgpu_renderer.rs:823]: No worries!

**Comment by zortax** [comment]
I believe this PR closes the following issues:
https://github.com/zed-industries/zed/issues/39097
https://github.com/zed-industries/zed/issues/44814
https://github.com/zed-industries/zed/issues/45836
https://github.com/zed-industries/zed/issues/40481
https://github.com/zed-industries/zed/issues/38497

There are some other issues this might close, but haven't tested/reproduced:
https://github.com/zed-industries/zed/issues/40361
https://github.com/zed-industries/zed/issues/44252

File: crates/gpui/src/platform/mac.rs (hunk 3 above)
Comment (pampas9000) [reply crates/gpui/src/platform/mac.rs:23]: > Since WGPU is a cross-platform API, I think it would be nice to be able to use it on Mac and Windows builds via a feature flag, similar to how `macos-blade` previously enabled the Blade renderer on Mac.

With Zed moving to wgpu (WebGPU), does this mean a web-based client is now technically possible, similar to Flutter Web?

Comment (maddythewisp) [reply crates/gpui/src/platform/mac.rs:23]: @bamboo512 There is significant work beyond the renderer that would need to happen to run Zed in a browser - notably background tasks and filesystem/input APIs would need web/wasm-compatible implementations.

**Comment by zeux** [comment]
This PR causes a significant regression in VRAM usage for me.

Here's `nvtop` comparing current production builds vs a local build off this branch; I verified that a local debug build off the commit on this branch before blade removal has the same VRAM requirement as the production build. The window sizes of two Zed instances are the same (2540x2076). This is running on a 4K screen (3840x2160), with DPI scaling 1.5x, using niri compositor on Ubuntu 25.10.

image

Here's `nvtop` with both windows maximized:

image

**Comment by zeux** [comment]
@zortax Re: 30 MB difference - you are looking at the wrong column in my screenshots; the rightmost column is "host memory" which I'm not interested in; the 6th column accounts for GPU memory allocation and that is where the difference is significant for me.

**Comment by zeux** [comment]
That seems to fix the problem for me; in fact, after this change, the VRAM consumption in this PR is better than it is in the production build. Here's a snapshot with both windows maximized:

image

**Comment by zortax** [comment]
@zeux yes that shows that in your specific case it doesn't make a difference, my point was more that it is bad practice to reason about memory or VRAM usage based on debug build data. There many possible scenarios that could lead to significant differences, even in VRAM usage, not just performance, even in the sense that release mode could make it worse. Now that I think about this, it may even be a problem in my implementation currently: I use Fifo mode (V-Sync locked in wgpu), but rely on present() for synchronization. I also create new buffers on every render (blade used a pool), so if the GPU falls behind, GPU buffers could potentially pile up. This would be worse in release mode, because in debug mode the CPU part of the pipeline could be significantly slower. 

So again, the point of my comments is only that it is bad practice to base arguments on debug builds (especially when comparing against release builds), especially if the underlying "issue" is not even reproducible for everyone involved.

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 7]
```diff
@@ -0,0 +1,1286 @@
...
+    pub fn gpu_specs(&self) -> GpuSpecs {
+        GpuSpecs {
+            is_software_emulated: self.adapter_info.device_type == wgpu::DeviceType::Cpu,
+            device_name: self.adapter_info.name.clone(),
+            driver_name: self.adapter_info.driver.clone(),
+            driver_info: self.adapter_info.driver_info.clone(),
+        }
+    }
+
+    fn create_storage_buffer(&self, data: &[u8]) -> wgpu::Buffer {
```
Comment (jlucaso1) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: this allocates a new GPU buffer for every single batch every frame - quads, shadows, sprites, underlines, etc. that's easily 10-20+ buffer allocations per frame, so at 60fps you're looking at ~1000 GPU allocs/sec.

the old blade renderer used `BufferBelt` from blade-util for exactly this reason, and the metal renderer on macOS uses a custom `InstanceBufferPool` (see `crates/gpui/src/platform/mac/metal_renderer.rs:56`). both pool and reuse buffers across frames

wgpu's `write_buffer` uses internal staging so it's safe to reuse a buffer from a previous frame even if the GPU hasn't finished reading it yet. a simple pool with two vecs (available + in_flight) swapped at the start of each frame would eliminate all these allocations after the first few frames stabilize

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 8]
```diff
@@ -0,0 +1,1286 @@
...
+        self.queue.write_buffer(&self.gamma_buffer, 0, bytemuck::bytes_of(&gamma_params));
+
+        let globals_bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
+            label: Some("globals_bind_group"),
+            layout: &self.bind_group_layouts.globals,
+            entries: &[wgpu::BindGroupEntry {
+                binding: 0,
+                resource: self.globals_buffer.as_entire_binding(),
+            }],
+        });
```
Comment (jlucaso1) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: `globals_bind_group` and `globals_with_gamma_bind_group` are recreated every frame but the underlying buffer handles never change (only the contents via `write_buffer`). bind groups reference buffer handles not their contents, so these can be created once in `new()` and stored as fields. small win but it's free

File: crates/gpui/src/platform/wgpu/wgpu_renderer.rs [hunk 9]
```diff
@@ -0,0 +1,1286 @@
...
+            premultiplied_alpha: 0,
+            pad: 0,
+        };
+        let globals_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
+            label: Some("path_globals"),
+            size: std::mem::size_of::<GlobalParams>() as u64,
+            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
+            mapped_at_creation: false,
+        });
+        self.queue.write_buffer(&globals_buffer, 0, bytemuck::bytes_of(&globals));
```
Comment (jlucaso1) [inline crates/gpui/src/platform/wgpu/wgpu_renderer.rs]: this creates a brand new uniform buffer + bind group every time paths are rendered, just to set `premultiplied_alpha: 0` instead of the main globals value. could just have a persistent `path_globals_buffer` field created once in `new()` and updated with `write_buffer` each frame, same as you do with `self.globals_buffer`. saves a buffer allocation + bind group creation per path batch

**Comment by gohryt** [comment]
No problem with your concrete implementation and yes it will be zed maintainers decision. I am just hinting that this medal has two sides and while wgpu is good for libraries and apps with many different target OSes and architectures it has twice dependencies which means slow compilation and twice rust-analyzer ram usage at dev time, it works worser for vram and perfomance in run time and sometimes it has long-time problems without fixes as for example you can check its github issues.

You personally like wgpu, i personally dislike it especially after development and usage of apps based on it. My point was that wgpu is not solution for everybody and looks like something that can be made selectable by cfg flags based on checking  this pr.

**Comment by zortax** [comment]
> it works worse for vram and perfomance

have you read the thread above? This statement is simply not true when comparing to blade. The implementation already has a lower VRAM and memory footprint than the blade implementation had, and that is before some performance improvements addressing the comments above. Performance will not change with this PR significantly either, the wgpu implementation does essentially the same thing as the blade implementation did. Feel free to run benchmarks on this...

>  slow compilation and twice rust-analyzer ram usage at dev time

Have you tried compiling the zed repo? Wgpu build times are not the issue or bottleneck here. On my system the difference was barely noticable, and since we have incremental builds for dependencies most of it will be one-time only anyway.

> sometimes it has long-time problems without fixes

Sure, wgpu has issues too. The difference is that it is actively maintained and a core dependency of many big projects. There is generally a big interest in getting significant things fixed. Blade on the other hand has open PRs (not even just issues) with small fixes that have a big impact (breaking issues) for downstream apps that haven't been merged in half a year. I don't want to attack the author, I know maintaining OSS is a lot of work and usually doesn't pay the bills, but zed and gpui are projects people rely on, so I don't think this is acceptable for a core dependency.

> You personally like wgpu, i personally dislike it especially after development and usage of apps based on it

I could also turn that argument around, but more importantly I think community support and stability are plainly more important that slight differences in API ergonomics.

> looks like something that can be made selectable by cfg flags based on checking this pr

Yes of course it could, but that has certain implications that should be considered. If you add it  as a new backend, it will also have to be maintained, so more work for further improvements. This is already a bit of an issue with GPUI given the different renderer implementation. I respect the decision of the zed maintainers to support those implementation, but personally I think we should thrive to consolidate the rendering infrastructure, not further fragment it. There are exciting things for the future that could be enabled (or significantly simplified for end-users) by consolidation, like APIs for custom shaders, direct buffer access for custom elements, embedding into other wgpu apps (or being embeddable by them), like bevy.

**Comment by reflectronic** [comment]
I've merged some optimizations and simplifications. In particular, we're reusing the same buffer object for every frame now.

**Comment by reflectronic** [comment]
> Maybe make this optional like gles instead of replacing blade?

The Blade backend is a lot of code that we (Zed) don't have a use for anymore; I don't think we're interested in maintaining it.

**Comment by reflectronic** [comment]
f988a34 (the latest commit) is still a memory usage improvement over Zed Stable (listed as `zed-editor`):

image

<br>

Additionally, f988a34 is a ~20% CPU time improvement over b64007c40ef1b93fc841f78fef6d1b6d6bb28a3d (before I started optimizing) with approximately the same GPU time: 

```
frames 1320-1439: CPU draw median=238.82µs, GPU median=12.303ms
frames 1440-1559: CPU draw median=229.59µs, GPU median=12.304ms
frames 1560-1679: CPU draw median=240.19µs, GPU median=12.272ms
frames 1680-1799: CPU draw median=236.18µs, GPU median=12.466ms
```
vs.

```
frames 5400-5519: CPU draw median=301.45µs, GPU median=12.328ms
frames 5520-5639: CPU draw median=305.02µs, GPU median=12.269ms
frames 5640-5759: CPU draw median=295.21µs, GPU median=12.022ms
frames 5760-5879: CPU draw median=291.69µs, GPU median=11.812ms
```

The GPU time seems rather high, but this doesn't seem like it was caused by the pull request. (I have not properly benchmarked Blade, but the FPS does not feel higher for me in Zed Stable).

**Review by reflectronic — APPROVED** [review]
I think we're good to go with this. Thank you for your work on this, @zortax.

**Comment by Akiyamka** [comment]
How to disable this? after update editor constantly freezes on Radeon 780M Graphic  (Framework Laptop)

**Comment by jlucaso1** [comment]
> How to disable this? after update editor constantly freezes on Radeon 780M Graphic (Framework Laptop)

Can you provide some debug logs? I've tested here in a rx 6600 and it's running fine. Also check if you are using the latest mesa version

File: crates/gpui/src/platform/mac.rs (hunk 3 above)
Comment (TimTheBig) [reply crates/gpui/src/platform/mac.rs:23]: True, I do think that [`WASI`](https://wasi.dev/) as a minimum feature-set would ease that work
