### PR TITLE
worktree: Create parent directories on rename

### LINKED ISSUE #37357: Cannot create a new directory as part of af file rename action
### Summary

Renaming file with a new directory to be created constantly fails

### Description

When i try to rename a file from e.g. `file.txt` to `dir/file.txt`, I get
```
2025-09-02T10:22:18+02:00 ERROR [workspace::notifications] Renaming "<workspace-path>/file.tx" into "<workspace-path>/dir/file.txt"

Caused by:
    No such file or directory (os error 2)
```

Steps to reproduce:
1. Create a new directory
2. Open the newly created directory in zed
3. Create a `file.txt` in the root of the directory using zeds project panel
4. Rename the file to `dir/file.txt` using zed's project panel

**Expected Behavior**: New directory `dir` created and `file.txt` moved into this directory
**Actual Behavior**: Error message. Nothing else happens.

### Zed Version and System Specs

Zed: v0.201.8 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by Zertsov**
Closes https://github.com/zed-industries/zed/issues/37357

Release Notes:

- Allow creating sub-directories when renaming a file in file finder

### CODE REVIEW

File: crates/worktree/src/worktree.rs [hunk 1]
```diff
@@ -1775,6 +1775,20 @@ impl LocalWorktree {
             };
             absolutize_path
         };
+
+        if !is_root_entry {
+            // If the parent directory doesn't exist, create it
+            if let Some(parent) = abs_new_path.parent() {
+                if !parent.exists() {
+                    if let Err(e) = std::fs::create_dir_all(parent).with_context(|| {
```
Comment (SomeoneToIgnore) [inline crates/worktree/src/worktree.rs]: Zed uses `fs` (used just below for FS operations, very odd that it was overlooked by this impl) to leverage non-blocking FS API instead of the blocking one from `std`.

So,

* both `exists` and `std::fs::create_dir_all` should not be used
* do we even need `exists` at all? does `fs.create_dir_all(path).await` fails if `path` exists already? 
We can detect that by the error type, if it's so, and ignore this particular error.

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
Great point about the tests in the [related discussion](https://github.com/zed-industries/zed/discussions/37435), let's add them too.

File: crates/worktree/src/worktree.rs (hunk 1 above)
Comment (Zertsov) [reply crates/worktree/src/worktree.rs]: I was initially trying to use the the non-std `fs` through `self.fs`, but it was really late and I was running into issues since the rename function isn't async. Totally skipped over the `fs` below and didn't grok at the time that y'all are using the context to deal with the async issues. I'll play around some more to see how to properly move this into the async fs - been a minute since I've written Rust.

Also, I just played around with the `exists` check, I initially didn't check to see if `create_dir_all` fails when a dir exists, and looks like it doesn't fail. I'll clean that up too

Comment (Zertsov) [reply crates/worktree/src/worktree.rs]: I was just thinking about this - do we want to eagerly create directories if something else fails below? I'd think no, so this implementation has that to deal with too.

Comment (SomeoneToIgnore) [reply crates/worktree/src/worktree.rs]: Well, yes, right before `fs.rename` call?

Comment (Zertsov) [reply crates/worktree/src/worktree.rs]: Yeah, before the `fs.rename` call. If, for whatever reason, that fails, we'd end up with directories while the rename op fails. I just did an implementation where we try the rename first, and if it fails due to the directories not existing then we do the directory creation and retry the rename one more time. I'll push it up now so you can see what I'm talking about. Tests should be there too - I _think_ the style is followed but let me know if you need / want more things changed there.

**Comment by Zertsov** [comment]
https://github.com/user-attachments/assets/1733c028-1c16-4d41-9452-8af9e309bdc9

Attached a screen recording showing rename working and creating dirs with latest commit

File: crates/worktree/src/worktree.rs (hunk 1 above)
Comment (Zertsov) [reply crates/worktree/src/worktree.rs]: I only know this is a case because it happened to me while I was testing stuff out 😔

File: crates/worktree/src/worktree.rs [hunk 2]
```diff
@@ -1791,16 +1802,32 @@ impl LocalWorktree {
...
+                            return fs.rename(&abs_old_path, &abs_new_path, fs::RenameOptions {
+                                overwrite,
+                                ..Default::default()
+                            }).await
+                            .with_context(|| format!("Renaming {abs_old_path:?} into {abs_new_path:?}"));
+                        }
+                    }
+                    Err(e)
+                }
+            }
```
Comment (Zertsov) [inline crates/worktree/src/worktree.rs]: I went with this since I figured that on average, creating directories with a rename happens infrequently, so might be a minor optimization, but through my testing this seems to work and tests are passing as well

File: crates/worktree/src/worktree.rs [hunk 3]
```diff
@@ -1818,6 +1845,11 @@ impl LocalWorktree {
                         );
                         Task::ready(Ok(this.root_entry().cloned()))
                     } else {
+                        // First refresh the parent directory (in case it was newly created)
+                        if let Some(parent) = new_path.parent() {
+                            let _ = local.refresh_entries_for_paths(vec![parent.into()]);
+                        }
+                        // Then refresh the new path
```
Comment (Zertsov) [inline crates/worktree/src/worktree.rs:1843]: This took me a while. The tests were failing if we didn't refresh the entries after a creation. To be honest, I'm not the biggest fan of this, but I haven't noticed any notable perf issues. Open to suggestions here - I might've just been writing my tests incorrectly.

Comment (SomeoneToIgnore) [reply crates/worktree/src/worktree.rs:1843]: Good find, I think this is ok to do, thank you.

**Review by SomeoneToIgnore — APPROVED** [review]
