### PR TITLE
diagnostics: Fix losing focus when activating from diagnostics view

### LINKED ISSUE #25509: If already in Diagnostics View, triggering `diagnostics: deploy` again loses focus
### Summary

Triggering `diagnostics: deploy` a second time removes your cursor (and focus from multibuffer).

Steps to trigger the problem:
1. Have Rust diagnostics.
2. Run `diagnostics: deploy` twice.

Actual Behavior:

Cursor disappears.

Expected Behavior:

Cursor stays where it was added when you first triggered.

### Zed Version and System Specs

Zed: v0.176.0 (Zed Nightly 918cba4cce84f9c76e8ebbc93e3f7392964f341a) 
OS: Linux X11 arch unknown
Memory: 60.3 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6750 XT (RADV NAVI22) || radv || Mesa 24.3.4-arch1.1

### PR DESCRIPTION
**Pull request by 5brian**
Closes #25509

Changes:
- If active item is already diagnostics, don't try to focus it again.

Instead of not focusing, should it just not activate instead? Something like:

            if !workspace
                .active_item(cx)
                .map(|item| item.item_id() == existing.item_id())
                .unwrap_or(false)
            {
                workspace.activate_item(&existing, true, true, window, cx);
            }

Release Notes:

- N/A

### CODE REVIEW

File: crates/diagnostics/src/diagnostics.rs [hunk 1]
```diff
@@ -280,7 +280,11 @@ impl ProjectDiagnosticsEditor {
         cx: &mut Context<Workspace>,
     ) {
         if let Some(existing) = workspace.item_of_type::<ProjectDiagnosticsEditor>(cx) {
-            workspace.activate_item(&existing, true, true, window, cx);
+            let is_active = workspace
+                .active_item(cx)
+                .map(|item| item.item_id() == existing.item_id())
+                .unwrap_or(false);
```
Comment (Anthony-Eid) [inline crates/diagnostics/src/diagnostics.rs:286]: This is a nit, but using `is_some_and()` would show your intent better here

```rust
let is_active = workspace
    .active_item(cx)
    .is_some_and(|item| item.item_id() == existing.item_id());
```

Comment (5brian) [reply crates/diagnostics/src/diagnostics.rs]: thank you

**Comment by Anthony-Eid** [comment]
Thank you
