### PR TITLE
vim: Fix change surround with any brackets text object

### LINKED ISSUE #24439: Vim: `csb` doesn't work with AnyBrackets
### Summary

With AnyBrackets mapped to `b`, `csb}` doesn't replace the surrounding brackets with `{}`. It appears to end the sequence after the `b`.

Steps to trigger the problem:
1. Using text with parentheses (or other brackets): `(bracketed)` and the cursor inside the parens.
2. Try `cib}` to change it to `{bracketed}`

Actual Behavior:
Brackets don't change. Your cursor moves to the end of the current paragraph, because the `}` is interpreted as a next action.

Image
`csb}`

Image

Expected Behavior:

The closest surrounding parens get replaced with `{}`:

Image

Keyboard context seems to imply that it should be anybrackets:
Image

Compare with the same `csb` without mapping anybrackets

Image

I've used the supplied keymapping from the PR:
```json
{
	"context": "vim_operator == a || vim_operator == i || vim_operator == cs",
	"bindings": {
		"b": "vim::AnyBrackets"
	}
}
```

### Zed Version and System Specs

Zed: v0.172.9 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by dinocosta**
This commit fixes an issue with how the `AnyBrackets` object was handled with change surrounds (`cs`). With the keymap below, if one was to use `csb{` with the text `(bracketed)` and the cursor inside the parentheses, the text would not change.

```json
{
  "context": "vim_operator == a || vim_operator == i || vim_operator == cs",
  "bindings": {
    "b": "vim::AnyBrackets"
  }
}
```

Unfortunately there was no implementation for finding a corresponding `BracketPair` for the `AnyBrackets` object, meaning that, when using `cs` (change surrounds) the code would simply do nothing.

This commit updates this logic so as to try and find the nearest surrounding bracket (parentheses, curly brackets, square brackets or angle brackets), ensuring that `cs` also works with `AnyBrackets`.

Closes #24439

Release Notes:

- Fixed handling of `AnyBrackets` in vim's change surrounds (`cs`)

### CODE REVIEW

File: crates/vim/src/surrounds.rs [hunk 1]
```diff
@@ -388,6 +388,140 @@ impl Vim {
...
+                                        })
+                                    }
+                                }
+                            }
+                        }
+                    }
+                });
+
+                bracket_pair
+            }
```
Comment (dinocosta) [inline crates/vim/src/surrounds.rs:521]: A lot of this code has been copied over from the `vim::object::Object.range` method, so I believe there's space to abstract this to a separate function that can be reused by both. Just want to confirm it's okay to have the `object_to_bracket_pair` method be moved from the `vim::surrounds` module into the `vim::surrounds::Vim` implementation first 🫡

**Review by dinocosta — COMMENTED** [review]
@ConradIrwin I also picked this one up, which relates to #24439 🧹 

I changed the visibility of one function, updated another to a method, and duplicated some code. I left a comment to see if you have a better recommendation for where these items should belong. I'll address it after your feedback. Thanks! 🙇

File: crates/vim/src/surrounds.rs (hunk 1 above)
Comment (ConradIrwin) [reply crates/vim/src/surrounds.rs:521]: totally fine, thanks!
