### PR TITLE
editor: Remove folded buffer ID on all excerpts removed

### LINKED ISSUE #50521: Project Search's expand/collapse button broken when searching after folding
### Reproduction steps

1. Start Zed
2. Perform a new project search
3. Collapse all excerpts on the top left button ("Collapse All Search Results")
4. Update the search query and press `enter` to perform a new search
5. Confirm that, even though all excerpts are expanded, the button still shows "Expand All Search Results" and pressing it does nothing

### Current vs. Expected behavior

Current Behavior: Expand/Collapse All button does not reset on a new project search
Expected Behavior: Expand/Collapse All button should reset when a new project search is performed

### Zed version and system specs

Zed: v0.227.0+nightly.2249.ac4b14370c0254a27962e787bfa5c4c69e0ba1f0 (Zed Nightly ac4b14370c0254a27962e787bfa5c4c69e0ba1f0) 
OS: macOS 26.3
Memory: 36 GiB
Architecture: aarch64

### Attach Zed log file

Not Applicable

### Relevant Zed settings

Not Applicable

### Relevant Keymap

Not Applicable

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by dinocosta**
Fix a bug in the editor's handling of the `multi_buffer::Event::ExcerptsRemoved` event, where the display map's `folded_buffers` set was not updated according to the list of removed buffer ids.

Since the `ProjectSearchView` now relies on the `Editor.has_any_buffer_folded` method in order to decide the state of the expand/collapse all excerpts button (updated on https://github.com/zed-industries/zed/pull/48773) this could lead to a bug where, after an initial project search, all excerpts would be collapsed, and performing a new search would leave the button in a wrong state, as all excerpts from the new search result would be expanded, but the button would still consider that there were folded excerpts for the buffers.

Closes https://github.com/zed-industries/zed/issues/50521

Before you mark this PR as ready for review, make sure that you have:
- [x] Added a solid test coverage and/or screenshots from doing manual testing
- [X] Done a self-review taking into account security and performance aspects
- [X] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Release Notes:

- Fixed bug in project search where collapsing a single buffer then performing a new search in the same view, would break the expand/collapse all button behavior

### CODE REVIEW

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -24145,6 +24145,7 @@ impl Editor {
                     self.display_map.update(cx, |display_map, cx| {
                         display_map.invalidate_semantic_highlights(*buffer_id);
                         display_map.clear_lsp_folding_ranges(*buffer_id, cx);
+                        display_map.clear_folded_buffer(*buffer_id);
```
Comment (SomeoneToIgnore) [inline crates/editor/src/editor.rs:24148]: I have a strong suspicion you want to call `sync` on the block map after doing this: otherwise you might get a very stale coordinate system that did not update after this removal?

Comment (dinocosta) [reply crates/editor/src/editor.rs:24148]: Thank you for calling that out! Too bad that I had already enabled auto-merge but will take a look ASAP 🔍

Comment (dinocosta) [reply crates/editor/src/editor.rs:24148]: You were absolutely right to call this out. The changes in https://github.com/zed-industries/zed/pull/50695 ensure that the block map is now synced when handling the ‎`multi_buffer::Event::ExcerptsRemoved` event.

Thank you again for catching this. 🙇
