### PR TITLE
project search: Reduce hangs on main thread

### LINKED ISSUE #37267: Windows Alpha: Zed craches while "Project search"
### Summary

When I do "Project search" by a folder with a lot of (1700+) HTML files with 470MB total size, Zed craches (attached the archive).
While works well when I search by Zed's repository with 3500+ files with 260MB total size.

### Description

Steps to trigger the problem:
1. Open a folder with a big number of files (attached archive from the video)
2. Try to search something with "Project search"

**Expected Behavior**:
Successful search

**Actual Behavior**:
Starts consuming RAM and CPU and then craches

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/507ab7f2-a5e6-4b61-ab99-fa8100d7cefc

</p>
</details> 

<details><summary>Archived folder (that Zed crashes with)</summary>
<p>

This is 7zip archive (not Zip). I had to rename it, because Github doesn't allow to upload 7Zip archives

[parsing-new.zip](https://github.com/user-attachments/files/22066649/parsing-new.zip)

</p>
</details> 

### Zed Version and System Specs

Zed: v0.203.0 (Zed Nightly ad746f25f268ef0ad3aeddc41bc05287c1d0d006) 
OS: Windows 10.0.26100
Memory: 27.8 GiB
Architecture: x86_64
GPU: AMD Radeon 780M Graphics || AMD Corporation || 24.10.39.05 (24.10.39.05-241017a-409950C-Lenovo)

### PR DESCRIPTION
**Pull request by osiewicz**
This takes the idea that @RemcoSmitsDev started on in https://github.com/zed-industries/zed/pull/39354. We did away with grabbing a snapshot of the display map when buffer coordinates were sufficient.
Closes #37267

Release Notes:

- Reduced micro-stutters in project search with large multi-buffer contents.

### CODE REVIEW

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -6607,26 +6607,31 @@ impl Editor {
...
         self.code_actions_task = Some(cx.spawn_in(window, async move |this, cx| {
             cx.background_executor()
                 .timer(CODE_ACTIONS_DEBOUNCE_TIMEOUT)
                 .await;
 
+            let (start_buffer, start, _, end, newest_selection) = this
+                .update(cx, |this, cx| {
+                    let newest_selection = this.selections.newest_anchor().clone();
+                    let newest_selection_adjusted = this.selections.newest_adjusted(cx);
+                    let buffer = this.buffer.read(cx);
```
Comment (RemcoSmitsDev) [inline crates/editor/src/editor.rs]: To make it even better, we can place this after the statement:
```rust
if newest_selection.head().diff_base_anchor.is_some() {
```
To prevent creating a potentially unused displaysnap that happens inside the `self.selections.newest_adjusted` method.

Comment (osiewicz) [reply crates/editor/src/editor.rs]: Good point!
