### PR TITLE
Fix animations in the component preview

### LINKED ISSUE #33869: Animation examples in the Component Preview are not easily viewable
### Summary

The Animations component preview renders some animations incorrectly, and users cannot watch every animation.

### Description

- The animations only run once, so you can't watch animations below the fold.
- The offset math is wrong, so some animated elements are rendered outside of the parent container.
- The "animate in from right" elements are defined with an initial `.left()` offset, which overrides the animation behavior.

Steps to reproduce:
1. Open the Component Preview
2. Navigate to the Uncategorized / Animation page
3. Scroll the page to view all examples

**Expected Behavior**:

- Examples should be rendered inside of the parent container, to help orient you to the direction of the animation.
- It should be possible to trigger the animation multiple times, so that you can scroll down the page and still see the animation for each example.

**Actual Behavior**:

- Most examples are rendered _outside_ of their parent container
- The animations are only triggered on page load, which prevents you from watching animations below the fold

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: macOS 15.5.0
Memory: 32 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by djsauble**
Fixes #33869

The Animation page in the Component Preview had a few issues.

* The animations only ran once, so you couldn't watch animations below the fold.
* The offset math was wrong, so some animated elements were rendered outside of their parent container.
* The "animate in from right" elements were defined with an initial `.left()` offset, which overrode the animation behavior.

I made fixes to address these issues. In particular, every time you click the active list item, it renders the preview again (which causes the animations to run again).

Before:

https://github.com/user-attachments/assets/a1fa2e3f-653c-4b83-a6ed-c55ca9c78ad4

After:

https://github.com/user-attachments/assets/3623bbbc-9047-4443-b7f3-96bd92f582bf

Release Notes:

- N/A

### CODE REVIEW

**Comment by 0x2CA** [comment]
I think the animated demo should add a button to click to play it once, looping is a bit strange

**Comment by djsauble** [comment]
I got rid of the auto-loop behavior. Now you trigger the animations by clicking the list item again. It's much simpler this way. Thanks for the suggestion @0x2CA.

File: crates/zed/src/zed/component_preview.rs [hunk 1]
```diff
@@ -1163,6 +1174,7 @@ impl ComponentPreviewPage {
         };
 
         v_flex()
+            .id(("component-preview", self.reset_key))
```
Comment (mikayla-maki) [inline crates/zed/src/zed/component_preview.rs:1177]: Clever solution!
