### PR TITLE
linux: Fix saving file with root ownership

### LINKED ISSUE #13585: RFE/Linux: polkit integration
### Check for existing issues

- [X] Completed

### Describe the feature

Currently on linux, zed has no way to prompt for elevated permissions (root) if the user does not have the permissions to write/read a file.

This is traditionally done with a request to polkit over dbus which will then prompt the user to input the superuser password in order to successfully perform the operation.

This is useful when attempting to use zed to update config files in the /etc/ directory, or, attempting to open files the user doesn't have read permission on, as some examples.

#10423 is a tangibly related issue for macos, however this request is for linux.

### If applicable, add mockups / screenshots to help present your vision of the feature

Example of a polkit prompt
Screenshot from 2024-06-27 11-15-04

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #13585

Currently, saving files with `root` ownership or `root` as the group throws a `Permission denied (os error 13). Please try again.` error. This PR fixes the issue on Linux by prompting the user for a password and saving the file with elevated privileges.

It uses `pkexec` (Polkit), which is by default available on GNOME, KDE, and most Linux systems. I haven't implemented this for macOS as I don't have a device to test it on.

This implementation is similar to how Vscode handles it. Except, they don't show custom message.

**Working**:

When file saving fails due to a `PermissionDenied` error, we create a temporary file in the same directory as the target file and writes the data to this temporary file. After, the contents of this file are copied to the original file using the `tee` command instead of `cp` or `mv`. This ensures that the ownership and permissions of the original file are preserved. This command is executed using `pkexec` which will prompt user for their password. 

**Custom Message**:

The message displayed to the user in the prompt is automatically retrieved from the `org.zed.app.policy` file, which is located at `/usr/share/polkit-1/actions/`. This file should be installed during the setup process. While the policy file is optional, omitting it will cause the user to see the underlying command being executed rather than a user-friendly message. Currently, VSCode does not display the user-friendly message.

The policy file must specify a unique binary, ensuring that only that binary can use the policy file. It cannot be as generic as a `/bin/bash`, as any software using bash to prompt will end up showing Zed’s custom message. To address this, we will create a custom bash script, as simple as the following, placed in `/usr/bin/zed/elevate.sh`. The script should have root ownership and should not reside in the home directory, since the policy file cannot resolve `$HOME`.

```sh
#!/bin/bash
eval "$@"
```

*IMPORTANT NOTE*

Since copying the policy file and our script requires sudo privileges, the installation script will now prompt for the password at very end. Only on Linux, if `pexec` is installed.

Screenshots:

KDE with policy file:
Screenshot from 2024-12-15 22-13-06

Gnome with policy file:
Screenshot from 2024-12-15 22-21-48

Gnome without policy file:
image

VSCode:
image

User declines the permission request:
image

Release Notes:

- Fixed file saving with root ownership on Linux.

### CODE REVIEW

File: script/install.sh [hunk 1]
```diff
@@ -126,6 +126,37 @@ linux() {
     cp "$HOME/.local/zed$suffix.app/share/applications/zed$suffix.desktop" "${desktop_file_path}"
     sed -i "s|Icon=zed|Icon=$HOME/.local/zed$suffix.app/share/icons/hicolor/512x512/apps/zed.png|g" "${desktop_file_path}"
     sed -i "s|Exec=zed|Exec=$HOME/.local/zed$suffix.app/bin/zed|g" "${desktop_file_path}"
+
+    # Copy PolicyKit if pkexec is available
+    if command -v pkexec >/dev/null 2>&1; then
+        echo "Zed requires sudo access to setup polkit policy file and elevation script."
```
Comment (mikayla-maki) [inline script/install.sh:132]: I think I'd prefer if we didn't handle this by exiting. Maybe change it to "Rerun this script with polkit so we can setup the policy file", or provide a separate script people can run like `sudo curl -f https://zed.dev/setup-polkit.sh | sh` . I think it's important that we offer a streamlined, non-sudo install path for our users by default.

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by 0xtimsb** [comment]
@mikayla-maki moved it to a separate optional script, as you asked. Also added docs for it in `linux.md`.

**Comment by mikayla-maki** [comment]
@0xtimsb thanks for making that change

That said, I think my suggestion has terrible UX… could we do something like detect if the user has Polkit installed, and then prompt them if they want  to install our policy, and only then escalate the scripts permissions to sudo to do the installation?

**Comment by 0xtimsb** [comment]
Yes, it's weird to ask them to run script to get pretty message :P.  Updated it to do it in `install.sh` itself. 

Now, in case Polkit is detected, we prompt the user to ask if we should configure Polkit. Only when the user accepts (y/Y/ enter) will it ask for the user's password. 

yes

If the user rejects the installation will proceed normally.

no

If Polkit is not detected, we simply add a warning and a docs link to install it. This should be very rare.

no

File: script/install.sh [hunk 2]
```diff
@@ -126,6 +126,72 @@ linux() {
...
+  </action>
+</policyconfig>'
+
+            # We only request sudo access now
+            if sudo mkdir -p "$LIBEXEC_DIR" && \
+                echo "$ELEVATE_SCRIPT_CONTENT" | sudo tee "$ELEVATE_SCRIPT" > /dev/null && \
+                sudo chmod 755 "$ELEVATE_SCRIPT" && \
+                sudo mkdir -p "$POLKIT_DIR" && \
+                echo "$POLICY_CONTENT" | sudo tee "$POLKIT_DIR/org.zed.app.policy" > /dev/null && \
+                sudo chmod 644 "$POLKIT_DIR/org.zed.app.policy"; then
```
Comment (jansol) [inline script/install.sh:183]: ditto about the app id

File: crates/fs/src/fs.rs [hunk 3]
```diff
@@ -1999,6 +2013,70 @@ fn chunks(rope: &Rope, line_ending: LineEnding) -> impl Iterator<Item = &str> {
...
+    let mut cmd = Command::new(pkexec_path);
+    cmd.arg("--disable-internal-agent");
+
+    let script_path = PathBuf::from("/usr/libexec/zed/elevate.sh");
+    if script_path.exists() {
+        // Custom message will be shown to user
+        cmd.arg(&script_path).arg(command);
+    } else {
+        // Default message will be shown to user
+        cmd.arg("/bin/bash").arg("-c").arg(command);
```
Comment (jansol) [inline crates/fs/src/fs.rs:2069]: `/bin/bash` doesn't exist e.g. on NixOS. `/bin/sh` is more reliable in that regard. If bash is *really* necessary `/usr/bin/env bash` is a better way to invoke it.

File: script/install.sh [hunk 4]
```diff
@@ -126,6 +126,72 @@ linux() {
...
+        echo "Note: 'pkexec' not detected. You won't be able to edit root files in Zed."
+        echo "See https://zed.dev/docs/linux#root for more information."
+        echo
+        return 0
+    fi
+
+    # Prompt user
+    echo
+    echo "Zed needs sudo access to improve root file editing experience."
+    printf "Configure polkit? [Y/n] "
```
[the remark this answers is not in the document]
Comment (0xtimsb) [reply script/install.sh]: Yup, not super accurate (since it’d still work even after saying no), but let’s just write it this way for simplicity's sake.

File: crates/fs/src/fs.rs [hunk 5]
```diff
@@ -1999,6 +2013,70 @@ fn chunks(rope: &Rope, line_ending: LineEnding) -> impl Iterator<Item = &str> {
...
+        return Err(anyhow::anyhow!(
+            "pkexec not found at {}",
+            pkexec_path.display()
+        ));
+    }
+
+    let mut cmd = Command::new(pkexec_path);
+    cmd.arg("--disable-internal-agent");
+
+    let script_path = PathBuf::from("/usr/libexec/zed/elevate.sh");
```
[the remark this answers is not in the document]
Comment (0xtimsb) [reply crates/fs/src/fs.rs]: I’ve added the env variable which can be used in Nix installation. But, I'm not picking that in this PR as I'm not familiar with Nix yet. It should still work on NixOS as long as pkexec is in the PATH without custom message. I will create another PR after setting up NixOS VM and testing there.

[the remark this answers is not in the document]
Comment (jansol) [reply crates/fs/src/fs.rs]: Thanks! In nixpkgs we wrap the executable in a shell script to add node.js into its PATH already so adding pkexec in that mix is trivial. Similarly setting the environment variable for the elevate script to point to `/nix/store/<hash>` is easily doable now. Updating the nix files in this repo can indeed be done separately (especially since this is not a change that breaks something that was working before).

**Comment by ConradIrwin** [comment]
@0xtimsb thanks for this!

We should not add this functionality to the install.sh script. It should not prompt (so that it can be run in people's setup scripts without needing arguments to skip prompts) and it should not write outside of your home directory or ask for root (so that anyone can install Zed on any machine).

If we need polkit support for this feature, we should defer installing it to later as we do with the `zed::InstallCli` action on macOS. That said, if we need sudo access to install a thing just to get sudo access, we have a catch-22..

Is there a way of building this feature that does not require configuration changes on the machine? It sounds like we could get the same behavior as VSCode without it. If so that seems like the better trade-off (and if we call the script something like `write-to-file-as-root` hopefully it's clear enough what's going on)

**Comment by 0xtimsb** [comment]
@ConradIrwin thanks for the suggestions!

I've removed the policy and custom script, so there are no changes to the installation process now. I went with a similar approach to VSCode, creating a temporary script during runtime instead of setting up a script during the Zed installation.

It’s much simpler now - just the script name shows up in prompt instead of a bunch of arguments, so it’s clearer. This should also work on NixOS.

Gnome:
gnome

KDE:
kde

File: crates/fs/src/fs.rs [hunk 6]
```diff
@@ -546,13 +531,35 @@ impl Fs for RealFs {
...
+                let mut writer = smol::io::BufWriter::with_capacity(buffer_size, file);
+                for chunk in chunks(text, line_ending) {
+                    writer.write_all(chunk.as_bytes()).await?;
+                }
+                writer.flush().await?;
+                Ok(())
+            }
+            Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
+                if cfg!(any(target_os = "linux", target_os = "freebsd")) {
+                    let tmp_file = create_temp_file(&path)?;
```
Comment (mikayla-maki) [inline crates/fs/src/fs.rs:545]: I believe this should be inside a `smol::unblock(|| { /**/ }).await`

File: crates/fs/src/fs.rs [hunk 7]
```diff
@@ -1999,6 +2006,74 @@ fn chunks(rope: &Rope, line_ending: LineEnding) -> impl Iterator<Item = &str> {
...
+    writeln!(
+        script_file.as_file(),
+        "#!/usr/bin/env bash\ncat \"{}\" > \"{}\"",
+        temp_file_path.display(),
+        target_file_path.display()
+    )?;
+
+    let mut perms = script_file.as_file().metadata()?.permissions();
+    perms.set_mode(0o700); // rwx------
+    script_file.as_file().set_permissions(perms)?;
```
Comment (mikayla-maki) [inline crates/fs/src/fs.rs:2062]: As should all of the file IO in this function, down to about this line.

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by mikayla-maki** [comment]
Beyond the blocking IO, this implementation looks great!

**Comment by 0xtimsb** [comment]
Resolved the blocking I/O issue—thanks, @mikayla-maki, for your patience. Learning a lot from your suggestions and others.

File: crates/fs/src/fs.rs [hunk 8]
```diff
@@ -1999,6 +2014,81 @@ fn chunks(rope: &Rope, line_ending: LineEnding) -> impl Iterator<Item = &str> {
...
+    let script_file = smol::unblock(move || {
+        let script_file = tempfile::Builder::new()
+            .prefix("write-to-file-as-root-")
+            .tempfile_in(paths::temp_dir())?;
+
+        writeln!(
+            script_file.as_file(),
+            "#!/usr/bin/env bash\ncat \"{}\" > \"{}\"",
+            temp_file_path.display(),
+            target_file_path.display()
```
Comment (jansol) [inline crates/fs/src/fs.rs:2068]: These MUST have any quotes escaped since they are inserted with plain string interpolation.

Also the script is simple enough that we can get away with plain `sh`, like the install.sh script does, instead of adding a dependency on bash.

**Review by jansol — CHANGES_REQUESTED** [review]

File: crates/fs/src/fs.rs (hunk 8 above)
Comment (0xtimsb) [reply crates/fs/src/fs.rs]: Make sense. Updated.

**Review by mikayla-maki — APPROVED** [review]

**Comment by mikayla-maki** [comment]
This PR implementation looks good, and no longer changes our install script at all, so I'm going to merge it.

**Comment by ReillyBrogan** [comment]
Just got the notification that this PR existed otherwise I would have been here sooner.

The polkit file isn't in the changes anymore, is that intentional? I looked back at the history for it, and the following:
```
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>
 ```
 
 Should be
 ```
     <defaults>
      <allow_inactive>no</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>
```

```
        writeln!(
            script_file.as_file(),
            "#!/usr/bin/env sh\nset -eu\ncat \"{}\" > \"{}\"",
            try_quote(&temp_file_path.to_string_lossy())?,
            try_quote(&target_file_path.to_string_lossy())?
        )?;
```

Yeah this is completely insecure. This opens up the attack vector that the script can be modified by another process between it being written and it being executed allowing that process to execute arbitrary code as root with the user being none the wiser. The initial design of having a separate script that was installed by the install script was the correct one as, assuming Zed is installed to a system location that the user executing Zed does not have direct write access to, it completely mitigates that vector of attack. 

Instead of using a script you could use a dedicated binary (faster, some systems have profile scripts that may introduce noticeable delay while a binary will be more consistent) or have a separate "command" that zed understands so it can pkexec itself. You should also hash the file contents and pass that hash to the helper script/binary so that it can verify that the temporary file hasn't been modified by another process.

**Comment by jansol** [comment]
> assuming Zed is installed to a system location that the user executing Zed does not have direct write access to

If you use the official installer script this won't be the case.

**Comment by 0xtimsb** [comment]
>  This opens up the attack vector that the script can be modified by another process between it being written and it being executed allowing that process to execute arbitrary code as root with the user being none the wiser. 

Isn't risk is more if script is pre-defined at some location (usually in .local dir)? This is also how VSCode currently does it, [here](https://github.com/bpasero/sudo-prompt/blob/vscode/index.js).

**Comment by ReillyBrogan** [comment]
> > This opens up the attack vector that the script can be modified by another process between it being written and it being executed allowing that process to execute arbitrary code as root with the user being none the wiser.
> 
> Isn't risk is more if script is pre-defined at some location (usually in .local dir)? This is also how VSCode currently does it, [here](https://github.com/bpasero/sudo-prompt/blob/vscode/index.js?rgh-link-date=2024-12-20T04%3A23%3A41Z).

I don't believe that that is true. I instrumented process execution on my machine (using execsnoop from bcc) and see the following process started by vscode:
```
/usr/bin/pkexec --disable-internal-agent /bin/bash -c echo SUDOPROMPT; "/usr/share/vscode/bin/code" --file-write "/home/reilly/.config/Code/code-elevated-ekxS9Ub6"
```

Crucially we see that vscode is executing itself with the `--file-write` flag. Logic for which is available [here](https://github.com/microsoft/vscode/blob/main/src/vs/code/node/cli.ts#L140), but the gist of which is that the value of `--file-write` is a metadata json file containing the source (the temporary file) and the destination. There's also logic around restoring file permissions (chmod/chown) that you'll want to implement as well since the newly replaced file will not inherit the permissions that the "old" file had (this could be problematic for a user if a service is supposed to have read/write based on group to a file that it loses since the new permissions will be root:root).

Though vscode doesn't implement it this could be further improved by checksumming the temporary file and passing that checksum to the "root" process, not sure why they're not doing that.

Additionally there's a bit of logic to prevent vscode from being ran as root unless that flag is passed [here](https://github.com/microsoft/vscode/blob/main/resources/linux/bin/code.sh#L31), which is probably a good idea to implement as well if similar does not already exist.

**Comment by ReillyBrogan** [comment]
Alright it's been two weeks since I reported this security issue and I don't see any follow-up PRs addressing the insecure behavior. If my understanding of the release schedule is correct this is going to go out to users next week correct? I suppose I'll have to file a CVE if that happens, I don't see that Zed currently has a CPE, I suppose the correct one to create would be `zed_project:zed` for the vendor:product combination. Is there a different combination that would be preferred?

CC @ConradIrwin

**Comment by 0xtimsb** [comment]
Hi, @ReillyBrogan 

I have few questions regarding this, I would like if we can figure out some actionables to follow up security issues you mentioned. FYI, I'm not associated with Zed, just an external contributor.

> Crucially we see that vscode is executing itself with the --file-write flag. Logic for which is available [here](https://github.com/microsoft/vscode/blob/main/src/vs/code/node/cli.ts#L140), but the gist of which is that the value of --file-write is a metadata json file containing the source (the temporary file) and the destination.

I don’t understand how this differs from the current implementation. I see, instead of a script containing the file content, we have a script that points to the file path. But both approaches are similar in terms of temporary script creation, execution, and deletion. So, doesn’t VS Code’s script also have the same mentioned vulnerability when it comes to modifying the script?

> There's also logic around restoring file permissions (chmod/chown) that you'll want to implement as well since the newly replaced file will not inherit the permissions that the "old" file had (this could be problematic for a user if a service is supposed to have read/write based on group to a file that it loses since the new permissions will be root:root).

We are not replacing the target file, only modifying its content, so the existing permissions will remain unchanged. The ownership may change to root, but since the file is already owned by root, this should not be an issue?

**Comment by ConradIrwin** [comment]
@ReillyBrogan Sorry for the slow reply here.

To summarize the problem:
* If you have a rogue user/process that has the ability to edit files owned by the current user, but not the ability to run code as root, they can use this Zed feature to privilege escalate.

Do I understand the threat model correctly?

It seems like we can simplify the implementation to avoid the issue by doing:
```
pkexec sh -c 'cat > {filename}'
```
and passing input on STDIN.

This avoids the need for an extra shell-script, and avoids the ability for the rogue entity to edit the copy of the file on disk. Does that fix the problem for you?

I'm not sure it's a huge issue (an actor with the ability to edit your files can achieve more reliable success by changing your shell configuration to make `pkexec` an alias that does nefarious things avoiding the need to win a race condition), but it seems nice to simplify the implementation regardless.

**Comment by ConradIrwin** [comment]
@0xtimsb I noticed when working on #22843 that while saving seems to work fine, we never get a notification that the file has changed on disk, and so Zed continues to think the file is unsaved/has a conflict.

Did you also experience that in the first implementation, or is there something different about our setups?

**Comment by 0xtimsb** [comment]
I believe this is setup-related. I faced this on Kubuntu 24.10 with both Zed and VSCode - neither detected file changes. I let it pass, assuming it was a KDE issue on the latest version. On 24.04 LTS, it worked fine. What DE are you using?

**Comment by 0xtimsb** [comment]
Oh wait, I misunderstood your question. I tried this (https://github.com/zed-industries/zed/pull/22843), and something similar to what you're experiencing happened to me while working on it. I don't quite remember how I fixed it. I'm debugging.

The current latest preview works on my machine.

**Comment by ZA0068** [comment]
I have gotten this same issue, but i request a more streamlined approach: A built-in tool where I can save as sudo/root.
