### PR TITLE
repl: Avoid duplicate kernelspec fetches

### LINKED ISSUE #50988: Zed creates "infinite" Python processes during repl kernel discovery, High CPU usage
### Reproduction steps

1. Start Zed
2. Open py with repl enabled
3. Click on kernel to initiate search
4. Not always reproducible

usually how it starts is that I search for kernels by clicking on the repl button and I either only see Jupyter kernels or I see these kernels but it says (incorrectly) that ipykernel is not installed. Then the entire editor slows down and affects my entire machine. I've attached the screenshot of the error behavior for the repl kernels to provide some context.

When it fails: 
Image

When it works: 
Image

As you can see from the Activity Monitor, it spawns a ton of Python processes. Based on the different versions listed, I suspect that it is to do with the searching for ipykernels. The parent process is Zed.

it seems to happen more maybe when I open multiple windows. Again, I cannot provide that many details because my entire computer slows down significantly when this happens to the point that I have to force shutdown. 

Image

Image

### Zed version and system specs

Zed: v0.226.5+stable.197.07dae3b7020b0ad79ed91e18c750a16952432866 (Zed) 
OS: macOS 15.5
Memory: 16 GiB
Architecture: aarch64

<details><summary>Sampling of Python process (after quitting zed, not sure if accurate)</summary>

```log
Analysis of sampling python (pid 25375) every 1 millisecond
Process:         python3.10 [25375]
Path:            /Users/USER/*/python3.10
Load Address:    0x1004b4000
Identifier:      python3.10
Version:         0
Code Type:       ARM64
Platform:        macOS
Parent Process:  launchd [1]
Target Type:     live task

Date/Time:       2026-03-07 00:52:18.240 -0500
Launch Time:     2026-03-07 00:47:04.641 -0500
OS Version:      macOS 15.5 (24F74)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         24.1M
Physical footprint (peak):  24.1M
Idle exit:                  untracked

Call graph:
    2272 Thread_156280   DispatchQueue_1: com.apple.main-thread  (serial)
      2272 start  (in dyld) + 6076  [0x188d36b98]
        2272 main  (in python3.10) + 56  [0x1004b85dc]
          2272 pymain_main  (in python3.10) + 1272  [0x1006719a0]
            2272 Py_RunMain  (in python3.10) + 3000  [0x100670a78]
              2272 Py_FinalizeEx  (in python3.10) + 692  [0x100643270]
                2237 finalize_modules  (in python3.10) + 4964  [0x100644be8]
                + 1025 _PyModule_ClearDict  (in python3.10) + 628  [0x100563dac]
                + ! 994 insertdict  (in python3.10) + 688  [0x10054c540]
                + ! : 396 func_dealloc  (in python3.10) + 76  [0x100532c4c]
                + ! : | 345 func_clear  (in python3.10) + 100  [0x100532e5c]
                + ! : | + 176 code_dealloc  (in python3.10) + 444,276,...  [0x1005123bc,0x100512314,...]
                + ! : | + 150 code_dealloc  (in python3.10) + 244  [0x1005122f4]
                + ! : | + ! 131 tupledealloc  (in python3.10) + 240  [0x10057a600]
                + ! : | + ! : 130 unicode_dealloc  (in python3.10) + 136  [0x10059032c]
                + ! : | + ! : | 130 _PyDict_DelItem_KnownHash  (in python3.10) + 116  [0x100552690]
                + ! : | + ! : 1 code_dealloc  (in python3.10) + 216  [0x1005122d8]
                + ! : | + ! 19 tupledealloc  (in python3.10) + 220,212  [0x10057a5ec,0x10057a5e4]
                + ! : | + 14 code_dealloc  (in python3.10) + 344  [0x100512358]
                + ! : | + ! 14 tupledealloc  (in python3.10) + 212  [0x10057a5e4]
                + ! : | + 4 code_dealloc  (in python3.10) + 328  [0x100512348]
                + ! : | + ! 4 tupledealloc  (in python3.10) + 212  [0x10057a5e4]
                + ! : | + 1 code_dealloc  (in python3.10) + 260  [0x100512304]
                + ! : | +   1 object_dealloc  (in python3.10) + 0  [0x10058b058]
                + ! : | 46 func_clear  (in python3.10) + 120,36,...  [0x100532e70,0x100532e1c,...]
                + ! : | 5 func_clear  (in python3.10) + 468  [0x100532fcc]
                + ! : |   5 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : |     5 free_tiny  (in libsystem_malloc.dylib) + 460  [0x188edb99c]
                + ! : |       5 tiny_free_no_lock  (in libsystem_malloc.dylib) + 792  [0x188edbe34]
                + ! : |         5 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 176  [0x188edc640]
                + ! : 217 dict_dealloc  (in python3.10) + 660  [0x10054a460]
                + ! : | 79 pattern_dealloc  (in python3.10) + 224  [0x1006989bc]
                + ! : | + 79 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : | +   76 _nanov2_free  (in libsystem_malloc.dylib) + 0  [0x188efbcc4]
                + ! : | +   3 _free  (in libsystem_malloc.dylib) + 12  [0x188f09c20]
                + ! : | 75 pattern_dealloc  (in python3.10) + 40,120  [0x100698904,0x100698954]
                + ! : | 62 pattern_dealloc  (in python3.10) + 212  [0x1006989b0]
                + ! : | + 51 PyObject_Free  (in python3.10) + 0,12  [0x10056d300,0x10056d30c]
                + ! : | + 11 _PyObject_Free  (in python3.10) + 0,92  [0x10056a768,0x10056a7c4]
                + ! : | 1 pattern_dealloc  (in python3.10) + 164  [0x100698980]
                + ! : |   1 dict_dealloc  (in python3.10) + 484  [0x10054a3b0]
                + ! : 167 dict_dealloc  (in python3.10) + 596,632  [0x10054a420,0x10054a444]
                + ! : 73 lru_cache_dealloc  (in python3.10) + 88  [0x1006a4c48]
                + ! : | 73 lru_cache_tp_clear  (in python3.10) + 308  [0x1006a4ee4]
                + ! : |   73 dict_dealloc  (in python3.10) + 660  [0x10054a460]
                + ! : |     73 func_dealloc  (in python3.10) + 76  [0x100532c4c]
                + ! : |       30 func_clear  (in python3.10) + 100  [0x100532e5c]
                + ! : |       + 30 code_dealloc  (in python3.10) + 656  [0x100512490]
                + ! : |       +   30 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : |       +     30 free_tiny  (in libsystem_malloc.dylib) + 148  [0x188edb864]
                + ! : |       29 func_clear  (in python3.10) + 560  [0x100533028]
                + ! : |       + 27 tupledealloc  (in python3.10) + 44  [0x10057a53c]
                + ! : |       + 2 tupledealloc  (in python3.10) + 240  [0x10057a600]
                + ! : |       +   2 _PyObject_Free  (in python3.10) + 92  [0x10056a7c4]
                + ! : |       14 func_clear  (in python3.10) + 212,28  [0x100532ecc,0x100532e14]
                + ! : 57 dict_dealloc  (in python3.10) + 624  [0x10054a43c]
                + ! : | 57 tupledealloc  (in python3.10) + 212  [0x10057a5e4]
                + ! : 34 subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]
                + ! : | 31 dict_dealloc  (in python3.10) + 196  [0x10054a290]
                + ! : | + 19 func_dealloc  (in python3.10) + 76  [0x100532c4c]
                + ! : | + ! 12 func_clear  (in python3.10) + 376  [0x100532f70]
                + ! : | + ! : 12 tupledealloc  (in python3.10) + 232  [0x10057a5f8]
                + ! : | + ! 7 func_clear  (in python3.10) + 212,28  [0x100532ecc,0x100532e14]
                + ! : | + 9 list_dealloc  (in python3.10) + 40  [0x100536bbc]
                + ! : | + 3 subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]
                + ! : | +   3 dict_dealloc  (in python3.10) + 196  [0x10054a290]
                + ! : | +     3 subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]
                + ! : | +       3 dict_dealloc  (in python3.10) + 128  [0x10054a24c]
                + ! : | 3 dict_dealloc  (in python3.10) + 128  [0x10054a24c]
                + ! : 20 func_dealloc  (in python3.10) + 24,68,...  [0x100532c18,0x100532c44,...]
                + ! : 12 meth_dealloc  (in python3.10) + 236,120  [0x100560674,0x100560600]
                + ! : 10 dict_dealloc  (in python3.10) + 740  [0x10054a4b0]
                + ! : | 10 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : |   10 free_small  (in libsystem_malloc.dylib) + 520  [0x188eda62c]
                + ! : |     10 small_free_list_find_by_ptr  (in libsystem_malloc.dylib) + 68  [0x188edccc4]
                + ! : 7 subtype_dealloc  (in python3.10) + 360  [0x10057f7a0]
                + ! : 1 module_dealloc  (in python3.10) + 52  [0x1005618e4]
                + ! 31 insertdict  (in python3.10) + 656,572,...  [0x10054c520,0x10054c4cc,...]
                + 947 _PyModule_ClearDict  (in python3.10) + 1268  [0x10056402c]
                + ! 753 insertdict  (in python3.10) + 688  [0x10054c540]
                + ! : 457 func_dealloc  (in python3.10) + 76  [0x100532c4c]
                + ! : | 255 func_clear  (in python3.10) + 100  [0x100532e5c]
                + ! : | + 155 code_dealloc  (in python3.10) + 260  [0x100512304]
                + ! : | + ! 129 _PyObject_Free  (in python3.10) + 92  [0x10056a7c4]
                + ! : | + ! 26 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : | + !   26 free_tiny  (in libsystem_malloc.dylib) + 460  [0x188edb99c]
                + ! : | + !     26 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1012  [0x188edbf10]
                + ! : | + !       26 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 176  [0x188edc640]
                + ! : | + 63 code_dealloc  (in python3.10) + 192,236,...  [0x1005122c0,0x1005122ec,...]
                + ! : | + 19 code_dealloc  (in python3.10) + 328  [0x100512348]
                + ! : | + ! 10 tupledealloc  (in python3.10) + 240  [0x10057a600]
                + ! : | + ! : 10 unicode_dealloc  (in python3.10) + 136  [0x10059032c]
                + ! : | + ! :   10 _PyDict_DelItem_KnownHash  (in python3.10) + 128  [0x10055269c]
                + ! : | + ! :     10 lookdict_unicode  (in python3.10) + 332  [0x100552b10]
                + ! : | + ! 9 tupledealloc  (in python3.10) + 212,220  [0x10057a5e4,0x10057a5ec]
                + ! : | + 18 code_dealloc  (in python3.10) + 244  [0x1005122f4]
                + ! : | +   9 tupledealloc  (in python3.10) + 240  [0x10057a600]
                + ! : | +   : 6 code_dealloc  (in python3.10) + 284  [0x10051231c]
                + ! : | +   : 3 tupledealloc  (in python3.10) + 212  [0x10057a5e4]
                + ! : | +   9 tupledealloc  (in python3.10) + 212  [0x10057a5e4]
                + ! : | 115 func_clear  (in python3.10) + 468  [0x100532fcc]
                + ! : | + 115 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : | +   107 free_small  (in libsystem_malloc.dylib) + 816  [0x188eda754]
                + ! : | +   ! 107 small_free_list_add_ptr  (in libsystem_malloc.dylib) + 464  [0x188edc958]
                + ! : | +   6 free_tiny  (in libsystem_malloc.dylib) + 460  [0x188edb99c]
                + ! : | +   ! 5 tiny_free_no_lock  (in libsystem_malloc.dylib) + 792  [0x188edbe34]
                + ! : | +   ! : 5 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 112  [0x188edc600]
                + ! : | +   ! 1 tiny_free_no_lock  (in libsystem_malloc.dylib) + 416  [0x188edbcbc]
                + ! : | +   !   1 tiny_free_list_add_ptr  (in libsystem_malloc.dylib) + 184  [0x188edc3f4]
                + ! : | +   2 free_tiny  (in libsystem_malloc.dylib) + 148  [0x188edb864]
                + ! : | 85 func_clear  (in python3.10) + 28,332  [0x100532e14,0x100532f44]
                + ! : | 2 func_clear  (in python3.10) + 360  [0x100532f60]
                + ! : |   2 dict_dealloc  (in python3.10) + 484  [0x10054a3b0]
                + ! : 182 set_dealloc  (in python3.10) + 244  [0x100570b5c]
                + ! : | 182 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : |   182 free_small  (in libsystem_malloc.dylib) + 52,124,...  [0x188eda458,0x188eda4a0,...]
                + ! : 71 subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]
                + ! : | 48 dict_dealloc  (in python3.10) + 52,48,...  [0x10054a200,0x10054a1fc,...]
                + ! : | 23 dict_dealloc  (in python3.10) + 196  [0x10054a290]
                + ! : |   14 subtype_dealloc  (in python3.10) + 180  [0x10057f6ec]
                + ! : |   7 rlock_dealloc  (in python3.10) + 60  [0x1006c3628]
                + ! : |   ! 7 PyThread_free_lock  (in python3.10) + 32  [0x100660338]
                + ! : |   !   7 pthread_cond_destroy  (in libsystem_pthread.dylib) + 32,248  [0x1890d4ee8,0x1890d4fc0]
                + ! : |   2 subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]
                + ! : |     2 dict_dealloc  (in python3.10) + 788  [0x10054a4e0]
                + ! : |       2 PyObject_GC_Del  (in python3.10) + 0  [0x100675140]
                + ! : 18 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! : | 13 free_small  (in libsystem_malloc.dylib) + 52  [0x188eda458]
                + ! : | 5 free_tiny  (in libsystem_malloc.dylib) + 460  [0x188edb99c]
                + ! : |   5 tiny_free_no_lock  (in libsystem_malloc.dylib) + 1012  [0x188edbf10]
                + ! : |     5 tiny_free_list_remove_ptr  (in libsystem_malloc.dylib) + 112  [0x188edc600]
                + ! : 8 dict_dealloc  (in python3.10) + 484  [0x10054a3b0]
                + ! : 8 subtype_dealloc  (in python3.10) + 184  [0x10057f6f0]
                + ! : 5 list_dealloc  (in python3.10) + 36  [0x100536bb8]
                + ! : 3 func_dealloc  (in python3.10) + 0  [0x100532c00]
                + ! : 1 list_dealloc  (in python3.10) + 272  [0x100536ca4]
                + ! :   1 _PyObject_Free  (in python3.10) + 156  [0x10056a804]
                + ! :     1 free_small  (in libsystem_malloc.dylib) + 52  [0x188eda458]
                + ! 185 insertdict  (in python3.10) + 656,664,...  [0x10054c520,0x10054c528,...]
                + ! 9 insertdict  (in python3.10) + 184  [0x10054c348]
                + !   9 lookdict_unicode_nodummy  (in python3.10) + 472  [0x10054d208]
                + 255 _PyModule_ClearDict  (in python3.10) + 304,248,...  [0x100563c68,0x100563c30,...]
                + 10 _PyModule_ClearDict  (in python3.10) + 852  [0x100563e8c]
                +   10 _PyUnicode_EqualToASCIIString  (in python3.10) + 56,0  [0x1005be12c,0x1005be0f4]
                35 finalize_modules  (in python3.10) + 4768,4948,...  [0x100644b24,0x100644bd8,...]

Total number in stack (recursive counted multiple, when >=5):
        9       _PyObject_Free  (in python3.10) + 156  [0x10056a804]
        9       tupledealloc  (in python3.10) + 0  [0x10057a510]
        7       dict_dealloc  (in python3.10) + 0  [0x10054a1cc]
        5       subtype_dealloc  (in python3.10) + 1168  [0x10057fac8]

Sort by top of stack, same collapsed (when >= 5):
        _PyModule_ClearDict  (in python3.10)        255
        code_dealloc  (in python3.10)        246
        dict_dealloc  (in python3.10)        232
        insertdict  (in python3.10)        216
        free_small  (in libsystem_malloc.dylib)        196
        tupledealloc  (in python3.10)        154
        func_clear  (in python3.10)        152
        _PyObject_Free  (in python3.10)        142
        _PyDict_DelItem_KnownHash  (in python3.10)        130
        small_free_list_add_ptr  (in libsystem_malloc.dylib)        107
        _nanov2_free  (in libsystem_malloc.dylib)        76
        pattern_dealloc  (in python3.10)        75
        PyObject_Free  (in python3.10)        51
        tiny_free_list_remove_ptr  (in libsystem_malloc.dylib)        41
        finalize_modules  (in python3.10)        35
        free_tiny  (in libsystem_malloc.dylib)        32
        subtype_dealloc  (in python3.10)        29
        func_dealloc  (in python3.10)        23
        list_dealloc  (in python3.10)        14
        meth_dealloc  (in python3.10)        12
        _PyUnicode_EqualToASCIIString  (in python3.10)        10
        lookdict_unicode  (in python3.10)        10
        small_free_list_find_by_ptr  (in libsystem_malloc.dylib)        10
        lookdict_unicode_nodummy  (in python3.10)        9
        pthread_cond_destroy  (in libsystem_pthread.dylib)        7

```
</details>

### Attach Zed log file
<details><summary>Zed.log</summary>

```log
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 458698e8-3045-4116-9695-c3db6dfd9ffd at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 193.51120899617672ms"
}
2026-03-04T13:08:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request b924122e-89aa-493f-a85e-0365bd0d3216 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 212.90233400464058ms"
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 4bd94ea1-2426-4f5b-b208-986094673f41 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 201.89070799946785ms"
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 923acd31-166e-4f2f-b23c-769425611aec at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 303.8002080023289ms"
}
2026-03-04T13:08:40-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [652f032b-80bb-4823-8975-297fd6ee2a85] model deployment ID: []] "
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request e54e6583-a649-43bd-9ced-a56e04bd56e2 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 225.24454100430012ms"
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [1b39b03a-9f9d-4f66-af4b-6fc3a70c32c9] model deployment ID: []] "
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:42-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 51a203f4-6f95-4923-a0bc-461abd98d87e at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 338.78154200315475ms"
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 93d16c85-9e3f-4b92-908a-f4b4e9d7b13d at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 205.8969999998808ms"
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:08:43-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:30-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:09:30-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 93d7f957-0eea-4e71-b020-bd0c829165a6 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 218.72945798933506ms"
}
2026-03-04T13:09:30-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:09:30-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:33-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:33-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [0575865d-4978-4210-910b-82ba71657972] model deployment ID: []] "
}
2026-03-04T13:09:34-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:34-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [43a4bdcc-700a-4eb6-aa3b-602a784a8b60] model deployment ID: []] "
}
2026-03-04T13:09:36-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:36-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [c9ed5e6d-5c2f-4549-abbc-67325d2e6f46] model deployment ID: []] "
}
2026-03-04T13:09:37-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request d5362da2-e07f-4af6-a63c-d43e93e95994 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 159.0539579987526ms"
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 54685411-60ce-4a2d-88ac-7bac988baeab at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 248.2491250038147ms"
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 36e62f95-5270-45c5-be22-f63ce57e5e4a at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 218.82058399915695ms"
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:09:38-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:39-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [140e80e4-3cb1-44c6-a00e-c7d046a9f2d1] model deployment ID: []] "
}
2026-03-04T13:09:44-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:09:44-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 41e67011-a9de-4354-b09f-59c672c39e71 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 295.8320830017328ms"
}
2026-03-04T13:09:44-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:09:44-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:44-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:09:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [f048bbdc-fad9-4f1b-ae7b-89cc37cdc983] model deployment ID: []] "
}
2026-03-04T13:09:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:09:48-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:09:48-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [0d36ab1d-1001-4096-a03e-a7e9c47a2378] model deployment ID: []] "
}
2026-03-04T13:10:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:10:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request b703156d-9a36-43c8-9bc4-dc1a53d9e511 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 207.25895799696445ms"
}
2026-03-04T13:10:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:10:41-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:10:50-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:10:50-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [da1aa0f5-eee9-4e8a-8601-4b592311be75] model deployment ID: []] "
}
2026-03-04T13:13:32-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:13:32-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request dabf43f9-7b82-42ab-98f6-ceb806820516 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 337.5019589960575ms"
}
2026-03-04T13:13:32-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:13:32-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:13:35-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:13:35-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [66069521-1033-4b5c-ad88-244fdc0b0d76] model deployment ID: []] "
}
2026-03-04T13:13:36-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:13:36-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [459030f5-1584-41e2-9fb3-8f6d4836d252] model deployment ID: []] "
}
2026-03-04T13:13:37-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:13:37-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [a54e3299-d453-4cfd-a227-4a774a2fec33] model deployment ID: []] "
}
2026-03-04T13:15:02-05:00 INFO  [lsp] starting language server process. binary path: "/Users/seanlim/.nvm/versions/node/v22.13.1/bin/node", working directory: "/Users/seanlim/Documents/Github/PetProj/2025/portfolio", args: ["/Users/seanlim/Library/Application Support/Zed/languages/vscode-css-language-server/node_modules/vscode-langservers-extracted/bin/vscode-css-language-server", "--stdio"]
2026-03-04T13:15:08-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:15:08-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [9b42b1f0-1a21-4154-a7bf-ac607eb4eb9a] model deployment ID: []] "
}
2026-03-04T13:17:01-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:01-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:17:01-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [cd3a6123-f153-44a7-af89-67876788b4a2] model deployment ID: []] "
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request ab813f14-3b54-4850-8c5c-8cda30068e4c at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 192.94429099559784ms"
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 38ec90e0-adba-42c8-8c89-32e6875c17d2 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 219.17091700434685ms"
}
2026-03-04T13:17:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 464828fe-578b-43a4-be10-7b00391a6694 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 173.7487089931965ms"
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [content_filter]"
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request c0158e7c-ed80-4bc0-8369-d6a185aef5dc at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 198.66216699779034ms"
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:17:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[code-referencing] Calling Match"
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[code-referencing] No match found"
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 8ad27e1a-4810-49b1-a6cd-264166cc689b at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 225.81912499666214ms"
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:17:04-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[code-referencing] Calling Match"
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[code-referencing] No match found"
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request fb3b9a5e-de7c-450e-9153-406e5768ebdd at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 204.10087499022484ms"
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:17:05-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:08-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:17:08-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [913d19af-00ba-4dad-aeba-307fa57e5b17] model deployment ID: []] "
}
2026-03-04T13:17:09-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:17:09-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [baa0224f-ca03-4d82-9d20-4ead4ab7534b] model deployment ID: []] "
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [577db905-081f-40d4-be54-c9c8ba07a0ec] model deployment ID: []] "
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request e230f6a1-1515-4575-9de2-4d3d892b9d5f at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 249.1942920088768ms"
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:17:12-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:17:15-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:17:15-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [5364f3e1-0297-4e26-ae38-e2e4b6c009ce] model deployment ID: []] "
}
2026-03-04T13:22:10-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:22:10-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [21d6dbef-52cb-4825-bfbe-f62c1bc86c73] model deployment ID: []] "
}
2026-03-04T13:22:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:22:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 4a6cfc38-ec89-4503-90e6-36a6253b07c3 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 388.96175000071526ms"
}
2026-03-04T13:22:45-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:22:46-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:22:48-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:22:48-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [f268474e-52c3-48af-96d8-142d8c6e23be] model deployment ID: []] "
}
2026-03-04T13:22:59-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:22:59-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [083dfa32-0628-4a01-91e5-db802e93b51e] model deployment ID: []] "
}
2026-03-04T13:23:17-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:23:17-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [4a02dd6b-ae9f-41c9-a9a9-b451eddca19c] model deployment ID: []] "
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 2d7862a1-3934-4f84-bd7d-0c008742e3ad at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 580.5127910077572ms"
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [stop]"
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[fetchCompletions] Request 217e8a45-fbc4-4fc3-a83a-c7d79f2d95c5 at <https://proxy.individual.githubcopilot.com/v1/engines/gpt-41-copilot/completions> finished with 200 status after 186.9057080000639ms"
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[streamChoices] solution 0 returned. finish reason: [null]"
}
2026-03-04T13:24:54-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:25:01-05:00 ERROR [editor] No entry in selection_history found for undo. This may correspond to a bug where undo does not update the selection. If this is occurring, please add details to https://github.com/zed-industries/zed/issues/22692
2026-03-04T13:25:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:25:02-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:25:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": true,
  "kind": "Normal",
  "status": "InProgress",
  "message": ""
}
2026-03-04T13:25:03-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification statusNotification:
{
  "busy": false,
  "kind": "Normal",
  "status": "Normal",
  "message": ""
}
2026-03-04T13:25:18-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[message 0 returned. finish reason: [stop]] "
}
2026-03-04T13:25:18-05:00 INFO  [lsp] Language server with id 3 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[request done: requestId: [9152e35d-22d9-4c2a-a87c-111824dbedf6] model deployment ID: []] "
}
2026-03-04T14:11:57-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T15:48:49-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T16:48:49-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T17:48:49-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T18:48:49-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T22:50:42-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-04T23:50:42-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T01:21:18-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T03:06:24-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T05:11:33-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T06:11:33-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T06:53:37-05:00 INFO  [zed::reliability] hang detected, trace file saved at: /Users/seanlim/Library/Application Support/Zed/hang_traces/hang-2026-03-05_06-53-35.miniprof
2026-03-05T07:11:33-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T08:11:33-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T09:11:33-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T10:11:34-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T11:56:18-05:00 INFO  [auto_update] Auto Update: checking for updates
2026-03-05T15:58:24-05:00 ERROR [gpui::app] timed out waiting on app_will_quit

```

</details>

### PR DESCRIPTION
**Pull request by MostlyKIGuess**
Switch python_env_kernel_specifications to a buffered stream (using buffer_unordered(4) and filter_map) to run discovery concurrently with a bounded parallelism and skip None results.

Closes #50988

Before you mark this PR as ready for review, make sure that you have:
- [x] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [x] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Release Notes:

- N/A

### CODE REVIEW

File: crates/repl/src/kernels/mod.rs [hunk 1]
```diff
@@ -503,11 +503,11 @@ pub fn python_env_kernel_specifications(
...
-        let mut kernel_specs: Vec<KernelSpecification> = futures::future::join_all(kernelspecs)
-            .await
-            .into_iter()
-            .flatten()
-            .collect();
+        let mut kernel_specs: Vec<KernelSpecification> = futures::stream::iter(kernelspecs)
+            .buffer_unordered(4)
+            .filter_map(|x| async move { x })
+            .collect::<Vec<_>>()
+            .await;
```
Comment (rgbkrk) [inline crates/repl/src/kernels/mod.rs:510]: Way better, thank you.

**Review by rgbkrk — APPROVED** [review]
Brilliant.

It seems like we might want to persist this in the workspace database so we don't have to re-search each time or it's a matter of only adding ipykernel if they try to use that kernel. Food for thought for later.
