### PR TITLE
Fix case-only renaming of files in project panel

### LINKED ISSUE #5211: Case-Only File rename does not work
### Check for existing issues

- [X] Completed

### Describe the bug

https://user-images.githubusercontent.com/620553/192087767-441811e2-8192-453e-a071-2ef1361ef319.mov

### To reproduce

See video

### Expected behavior

It should rename correctly.

### Environment

Zed 0.54.1 – /Applications/Zed.app
macOS 10.15.7
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

_No response_

### PR DESCRIPTION
**Pull request by mrnugget**
This is a follow-up to #7768 but now also fixes #5211.

Explanation is relatively simple: case-only renames previously failed because while Zed would think that `foobar` and `FOOBAR` are different, the filesystem would give us an file-already-exists error when renaming.

So what we're doing here is to check whether we're on a case-insensitive filesystem and if so, we overwrite the old file.

Release Notes:

- Fixed case-only renaming of files in project panel. ([#5211](https://github.com/zed-industries/zed/issues/5211)).

Proof:

https://github.com/zed-industries/zed/assets/1185253/57d5063f-09d9-47b1-a2df-3d7edefca97d

### CODE REVIEW

File: crates/project/src/worktree.rs [hunk 1]
```diff
@@ -1301,9 +1310,29 @@ impl LocalWorktree {
...
         let abs_new_path = self.absolutize(&new_path);
         let fs = self.fs.clone();
+        let case_sensitive = self.fs_case_sensitive;
         let rename = cx.background_executor().spawn(async move {
-            fs.rename(&abs_old_path?, &abs_new_path?, Default::default())
-                .await
+            let abs_old_path = abs_old_path?;
+            let abs_new_path = abs_new_path?;
+
+            let abs_old_path_lower = abs_old_path.clone().to_str().map(|p| p.to_lowercase());
```
Comment (as-cii) [inline crates/project/src/worktree.rs:1318]: I think we don't need the `clone()` here:

```suggestion
            let abs_old_path_lower = abs_old_path.to_str().map(|p| p.to_lowercase());
```

File: crates/project/src/worktree.rs [hunk 2]
```diff
@@ -1301,9 +1310,29 @@ impl LocalWorktree {
...
+            let abs_new_path_lower = abs_old_path.clone().to_str().map(|p| p.to_lowercase());
```
Comment (as-cii) [inline crates/project/src/worktree.rs:1319]: I believe we should use the new path here instead:

```suggestion
            let abs_new_path_lower = abs_new_path.to_str().map(|p| p.to_lowercase());
```

**Review by as-cii — COMMENTED** [review]
Left a couple of comments but the approach sounds reasonable to me!
