### PR TITLE
Fix gutter hover breakpoint not updating when switching the tabs

### LINKED ISSUE #42073: Debug symbol doesn't disappear when switching tabs
### Summary

When hovering over the left side of the screen where the debug symbol appears, switch the tab, move the mouse away, and switch back to the tab we hovered, the symbol doesn't go away.

Steps to reproduce:
1. Hover for the debug symbol to appear

Image

2. Switch to another tab

Image

3. Move the mouse away

Image

4. Switch back to the original tab

Image

**Expected Behavior**: The debug symbol should've disappeared
**Actual Behavior**: The debug symbol doesn't disappear

This is a very minor bug and doesn't affect my workflow in any way, just thought I'd report it so you are aware.

### Zed Version and System Specs

Zed: v0.210.4 (Zed) 
OS: Linux Wayland arch unknown
Memory: 23.4 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA || 580.95.05

### PR DESCRIPTION
**Pull request by shaik-zeeshan**
Closes #42073

fixes hover breakpoint not disappearing from a tab when tabs are switched 

https://github.com/user-attachments/assets/43096d2a-cc5b-46c4-b903-5bc8c33305c5

Release Notes:

- N/A

### CODE REVIEW

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -22061,6 +22061,21 @@ impl Editor {
                     );
                 }
             });
+
+            if let Some(position_map) = self.last_position_map.clone() {
+                let points = window.mouse_position();
+                EditorElement::mouse_moved(
+                    self,
+                    &MouseMoveEvent {
+                        position: points,
```
Comment (MrSubidubi) [inline crates/editor/src/editor.rs]:
```suggestion
                EditorElement::mouse_moved(
                    self,
                    &MouseMoveEvent {
                        position: window.mouse_position(),
```

**Review by MrSubidubi — APPROVED** [review]
Nice, this looks good. Thank you!
