### PR TITLE
Fix terminal key bindings

### LINKED ISSUE #12556: Terminal key bindings do not work as expected
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The integrated terminal in Zed seems to rewrite the custom key bindings I have in my zsh config:
```zsh
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
```

### Environment

Zed: v0.139.0 (Zed Nightly 94c3101fb0ecbaf5f322dd7b94c239f8a66a5a5f)
OS: Linux 1.0.0
Memory: 30.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Konsole:

[Screencast_20240601_113614.webm](https://github.com/zed-industries/zed/assets/71973804/77857d37-4719-406b-b4bf-6c8bba366bfa)

Zed:

[Screencast_20240601_113739.webm](https://github.com/zed-industries/zed/assets/71973804/94ab7bbb-8242-4971-8c69-d038248ff8fc)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by apricotbucket28**
Fixes https://github.com/zed-industries/zed/issues/12556

Only changed the keymap on Linux since I'm not sure if the behaviour is correct on macOS

Release Notes:

- N/A

### CODE REVIEW

File: crates/terminal/src/mappings/keys.rs [hunk 1]
```diff
@@ -54,6 +54,7 @@ pub fn to_esc_str(keystroke: &Keystroke, mode: &TermMode, alt_is_meta: bool) ->
         ("backspace", AlacModifiers::None) => Some("\x7f".to_string()),
         //Interesting escape codes
         ("tab", AlacModifiers::Shift) => Some("\x1b[Z".to_string()),
+        ("backspace", AlacModifiers::Ctrl) => Some("\x08".to_string()),
```
Comment (apricotbucket28) [inline crates/terminal/src/mappings/keys.rs:57]: I used the Control-H key here since that's what Konsole and Gnome Terminal send when doing Ctrl+Backspace. VSCode sends `\x1b\x7f` like when doing Alt+Backspace.

Comment (mikayla-maki) [reply crates/terminal/src/mappings/keys.rs:57]: I think I'd prefer if we didn't make this change, everything else being equal.

Comment (apricotbucket28) [reply crates/terminal/src/mappings/keys.rs:57]: This seems to be the expected behaviour: https://github.com/alacritty/alacritty/issues/7100#issuecomment-1645035896
Asides, if the keymap overwrites the keybinding (like in macOS, where I did not change it) it takes precedence over the code here.

Comment (mikayla-maki) [reply crates/terminal/src/mappings/keys.rs:57]: Oh excellent. We should stick to alacritty then. Thanks for clarifying :)
