### PR TITLE
Fix a Wayland-related graphic bug for the status bar

### LINKED ISSUE #46008: Visible gap between editor pane and footer
### Reproduction steps

1. Start Zed

### Current vs. Expected behavior

Image

### Zed version and system specs

Zed: 0.217.3
OS: Linux (Fedora 43 w/ KDE Plasma 6.5.4) 

Image

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by pauldipietro**
Release Notes:

- Address a scenario where scaling in Wayland can cause a 1px gap above the status bar

Closes #46008

### CODE REVIEW

**Comment by pauldipietro** [comment]
@cla-bot check

File: crates/workspace/src/status_bar.rs [hunk 1]
```diff
@@ -56,6 +56,15 @@ impl Render for StatusBar {
                     })
                     // This border is to avoid a transparent gap in the rounded corners
                     .mb(px(-1.))
+                    // Running on Wayland and using some scaling levels other than 100% causes a
+                    // 1px gap above the status bar; adding a margin avoids this.
```
Comment (probably-neb) [inline crates/workspace/src/status_bar.rs:60]: This seems like a quite hacky solution. Are we sure there isn't something better we could be doing to fix this? Are we sure it is Wayland specific?
> some scaling levels other than 100%

The code seems to activate this for all scaling levels other than 1.0. Are we sure this is an issue at _every_ scaling factor other than 1.0?

**Review by probably-neb — CHANGES_REQUESTED** [review]

File: crates/workspace/src/status_bar.rs (hunk 1 above)
Comment (pauldipietro) [reply crates/workspace/src/status_bar.rs]: I'm not the person who wrote the surrounding implementation, so no, I don't know if there's something somewhere else in the code base that could provide a cleaner fix, but my presumption has been that it's something upstream unless if there's a specific handler somewhere for Wayland rendering. As I stated on the original report, I tried it against both X11 and Wayland and didn't notice the issue on the former when scaling to different values.

As to whether we be sure that it's an issue at every scaling factor? Sure, if we test it manually against every single value. I shared screenshots of some common ones that could be set as a default by Plasma based on the monitor size. If you want to go more granular, you could also test it against thirds e.g. 1.33x or 1.66x, but I don't think there's any realistic scenario where a user will do anything beyond that.

To be candid I've more or less moved on from this PR given how long it's been open, so I'll leave it to your judgement as to whether or not you want to do anything with it.

Comment (probably-neb) [reply crates/workspace/src/status_bar.rs]: Ah ok, I clearly forgot to look at the issue when reviewing the PR. Thanks for the explanation and sorry about the long time to review!
Going to merge this

**Review by probably-neb — APPROVED** [review]
