### PR TITLE
Switch LSP prompts to use a non-blocking toast

### LINKED ISSUE #8229: ESLint error in my React Native (javascript) project
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I save / change my zed settings (~/.config/zed) I get this ESLint error, I'm not even sure how to disable the linter or attempt a fix at this issue myself.

ESLint: prettier.resolveConfig.sync is not a function Occurred while linting /Users/macbook/Desktop/gps/gps/index.js:5 Rule: "prettier/prettier". Please see the 'ESLint' output channel for details.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-23T00:51:22+02:00 [INFO] Initializing default prettier with plugins {}
2024-02-23T00:51:22+02:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-23T00:51:22+02:00 [INFO] 13 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/App.tsx",
  "state": 3
}
2024-02-23T00:51:22+02:00 [INFO] 13 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/app/screens/Login.js",
  "state": 3
}
2024-02-23T00:51:23+02:00 [INFO] 13 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/index.js",
  "state": 3
}
2024-02-23T00:51:31+02:00 [INFO] reload git repository ".git"
2024-02-23T00:51:31+02:00 [INFO] reload git repository ".git"
2024-02-23T00:52:31+02:00 [INFO] reload git repository ".git"
2024-02-23T00:52:31+02:00 [INFO] reload git repository ".git"
2024-02-23T00:52:58+02:00 [INFO] 13 unhandled notification eslint/showOutputChannel:
[
  null
]
2024-02-23T00:52:59+02:00 [INFO] 13 unhandled notification eslint/showOutputChannel:
[
  null
]
2024-02-23T00:52:59+02:00 [INFO] 13 unhandled notification eslint/showOutputChannel:
[
  null
]
2024-02-23T00:53:14+02:00 [INFO] stopping language server tailwindcss-language-server
2024-02-23T00:53:14+02:00 [INFO] stopping language server typescript-language-server
2024-02-23T00:53:14+02:00 [INFO] stopping language server eslint
2024-02-23T00:53:14+02:00 [INFO] Initializing default prettier with plugins {}
2024-02-23T00:53:14+02:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-23T00:53:14+02:00 [INFO] starting language server "typescript-language-server", path: "/Users/macbook/Desktop/gps/gps", id: 15
2024-02-23T00:53:14+02:00 [INFO] starting language server "eslint", path: "/Users/macbook/Desktop/gps/gps", id: 16
2024-02-23T00:53:14+02:00 [INFO] starting language server "tailwindcss-language-server", path: "/Users/macbook/Desktop/gps/gps", id: 17
2024-02-23T00:53:14+02:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-23T00:53:14+02:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-23T00:53:14+02:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-23T00:53:15+02:00 [INFO] 16 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v18.15.0"
}
2024-02-23T00:53:15+02:00 [INFO] 15 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Using Typescript version (user-setting) 5.2.2 from path \"/Users/macbook/Desktop/gps/gps/node_modules/typescript/lib/tsserver.js\""
}
2024-02-23T00:53:15+02:00 [INFO] 15 unhandled notification $/typescriptVersion:
{
  "version": "5.2.2",
  "source": "user-setting"
}
2024-02-23T00:53:21+02:00 [INFO] 16 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/App.tsx",
  "state": 3
}
2024-02-23T00:53:22+02:00 [INFO] 16 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/app/screens/Login.js",
  "state": 3
}
2024-02-23T00:53:22+02:00 [INFO] 16 unhandled notification eslint/status:
{
  "uri": "file:///Users/macbook/Desktop/gps/gps/index.js",
  "state": 3
}

### LINKED ISSUE #8255: Allow me to disable popup warning
### Check for existing issues

- [X] Completed

### Describe the feature

CleanShot 2024-02-23 at 10 04 49

Not sure if this is a bug or expected behaviour. I copy+pasted some faulty code into my prisma.schema.

With each key stroke, I get a popup warning that I should switch the language server, making it hard to fix the code.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by mikayla-maki**
This fixes a major degradation in usability that some users ran into.

Fixes https://github.com/zed-industries/zed/issues/8255 
Fixes https://github.com/zed-industries/zed/issues/8229

Release Notes:

- Switch from using platform prompts to toasts for LSP prompts. ([8255](https://github.com/zed-industries/zed/issues/8255), [8229](https://github.com/zed-industries/zed/issues/8229))

Screenshot 2024-02-23 at 2 40 05 PM

### CODE REVIEW

File: crates/project/src/project.rs [hunk 1]
```diff
@@ -3160,8 +3162,10 @@ impl Project {
         language_server
             .on_request::<lsp::request::ShowMessageRequest, _, _>({
                 let this = this.clone();
+                let name = name.to_string();
                 move |params, mut cx| {
                     let this = this.clone();
+                    let name = name.to_string();
```
Comment (mikayla-maki) [inline crates/project/src/project.rs:3168]: I'd rather not do this double-capture-clone dance, but I was unable to use the server ID to grab the LSP from the project.

File: crates/ui/src/components/label/label_like.rs [hunk 2]
```diff
@@ -97,6 +98,7 @@ impl RenderOnce for LabelLike {
                 )
             })
             .map(|this| match self.size {
+                LabelSize::Large => this.text_ui_lg(),
```
Comment (mikayla-maki) [inline crates/ui/src/components/label/label_like.rs:101]: I added this to make the title larger, but then decided not to use it. Regardless, it seemed useful and I already fixed the documentation so I thought I'd leave it :)
