### PR TITLE
collab: Reconnect to channel notes

### LINKED ISSUE #31758: Collab: Channel notes do not reconnect
### Summary

If you connection to collab servers becomes unavailable, channel notes do not automatically reconnect. Use must manually re-open all channel notes buffers.

### Description

Steps to reproduce:
1. Open the channel notes for collab channel
2. Turn off your wifi
3. Watch your log spammed with:
  ```
  ERROR [channel] not connected
  ERROR [channel] not connected
  INFO  [client] set status on client 85554: Reauthenticating
  INFO  [client] set status on client 85554: Reconnecting
  INFO  [client] set status on client 85554: ConnectionError
  ERROR [client] failed to connect: client auth and connect
  INFO  [client] set status on client 85554: ReconnectionError { next_reconnection: Instant { tv_sec: 684689, tv_nsec: 836337458 } }
  ERROR [channel] not connected
  ERROR [channel] not connected
  INFO  [client] set status on cli
  ```
4. After 30seconds the channel will show disconnected and the following will be logged 
```
INFO  [channel::channel_buffer] channel buffer 22803 disconnected
```
5. Turn your wifi back and watch collab reconnect.

Expected Behavior: Channel notes will reconnect
Actual Behavior: Channel notes stay disconnected.

Workaround: User must manually re-find the channel in the channel tree, and select "Open Channel Notes" to reconnect. Repeat for each open channel notes buffer.

Note: Re-joining the voice channel is insufficient. You must explicitly click the notes from the collab sidebar to reconnect a buffer.

### Zed Version and System Specs

Zed: v0.190.0 (Zed Nightly a23ee61a4b55ace5983b5c03b2edfe77b20013d8) 
OS: macOS 15.4.1
Memory: 64 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by osiewicz**
Closes #31758

Release Notes:

- Fixed channel notes not getting re-connected when a connection to Zed servers is restored.

### CODE REVIEW

File: crates/channel/src/channel_store.rs [hunk 1]
```diff
@@ -19,7 +19,7 @@ use settings::Settings;
 use std::{mem, sync::Arc, time::Duration};
 use util::{ResultExt, maybe};
 
-pub const RECONNECT_TIMEOUT: Duration = Duration::from_secs(30);
+pub const RECONNECT_TIMEOUT: Duration = Duration::from_secs(1);
```
Comment (osiewicz) [inline crates/channel/src/channel_store.rs]: Whoops. This is here just because I wanted to get into disconnected state quicker, but we should definitely not go forward with it.
```suggestion
pub const RECONNECT_TIMEOUT: Duration = Duration::from_secs(30);
```
