### PR TITLE
Fix a bug where the IME pre-edit would desync from Zed

### LINKED ISSUE #11829: IME pre-edit is unusable on macOS
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When entering text via an IME, there is a *pre-edit* buffer where the input is held until the user has chosen the right conversion and committed the input to the application. It is possible to navigate within this buffer with the shift and arrow keys to select a subsection of it and convert this selection independently of the rest of the string. However Zed intercepts those keys and moves the cursor in the underlying file buffer in addition to sending them to the IME. As a result IME input lands in a completely different position in the file than where the IME was originally invoked.

How to reproduce (If you are not familiar, try this first in TextEdit to see how it *should* work):
1. Enable the "Japanese - Romaji" input source (formerly also known as "Kotoeri") in macOS keyboard settings, in the Input Sources tab; default settings should suffice
2. Head to Zed, open a buffer with some text and navigate somewhere in the middle of it and activate the Japanese input source
3. Type "shinnkannsenn", you should see a candidate string like "しんかんせん"
4. Press space to get an initial conversion attempt, turning the candidate string into "新幹線"
5. Press shift+left a few times and you should see a highlight under a subsection of the candidate string, beginning from the start of the string with the other end moving as you press shift+arrows
6. Press up/down or tab to cycle through alternative conversions of the highlighted region, or left/right to move the highlight between the splits created with shift+left/right (try to change the first symbol to 心 for example)
7. Commit the final result with enter - note that the cursor has moved to a different position in the buffer and the IME input got inserted at the new position rather than where it was at the start of step 3.

If you want to back out while testing you can either discard the current input by pressing escape a few times or switch back to your usual keyboard input source, which commits the current candidate string.

(This can be replicated with the same steps when using a Chinese IME and probably with any other IME that makes nontrivial use of pre-edit.)

### Environment

Zed: v0.135.1 (Zed Preview)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by mikayla-maki**
fixes #11829 

In https://github.com/zed-industries/zed/pull/7494, we introduced IME event buffering, so that we could preempt the IME with a keystroke event in some cases. However, this caused a desynchronization bug in long multi-step IME composition, such as the pre-edit used in the Japanese Romaji keyboard (and other languages).  We found that this was due to the IME issuing actions, and then immediately querying the editor's state before we had applied those actions. Therefore, this PR removes IME action buffering.

We have tested all of the cases in the `handle_key_event` documentation and added a few of our own.

Release Notes:

- Fixed an issue where the IME pre-edit could desynchronize from the editor on macOS ([#11829](https://github.com/zed-industries/zed/pull/12651))

### CODE REVIEW

File: crates/gpui/src/platform/mac/window.rs [hunk 1]
```diff
@@ -1190,14 +1191,22 @@ extern "C" fn handle_key_down(this: &Object, _: Sel, native_event: id) {
 }
 
 // Things to test if you're modifying this method:
+//  U.S. layout:
+//   - The IME consumes characters like 'j' and 'k', which makes paging through `less` in
+//     the terminal behave incorrectly by default. This behavior should be patched by our
+//     IME integration
 //  Brazilian layout:
-//   - `" space` should type a quote
+//   - `" space` should create an unmarked quote (note: use_autoclose may type an extra ")
```
Comment (ConradIrwin) [inline crates/gpui/src/platform/mac/window.rs:1199]: @mikayla-maki to clarify you mean it might type `""` - or is the bug where it types `""""` back again?

Comment (mikayla-maki) [reply crates/gpui/src/platform/mac/window.rs:1199]: To be very clear: Typing `" space` may result in an unmarked `""`. How about updating the comment to be:

`// (note: quotes may be autoclosed by your GPUI application. This may result in the text `""`, rather than the expected `"`)`

Comment (mikayla-maki) [reply crates/gpui/src/platform/mac/window.rs:1199]: Adding this comment is not strictly necessary but given the finickiness of IME code, I thought it might be helpful. But reading over that comment, it might be simpler to just remove it.
