### PR TITLE
language_models: Clear cached credentials when OpenAI and OpenAI Compatible provider `api_url` change

### LINKED ISSUE #37093: Security: OpenAI API key is sent to arbitrary OpenAI-compatible endpoints
### Summary

When a user adds an openai api compatible server to their language_models settings, as per the [docs](https://zed.dev/docs/ai/llm-providers#openai-api-compatible), an existing openai api key that was previously set for interacting with platform.openai.com will be sent to the custom openai api compatible server.

### Description
No mechanism is documented for adding api keys to zed that are intended for openai api compatible servers other than modifying the key configured for platform.openai.com

Steps to reproduce:
1. In Zed, set your OpenAI key.

2. Configure an OpenAI-compatible provider pointing at http://localhost:8000/v1 (or any custom server).

3. Make a request.

4. Observe on the server that Authorization: Bearer <your OpenAI key> is received.

**Expected Behavior**: Zed should not send the OpenAI key to non-OpenAI origins by default, or should allow a different key per endpoint.
**Actual Behavior**: The OpenAI key is forwarded to any configured OpenAI-compatible server.

### Zed Version and System Specs

Zed: v0.202.0 (Zed Dev 1b91f3de41bf86c1792d9bd4a8677a222ca4d903) 
OS: Linux Wayland fedora 42
Memory: 125.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA || 575.64.05

### PR DESCRIPTION
**Pull request by imumesh18**
Closes #37093

Also check this: #37099.

So currently in zed for both OpenAI and OpenAI Compatible provider when the url is changed from settings the api_key stored in the provider state is not cleared and it is still used. But if you restart zed the api_key is cleared. Currently zed uses the api_url to store and fetch the api key from credential provider. The behaviour is not changed overall, it's just that we have made it consistent it with the zed restart logic where it re-authenticates and fetches the api_key again. I have attached the video below to show case before and after of this.

So all in all the problem was we were not re-authenticating the in case api_url change while zed is still running. Now we trigger a re-authentication and clear the state in case authentication fails.
 
OpenAI Compatible Provider:

| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/324d2707-ea72-4119-8981-6b596a9f40a3" /> | <video src="https://github.com/user-attachments/assets/cc7fdb73-8975-4aaf-a642-809bb03ce319" /> | 

OpenAI Provider:

| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/a1c07d1b-1909-4b49-b33c-fc05123e92e7" /> | <video src="https://github.com/user-attachments/assets/d78aeccd-5cd3-4d0c-8b9f-6f98e499d7c8" /> | 

Release Notes:

- Fixed OpenAI and OpenAI Compatible provide API keys being persisted when changing the API URL setting. Authentication is now properly revalidated when settings change.

### CODE REVIEW

File: crates/language_models/src/provider/open_ai.rs [hunk 1]
```diff
@@ -136,14 +132,50 @@ impl State {
...
+            _subscription: cx.observe_global::<SettingsStore>(|this: &mut State, cx| {
+                let current_api_url = AllLanguageModelSettings::get_global(cx)
+                    .openai
+                    .api_url
+                    .clone();
+
+                if this.last_api_url != current_api_url {
+                    this.last_api_url = current_api_url;
+                    this.api_key = None;
+                    let spawn_task = cx.spawn(async move |handle, cx| {
```
Comment (benbrandt) [inline crates/language_models/src/provider/open_ai.rs]: Do we want to check if this was from the env before? And in this case not do this update?
Basically we only do the reset if it didn't come from the env?

File: crates/language_models/src/provider/open_ai_compatible.rs [hunk 2]
```diff
@@ -160,11 +164,27 @@ impl OpenAiCompatibleLanguageModelProvider {
...
-                    this.settings = settings.clone();
+                if &this.settings != &settings {
+                    if settings.api_url != this.settings.api_url {
+                        let spawn_task = cx.spawn(async move |handle, cx| {
+                            if let Ok(task) = handle.update(cx, |this, cx| this.get_api_key(cx)) {
+                                if let Err(_) = task.await {
+                                    handle
+                                        .update(cx, |this, _| {
+                                            this.api_key = None;
+                                            this.api_key_from_env = false;
```
Comment (benbrandt) [inline crates/language_models/src/provider/open_ai_compatible.rs:178]: Same note here

**Review by benbrandt — CHANGES_REQUESTED** [review]

File: crates/language_models/src/provider/open_ai.rs (hunk 1 above)
Comment (imumesh18) [reply crates/language_models/src/provider/open_ai.rs]: Oh yes, makes sense. made the changes for it. Thanks.

File: crates/language_models/src/provider/open_ai_compatible.rs (hunk 2 above)
Comment (imumesh18) [reply crates/language_models/src/provider/open_ai_compatible.rs:178]: Done

**Review by benbrandt — APPROVED** [review]
Thanks!
