### PR TITLE
terminal: Fix terminal cloning on WSL

### LINKED ISSUE #39428: Windows Beta: Remote terminal cannot be split into multiple panes
### Summary

When using the remote terminal, the split feature does not work in any direction. Neither horizontal (top/bottom) nor vertical (left/right) splits are available.

### Description

Steps to trigger the problem:
1. open wsl project
2. split terminal
3.

**Expected Behavior**:
**Actual Behavior**:

https://github.com/user-attachments/assets/cfab99d3-47cd-400d-9358-d07c481157c7

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly fb343a774391984f7837bcb15dd935d11660409d) 
OS: Windows 10.0.26220
Memory: 15.2 GiB
Architecture: x86_64
GPU: AMD Radeon 780M Graphics || AMD Corporation || 25.9.2 (25.10.25.15-250916a-419139E-AMD-Software-Adrenalin-Edition)

### PR DESCRIPTION
**Pull request by marcocondrache**
Should close #39428

The working directory of the `wsl.exe` program is set to a Linux path, which is invalid on the Windows side, causing the terminal to crash. The first spawn works because there is no active terminal view, allowing a new shell (which checks for the remote) to be created. I cannot explain why it works on SSH remote clients, but I may be missing something in the remote connection implementation.

I don't have a Windows machine to test this, so I would appreciate someone testing it. 🙏🏼

Release Notes:

- Fixed an issue where WSL terminals could not be splitted

### CODE REVIEW

File: crates/terminal/src/terminal.rs [hunk 1]
```diff
@@ -2131,14 +2131,9 @@ impl Terminal {
...
 
-    pub fn clone_builder(
-        &self,
-        cx: &App,
-        cwd: impl FnOnce() -> Option<PathBuf>,
-    ) -> Result<TerminalBuilder> {
-        let working_directory = self.working_directory().or_else(cwd);
+    pub fn clone_builder(&self, cx: &App, cwd: Option<PathBuf>) -> Result<TerminalBuilder> {
         TerminalBuilder::new(
-            working_directory,
```
Comment (Veykril) [inline crates/terminal/src/terminal.rs:2141]: We should keep this, we do want to prefer the current terminals working directory, its just a no-op (always `None` for remote terminals)

File: crates/project/src/terminals.rs [hunk 2]
```diff
@@ -404,31 +404,40 @@ impl Project {
...
-                    handles.remove(index);
-                    cx.notify();
-                }
-            })
-            .detach();
+        let local_path = if self.is_via_remote_server() {
+            None
+        } else {
+            cwd
+        };
```
Comment (Veykril) [inline crates/project/src/terminals.rs:413]: This I think is the wrong place to branch, we should check for whether the terminal we spawn is remote and apply the cwd correctly there. That is, if the terminal we spawn is a remote one, we want to use the cwd for the actual shell spawned in the remote, not for the `ssh`/`wsl` command

Comment (marcocondrache) [reply crates/project/src/terminals.rs:413]: @Veykril I branched here to stay consistent with the logic in `create_terminal_shell`, which also performs this branching when spawning the initial terminal.

https://github.com/zed-industries/zed/blob/4bd7ef8bad7e870fa9cdda369dedc6defd716ecc/crates/project/src/terminals.rs#L303

When creating a remote shell, we launch a local program (`ssh` or `wsl`), but its working directory (the one that is being passed to `TerminalBuilder`) applies only to the local process. The desired working directory for the remote shell itself needs to be set separately by the remote connection’s `build_command`, which is exactly how `create_terminal_shell` handles it

I'm happy to pair on this and discuss it further, I may be missing something

Comment (Veykril) [reply crates/project/src/terminals.rs:413]: Ah okay that makes sense

File: crates/terminal/src/terminal.rs (hunk 1 above)
Comment (marcocondrache) [reply crates/terminal/src/terminal.rs:2141]: Good catch, I wrongly pushed it

**Review by Veykril — APPROVED** [review]
Thanks!
