### PR TITLE
project_panel: Fix the confusing display when files or directories have the same name in a case-insensitive comparison

### LINKED ISSUE #18851: Project Panel confuses folders which only differ in case on Linux case sensitive filesystems
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I create two folders, but with different case, creating files in any folder, they all appear in one. 

obraz

But collapsing the folders, one or the other hides those files that are assigned to a specific folder

obraz

### Environment

Zed: v0.155.2 (Zed)
OS: ArchLinux
Memory: 64 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by wannacu**
- Closes #18851

Release Notes:

- Fixed directory name comparison on Linux not considering the case ([#18851](https://github.com/zed-industries/zed/issues/18851))

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -1942,9 +1942,8 @@ impl ProjectPanel {
                 }
                 entry_iter.advance();
             }
-
+            visible_worktree_entries.sort_by(|a, b| a.path.as_ref().cmp(b.path.as_ref()));
```
Comment (SomeoneToIgnore) [inline crates/project_panel/src/project_panel.rs:1945]: You cannot do that, as `propagate_git_statuses` expects certain file order, otherwise it panics.

File: crates/util/src/paths.rs [hunk 2]
```diff
@@ -382,6 +382,8 @@ pub fn compare_paths(
                 });
                 if !ordering.is_eq() {
                     return ordering;
+                } else if !component_a.as_os_str().cmp(component_b.as_os_str()).is_eq() {
```
Comment (SomeoneToIgnore) [inline crates/util/src/paths.rs:385]: This looks quite odd, it says that we do
```if !ordering.is_eq() && a != b {
  b.cmp(&a)
}
```

Isn't this `ordering.then_with(|| component_b.as_os_str().cmp(component_a.as_os_str()))`?

I find it also a bit confusing that we do `num_and_remainder_a.cmp(&num_and_remainder_b)` (a with b) comparison above, and (b with a) comparison here, changing the direction comparison.
Let's add a comment explaining this?

Also curious if we can avoid `.as_os_str()` call at all, as there's a `PartialOrd` on the `Ordering` itself?

**Review by SomeoneToIgnore — COMMENTED** [review]
So, the issue seems to be that we do not consider case when parsing into `NumericPrefixWithSuffix` and sorting them?

This comparison function is quite important as now can cause panics in Rust stdlib's collections, if implemented incorrectly, and Zed uses it for all file-related trees now.

So let's make it a bit more tidied up before merging.

File: crates/util/src/paths.rs (hunk 2 above)
Comment (SomeoneToIgnore) [reply crates/util/src/paths.rs:385]: Yeah, `.reverse()` + some small comment on top of the new comparison section seems to be the best option.

Comment (SomeoneToIgnore) [reply crates/util/src/paths.rs:385]: We can indeed place the thing into the `NumericPrefixWithSuffix`, but maybe not in every branch but below the match, so that it looks like `match .. {}.then_with(|| ...reverse())` + maybe have more tests there instead (?).

But that all does not matter that much, current place is also fine.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!
