### PR TITLE
Fix nushell local env detection by using direnv export

### LINKED ISSUE #8633: Direnv environments are not picked up with either fish or nushell used
### Current status
- Fish fix is merged
- Nushell fix is yet to be found
- Should we also ship fixes for stuff like elvish/oil/etc?

### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The current way to pick up the environment as used in 
https://github.com/zed-industries/zed/blob/dab886f4794e8d14cc82dc8e4906e93b78aa8fe8/crates/project/src/project.rs#L9366-L9385

does not work with neither fish nor nu shells. This is because direnv has some weird behaviour preventing it from evaluating. The dirty fix would be to force evaluation:
```rust
let additional_command = match PathBuf::from_str(shell.as_str()) {
    Ok(shell_path) if shell_path.file_name() == Some(OsStr::new("fish")) => {
        Some("eval (direnv export fish)")
    }
    Ok(shell_path) if shell_path.file_name() == Some(OsStr::new("nu")) => {
        Some("direnv export json | from json | default {} | load-env")
    }
    _ => None,
};

let command = match additional_command {
    Some(additional_command) => format!(
        "cd {dir:?}; {}; echo {marker}; /usr/bin/env -0; exit 0;",
        additional_command
    ),
    None => format!("cd {dir:?}; echo {marker}; /usr/bin/env -0; exit 0;"),
};
```
or something like that. 

### Environment

Zed: v0.125.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-02-29 at 22 00 12

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by WeetHet**
I don't intend fully on getting this merged, this is just an experiment on using `direnv` directly without relying on shell-specific behaviours. It works though, so this finally closes #8633
Release Notes:

- Fixed nushell not picking up `direnv` environments by directly interfacing with it using `direnv export`

### CODE REVIEW

File: crates/project/src/project.rs [hunk 1]
```diff
@@ -11730,6 +11769,7 @@ async fn load_shell_environment(dir: &Path) -> Result<HashMap<String, String>> {
 
     let output = smol::process::Command::new(&shell)
         .args(["-i", "-c", &command])
+        .envs(direnv_environment)
```
Comment (mrnugget) [inline crates/project/src/project.rs:11772]: Why do we have to spawn a login shell with that environment? Wouldn't the better approach be to collect both environments and then merge them?

File: crates/project/src/project.rs [hunk 2]
```diff
@@ -11692,7 +11692,46 @@ fn include_text(server: &lsp::LanguageServer) -> bool {
         .unwrap_or(false)
 }
 
+async fn load_direnv_environment(dir: &Path) -> Result<Option<HashMap<String, String>>> {
+    let direnv_res = smol::process::Command::new("direnv")
```
Comment (mrnugget) [inline crates/project/src/project.rs:11696]: Hmmm, what I don't like about this approach is that we always try to run direnv, even though it might not be installed. It's not a big deal from a performance perspective or anything, but I think checking in `PATH` whether direnv exists first is the better approach.

**Review by mrnugget — COMMENTED** [review]
As discussed on Discord: I'd love to rethink how we manage environment variables on projects, including runnables, direnv, etc.

Need to think about this some more before deciding whether to merge this or not. I do appreciate the PR in any case though!

File: crates/project/src/project.rs (hunk 1 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11772]: The shell does it for us, so I'm basically leveraging it's infrastructure to help us not do additional work. It also has some other upsides, imagine if someone uses direnv to install some other local environment tool, well, now we support that, very specific usecase too

Comment (mrnugget) [reply crates/project/src/project.rs:11772]: Yeah, it does, but is it correct? Technically you only get that `direnv` environment once you're inside the directory. Now we set it before you get to that directory and then `cd` into it. Doesn't that have the potential to mess up some other shell hooks?

File: crates/project/src/project.rs (hunk 2 above)
Comment (mrnugget) [reply crates/project/src/project.rs:11696]: So `smol::process::Command::new` returns `ErrorKind::NotFound` _before_ it creates a process? Or does it create the process and returns the error from `exec`?

Comment (WeetHet) [reply crates/project/src/project.rs:11696]: That's a hard question and the answer is: I don't know... But I also kinda don't know about any other cross platform way to check if program is in PATH so I'd say that it's probably fine, as spawning processes (not shells) is pretty cheap overall

File: crates/project/src/project.rs (hunk 1 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11772]: If you have multiple shell hooks, I don't think their order is really determined anyways, so I think this is just equivalent to direnv executing first. As far as I know, it won't mess itself up if you already have the environment set before the `cd`, and anything else would've probably executed after it in some case anyways. The shell behaviours are sometimes strange though, so I can't guarantee that this is correct. Can we maybe try doing it and waiting for any potential bug reports, or adding this under an opt-in setting?

File: crates/project/src/project.rs (hunk 2 above)
Comment (mrnugget) [reply crates/project/src/project.rs:11696]: There's this: https://crates.io/crates/which We already use that to check for language server binaries in the environment returned from this function here.

File: crates/project/src/project.rs (hunk 1 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11780]: I've added a setting for that, defaulting to the old behaviour. I think that should resolve this issue

File: crates/project/src/project.rs (hunk 2 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11699]: Oh, we already have it as a dependency? I didn't know about that, so I've avoided using it, sorry

Comment (WeetHet) [reply crates/project/src/project.rs]: Okay, I've added a check

File: crates/project/src/project.rs [hunk 3]
```diff
@@ -11692,7 +11695,45 @@ fn include_text(server: &lsp::LanguageServer) -> bool {
...
+    ))
+}
+
+async fn load_shell_environment(
+    dir: &Path,
+    load_direnv: &DirenvSettings,
+) -> Result<HashMap<String, String>> {
+    // Start by loading the direnv environment
+    let direnv_environment = match load_direnv {
+        DirenvSettings::ShellHook => None,
```
Comment (mrnugget) [inline crates/project/src/project.rs:11732]: It will get loaded anyways, right? By `cd`ing into the directory. As in: I think the setting suggests an either-or decision, when it fact it's more that `ShellHook` is the default and `direct` is an additional thing, no?

File: crates/project/src/project.rs [hunk 4]
```diff
@@ -11466,19 +11467,21 @@ impl ProjectLspAdapterDelegate {
...
             fs: project.fs.clone(),
             http_client: project.client.http_client(),
             language_registry: project.languages.clone(),
             shell_env: Default::default(),
+            load_direnv,
         })
     }
 
-    async fn load_shell_env(&self) {
+    async fn load_shell_env(&self, load_direnv: &DirenvSettings) {
```
Comment (mrnugget) [inline crates/project/src/project.rs:11482]: Why pass this in? Can't `load_shell_env` access `self` itself?

**Review by mrnugget — COMMENTED** [review]
Left some comments. I'm not sure about that additional setting. I think it might be more confusing than helping. Not sure yet how to improve it.

File: crates/project/src/project.rs (hunk 3 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11732]: If the direct option is selected, then when the shell hook is invoked, direnv would do nothing because it adds a marker environment variable to indicate that is has been activated

File: crates/project/src/project.rs (hunk 4 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11482]: Yeah, sorry for that, I'll fix it in a moment

File: assets/settings/default.json [hunk 5]
```diff
@@ -539,6 +539,12 @@
       // "delay_ms": 600
     }
   },
+  // Configuration for how direnv configuration should be loaded. May take 2 values:
+  // 1. Load direnv configuration through the shell hook
+  //      "direnv": "shell_hook"
+  // 2. Load direnv configuration using `direnv export json` directly
+  //      "direnv": "direct"
```
Comment (mrnugget) [inline assets/settings/default.json:546]: Can you add an explanation for why you would want to use one over the other?

File: crates/project/src/project.rs [hunk 6]
```diff
@@ -11692,7 +11695,45 @@ fn include_text(server: &lsp::LanguageServer) -> bool {
...
+    Ok(Some(
+        serde_json::from_str(&output).context("failed to parse direnv output")?,
+    ))
+}
+
+async fn load_shell_environment(
+    dir: &Path,
+    load_direnv: &DirenvSettings,
+) -> Result<HashMap<String, String>> {
+    // Start by loading the direnv environment
```
Comment (mrnugget) [inline crates/project/src/project.rs:11730]:
```suggestion
```

File: crates/project/src/project.rs (hunk 3 above)
Comment (mrnugget) [reply crates/project/src/project.rs:11732]: There's a comment on line 11744 — can you update that to include this bit here?

File: assets/settings/default.json (hunk 5 above)
Comment (mrnugget) [reply assets/settings/default.json:546]: And can you add this to `docs/src/configuring-zed.md`?

**Review by mrnugget — COMMENTED** [review]
Some more comments! I think the change is minimal enough so that we can still refactor it in the future when/if we change the way we handle environments works.

File: crates/project/src/project.rs (hunk 3 above)
Comment (WeetHet) [reply crates/project/src/project.rs:11732]: Sure!

File: assets/settings/default.json (hunk 5 above)
Comment (WeetHet) [reply assets/settings/default.json]: Yeah, sure, it turned out a bit clumsy in my opinion, so if you have any tips on improving it I would appreciate that

File: docs/src/configuring-zed.md [hunk 7]
```diff
@@ -180,6 +180,22 @@ You can also set other OpenType features, like setting `cv01` to `7`:
 The `left_padding` and `right_padding` options define the relative width of the
 left and right padding of the central pane from the workspace when the centered layout mode is activated. Valid values range is from `0` to `0.4`.
 
+## Direnv Integration
+
+- Description: Settings for direnv integration.
```
Comment (mrnugget) [inline docs/src/configuring-zed.md:185]:
```suggestion
- Description: Settings for [direnv](https://direnv.net/) integration. Requires `direnv` to be installed. `direnv` integration currently only means that the environment variables set by a `direnv` configuration can be used to detect some language servers in `$PATH` instead of installing them.
```
