### PR TITLE
Hide block cursor text when the cursor is within a redacted range

### LINKED ISSUE #20696: redact_private_values: vim / block cursor exposes private values
### Summary

Steps to reproduce.

1. Enable `redact_private_values` and block cursors or vim mode in settings.
```json
{
  "redact_private_values": true,
  "cursor_shape": "block",
  //"vim_mode": false
}
```
2. Create a private file and open it in zed:
```sh
echo "FOO=BAR" > .env
zed . .env
```
3. Move the cursor and the private values bleed through the cursor.

### Environment

Zed: v0.163.0 (Zed Nightly 093c9cc87b052c4bdf2afc09a6d52e86eb9c7d3d)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-11-14 at 16 06 13

### PR DESCRIPTION
**Pull request by tacshi**
Closes [#ISSUE](https://github.com/zed-industries/zed/issues/20696)

Release Notes:

- Hide block cursor text when the cursor is within a redacted range

Screenshot:

image

### CODE REVIEW

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -1705,7 +1706,14 @@ impl EditorElement {
                     if block_width == Pixels::ZERO {
                         block_width = em_advance;
                     }
-                    let block_text = if let CursorShape::Block = selection.cursor_shape {
+                    // Don't show block cursor text if cursor is in a redacted range
```
Comment (SomeoneToIgnore) [inline crates/editor/src/element.rs]: Can we
* remove the useless comment that repeats the code
* move this after the `&&` so we do not have to iterate over ranges all time if the `CursorShape::Block = selection.cursor_shape` condition is false (maybe, turn it into `==` instead of patter matching too?)

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you.
