### PR TITLE
terminal: Prevent terminal cursor stretching by always using cell width

### LINKED ISSUE #8516: Terminal cursor "stretched" during shell script execution
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While a process is running in the Zed terminal, pressing the Tab key and then deleting the indentation causes the cursor to be stretched to the right of the terminal 1 cursor wide.

1. Open Zed Terminal
2. Start a process that will run for a while _(e.g. `sleep 10`)_.
3. Press the Tab key.
4. Press the Backspace key.
5. Notice that the cursor expands to the right of the terminal 1 cursor.

### Environment

Zed: v0.124.6 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16290753/ec722ae2-4c3c-4ff6-a6ec-87c94b5028ca

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by tacshi**
Closes https://github.com/zed-industries/zed/issues/8516

Release Notes:

- Prevent terminal cursor stretching by always using cell width.

### CODE REVIEW

File: crates/terminal_view/src/terminal_element.rs [hunk 1]
```diff
@@ -2333,4 +2332,18 @@ mod tests {
         assert_eq!(negative_filtered.first().unwrap().point.line, Line(-7));
         assert_eq!(negative_filtered.last().unwrap().point.line, Line(-4));
     }
+
+    #[test]
+    fn test_cursor_width_always_uses_cell_width() {
```
Comment (SomeoneToIgnore) [inline crates/terminal_view/src/terminal_element.rs]: What does this test check, exactly?

**Review by Veykril — CHANGES_REQUESTED** [review]
I don't think this is quite right, that will look funny for emojis and other non-standard cell characters. Let's do a check if the text fragment consists solely of whitespace instead, and if that is the case fall back to the cell width instead

**Review by Veykril — COMMENTED** [review]
As assumed this still breaks the cursor for bigger non whitespace glyphs 

Image

**Review by Veykril — APPROVED** [review]
Thanks!
