### PR TITLE
languages: Update vscode-eslint to 3.0.24 and fix ESLint 8-10 breaking cases

### LINKED ISSUE #29757: ESLint is a major version behind (broken with svelte, etc)
### Summary

The ESLint LSP server is at version 2.4.4  whilst there is 3.0.10, leading to the sveltekit template with eslint not working.

### Description

Steps to reproduce:
1. Install a normal version of zed
2. Create a sveltekit template with eslint using npx sv create

Expected Behavior: Works
Actual Behavior: Shows errors in all svelte files

Note: I have fixed it on my instance by simply deleting the contents of zed/languages/vscode-eslint-2.4.4/vscode-eslint and replacing them with what is currently in the vscode-eslint repository.

### Zed Version and System Specs

Zed: v0.184.0 (Zed Dev 107d8ca483276263362c23482612d1cadea81c71) 
OS: Windows 10.0.22635
Memory: 63.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### LINKED ISSUE #49387: ESLint 10 does not work
### Reproduction steps

Hey,
I've been waiting for the ESLint 10 update to fully support our monorepo setup (which uses multiple ESLint configuration files).

We've updated our project and can confirm that ESLint is working as intended from both the CLI and VS Code.

Zed, unfortunately, does not seem to work with ESLint 10 at all.
It doesn't report any ESLint issues, and the LSP logs aren't showing any errors, only successful code validations.
I've added the eslint-10 branch to my reproduction repository here:

https://github.com/dotMortis/zed-monorepo-eslint-issues/tree/eslint-10

You can follow the instructions in the README file.

### Current vs. Expected behavior

Current:
- does not report any eslint issues

Expexted:
- show all eslint issues

### Zed version and system specs

Zed: 0.223.3 (pacman zed package)
OS: Arch Linux x86_64
Kernel: Linux 6.18.9-arch1-2
Memory: 64GB
CPU: AMD Tyzen 9 9950x
GPU: Intel Arc B580

### Attach Zed log file

_No response_

### Relevant Zed settings

_No response_

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #29757
Closes #49387

This PR upgrades ESLint language server from `vscode-eslint 2.4.4` to upstream `microsoft/vscode-eslint 3.0.24`, and make the workspace configuration version-aware so ESLint 8, 9, and 10 take the correct config-mode path.

The key part is that the 3.x bump alone is not enough. This PR keeps Zed out of that path except where it is still actually needed. Rest heavy-lifting is done by eslint server itself.

Zed now only overrides ESLint settings in the two known broken cases:
  - ESLint 8.21-8.56 flat config: send `experimental.useFlatConfig = true`
  - ESLint 9 legacy config: send `useFlatConfig = false`
  
All other cases defer to `vscode-eslint 3.x`'s own config and working-directory discovery.

For testing, I created https://github.com/smitbarmase/eslint-repros, which contains a versioned ESLint repros covering root flat config, legacy config, and package-local monorepo cases across ESLint 8, 9, and 10. Here is compare between `zed/main`, a pure `vscode-eslint 3.x` upgrade and this branch with the config-mode fixes:

  ## zed main

  ```text
  eslint-v8_21-flat-root-single
  eslint-v8_56-flat-package-local-monorepo  -> breaks on main
  eslint-v8_56-flat-root-single
  eslint-v8_56-legacy-root-single
  eslint-v8_57-flat-package-local-monorepo  -> breaks on main
  eslint-v8_57-flat-root-single
  eslint-v8_57-legacy-root-single
  eslint-v9_0-flat-package-local-monorepo
  eslint-v9_0-flat-root-single
  eslint-v9_0-legacy-root-single            -> breaks on main
  eslint-v10_0-flat-package-local-monorepo
  eslint-v10_0-flat-root-single             -> breaks on main
  ```
  
  ## vscode-eslint 3.x upgrade

  ```text
  eslint-v8_21-flat-root-single
  eslint-v8_56-flat-package-local-monorepo  -> breaks on 3.x upgrade
  eslint-v8_56-flat-root-single
  eslint-v8_56-legacy-root-single
  eslint-v8_57-flat-package-local-monorepo
  eslint-v8_57-flat-root-single
  eslint-v8_57-legacy-root-single
  eslint-v9_0-flat-package-local-monorepo
  eslint-v9_0-flat-root-single
  eslint-v9_0-legacy-root-single            -> breaks on 3.x upgrade
  eslint-v10_0-flat-package-local-monorepo
  eslint-v10_0-flat-root-single             -> breaks on 3.x upgrade
  ```
  
  ## vscode-eslint 3.x upgrade + use flat config fixes

  ```text
  eslint-v8_21-flat-root-single
  eslint-v8_56-flat-package-local-monorepo
  eslint-v8_56-flat-root-single
  eslint-v8_56-legacy-root-single
  eslint-v8_57-flat-package-local-monorepo
  eslint-v8_57-flat-root-single
  eslint-v8_57-legacy-root-single
  eslint-v9_0-flat-package-local-monorepo
  eslint-v9_0-flat-root-single
  eslint-v9_0-legacy-root-single
  eslint-v10_0-flat-package-local-monorepo
  eslint-v10_0-flat-root-single
  ```
  
Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Release Notes:

- Fixed ESLint not reporting diagnostics in some cases for projects that use flat-config, legacy-config, and monorepo projects across ESLint 8, 9, and 10.

### CODE REVIEW

File: crates/languages/src/eslint.rs [hunk 1]
```diff
@@ -157,6 +168,39 @@ impl LspInstaller for EsLintLspAdapter {
...
+    fn apply_to(self, workspace_configuration: &mut Value) {
+        if let Some(use_flat_config) = self.use_flat_config
+            && let Some(workspace_configuration) = workspace_configuration.as_object_mut()
+        {
+            workspace_configuration.insert("useFlatConfig".to_string(), json!(use_flat_config));
+        }
+
+        if let Some(experimental_use_flat_config) = self.experimental_use_flat_config
+            && let Some(experimental) = workspace_configuration
+                .get_mut("experimental")
```
Comment (SomeoneToIgnore) [inline crates/languages/src/eslint.rs]: Should we also create the new field if it's not found?

File: crates/languages/src/eslint.rs [hunk 2]
```diff
@@ -272,6 +320,108 @@ impl LspAdapter for EsLintLspAdapter {
...
+fn ancestor_directories(worktree_root: &Path, requested_file: Option<&Path>) -> Vec<PathBuf> {
+    let start = requested_file
+        .filter(|file| file.starts_with(worktree_root))
+        .and_then(Path::parent)
+        .unwrap_or(worktree_root);
+
+    start
+        .ancestors()
+        .take_while(|dir| dir.starts_with(worktree_root))
+        .map(Path::to_path_buf)
```
Comment (SomeoneToIgnore) [inline crates/languages/src/eslint.rs]: Hm, wondering if it's possible to keep `&Path` as those supposedly have the same lifetime as both inputs?

File: crates/languages/src/eslint.rs [hunk 3]
```diff
@@ -174,9 +218,25 @@ impl LspAdapter for EsLintLspAdapter {
...
+            delegate.as_ref(),
+            worktree_root,
+            requested_file_path.as_deref(),
+        )
+        .await?;
+        let config_kind = find_eslint_config_kind(
+            worktree_root,
+            requested_file_path.as_deref(),
+            eslint_version.as_ref(),
+            |path| path.is_file(),
```
Comment (SomeoneToIgnore) [inline crates/languages/src/eslint.rs]: Wow, that's a bunch of blocking os methods off the bat.
I see that `RuffLspAdapter` is initialized with `fs`, would it make any sense to do here too instead?

**Review by SomeoneToIgnore — APPROVED** [review]
Nice improvement and very impressive test set overall!

Somewhat concerned by the fs-related comments of mine, but worst case that can be a TODO and a follow-up PR?
