### PR TITLE
linux: Make prompt detail selectable

### LINKED ISSUE #21305: [Linux] Cannot copy "About Zed" information
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Technically, any Zed Linux popovers seem to disallow copying, so I might have missed the issue.

But this particular popover is the most crucial, as for e.g. Nightly it contains a long SHA version in it.

Open the menu, under `Help` section select `About Zed`, a new popover opens:

image

Expected: can select and copy any text in it, same as in masOS modal
Actual: nothing but the button is interactive

I had to open a macOS version and copy over that SHA into the issue

### Environment

Zed Nightly 0.165.0 cacec06db66fe29252b0f24b08e53509812f32a6

Linux alpc 6.11.8-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 14 20:37:39 UTC 2024 x86_64 GNU/Linux

LSB Version:	n/a
Distributor ID:	Fedora
Description:	Fedora Linux 41 (Workstation Edition)
Release:	41
Codename:	n/a

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #21305

As Linux doesn’t have native prompts, Zed uses a custom GPU-based prompt, like the "About Zed" prompt. Currently, the detail in the prompt isn’t selectable.

This PR fixes that by using the editor's multi-line selectable functionality to make the detail selectable (and thus copyable). It achieves this by disabling editing and setting the cursor to transparent. The editor also does all the heavy lifting, like double-clicking to select a word or triple-clicking to select a line, like what user expects from selectable.

Before/After:

before

after

When detail is `None` or empty string:

none

Release Notes:

- N/A

### CODE REVIEW

File: crates/zed/src/zed/linux_prompts.rs [hunk 1]
```diff
@@ -28,10 +30,18 @@ pub fn fallback_prompt_renderer(
         |cx| FallbackPromptRenderer {
             _level: level,
             message: message.to_string(),
-            detail: detail.map(ToString::to_string),
             actions: actions.iter().map(ToString::to_string).collect(),
             focus: cx.focus_handle(),
             active_action_id: 0,
+            detail: detail.filter(|text| !text.is_empty()).map(|text| {
+                cx.new_view(|cx| {
+                    let mut editor = Editor::auto_height(3, cx);
```
Comment (mikayla-maki) [inline crates/zed/src/zed/linux_prompts.rs:38]: Rather than using an Editor, could we use a Markdown element? That's how we implement the selections in the hover popover: https://github.com/zed-industries/zed/blob/aca23da9714e0482be8bee1b56695ac3ff1d4cc6/crates/editor/src/hover_popover.rs#L779

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by 0xtimsb** [comment]
@mikayla-maki  Thank you! Updated it with Markdown. Above GIFs too.

**Comment by mikayla-maki** [comment]
Can you rebase on main? https://github.com/zed-industries/zed/pull/21497 is causing your CI to fail :)

**Comment by 0xtimsb** [comment]
Done.

**Comment by mikayla-maki** [comment]
Thank you!
