### PR TITLE
vim: Fix end of paragraph deletion when there's no blank lines

### LINKED ISSUE #29393: Vim - Bug with end of paragraph (`d}`) deletion
### Summary

When using the `d}` command, if there's no new line at the end of the buffer, the last character will be left behind. The same command, in vim, would delete all lines.

Steps to reproduce:

1. Create new file with `workspace: new file`
2. Write two lines of text, for example, `This is\ntwo lines`
3. Move the cursor to the first column of the first row, location `1:1` on the bottom right
4. Press `d}` to delete until the end of the paragraph
5. Confirm that the `s` from `lines` is not deleted

Expected Behavior: All lines are deleted, regardless of whether a new line exists at the end of the file
Actual Behavior: The last character is not deleted

### Screencast

<details>
<summary>Vim</summary>

https://github.com/user-attachments/assets/626ef7f5-8334-469d-9253-b9ecde26f160
</details>

<details>
<summary>Zed</summary>

https://github.com/user-attachments/assets/bfafd6a3-ac7e-46ed-9628-e3adc1897496
</details>

### Zed Version and System Specs

Zed: v0.183.10 (Zed) 
OS: macOS 15.3.2
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by dinocosta**
This Pull Request attempts to fix an issue where using `d}` in vim mode would not delete all characters in case there's no blank lines at the end of the buffer.

When calculating the end point for this motion, if there's no blank lines at the end of the buffer, Zed was calculating it to be the last character in the last line. However, if there's a newline at the end of the buffer, it calculates the end point to be the point at the right of the last character.

Here's an example, for the following buffer contents:

```
Hello!
Hello!
```

If the `d}` command is run at `(0, 0)`, the end point will be set to `(1, 5)`. However, fi the same command is run for this buffer instead:

```
Hello!
Hello!

```

The end point will be set to `(1, 6)`, there's a 1 unit difference in the column, which leads to all characters actually being deleted.

Closes #29393 

Release Notes:

- Fixed deleting to the end of paragraph when there's no blank lines

### CODE REVIEW

File: crates/vim/src/motion.rs [hunk 1]
```diff
@@ -904,10 +904,22 @@ impl Motion {
...
+                // on a buffer with no newlines at the end. In that case, we
+                // want to extend the point's column 1 position to the right,
+                // ensuring that all characters are deleted.
+                if display_point.column() != 0 {
+                    display_point =
+                        DisplayPoint::new(display_point.row(), display_point.column() + 1);
+                }
+
+                (display_point, SelectionGoal::None)
+            }
```
Comment (dinocosta) [inline crates/vim/src/motion.rs:922]: @ConradIrwin I'm not sure if this the best place to actually fix this issue, so I'd love your feedback here 🔍

I believe there's multiple places where this could be handled:

- `vim::motion::Motion::range` - It seems there's already some cases handled in that method so I tried to avoid adding it here to avoid making that method more complex
- `vim::motion::Motion::move_point` - This is where I added the fix, as this seems to be the function where Zed actually determined the end point for the motion.
- `editor::movement::end_of_paragraph` - I pondered adding the fix here, but since this issue seems to be Vim-specific it kind of feels like this function should not be touched. As if there's actually only two lines in the buffer, the end of paragraph actually makes sense to be the point for the last character in the last line?

Let me know what you think! If you prefer, I can also schedule some pairing time, thanks! 🙇

**Comment by dinocosta** [comment]
Here's a quick screen capture showing the fix in action 📹 

https://github.com/user-attachments/assets/057ac592-5105-4b36-9c17-3e3e9c5e468d

File: crates/vim/src/motion.rs (hunk 1 above)
Comment (ConradIrwin) [reply crates/vim/src/motion.rs:922]: Hmm.. I think `range` is probably the right fix, as using `}` to go to the end seems to work alright today.

That said, the tests will probably catch mistakes, so where-ever is ok :D.

**Comment by ConradIrwin** [comment]
Looks great, thank you!

`+ 1` is not safe in Zed, as the columns are "number of utf-8 encoded bytes since the start of the line", and if you have a multibyte character in the last position, this will panic (because rust is very strict about ensuring strings are valid utf-8). I fixed this by using `movement::saturating_right`, but we could also have used `clip_point` to move the new index to a valid utf-8 offset.

**Comment by dinocosta** [comment]
> Looks great, thank you!
> 
> `+ 1` is not safe in Zed, as the columns are "number of utf-8 encoded bytes since the start of the line", and if you have a multibyte character in the last position, this will panic (because rust is very strict about ensuring strings are valid utf-8). I fixed this by using `movement::saturating_right`, but we could also have used `clip_point` to move the new index to a valid utf-8 offset.

Thank you for the detailed explanation! Should have noticed the usage of `movement::saturating_right` right below the code I touched, my bad 🙇
