### PR TITLE
editor: Fix soft wrap premature wrapping with certain fonts

### LINKED ISSUE #45107: Soft wrap is off by one character
### Reproduction steps

1. Configure preferred line length to 80 characters
2. Write a line that's exactly 80 characters long
3. Turn on soft wrap
4. Notice how the line is now wrapped

### Current vs. Expected behavior

This is what my text looks like without any soft wrapping enabled 
Image

This is what it looks like when I enable wrapping

Image

Notice how line 828 and 830 now wraps, even though they never extended beyond the wrap guide.  

I expect text to be allowed to reach right up to the wrap guide.

Here are my settings

Image

### Zed version and system specs

Zed: v0.217.1+stable.98.56049ac3b58f2da9e171c3fee318f7d4944b0159 (Zed) 
OS: macOS 15.2
Memory: 36 GiB
Architecture: aarch64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/modelListComponent.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/relationFields.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 10
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/layout/icons.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 93
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 8
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/pages.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/__tests__/relationFields.test.ts"
  }
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 98
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 101
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 105
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 120
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 125
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 61
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 41
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 48
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 66
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 82
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 99
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 107
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 126
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 63
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 73
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 86
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 93
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 123
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 128
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 135
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 142
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 157
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 165
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 187
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 186
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 154
}
2025-12-17T14:04:22+01:00 INFO  [lsp] Language server with id 29 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2025-12-17T14:04:23+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/pages/AirPage/AirPage.tsx",
  "state": 1,
  "validationTime": 1612
}
2025-12-17T14:04:23+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/components/FanControlCell/FanControlCell.tsx",
  "state": 1,
  "validationTime": 33
}
2025-12-17T14:04:23+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/services/mqttMessages/mqttMessages.ts",
  "state": 1,
  "validationTime": 152
}
2025-12-17T14:04:24+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/jobs/RootChamberRhCronJob/RootChamberRhCronJob.ts",
  "state": 1,
  "validationTime": 29
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 29 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 29 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 22 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 42
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 45
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/layout/icons.ts"
  }
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 65
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 29 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/modelListComponent.ts"
  }
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 14
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/pages.ts"
  }
}
2025-12-17T14:04:48+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/sdl.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 29 sent unhandled notification @/tailwindCSS/clearColors:
[
  null
]
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 75
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 102
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 11
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/__tests__/relationFields.test.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/jobs/RootChamberRhCronJob/RootChamberRhCronJob.ts",
  "state": 1,
  "validationTime": 299
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/relationFields.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 195
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/modelListComponent.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 149
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 186
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/pages.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 156
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 93
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/layout/icons.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/sdl.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 365
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 21
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 216
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/relationFields.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/layout/icons.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/pages.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/services.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/sdl.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/__tests__/relationFields.test.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/layout/icons.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/sdl.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/templates/tsx/radminFormatters.tsx"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/pages.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/modelListComponent.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 10 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/tmp/cedar-share-code/shared/hello.js",
  "state": 1,
  "validationTime": 50
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/relationFields.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/__tests__/relationFields.test.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/columnFilter.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/__tests__/relationFields.test.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/pages/components/modelListComponent.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 16 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/tobbe/dev/radmin/src/lib/relationFields.ts"
  }
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 249
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 108
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 112
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 136
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 151
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 154
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 158
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 159
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 164
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 162
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 164
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 171
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 182
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 16
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 21
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.mjs",
  "state": 1,
  "validationTime": 31
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/index.js",
  "state": 1,
  "validationTime": 39
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 61
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/web/src/global.web-auto-imports.ts",
  "state": 1,
  "validationTime": 76
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 89
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 23 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/cedar/packages/eslint-config/shared.mjs",
  "state": 1,
  "validationTime": 97
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 57
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 59
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 71
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 75
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 80
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/renovate/release_notes.ts",
  "state": 1,
  "validationTime": 81
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 85
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 87
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release.ts",
  "state": 1,
  "validationTime": 90
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 96
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/lib/release_functions.ts",
  "state": 1,
  "validationTime": 115
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/console_helpers.ts",
  "state": 1,
  "validationTime": 117
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 120
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/run.ts",
  "state": 1,
  "validationTime": 122
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release/run.ts",
  "state": 1,
  "validationTime": 127
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/release_notes/run.ts",
  "state": 1,
  "validationTime": 104
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 108
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/components/FanControlCell/FanControlCell.tsx",
  "state": 1,
  "validationTime": 231
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/services/mqttMessages/mqttMessages.ts",
  "state": 1,
  "validationTime": 163
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/pages/AirPage/AirPage.tsx",
  "state": 1,
  "validationTime": 25
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/jobs/RootChamberRhCronJob/RootChamberRhCronJob.ts",
  "state": 1,
  "validationTime": 21
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/services/mqttMessages/mqttMessages.ts",
  "state": 1,
  "validationTime": 69
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/components/FanControlCell/FanControlCell.tsx",
  "state": 1,
  "validationTime": 15
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/lib/commits.ts",
  "state": 1,
  "validationTime": 6
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 13 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/cedarjs/release-tooling/triage/lib/triage.ts",
  "state": 1,
  "validationTime": 12
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/pages/AirPage/AirPage.tsx",
  "state": 1,
  "validationTime": 18
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/jobs/RootChamberRhCronJob/RootChamberRhCronJob.ts",
  "state": 1,
  "validationTime": 43
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/components/FanControlCell/FanControlCell.tsx",
  "state": 1,
  "validationTime": 15
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/pages/AirPage/AirPage.tsx",
  "state": 1,
  "validationTime": 10
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/services/mqttMessages/mqttMessages.ts",
  "state": 1,
  "validationTime": 48
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/jobs/RootChamberRhCronJob/RootChamberRhCronJob.ts",
  "state": 1,
  "validationTime": 13
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/api/src/services/mqttMessages/mqttMessages.ts",
  "state": 1,
  "validationTime": 47
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/pages/AirPage/AirPage.tsx",
  "state": 1,
  "validationTime": 8
}
2025-12-17T14:04:49+01:00 INFO  [lsp] Language server with id 30 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/tobbe/dev/aerafarms/victory/web/src/components/FanControlCell/FanControlCell.tsx",
  "state": 1,
  "validationTime": 8
}
2025-12-17T14:10:12+01:00 INFO  [auto_update] Auto Update: checking for updates
2025-12-17T14:15:43+01:00 ERROR [crates/gpui/src/window.rs:1203] window not found
2025-12-17T14:16:12+01:00 ERROR [crates/gpui/src/window.rs:1203] window not found


```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "soft_wrap": "preferred_line_length",
  "colorize_brackets": true,
  // [...]
  "wrap_guides": [80],
  // etc
```
</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by errmayank**
Closes #45107

Release Notes:

- Fixed soft wrap prematurely wrapping with certain fonts

### CODE REVIEW

**Comment by errmayank** [comment]
Here's before/after:

Screenshot 2025-12-18 at 13 46 39

<details>
<summary><h5>Example README.md</h5></summary>

`````
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut iaculis nisi et non.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut urna nibh tincidunt.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer imperdiet quam.

`````
</details>

**Review by Veykril — APPROVED** [review]
Thanks!

**Comment by MrSubidubi** [comment]
The test very much checks what the error says, so if this fails, it is very likely that we actually have minimal scrolling with soft wrap enabled, which we should never have. Test is supposed to catch just that (we regressed there too many times). 

So this might change more in the editor than it perhaps should, some calculation there might be different due to this change and would result in scrolling with soft wrap

**Comment by errmayank** [comment]
Thanks @/MrSubidubi. Tests should pass now 🙈

**Comment by Veykril** [comment]
Can you give a bit more context on this as to why this fixes the issue now?

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -9062,6 +9060,15 @@ impl Element for EditorElement {
...
                     let em_advance = window.text_system().em_advance(font_id, font_size).unwrap();
+                    let run = TextRun {
+                        len: 1,
+                        font: style.text.font(),
+                        ..Default::default()
+                    };
+                    let em_rendered_width = window
+                        .text_system()
+                        .layout_line("m", font_size, &[run], None)
+                        .width;
```
Comment (Veykril) [inline crates/editor/src/element.rs]: Feels like we should give this its own method like is done with `em_width` and `em_advance` for consistency

Comment (Veykril) [reply crates/editor/src/element.rs]: Also, why does `em_width` not suffice here?

Comment (Veykril) [reply crates/editor/src/element.rs]: any comment on this?

Comment (errmayank) [reply crates/editor/src/element.rs]: Hey, apologies for the delay. Yeah i tried using `em_width` but it doesn't work and i'm not really sure why tbh. So i just made it match with the line wrapper calculation.
