### PR TITLE
Fix copy button not working for REPL error output

### LINKED ISSUE #40207: `copy` button(s) do not work in REPL interactive mode
### Summary

`copy` button for REPL errors does not work

### Description
using an interactive python REPL with a content like:
```python
# %%
import sys

print("std")
print("err", file=sys.stderr)
not_existing
```
would produce an error (as `not_existing` is undefined) and the output is split into two sections, stdout+stderr where the copy button works, and a second section where the `NameError:` is shown and where both the `copy` and `open REPL Output` buttons have no effect.

DESCRIPTION_HERE

Steps to reproduce:
1. start a REPL in the editor (with content as above)
2. execute
3. try to copy the stderr+stdout - works
4. try to copy the error - nothing happens (see the second copy button in the attached screenshot)

### Zed Version and System Specs

recent 0.207.4 - but I believe it never actually worked

Image

### PR DESCRIPTION
**Pull request by h-michaelson20**
## Description

Fixes the copy button functionality in REPL interactive mode error output sections.

When executing Python code that produces errors in the REPL (e.g., `NameError`), the copy button in the error output section was unresponsive. The stdout/stderr copy button worked correctly, but the error traceback section copy button had no effect when clicked.

Fixes #40207

## Changes

Modified the following:
src/outputs.rs: Fixed context issues in render_output_controls by replacing cx.listener() with simple closures, and added custom button implementation for ErrorOutput that copies/opens the complete error (name + message + traceback)
src/outputs/plain.rs: Made full_text() method public to allow access from button handlers
src/outputs/user_error.rs: Added Clone derive to ErrorView struct and removed a couple pieces of commented code

## Why This Matters

The copy button was clearly broken and it is useful to have for REPL workflows. Users could potentially need to copy error messages for a variety of reasons.

## Testing

See attached demo for proof that the fix is working as intended. (this is my first ever commit, if there are additional test cases I need to write or run, please let me know!)

https://github.com/user-attachments/assets/da158205-4119-47eb-a271-196ef8d196e4

Release Notes:

- Fixed copy button not working for REPL error output

### CODE REVIEW

**Review by Veykril — APPROVED** [review]
Thanks!

**Comment by Veykril** [comment]
You'll need to sign the CLA for us to merge this.

**Comment by h-michaelson20** [comment]
@Veykril Done! Thank you.

File: crates/repl/src/outputs.rs [hunk 1]
```diff
@@ -237,7 +237,69 @@ impl Output {
...
+                                    ElementId::Name("open-full-error-in-buffer-traceback".into()),
+                                    IconName::FileTextOutlined,
+                                )
+                                .style(ButtonStyle::Transparent)
+                                .tooltip(Tooltip::text("Open Full Error in Buffer"))
+                                .on_click({
+                                    let ename = err.ename.clone();
+                                    let evalue = err.evalue.clone();
+                                    let traceback = err.traceback.clone();
+                                    let workspace = workspace.clone();
```
Comment (Veykril) [inline crates/repl/src/outputs.rs]:
```suggestion
                                    let traceback = err.traceback.clone();
```
