### PR TITLE
XDG_BASE_DIR support (linux, windows)

### LINKED ISSUE #7155: Don't write .tmp files to ~/.config/zed/
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've got dozens of temp files like `.tmp2kFlv3` in my `~/.config/zed/` directory, presumably containing telemetry entries. Per the XDG specification, they should go to `~/.local/share/zed/` or somewhere else. 

Arguably, `~/.config/zed/conversations/` and maybe `~/.config/zed/embeddings/` (whatever the latter is) are no config data either.

Otherwise, I'm thrilled to trying out Zed.

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 12.7.3
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### LINKED ISSUE #9308: Zed puts stuff into $XDG_CONFIG_HOME that doesn't belong there
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

From what I understand, XDG_CONFIG_HOME is for configuration files, like `settings.json` and `keybindings.json` and `tasks.json`.

Zed misuses that directory to place some autogenerated files and directories in there:

```
$ tree -a ~/.config/zed
zed
├── .tmpgQCsHZ
├── conversations
├── embeddings
│   └── stable
│       ├── embeddings_db
│       ├── embeddings_db-shm
│       └── embeddings_db-wal
├── keymap.json
├── settings.json
└── themes
```

I think stuff like `embeddings` with some generated databases, and a random directory like `.tmpgQCsHZ` doesn't belong to XDG_DATA_HOME.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by elkowar**
This PR adds XDG_BASE_DIR support on linux, and cleans up the path declarations slightly. Additionally, we move the embeddings and conversations directly to the SUPPORT_DIR on those platforms.
I _think_ that should also be done on MacOS in the future, but that has been left out here for now to not break existing users setups. 

Additionally, we move the SUPPORT_DIR into LocalAppData on windows for consistency.

fixes https://github.com/zed-industries/zed/issues/9308
fixes https://github.com/zed-industries/zed/issues/7155

Release Notes:

- N/A

### CODE REVIEW

**Comment by elkowar** [comment]
@cla-bot check

**Review by phisch — APPROVED** [review]

File: crates/util/src/paths.rs [hunk 1]
```diff
@@ -12,46 +12,55 @@ lazy_static::lazy_static! {
...
+        SUPPORT_DIR.join("logs")
+    };
     pub static ref EXTENSIONS_DIR: PathBuf = SUPPORT_DIR.join("extensions");
     pub static ref LANGUAGES_DIR: PathBuf = SUPPORT_DIR.join("languages");
     pub static ref COPILOT_DIR: PathBuf = SUPPORT_DIR.join("copilot");
     pub static ref DEFAULT_PRETTIER_DIR: PathBuf = SUPPORT_DIR.join("prettier");
     pub static ref DB_DIR: PathBuf = SUPPORT_DIR.join("db");
     pub static ref CRASHES_DIR: PathBuf = if cfg!(target_os = "macos") {
         HOME.join("Library/Logs/DiagnosticReports")
-    } else if cfg!(target_os = "windows") {
```
Comment (mikayla-maki) [inline crates/util/src/paths.rs:46]: This variable is used for us to detect segfaults and other crashes which are recorded by the system but couldn't be intercepted by us. I don't know if it's possible for us to find this data on linux, but I expect there might be something on Windows.

File: crates/util/src/paths.rs [hunk 2]
```diff
@@ -12,46 +12,55 @@ lazy_static::lazy_static! {
...
-        dirs::data_local_dir()
-            .expect("failed to determine LocalAppData directory")
-            .join("Zed/crashes")
     } else {
-        CONFIG_DIR.join("crashes")
+        SUPPORT_DIR.join("crashes")
     };
     pub static ref CRASHES_RETIRED_DIR: PathBuf = if cfg!(target_os = "macos") {
```
Comment (mikayla-maki) [inline crates/util/src/paths.rs:62]: Same with this variable.

File: crates/util/src/paths.rs (hunk 1 above)
Comment (mikayla-maki) [reply crates/util/src/paths.rs:46]: Perhaps we should make it an Option instead, that's only defined for platforms we can find this information on.
