### PR TITLE
Autosave files on close, when setting is `afterDelay`

### LINKED ISSUE #12149: Autosave on both focus change and after a delay
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to propose an improvement to Zed's `autosave` setting. [As of today][1], the setting accepts values `after_delay` or one of `on_focus_change` or `on_window_change`. I suggest changing it, so one could set both a delay and on focus change.

When `autosave` runs more often than once a second, I find it annoying that it also triggers autoformatting, causing the code on the screen to "wiggle" (i.e. reformatted) when I pause editing for a bit. Although, I do want the edits to be saved when I paused editing, to think for a second or two. Also, when I switch to another file or window, I want my last edits to be saved immediately.

I think, something like below could improve the editor's behaviour:

```
"autosave": {
  "on_focus_change": true,
  "after_delay": {
    "milliseconds": 3000
  }
}
```

[1]: https://zed.dev/docs/configuring-zed#autosave

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #35524: Unsaved changes dialog appears when closing buffers quickly, despite autosave
### Summary

If I make a quick change and cmd+w (to close the file tab) too quickly, I see a "you have unsaved changes" dialog, which is annoying

### Description
As above. This doesn't happen with JetBrains or VSCode, where in VSCode I'm using exactly the same autosave = `afterDelay` w/ delay of 1000ms

Steps to reproduce:
1.
```
  "autosave": {
    "after_delay": {
      "milliseconds": 1000,
    }
  },
```
2. Open an existing file in Zed
3. Add some words and quickly close the buffer with cmd+w
4. See a dialog: 

Image

**Expected Behavior**: the buffer closes without any dialogs, and either a save is triggered synchronously, or tries to save in the background at the normal autosave (I guess,  whatever JetBrains and VSCode are doing in this case)
**Actual Behavior**: "unsaved changes" dialog

### Zed Version and System Specs

Zed: v0.197.5 (Zed) 
OS: macOS 15.5.0
Architecture: x86_64

### PR DESCRIPTION
**Pull request by itsaphel**
Closes https://github.com/zed-industries/zed/issues/12149
Closes #35524

Release Notes:

- Improved autosave behavior, to prevent a confirmation dialog when quickly closing files and using the `afterDelay` setting

### CODE REVIEW

**Comment by MrSubidubi** [comment]
Thanks for taking a stab at fixing this yourself, looks good!

Three small things I'd like to have with this:

- Can you move the `matches!(..)` here for both cases to a method like `AutosaveSetting::on_window_change` so that it becomes more concise and immeadiately clear what is happening here?
- Please add a test for this to https://github.com/zed-industries/zed/blob/db497ac867ce8c9a2bad0aef6261ac2acb2896fa/crates/workspace/src/workspace.rs#L8665 
- Lastly, I think we should probably add a sentence about this to the code and/or docs so people do not get confused as to why this is happening.

File: crates/workspace/src/workspace.rs [hunk 1]
```diff
@@ -8639,6 +8639,14 @@ mod tests {
...
         cx.executor().advance_clock(Duration::from_millis(250));
         item.read_with(cx, |item, _| assert_eq!(item.save_count, 4));
+        
+        // Autosave after delay, should save earlier than delay if tab is closed
+        item.update(cx, |item, cx| {
+            item.is_dirty = true;
+            cx.emit(ItemEvent::Edit);
+        });
+        cx.executor().advance_clock(Duration::from_millis(250));
+        item.read_with(cx, |item, _| assert_eq!(item.save_count, 5));
```
Comment (MrSubidubi) [inline crates/workspace/src/workspace.rs]: The test does not actually test this case yet, you'll need to duplicate the logic below once for closing a tab, as we change the setting right below

**Review by MrSubidubi — CHANGES_REQUESTED** [review]
Looks better, thank you. 

Aside from the one comment, you'll also need to merge `main` once and resolve the conflicts, please.

**Review by MrSubidubi — APPROVED** [review]
Went ahead and quickly applied that fix myself. Thanks for getting the ball rolliing here and your contribution!

**Comment by itsaphel** [comment]
Thanks for getting this over the line @MrSubidubi - sorry, have been all over the place in the past week-ish so wasn't able to get back around to this.

**Comment by MrSubidubi** [comment]
My pleasure, and all good, no need to apologize. Hope things calm back down again for you!
