### PR TITLE
Discover available python environments with Jupyter kernel support

### LINKED ISSUE #15563: REPL: env detection not working properly
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

let's create 2 different virtual environments, one with `polars` as a dependency, one without

### create first env
```sh
# create dir
>  mkdir env1

>  cd env1

# create virtual env
>  python3 -m virtualenv .venv 

>  source .venv/bin/activate
>  pip install ipykernel 
>  python -m ipykernel install --user
>  pip install polars
>  cd - 
```

### Same thing but without the additional dependency 
```sh
# create dir
>  mkdir env2

>  cd env2

# create virtual env
>  python3 -m virtualenv .venv 

>  source .venv/bin/activate
>  pip install ipykernel 
>  python -m ipykernel install --user
```

Now create a simple file in both directories
```py
# env1/main.py
# %% Cell 1
import polars as pl
```

```py
# env2/main.py
# %% Cell 1
import polars as pl
```

I would fully expect running 'Cell 1' from `env2` to fail as the dependency is not installed in that virtualenv, but it instead uses the other one. 

### Environment

Zed: v0.146.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

image

image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### LINKED ISSUE #16757: REPL not working for venv setup
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

REPL doesn't seem to find the kernel at all. My assumption is that it's looking for only system kernels, while I want to use the one in .venv. I can't find any way of selecting python .venv for this?

Opening a terminal in this and running things there naturally works as direnv works.

### Environment

Linux fedora, python 3.12.
direnv activating and installing .venv
```
pyenv local $(cat .python-version)
export POETRY_VIRTUALENVS_IN_PROJECT=1
poetry env use "$(pyenv root)/versions/$(cat .python-version)/bin/python"
poetry install --sync --no-root
export VIRTUAL_ENV=$(poetry env info --path)
PATH_add "$VIRTUAL_ENV/bin"
export POETRY_ACTIVE=1
```

```
[tool.poetry]
name = "nansen-clickhouse"
version = "0.1.0"
description = ""
authors = ["Anders Aagaard <anders.aagaard@nansen.ai>"]

[tool.poetry.dependencies]
python = "^3.11"
jupysql = "^0.10.1"
clickhouse-sqlalchemy = "^0.2.4"
ipykernel = "^6.25.2"
toml = "^0.10.2"
pandas = "^2.1.0"
matplotlib = "^3.8.0"
clickhouse-connect = "^0.6.22"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.jupysql.SqlMagic]
autopandas = true
displaylimit = 0
named_parameters = true

```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[zed.log](https://github.com/user-attachments/files/16730776/zed.log)

</pre></details>

### LINKED ISSUE #18291: unclear `repl run` source environment
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

So I was trying to test some plot using `repl: run` around `python`. After setting up environment `pyrightconfig.json` with appropriate source python environment I tried to execute a simple code that uses `matplotlib`.

Despite `matplotlib` being present in source environment I want to use that is defined in `pyrightconfig.json` the `repl` interpreter does not seem to recognize it delivering:

Screenshot 2024-09-24 at 11 52 52 AM

In short, please help me figure out how to source desired environment via `repl`. Thanks.

PS. `repl: sessions` would show me all active kernels, just not sure how I can select the one of my liking?
Screenshot 2024-09-24 at 11 58 46 AM

and to repeat myself, the source env does have `matplotlib` installed, but the message show it isn't.

### Environment

```
Zed: v0.154.1 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I expect ZED to recognize environment of my liking and be able to recognize underlying installed packages.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-24T12:00:43.489139-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:43.622842-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:43.748363-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:43.807815-05:00 [INFO] language server 2: unregistered workspace/DidChangeWatchedFiles capability with id f0e3c60e-462d-4e16-b6c1-7f6735c54b78
2024-09-24T12:00:44.209337-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:44.33084-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:44.40455-05:00 [INFO] language server 6: unregistered workspace/DidChangeWatchedFiles capability with id 400aeb1f-c1d2-46d2-86f4-35676fb005a8
2024-09-24T12:00:44.46633-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:44.469399-05:00 [INFO] starting language server process. binary path: "/Users/<user>/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/<user>/GitHubs/Bombora/<project2>", args: ["/Users/<user>/Library/Application Support/Zed/extensions/work/dockerfile/node_modules/dockerfile-language-server-nodejs/bin/docker-langserver", "--stdio"]
2024-09-24T12:00:44.598945-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:44.638133-05:00 [WARN] unhandled capability registration: Registration { id: "7f5b5ed7-0160-4b06-91fc-df6c639560bd", method: "workspace/didChangeConfiguration", register_options: Some(Object {}) }
2024-09-24T12:00:45.169638-05:00 [INFO] Node runtime install_if_needed
2024-09-24T12:00:45.286996-05:00 [INFO] starting language server process. binary path: "/Users/<user>/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/<user>/GitHubs/Bombora/<project1>", args: ["/Users/<user>/Library/Application Support/Zed/extensions/work/docker-compose/node_modules/.bin/docker-compose-langserver", "--stdio"]
2024-09-24T12:00:45.288139-05:00 [INFO] starting language server process. binary path: "/Users/<user>/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/<user>/GitHubs/Bombora/<project2>", args: ["/Users/<user>/Library/Application Support/Zed/extensions/work/docker-compose/node_modules/.bin/docker-compose-langserver", "--stdio"]
2024-09-24T12:00:45.591431-05:00 [INFO] language server 3: unregistered workspace/DidChangeWatchedFiles capability with id d386a8a0-479d-487d-a192-bdd216d5f649
2024-09-24T12:00:45.913819-05:00 [INFO] language server 5: unregistered workspace/DidChangeWatchedFiles capability with id 073ca66a-a449-4bdf-a715-6f94b5f0e896
2024-09-24T12:00:47.403122-05:00 [INFO] language server 5: unregistered workspace/DidChangeWatchedFiles capability with id fcf6eade-6da0-4426-8088-5bf206f28f37
2024-09-24T12:01:07.685492-05:00 [INFO] kernel: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
2024-09-24T12:01:07.68567-05:00 [INFO] kernel: 
2024-09-24T12:01:07.685794-05:00 [INFO] kernel: To exit, you will have to explicitly quit this process, by either sending
2024-09-24T12:01:07.685922-05:00 [INFO] kernel: "quit" from a client, or using Ctrl-\ in UNIX-like environments.
2024-09-24T12:01:07.686051-05:00 [INFO] kernel: 
2024-09-24T12:01:07.686173-05:00 [INFO] kernel: To read more about this, see https://github.com/ipython/ipython/issues/2049
2024-09-24T12:01:07.6863-05:00 [INFO] kernel: 
2024-09-24T12:01:07.686426-05:00 [INFO] kernel: 
2024-09-24T12:01:07.686553-05:00 [INFO] kernel: To connect another client to this kernel, use:
2024-09-24T12:01:07.68668-05:00 [INFO] kernel:     --existing kernel-zed-4294968086.json
</pre></details>

### PR DESCRIPTION
**Pull request by rgbkrk**
image

Closes #18291
Closes #16757
Closes #15563

Release Notes:

- Added support for kernelspecs based on python environments

### CODE REVIEW

File: crates/repl/src/repl_editor.rs [hunk 1]
```diff
@@ -156,6 +177,22 @@ pub enum SessionSupport {
...
+        editor
+            .read(cx)
+            .buffer()
+            .read(cx)
+            .as_singleton()?
+            .read(cx)
+            .project_path(cx)
+            .map(|path| path.worktree_id)
+    })
+}
```
Comment (rgbkrk) [inline crates/repl/src/repl_editor.rs:194]: I could see `worktree_id(cx)` being defined on `View<Editor>`. Not sure if others want that but I need to reuse it here in repl.

File: crates/repl/src/repl_editor.rs [hunk 2]
```diff
@@ -87,11 +99,20 @@ pub fn run(editor: WeakView<Editor>, move_down: bool, cx: &mut WindowContext) ->
...
+                language.code_fence_block_name().as_ref(),
+                cx,
+            )
+            .ok_or_else(|| anyhow::anyhow!("No kernel found for language: {}", language.name()))?;
+
+        // let kernel_specification = store.update(cx, |store, cx| {
+        //     store
+        //         .kernelspec(language.code_fence_block_name().as_ref(), cx)
+        //         .with_context(|| format!("No kernel found for language: {}", language.name()))
+        // })?;
```
Comment (rgbkrk) [inline crates/repl/src/repl_editor.rs:115]: 🗡️

File: crates/quick_action_bar/src/repl_menu.rs [hunk 3]
```diff
@@ -294,6 +294,11 @@ impl QuickActionBar {
             return div().into_any_element();
         };
 
+        let Some(worktree_id) = worktree_id_for_editor(editor.downgrade(), cx) else {
+            // todo!()
```
Comment (rgbkrk) [inline crates/quick_action_bar/src/repl_menu.rs:298]: Perhaps `render_kernel_selector` should return an `Option<AnyElement>` instead of this. We just shouldn't even render this if there's no worktree because of later constraints with the toolchains. A little bit too bad because it's nice to be able to have an untitled buffer be a scratch space.

File: crates/repl/src/kernels.rs [hunk 4]
```diff
@@ -465,6 +467,123 @@ async fn read_kernels_dir(path: PathBuf, fs: &dyn Fs) -> Result<Vec<LocalKernelS
...
+                    ],
+                    display_name: format!("Python ({})", toolchain.name),
+                    language: "python".to_string(),
+                    interrupt_mode: None,
+                    metadata: None,
+                    env: None,
+                };
+
+                kernel_specs.push(KernelSpecification::PythonEnv(LocalKernelSpecification {
+                    name: format!("Python ({})", toolchain.name),
```
Comment (rgbkrk) [inline crates/repl/src/kernels.rs:576]: This ends up being really redundant so it should just be the `toolchain.name`.

File: crates/repl/src/repl_sessions_ui.rs [hunk 5]
```diff
@@ -63,17 +62,34 @@ pub fn init(cx: &mut AppContext) {
...
 
             if !is_local_project {
                 return;
             }
 
+            let project_path = editor
+                .buffer()
+                .read(cx)
+                .as_singleton()
+                .and_then(|buffer| buffer.read(cx).project_path(cx));
```
Comment (rgbkrk) [inline crates/repl/src/repl_sessions_ui.rs:80]: Reuse the `worktree_id_for_editor` function here.

File: crates/repl/src/repl_store.rs [hunk 6]
```diff
@@ -22,6 +22,8 @@ pub struct ReplStore {
     enabled: bool,
     sessions: HashMap<EntityId, View<Session>>,
     kernel_specifications: Vec<KernelSpecification>,
```
Comment (rgbkrk) [inline crates/repl/src/repl_store.rs:24]: Now that this list is _just_ the global Jupyter kernels, we should probably name it as such.

File: crates/repl/src/repl_store.rs [hunk 7]
```diff
@@ -105,8 +120,29 @@ impl ReplStore {
...
+
+            this.update(&mut cx, |this, cx| {
+                this.kernel_specifications_for_worktree
+                    .insert(worktree_id, kernel_specifications);
+                cx.notify();
+            })
+        })
+    }
+
     pub fn refresh_kernelspecs(&mut self, cx: &mut ModelContext<Self>) -> Task<Result<()>> {
```
Comment (rgbkrk) [inline crates/repl/src/repl_store.rs:143]: Given _when_ someone would call `refresh_kernelspecs` likely from the comforts of an editor, we should also refresh the python kernelspecs.

File: crates/repl/src/repl_store.rs [hunk 8]
```diff
@@ -105,8 +120,29 @@ impl ReplStore {
...
+    ) -> Task<Result<()>> {
+        let kernel_specifications = python_env_kernel_specifications(project, worktree_id, cx);
+        cx.spawn(move |this, mut cx| async move {
+            let kernel_specifications = kernel_specifications
+                .await
+                .map_err(|e| anyhow::anyhow!("Failed to get python kernelspecs: {:?}", e))?;
+
+            this.update(&mut cx, |this, cx| {
+                this.kernel_specifications_for_worktree
+                    .insert(worktree_id, kernel_specifications);
```
Comment (rgbkrk) [inline crates/repl/src/repl_store.rs:137]: If any kernelspecs are equivalent, we should dedupe them.

File: crates/repl/src/repl_store.rs [hunk 9]
```diff
@@ -122,9 +158,33 @@ impl ReplStore {
...
+    }
+
+    fn kernelspec_legacy_by_lang_only(
+        &self,
+        language_at_cursor: &str,
+        cx: &AppContext,
+    ) -> Option<KernelSpecification> {
         let settings = JupyterSettings::get_global(cx);
-        let selected_kernel = settings.kernel_selections.get(language_name);
+        let selected_kernel = settings.kernel_selections.get(language_at_cursor);
```
Comment (rgbkrk) [inline crates/repl/src/repl_store.rs:187]: Can this be tossed now?

Better yet, can we store the kernel for the worktree ID in the workspace DB for persistence?

File: crates/repl/src/repl_store.rs [hunk 10]
```diff
@@ -72,7 +76,18 @@ impl ReplStore {
...
-    pub fn kernel_specifications(&self) -> impl Iterator<Item = &KernelSpecification> {
+    pub fn kernel_specifications_for_worktree(
+        &self,
+        worktree_id: WorktreeId,
+    ) -> impl Iterator<Item = &KernelSpecification> {
+        self.kernel_specifications_for_worktree
+            .get(&worktree_id)
+            .into_iter()
+            .flat_map(|specs| specs.iter())
+            .chain(self.kernel_specifications.iter())
```
Comment (rgbkrk) [inline crates/repl/src/repl_store.rs:87]: This should dedupe in case any python env kernelspecs are exactly the same as the jupyter kernelspecs.

File: crates/repl/src/kernels.rs [hunk 11]
```diff
@@ -465,6 +467,123 @@ async fn read_kernels_dir(path: PathBuf, fs: &dyn Fs) -> Result<Vec<LocalKernelS
...
+    cx: &mut AppContext,
+) -> impl Future<Output = Result<Vec<KernelSpecification>>> {
+    let fs = project.read(cx).fs().clone();
+    let python_language = LanguageName::new("Python");
+
+    let toolchains = project
+        .read(cx)
+        .available_toolchains(worktree_id, python_language, cx);
+
+    async move {
```
Comment (rgbkrk) [inline crates/repl/src/kernels.rs:483]: These should be setup as futures that can await in parallel rather than serially.

File: crates/repl/src/kernels.rs [hunk 12]
```diff
@@ -465,6 +467,123 @@ async fn read_kernels_dir(path: PathBuf, fs: &dyn Fs) -> Result<Vec<LocalKernelS
...
+                kernel_specs.push(KernelSpecification::PythonEnv(LocalKernelSpecification {
+                    name: toolchain.name.to_string(),
+                    path: PathBuf::from(&python_path),
+                    kernelspec: default_kernelspec,
+                }));
+            } else {
+                continue;
+            }
+
+            let prefix = PathBuf::from(toolchain.path.to_string());
```
Comment (rgbkrk) [inline crates/repl/src/kernels.rs:529]: Delete this code now that we're just collecting pure python kernelspecs. We can bring back the kernelspecs-in-env code (which would likely support R kernels in conda) once we have the `prefix` from the python toolchains.

File: crates/repl/src/repl_sessions_ui.rs (hunk 5 above)
Comment (rgbkrk) [reply crates/repl/src/repl_sessions_ui.rs:80]: Nevermind, this one can't due to where these are on the stack.

File: crates/repl/src/repl_sessions_ui.rs [hunk 13]
```diff
@@ -198,97 +217,18 @@ impl Render for ReplSessionsPage {
...
-
-                                        el.child(
-
-                                        div().id("check").tooltip(move |cx| Tooltip::text(format!("Default Kernel for {language}"), cx))
-                                            .child(Icon::new(IconName::Check)))}),
-                            )
-
-                    }))
-            }));
-
```
Comment (rgbkrk) [inline crates/repl/src/repl_sessions_ui.rs:275]: Since we have a kernel options picker now, having this listing in the sessions UI is redundant (and hard to support given the reliance on an editor). Happy to drop this for now.

File: crates/repl/src/components/kernel_options.rs [hunk 14]
```diff
@@ -175,10 +183,13 @@ impl PickerDelegate for KernelPickerDelegate {
...
-        let all_kernels: Vec<KernelSpecification> =
-            store.kernel_specifications().cloned().collect();
 
-        let selected_kernelspec = self.current_kernelspec;
+        let all_kernels: Vec<KernelSpecification> = store
+            .kernel_specifications_for_worktree(self.worktree_id)
+            .cloned()
+            .collect();
+
+        let selected_kernelspec = store.active_kernelspec(self.worktree_id, "todo", cx);
```
Comment (rgbkrk) [inline crates/repl/src/components/kernel_options.rs:192]: Another remaining todo for collecting the active kernelspec.

**Comment by rgbkrk** [comment]
Remaining TODOs, either for this PR or future ones:

* [ ] Store the kernel for the worktree ID in the workspace DB for persistence
* [ ] Resolve kernelspecs from inside environments using prefix (not supported via toolchains yet)
* [ ] Dedupe kernelspecs
