### PR TITLE
x11: HiDPI support

### LINKED ISSUE #11121: App resolution is too high and does not follow system settings
### Check for existing issues

- [X] Completed

---

### Describe the bug / provide steps to reproduce it

As it's mentioned in the title. Also similar issue happened [here](https://github.com/iced-rs/iced/issues/2404), [here](https://github.com/simplex-chat/simplex-chat/issues/3986) and [here](https://github.com/lpereira/hardinfo/issues/712)

To reproduce:
1. Compile and run zed
2. The interface will look like this:
<details><summary>Screenshots</summary>
<p>

Screenshot_2024-04-28_12-40-44

Compared to vscode:
Screenshot_2024-04-28_12-46-16

</p>
</details> 

---

### Environment

<details><summary>System info (inxi -Faz)</summary>
<p>

```
System:
  Kernel: 6.7.12-1-liquorix-amd64 arch: x86_64 bits: 64 compiler: gcc
    v: 12.2.0 parameters: audit=0 intel_pstate=disable rcupdate.rcu_expedited=1
    BOOT_IMAGE=/vmlinuz-6.7.12-1-liquorix-amd64
    root=UUID=4360036c-6183-4585-aa57-03927d0f64ad ro quiet splash
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36 info: xfce4-panel wm: xfwm
    v: 4.18.0 dm: LightDM v: 1.26.0 Distro: MX-23.2_ahs_x64 Libretto January 21
    2024 base: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Desktop Mobo: Micro-Star model: MAG B550 TOMAHAWK MAX WIFI (MS-7C91)
    v: 1.0 serial: <filter> UEFI: American Megatrends LLC. v: 2.60
    date: 10/10/2023
CPU:
  Info: model: AMD Ryzen 9 5950X socket: AM4 bits: 64 type: MT MCP
    arch: Zen 3+ gen: 4 level: v3 note: check built: 2022 process: TSMC n6 (7nm)
    family: 0x19 (25) model-id: 0x21 (33) stepping: 2 microcode: 0xA20120E
  Topology: cpus: 1x cores: 16 tpc: 2 threads: 32 smt: enabled cache:
    L1: 1024 KiB desc: d-16x32 KiB; i-16x32 KiB L2: 8 MiB desc: 16x512 KiB
    L3: 64 MiB desc: 2x32 MiB
  Speed (MHz): avg: 2256 high: 3400 min/max: 2200/5083 boost: enabled
    base/boost: 3400/5050 scaling: driver: acpi-cpufreq governor: ondemand
    volts: 1.1 V ext-clock: 100 MHz cores: 1: 2200 2: 2200 3: 3400 4: 2200
    5: 2200 6: 2200 7: 2200 8: 2200 9: 2200 10: 2200 11: 2800 12: 2200
    13: 2200 14: 2200 15: 2200 16: 2200 17: 2200 18: 2200 19: 2200 20: 2200
    21: 2200 22: 2200 23: 2200 24: 2200 25: 2200 26: 2200 27: 2200 28: 2200
    29: 2200 30: 2200 31: 2200 32: 2200 bogomips: 217614
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
  Vulnerabilities:
  Type: gather_data_sampling status: Not affected
  Type: itlb_multihit status: Not affected
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data status: Not affected
  Type: reg_file_data_sampling status: Not affected
  Type: retbleed status: Not affected
  Type: spec_rstack_overflow mitigation: Safe RET
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via
    prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer
    sanitization
  Type: spectre_v2 mitigation: Retpolines, IBPB: conditional, IBRS_FW,
    STIBP: always-on, RSB filling, PBRSB-eIBRS: Not affected
  Type: srbds status: Not affected
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: NVIDIA GA104 [GeForce RTX 3060] vendor: Micro-Star MSI
    driver: nvidia v: 525.147.05 non-free: 530.xx+
    status: current (as of 2023-03) arch: Ampere code: GAxxx
    process: TSMC n7 (7nm) built: 2020-22 pcie: gen: 1 speed: 2.5 GT/s
    lanes: 16 link-max: gen: 4 speed: 16 GT/s bus-ID: 2b:00.0
    chip-ID: 10de:2487 class-ID: 0300
  Display: server: X.Org v: 1.21.1.7 compositor: xfwm v: 4.18.0 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa alternate: nv
    gpu: nvidia display-ID: :0.0 screens: 1
  Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.65x15.00")
    s-diag: 777mm (30.58")
  Monitor-1: DP-0 res: 2560x1440 hz: 165 dpi: 108
    size: 600x330mm (23.62x12.99") diag: 685mm (26.96") modes: N/A
  API: OpenGL v: 4.6.0 NVIDIA 525.147.05 renderer: NVIDIA GeForce RTX
    3060/PCIe/SSE2 direct-render: Yes
Audio:
  Device-1: NVIDIA GA104 High Definition Audio vendor: Micro-Star MSI
    driver: snd_hda_intel v: kernel pcie: gen: 4 speed: 16 GT/s lanes: 16
    bus-ID: 2b:00.1 chip-ID: 10de:228b class-ID: 0403
  Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI
    driver: snd_hda_intel v: kernel pcie: gen: 4 speed: 16 GT/s lanes: 16
    bus-ID: 2d:00.4 chip-ID: 1022:1487 class-ID: 0403
  API: ALSA v: k6.7.12-1-liquorix-amd64 status: kernel-api
    tools: alsamixer,amixer
  Server-1: PipeWire v: 1.0.0 status: n/a (root, process) with:
    1: pipewire-pulse status: active 2: wireplumber status: active
    3: pipewire-alsa type: plugin 4: pw-jack type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
Network:
  Device-1: MEDIATEK MT7921K Wi-Fi 6E 80MHz driver: mt7921e v: kernel
    modules: wl pcie: gen: 2 speed: 5 GT/s lanes: 1 bus-ID: 29:00.0
    chip-ID: 14c3:0608 class-ID: 0280
  IF: wlan0 state: up mac: <filter>
  Device-2: Realtek RTL8125 2.5GbE vendor: Micro-Star MSI driver: r8169
    v: kernel pcie: gen: 2 speed: 5 GT/s lanes: 1 port: f000 bus-ID: 2a:00.0
    chip-ID: 10ec:8125 class-ID: 0200
  IF: eth0 state: down mac: <filter>
Bluetooth:
  Device-1: MediaTek Wireless_Device type: USB driver: btusb v: 0.8
    bus-ID: 1-9:6 chip-ID: 0e8d:0608 class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0
    lmp-v: 5.2 sub-v: 2311 hci-v: 5.2 rev: 919
  Info: acl-mtu: 1021:6 sco-mtu: 240:8 link-policy: rswitch sniff
    link-mode: peripheral accept service-classes: rendering, capturing, object
    transfer, audio, telephony
Drives:
  Local Storage: total: 1.82 TiB used: 201.3 GiB (10.8%)
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: MSI model: M480 PRO 2TB
    size: 1.82 TiB block-size: physical: 512 B logical: 512 B speed: 63.2 Gb/s
    lanes: 4 type: SSD serial: <filter> rev: EIFM80.0 temp: 37.9 C scheme: GPT
  SMART: yes health: PASSED on: 23d 20h cycles: 100
    read-units: 1,938,468 [992 GB] written-units: 4,875,342 [2.49 TB]
Partition:
  ID-1: / raw-size: 1.82 TiB size: 1.79 TiB (98.37%) used: 200.98 GiB (11.0%)
    fs: ext4 block-size: 4096 B dev: /dev/dm-0 maj-min: 253:0
    mapped: luks-5d75316a-19bd-44ac-892e-477343b3b3ec
  ID-2: /boot raw-size: 1024 MiB size: 973.4 MiB (95.06%)
    used: 328.4 MiB (33.7%) fs: ext4 block-size: 4096 B dev: /dev/nvme0n1p2
    maj-min: 259:2
  ID-3: /boot/efi raw-size: 256 MiB size: 252 MiB (98.46%)
    used: 274 KiB (0.1%) fs: vfat block-size: 512 B dev: /dev/nvme0n1p1
    maj-min: 259:1
Swap:
  Kernel: swappiness: 15 (default 60) cache-pressure: 100 (default)
  ID-1: swap-1 type: file size: 6 GiB used: 0 KiB (0.0%) priority: -2
    file: /swap/swap
Sensors:
  System Temperatures: cpu: 42.8 C mobo: 38.0 C gpu: nvidia temp: 44 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Info:
  Processes: 594 Uptime: 2h 21m wakeups: 1 Memory: 31.27 GiB
  used: 5.53 GiB (17.7%) Init: SysVinit v: 3.06 runlevel: 5 default: graphical
  tool: systemctl Compilers: gcc: 12.2.0 alt: 12 clang: 14.0.6 Packages: 2485
  pm: dpkg pkgs: 2460 libs: 1323 tools: apt,apt-get,aptitude,nala,synaptic
  pm: rpm pkgs: 0 pm: flatpak pkgs: 25 Shell: Sudo (sudo) v: 1.9.13p3
  default: Bash v: 5.2.15 running-in: xfce4-terminal inxi: 3.3.26
```

</p>
</details> 

---

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

---

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by apricotbucket28**
Fixes https://github.com/zed-industries/zed/issues/11121

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 1]
```diff
@@ -143,6 +148,31 @@ impl X11Client {
...
+                xproto::AtomEnum::RESOURCE_MANAGER,
+                xproto::AtomEnum::STRING,
+                0,
+                100_000_000,
+            )
+            .unwrap();
+        let resource_manager = resource_manager.reply().unwrap();
+
+        // todo(linux): read hostname
+        let resource_database = Database::new_from_default(&resource_manager, "HOSTNAME".into());
```
Comment (apricotbucket28) [inline crates/gpui/src/platform/linux/x11/client.rs:167]: Reading the hostname would require pulling extra crates, so I decided not to do it. It is only used as a fallback.

File: crates/gpui/src/platform/linux/x11/window.rs [hunk 2]
```diff
@@ -403,11 +409,16 @@ impl PlatformWindow for X11Window {
     }
 
     fn content_size(&self) -> Size<Pixels> {
-        self.0.state.borrow_mut().content_size()
+        // We divide by the scale factor here because this value is queried to determine how much to draw,
+        // but it will be multiplied later by the scale to adjust for scaling.
```
Comment (apricotbucket28) [inline crates/gpui/src/platform/linux/x11/window.rs:413]: The comment may not be clear enough, but basically, if we don't do this, window content is cut off :sweat_smile:

**Comment by mikayla-maki** [comment]
Looks good :D let's fix those merge conflicts and I can merge this :)
