### PR TITLE
json_schema_store: Include available LSP adapters in settings schema

### LINKED ISSUE #46556: LSP property “ty" is not recognized in `settings.json` schema
### Reproduction steps

1. Add `ty` settings to settings.json, for example 
```json
{
  "lsp": {
    "ty": {}
  }
}
```
2. the editor gives message "Property `ty` is not allowed"

### Current vs. Expected behavior

Current behavior: A warning appears for `ty` settings in `settings.json` ("Property ty is not allowed"). However, this does not affect the actual functionality of the `ty` language server.

Image

Expected behavior: Since `ty` is a built-in language server for Python, the settings.json schema should recognize it as a valid property so that users can configure it without seeing warnings.

### Zed version and system specs

Zed: v0.219.3+preview.116.3d83b3c9c66e9e5ef6f01c8849beede35264ed04 (Zed Preview) 
OS: Windows 10.0.26200
Memory: 47.8 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 770 || Intel Corporation || 32.0.101.7082

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
  "lsp": {
    "basedpyright": {
      "settings": {
        "analysis": {
          "diagnosticMode": "workspace",
          "typeCheckingMode": "standard",
          "inlayHints.callArgumentNames": true,
          "inlayHints.variableTypes": true,
        },
      },
    },
    "ty": {
      "settings": {
        "diagnosticMode": "workspace",
        "inlayHints": {
          "variableTypes": true,
          "callArgumentNames": true,
        },
      },
    },
  },
```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by baeseokjae**
Closes #46556

  ## Summary

  - Fix "Property `ty` is not allowed" warning in `settings.json` for LSP adapters registered via `register_available_lsp_adapter()`
  - Add `available_lsp_adapter_names()` method to include these adapters in schema generation
  - Support `initialization_options` schema lookup for available adapters

  ## Problem

  LSP adapters registered via `register_available_lsp_adapter()` were not included in the settings JSON schema. This caused validation warnings like:

  Property ty is not allowed

  Even though `ty` is a built-in Python language server that works correctly.

  **Affected adapters:**
  - `ty`, `py`, `python-lsp-server`
  - `eslint`, `vtsls`, `typescript-language-server`
  - `tailwindcss-language-server`, `tailwindcss-intellisense-css`

  ## Solution

  Schema generation now queries both:
  1. `all_lsp_adapters()` - adapters bound to specific languages
  2. `available_lsp_adapter_names()` - adapters enabled via settings (new)

  Related: #43104, #45928 
  
  Release Notes:

- Fixed an issue where not all LSP adapters would be suggested for completion, or recognized as valid in `settings.json`

### CODE REVIEW

File: crates/json_schema_store/src/json_schema_store.rs [hunk 1]
```diff
@@ -224,6 +225,9 @@ async fn resolve_dynamic_schema(
                 .all_lsp_adapters()
                 .into_iter()
                 .find(|adapter| adapter.name().as_ref() as &str == lsp_name)
+                .or_else(|| {
+                    languages.load_available_lsp_adapter(&LanguageServerName::from(lsp_name))
```
Comment (lingyaochu) [inline crates/json_schema_store/src/json_schema_store.rs:229]: I'm concerned about calling `load_available_lsp_adapter` here. It is not a pure "getter" for information; it has significant side effects and directly mutates the state of the language server module.

In my view, the settings schema resolution should be decoupled from the LSP lifecycle. We should only be querying the existing state rather than triggering a "load" action, which could lead to unintended consequences.

**Comment by baeseokjae** [comment]
@cla-bot check

File: crates/json_schema_store/src/json_schema_store.rs (hunk 1 above)
Comment (baeseokjae) [reply crates/json_schema_store/src/json_schema_store.rs:229]: @lingyaochu thanks for the review.

Just to clarify, `load_available_lsp_adapter` here doesn’t really act as a pure accessor, but it also doesn’t mutate shared state. It only takes a read lock and creates a temporary instance for schema lookup, then drops it.

For available adapters like `ty`, `eslint`, or `pylsp`, this is basically the only way to access their schemas today since they’re lazy-loaded and not part of `all_lsp_adapters`.

I agree that having schema resolution go through a “load” path isn’t ideal. That feels like something better handled as a separate issue later on. For this PR though, sticking with the current approach seems reasonable to me and I don’t see this causing issues in practice.

Comment (lingyaochu) [reply crates/json_schema_store/src/json_schema_store.rs:229]: Thanks for the clarification! I misunderstood how `load_available_lsp_adapter` worked under the hood. Given that it doesn't mutate shared state and is necessary for lazy-loaded adapters, this approach makes sense for now. I'm happy with the fix!

**Comment by MrSubidubi** [comment]
@baeseokjae Can I ask you to re-sign the CLA? We track this only based on the current username, so would be nice if you could just sign it again. Thanks!
