### PR TITLE
editor: Fix bracket colorization with folds and large functions

### LINKED ISSUE #47846: Last folded function in file causes unfolded functions underneath it to not have colorized brackets
### Reproduction steps

1. Start Zed
2. Enable Colorized Brackets
3. Open a file with multiple functions
4. Collapse, starting from the top, all functions but leave a few unfolded underneath
5. Close and reopen Zed
6. The final folded function and the functions underneath will have standard, white brackets

### Current vs. Expected behavior

1. Fresh workspace, I fold the function authenticate_github(), it does not cause functions underneath to lose their colorized brackets

Image

2. I close and open Zed with the function collapsed, authenticate_github() lost it's colorized brackets, as well as the functions underneath it

>> 2.1 Xcode
Image

>> 2.2 Ayu Dark

Image

3. I now unfold the function, the brackets stay white

Image

4. I close and open Zed, the bracket colorization is back

Image

### Zed version and system specs

Version: Zed 0.220.6
OS: Linux 6.18.6-arch1-1 + Wayland
CPU: Intel Core i5-12600k
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
	Subsystem: XFX Limited Speedster MERC 319 AMD Radeon RX 6800 XT Black
	Kernel driver in use: amdgpu
Memory: 32 GB

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
{
  "theme": {
    "mode": "dark",
    "light": "Gruvbox Light",
    "dark": "Xcode Default Dark",
  },
  "ui_font_family": "JetBrainsMono Nerd Font Mono",
  "ui_font_size": 16,
  "buffer_font_family": "JetBrainsMono Nerd Font Mono",
  "buffer_font_size": 15,
  "icon_theme": "Colored Zed Icons Theme Dark",
  "colorize_brackets": true,
  "vim_mode": false,
  "extend_comment_on_newline": false,
  "disable_ai": true,
  "git_panel": {
    "tree_view": false,
  },
  "project_panel": {
    "dock": "right",
  },
  "lsp": {
    "rust-analyzer": {
      "binary": {
        "path": "/usr/lib/rustup/bin/rust-analyzer",
      },
      "initialization_options": {
        "check": {
          "command": "clippy",
        },
      },
    },
  },
  "format_on_save": "on",
}

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by notJoon**
Closes #47846

`visible_excerpts` computed the visible buffer range by adding display line count directly to the buffer start row:

```rust
// Before
multi_buffer_visible_start + Point::new(visible_line_count, 0)
```
This ignores folds entirely. When a 700-line function is folded into one display line, content after the fold is visible on screen but falls outside the computed buffer range, so its brackets are never colorized.

The fix converts through display coordinates so the fold/wrap layers are respected:

```rust
// After
let display_end = DisplayPoint::new(display_start.row + visible_line_count, 0);
let multi_buffer_visible_end = display_end.to_point(&display_snapshot);
```

### Results

**Before Fix**
스크린샷 2026-03-10 오후 8 29 10

**After Fix**
스크린샷 2026-03-10 오후 8 32 27

Before you mark this PR as ready for review, make sure that you have:
- [X] Added a solid test coverage and/or screenshots from doing manual testing
- [ ] Done a self-review taking into account security and performance aspects
- [ ] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Release Notes:

- Fixed bracket colorization not working for content after folded regions and for functions with large bodies.

### CODE REVIEW

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
> Removing the limit is safe because `set_byte_range` already constrains the search to the 50-row chunk boundary.

Unfortunately, it's not, as without it tree-sitter parser may still be forced to traverse the entire code tree to find all bracket ranges that __intersect__ with the range given (even it's just 50 lines).

Given the breadth of `{}<>()[]` queries in almost all `brackets.scm` ([e.g. Rust](https://github.com/zed-industries/zed/blob/171e7cb4a7e470f9cbd6580b2b268d445ffb620b/crates/languages/src/rust/brackets.scm#L1-L12)), this would happen quire regularly.

I am looking at ways to mitigate this with https://github.com/zed-industries/zed/tree/kb/bracket-pairs but not there yet.

Let's exclude related changes from this PR for now.

File: crates/editor/src/bracket_colorization.rs [hunk 1]
```diff
@@ -1455,6 +1455,56 @@ mod foo «1{
...
+        // trigger re-colorization after fold
+        cx.update_editor(|editor, _window, cx| {
+            editor.colorize_brackets(true, cx);
+        });
+        cx.executor().advance_clock(Duration::from_millis(100));
+        cx.executor().run_until_parked();
+
+        let markup_after = bracket_colors_markup(&mut cx);
+        assert!(
+            markup_after.contains("small_function«"),
```
Comment (SomeoneToIgnore) [inline crates/editor/src/bracket_colorization.rs]: That is a very odd assertion, especially given the rest of the tests use the entire markup comparison — please, update it to be the `assert_eq!` on the full one.

File: crates/editor/src/bracket_colorization.rs [hunk 2]
```diff
@@ -1455,6 +1455,56 @@ mod foo «1{
...
+        cx.update_editor(|editor, window, cx| {
+            editor.fold_ranges(
+                vec![Point::new(0, 0)..Point::new(701, 1)],
+                false,
+                window,
+                cx,
+            );
+        });
+
+        // trigger re-colorization after fold
```
Comment (SomeoneToIgnore) [inline crates/editor/src/bracket_colorization.rs]: That is not clear to me: we emulate user's actions, using editor API.

If we do not get the colorized brackets automatically, it means there's a bug we need to fix: presumably, all LSP-related refresh methods and whatever else uses `visible_excerpts`.

File: crates/editor/src/editor.rs [hunk 3]
```diff
@@ -5790,16 +5772,23 @@ impl Editor {
...
-        let multi_buffer_visible_start = self
+        let scroll_anchor = self
             .scroll_manager
-            .native_anchor(&display_snapshot, cx)
-            .anchor
-            .to_point(&multi_buffer_snapshot);
-        let multi_buffer_visible_end = multi_buffer_snapshot.clip_point(
-            multi_buffer_visible_start
-                + Point::new(self.visible_line_count().unwrap_or(0.).ceil() as u32, 0),
+            .native_anchor(&display_snapshot, cx);
```
Comment (SomeoneToIgnore) [inline crates/editor/src/editor.rs]: `refresh_selected_text_highlights` does something similar, so we need to adjust that too, it seems?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, that's a nice catch with the coordinate spaces — now let's fix it fully and find a place to react on folds and refresh the corresponding data.

File: crates/editor/src/bracket_colorization.rs (hunk 1 above)
Comment (notJoon) [reply crates/editor/src/bracket_colorization.rs]: https://github.com/zed-industries/zed/pull/51108/commits/4a5c1edca552bbf94761eecb1b12936f610158e7

File: crates/editor/src/bracket_colorization.rs (hunk 2 above)
Comment (notJoon) [reply crates/editor/src/bracket_colorization.rs]: https://github.com/zed-industries/zed/pull/51108/commits/2799ef9bebd44721fb9bc452d1cac1d06cd35bdd

File: crates/editor/src/editor.rs (hunk 3 above)
Comment (notJoon) [reply crates/editor/src/editor.rs]: Oh I just missed that one. I applied same logic to `refresh_selected_text_highlights` as well.
https://github.com/zed-industries/zed/pull/51108/commits/b576e62ef0ea41900022d6e45e4bd3933eec24d0

**Review by SomeoneToIgnore — APPROVED** [review]
Great, thank you so much for finding a right fix and writing the test.
