### PR TITLE
extension_host: Fix Windows manifest paths when uploading extensions to WSL remote

### LINKED ISSUE #42731: Windows: Can't upload recompiled extension to WSL remote
### Summary

A freshly recompiled extension cannot be uploaded to WSL (InstallExtension, error:No such file or directory (os error 2))

### Description

Steps to trigger the problem:
1. Clone an extension to your local windows - in this case `zed-extension/elixir`
2. Start Zed and `Install Dev Extension`
3.  Click Rebuild

**Expected Behavior**:
Upload rebuilt extension without any error
**Actual Behavior**:
Aborts with: InstallExtension, error:No such file or directory (os error 2))

### Zed Version and System Specs

Zed: v0.213.1 (Zed Preview) 
OS: Windows 10.0.26200
Memory: 63.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || 32.0.101.7040

### If applicable, attach your `Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log
2025-11-14T15:27:46+01:00 INFO  [extension::extension_builder] compiling Rust extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:27:46+01:00 INFO  [extension::extension_builder] compiling Rust crate for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] compiled Rust crate for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] encoding wasm component for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir written to C:\Users\User\AppData\Local\Zed\extensions\installed\elixir\extension.wasm
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] compiled Rust extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] compiling grammar elixir for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] downloading wasi-sdk to C:\Users\User\AppData\Local\Zed\extensions\build\wasi-sdk
2025-11-14T15:28:04+01:00 INFO  [extension::extension_builder] checking out elixir parser
2025-11-14T15:28:07+01:00 INFO  [extension::extension_builder] compiling elixir parser
2025-11-14T15:28:11+01:00 INFO  [extension::extension_builder] compiled grammar elixir for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:11+01:00 INFO  [extension::extension_builder] compiling grammar heex for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:11+01:00 INFO  [extension::extension_builder] downloading wasi-sdk to C:\Users\User\AppData\Local\Zed\extensions\build\wasi-sdk
2025-11-14T15:28:11+01:00 INFO  [extension::extension_builder] checking out heex parser
2025-11-14T15:28:13+01:00 INFO  [extension::extension_builder] compiling heex parser
2025-11-14T15:28:13+01:00 INFO  [extension::extension_builder] compiled grammar heex for extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:13+01:00 INFO  [extension::extension_builder] finished compiling extension C:\Users\User\AppData\Local\Zed\extensions\installed\elixir
2025-11-14T15:28:13+01:00 INFO  [extension_host] rebuilt extension index in 29.2183ms
2025-11-14T15:28:13+01:00 INFO  [extension_host] extensions updated. loading 0, reloading 1, unloading 0
2025-11-14T15:28:14+01:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: elixir, No such file or directory (os error 2)
2025-11-14T15:28:14+01:00 INFO  [extension_host] Uploading extension elixir
2025-11-14T15:28:14+01:00 WARN  [language] unrecognized capture name 'unary' in Elixir embedding TreeSitter query (suppress this warning by prefixing with '_')
2025-11-14T15:28:14+01:00 WARN  [language] unrecognized capture name '_identifier' in Elixir textobjects TreeSitter query
2025-11-14T15:28:14+01:00 INFO  [extension_host] Finished uploading extension elixir
2025-11-14T15:28:14+01:00 ERROR [remote::remote_client] (remote server) server:error handling message. type:InstallExtension, error:No such file or directory (os error 2)
2025-11-14T15:28:14+01:00 ERROR [crates/extension_host/src/extension_host.rs:1817] RPC request InstallExtension failed: No such file or directory (os error 2)
2025-11-14T15:28:34+01:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) Iris(R) Xe Graphics", driver_name: "Intel Corporation", driver_info: "32.0.101.7040" }
2025-11-14T15:28:34+01:00 ERROR [crates/gpui/src/platform/windows/platform.rs:228] Access is denied. (0x80070005)

```

</details>

### PR DESCRIPTION
**Pull request by th0jensen**
Closes #42731 

Before you mark this PR as ready for review, make sure that you have:
- [X] Added a solid test coverage and/or screenshots from doing manual testing
- [X] Done a self-review taking into account security and performance aspects
- [X] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Screenshot 2026-03-09 at 5 10 46 PM

Release Notes:

- Fixed Windows path handling in extension manifests to ensure extensions upload correctly to remote environments like WSL.

### CODE REVIEW

File: crates/extension/src/extension_manifest.rs [hunk 1]
```diff
@@ -378,23 +386,61 @@ impl ExtensionManifest {
...
+            .debug_adapters
+            .into_iter()
+            .map(|(name, mut entry)| {
+                entry.schema_path = entry.schema_path.map(normalize).transpose()?;
+                Ok((name, entry))
+            })
+            .collect::<Result<_>>()?;
+
+        Ok(self)
+    }
```
Comment (MrSubidubi) [inline crates/extension/src/extension_manifest.rs]: Do we actually need this method currently? From what it does currently, I think we would not, but happy to stand corrected.

**Review by MrSubidubi — CHANGES_REQUESTED** [review]
Also thanks from my side. Regarding the

> I was very unsure whether or not to add these to RelPath directly or just leave them locally scoped. I opted for the latter since it seemed cleaner and tightens the scope of the PR.

I think it would be better if we could try to shrink the diff here as much as possible and to see how far we can get here if we were to `impl AsRef<Path> for RelPathBuf` - I think we just don't have this currently since we overall use `RelPath` in the codebase mostly. 

Aside from that, left one other comment

File: crates/extension/src/extension_manifest.rs (hunk 1 above)
Comment (th0jensen) [reply crates/extension/src/extension_manifest.rs]: I believe the normalization step here is still needed since the types `RelPath` and `RelPathBuf` themselves don't guarantee that Windows paths are normalized to match POSIX, which the bug fix targets.

We could however do a custom `impl Deserialize for RelPathBuf` and target the actual construction of the manifest, but I tried to stay away from the `utils` crate.

If that's the route we want to go, alongside `impl AsRef<Path> for RelPathBuf`, I can do that! :)

Comment (MrSubidubi) [reply crates/extension/src/extension_manifest.rs]: Yeah I think that sounds like a more future-proof path going forward, so feel free to pursue that route 🙂

File: crates/util/src/rel_path.rs
Comment (th0jensen) [inline crates/util/src/rel_path.rs:69]: @MrSubidubi Could we remove the `PathStyle::Windows` condition here and normalize backslashes for all relative paths, so that Windows-style separators are never stored internally in `RelPath` / `RelPathBuf`?

I think there is some ambiguity at the call site right now, since this function takes the style of the input path rather than enforcing the target/internal representation directly.

File: crates/extension/src/extension_manifest.rs [hunk 2]
```diff
@@ -572,6 +577,23 @@ mod tests {
...
+    #[test]
+    fn test_deserialize_manifest_with_windows_separators() {
+        let manifest: ExtensionManifest = toml::from_str(
+            r#"
+id = "test-manifest"
+name = "Test Manifest"
+version = "0.0.1"
+schema_version = 0
+languages = ["foo\\bar"]
+"#,
```
Comment (MrSubidubi) [inline crates/extension/src/extension_manifest.rs]: Let's use `indoc` here so that it can have the same indentation as the rest

File: crates/util/src/rel_path.rs [hunk 3]
```diff
@@ -333,12 +333,44 @@ impl RelPathBuf {
...
     }
 }
 
+impl From<&str> for RelPathBuf {
+    fn from(value: &str) -> Self {
+        RelPath::unix(&value)
+            .expect("RelPathBuf::from(&str) requires a normalized relative POSIX path")
+            .to_rel_path_buf()
+    }
+}
```
Comment (MrSubidubi) [inline crates/util/src/rel_path.rs]: Can we not use `TryFrom` here instead`

File: crates/util/src/rel_path.rs [hunk 4]
```diff
@@ -333,12 +333,44 @@ impl RelPathBuf {
...
 }
 
+impl<'de> Deserialize<'de> for RelPathBuf {
+    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
+    where
+        D: serde::Deserializer<'de>,
+    {
+        let path = String::deserialize(deserializer)?;
+        let rel_path =
+            RelPath::new(Path::new(&path), PathStyle::Windows).map_err(serde::de::Error::custom)?;
```
Comment (MrSubidubi) [inline crates/util/src/rel_path.rs]: Should we not use `PathStyle::local()` here?

File: crates/util/src/rel_path.rs
Comment (MrSubidubi) [reply crates/util/src/rel_path.rs:69]: Hm, I do not think we can, as we cannot just replace that in non-windows paths

File: crates/extension/src/extension_builder.rs [hunk 5]
```diff
@@ -586,8 +586,11 @@ async fn populate_defaults(
             let language_dir = language_dir?;
             let config_path = language_dir.join(LanguageConfig::FILE_NAME);
             if fs.is_file(config_path.as_path()).await {
-                let relative_language_dir =
-                    language_dir.strip_prefix(extension_path)?.to_path_buf();
+                let relative_language_dir = RelPath::new(
+                    language_dir.strip_prefix(extension_path)?,
+                    PathStyle::local(),
+                )?
+                .into_owned();
```
Comment (MrSubidubi) [inline crates/extension/src/extension_builder.rs]: What about us adding an extension method to `Path` like `to_rel_path_buf` that does just what you are/were doing all around here? Think that could be handy elsewhere too

**Review by MrSubidubi — DISMISSED** [review]

File: crates/util/src/rel_path.rs (hunk 4 above)
Comment (th0jensen) [reply crates/util/src/rel_path.rs]: Manifests with Windows separators won't be normalized on macOS/Linux if we do this.

Screenshot 2026-03-27 at 7 39 59 PM

This is the caller site ambiguity that I was referring to in my comment.

I believe it will still work on Windows (haven't tested) but manifests can still contain Windows path separators on a macOS/Linux host.

If we explicitly target `PathStyle::Windows` here then we're at least compatible with the current API (Windows path separators will be removed on all platforms), and might this get revamped soon? [Roadmap; Beyond 1.0](https://zed.dev/roadmap)

**Comment by th0jensen** [comment]
@MrSubidubi is it possible to have a look at this again? :)

**Comment by reflectronic** [comment]
Sorry for the long delay in re-reviewing. I pushed a small change to propagate some errors upward instead of panicking. The patch looks good to me now.

**Review by reflectronic — APPROVED** [review]

**Comment by reflectronic** [comment]
Thank you
