### PR TITLE
Fix line number whitespace

### LINKED ISSUE #14025: Whitespace indicators disappear when line numbers are toggled off
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed that `editor: toggle line numbers` (<kbd>Cmd</kbd>+<kbd>;</kbd>) impacts the rendering of the whitespace characters in the editor.

Turning line numbers off also turns off the whitespace characters:

https://github.com/zed-industries/zed/assets/1486634/d97bae38-8abe-4b71-8474-65a8a9d587c1

Interestingly, it seems like it is just the indentation whitespace characters. In the video above, notice how when using `"show_whitespaces": "all"` the whitespace between individual characters is still rendered, even when the indentation whitespace is gone.

### Environment

Zed: v0.144.0 (Zed Nightly b3dad0bfcbb21496e63ae3524cb649caac4bc8c0)
OS: macOS 14.4.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by rtfeldman**
Closes #14025

https://github.com/user-attachments/assets/24b3f321-8246-4203-9510-66a7cf3d22f0

Release Notes:

- Fixed bug where toggling line numbers would incorrectly hide whitespace indicators.

### CODE REVIEW

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -5085,6 +5094,8 @@ impl Element for EditorElement {
                         .buffer_rows(start_row)
                         .take((start_row..end_row).len())
                         .collect::<Vec<_>>();
+                    let is_row_soft_wrapped =
+                        |row| buffer_rows.get(row).copied().flatten().is_none();
```
Comment (rtfeldman) [inline crates/editor/src/element.rs:5098]: This is where we actually use `buffer_rows` to figure out whether we've soft wrapped or not.
