### PR TITLE
markdown_preview: Enable parser options individually

### LINKED ISSUE #50170: Markdown not rendering content in preview mode
### Reproduction steps

Image

Image

### Current vs. Expected behavior

It should show up the content in preview mode

### Zed version and system specs

Zed: v0.225.9+stable.181.cbc2b428b9003b31077f91f06f8912880b1dbcf4 (Zed) 
OS: macOS 26.3
Memory: 16 GiB
Architecture: aarch64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by yeskunall**
Closes #50170.

Before you mark this PR as ready for review, make sure that you have:
- [x] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [x] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Release Notes:

- Enable parser options individually to avoid rendering issues

### CODE REVIEW

File: crates/markdown_preview/src/markdown_parser.rs [hunk 1]
```diff
@@ -14,15 +14,24 @@ use std::{
 };
 use ui::SharedString;
 
+const PARSE_OPTIONS: Options = Options::ENABLE_TABLES
```
Comment (MrSubidubi) [inline crates/markdown_preview/src/markdown_parser.rs]: Since this matches with what is found in the markdown crate, can we not instead re-export the options from the markdown crate and use that here instead? We want to migrate to that crate anyway at some point, so perhaps better to introduce the dependency here then?

Comment (yeskunall) [reply crates/markdown_preview/src/markdown_parser.rs]: > We want to migrate to that crate anyway at some point

Ah, OK that’s good to know.

> Since this matches with what is found in the markdown crate, can we not instead re-export the options from the markdown crate and use that here instead?

Perfectly sound and should be possible -- I’ll do that. Thanks Finn!

File: crates/markdown_preview/src/markdown_parser.rs [hunk 2]
```diff
@@ -3076,6 +3074,26 @@ More text
         );
     }
 
+    #[gpui::test]
```
Comment (yeskunall) [inline crates/markdown_preview/src/markdown_parser.rs:3077]: Left the regression tests I added intact since they test the preview-specific parsing behavior.

LMK if there is a better way/place to write these tests.

Comment (MrSubidubi) [reply crates/markdown_preview/src/markdown_parser.rs:3077]: Think that's fine to keep them here, especially with the prospect of the migration 🔜 ™️

**Review by MrSubidubi — APPROVED** [review]
