### PR TITLE
language: Select language based on longest matching path extension

### LINKED ISSUE #8408: Reconcile multiple language match by suffix length
### Check for existing issues

- [X] Completed

### Describe the feature

Inspired by https://github.com/zed-industries/zed/issues/7096#issuecomment-1948414691.

# The problem
Today, when multiple `LanguageMatcher`'s path_suffix match a file,  one random language will be chosen (see [language_registry.rs get_or_load_language function](https://github.com/zed-industries/zed/blob/ffdda588b41f7d9d270ffe76cab116f828ad545e/crates/language/src/language_registry.rs#L347-L358)). While this simple setting works well for most of the cases, it's not robust enough. E.g. there's no way to distinguish `.php` or `.blade.php`.

# Proposed fix
To make it simple, I propose changing [the callback function](https://github.com/zed-industries/zed/blob/ffdda588b41f7d9d270ffe76cab116f828ad545e/crates/language/src/language_registry.rs#L342) so that it returns a tuple of boolean + max matched suffix length among all the suffixes. When there're multiple matches, the language with the longest suffix wins.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #10997: When implementing a Zed extension, path_suffixes doesn't support dots (ex: filename.cf.sub)
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My extension:

https://github.com/olehermanse/zed-cfengine

Is not highlighting some of our test files which use the `.cf.sub` extension:

https://github.com/cfengine/core/blob/d7227da3cb47cbe8b6079559acac3cb6374f1a10/tests/acceptance/run_with_server.cf.sub

Even though I added it to the `path_suffixes`:

https://github.com/olehermanse/zed-cfengine/commit/f854236be02efc5cace5a731171081730da8fffc

As a programmer, I can understand why Zed would consider the extension / suffix anything after the last `.`, however as a user / extension author, I'd expect what I tried to do to "just work". Essentially, I'd expect the logic for `path_suffixes` to match any files which end with one of those strings (even if one of those strings include a `.`).

**Workaround:** I guess I could add just `sub` to `path_suffixes` to make it work for myself, but that doesn't "feel right" as it would conflict with any other language files which might end in `.sub`.

I found this other issue which seems almost the same, except it talks about wildcards:

https://github.com/zed-industries/zed/issues/8466

### Environment

Zed: v0.131.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by claytonrcarter**
Closes #8408  
Closes #10997

This is a reboot of [my original PR](https://github.com/zed-industries/zed/pull/11697) from last year. I believe that I've addressed all the comments raised in that original review, but Zed has changed a lot in the past year, so I'm sure there will be some new stuff to consider too.

- updates the language matching and lookup to consider not just "does the  suffix/glob match" but also "... and is it the longest such match"
- adds a new `LanguageCustomFileTypes` struct to pass user globs from settings  to the registry
- _minor/unrelated:_ updates a test for the JS extension that wasn't actually  testing what is intended to
- _minor/unrelated:_ removed 2 redundant path extensions from the JS lang  extension

**Languages that may use this**

- Laravel Blade templates use the `blade.php` compound extension
- [apparently](https://github.com/zed-industries/zed/issues/10765#issuecomment-2091293304)  Angular uses `component.html`
  - see also https://github.com/zed-industries/extensions/issues/169
- _hypothetically_ someone could publish a "JS test" extension w/ custom  highlights and/or snippets; many JS tests use `test.js` or `spec.js`

**Verifying these changes**

I added a number of assertions for this new behavior, and I also confirmed that the (recently patched) [Laravel Blade extension](https://github.com/bajrangCoder/zed-laravel-blade) opens as expected for `blade.php` files, whereas on `main` it does not.

cc @maxbrunsfeld (reviewed my original PR last year), @osiewicz and @MrSubidubi (have recently been in this part of the code) 

Release Notes:

- Added support for "compound" file extensions in language extensions, such  `blade.php` and `component.html`. Closes #8408 and #10997.

### CODE REVIEW

File: crates/language/src/language_registry.rs [hunk 1]
```diff
@@ -167,18 +164,12 @@ impl AvailableLanguage {
     }
 }
 
-#[derive(Copy, Clone, Default, PartialEq, Eq, PartialOrd, Ord)]
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:170]: These implementations are no longer needed because I removed the `<` enum comparison in favor an exhaustive `match`.

File: crates/language/src/language_registry.rs [hunk 2]
```diff
@@ -167,18 +164,12 @@ impl AvailableLanguage {
...
     #[default]
     Undetermined,
-    PathOrContent,
-    UserConfigured,
-}
-
-impl LanguageMatchPrecedence {
-    fn best_possible_match(&self) -> bool {
-        *self == LanguageMatchPrecedence::UserConfigured
-    }
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:181]: Because we need to consider the length of the extension/glob, we can no longer determine the "best possible" match based only on the enum variant. This means that the short-circuiting `fold_while` had to be reduced to traditional `fold`, and that this method was no longer needed.

File: crates/language/src/language_registry.rs [hunk 3]
```diff
@@ -621,9 +612,14 @@ impl LanguageRegistry {
...
-                && UniCase::new(&language_name.0) == name)
-                .then_some(LanguageMatchPrecedence::PathOrContent)
+            match current_best_match {
+                LanguageMatchPrecedence::Undetermined if UniCase::new(&language_name.0) == name => {
+                    Some(LanguageMatchPrecedence::PathOrContent(name.len()))
+                }
+                LanguageMatchPrecedence::Undetermined
+                | LanguageMatchPrecedence::UserConfigured(_)
+                | LanguageMatchPrecedence::PathOrContent(_) => None,
+            }
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:622]: @MrSubidubi can you take a peek at this change, as well the change to to `language_for_name_or_extension()`? 

I hadn't changed these in my initial implementation, but the recent refactor to use `LanguageMatchPrecedence` meant I needed to update this. I think that this is correct (and tests are passing) but I'd love a second opinion.

My understanding of this is: return a "better match" for a language name only if the name matches and there is no current match. This makes sense to me given the assumption that lang names are unique.

File: crates/language/src/language_registry.rs [hunk 4]
```diff
@@ -634,13 +630,23 @@ impl LanguageRegistry {
...
+
+            match current_best_match {
+                LanguageMatchPrecedence::Undetermined => {
+                    name_matches().then_some(LanguageMatchPrecedence::PathOrContent(string.len()))
+                }
+                LanguageMatchPrecedence::PathOrContent(len) => (name_matches()
+                    && string.len() > len)
+                    .then_some(LanguageMatchPrecedence::PathOrContent(string.len())),
+                LanguageMatchPrecedence::UserConfigured(_) => None,
+            }
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:649]: The gist here is: return a "better match" for a language name if the name matches and there is no current match, or if the name matches and is longer than the existing path match.

File: crates/language/src/language_registry.rs [hunk 5]
```diff
@@ -709,21 +706,44 @@ impl LanguageRegistry {
...
+                    acc
+                }
+            };
+
             let path_matches_default_suffix = || {
-                config
-                    .path_suffixes
-                    .iter()
-                    .any(|suffix| path_suffixes.contains(&Some(suffix.as_str())))
+                let len = config.path_suffixes.iter().fold(0, matching_suffix_len);
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:721]: I suppose that this could be short circuited: if any of the path suffixes registered for a lang match, perhaps we can assume that the language doesn't also include another longer match later in the list? Most languages don't register too many suffixes, but some do: `bash` has 19, C++ has 15, JS and TS both have 4, markdown has 5, etc. C, Go, Rust, PHP only have 1, fwiw.

File: crates/language/src/language_registry.rs [hunk 6]
```diff
@@ -709,21 +706,44 @@ impl LanguageRegistry {
...
+                            // if the glob matched, use the length of its pattern
+                            matches
+                                .iter()
+                                .filter_map(|i| custom_suffixes.patterns.get(*i))
+                                .fold(0, |acc, suffix| acc.max(suffix.len()))
+                        } else {
+                            // otherwise try to use the glob patterns as extensions, and
+                            // see if the file ends with any of them
+                            custom_suffixes.patterns.iter().fold(0, matching_suffix_len)
+                        };
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:741]: This is reason I added the `LanguageCustomFileTypes` struct: the glob matcher could be made up of more than 1 glob pattern, and `is_match()` and `is_match_candidate()` only say if any pattern matched. `matches()` returns which patterns matched, which then allows us to examine each matched pattern to see how long it was.

File: crates/language/src/language_registry.rs [hunk 7]
```diff
@@ -735,17 +755,33 @@ impl LanguageRegistry {
...
+                    } else if let Some(len) = path_matches_default_suffix() {
+                        Some(LanguageMatchPrecedence::PathOrContent(len))
+                    } else if content_matches() {
+                        Some(LanguageMatchPrecedence::PathOrContent(1))
+                    } else {
+                        None
+                    }
                 }
-                _ => None,
+                LanguageMatchPrecedence::UserConfigured(_) => None,
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:784]: I hope that my implementation of this preserves the "lazy matching" approach that was recently adopted. I don't like that it's so much more verbose, but I couldn't see a way to use exhaustive pattern matching without also repeating calls to some of the callbacks. My intent is that each of the callbacks is only called 1x per iteration, as before.

File: crates/language/src/language_registry.rs [hunk 8]
```diff
@@ -763,28 +799,57 @@ impl LanguageRegistry {
...
+                    )
+                    | (
+                        Some(LanguageMatchPrecedence::PathOrContent(new_len)),
+                        LanguageMatchPrecedence::UserConfigured(current_len),
+                    ) => {
+                        if new_len > current_len {
+                            language_score.map(|new_score| (language.clone(), new_score))
+                        } else {
+                            best_language_match
+                        }
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:834]: I very much prefer exhaustive pattern matches, but I very much dislike this verbosity. 😄 I think I'll add a few comments to better call out the different cases.

**Comment by claytonrcarter** [comment]
@maxbrunsfeld @osiewicz Nudging this, gently and politely. 😄 I've been using it w/o issue for the past few weeks, it will close 2 long standing issues, and staff have demonstrated interest in this feature/change several times in the past.

Input from @MrSubidubi would be welcome too, of course, esp as this change interacts with your recent changes in this area.

Thank you for taking a peek, if you're able!

File: crates/language/src/language_registry.rs (hunk 3 above)
Comment (MrSubidubi) [reply crates/language/src/language_registry.rs:627]: Yep, sounds right, whilst the uniqueness of a language name is currently not enforced, it is definitely assumed. Thus, this remains correct.

File: crates/language/src/language_registry.rs [hunk 9]
```diff
@@ -655,13 +651,23 @@ impl LanguageRegistry {
...
-            .then_some(LanguageMatchPrecedence::PathOrContent)
+                        .any(|suffix| UniCase::new(suffix) == string)
+            };
+
+            match current_best_match {
+                LanguageMatchPrecedence::Undetermined => {
+                    name_matches().then_some(LanguageMatchPrecedence::PathOrContent(string.len()))
+                }
+                LanguageMatchPrecedence::PathOrContent(len) => (name_matches()
+                    && string.len() > len)
```
Comment (MrSubidubi) [inline crates/language/src/language_registry.rs:667]:
```suggestion
                LanguageMatchPrecedence::PathOrContent(len) => (string.len() > len
                    && name_matches())
```
We can possibly swap this since the first check is slightly less expensive

File: crates/language/src/language_registry.rs (hunk 7 above)
Comment (MrSubidubi) [reply crates/language/src/language_registry.rs:805]: Yeah, the verbosity was already something I struggled with (and definitely somewhat a downsight of my approach), which obviously becomes much worse with this complexity added. Sorry for that 😅

**Comment by MrSubidubi** [comment]
Small and potentially slightly off-topic coment: 

I would possibly argue that in the long-run, glob patterns should also be available for language matching. There are some languages that would benefit from glob matches already and the ambiguity of `file_suffixes` is probably somthing you had to deal with a lot here.
Generally, I think it might be safe to say that if a glob pattern matches, it might be a better match than just a suffix match and we could potentially also incorporate https://github.com/zed-industries/zed/pull/11697#discussion_r1605598630 more easily. Admittedly, I might also be missing something here, feel free to point that out should that be the case.

But then, I would guess that this is not something for now but rather something to keep in mind for later. With the tests you added, I think it would be easy to add this in later whilst ensuring that we do not regress on previous behavior.

(Also, please keep in mind this is just my opinion and the team might have a different opinion on this)

File: crates/language/src/language_registry.rs (hunk 9 above)
Comment (claytonrcarter) [reply crates/language/src/language_registry.rs]: Good call, done!

File: crates/language/src/language_registry.rs [hunk 10]
```diff
@@ -756,17 +776,33 @@ impl LanguageRegistry {
...
-                LanguageMatchPrecedence::PathOrContent | LanguageMatchPrecedence::Undetermined
-                    if path_matches_custom_suffix() =>
-                {
-                    Some(LanguageMatchPrecedence::UserConfigured)
+                LanguageMatchPrecedence::PathOrContent(current_len) => {
+                    if let Some(len) = path_matches_custom_suffix() {
+                        Some(len)
+                            // >= because user config should win tie with system ext len
+                            .filter(|len| len >= &current_len)
+                            .map(LanguageMatchPrecedence::UserConfigured)
```
[the remark this answers is not in the document]
Comment (claytonrcarter) [reply crates/language/src/language_registry.rs]: Oh, yes. More compact and readable, too. 👍 Thank you!

**Comment by claytonrcarter** [comment]
> glob patterns should also be available for language matching

Yes, I found myself wondering the same thing, but also felt that it was out of scope here. 

Thank you for checking this out!

**Comment by maxbrunsfeld** [comment]
Thanks for following up @claytonrcarter . Reviewing now; I might push some minor stylistic changes.

File: crates/language/src/language_registry.rs [hunk 11]
```diff
@@ -710,18 +716,9 @@ impl LanguageRegistry {
...
         let filename = path.file_name().and_then(|name| name.to_str());
-        // `Path.extension()` returns None for files with a leading '.'
-        // and no other extension which is not the desired behavior here,
-        // as we want `.zshrc` to result in extension being `Some("zshrc")`
-        let extension = filename.and_then(|filename| filename.split('.').next_back());
-        let path_suffixes = [extension, filename, path.to_str()];
-        let path_suffixes_candidates = path_suffixes
-            .iter()
-            .filter_map(|suffix| suffix.map(globset::Candidate::new))
-            .collect::<SmallVec<[_; 3]>>();
```
Comment (maxbrunsfeld) [inline crates/language/src/language_registry.rs:724]: I think we should restore this. The purpose was to avoid repeatedly constructing match candidates (which is done by `GlobSet::matches`).

File: crates/language/src/language_registry.rs [hunk 12]
```diff
@@ -730,21 +727,44 @@ impl LanguageRegistry {
...
+                } else {
+                    acc
+                }
+            };
+
             let path_matches_default_suffix = || {
-                config
-                    .path_suffixes
-                    .iter()
-                    .any(|suffix| path_suffixes.contains(&Some(suffix.as_str())))
```
Comment (maxbrunsfeld) [inline crates/language/src/language_registry.rs:737]: I think you should keep the structure that was there before, but store the length of the matching suffix.

File: crates/language/src/language_registry.rs (hunk 6 above)
Comment (maxbrunsfeld) [reply crates/language/src/language_registry.rs:762]: I don't think you want to check the length of the glob pattern; we want the length of the suffix that matched (either the length of the file extension, the length of the filename, or the length of the entire path). So you don't need to store off the glob patterns.

File: crates/language/src/language_settings.rs [hunk 13]
```diff
@@ -63,7 +63,13 @@ pub struct AllLanguageSettings {
     pub edit_predictions: EditPredictionSettings,
     pub defaults: LanguageSettings,
     languages: HashMap<LanguageName, LanguageSettings>,
-    pub(crate) file_types: FxHashMap<Arc<str>, GlobSet>,
+    pub(crate) file_types: FxHashMap<Arc<str>, LanguageCustomFileTypes>,
```
Comment (maxbrunsfeld) [inline crates/language/src/language_settings.rs:66]: Let's put this back to just a `GlobSet` - as mentioned above, we don't need to store the patterns themselves - a glob pattern is not something that we want to compare the length of. The length to compare is the length of the actual path suffix that matched a pattern.

**Review by maxbrunsfeld — CHANGES_REQUESTED** [review]
I noted some changes that I think we need to make to this. Overall, we need to avoid discarding the performance optimization to precompute the glob match candidates, and tweak the semantics of the match length for user-defined globs.

File: crates/language/src/language_registry.rs (hunk 11 above)
Comment (claytonrcarter) [reply crates/language/src/language_registry.rs:724]: Done. Note that I changed this so that `path_suffixes` is now a small vec of `(suffix, candidate)` tuples. This makes is easy to keep matching on the candidate, while also making it easy to reference the suffix for that candidate.

File: crates/language/src/language_registry.rs (hunk 12 above)
Comment (claytonrcarter) [reply crates/language/src/language_registry.rs:737]: OK, done.

File: crates/language/src/language_settings.rs (hunk 13 above)
Comment (claytonrcarter) [reply crates/language/src/language_settings.rs]: Totally fair. This is what derailed me last year when I first attempted this: The change to add glob support was added after my initial attempt and I couldn't get my head around how to handle that change. I've reverted this change, so this PR no longer touches this file at all.

File: crates/language/src/language_registry.rs (hunk 6 above)
Comment (claytonrcarter) [reply crates/language/src/language_registry.rs]: Done!

**Comment by claytonrcarter** [comment]
@maxbrunsfeld Thank you for the review. I think I understood what you are asking for, but please correct me if I'm wrong:

My initial implementation was focused on comparing the length of the "pattern" that was being used for matching (ie the file extension or glob pattern), but this latest version is now storing the length of what that pattern actually matched (ie from the list of extension/filename/path in `language_registry::language_for_file_internal()`.

An example:
- extension 1 is looking for `path_suffixes = ["php"]`
- extension 2 is looking for `path_suffixes = ["blade.php"]`
- I open a file called `templates/index.blade.php`

Both extension 1 and extension 2 will be compared (in `language_registry::language_for_file_internal()`) against a list built from the file name, eg `["php", "index.blade.php", "templates/index.blade.php"]`

In my previous version, I was comparing the length of the matched element from `path_suffixes`; so 3 for ext 1 (because "php" matched the filename) and 9 for ext 2 (because "blade.php" matched the filename).

In this version, we should be comparing the length of the matched element from `language_registry::language_for_file_internal()`;
- ext 1 will match the first element (because `"php" == "php`) and will score 3
- ext 2 will not match the first element, but will match the second, (because `"index.blade.php".ends_with("blade.php")`) and will score 15

I hope that this is close to what you are asking for; please advise it it's not! The tests are passing on this, and I've tested it *a little* just now, but I'll put it through its paces tomorrow and see if any issues pop up.

Thank you again for the review on this!

File: crates/language/src/language_registry.rs [hunk 14]
```diff
@@ -731,20 +737,37 @@ impl LanguageRegistry {
...
+                let len =
+                    config
+                        .path_suffixes
+                        .iter()
+                        .fold(0, |acc: usize, path_suffix: &String| {
+                            let ext = ".".to_string() + path_suffix;
+
+                            let matched_suffix_len = path_suffixes
+                                .iter()
+                                .find(|(suffix, _)| suffix.ends_with(&ext) || suffix == path_suffix)
```
Comment (claytonrcarter) [inline crates/language/src/language_registry.rs:749]: This latest version is implicitly depending on the above defined `path_suffixes` to be sorted by length, so that find will find return the shortest matching element, and prevent us having to look at every element. I may add a `debug_assert!()` for that.

**Comment by claytonrcarter** [comment]
I’ve been using this latest implementation for the past day or two and haven’t noticed any issues. I think it’s ready for another look.

**Comment by maxbrunsfeld** [comment]
Yes, this is exactly what I was saying. And I believe that this now preserves the optimizations that have been made to this code. Thanks @claytonrcarter !

**Review by maxbrunsfeld — APPROVED** [review]
