### PR TITLE
markdown_preview: Fix Ctrl+S saving checkbox toggle state

### LINKED ISSUE #46901: Unable to save source Markdown file via Ctrl+S when focused in preview pane after toggling task items
### Reproduction steps

1. Open a Markdown file containing task list items in Zed, e.g.:  
   ```markdown  
   - [ ] Play Honkai Impact 3rd  
   - [ ] Finish work  
   ```  
2. Open the Markdown preview pane using `Ctrl+Shift+V`.  
3. While focused in the preview pane, hold `Ctrl` and click a task checkbox to toggle its state (e.g., from unchecked `[ ]` to checked `[x]`).  
4. Observe that the underlying source file updates automatically with the new state.  
5. With the preview pane still focused, press `Ctrl+S` to attempt saving changes.  

### Current vs. Expected behavior

**Current Behavior**:  
- `Ctrl+S` has no effect when the preview pane is focused.  
- Users must manually switch focus back to the source Markdown editor tab before saving.  

**Expected Behavior**:  
- When the preview pane is focused and the source Markdown file has unsaved modifications (e.g., after toggling task items via `Ctrl+click`), pressing `Ctrl+S` should immediately save the source file, maintaining workflow continuity.

### Zed version and system specs

Zed: v0.219.4+stable.119.5595f7ce23d51a58eb66dd025a487bbd6c75dad1 (Zed) 
OS: Linux Wayland opensuse-tumbleweed 20250822
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 25.1.7

### PR DESCRIPTION
**Pull request by Priyansh4444**
Changes Made:

- Adding the `Item::can_save()`, `save()`, `save_as()`, `can_save_as()` functions to help the Editor save when a checkbox is toggled
- Small refactor to seperate checkbox toggle and refreshing preview
- Adding support for both `/...` and `\\...` for windows users. [NOTE: I no longer own a window's machine and I am unsure if this is correct, and will fix it immediately if this is wrong]
- Resolving preview paths, strips out the fragment, and image paths are coalesced to None if they don't exist
- Adding Tests for the added behaviour  [NOTE: would love feedback since this is the first time I am writing tests, and had a bit of assistance from an AI, but manually reviewed the code and ran the application and it seemed fine]

Self-Review Checklist:

- [X] I've reviewed my own diff for quality, security, and reliability
- [X] Unsafe blocks (if any) have justifying comments
- [X] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [X] Tests cover the new/changed behavior
- [X] Performance impact has been considered and is acceptable

Closes #46901

Release Notes:

- Fixed Crtl+S saving while toggling checkbox in preview mode

### CODE REVIEW

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 1]
```diff
@@ -726,15 +754,16 @@ fn resolve_preview_image(
         .map(|decoded| decoded.into_owned())
         .unwrap_or_else(|_| dest_url.to_string());
 
-    let decoded_path = Path::new(&decoded);
-
-    if let Ok(relative_path) = decoded_path.strip_prefix("/") {
+    let workspace_relative_path = decoded.trim_start_matches(['/', '\\']);
+    if workspace_relative_path.len() != decoded.len() {
```
Comment (osiewicz) [inline crates/markdown_preview/src/markdown_preview_view.rs:758]:
```suggestion
    if let Some(stripped) = ['/', '\\'].iter().find_map(|prefix| decoded_path.strip_prefix(prefix)) {
```

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 2]
```diff
@@ -745,9 +774,13 @@ fn resolve_preview_image(
...
-    Some(ImageSource::Resource(Resource::Path(Arc::from(
-        path.as_path(),
-    ))))
+    if path.exists() {
+        Some(ImageSource::Resource(Resource::Path(Arc::from(
+            path.as_path(),
+        ))))
+    } else {
+        None
+    }
```
Comment (osiewicz) [inline crates/markdown_preview/src/markdown_preview_view.rs:783]:
```suggestion
    path.exists().then(|| ImageSource::Resource(Resource::Path(Arc::from(
            path.as_path(),
        ))))
```

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 3]
```diff
@@ -632,27 +633,44 @@ impl MarkdownPreviewView {
...
     }
+
+    fn apply_checkbox_toggle_to_editor(
+        editor: &Entity<Editor>,
+        source_range: std::ops::Range<usize>,
+        new_checked: bool,
+        cx: &mut App,
+    ) {
+        let task_marker = if new_checked { "[x]" } else { "[ ]" };
+        editor.update(cx, |editor, cx| {
```
Comment (osiewicz) [inline crates/markdown_preview/src/markdown_preview_view.rs:656]: It would be beneficial to check whether the range we're overwriting has a flipped state (e.g. if new_checked is true, then source_range contents should be `[ ]` and vice-versa). Maybe we could even have a `debug_assert`?

File: crates/markdown_preview/src/markdown_preview_view.rs [hunk 4]
```diff
@@ -965,98 +1044,199 @@ mod tests {
...
+        let save_task = multi_workspace
+            .update(cx, |multi_workspace, window, cx| {
+                let workspace: Entity<Workspace> = multi_workspace.workspace().clone();
+                let view_handle = preview.downgrade();
+                preview.update(cx, |preview, cx| {
+                    let editor = preview.active_editor.as_ref().unwrap().editor.clone();
+                    MarkdownPreviewView::apply_checkbox_toggle_to_editor(&editor, 2..5, true, cx);
+                });
+                MarkdownPreviewView::refresh_preview(view_handle, window, cx);
+
```
Comment (osiewicz) [inline crates/markdown_preview/src/markdown_preview_view.rs:1191]: You should prolly check whether the markdown preview view is focused at this point.

**Review by osiewicz — CHANGES_REQUESTED** [review]

File: crates/markdown_preview/src/markdown_preview_view.rs (hunk 3 above)
Comment (Priyansh4444) [reply crates/markdown_preview/src/markdown_preview_view.rs:671]: Added a `debug_assert_eq!` before the edit to verify the source range contains the opposite checkbox marker (`[ ]` vs `[x]`) as a safety check

File: crates/markdown_preview/src/markdown_preview_view.rs (hunk 4 above)
Comment (Priyansh4444) [reply crates/markdown_preview/src/markdown_preview_view.rs:1312]: Added the focus check in test!

**Comment by Priyansh4444** [comment]
Thank you so much for the comments @osiewicz, it is ready for review again!

**Review by osiewicz — APPROVED** [review]
Thank you!
