### PR TITLE
Ignore user config when checking remote git URL for dev extensions

### LINKED ISSUE #48163: Extension rebuild fails during development due to git URL redirect in gitconfig
### Reproduction steps

Re-report of #10569

1. `rm -rf grammars`
2. Click "Install dev extension" + choose repo
3. Click "Rebuild"

### Current vs. Expected behavior

I expect it to rebuild successfully. Currently rebuild fails with:
```
failed to compile grammar 'alex'

Caused by:
    grammar directory '/Users/bchinn/Library/Application Support/Zed/extensions/installed/alex/grammars/alex' already exists, but is not a git clone of 'https://github.com/jedimahdi/tree-sitter-alex.git'
```

I see the source code: https://github.com/zed-industries/zed/blob/0e118ac9ae0521a36355b605db979511861f55cb/crates/extension/src/extension_builder.rs#L292-L314

If I run the command:

```console
$ git --git-dir '/Users/bchinn/Library/Application Support/Zed/extensions/installed/alex/grammars/alex/.git' remote -v
origin	git@github.com:jedimahdi/tree-sitter-alex.git (fetch)
origin	git@github.com:jedimahdi/tree-sitter-alex.git (push)
```

This indeed does not match my repo:
```toml
[grammars.alex]
repository = "https://github.com/jedimahdi/tree-sitter-alex.git"
rev = "b69608039fa762a6e25e39dcde13fb5b863a8086"
```

The issue is probably my git config:
```ini
[url "git@github.com:"]
insteadOf = https://github.com/
```

The logic should probably be fixed to suppress URL rewrites.

### Zed version and system specs

Zed: v0.221.4+stable.137.128478628237a6d03a6890c810d21b55d3250a70 (Zed) 
OS: macOS 26.2
Memory: 16 GiB
Architecture: aarch64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2026-02-01T14:54:37-08:00 INFO  [extension::extension_builder] compiling grammar alex for extension /Users/bchinn/repos/zed-extension-alex
2026-02-01T14:54:37-08:00 INFO  [extension::extension_builder] downloading wasi-sdk to /Users/bchinn/Library/Application Support/Zed/extensions/build/wasi-sdk
2026-02-01T14:54:37-08:00 INFO  [extension::extension_builder] checking out alex parser
2026-02-01T14:54:38-08:00 INFO  [extension::extension_builder] compiling alex parser
2026-02-01T14:54:39-08:00 INFO  [extension::extension_builder] compiled grammar alex for extension /Users/bchinn/repos/zed-extension-alex
2026-02-01T14:54:39-08:00 INFO  [extension::extension_builder] finished compiling extension /Users/bchinn/repos/zed-extension-alex
2026-02-01T14:54:39-08:00 INFO  [extension_host] rebuilt extension index in 19.433125ms
2026-02-01T14:54:39-08:00 INFO  [extension_host] extensions updated. loading 1, reloading 0, unloading 0
2026-02-01T14:54:52-08:00 INFO  [extension::extension_builder] compiling grammar alex for extension /Users/bchinn/Library/Application Support/Zed/extensions/installed/alex
2026-02-01T14:54:52-08:00 INFO  [extension::extension_builder] downloading wasi-sdk to /Users/bchinn/Library/Application Support/Zed/extensions/build/wasi-sdk
2026-02-01T14:54:52-08:00 INFO  [extension::extension_builder] checking out alex parser
2026-02-01T14:54:52-08:00 ERROR [crates/extension_host/src/extension_host.rs:1063] failed to compile grammar 'alex'

Caused by:
    grammar directory '/Users/bchinn/Library/Application Support/Zed/extensions/installed/alex/grammars/alex' already exists, but is not a git clone of 'https://github.com/jedimahdi/tree-sitter-alex.git'

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by brandonchinn178**
## Context

Fixes #48163

Also update the logic from `git remote -v` + manually parse => `git remote get-url origin`

Not sure the best way to test this

## Self-Review Checklist

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [ ] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Release Notes:

- Fixed rebuilding dev extensions when user git config contains url rewriting rules

### CODE REVIEW

File: crates/extension/src/extension_builder.rs [hunk 1]
```diff
@@ -296,16 +296,12 @@ impl ExtensionBuilder {
             let remotes_output = util::command::new_command("git")
                 .arg("--git-dir")
                 .arg(&git_dir)
-                .args(["remote", "-v"])
+                .args(["remote", "get-url", "origin"])
+                .env("GIT_CONFIG_GLOBAL", "/dev/null")
```
Comment (smitbarmase) [inline crates/extension/src/extension_builder.rs:300]: Instead of overriding global config here, which feels way too broad for fixing this (it might lead to other side effects for other users who might have various different kinds of configuration there). Can we somehow ask Git to get `insteadOf` setting, and handle that case explicitly?

**Review by smitbarmase — CHANGES_REQUESTED** [review]
Thanks, I have a suggestion:

File: crates/extension/src/extension_builder.rs (hunk 1 above)
Comment (brandonchinn178) [reply crates/extension/src/extension_builder.rs:300]: I actually think global is the correct thing here. If a user creates an alias named `remote` that does something completely different, you definitely don't want that either. Instead of adding a fix for every possible setting that might mess up this logic, why not force git to operate completely vanilla?

I see this as similar to allowlist vs blocklist. Start from an empty slate and add user configs that we actually want applied, instead of allowing all user config and working around each one that causes problems here.

**Review by smitbarmase — APPROVED** [review]
Thanks, that makes sense. I think it wouldn't be the right approach for, say, `fetch` where user config like `credential.helper` or `http.proxy` will matter for us to preserve that, but in this case, it shouldn't harm.
