### PR TITLE
google_ai: Update Gemini models

### LINKED ISSUE #43040: AI: Error - Gemini 2.5 Flash Lite
### Summary

The following error occurs when using the Gemini 2.5 Flash Lite model.

### Description

```json
failed to stream completion: error during streamGenerateContent, status code: 404, body: {
  "error": {
    "code": 404,
    "message": "models/gemini-2.5-flash-lite-preview-06-17 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.",
    "status": "NOT_FOUND"
  }
}
```

This issue appears to be caused by the end-of-support for the `gemini-2.5-flash-lite-preview-06-17` model on **November 18**.

Related Link: https://ai.google.dev/gemini-api/docs/changelog#11-04-2025

It is expected that this issue can be resolved by changing the `gemini-2.5-flash-lite-preview-06-17` model to `gemini-2.5-flash-lite-preview-09-2025`, or by using another method. (I am not sure.)

### Model Provider Details
- Provider: Gemini
- Model Name: Gemini 2.5 Flash Lite
- Mode: Agent Panel, Inline Assistant, Terminal Assistant

### Zed Version and System Specs

Zed: v0.212.7 (Zed) 
OS: Linux Wayland fedora 43
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 570 Series (RADV POLARIS10) || radv || Mesa 25.2.6

### PR DESCRIPTION
**Pull request by jsparkdev**
Closes #43040

Release Notes:

- Remove the end-of-support Gemini 1.5 model from the options.
- Remove the older Gemini 2.0 model from the options.
  - Please let me know if you think it's better to keep it, as it is still a usable model.
- Update the incorrect amounts for some input/output tokens.
- Update the default model to Gemini 2.5 Flash-Lite.
- Rename variant `Gemini3ProPreview` to `Gemini3Pro`

When this PR is merged, users will be able to select the following Gemini models.

- 2.5 Flash
- 2.5 Flash-Lite
- 2.5 Pro
- 3 Pro

### CODE REVIEW

**Comment by jsparkdev** [comment]
For the Gemini 2.5 Flash and Flash-Lite models, although the better performing `preview-09-2025` version could have been used, I've updated to use the `stable` version for stability in production products.

Please let me know if you have any feedback on this.

File: crates/google_ai/src/google_ai.rs [hunk 1]
```diff
@@ -536,49 +525,34 @@ pub enum Model {
...
-            Self::Gemini15Flash8b => "gemini-1.5-flash-8b",
-            Self::Gemini15Flash => "gemini-1.5-flash",
-            Self::Gemini20FlashLite => "gemini-2.0-flash-lite",
-            Self::Gemini20Flash => "gemini-2.0-flash",
-            Self::Gemini25FlashLitePreview => "gemini-2.5-flash-lite-preview",
+            Self::Gemini25FlashLite => "gemini-2.5-flash-lite",
             Self::Gemini25Flash => "gemini-2.5-flash",
             Self::Gemini25Pro => "gemini-2.5-pro",
-            Self::Gemini3ProPreview => "gemini-3-pro-preview",
+            Self::Gemini3Pro => "gemini-3-pro-preview",
```
Comment (rtfeldman) [inline crates/google_ai/src/google_ai.rs:536]: It's weird that they still only have this available as "-preview" but that is what [the docs](https://ai.google.dev/gemini-api/docs/models) currently say, so I guess that's what we're going with!

**Review by rtfeldman — APPROVED** [review]
Thanks @jsparkdev! 🎉
