### PR TITLE
bedrock: Fix UX bug

### LINKED ISSUE #29072: Agent Panel: bedrock static credentials unusable
### Summary

Any interaction with any of the bedrock models produces the following error:

Image

### Description

Bedrock -- Amazon Nova Micro and Claude 3.5 Haiku

Steps to trigger the problem:
1. Configure Bedrock Agent
2. Restart Zed
3. Choose a Bedrock Model
4. Send any query

Actual Behavior: TimedOutError(5s) gets created
Expected Behavior: Response received

### Zed Version and System Specs

Zed: v0.182.11 (Zed) 
OS: macOS 15.3.1
Memory: 16 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by 5herlocked**
Closes #29072, #28390, 

Release Notes:

- AWS Bedrock: Fixed case where user couldn't delete manually added AWS credentials.

### CODE REVIEW

File: crates/language_models/src/provider/bedrock.rs [hunk 1]
```diff
@@ -319,6 +288,7 @@ impl LanguageModelProvider for BedrockLanguageModelProvider {
 
         for model in bedrock::Model::iter() {
             if !matches!(model, bedrock::Model::Custom { .. }) {
+                // ToDo: Sonnet 3.7 vs. 3.7 Thinking bug is here
```
Comment (maxdeviant) [inline crates/language_models/src/provider/bedrock.rs:291]:
```suggestion
                // TODO: Sonnet 3.7 vs. 3.7 Thinking bug is here.
```

**Review by maxdeviant — APPROVED** [review]
Thank you!

And sorry for the delay.
