### PR TITLE
windows: Fix fs watch when file doesn't exist or is a symlink

### LINKED ISSUE #22659: Unable to toggle items on the Welcome page on Windows
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There are two issues here:

1. Currently, we don't watch the parent directory of a file if the file doesn't exist. As a result, on the first start of Zed, when `settings.json` hasn't been created yet (it gets created later, but the watcher doesn't detect it), the Welcome page fails to accept toggle clicks. Ironically, because the Welcome page is shown on the first launch, this issue likely affects all users.

2. Symlinked files are currently not being watched on Windows, causing the UI to become unresponsive when `settings.json` is a symlink.

You can create a symlink on Windows using the Command Prompt.

For an absolute symlink:
```
mklink "C:\Users\tims\AppData\Roaming\Zed\settings.json" "C:\Users\tims\Desktop\settings.json"
```
or

For a relative symlink: 
```
mklink "settings.json" "..\..\..\Desktop\settings.json"
```

### Zed Version and System Specs

Zed: v0.169.0 (Zed Dev 8151dc7696829022c15980ed5891ccdcde6c84d7)
OS: Windows 10.0.26100
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 770 || Intel Corporation || 101.6129

### If applicable, add screenshots or screencasts of the incorrect state / behavior

https://github.com/user-attachments/assets/78a91e04-ea35-428b-ba02-3777d74b9c90

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #22659

More context can be found in attached issue.

This is specific to Windows:

1. Add parent directory watching for fs watch when the file doesn't exist. For example, when Zed is first launched and `settings.json` isn't there.
2. Add proper symlink handling for fs watch. For example, when `settings.json` is a symlink.

This is exactly same as how we handle it on Linux.

Release Notes:

- Fixed an issue where items on the Welcome page could not be toggled on Windows, either on first launch or when `settings.json` is a symlink.

### CODE REVIEW

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
Could we change these to be literally the same? As in adjust the `cfg()` to use the same implementation on Linux and windows?

**Comment by 0xtimsb** [comment]
Done. I made one intentional change for Windows, which is switching from `Recursive` watch mode to `NonRecursive`. I couldn’t find any compelling or definitive documentation suggesting that `Recursive` is necessary on Windows. `NonRecursive` seems to work just fine, as it already does on Linux. It might be good for performance.

File: crates/fs/src/fs_watcher.rs [hunk 1]
```diff
@@ -89,6 +89,8 @@ pub struct GlobalWatcher {
     pub(super) inotify: Mutex<notify::INotifyWatcher>,
     #[cfg(target_os = "freebsd")]
     pub(super) inotify: Mutex<notify::KqueueWatcher>,
+    #[cfg(target_os = "windows")]
+    pub(super) inotify: Mutex<notify::ReadDirectoryChangesWatcher>,
```
Comment (mikayla-maki) [inline crates/fs/src/fs_watcher.rs:93]: inotify is a linux-exclusive API, could we change the name of this variable to be generic?

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by mikayla-maki** [comment]
thanks!

**Review by mikayla-maki — APPROVED** [review]
