### PR TITLE
On windows, recreate renderer swap chain on restore from minimized

### LINKED ISSUE #21688: On windows, the app crashes when I minimize it
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

If I just switch to another application, then when I return to zed, it continues to function, but if I minimize it and expand it, it stops responding to any actions other than the window control buttons.
If I expand it to full screen (using the window control button at the top of the zed window), it will start functioning again.
If i collapse it again, everything will repeat itself.

### Environment

Windows 11 24H2   
AMD Ryzen 2700 Eight-Core (x64)
16gb ram
I have compiled zed from the source code   
I have not installed any plugins on it

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>
```
[Zed.log](https://github.com/user-attachments/files/18049222/Zed.log)
```
</details>

### PR DESCRIPTION
**Pull request by mgsloan**
Closes #21688

Release Notes:

- Windows: Fix freeze after window minimize and maximize

### CODE REVIEW

**Comment by dovakin0007** [comment]
I can confirm this works in my machine well

File: crates/gpui/src/platform/blade/blade_renderer.rs [hunk 1]
```diff
@@ -431,13 +431,25 @@ impl BladeRenderer {
...
+    fn update_drawable_size_impl(&mut self, size: Size<DevicePixels>, always_resize: bool) {
         let gpu_size = gpu::Extent {
             width: size.width.0 as u32,
             height: size.height.0 as u32,
             depth: 1,
         };
 
-        if gpu_size != self.surface_config.size {
+        if always_resize || gpu_size != self.surface_config.size {
             self.wait_for_gpu();
```
Comment (kvark) [inline crates/gpui/src/platform/blade/blade_renderer.rs:453]: perhaps we would instead do something like this:
```rust
if size.width.0 > 0 && size.height.0 > 0 {
  self.wait_for_gpu();
  self.gpu.resize(self.surface_config);
}
```
This will naturally make us to recreate the surface after the minimize is done, without `always_resize` flag

Comment (mgsloan) [reply crates/gpui/src/platform/blade/blade_renderer.rs:453]: Thanks for taking a look!  Wouldn't that cause this to always resize even if the size is the same as it as before?  (I assume that check is there for a good reason)

**Comment by feeiyu** [comment]
It works on my machine, but generate some warning logs `Acquire failed because the surface is out of date`,  the app still try render after minimized? 

freeze1210

File: crates/gpui/src/platform/blade/blade_renderer.rs (hunk 1 above)
Comment (feeiyu) [reply crates/gpui/src/platform/blade/blade_renderer.rs:453]: After add log in handle_size_msg, I found the window size is (181, 24) in WM_SIZE event after minimize.

Comment (dovakin0007) [reply crates/gpui/src/platform/blade/blade_renderer.rs:453]: > (181, 24)
this article might be old but it can be releated to this one
https://devblogs.microsoft.com/oldnewthing/20050210-00/?p=36483

Comment (dovakin0007) [reply crates/gpui/src/platform/blade/blade_renderer.rs:453]: > > (181, 24)
 this article might be old but it can be releated to this one.
 https://devblogs.microsoft.com/oldnewthing/20050210-00/?p=36483

**Comment by mgsloan** [comment]
Going to go ahead and merge since the fix is working.  Can refine from here.
