### PR TITLE
pane: Improve close active item to better handle pinned tabs

### LINKED ISSUE #22247: Exclude pinned tabs when closing active item with shortcut
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Pinned tabs should follow VS Code's behavior where CMD + W (or whatever the keybind is) doesn't close pinned tabs - a manual context menu action or close button click, or unpin and then close shortcut is needed instead. See also my failed attempt #21572 😅 

### Zed Version and System Specs

N/A

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by smitbarmase**
Closes #22247

This PR does following:

- [x]  Do not close pinned tab on keyboard shortcuts like `ctrl+w` or `alt+f4`
- [x] Close pinned tab on context menu action, menu bar action, or vim bang
- [x] While closing pinned tab via shortcut (where it won't close), instead activate any other non-pinned tab in same pane
- [x] Else, if any other pane contains non-pinned tab, activate that
- [x] Tests

This PR also fixes a bug where the `close_pinned` boolean in the keymap wasn’t being respected. The issue was in deserialization from JSON to the Rust struct. The struct had `#[serde(rename_all = "camelCase")]` annotated on it, which means serialize keys to camelCase, and deserialize keys **only** from camelCase. Because of this, `close_pinned` wasn’t being parsed correctly. I have updated the key to camelCase now, which is also pattern at lot of places. We should make this consistent in long run.

Preview:

This mimics the behavior in VSCode.

https://github.com/user-attachments/assets/67d18971-e13c-411b-bb83-dd994b6ebcd9

Release Notes:

- Pinned tab now stay open when using close shortcuts, auto focuses to any other non-pinned tab instead.

### CODE REVIEW

File: crates/workspace/src/pane.rs [hunk 1]
```diff
@@ -2837,14 +2894,9 @@ impl Pane {
 
         self.items
             .iter()
-            .map(|item| item.item_id())
-            .filter(|item_id| {
-                if let Some(ix) = self.index_for_item_id(*item_id) {
```
Comment (0xtimsb) [inline crates/workspace/src/pane.rs:2842]: Additional:

Seems like redundant logic as `index_for_item_id` goes through same `self.items` to find index. Can use `enumerate` instead.

File: assets/keymaps/default-linux.json [hunk 2]
```diff
@@ -274,14 +274,14 @@
       "ctrl-pagedown": "pane::ActivateNextItem",
       "ctrl-shift-pageup": "pane::SwapItemLeft",
       "ctrl-shift-pagedown": "pane::SwapItemRight",
-      "ctrl-f4": "pane::CloseActiveItem",
-      "ctrl-w": "pane::CloseActiveItem",
-      "alt-ctrl-t": ["pane::CloseInactiveItems", { "close_pinned": false }],
+      "ctrl-f4": ["pane::CloseActiveItem", { "closePinned": false }],
```
Comment (SomeoneToIgnore) [inline assets/keymaps/default-linux.json:277]: > closePinned

Any reason to abandon snake case and potentially break everyone's custom keymaps?

Comment (0xtimsb) [reply assets/keymaps/default-linux.json:277]: I mentioned the reason above. Currently `close_pinned` is not working for anyone, it's value is always false despite what you define in keymap. This is due to serde is aspecting came case `closePinned`, due to use of `#[serde(rename_all = "camelCase")]` on this struct.

Comment (SomeoneToIgnore) [reply assets/keymaps/default-linux.json:277]: And why do we need that camelCase rename?

Comment (SomeoneToIgnore) [reply assets/keymaps/default-linux.json:277]: 😢 

I just feel that it's so odd to have both mixed, then introduce another one here and then "make this consistent in long run" and break that.

cc @ConradIrwin as the one who seem to know better about all this, maybe he has better ideas.
I vote for camel case for new entities for now.

Comment (SomeoneToIgnore) [reply assets/keymaps/default-linux.json:277]: Discussed offline, and seems that after the next release, we're changing everything to snake_case.
I will try to work on that and finish on Thursday, but welcome to do so before, if you want to — this PR better wait before the massive change.

Comment (0xtimsb) [reply assets/keymaps/default-linux.json:277]: I'll pick that up, expect PR on Thursday morning.

**Comment by uncenter** [comment]
Thank you for pushing this through, can't wait for this to land!

> I added you as a co-author, though I don't know why it’s not showing (typo maybe?). Just a small nod.

Ah that's sweet, I think it is because `Co-authored-by: uncenter <47499684+uncenter@users.noreply.github.com>` is not the last line of the message? The release notes text that is below it may be causing the issue. Regardless, thanks for the nod :)
