### PR TITLE
terminal: Sanitize trailing periods in URL detection

### LINKED ISSUE #12338: Cmd+click to linkify file in terminal doesn't work when there are whitespace or certain separators in the filename
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For example, these 3 filenames won't work:
* 'test file 1.txt'
* test、2.txt
* test。3.txt

### Environment

Zed: v0.137.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by Mearman**
Fixes #12338, related to #37616

This change improves URL detection in the terminal by removing trailing periods that appear to be sentence punctuation rather than part of the URL structure. It builds upon the parentheses sanitization work from #37076 by consolidating both approaches into a unified `sanitize_url_punctuation` function.

## Changes
- Combines parentheses and period sanitization into a single `sanitize_url_punctuation` function
- Uses optimized single traversal with `fold()` for parentheses counting (addressing code review feedback)
- Removes trailing periods using heuristics to distinguish sentence punctuation from legitimate URL components
- Removes multiple trailing periods (always considered punctuation)
- Removes single trailing periods when they appear after alphanumeric characters or slashes
- Preserves periods that are part of legitimate URL structure (e.g., version numbers, IP addresses, subdomains)
- Maintains existing parentheses balancing logic from #37076

## Implementation Details
- **Parentheses handling**: Counts opening and closing parentheses, removes trailing `)` when unbalanced
- **Period handling**: Uses `take_while()` iterator for efficient period counting
- **Performance**: Single pass counting with optimized loop to avoid redundant work
- **Code clarity**: Uses let-else pattern for readable conditional logic

## Testing
- Added comprehensive test coverage for both parentheses and period sanitization
- Tests cover balanced vs unbalanced parentheses cases  
- Tests cover various period scenarios including legitimate URL periods vs sentence punctuation
- All existing tests continue to pass

## Release Notes

- Improved: Terminal URL detection now correctly handles trailing punctuation from sentence context. URLs ending with periods (like `https://example.com.`) and unbalanced parentheses (like `https://example.com/path)`) are now properly detected without including the trailing punctuation. ([#12338](https://github.com/zed-industries/zed/issues/12338), [#37616](https://github.com/zed-industries/zed/issues/37616))

### CODE REVIEW

**Review by probably-neb — CHANGES_REQUESTED** [review]
Please fix the formatting errors in CI (just need to run `cargo fmt` and push), and I'll be ready to merge. Curious if @davewa has any thoughts on this as well.

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 1]
```diff
@@ -233,6 +315,73 @@ mod tests {
...
+        for (input, expected) in test_cases {
+            // Create a minimal terminal for testing
+            let term = Term::new(Config::default(), &TermSize::new(80, 24), VoidListener);
+            
+            // Create a dummy match that spans the entire input
+            let start_point = AlacPoint::new(alacritty_terminal::index::Line(0), alacritty_terminal::index::Column(0));
+            let end_point = AlacPoint::new(alacritty_terminal::index::Line(0), alacritty_terminal::index::Column(input.len()));
+            let dummy_match = alacritty_terminal::term::search::Match::new(start_point, end_point);
+            
+            // This test should initially fail since we haven't implemented period sanitization yet
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: This comment seems stale?

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 2]
```diff
@@ -164,6 +165,87 @@ pub(super) fn find_from_grid_point<T: EventListener>(
...
+    url: String,
+    url_match: Match,
+    term: &Term<T>,
+) -> (String, Match) {
+    let mut sanitized_url = url;
+    let mut chars_trimmed = 0;
+    
+    // First, handle parentheses balancing
+    let open_parens = sanitized_url.chars().filter(|&c| c == '(').count();
+    let close_parens = sanitized_url.chars().filter(|&c| c == ')').count();
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: This could be done with one traversal (`.scan((0, 0), |(opens, closes), c| ...)`) instead of two.

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 3]
```diff
@@ -164,6 +165,87 @@ pub(super) fn find_from_grid_point<T: EventListener>(
...
+    
+    // If there are more closing parentheses than opening ones, and the URL ends with ')',
+    // trim trailing ')' characters until balanced or no more trailing ')' exist
+    if close_parens > open_parens && sanitized_url.ends_with(')') {
+        while sanitized_url.ends_with(')') {
+            let remaining_open = sanitized_url.chars().filter(|&c| c == '(').count();
+            let remaining_close = sanitized_url.chars().filter(|&c| c == ')').count();
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: I don't believe these traversals are necessary? `remaining_open` should be constant for this loop, and `remaining_close` can be decremented as they are trimmed.

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 4]
```diff
@@ -164,6 +165,87 @@ pub(super) fn find_from_grid_point<T: EventListener>(
...
+    let mut sanitized_url = url;
+    let mut chars_trimmed = 0;
+    
+    // First, handle parentheses balancing
+    let open_parens = sanitized_url.chars().filter(|&c| c == '(').count();
+    let close_parens = sanitized_url.chars().filter(|&c| c == ')').count();
+    
+    // If there are more closing parentheses than opening ones, and the URL ends with ')',
+    // trim trailing ')' characters until balanced or no more trailing ')' exist
+    if close_parens > open_parens && sanitized_url.ends_with(')') {
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: The `ends_with()` test in the `if` seems redundant with the test in the `while`

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 5]
```diff
@@ -164,6 +165,87 @@ pub(super) fn find_from_grid_point<T: EventListener>(
...
+    if sanitized_url.ends_with('.') {
+        // Count trailing periods
+        let mut trailing_periods = 0;
+        for char in sanitized_url.chars().rev() {
+            if char == '.' {
+                trailing_periods += 1;
+            } else {
+                break;
+            }
+        }
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: Can be just `let trailing_periods = sanitized_url.chars().rev().take_while(|c| c == '.').count()`

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 6]
```diff
@@ -233,6 +315,73 @@ mod tests {
...
+        ];
+        
+        for (input, expected) in test_cases {
+            // Create a minimal terminal for testing
+            let term = Term::new(Config::default(), &TermSize::new(80, 24), VoidListener);
+            
+            // Create a dummy match that spans the entire input
+            let start_point = AlacPoint::new(alacritty_terminal::index::Line(0), alacritty_terminal::index::Column(0));
+            let end_point = AlacPoint::new(alacritty_terminal::index::Line(0), alacritty_terminal::index::Column(input.len()));
+            let dummy_match = alacritty_terminal::term::search::Match::new(start_point, end_point);
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: I think here and below in the periods test would be easier on the eyes if you `use`'d `Line`, `Column`, and `Match` instead of qualifying them.

File: crates/terminal/src/terminal_hyperlinks.rs [hunk 7]
```diff
@@ -164,6 +165,87 @@ pub(super) fn find_from_grid_point<T: EventListener>(
...
+                    second_last_char.is_alphanumeric() ||
+                    // Also remove if it's a slash (path ending: /path.)
+                    second_last_char == '/'
+                };
+                
+            if should_remove_period {
+                sanitized_url.pop();
+                chars_trimmed += 1;
+            }
+        }
```
Comment (davewa) [inline crates/terminal/src/terminal_hyperlinks.rs]: I think this can be simplified to:
```
else if trailing_periods == 1 
    && let Some(second_last_char) = sanitized_url.chars().rev().nth(1) 
    && (second_last_char.is_alphanumeric() || second_last_char == '/')
{
    sanitized_url.pop();
    chars_trimmed += 1;
}
```

**Review by davewa — COMMENTED** [review]
Looks nice! I think this is a useful heuristic to have for urls. I left a few minor suggestions.

File: crates/terminal/src/terminal_hyperlinks.rs (hunk 1 above)
Comment (Mearman) [reply crates/terminal/src/terminal_hyperlinks.rs]: oops meant to leave a `// TODO` to remove it after I'd confirmed the behaviour 🙃

**Review by davewa — APPROVED** [review]
Very nice, thanks!

**Review by probably-neb — APPROVED** [review]
Looks good. Thanks!
