### PR TITLE
Fix linux double click

### LINKED ISSUE #17573: "Middle click paste" on Linux followed by a "left click" is being recognized as a "double left click"
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"Middle click paste" on Linux immediately followed by a "left click" is being recognized as a "double left click" and selects the text instead of changing cursor position.

### Environment

Zed: v0.150.4 (Zed)
OS: Linux X11 arch unknown
Memory: 30.7 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV RENOIR) || radv || Mesa 24.2.1-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by mycroft**
Closes #17573

Release Notes:

- Fixed a bug where middle mouse clicks could be interpreted as left or right mouse clicks.

### CODE REVIEW

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 1]
```diff
@@ -951,6 +954,8 @@ impl X11Client {
                     let click_elapsed = state.last_click.elapsed();
 
                     if click_elapsed < DOUBLE_CLICK_INTERVAL
+                        && state.last_mouse_button.is_some()
+                        && state.last_mouse_button.unwrap() == button
```
Comment (RemcoSmitsDev) [inline crates/gpui/src/platform/linux/x11/client.rs:958]: I think this is better, that way we can avoid an unwrap.
```suggestion
                        && state.last_mouse_button.is_some_and(|prev_button| prev_button == button)
```

File: crates/gpui/src/platform/linux/wayland/client.rs [hunk 2]
```diff
@@ -1524,6 +1526,8 @@ impl Dispatch<wl_pointer::WlPointer, ()> for WaylandClientStatePtr {
                         let click_elapsed = state.click.last_click.elapsed();
 
                         if click_elapsed < DOUBLE_CLICK_INTERVAL
+                            && state.click.last_mouse_button.is_some()
+                            && state.click.last_mouse_button.unwrap() == button
```
Comment (RemcoSmitsDev) [inline crates/gpui/src/platform/linux/wayland/client.rs:1530]: I think this is better, that way we can avoid an unwrap.
```suggestion
                        && state.click.last_mouse_button.is_some_and(|prev_button| prev_button == button)
```

**Review by RemcoSmitsDev — CHANGES_REQUESTED** [review]

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 1 above)
Comment (mycroft) [reply crates/gpui/src/platform/linux/x11/client.rs]: Thanks for the suggestion. I updated the branch accordingly.

File: crates/gpui/src/platform/linux/wayland/client.rs (hunk 2 above)
Comment (mycroft) [reply crates/gpui/src/platform/linux/wayland/client.rs]: Thanks for the suggestion. I updated the branch accordingly.

**Comment by mikayla-maki** [comment]
Thank you!
