### PR TITLE
recent_projects: Fix unaligned keybinding labels in quick-switch menu

### LINKED ISSUE #54324: Shortcut labels are not aligned in recent projects quick-switch menu
### Reproduction steps

1. Open Zed with any workspace.
2. Open the recent projects quick-switch menu from the bottom-left area (using "Add Project" button at the bottom of thread panel).
3. Look at rows such as:
   - `Add Local Folders` with `Ctrl-K  Ctrl-O`
   - `Add Remote Folder` with `Ctrl-Alt-Shift-O`
4. Compare shortcut label positioning between rows.

**Observed:** Shortcut labels are not visually aligned to the same right-side column.

### Current behavior

- Action labels and shortcut labels are shown in each row.
- Shortcut labels appear at inconsistent horizontal positions.
- UI feels uneven compared to other menu lists in the app.

Image

### Expected behavior

- Shortcut labels should align to a single right-side column across all relevant rows.
- Row layout should match other menus that use stable two-column alignment (label left, shortcut right).
- Visual spacing should remain consistent regardless of shortcut length.

Image

### Zed version and system specs

Zed: v0.234.0+dev.554f5c6b65708e054ee34a12e0b8015cb9bed71f
OS: Windows
RAM: 32GB

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by galuis116**
Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #54324 

Release Notes:

- Fixed shortcut label alignment in the Recent Projects quick-switch footer by rendering action rows with a consistent two-column layout (label left, keybinding right) for “Add Local Folders” and “Add Remote Folder”.

### CODE REVIEW

**Review by danilo-leal — COMMENTED** [review]
Can we use the `ButtonLike` component like I did in your last PR?

**Comment by galuis116** [comment]
I will check your last PR relative to ButtonLike component and commit.

**Comment by galuis116** [comment]
I have updatede as what you mentioned and pushed commit.

File: crates/recent_projects/src/sidebar_recent_projects.rs [hunk 1]
```diff
@@ -417,22 +417,38 @@ impl PickerDelegate for SidebarRecentProjectsDelegate {
...
 
-                    Button::new("open_local_folder", "Add Local Folders")
-                        .key_binding(KeyBinding::for_action_in(&open_action, &focus_handle, cx))
+                    ButtonLike::new("open_local_folder")
+                        .child(
+                            h_flex()
+                                .w_full()
+                                .gap_1()
+                                .justify_between()
+                                .items_center()
```
Comment (danilo-leal) [inline crates/recent_projects/src/sidebar_recent_projects.rs]:
```suggestion

```

You can take off these `item_center` methods as they're included already in `h_flex`.

Comment (galuis116) [reply crates/recent_projects/src/sidebar_recent_projects.rs]: Okay. I have just updated according to your feedback and pushed commit.

**Comment by galuis116** [comment]
I have updated according to your feedback and pushed commit.

**Comment by galuis116** [comment]
It seems that it is ready to merge.

**Comment by galuis116** [comment]
I am waiting for this to be merged as all passed and verified.
image

**Comment by galuis116** [comment]
Hellow @danilo-leal,  I am waiting for you to merge this pull request.

**Review by danilo-leal — APPROVED** [review]
Thank you!
