### PR TITLE
Wait for worktree scan to complete before starting search

### LINKED ISSUE #9858: project search doesn't work correctly while the file index isn't finished
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening Zed, it appears the a file index with the files of the project is created. For big repos (e.g. Chromium), this index takes a while to build. During that time, project search seems to be limited to the files already indexed.

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by osyvokon**
When starting a search on a project that is in the middle of a scan, we used to miss results in files that had not yet been scanned.

This change makes the search wait for the scan to complete.

Closes #9858

Release Notes:

- Fixed incomplete search results when the project scan is incomplete

### CODE REVIEW

File: crates/project/tests/integration/project_tests.rs [hunk 1]
```diff
@@ -12281,6 +12281,7 @@ async fn search(
                 results.entry(buffer).or_insert(ranges);
             }
             SearchResult::LimitReached => {}
+            SearchResult::WaitingForScan => {}
```
Comment (osiewicz) [inline crates/project/tests/integration/project_tests.rs]:
```suggestion
SearchResult::LimitReached | SearchResult::WaitingForScan => {}
```

File: crates/search/src/project_search.rs [hunk 2]
```diff
@@ -516,8 +533,11 @@ impl Render for ProjectSearchView {
             let model = self.entity.read(cx);
             let has_no_results = model.no_results.unwrap_or(false);
             let is_search_underway = model.pending_search.is_some();
+            let is_waiting_for_scan = model.waiting_for_scan;
 
-            let heading_text = if is_search_underway {
+            let heading_text = if is_waiting_for_scan {
+                "Waiting for project scan to complete…"
```
Comment (osiewicz) [inline crates/search/src/project_search.rs]: How about something slightly more generic, like "Loading project..."?

**Review by osiewicz — APPROVED** [review]
LGTM, thanks!

**Comment by hferreiro** [comment]
IIUC this will make searching for files in big repos even slower. Are there plans for doing the search in parallel to the scanning?

**Comment by osyvokon** [comment]
> IIUC this will make searching for files in big repos even slower. 

This change doesn't make the overall search slower, but it may increase the time to first result -- under specific conditions. Like, for example, in this scenario:

1. Open Chromium in Zed
2. Start searching _immediately_
3. Observe about 10 seconds delay before the search starts.

However, it's not as bad as it sounds because:

- Subsequent searches won't have this delay
- If you don't search as the first thing after opening the editor, you won't have this delay either.


> Are there plans for doing the search in parallel to the scanning?

Not at the moment, but if you see a good motivational case for it, please open an issue.
