### PR TITLE
file_finder: Respect .gitignore and file_scan_inclusions with ** in glob

### LINKED ISSUE #39037: File Picker does not respect .gitignore with file_scan_inclusions set as **/xxx
### Summary

The file picker (cmd+p) does show files from folders in `.gitignore` when `"file_scan_inclusions"` is set in settings with a `**/xxxx` flag.

### Description
When I set a match in the array of `file_scan_inclusions`, in my case 
```
"file_scan_inclusions": [
  "**/.env"
],
```
it causes the whole exclusion functionality to fail. I then need to specifically include folders in `file_scan_exclusions` in order for them to not show up anymore.

I stepped onto this since I worked in a monorepo where there where .env files located in /apps subdirs.

Steps to reproduce:
1. Have a /node_modules folder
2. add it to .gitignore
3. add the snippet above for `file_scan_inclusions` to the settings.json
4. use cmd+p to search for package.json
5. You have to restart zed again when you delete the setting from the file to get the intended behavior.

**Expected Behavior**: Files from node_modules should NOT show up
**Actual Behavior**: Files from node_modules show up

### Settings.json
```json
{ "file_scan_inclusions": ["**/.env"] } // triggers as whole settings file
```

### Zed Version and System Specs

Zed: v0.206.3 (Zed Preview) 
OS: macOS 15.7
Memory: 36 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by bnjjj**
Closes #39037 

Previously, the code split the `**/.env` glob in `file_scan_inclusions` into two sources for the `PathMatcher`: `["**", "**/.env"]`. This approach works for directories, but including `**` will match all directories and their files. To address this, I now select the appropriate `PathMatcher` using only `**/.env` when specifically targeting a file to determine whether to include it in the file finder.

Release Notes:

- Fixed: respect `.gitignore` and `file_scan_inclusions` settings with `**` in glob for file finder

### CODE REVIEW

**Comment by bnjjj** [comment]
@Anthony-Eid any feedback to give me in order to land this fix ?

**Comment by P1n3appl3** [comment]
@dvdsk and I looked at this last week, sorry for not following up in the thread. We were initially confused why it was necessary to keep around both the "parsed" and the "unparsed" inclusions. I'd prefer that we change the code to explicitly call the former "parent_dir_inclusions" and the latter "file_inclusions" and prevented the former from including the last component of the path (by skipping the first element of `ancestors`). That way there's a clear separation between "we need to avoid skipping directories that match this partial glob" vs "we need to include files/dirs that match this full glob". Otherwise the change looks good to me, and thx for adding the tests.

This isn't super related to this PR, but regarding the feature in general: it seems like it's usually a mistake to use `**` in globs for inclusions, because it forces the directory scanning to traverse the entire tree which can horribly degrade project search/scanning perf in the presence of build directories/`.git/`/etc. This issue was [mentioned](https://github.com/zed-industries/zed/pull/16852#issuecomment-2309241960) in the PR adding the feature, but I wonder if we should somehow warn on, or even disallow, inclusion globs starting with `**`.

**Comment by P1n3appl3** [comment]
It also might be worth investigating what the [ignore crate](https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html#method.filter_entry) does for this, they have to solve the same problem with partial globset matching.

File: crates/worktree/src/worktree_settings.rs [hunk 1]
```diff
@@ -46,6 +51,7 @@ impl Settings for WorktreeSettings {
             .flat_map(|glob| {
                 Path::new(glob)
                     .ancestors()
+                    .skip(1)
```
Comment (bnjjj) [inline crates/worktree/src/worktree_settings.rs:55]: @P1n3appl3 is it what you meant when skipping the first ancestor ?

Comment (P1n3appl3) [reply crates/worktree/src/worktree_settings.rs:55]: Yep, that should be good. We already have each full path in `file_scan_inclusions` so we don't need them there.

**Comment by bnjjj** [comment]
@P1n3appl3 thanks for the review I think I need you to re-run the tests because I don't think it's related to my changes
