### PR TITLE
terminal: Drain task output on completion

### LINKED ISSUE #18342: Linux task terminal output is sometimes missing
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whatever I write in, if i try to click on the run button, it will run but it doesn't show any output and I think it doesn't actually run or something. However very rarely it does show, but if i run again then the output is disappearing again.

### Environment

Zed: v0.153.7 (Zed)
OS: Linux Wayland fedora 40
Memory: 15.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU || NVIDIA || 560.35.03

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot from 2024-09-25 18-15-11

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by aborg-dev**
Now we ensure that task output is fully drained and printed to Zed terminal pane on task completion.

This change depends on a recent change to alacritty_terminal crate: https://github.com/alacritty/alacritty/commit/5e78d20c709cb1ab8d44ca7a8702cc26d779227c.

Closes https://github.com/zed-industries/zed/issues/18342

Release Notes:

- Fixed missing task terminal output on Linux for short-running commands

### CODE REVIEW

File: crates/repl/src/outputs/plain.rs
Comment (aborg-dev) [inline crates/repl/src/outputs/plain.rs:1]: This is needed, because I'm building on top of new Alacritty version to simplify landing the change to upstream. Ideally, we would backport it to 0.24 and eliminate the need to rely on latest Alacritty. Otherwise we'll need to wait until the cut the new stable release.

**Comment by aborg-dev** [comment]
@SomeoneToIgnore , the change in Alacritty has landed and I've updated this PR to point to the commit in Alacritty upstream repo.

I'm attaching the video with my test:
1. Run a task with a very fast command `echo hello, world`
2. See the output
3. Rerun the task many times, observe that all of them have the output

[fast_command.webm](https://github.com/user-attachments/assets/56388dc1-ebd9-496b-a5e5-be66f1e2f766)

For comparison, in the current Linux Zed version, I **never** see the output of this command unless I add a `sleep` call at the end.

File: Cargo.toml [hunk 1]
```diff
@@ -336,7 +336,8 @@ zeta = { path = "crates/zeta" }
 #
 
 aho-corasick = "1.1"
-alacritty_terminal = "0.24"
+# TODO(#18342): Update to version 0.25 from crates.io when it is released.
```
Comment (aborg-dev) [inline Cargo.toml:339]: I tagged the TODO with a GitHub issue to keep the context and remember to clean up this dependency when new Alacritty crate is released.
Is there any convention in the codebase for such tagging?

Comment (SomeoneToIgnore) [reply Cargo.toml:339]: I think `TODO(..)` is a convention, at least there's a bunch if Windows-related items like that, or just `TODO ...` is also used.

**Review by SomeoneToIgnore — APPROVED** [review]
Nice to see it working, thank you!
