### PR TITLE
Always invalidate tree-sitter data on buffer reparse end

### LINKED ISSUE #45182: Bracket colorization is applied only after the first edit of the file.
### Reproduction steps

1) Open Zed
2) Open a code file in the editor 
3) Brackets are not colorized in the opened file

I'm not sure if it is an intended behavior or not 

### Current vs. Expected behavior

**Current:** when I first open any file, all brackets are not colorized, and only after I make a change in the file are the colors applied. If I close the tab and reopen the file, the brackets are grey again.

**Expected:** brackets are colorized on file opening

### Zed version and system specs

Zed: v0.217.2 (Zed stable 3d2e6ee76b4d9a932248242506611985cae6b0a8)
OS: Windows 10
Memory: 16GiB
Architecture: x86_64

### Attach Zed log file

<details><summary>Zed.log</summary>

```log


2025-12-18T03:11:17+02:00 INFO  [zed] ========== starting zed version 0.217.2+stable.102.3d2e6ee76b4d9a932248242506611985cae6b0a8, sha 3d2e6ee ==========
2025-12-18T03:11:17+02:00 INFO  [gpui::platform::windows::directx_devices] Using GPU: Intel(R) UHD Graphics 630
2025-12-18T03:11:17+02:00 INFO  [gpui::platform::windows::directx_devices] Created device with Direct3D 11.1 feature level.
2025-12-18T03:11:17+02:00 INFO  [gpui::platform::windows::direct_write] Use Segoe UI as UI font.
2025-12-18T03:11:17+02:00 INFO  [crashes] spawning crash handler process
2025-12-18T03:11:17+02:00 INFO  [extension_host] extensions updated. loading 22, reloading 0, unloading 0
2025-12-18T03:11:17+02:00 INFO  [crashes] connected to crash handler process after 100ms
2025-12-18T03:11:17+02:00 INFO  [crashes] crash handler registered
2025-12-18T03:11:17+02:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2025-12-18T03:11:17+02:00 ERROR [crates/client/src/client.rs:359] Element not found. (0x80070490)
2025-12-18T03:11:17+02:00 INFO  [auto_update] Auto Update: checking for updates
2025-12-18T03:11:17+02:00 INFO  [workspace] Rendered first frame
2025-12-18T03:11:17+02:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics 630", driver_name: "Intel Corporation", driver_info: "27.20.100.8729" }
2025-12-18T03:11:17+02:00 INFO  [util::shell] Found powershell in: C:\Program Files\PowerShell\7\pwsh.exe
2025-12-18T03:11:17+02:00 INFO  [util::shell] Found bash at C:\Program Files\Git\bin\bash.exe
2025-12-18T03:11:17+02:00 ERROR [agent] Failed to authenticate provider: Amazon Bedrock: Element not found. (0x80070490)
2025-12-18T03:11:17+02:00 ERROR [crates/gpui/src/platform/windows/platform.rs:234] Access is denied. (0x80070005)
2025-12-18T03:11:17+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 64 to 128
2025-12-18T03:11:17+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating monochrome_sprite_pipeline buffer size from 512 to 1024
2025-12-18T03:11:20+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating monochrome_sprite_pipeline buffer size from 1024 to 2048
2025-12-18T03:11:22+02:00 INFO  [node_runtime] Node runtime install_if_needed
2025-12-18T03:11:22+02:00 INFO  [alacritty_terminal::tty::windows::conpty] Using conpty.dll for pseudoconsole
2025-12-18T03:11:22+02:00 INFO  [lsp] starting language server process. binary path: "..user_path\\AppData\\Local\\Zed\\extensions\\work\\cargo-tom\\cargotom-2.3.13\\cargotom.exe", working directory: "..user_path\\Workspace\\Repositories\\hello-world", args: ["--storage", ..user_path/AppData/Local/Zed/extensions/work/cargo-tom"]
2025-12-18T03:11:22+02:00 INFO  [language] found user-installed language server for rust-analyzer. path: "..user_path\\.cargo\\bin\\rust-analyzer.exe", arguments: []
2025-12-18T03:11:22+02:00 INFO  [lsp] starting language server process. binary path: "..user_path\\.cargo\\bin\\rust-analyzer.exe", working directory: "..user_path\\Workspace\\Repositories\\hello-world", args: []
2025-12-18T03:11:22+02:00 WARN  [node_runtime] using Zed managed Node.js at ..user_path\AppData\Local\Zed\node\node-v24.11.0-win-x64 since checking system Node.js failed with error: node at C:\Program Files\nodejs\node.exe is too old. want: 22.0.0, got: 21.5.0
2025-12-18T03:11:23+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating path_rasterization_pipeline buffer size from 32 to 64
2025-12-18T03:11:23+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating path_rasterization_pipeline buffer size from 64 to 128
2025-12-18T03:11:23+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating path_rasterization_pipeline buffer size from 128 to 256
2025-12-18T03:11:23+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating path_rasterization_pipeline buffer size from 256 to 512
2025-12-18T03:11:23+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating path_rasterization_pipeline buffer size from 512 to 1024
2025-12-18T03:11:24+02:00 ERROR [project::context_server_store] Failed to create context server configuration from settings: from extension "GitLab MCP Server" version 0.0.5: missing field `gitlab_personal_access_token`
2025-12-18T03:11:25+02:00 WARN  [project::lsp_store] Get diagnostics via rust-analyzer failed: server cancelled the request
2025-12-18T03:11:25+02:00 ERROR [crates/editor/src/editor.rs:7039] Get document highlights via rust-analyzer failed: content modified
2025-12-18T03:11:25+02:00 ERROR [editor] Failed to update project diagnostics: pulling diagnostics: Get diagnostics via rust-analyzer failed: server cancelled the request
2025-12-18T03:11:30+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating monochrome_sprite_pipeline buffer size from 2048 to 8192

</details>


### Relevant Zed settings

<details><summary>settings.json</summary>

<!-- Paste your settings inside the code block. -->
```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Also do not eagerly invalidate this data on buffer reparse start

Closes https://github.com/zed-industries/zed/issues/45182

Release Notes:

- Fixed bracket colorization not applied on initial file open

### CODE REVIEW

File: crates/language/src/buffer.rs [hunk 1]
```diff
@@ -1697,9 +1697,6 @@ impl Buffer {
     /// for the same buffer, we only initiate a new parse if we are not already
     /// parsing in the background.
     pub fn reparse(&mut self, cx: &mut Context<Self>, may_block: bool) {
-        if self.text.version() != *self.tree_sitter_data.version() {
-            self.invalidate_tree_sitter_data(self.text.snapshot());
-        }
```
Comment (Veykril) [inline crates/language/src/buffer.rs:1702]: I think we need to keep this one still, otherwise we run into risk of using an outdated treesitterdata (version wise)

Comment (SomeoneToIgnore) [reply crates/language/src/buffer.rs:1702]: https://github.com/zed-industries/zed/pull/45210
