### PR TITLE
workspace: Fix inactive pane dimming

### LINKED ISSUE #27173: `active_pane_modifiers.inactive_opacity` can result in the ative pane getting transparent
### Summary

Setting `active_pane_modifiers.inactive_opacity` set to something < 1 can result in the active pane being transparent if 3 or more panes are opened and not all are in one row/column.

Steps to trigger the problem:
1. Set `active_pane_modifiers.inactive_opacity` to 0.2
2. Open a second pane to the right
3. Open a third pane to the bottom
4. Select each pane (any order)

Actual Behavior:
- One pane seems to have opacity 1 when active 0.2 when not
- Two panes seem to have opacity 0.2 when active and 0.04 when not

Expected Behavior:
- For all 3 panes: Opacity 1 when active and opacity 0.2 when not (independent on which of the other panes is active).

 ```json
{
  "active_pane_modifiers": {
    "inactive_opacity": 0.2
  },
}
```

The following three screenshots are made with the same config

Image
Image
Image

### Zed Version and System Specs

Zed: v0.177.9 (Zed) 
OS: Linux X11 arch unknown
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (CML GT2) || Intel open-source Mesa driver || Mesa 25.0.1-arch1.2

### PR DESCRIPTION
**Pull request by ronharel02**
Closes #27173

Problem:

Active panes nested within axes were incorrectly receiving opacity overlays, while inactive panes in nested structures would get multiple overlays applied, making them appear darker than intended.

Solution:

I fixed this by distinguishing between leaf panes and axes in the rendering pipeline, applying overlays only to elements that are both leaf panes and not active, ensuring consistent visual treatment regardless of their position in the hierarchy.

Release Notes:

- Fixed an issue where `inactive_opacity` settings would be applied to panes multiple times and even to the active pane when nested within another pane.

### CODE REVIEW

File: crates/workspace/src/pane_group.rs [hunk 1]
```diff
@@ -720,27 +723,49 @@ impl PaneAxis {
         render_cx: &dyn PaneLeaderDecorator,
         window: &mut Window,
         cx: &mut App,
-    ) -> gpui::AnyElement {
+    ) -> (gpui::AnyElement, bool) {
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:726]: Let's introduce a regular `struct` with named fields instead of this newtype, so it's more clear what that `bool` means.

File: crates/workspace/src/pane_group.rs [hunk 2]
```diff
@@ -1183,12 +1225,16 @@ mod element {
...
+                    if overlay_opacity.is_some()
+                        && child.is_leaf_pane
+                        && self.active_pane_ix != Some(ix)
+                    {
                         window.paint_quad(gpui::fill(overlay_bounds, overlay_background));
                     }
 
                     if let Some(border) = overlay_border {
-                        if self.active_pane_ix == Some(ix) {
+                        // Only draw borders on active leaf panes
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:1236]: Let's not add comments that explain a single line of code below, the `if` statement below is pretty self-documenting (after all, the `if` statement above is not documented).

File: crates/workspace/src/pane_group.rs [hunk 3]
```diff
@@ -902,6 +930,11 @@ mod element {
             self
         }
 
+        pub fn with_is_leaf_pane_mask(self, mask: Vec<bool>) -> Self {
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:933]:
```suggestion
        fn with_is_leaf_pane_mask(self, mask: Vec<bool>) -> Self {
```

Since the PR changes a single module only, we do not seem to need to expose any extra public API?

File: crates/workspace/src/pane_group.rs [hunk 4]
```diff
@@ -1118,10 +1151,19 @@ mod element {
                 child.prepaint_at(origin, window, cx);
 
                 origin = origin.apply_along(self.axis, |val| val + child_size.along(self.axis));
+
+                let is_leaf_pane = self
+                    .is_leaf_pane_mask
+                    .lock()
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:1157]: I do not understand: here, we have `&mut self`, and `with_is_leaf_pane_mask` requires `self`.

There's no clones and some inter-task/thread state exchange that happens: why do we need `Arc` and `Mutex` here? 
Would it be possible to use `Vec<T>` directly here instead?

File: crates/workspace/src/pane_group.rs [hunk 5]
```diff
@@ -720,27 +723,49 @@ impl PaneAxis {
         render_cx: &dyn PaneLeaderDecorator,
         window: &mut Window,
         cx: &mut App,
-    ) -> gpui::AnyElement {
+    ) -> (gpui::AnyElement, bool) {
         debug_assert!(self.members.len() == self.flexes.lock().len());
         let mut active_pane_ix = None;
+        let mut contains_active_pane = false;
+
+        // Track which children are leaf panes (Member::Pane) vs axes (Member::Axis)
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:731]: That seems like a good `///` comment on an actual struct field, let's move it there.

File: crates/workspace/src/pane_group.rs [hunk 6]
```diff
@@ -720,27 +723,49 @@ impl PaneAxis {
...
+        let mut is_leaf_pane = vec![false; self.members.len()];
 
-        pane_axis(
+        let rendered_children = self
+            .members
+            .iter()
+            .enumerate()
+            .map(|(ix, member)| {
+                // Mark if this is a leaf pane (Member::Pane) or an axis (Member::Axis)
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/pane_group.rs:739]: Self-documenting comment again.

Also, below we seem to do two `matches!(member, Member::Pane(_)` in a row: the 2nd one has extra condition, but nontheless it seems possible to write it into a single `match member` expression instead.

**Review by SomeoneToIgnore — COMMENTED** [review]
That `Arc<Mutex<..>>` in the rendering code looks quite odd to me, but otherwise seems nice.

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you.
