### PR TITLE
editor: Stabilize IME candidate box position during pre-edit on Wayland

### LINKED ISSUE #21004: Issue with Chinese Input Candidate Box Movement
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I’ve encountered an issue with the Chinese input experience in Zed when using the Fcitx5 input method. Specifically, the candidate box behaves differently compared to other applications.

When I type multiple Chinese words in Zed, the left edge of the candidate box follows the cursor and moves to the right as I type. This causes a significant problem with usability because I have to constantly adjust my focus to follow the moving candidate box.

In comparison, when I use applications like Alacritty or Firefox, the candidate box remains fixed at the initial input position, which provides a much better input experience.

### Environment

Zed: v0.159.7 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.2.5

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I am attaching two screenshots for reference:

1. A screenshot showing the moving candidate box behavior in Zed.
Screenshot from 2024-11-22 01-16-42

2. A screenshot showing the fixed candidate box behavior in Alacritty.
Screenshot from 2024-11-22 01-17-00

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by WantenMN**
Modify the `replace_and_mark_text_in_range` method in the `Editor` to keep the cursor at the start of the preedit range during IME composition. Previously, the cursor would move to the end of the preedit text with each update, causing the IME candidate box to shift (e.g., when typing pinyin with Fcitx5 on Wayland). This change ensures the cursor and candidate box remain fixed until the composition is committed, improving the IME experience.

Closes #21004

Release Notes:

- N/A

### CODE REVIEW

**Comment by WantenMN** [comment]
@cla-bot check

**Comment by WantenMN** [comment]
I believe that the cursor moving continuously while typing is expected behavior and shouldn’t be addressed with a hack. The issue of the IME candidate box shifting with the cursor is a problem with the input method itself, not the editor. Instead of modifying the editor’s code, it would be more appropriate to submit a pull request to the IME to ensure the candidate box remains fixed at its initial position.

**Comment by WantenMN** [comment]
I’ve updated the fix for this issue in my latest commit ([d6ccb78](https://github.com/zed-industries/zed/pull/28429/commits/d6ccb7845fbc03521506be491288955f5b36dada)). 

I realized the issue was with `selected_text_range`—it’s the function causing the candidate box to follow the cursor on Wayland. Switching to `marked_text_range` ensures it stays fixed at the pre-edit start position

One thing I noticed: `selected_text_range` always returns a range where `start` and `end` are the same (the cursor position), so I’m not sure what `selection.reversed` is supposed to do in this case—or how `reversed` even gets triggered. 

It’s unclear to me why `get_ime_area` relied on `selected_text_range` in the first place. I think `marked_text_range` is a much better fit here, and this change should fully resolve the moving candidate box issue on Linux Wayland.

Here are some screenshots:
- Editor
Screenshot from 2025-04-11 03-20-39

- AI Assistant Panel 
Screenshot from 2025-04-11 03-22-11

- Command Palette
Screenshot from 2025-04-11 03-23-08

- Project Panel creating a new file
Screenshot from 2025-04-11 03-21-16

**Comment by mikayla-maki** [comment]
> selection.reversed

This is to model the case when the user selects from bottom to top, e.g.:

`-------<|---------|----------`
    
If the user starts their selection at `|` and then moves to `<|`, then the selection will be marked as "reversed"

File: crates/gpui/src/platform/linux/wayland/window.rs [hunk 1]
```diff
@@ -635,12 +635,10 @@ impl WaylandWindowStatePtr {
...
         if let Some(mut input_handler) = state.input_handler.take() {
             drop(state);
-            if let Some(selection) = input_handler.selected_text_range(true) {
-                bounds = input_handler.bounds_for_range(if selection.reversed {
-                    selection.range.start..selection.range.start
-                } else {
-                    selection.range.end..selection.range.end
-                });
+            if let Some(selection) = input_handler.marked_text_range() {
+                bounds = input_handler.bounds_for_range(
```
Comment (mikayla-maki) [inline crates/gpui/src/platform/linux/wayland/window.rs:639]: Let's restore this selection.reversed check.

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
> selection.reversed

This is to model the case when the user selects from bottom to top, e.g.:

`-------<|---------|----------`
    
If the user starts their selection at `|` and then moves to `<|`, then the selection will be marked as "reversed", but the range will still be in order relative to the buffer contents. Therefore, the correct side to query should be the "start", whereas in this case:

`-------|---------|>----------`

If the user starts their selection at `|` and then moves to `|>`, then the selection will not be marked as "reversed", the correct side to query should be the "end"


Otherwise, this change seems pretty good!

File: crates/gpui/src/platform/linux/wayland/window.rs (hunk 1 above)
Comment (WantenMN) [reply crates/gpui/src/platform/linux/wayland/window.rs:639]: Thanks so much for the detailed explanation of `selection.reversed`!  I appreciate you taking the time to clarify that.

However, I’m still a bit puzzled about restoring the `selection.reversed` check in `get_ime_area`, and I wanted to share my observations to see if I’m missing something. 

From what I’ve noticed, `get_ime_area` only gets called when starting to input text (e.g., Chinese characters), and it doesn’t seem to be used during text selection. If I select text and then start typing, the selected text gets immediately replaced by the new input, which makes me think `selection.reversed` might not apply here. At the moment of input, `selection.range.start` and `selection.range.end` seem to be the same value (the cursor position), so checking `reversed` doesn’t appear to make a difference.

I also tried selecting text during IME composing (pre-edit) state, but the pre-edit session gets interrupted immediately—the candidate box disappears, and input stops. So, I’m wondering: is it even possible to have a text selection active during composition? If not, I’m not sure how `selection.reversed` would come into play.

Another point is that `marked_text_range`, which I switched to, doesn’t return a `reversed` attribute, unlike `selected_text_range`. More importantly, during IME composing (pre-edit) state, in `selected_text_range`, the call to `selections.newest::<OffsetUtf16>(cx)` returns the latest cursor position, where the range’s `start` and `end` are always identical. This seems to confirm that whether the selection is reversed or not, it wouldn’t affect the outcome in this case.

https://github.com/zed-industries/zed/blob/353ae2335b8b72fd29ac099e90455477c98c6e38/crates/editor/src/editor.rs#L19707

I might be overlooking something, so I’d love to hear your thoughts! Should we still restore the `selection.reversed` check for a specific edge case I haven’t considered? Thanks again for your guidance—this discussion is super helpful for getting to the bottom of this.

Comment (mikayla-maki) [reply crates/gpui/src/platform/linux/wayland/window.rs:639]: Nice call @WantenMN, I hadn't realized that the marked_text_range call doesn't return the reversed bit.

**Review by mikayla-maki — APPROVED** [review]

**Comment by JunkuiZhang** [comment]
@WantenMN Hello, looks like this PR requires a rebase on main

**Comment by imumesh18** [comment]
Hey @JunkuiZhang last pr merge broke the ci. I have a pr open: https://github.com/zed-industries/zed/pull/32049. I believe this pr will be fixed once we have this on main.

**Comment by JunkuiZhang** [comment]
@imumesh18 Thanks for the fix!

**Comment by JunkuiZhang** [comment]
Still requires a rebase I think, tests failed even that pr was merged

**Comment by JunkuiZhang** [comment]
Thanks!
