### PR TITLE
markdown: Add HTML `img` tag support

### LINKED ISSUE #21992: preview markdown support for png images
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed does not appear to render png files that are listed in the markdown.

e.g. if `png/myimage.png` exists then `` should render the image in the preview.

I tested this in Zed and don't see the image.
The same markdown renders the image in VSCode.

### Environment

Zed: v0.165.4 (Zed)
OS: Linux X11 pop 22.04
Memory: 23.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by RemcoSmitsDev**
Closes #21992

Screenshot 2025-08-21 at 18 09 24

Code example:

```markdown
# Html Tag
<img src="https://picsum.photos/200/300" alt="Description of image" />

# Html Tag with width and height
<img src="https://picsum.photos/200/300" alt="Description of image" width="100" height="200" />

# Html Tag with style attribute with width and height
<img src="https://picsum.photos/200/300" alt="Description of image" style="width: 100px; height: 200px" />

# Normal Tag
![alt text](https://picsum.photos/200/300)
```

Release Notes:

- Markdown: Added HTML `` tag support

### CODE REVIEW

File: crates/markdown_preview/src/markdown_parser.rs [hunk 1]
```diff
@@ -741,6 +746,78 @@ impl<'a> MarkdownParser<'a> {
...
+            if let Some(width) = element
+                .attr("width")
+                .and_then(|width| width.parse::<u32>().ok())
+            {
+                image.set_width(width);
+            }
+
+            if let Some(height) = element
+                .attr("height")
+                .and_then(|height| height.parse::<u32>().ok())
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs]:
```rs
/// Parse length value from style attribute.
///
/// When is percentage, it will be converted to relative length.
/// Else, it will be converted to pixels.
fn value_to_length(value: &str) -> Option<DefiniteLength> {
    if value.ends_with("%") {
        value
            .trim_end_matches("%")
            .parse::<f32>()
            .ok()
            .map(|v| relative(v / 100.))
    } else {
        value
            .trim_end_matches("px")
            .parse()
            .ok()
            .map(|v| px(v).into())
    }
}
```

https://github.com/longbridge/gpui-component/blob/09ab49b2d3c9278cdf763d6570a5cd5a1503428e/crates/ui/src/text/html.rs#L259-L283

Use like this method can support `100%` and `100px` both.

Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_parser.rs]: Yeah nice catch will change that! Thanks

Comment (huacnlee) [reply crates/markdown_preview/src/markdown_parser.rs]: Also the width, height may inside the `style` attribute.

So we can extract from style.

```rs
/// Get style properties to HashMap
/// TODO: Use cssparser to parse style attribute.
fn style_attrs(attrs: &RefCell<Vec<html5ever::Attribute>>) -> HashMap<String, String> {
    let mut styles = HashMap::new();
    let Some(css_text) = attr_value(attrs, local_name!("style")) else {
        return styles;
    };

    for decl in css_text.split(';') {
        for rule in decl.split(':') {
            let mut parts = rule.splitn(2, ':');
            if let (Some(key), Some(value)) = (parts.next(), parts.next()) {
                styles.insert(
                    key.trim().to_lowercase().to_string(),
                    value.trim().to_string(),
                );
            }
        }
    }

    styles
}

/// Get width, height from attributes or parse them from style attribute.
fn attr_width_height(
    attrs: &RefCell<Vec<html5ever::Attribute>>,
) -> (Option<DefiniteLength>, Option<DefiniteLength>) {
    let mut width = None;
    let mut height = None;

    if let Some(value) = attr_value(attrs, local_name!("width")) {
        width = value_to_length(&value);
    }

    if let Some(value) = attr_value(attrs, local_name!("height")) {
        height = value_to_length(&value);
    }

    if width.is_none() || height.is_none() {
        let styles = style_attrs(attrs);
        if width.is_none() {
            width = styles.get("width").and_then(|v| value_to_length(&v));
        }
        if height.is_none() {
            height = styles.get("height").and_then(|v| value_to_length(&v));
        }
    }

    (width, height)
}
```

Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_parser.rs]: Thanks for providing the code that you used for your markdown parser. I found one issue with your css parser code, submitted a PR for it: https://github.com/longbridge/gpui-component/pull/1171

**Comment by RemcoSmitsDev** [comment]
In a follow-up PR, we can support other HTML elements and add better support for HTML text.

File: crates/markdown_preview/src/markdown_parser.rs [hunk 2]
```diff
@@ -741,6 +749,177 @@ impl<'a> MarkdownParser<'a> {
             highlights,
         }
     }
+
+    async fn parse_html_block(&mut self) -> Vec<ParsedMarkdownElement> {
+        let (_event, _source_range) = self.previous().unwrap();
+        let mut elements = Vec::new();
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs:762]: Avoid unwrap, if unexpected, here we can just return an empty Vec.

File: crates/markdown_preview/src/markdown_parser.rs [hunk 3]
```diff
@@ -741,6 +749,177 @@ impl<'a> MarkdownParser<'a> {
...
+                .parse::<f32>()
+                .ok()
+                .map(|value| relative(value / 100.))
+        } else {
+            value
+                .trim_end_matches("px")
+                .parse()
+                .ok()
+                .map(|value| px(value).into())
+        }
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs:927]: This method only need `if value.ends_with("%") { } else { }`

```rs
if value.ends_with("%") {
    value
        .trim_end_matches("%")
        .parse::<f32>()
        .ok()
        .map(|v| relative(v / 100.))
} else {
    value
        .trim_end_matches("px")
        .parse()
        .ok()
        .map(|v| px(v).into())
}
```

File: crates/markdown_preview/src/markdown_parser.rs [hunk 4]
```diff
@@ -1004,11 +1192,77 @@ mod tests {
...
+                source_range: 0..65,
+                link: Link::Web {
+                    url: "http://example.com/foo.png".to_string(),
+                },
+                alt_text: None,
+                height: Some(DefiniteLength::Absolute(AbsoluteLength::Pixels(px(100.)))),
+                width: Some(DefiniteLength::Absolute(AbsoluteLength::Pixels(px(200.)))),
+            },
+        );
+    }
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs:1334]: More test for `style="width: 100%"`

File: crates/markdown_preview/src/markdown_parser.rs [hunk 5]
```diff
@@ -2,9 +2,12 @@ use crate::markdown_elements::*;
 use async_recursion::async_recursion;
 use collections::FxHashMap;
 use gpui::FontWeight;
+use html5ever::{ParseOpts, local_name, parse_document, tendril::TendrilSink};
 use language::LanguageRegistry;
+use markup5ever_rcdom::RcDom;
 use pulldown_cmark::{Alignment, Event, Options, Parser, Tag, TagEnd};
-use std::{ops::Range, path::PathBuf, sync::Arc, vec};
+use std::{cell::RefCell, collections::HashMap, ops::Range, path::PathBuf, rc::Rc, sync::Arc, vec};
+use ui::{px, relative};
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs]: ? Why not from `gpui::{px, relative}`

File: crates/markdown_preview/src/markdown_parser.rs [hunk 6]
```diff
@@ -741,6 +749,177 @@ impl<'a> MarkdownParser<'a> {
...
+            .and_then(|height| Self::parse_length(&height))
+        {
+            image.set_height(height);
+        }
+
+        Some(image)
+    }
+
+    /// Parses the width/height attribute value of an html element (e.g. img element)
+    fn parse_length(value: &str) -> Option<ui::DefiniteLength> {
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs]: `Option<ui::DefiniteLength>` -> `Option<DefiniteLength>`

File: crates/markdown_preview/src/markdown_renderer.rs [hunk 7]
```diff
@@ -259,7 +263,7 @@ fn render_markdown_list_item(
             )
             .hover(|s| s.cursor_pointer())
             .tooltip(|_, cx| {
-                InteractiveMarkdownElementTooltip::new(None, "toggle checkbox", cx).into()
+                InteractiveMarkdownElementTooltip::new(None, TOGGLE_CHECKBOX_TOOLTIP, cx).into()
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_renderer.rs]: There seems to be no need to change it to const here. 

This line is only triggered when hovering, and the overhead is minimal.

**Comment by huacnlee** [comment]
I feel the other parts are OK. Based on the current adjustments, MarkdownPreview can easily support more HTML formats little by little on this basis.

File: crates/markdown_preview/src/markdown_parser.rs (hunk 5 above)
Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_parser.rs]: I think auto import, changed it to be from gpui.

File: crates/markdown_preview/src/markdown_renderer.rs (hunk 7 above)
Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_renderer.rs]: yeah true, but like it more than doing an into everytime we want to create a tooltip

File: crates/markdown_preview/src/markdown_elements.rs [hunk 8]
```diff
@@ -3,6 +3,7 @@ use gpui::{
 };
 use language::HighlightId;
 use std::{fmt::Display, ops::Range, path::PathBuf};
+use ui::DefiniteLength;
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_elements.rs]: gpui::DefiniteLength

File: crates/markdown_preview/src/markdown_renderer.rs (hunk 7 above)
Comment (huacnlee) [reply crates/markdown_preview/src/markdown_renderer.rs]: My takeaway here is that you can avoid unnecessary changes.

Secondly, your changes' is no improve, because:

https://github.com/zed-industries/zed/blob/fda6eda3c2abcbe90af48bd112ee560eb63706e7/crates/markdown_preview/src/markdown_renderer.rs#L802-L809

Comment (huacnlee) [reply crates/markdown_preview/src/markdown_renderer.rs]: Oh, I see you have changed that code.

But you assign a static str here, is a very low cost. The SharedString will ref that static str.

File: crates/markdown_preview/src/markdown_renderer.rs [hunk 9]
```diff
@@ -793,18 +739,86 @@ fn render_markdown_rule(cx: &mut RenderContext) -> AnyElement {
...
     tooltip_text: Option<SharedString>,
-    action_text: String,
+    action_text: SharedString,
 }
 
 impl InteractiveMarkdownElementTooltip {
-    pub fn new(tooltip_text: Option<String>, action_text: &str, cx: &mut App) -> Entity<Self> {
+    pub fn new(
+        tooltip_text: Option<SharedString>,
+        action_text: SharedString,
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_renderer.rs]: This should change to `action_text: impl Into<SharedString>`

Then we can `InteractiveMarkdownElementTooltip::new(None, "foo", cx)`

File: crates/markdown_preview/src/markdown_parser.rs [hunk 10]
```diff
@@ -734,27 +750,195 @@ impl<'a> MarkdownParser<'a> {
...
-
     use ParsedMarkdownListItemType::*;
-    use gpui::BackgroundExecutor;
+    use core::panic;
+    use gpui::{AbsoluteLength, BackgroundExecutor, DefiniteLength};
     use language::{
         HighlightId, Language, LanguageConfig, LanguageMatcher, LanguageRegistry, tree_sitter_rust,
     };
     use pretty_assertions::assert_eq;
+    use ui::Pixels;
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs]: gpui::Pixels

File: crates/markdown_preview/src/markdown_parser.rs [hunk 11]
```diff
@@ -1004,11 +1196,182 @@ mod tests {
...
+        assert_eq!(MarkdownParser::parse_length("abcpx"), None);
+
+        // Test decimal values
+        assert_eq!(
+            MarkdownParser::parse_length("50.5%"),
+            Some(DefiniteLength::Fraction(0.505))
+        );
+        assert_eq!(
+            MarkdownParser::parse_length("100.25px"),
+            Some(DefiniteLength::Absolute(AbsoluteLength::Pixels(Pixels(
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_parser.rs]: Use `px` method

File: crates/markdown_preview/src/markdown_renderer.rs (hunk 9 above)
Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_renderer.rs]: Ahh oke, thanks!

File: crates/markdown_preview/src/markdown_elements.rs [hunk 12]
```diff
@@ -1,3 +1,4 @@
+use gpui::DefiniteLength;
 use gpui::{
     FontStyle, FontWeight, HighlightStyle, SharedString, StrikethroughStyle, UnderlineStyle, px,
 };
```
Comment (huacnlee) [inline crates/markdown_preview/src/markdown_elements.rs:4]: merge

**Review by huacnlee — APPROVED** [review]

File: crates/markdown_preview/Cargo.toml [hunk 13]
```diff
@@ -19,19 +19,21 @@ anyhow.workspace = true
 async-recursion.workspace = true
 collections.workspace = true
 editor.workspace = true
+fs.workspace = true
```
Comment (SomeoneToIgnore) [inline crates/markdown_preview/Cargo.toml:22]: Very strange that `machete` is not reacting, but new code dose not use this, it seems?

Let's remove it if we can, otherwise curious to get some context.

Comment (SomeoneToIgnore) [reply crates/markdown_preview/Cargo.toml:22]: Ahh, `Cargo.lock` seems to be not updated even, maybe that's why the machete is fine.

File: crates/markdown_preview/src/markdown_parser.rs [hunk 14]
```diff
@@ -734,23 +750,190 @@ impl<'a> MarkdownParser<'a> {
...
+            .and_then(|height| Self::parse_length(&height))
+        {
+            image.set_height(height);
+        }
+
+        Some(image)
+    }
+
+    /// Parses the width/height attribute value of an html element (e.g. img element)
+    fn parse_length(value: &str) -> Option<DefiniteLength> {
```
Comment (SomeoneToIgnore) [inline crates/markdown_preview/src/markdown_parser.rs:914]: Optional NIT: `parse_html_element_dimension` or anything else might help to remove the comment.

**Review by SomeoneToIgnore — COMMENTED** [review]
Given the isolated nature of the markdown renderer, happy to trust @\huacnlee and you on this change — but let's deal with dependency issues before.

File: crates/markdown_preview/Cargo.toml (hunk 13 above)
Comment (RemcoSmitsDev) [reply crates/markdown_preview/Cargo.toml:22]: It was already there but just did a sort of all the deps.

Comment (SomeoneToIgnore) [reply crates/markdown_preview/Cargo.toml:22]: Indeed, sorry.

**Review by SomeoneToIgnore — APPROVED** [review]

File: crates/markdown_preview/src/markdown_parser.rs (hunk 14 above)
Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_parser.rs:914]: Will change this then!

Comment (SomeoneToIgnore) [reply crates/markdown_preview/src/markdown_parser.rs:914]: Ah, well, I was too hasty again...

Looking forward for more tag support in this preview from you later then! 😄

Comment (RemcoSmitsDev) [reply crates/markdown_preview/src/markdown_parser.rs:914]: No worries! Will work soon on adding more of them🙂
