### PR TITLE
Use shared text system on Linux and Windows

### LINKED ISSUE #10129: panic loading Extension page on Windows
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Crash when opening the Extensions page on Windows. 

It appears the emoji font is missing from `self.fonts` https://github.com/zed-industries/zed/blob/469be39a32133c4a5a68780f7dcc45ac62656061/crates/gpui/src/platform/windows/text_system.rs#L364-L369

Probably because `Segoe UI Emoji` wasn't loaded with `load_family`

https://github.com/zed-industries/zed/blob/469be39a32133c4a5a68780f7dcc45ac62656061/crates/gpui/src/platform/windows/text_system.rs#L235-L239

### Environment

Zed: v0.130.0 (Zed Dev b118b762728bf802d9b4e9f89c0502de43f246dc)
OS: Windows 10.0.22631
Memory: 15.8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

The full stack trace is long but here's the relevant part:

```
Thread "main" panicked with "called `Option::unwrap()` on a `None` value" at crates\gpui\src\platform\windows\text_system.rs:368:22
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\Danny\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\Danny\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\Danny\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\Danny\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:176
   4: backtrace::capture::Backtrace::new
             at C:\Users\Danny\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:140
   5: Zed::init_panic_hook::closure$0
             at crates\zed\src\main.rs:645
   6: alloc::boxed::impl$49::call
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\alloc\src\boxed.rs:2029
   7: std::panicking::rust_panic_with_hook
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:785
   8: std::panicking::begin_panic_handler::closure$0
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:651
   9: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\sys_common\backtrace.rs:171
  10: std::panicking::begin_panic_handler
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:647
  11: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\panicking.rs:72
  12: core::panicking::panic
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\panicking.rs:144
  13: core::option::unwrap_failed
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\option.rs:1978
  14: core::option::Option::unwrap
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\option.rs:931
  15: gpui::platform::windows::text_system::WindowsTextSystemState::layout_line
             at crates\gpui\src\platform\windows\text_system.rs:365
  16: gpui::platform::windows::text_system::impl$2::layout_line
             at crates\gpui\src\platform\windows\text_system.rs:177
  17: gpui::text_system::line_layout::LineLayoutCache::layout_line
             at crates\gpui\src\text_system\line_layout.rs:425
  18: gpui::text_system::line_layout::LineLayoutCache::layout_wrapped_line
             at crates\gpui\src\text_system\line_layout.rs:378
  19: gpui::text_system::impl$1::shape_text::closure$0
             at crates\gpui\src\text_system.rs:415
  20: gpui::text_system::WindowTextSystem::shape_text
             at crates\gpui\src\text_system.rs:452
  21: gpui::elements::text::impl$8::layout::closure$0
             at crates\gpui\src\elements\text.rs:242
```

### LINKED ISSUE #10269: [Windows build] crashes when jumping into extension management and joining channels
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

here is the traceback when `cargo run` (and switch to extension management page):

```
 0: backtrace::backtrace::dbghelp::trace
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:176     
   4: backtrace::capture::Backtrace::new
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:140     
   5: Zed::init_panic_hook::closure$0
             at crates\zed\src\main.rs:645
   6: alloc::boxed::impl$49::call
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\alloc\src\boxed.rs:2029
   7: std::panicking::rust_panic_with_hook
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:785
   8: std::panicking::begin_panic_handler::closure$0
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:651
   9: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>     
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\sys_common\backtrace.rs:171
  10: std::panicking::begin_panic_handler
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:647
  11: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\panicking.rs:72
  12: core::panicking::panic
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\panicking.rs:144
  13: core::option::unwrap_failed
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\core\src\option.rs:1978
  14: core::option::Option::unwrap
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\option.rs:931
  15: gpui::platform::windows::text_system::WindowsTextSystemState::layout_line
             at crates\gpui\src\platform\windows\text_system.rs:365
  16: gpui::platform::windows::text_system::impl$2::layout_line
             at crates\gpui\src\platform\windows\text_system.rs:177
  17: gpui::text_system::line_layout::LineLayoutCache::layout_line
             at crates\gpui\src\text_system\line_layout.rs:425
  18: gpui::text_system::line_layout::LineLayoutCache::layout_wrapped_line
             at crates\gpui\src\text_system\line_layout.rs:378
  19: gpui::text_system::impl$1::shape_text::closure$0
             at crates\gpui\src\text_system.rs:415
  20: gpui::text_system::WindowTextSystem::shape_text
             at crates\gpui\src\text_system.rs:452
  21: gpui::elements::text::impl$8::layout::closure$0
             at crates\gpui\src\elements\text.rs:242
  22: alloc::boxed::impl$48::call_mut<tuple$<gpui::geometry::Size<enum2$<core::option::Option<gpui::geometry::Pixels> > >,gpui::geometry::Size<enum2$<gpui::taffy::AvailableSpace> >,ref_mut$<gpui::window::WindowContext> >,dyn$<core::ops::function::FnMut<tuple$<g
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\alloc\src\boxed.rs:2022
  23: gpui::taffy::impl$0::compute_layout::closure$0
             at crates\gpui\src\taffy.rs:193
  24: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:200
  25: core::ops::function::FnOnce::call_once<taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0::closure_env$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>,tuple$<taffy::geometry::Size<enum2$<core::option::Option<f32> > >,taffy::ge
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\ops\function.rs:250
  26: taffy::compute::leaf::compute_leaf_layout<taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0::closure_env$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\leaf.rs:119
  27: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:202
  28: taffy::compute::block::determine_content_based_container_width::closure$1<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:292
  29: taffy::compute::block::determine_content_based_container_width<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:289
  30: taffy::compute::block::compute_inner::closure$1<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:158
  31: core::option::Option::unwrap_or_else
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\option.rs:976
  32: taffy::compute::block::compute_inner<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:156
  33: taffy::compute::block::compute_block_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:91
  34: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:189
  35: taffy::compute::flexbox::determine_flex_base_size<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:644
  36: taffy::compute::flexbox::compute_preliminary<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:207
  37: taffy::compute::flexbox::compute_flexbox_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:181
  38: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:191
  39: taffy::compute::flexbox::determine_flex_base_size<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:644
  40: taffy::compute::flexbox::compute_preliminary<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:207
  41: taffy::compute::flexbox::compute_flexbox_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:181
  42: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:191
  43: taffy::compute::flexbox::determine_flex_base_size<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:644
  44: taffy::compute::flexbox::compute_preliminary<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:207
  45: taffy::compute::flexbox::compute_flexbox_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\flexbox.rs:181
  46: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:191
  47: taffy::compute::compute_cached_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\mod.rs:76
  48: taffy::tree::taffy_tree::impl$5::compute_child_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:172
  49: taffy::tree::PartialLayoutTreeExt::perform_child_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\mod.rs:105
  50: taffy::compute::block::perform_final_layout_on_in_flow_children<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:343
  51: taffy::compute::block::compute_inner<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:173
  52: taffy::compute::block::compute_block_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\block.rs:91
  53: taffy::tree::taffy_tree::impl$5::compute_child_layout::closure$0<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:189
  54: taffy::compute::compute_cached_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\mod.rs:76
  55: taffy::tree::taffy_tree::impl$5::compute_child_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:172
  56: taffy::tree::PartialLayoutTreeExt::perform_child_layout
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\mod.rs:105
  57: taffy::compute::compute_layout<taffy::tree::taffy_tree::TaffyView<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0> >
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\compute\mod.rs:37
  58: taffy::tree::taffy_tree::Taffy::compute_layout_with_measure<tuple$<>,gpui::taffy::impl$0::compute_layout::closure_env$0>
             at C:\Users\bians\.cargo\git\checkouts\taffy-3438f0b42e7e0e0f\1876f72\src\tree\taffy_tree.rs:535
  59: gpui::taffy::TaffyLayoutEngine::compute_layout
             at crates\gpui\src\taffy.rs:179
  60: gpui::window::element_cx::ElementContext::compute_layout
             at crates\gpui\src\window\element_cx.rs:1293
  61: gpui::element::Drawable::measure<gpui::element::Component<extensions_ui::components::extension_card::ExtensionCard> > 
             at crates\gpui\src\element.rs:337
  62: gpui::element::impl$6::measure<gpui::element::Component<extensions_ui::components::extension_card::ExtensionCard> >   
             at crates\gpui\src\element.rs:393
  63: gpui::element::AnyElement::measure
             at crates\gpui\src\element.rs:439
  64: gpui::element::AnyElement::layout
             at crates\gpui\src\element.rs:449
  65: gpui::elements::uniform_list::impl$2::after_layout::closure$1::closure$0
             at crates\gpui\src\elements\uniform_list.rs:225
  66: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<>,gpui::elements::uniform_list::impl$2::after_layout::closure$1::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:630
  67: gpui::elements::uniform_list::impl$2::after_layout::closure$1
             at crates\gpui\src\elements\uniform_list.rs:217
  68: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::uniform_list::impl$2::after_layout::closure_env$1>
             at crates\gpui\src\elements\div.rs:1339
  69: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:630
  70: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::uniform_list::impl$2::after_layout::closure_env$1>
             at crates\gpui\src\elements\div.rs:1331
  71: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::uniform_list::impl$2::after_layout::closure_env$1
             at crates\gpui\src\window\element_cx.rs:579
  72: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::uniform_list::impl$2::after_layout::closure_env$1>
             at crates\gpui\src\elements\div.rs:1330
  73: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:845
  74: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:611
  75: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
  76: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::uniform_list::impl$2::after_layout::closure_env$1>
             at crates\gpui\src\elements\div.rs:1308
  77: gpui::elements::uniform_list::impl$2::after_layout
             at crates\gpui\src\elements\uniform_list.rs:169
  78: gpui::element::Drawable::after_layout<gpui::elements::uniform_list::UniformList>
             at crates\gpui\src\element.rs:291
  79: gpui::element::impl$6::after_layout<gpui::elements::uniform_list::UniformList>
             at crates\gpui\src\element.rs:381
  80: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
  81: gpui::element::impl$7::layout::closure$0
             at crates\gpui\src\element.rs:450
  82: gpui::window::element_cx::ElementContext::with_absolute_element_offset<tuple$<>,gpui::element::impl$7::layout::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:664
  83: gpui::element::AnyElement::layout
             at crates\gpui\src\element.rs:450
  84: extensions_ui::impl$2::render::closure$7::closure$0
             at crates\extensions_ui\src\extensions_ui.rs:906
  85: core::ops::function::FnOnce::call_once<extensions_ui::impl$2::render::closure$7::closure_env$0,tuple$<gpui::geometry::Bounds<gpui::geometry::Pixels>,ref_mut$<gpui::window::element_cx::ElementContext> > >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\ops\function.rs:250
  86: alloc::boxed::impl$47::call_once<tuple$<gpui::geometry::Bounds<gpui::geometry::Pixels>,ref_mut$<gpui::window::element_cx::ElementContext> >,dyn$<core::ops::function::FnOnce<tuple$<gpui::geometry::Bounds<gpui::geometry::Pixels>,ref_mut$<gpui::window::eleme
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\alloc\src\boxed.rs:2015
  87: gpui::elements::canvas::impl$1::after_layout<gpui::element::AnyElement>
             at crates\gpui\src\elements\canvas.rs:51
  88: gpui::element::Drawable::after_layout<gpui::elements::canvas::Canvas<gpui::element::AnyElement> >
             at crates\gpui\src\element.rs:291
  89: gpui::element::impl$6::after_layout<gpui::elements::canvas::Canvas<gpui::element::AnyElement> >
             at crates\gpui\src\element.rs:381
  90: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
  91: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
  92: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
  93: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
  94: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
  95: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:630
  96: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
  97: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
  98: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
  99: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 100: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 101: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 102: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 103: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 104: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 105: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 106: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 107: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 108: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 109: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 110: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 111: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:634
 112: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 113: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 114: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 115: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 116: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 117: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 118: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 119: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 120: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 121: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 122: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 123: gpui::view::impl$16::after_layout::closure$1
             at crates\gpui\src\view.rs:350
 124: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::element::AnyElement> >,enum2$<gpui::window::ElementId>,gpui::view::impl$16::after_layout::closure_env$1>
             at crates\gpui\src\window\element_cx.rs:611
 125: gpui::view::impl$16::after_layout
             at crates\gpui\src\view.rs:348
 126: gpui::element::Drawable::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:291
 127: gpui::element::impl$6::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:381
 128: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 129: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 130: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 131: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 132: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 133: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:634
 134: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 135: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 136: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 137: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 138: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 139: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 140: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 141: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 142: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 143: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 144: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 145: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 146: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 147: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 148: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 149: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:630
 150: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 151: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 152: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 153: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 154: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 155: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 156: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 157: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 158: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 159: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 160: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 161: gpui::element::impl$7::layout::closure$0
             at crates\gpui\src\element.rs:450
 162: gpui::window::element_cx::ElementContext::with_absolute_element_offset<tuple$<>,gpui::element::impl$7::layout::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:664
 163: gpui::element::AnyElement::layout
             at crates\gpui\src\element.rs:450
 164: gpui::view::impl$16::after_layout::closure$0
             at crates\gpui\src\view.rs:330
 165: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::view::AnyViewState,enum2$<core::option::Option<gpui::element::AnyElement> >,gpui::view::impl$16::after_layout::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:845
 166: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::element::AnyElement> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::view::AnyViewState,enum2$<core::o
             at crates\gpui\src\window\element_cx.rs:611
 167: gpui::window::element_cx::ElementContext::with_element_state<gpui::view::AnyViewState,enum2$<core::option::Option<gpui::element::AnyElement> >,gpui::view::impl$16::after_layout::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:790
 168: gpui::view::impl$16::after_layout
             at crates\gpui\src\view.rs:305
 169: gpui::element::Drawable::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:291
 170: gpui::element::impl$6::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:381
 171: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 172: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 173: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 174: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 175: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 176: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:634
 177: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 178: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 179: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 180: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 181: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 182: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 183: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 184: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 185: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 186: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 187: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 188: gpui::element::impl$8::after_layout
             at crates\gpui\src\element.rs:470
 189: gpui::element::Drawable::after_layout<gpui::element::AnyElement>
             at crates\gpui\src\element.rs:291
 190: gpui::element::impl$6::after_layout<gpui::element::AnyElement>
             at crates\gpui\src\element.rs:381
 191: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 192: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 193: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 194: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 195: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 196: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:630
 197: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 198: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 199: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 200: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 201: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 202: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 203: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 204: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 205: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 206: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 207: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 208: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 209: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 210: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 211: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 212: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:634
 213: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 214: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 215: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 216: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 217: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 218: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 219: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 220: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 221: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 222: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 223: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 224: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 225: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 226: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 227: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 228: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:630
 229: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 230: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:579
 231: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 232: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:845
 233: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:611
 234: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 235: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 236: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 237: gpui::elements::div::impl$22::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\elements\div.rs:2299
 238: gpui::element::Drawable::after_layout<gpui::elements::div::Stateful<gpui::elements::div::Div> >
             at crates\gpui\src\element.rs:291
 239: gpui::element::impl$6::after_layout<gpui::elements::div::Stateful<gpui::elements::div::Div> >
             at crates\gpui\src\element.rs:381
 240: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 241: gpui::elements::div::impl$5::after_layout::closure$0::closure$0
             at crates\gpui\src\elements\div.rs:1148
 242: gpui::window::element_cx::ElementContext::with_element_offset<tuple$<>,gpui::elements::div::impl$5::after_layout::closure$0::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:646
 243: gpui::elements::div::impl$5::after_layout::closure$0
             at crates\gpui\src\elements\div.rs:1146
 244: gpui::elements::div::impl$7::after_layout::closure$0::closure$1::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1339
 245: gpui::window::element_cx::ElementContext::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$7::after_layout::clo
             at crates\gpui\src\window\element_cx.rs:634
 246: gpui::elements::div::impl$7::after_layout::closure$0::closure$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1331
 247: gpui::window::element_cx::ElementContext::with_text_style<gpui::elements::div::impl$7::after_layout::closure$0::closure_env$1<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>,tuple$<
             at crates\gpui\src\window\element_cx.rs:575
 248: gpui::elements::div::impl$7::after_layout::closure$0<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1330
 249: gpui::window::element_cx::impl$12::with_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Opt
             at crates\gpui\src\window\element_cx.rs:792
 250: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,enum2$<gpui::window::ElementId>,gpui::window::element_cx::impl$12::with_element_state::closure_env$0<gpui::elements::div::Interactive
             at crates\gpui\src\window\element_cx.rs:616
 251: gpui::window::element_cx::ElementContext::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$7::after_layout::closure_env$0<enum2$<core::option::Option<
             at crates\gpui\src\window\element_cx.rs:790
 252: gpui::elements::div::Interactivity::after_layout<enum2$<core::option::Option<gpui::window::element_cx::Hitbox> >,gpui::elements::div::impl$5::after_layout::closure_env$0>
             at crates\gpui\src\elements\div.rs:1308
 253: gpui::elements::div::impl$5::after_layout
             at crates\gpui\src\elements\div.rs:1141
 254: gpui::element::Drawable::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:291
 255: gpui::element::impl$6::after_layout<gpui::elements::div::Div>
             at crates\gpui\src\element.rs:381
 256: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 257: gpui::view::impl$16::after_layout::closure$1
             at crates\gpui\src\view.rs:350
 258: gpui::window::element_cx::ElementContext::with_element_id<enum2$<core::option::Option<gpui::element::AnyElement> >,enum2$<gpui::window::ElementId>,gpui::view::impl$16::after_layout::closure_env$1>
             at crates\gpui\src\window\element_cx.rs:611
 259: gpui::view::impl$16::after_layout
             at crates\gpui\src\view.rs:348
 260: gpui::element::Drawable::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:291
 261: gpui::element::impl$6::after_layout<gpui::view::AnyView>
             at crates\gpui\src\element.rs:381
 262: gpui::element::AnyElement::after_layout
             at crates\gpui\src\element.rs:425
 263: gpui::element::impl$7::layout::closure$0
             at crates\gpui\src\element.rs:450
 264: gpui::window::element_cx::ElementContext::with_absolute_element_offset<tuple$<>,gpui::element::impl$7::layout::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:664
 265: gpui::element::AnyElement::layout
             at crates\gpui\src\element.rs:450
 266: gpui::window::element_cx::ElementContext::draw_roots
             at crates\gpui\src\window\element_cx.rs:358
 267: gpui::window::impl$17::draw::closure$0
             at crates\gpui\src\window.rs:1021
 268: gpui::window::WindowContext::with_element_context<tuple$<>,gpui::window::impl$17::draw::closure_env$0>
             at crates\gpui\src\window\element_cx.rs:215
 269: gpui::window::WindowContext::draw
             at crates\gpui\src\window.rs:1021
 270: gpui::window::impl$15::new::closure$2::closure$1::closure$0
             at crates\gpui\src\window.rs:471
 271: gpui::app::impl$5::update_window::closure$0<tuple$<>,gpui::window::impl$15::new::closure$2::closure$1::closure_env$0> 
             at crates\gpui\src\app.rs:1282
 272: gpui::app::AppContext::update<enum2$<core::result::Result<tuple$<>,anyhow::Error> >,gpui::app::impl$5::update_window::closure_env$0<tuple$<>,gpui::window::impl$15::new::closure$2::closure$1::closure_env$0> >
             at crates\gpui\src\app.rs:363
 273: gpui::app::impl$5::update_window<tuple$<>,gpui::window::impl$15::new::closure$2::closure$1::closure_env$0>
             at crates\gpui\src\app.rs:1273
 274: gpui::app::async_context::impl$0::update_window<tuple$<>,gpui::window::impl$15::new::closure$2::closure$1::closure_env$0>
             at crates\gpui\src\app\async_context.rs:70
 275: gpui::window::AnyWindowHandle::update<gpui::app::async_context::AsyncAppContext,tuple$<>,gpui::window::impl$15::new::closure$2::closure$1::closure_env$0>
             at crates\gpui\src\window.rs:2741
 276: gpui::window::impl$15::new::closure$2::closure$1
             at crates\gpui\src\window.rs:469
 277: util::measure<tuple$<>,gpui::window::impl$15::new::closure$2::closure_env$1>
             at crates\util\src\util.rs:186
 278: gpui::window::impl$15::new::closure$2
             at crates\gpui\src\window.rs:468
 279: alloc::boxed::impl$48::call_mut<tuple$<>,dyn$<core::ops::function::FnMut<tuple$<>,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\alloc\src\boxed.rs:2022
 280: gpui::platform::windows::window::WindowsWindowInner::handle_paint_msg
             at crates\gpui\src\platform\windows\window.rs:358
 281: gpui::platform::windows::window::WindowsWindowInner::handle_msg
             at crates\gpui\src\platform\windows\window.rs:262
 282: gpui::platform::windows::window::wnd_proc
             at crates\gpui\src\platform\windows\window.rs:1764
 283: DispatchMessageW
 284: CallWindowProcW
 285: wglSwapBuffers
 286: DispatchMessageW
 287: DispatchMessageW
 288: GetClassLongW
 289: KiUserCallbackDispatcher
 290: NtUserRedrawWindow
 291: windows::Win32::Graphics::Gdi::RedrawWindow<windows::Win32::Foundation::HWND,windows::Win32::Graphics::Gdi::HRGN>     
             at C:\Users\bians\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.53.0\src\Windows\Win32\Graphics\Gdi\mod.rs:2392
 292: gpui::platform::windows::platform::WindowsPlatform::redraw_all
             at crates\gpui\src\platform\windows\platform.rs:188
 293: gpui::platform::windows::platform::impl$3::run
             at crates\gpui\src\platform\windows\platform.rs:232
 294: gpui::app::App::run<Zed::main::closure_env$3>
             at crates\gpui\src\app.rs:142
 295: Zed::main
             at crates\zed\src\main.rs:138
 296: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\core\src\ops\function.rs:250
 297: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\std\src\sys_common\backtrace.rs:155
 298: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\std\src\sys_common\backtrace.rs:155
 299: std::rt::lang_start::closure$0<tuple$<> >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\std\src\rt.rs:166
 300: std::rt::lang_start_internal::closure$2
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\rt.rs:148
 301: std::panicking::try::do_call
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:554
 302: std::panicking::try
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panicking.rs:518
 303: std::panic::catch_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\panic.rs:142
 304: std::rt::lang_start_internal
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library\std\src\rt.rs:148
 305: std::rt::lang_start<tuple$<> >
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97\library\std\src\rt.rs:165
 306: main
 307: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
 308: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 309: BaseThreadInitThunk
 310: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)
```

### Environment

Build: https://github.com/HeavySnowJakarta/zed/releases/tag/5a2a85a7

toolchain:
```
x86_64-pc-windows-msvc
cargo 1.76.0 (c84b36747 2024-01-18)
Windows 11 23H2 22631.3296
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

none

### PR DESCRIPTION
**Pull request by zaucy**
closes #10129
closes #10269

Release Notes:

- N/A

### CODE REVIEW

File: crates/gpui/src/platform/common/text_system.rs [hunk 1]
```diff
@@ -228,8 +228,15 @@ impl LinuxTextSystemState {
                 .get_font(font_id)
                 .ok_or_else(|| anyhow!("Could not load font"))?;
 
-            // HACK: to let the storybook run, we should actually do better font fallback
-            if font.as_swash().charmap().map('m') == 0 || postscript_name == "Segoe Fluent Icons" {
+            // HACK: To let the storybook run and render Windows caption icons. We should actually do better font fallback.
+            let allowed_bad_font_names = vec![
+                "SegoeFluentIcons", // NOTE: Segoe fluent icons postscript name is inconsistent
+                "Segoe Fluent Icons",
+            ];
```
Comment (zaucy) [inline crates/gpui/src/platform/common/text_system.rs:235]: this is my finding while running on my system with the pre installed segoe fluent icons on Windows

**Comment by zaucy** [comment]
NOTE: this fixes a panic that occurs on Windows when opening terminal.

File: crates/gpui/src/platform.rs [hunk 2]
```diff
@@ -6,6 +6,9 @@
 mod app_menu;
 mod keystroke;
 
+#[cfg(not(target_os = "macos"))]
+mod common;
```
Comment (zaucy) [inline crates/gpui/src/platform.rs:10]: I don't know if this is the best choice. I was considering adding a module called `cosmic_text` instead of 'common' and haing a `CosmicTextSystem` instead of `CommonTextSystem`. Thoughts?

```suggestion
#[cfg(not(target_os = "macos"))]
mod cosmic_text;
```

**Comment by zaucy** [comment]
some weird error in the CI that I believe isn't related to the contents of this PR 🤷

**Comment by maxdeviant** [comment]
> some weird error in the CI that I believe isn't related to the contents of this PR 🤷

Should be fixed on on `main`, if you want to merge that in to your branch.

**Comment by zaucy** [comment]
great! looks like it passed now :)

File: crates/gpui/src/platform/common/text_system.rs (hunk 1 above)
Comment (jansol) [reply crates/gpui/src/platform/common/text_system.rs]: This seems to be the case with a few others as well -- at least Intel One Mono comes to mind as one that is known to have used both "IntelOneMono" and "Intel One Mono". (IIRC they originally used the former and then fixed it to the latter in an update)

Maybe the code could just silently retry with all whitespace removed from the name? And potentially log a note if it finds the font with a different name. Maybe even show it as a hint when editing the config file.

Comment (maxdeviant) [reply crates/gpui/src/platform/common/text_system.rs]: > Maybe the code could just silently retry with all whitespace removed from the name? And potentially log a note if it finds the font with a different name. Maybe even show it as a hint when editing the config file.

I think explicitly enumerating the variants we want to try will be better, at least until we better understand the impact.

**Comment by zaucy** [comment]
anything more I need to do for this to be merged? Would be nice to have this in so I can run off `main` again :P

only conflict I see is #10119, but only a very minor change would have to be made on that side.

File: crates/gpui/src/platform/cosmic_text/text_system.rs [hunk 3]
```diff
@@ -210,9 +210,16 @@ impl CosmicTextSystemState {
     #[profiling::function]
     fn load_family(
         &mut self,
-        name: &SharedString,
+        name: &str,
         _features: FontFeatures,
     ) -> Result<SmallVec<[FontId; 4]>> {
+        // TODO: Determine the proper system UI font.
```
Comment (jansol) [inline crates/gpui/src/platform/cosmic_text/text_system.rs:216]: A lot of distros seem to converge on Noto Sans these days. Alternatively (if only fontconfig aliases got resolved properly) the abstract "sans-serif" family could be used to pick up whatever the user has configured in their fonts.conf. (which unfortunately is not in sync with what is configured in the GNOME/KDE appearance settings...)

Of course sticking with Zed Sans as a conscious style choice is always option.

Comment (zaucy) [reply crates/gpui/src/platform/cosmic_text/text_system.rs:216]: This PR simply renames the linux text system to the cosmic text system and uses it on both windows and linux.

This TODO is possibly not relevant unless you're worried about something negatively impacting the Windows usage?

Comment (jansol) [reply crates/gpui/src/platform/cosmic_text/text_system.rs:216]: Ah, true. I must've been looking at the old name. :+1:
