### PR TITLE
lsp: Fix workspace diagnostics lag & add streaming support

### LINKED ISSUE #33980: Workspace diagnostics cause zed to freeze for long time
### Summary

LSP workspace diagnostics is processed so that it can freeze Zed for long durations of time, in sufficiently large projects.

### Description

LSP workspace diagnostics is processed so that it can freeze Zed for long durations of time, in sufficiently large projects. This happens because the `DiagnosticsUpdated` event, emitted after the workspace diagnostics refresh task (spawned in `lsp_store::lsp_workspace_diagnostics_refresh`) refreshes diagnostics, leads to very expensive blocking operations in subscriptions inside `DiagnosticIndicator::new` and `ProjectPanel::new`.

Steps to reproduce:
1. Get the Luau extension
2. Open up a sufficiently large Luau project. You may get away with just making the language be Luau in an arbitrary large project. You can also use [Quenty/NevermoreEngine](https://github.com/Quenty/NevermoreEngine), and use the following project settings:

```json
{
  "file_types": {
    "Luau": ["lua"]
  },
  "lsp": {
    "luau-lsp": {
      "settings": {
        "luau-lsp": {
          "diagnostics": {
            "workspace": true
          }
        },
        "ext": {
          "binary": {
            "ignore_system_version": true
          }
        }
      }
    }
  }
}
```
(`ignore_system_version` is enabled to ensure the luau-lsp binary in `aftman.toml` and `foreman.toml` is not used)

**Expected Behavior**:

It takes a while for workspace diagnostics to be added in, but the editor does not slow down let alone freeze. Some kind of indicator that shows that workspace diagnostics are being loaded and maybe even how much has been loaded and how much there is to load would be ideal.

**Actual Behavior**:

The editor completely freezes for seconds when Luau diagnostics are sent from the language server, luau-lsp, which happens on startup and on every keystroke.

Even if Zed used partial result for it not to freeze on keystrokes (https://github.com/zed-industries/zed/discussions/33979), the initial workspace diagnostics sent from luau-lsp would be the size they are now. For this reason, partial result support is not enough and it's important that the work of going through the workspace diagnostic response is e.g. put in a separate thread or split into many smaller tasks.

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: macOS 15.5.0
Memory: 18 GiB
Architecture: aarch64

### PR DESCRIPTION
**Pull request by 4teapo**
Closes https://github.com/zed-industries/zed/issues/33980
Closes https://github.com/zed-industries/zed/discussions/33979

- Switches to the debounce task pattern for diagnostic summary computations, which most importantly lets us do them only once when a large number of DiagnosticUpdated events are received at once.
- Makes workspace diagnostic requests not time out if a partial result is received.
- Makes diagnostics from workspace diagnostic partial results get merged. 

There might be some related areas where we're not fully complying with the LSP spec but they may be outside the scope of what this PR should include.

Release Notes:

- Added support for streaming LSP workspace diagnostics.
- Fixed editor freeze from large LSP workspace diagnostic responses.

### CODE REVIEW

File: crates/diagnostics/src/items.rs [hunk 1]
```diff
@@ -134,7 +134,7 @@ impl DiagnosticIndicator {
                 cx.notify();
             }
 
-            project::Event::DiagnosticsUpdated { .. } => {
+            project::Event::DiagnosticsBatchUpdated => {
```
Comment (SomeoneToIgnore) [inline crates/diagnostics/src/items.rs]: I wonder if we could go away without adding another event and all complications related to accumulating a batch on the client side.

The usual pattern for this would be to do a 

```rs
self.task = cx.spawn(async move |this, cx| { 
    cx.background_executor().timer(Duration::from_millis(30)).await;
    ...
})
```

or, as an idea, can we extend the existing event to report multiple updates?

We always either accept a per-file diagnostics push, or per N files diagnostics pull result, so can know the list and do not need to batch anything?

File: crates/lsp/src/lsp.rs [hunk 2]
```diff
@@ -60,6 +61,39 @@ pub enum IoKind {
...
+}
+
+#[derive(Debug, PartialEq, Deserialize, Serialize, Clone)]
+#[serde(untagged)]
+pub enum ProgressParamsValue {
+    WorkDone(WorkDoneProgress),
+    WorkspaceDiagnostics(WorkspaceDiagnosticReportResult),
+}
+
+pub mod notification {
```
Comment (SomeoneToIgnore) [inline crates/lsp/src/lsp.rs]: Why https://github.com/zed-industries/zed/blob/c35af6c2e2225c055d106b394c346eea02de8996/crates/project/src/lsp_store.rs#L979-L996 is not enough?

We also need to fiddle with the local lsp store state to store a data about the token we expect the work progress reports for, see the code related to the same snippet linked.

File: crates/project/src/lsp_store/clangd_ext.rs [hunk 3]
```diff
@@ -91,6 +91,7 @@ pub fn register_notifications(
                         cx,
                     )
                     .log_err();
+                    cx.emit(LspStoreEvent::DiagnosticsBatchUpdated);
```
Comment (SomeoneToIgnore) [inline crates/project/src/lsp_store/clangd_ext.rs]: I've already mentioned a strive towards getting rid of this event, but wanted to highlight another point here: this is a plugin code, even though right now hardcoded: the fact that we have to send a custom event in the plugin code is bad and dangerous, as not every plugin writer may do that, causing odd state.
We have to solve this outside of the plugin code.

File: crates/lsp/src/lsp.rs (hunk 2 above)
Comment (SomeoneToIgnore) [reply crates/lsp/src/lsp.rs]: Took me a while: `ProgressParams` from the Zed's version does not have the diagnostics-related variant at all.
Let's solve this on a library level, to avoid further hardcodes in Zed itself.

File: crates/project/src/lsp_store.rs [hunk 4]
```diff
@@ -11434,72 +11534,11 @@ fn lsp_workspace_diagnostics_refresh(
...
-                                                        DiagnosticSourceKind::Other
-                                                        | DiagnosticSourceKind::Pushed => true,
-                                                    },
-                                                    cx,
-                                                )
-                                                .log_err();
-                                        }
-                                    }
-                                }
+                                lsp_store.apply_workspace_diagnostic_report(
```
Comment (SomeoneToIgnore) [inline crates/project/src/lsp_store.rs:11586]: It was sort of a surprise for me to discover that the workspace events will be used for this mode of updates, and the request does not really ever return.

Is it really what we can rely on? 
How far https://github.com/zed-industries/zed/discussions/33979#discussioncomment-13673498 ideas of mine about partial results returned here, over and over, until the final one — could that mode be supported by the server and if it could, we seem to need to preserve the token between invocations.

It would be very good if we could create a test for this.

File: crates/project/src/lsp_store.rs [hunk 5]
```diff
@@ -11407,14 +11500,21 @@ fn lsp_workspace_diagnostics_refresh(
                     return;
                 };
 
+                let token = Uuid::new_v4().to_string();
```
Comment (SomeoneToIgnore) [inline crates/project/src/lsp_store.rs]: There's no requirement for the token to be uuid, right?
Would a `format!("foo-bar-{usize_counter}")` form suffice? 
Seems to me that it would, which is great as no extra dependencies and extra algorithms are involved.

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you a lot for coming up with the investigation and the PR: the forever-hanging request was sort of a surprise to me, and I wonder, could we test it and handle a bit better, if my fantasies about the spec and partial responses make sense?

Also, let's take care of the types better and see if we can bump Zed's lsp types library instead of introducing a custom handler.

Secondly, it would be great to rework the new event approach a bit: either by postponing any git diff calculations with a debounce, in a task (those events do not need to be waited upon synchronously) or at least, by uniting the new event's idea into the previous one, so we explicitly take care of all event-related, existing places.

Overall, seems so good that the test might be the hardest part that's left.

File: crates/project/src/lsp_store.rs (hunk 4 above)
Comment (4teapo) [reply crates/project/src/lsp_store.rs:11586]: Spec says

> It is recommended for clients to implement partial result progress for the workspace pull to allow servers to keep the request open for a long time. If a server closes a workspace diagnostic pull request the client should re-trigger the request.

> Partial results are also reported using the generic [$/progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin) notification

and does not seem to allow the `workspace/diagnostic` request to return partial results directly, like its return type here in Rust would suggest. This type also has `#[serde(untagged)]` and its variants are structurally equivalent to each other, which I think means a partial result directly from `workspace/diagnostic` shouldn't be handled.

On another note, the server may still fail to respond to the request. I could make it get cancelled after the usual 2 minutes have passed unless it has received a progress notification. I initially left this out because I wasn't sure it's worth the complexity

Comment (SomeoneToIgnore) [reply crates/project/src/lsp_store.rs:11586]: I am a bit confused still as see no explicit description on what server can and can not do with both ways of sending the data back (via `$/progress` and via the workspace diagnostics pull responses).

I fully agree with the normal path, routed via `$/progress` and fine to keep it the only one covered if you think so.
What we miss here is a thing that makes it obvious that the distant bits connect: that's why a hope that we can write a test.

We could also move all functions/methods related to the disagnostics pull into a submodule within `lsp_store`, so it's more visible that the code is related.

Comment (SomeoneToIgnore) [reply crates/project/src/lsp_store.rs:11586]: > On another note, the server may still fail to respond to the request. I could make it get cancelled after the usual 2 minutes have passed unless it has received a progress notification. I initially left this out because I wasn't sure it's worth the complexity

Sounds interesting, but we do not need to restart anything until a next event (refresh or user modifications) kicks in.
Feels like the change touches the workspace diagnostics polling loop contents only, so is not that large to do?
I expect writing a new test would add much more into the final diff compared to this change.

File: crates/diagnostics/src/items.rs (hunk 1 above)
Comment (4teapo) [reply crates/diagnostics/src/items.rs]: I agree that the current way things work when it comes to the event. I think we could also get away with an infinite loop that each iteration waits 30 ms, checks if a DiagnosticsUpdated event has been received since the last iteration, and if so emits, say `DiagnosticsUpdated::Batch`.

We can also have something like
```rs
lsp_store.update_diagnostics(cx, |lsp_store, batch, cx| {
    lsp_store.merge_diagnostics(batch, ...);
})
```
which emits some modified DiagnosticsUpdated event that contains a `Vec` of updates after the closure has ran.

What do you think is the best way to go?

Comment (SomeoneToIgnore) [reply crates/diagnostics/src/items.rs]: I think it's a totally different direction.
What I want to fully avoid, is an extra state management, batch management and other extra knowledge related.

If we take a step back, our issue seems to be in the fact, that certain global entities like project panel and diagnostics indicator react on each file diagnostics update synchronously.
We send diagnostics updates per file, and might send a lot of updates at once now, causing those synchronous reactions to call something heavy enough to block things.

When looking at all `DiagnosticsUpdated` exact word usages, it seems surprisingly small:

image

Those are basically buffer sync mechanisms that bubble up, either caused by the buffer state sync mechanisms, or the diagnostics update - each happen per buffer.

What can we do, without introducing any extra "clever" state, to batch this?

1. We always know whether it's one file (due to diagnostics push or buffer state sync) or multiple, so can, in theory, pass some `send_event: bool` extra parameter somewhere on the `update_buffer_diagnostics` in the `LspStore`, and then send the same kind of "diagnostics updated" event from the lsp store level, after all diagnostics are applied.

We would need to change the project/lsp_store events to contain a `Vec<_>` of values, and introduce ~medium change to the codebase around the buffer sync.
Due to background remote buffer sync, the remote part will receive a lot of update messages anyway, but those will be passing through the wire, in a slower pace, causing less blocking.

2. We can do less work on such "diagnostics updated" events.

Due to the nature of our batches (born out of pull diagnostics), we do not get any frequent updates per single buffer, it's all different buffers.

So, reacting on such events in editors is still fine, and what's left are ~3 places where we recalculate things.
Some of these recaltulations happen per file path and seem to be ok to do, and pretty fast: it's the diagnostic summaries that usually cause issues it seems, and whatever else that got moved away into `DiagnosticsBatchUpdated` event handling branches.

Given that it's so few places that cause actual issues, we can do things fully asynchronously.
Inline diagnostics in the editor is a good example:

https://github.com/zed-industries/zed/blob/7432e947bc60204bc0f8fcfb13ab06f190369451/crates/editor/src/editor.rs#L16504-L16549

this code is called on any "diagnostics updated"-like call, fully traversing all diagnostics per file, and seem to work ok performance-wise.

This is achieved with a `inline_diagnostics_update: Task<()>` field in the `Editor`.
That field is initialized with `Task::ready(())` in the beginning and later, on each subsequent call, it creates another task that waits for a debounce (my 30ms proposed), then does all stateless, heavy operations in the `background_spawn`, off the main thread; regular state updates are available in the async task due to `cx.spawn_in(window, async move |editor, cx|`, outside the background spawn.

Using these primitives, we can always postpone the diagnostics summary calculation in the button and the project panel, and whatever remote or local source causing a flood of events, it is working ok, if we have a good debounce value?

-------------------------------

Neither options are great, but seem relatively small and bring no extra clever state and logic, really (that 2nd case is more like a pattern).

I lean towards the 2nd approach more, but happy with anything else that's matching the criteria.

File: crates/lsp/src/lsp.rs [hunk 6]
```diff
@@ -1126,13 +1127,36 @@ impl LanguageServer {
         )
     }
 
-    fn request_internal<T>(
+    /// Sends a RPC request to the language server, with a custom timer, a future which when becoming
+    /// ready causes the request to be timed out with the future's output message.
+    ///
+    /// [LSP Specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#requestMessage)
+    pub fn request_with_timer<T: request::Request, U: Future<Output = String> + Unpin>(
```
Comment (4teapo) [inline crates/lsp/src/lsp.rs]: We can also centralize timeout behavior by giving the workspace diagnostic request special treatment in here instead. What do you think we should do?

**Review by 4teapo — COMMENTED** [review]
Thanks for the great review! I've added a bit to editor tests, switched to the debounce task pattern, and some more, and I'm ready for round 2.

File: crates/lsp/src/lsp.rs (hunk 6 above)
Comment (SomeoneToIgnore) [reply crates/lsp/src/lsp.rs]: I think we're supposed to do more similar request in the future, e.g. there are workspace symbols request that might stream.

So, instead, we should keep it as is, ready for more timers to come?

File: crates/lsp/src/lsp.rs [hunk 7]
```diff
@@ -1126,13 +1127,36 @@ impl LanguageServer {
...
+            &self.next_id,
+            &self.response_handlers,
+            &self.outbound_tx,
+            &self.executor,
+            timer,
+            params,
+        )
+    }
+
+    fn request_internal_with_timer<T, U: Future<Output = String> + Unpin>(
```
Comment (SomeoneToIgnore) [inline crates/lsp/src/lsp.rs]: Here in all methods: we have `where`, let's not pollute the `<T, U>` block with any bounds, and move all into `where` clause.

File: crates/project/src/lsp_store.rs [hunk 8]
```diff
@@ -11379,7 +11464,7 @@ fn subscribe_to_binary_statuses(
 fn lsp_workspace_diagnostics_refresh(
     server: Arc<LanguageServer>,
     cx: &mut Context<'_, LspStore>,
-) -> Option<(mpsc::Sender<()>, Task<()>)> {
+) -> Option<(mpsc::Sender<()>, mpsc::Sender<()>, Task<()>)> {
```
Comment (SomeoneToIgnore) [inline crates/project/src/lsp_store.rs]: At this point, should we introduce a struct with named fields for all this?
It is not very clear what each channel is doing by looking at this.

File: crates/project/src/lsp_store.rs [hunk 9]
```diff
@@ -9130,67 +9133,77 @@ impl LspStore {
...
-        };
-
-        let language_server_status =
-            if let Some(status) = self.language_server_statuses.get_mut(&language_server_id) {
-                status
-            } else {
-                return;
-            };
+        match progress.value {
+            lsp::ProgressParamsValue::WorkDone(progress) => {
```
Comment (SomeoneToIgnore) [inline crates/project/src/lsp_store.rs:9137]: NIT: would be nice to extract this into another method too.

**Review by SomeoneToIgnore — COMMENTED** [review]
This looks really nice and not invasive at all.
I also see no blocks in the `NevermoreEngine` project.

Thank you for putting it up together: I've left some minor notes, but we're almost ready to merge overall.

File: crates/project/src/lsp_store.rs (hunk 8 above)
Comment (4teapo) [reply crates/project/src/lsp_store.rs]: Yeah I agree

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you a lot for taking care of all this, that was very revealing spec-wise.
