### PR TITLE
Fix project entry rename in Remote Development

### LINKED ISSUE #22883: client:unhandled ssh message name:UpdateProject
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I connect to a remote server via SSH, I encounter the following error message:
```
client: unhandled ssh message name: UpdateProject
```
This error appears consistently when I use zed to connect to the server. However, basic SSH commands (ssh user@host) seem to work fine.

### Zed Version and System Specs

Zed Preview 0.169.0

macOS 15.2 / Apple M1 Max

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by aborg-dev**
Closes #22883

To fix the problem, we move `handle_rename_project_entry` from `Worktree` to `LspStore` and register it there. This way it becomes available both in local and headless projects and this avoids the duplication.

Release Notes:

- Fixed renaming project entries in Remote Development

### CODE REVIEW

**Comment by aborg-dev** [comment]
Found a nice way to fix this: move `handle_rename_project_entry` to `LspStore`. This avoids the need to define it twice, as `LspStore` is tracked by Headless project already. I guess it also makes conceptual sense, given that LSP is involved in the rename?

I also noticed `rename_entry` implemented in `Project` that has pretty much the same code. I think that's an opportunity to move it to `LspStore` as well and call it from there to further remove duplication. I'll see if I can do it here or as separate PR.

Overall, I think this PR is ready for review. CC @osiewicz

File: crates/project/src/lsp_store.rs [hunk 1]
```diff
@@ -5920,6 +5921,52 @@ impl LspStore {
...
+            this.downgrade(),
+            worktree_id,
+            &old_abs_path,
+            &new_abs_path,
+            is_dir,
+            cx.clone(),
+        )
+        .await;
+        let response = Worktree::handle_rename_entry(worktree, envelope.payload, cx.clone()).await;
+        this.update(&mut cx, |this, _| {
```
Comment (aborg-dev) [inline crates/project/src/lsp_store.rs:5963]: Do I need this indirection through `update` or can I just directly call `this.did_rename_entry`?

**Comment by aborg-dev** [comment]
Added a test and verified that it passed on the PR but fails on the current `main` branch.
The error message is somewhat cryptic:

```
failures:
---- remote_editing_tests::test_remote_rename_entry stdout ----
thread 'remote_editing_tests::test_remote_rename_entry' panicked at crates/remote_server/src/remote_editing_tests.rs:1138:1:
parked with nothing left to run
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    remote_editing_tests::test_remote_rename_entry
```

Not sure how to improve it though, suggestions would be appreciated.

File: crates/project/src/lsp_store.rs (hunk 1 above)
Comment (osiewicz) [reply crates/project/src/lsp_store.rs:5963]: I'm pretty sure you need the indirection, as the types in both cases are different (`Model<LspStore>` vs `&mut LspStore`)

**Comment by osiewicz** [comment]
@aborg-dev this message basically means that there's an await in the test somewhere which never completes. I'm pretty sure this is good (though admittedly the error message is very cryptic).

**Comment by aborg-dev** [comment]
@osiewicz , got it, thanks!

Let's merge it as is and I'll look into improving the error message separately.

**Comment by osiewicz** [comment]
This message is used only in tests, so we may as well just explain what's going on verbatim. :)
