### PR TITLE
Fix duplicate prefixes when repeating completions in Vim mode

### LINKED ISSUE #30758: vim:repeat doesn't repeat completions well
### Summary

Repeating lsp completions in vim mode mangles the resulting text

### Description
example code:
```python
class MyClass:
    pass

a = 
b = 
```

Steps to reproduce:
1. configure `vim_mode: true`
2. in the line of `a = ` write `Myc`, and press enter to accept the MyClass suggestion
3. press esc to go back to normal mode
4. in the line of `b = ` go to the end of the line, press `.` (or vim: repeat),

Expected Behavior: I want to see `b = MyClass`
Actual Behavior: I see `b = MycMyClass`

Example video:
https://github.com/user-attachments/assets/2beb0334-9521-4a5a-8951-af9ff3686dea

### Zed Version and System Specs

Zed: v0.186.9 (Zed) 
OS: Linux Wayland ubuntu 24.10
Memory: 62.6 GiB
Architecture: x86_64
GPU: NVIDIA RTX A3000 Laptop GPU || NVIDIA || 570.133.07

### LINKED ISSUE #31759: Vim: Regression with edit repetition (.) after completions
### Summary

Repeating the edit action via `.` that contained completion results in completed text added *after* the completion prefix, duplicating it.

### Description

Here's a screencast of the reproduction in a new document:

[Screencast From 2025-05-29 22-08-02.webm](https://github.com/user-attachments/assets/8bf355c6-655f-4bc6-af34-6d46b6a2917e)

When typing `hello` again, I'm using the sequence `i` + `he` + `Tab` + `Esc`. After that, using `.` to repeat the action types `hehello`, as it repeats `he` and adds the completed text.

Expected behavior is that typing `.` should just insert `hello`.

I've bisected this to https://github.com/zed-industries/zed/pull/28586 - before that PR, the sequence above works as expected.

### Zed Version and System Specs

Zed: v0.188.4 (Zed) 
OS: Linux Wayland ubuntu 25.04
Memory: 183.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 5070 || NVIDIA || 570.133.07

### LINKED ISSUE #31779: [Vim] Repeating insert operation will include both the text you written and the full autocomplete text, leading to unwanted results
### Summary

With Vim mode, if you are in insert mode and you make a completion, then repeating the insert action with dot (`.`) will insert the text you typed and then the full autocomplete text. This leads to repeat actions that are almost always not what you want, and makes it annoying to repeat insertions generally since it's very common to use autocomplete in insert mode. 

### Description

Steps to reproduce:
1. Be in Vim mode
2. Enter insert mode, and start writing something that has autocomplete:
```
|  -- the cursor on a blank line
```
```
va|   -- autocomplete to `variableName`
```
```
variableName|
```
3. Exit insert mode, then use the repeat action

Expected Behavior:
```
variableNamevariableName|
```

Actual Behavior:
```
variableNamevavariableName|
```

Notice the extra `va` inserted in the front, since that is what I typed before accepting the completion.

### Zed Version and System Specs

Zed: v0.189.3 (Zed Preview) 
OS: Linux Wayland fedora 41
Memory: 62.6 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-S) || Intel open-source Mesa driver || Mesa 25.0.4

### PR DESCRIPTION
**Pull request by zeux**
When text is completed, new_text contains the entire new completion which replaces the old_text. In Vim mode, pressing . repeats the completion; if InputHandled records the full text and no range to replace, the entire completion gets appended; this happens after the completion prefix typing repeats, and we get a duplicate prefix.

Using range to replace has some downsides when the completion is repeated as a standalone action; in a common case, it should be sufficient to record the new suffix. This is actually what used to happen before #28586, which removed this code in a larger attempt to fix completions at multiple cursors:

```rust
let text = &new_text[common_prefix_len..];
let utf16_range_to_replace = ...

cx.emit(EditorEvent::InputHandled {
    utf16_range_to_replace,
    text: text.into(),
});
```

Fixes #30758
Fixes #31759
Fixes #31779

Release Notes:

- Vim: Fix duplicate prefixes when repeating completions via `.`

### CODE REVIEW

**Review by marcospb19 — APPROVED** [review]

**Comment by Peiffap** [comment]
This does the same thing and looks cleaner (imo!) :)
```rust
cx.emit(EditorEvent::InputHandled {
    utf16_range_to_replace: None,
    text: new_text[old_text.chars()
        .zip(new_text.chars())
        .take_while(|(a, b)| a == b)
        .map(|(a, _)| a.len_utf8())
        .sum::<usize>()..]
        .into(),
});
```

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -5475,9 +5475,18 @@ impl Editor {
...
 
+        let mut common_prefix_len = 0;
+        for (a, b) in old_text.chars().zip(new_text.chars()) {
+            if a == b {
+                common_prefix_len += a.len_utf8();
+            } else {
+                break;
+            }
+        }
+
```
Comment (Peiffap) [inline crates/editor/src/editor.rs:5486]: This does the same thing, but cleaner (imo!)
Edit: removed wrong suggestion, see below.

Comment (marcospb19) [reply crates/editor/src/editor.rs:5486]: code in red is exactly as it was before https://github.com/zed-industries/zed/pull/28586

but more importantly, you did .as_bytes() + count(), which is slightly different then that += with a.len_utf8()

the exact equivalent: 

```suggestion
        let common_prefix_len = old_text
            .chars()
            .iter()
            .zip(new_text.chars())
            .take_while(|(a, b)| a == b)
            .map(|(a, _)| a.len_utf8())
            .sum::<usize>();
```

I think

And that's not to avoid non-utf8, cause it can't happen here, but to avoid wider characters that match partially

Comment (Peiffap) [reply crates/editor/src/editor.rs:5486]: You're right, good catch! I've removed my suggestion to avoid mistakes. I still like your suggestion more than the explicit loop, fwiw!

Comment (zeux) [reply crates/editor/src/editor.rs:5486]: Yeah for posterity, the loop in this PR is simply taken from the original code in this file.

**Comment by ConradIrwin** [comment]
Nice, thanks!
