### PR TITLE
extensions: Pass protobuf-language-server settings and initialization_options to the LSP

### LINKED ISSUE #43786: protobuf-language-server settings and initialization_options not passed to the lsp
### Reproduction steps

1. Start zed
2. Configure `protobuf-language-server` to for example add `additional-proto-dirs` setting
3. Create a .proto file that depends on the `additional-proto-dirs`

### Current vs. Expected behavior

Current behavior: The lsp does not recognize the `additional-proto-dirs` or other settings
Expected behavior: The lsp should recognize the `additional-proto-dirs` and other settings

### Zed version and system specs

Zed: v0.214.6 (Zed) 
OS: Windows 10.0.22631
Memory: 15.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA Corporation || 581.63 r580_00

### Attach Zed log file

_No response_

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
  "lsp": {
    "protobuf-language-server": {
      "settings": {
        "additional-proto-dirs": [
          "~/proto-test/proto/"
        ]
      }
    }
  }
```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by dajooo**
pass protobuf-language-server settings and initialization_options to the protobuf-language-server

Closes #43786

Release Notes:

- N/A

### CODE REVIEW

**Comment by dajooo** [comment]
@cla-bot check

File: extensions/proto/src/proto.rs [hunk 1]
```diff
@@ -59,6 +59,30 @@ impl zed::Extension for ProtobufExtension {
...
+
+    fn language_server_workspace_configuration(
+        &mut self,
+        server_id: &zed::LanguageServerId,
+        worktree: &zed::Worktree,
+    ) -> Result<Option<zed::serde_json::Value>> {
+        let settings = LspSettings::for_worktree(server_id.as_ref(), worktree)
+            .ok()
+            .and_then(|lsp_settings| lsp_settings.settings)
+            .unwrap_or_default();
```
Comment (SomeoneToIgnore) [inline extensions/proto/src/proto.rs]: Any reason here and below, to do `.unwrap_or_default()` and then return `Some` of it value?
Why not return `None`?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you for noticing, it seems that almost no one configures this server to notice this.

File: extensions/proto/src/proto.rs (hunk 1 above)
Comment (dajooo) [reply extensions/proto/src/proto.rs]: To be honest, I just copied this from the html extension 😅
But you are absolutely right to point that out, I just changed it

**Review by SomeoneToIgnore — APPROVED** [review]

File: extensions/proto/src/proto.rs (hunk 1 above)
Comment (SomeoneToIgnore) [reply extensions/proto/src/proto.rs]: Yeah, that does not seem too useful to do that there too 🙂 
Thank you!
