### PR TITLE
rust: Add runnable icon for `#[cfg(test)] mod tests`

### LINKED ISSUE #11967: task missing play buttons for main & cfg(test)
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

there is an icon to run the task for a single test, but not for main & all tasks

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot 2024-05-17 at 12 16 56

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by RemcoSmitsDev**
This allows you to run all the tests inside the `mod tests` block. 
Fixes #11967.

Screenshot 2024-05-18 at 16 07 32

Screenshot 2024-05-18 at 16 37 21

Release Notes:

- Added runnable icon for Rust `#[cfg(test)] mod tests` blocks ([#11967](https://github.com/zed-industries/zed/issues/11967)).

### CODE REVIEW

File: crates/language/src/task_context.rs [hunk 1]
```diff
@@ -90,8 +90,13 @@ impl ContextProvider for BasicContextProvider {
             task_variables.insert(VariableName::SelectedText, selected_text);
         }
         if let Some(path) = current_file {
-            task_variables.insert(VariableName::File, path);
+            task_variables.insert(VariableName::File, path.clone());
+
+            if let Some(file) = Path::new(&path).file_stem().and_then(|f| f.to_str()) {
+                task_variables.insert(VariableName::Filename, String::from(file));
```
Comment (osiewicz) [inline crates/language/src/task_context.rs:96]: I think this is a bit confusing, as it's just the stem portion of the file, without an extension. I'd either change the name of the variable or (preferably) have it include the full name of the file with extension.

File: crates/languages/src/rust.rs [hunk 2]
```diff
@@ -389,6 +389,22 @@ impl ContextProvider for RustContextProvider {
...
+                    VariableName::Filename.template_value(),
+                ),
+                command: "cargo".into(),
+                args: vec![
+                    "test".into(),
+                    "-p".into(),
+                    RUST_PACKAGE_TASK_VARIABLE.template_value(),
+                    VariableName::Filename.template_value(),
+                ],
+                tags: vec!["rust-file-test".to_owned()],
```
Comment (osiewicz) [inline crates/languages/src/rust.rs:405]: Can we use a different tag than `rust-file-test`? I want to introduce a tag for testing whole file if we detect at least one test in it and I guess I'd like to use a tag similar to the one you have there.
I wonder if we could even perhaps use `rust-test` again there.

File: crates/language/src/task_context.rs (hunk 1 above)
Comment (RemcoSmitsDev) [reply crates/language/src/task_context.rs:96]: I will change the name of the `VariableName::Filename` to `VariableName::Stem` because the rust test CLI command seems not to work if you include the extension.

File: crates/languages/src/rust.rs (hunk 2 above)
Comment (RemcoSmitsDev) [reply crates/languages/src/rust.rs:405]: Unfortunately, we cannot reuse the `rust-test` tag because it will run the wrong task.
Screenshot 2024-05-18 at 18 43 24

File: crates/language/src/task_context.rs (hunk 1 above)
Comment (osiewicz) [reply crates/language/src/task_context.rs]: That works; an alternative (that's admittedly a bit ugly) is that we could have it be the filename and process the filename to get rid of the extension before invoking cargo (as a part of a task). I don't think that's too bad honestly.

Comment (RemcoSmitsDev) [reply crates/language/src/task_context.rs]: Yeah, sounds good. But the only thing I don't like is that if more task gonna need this, they are going to do the same job on each task. Instead, we are doing it once when building the context. 

But if you think like, we give you the filename and if you only want/need the `stem` than just parse it yourself. So we keep it more general.

File: crates/languages/src/rust.rs (hunk 2 above)
Comment (osiewicz) [reply crates/languages/src/rust.rs:405]: Oh, right; you're totally right.

File: crates/language/src/task_context.rs (hunk 1 above)
Comment (osiewicz) [reply crates/language/src/task_context.rs]: Yep, that sounds good to me; let's have both

File: docs/src/tasks.md [hunk 3]
```diff
@@ -43,7 +43,9 @@ These variables allow you to pull information from the current editor and use it
 
 - `ZED_COLUMN`: current line column
 - `ZED_ROW`: current line row
-- `ZED_FILE`: absolute path to the file
+- `ZED_FILE`: absolute path of the currently opened file
+- `ZED_FILENAME`: filename of the currently opened file
+- `ZED_STEM`: stem (filename without extension) of the currently opened file
```
Comment (mrnugget) [inline docs/src/tasks.md:48]: Nitpick: I think example values here would help a lot

Comment (RemcoSmitsDev) [reply docs/src/tasks.md:48]: Yeah I agree, will add them!

File: docs/src/tasks.md [hunk 4]
```diff
@@ -43,10 +43,12 @@ These variables allow you to pull information from the current editor and use it
 
 - `ZED_COLUMN`: current line column
 - `ZED_ROW`: current line row
-- `ZED_FILE`: absolute path to the file
+- `ZED_FILE`: absolute path of the currently opened file (e.g. `~/path/to/project/src/main.rs`)
```
Comment (mrnugget) [inline docs/src/tasks.md:46]: That's not an absolute path though, right? 😄 
```suggestion
- `ZED_FILE`: absolute path of the currently opened file (e.g. `/Users/my-user/path/to/project/src/main.rs`)
```

**Review by mrnugget — COMMENTED** [review]
One more comment! Rest also looks fine to me, but I'll defer to @osiewicz

File: docs/src/tasks.md (hunk 4 above)
Comment (RemcoSmitsDev) [reply docs/src/tasks.md:46]: Oops😄 Your right!

Comment (RemcoSmitsDev) [reply docs/src/tasks.md]: I fixed both wrong absolute paths

**Review by mrnugget — APPROVED** [review]

File: crates/languages/src/rust/runnables.scm [hunk 5]
```diff
@@ -1,3 +1,23 @@
...
+            (#eq? @_attribute "cfg")
+
+            arguments: (token_tree (
+                (identifier) @_argument
+                (#eq? @_argument "test")
+            ))
+        )
+    )
+    .
+    (attribute_item) *
```
Comment (osiewicz) [inline crates/languages/src/rust/runnables.scm:13]: I think we can be a bit more lenient here; We don't need to check for attributes, as it may be too restrictive at times (e.g. this query does not match with `#[cfg(any(test))]` etc).

Comment (RemcoSmitsDev) [reply crates/languages/src/rust/runnables.scm:13]: Do you want to just match on the `tests` identifier? So just this:
```scm
(mod_item
    name: (_) @run
    (#eq? @run "tests")
) @rust-file-test
```

Comment (RemcoSmitsDev) [reply crates/languages/src/rust/runnables.scm:13]: We can maybe call it `rust-mod-test` instead?

Comment (osiewicz) [reply crates/languages/src/rust/runnables.scm:13]: Yup, exactly. A shorter query and rust-mod-test should suffice.

**Review by osiewicz — APPROVED** [review]
LGTM! There's a conflict that prevents the merge, but once that's out of the way I think we'll be good to merge
