### PR TITLE
Fall back to stdout if log file is inaccessible

### LINKED ISSUE #8209: If create/access `~/Library/Logs/Zed/Zed.log` failed, Zed can't be launched.
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

Zed app launch need `~/Library/Logs/Zed/Zed.log` file to be created, is it necessary?
If some system disable log writing, you can't create/write log files to specific folder.

1. Zed app launch shouldn't crash if log file can't be created or accessed.
2. Zed.log file should set as an logging option NOT a requirement.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

### PR DESCRIPTION
**Pull request by dheeraj-coding**
Release Notes:

Fixes #8209. Defaults to env logger in case of open/access failure. 
- OpenLog action shows a nice toast notification to user that indicates access/open failure.

Screenrecording:

https://github.com/zed-industries/zed/assets/31967125/644f3524-e680-457c-bf4c-a7f11f3ec8db

### CODE REVIEW

File: crates/zed/src/zed.rs [hunk 1]
```diff
@@ -477,42 +477,54 @@ fn open_log_file(workspace: &mut Workspace, cx: &mut ViewContext<Workspace>) {
...
-                            .expect("creating buffers on a local workspace always succeeds");
-                        buffer.update(cx, |buffer, cx| buffer.edit([(0..0, log)], None, cx));
-
-                        let buffer = cx.new_model(|cx| {
-                            MultiBuffer::singleton(buffer, cx).with_title("Log".into())
-                        });
-                        workspace.add_item(
-                            Box::new(
-                                cx.new_view(|cx| {
+                        if let Some(log) = log {
```
Comment (maxdeviant) [inline crates/zed/src/zed.rs:505]: I think a `let` / `else` here would be better to avoid having to indent the happy path:

```rs
let Some(log) = log else {
    workspace.show_notification(1, cx, |cx| {
        cx.new_view(|_| {
            MessageNotification::new("Unable to access/open log file.")
        })
    });
    return;
}
```

We also need to give the notification a more unique ID to avoid any potential overlap.

Comment (dheeraj-coding) [reply crates/zed/src/zed.rs:505]: is it a random generated number? or is there a table I could use?

File: crates/zed/src/main.rs [hunk 2]
```diff
@@ -521,19 +498,54 @@ fn init_logger() {
...
+                simplelog::WriteLogger::init(level, config, log_file)
+                    .expect("could not initialize logger");
+            }
+            Err(_) => {
+                // Silently defaulting to use stdout logger in case of any error.
+                init_stdout_logger();
+            }
+        }
     }
+    log::debug!("testing debug");
```
Comment (maxdeviant) [inline crates/zed/src/main.rs:521]: We should remove this line prior to merge.

File: crates/zed/src/zed.rs (hunk 1 above)
Comment (maxdeviant) [reply crates/zed/src/zed.rs:505]: Right now we're just randomly assigning integers.

File: crates/zed/src/main.rs (hunk 2 above)
Comment (dheeraj-coding) [reply crates/zed/src/main.rs]: This was already there but I have removed it.

File: crates/zed/src/zed.rs (hunk 1 above)
Comment (dheeraj-coding) [reply crates/zed/src/zed.rs]: Reassigned integer and used let/else for better readability.

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, left a few small notes but looks good in general.

File: crates/zed/src/zed.rs [hunk 3]
```diff
@@ -477,25 +477,39 @@ fn open_log_file(workspace: &mut Workspace, cx: &mut ViewContext<Workspace>) {
...
-                    .flat_map(|line| [line, "\n"])
-                    .collect::<String>();
+                };
 
                 workspace
                     .update(&mut cx, |workspace, cx| {
+                        let Some(log) = log else {
+                            workspace.show_notification(29, cx, |cx| {
+                                cx.new_view(|_| {
+                                    MessageNotification::new("Unable to access/open log file.")
```
[the remark this answers is not in the document]
Comment (dheeraj-coding) [reply crates/zed/src/zed.rs]: added the path in notification.

File: crates/zed/src/main.rs [hunk 4]
```diff
@@ -521,21 +498,55 @@ fn init_logger() {
...
+                let config = ConfigBuilder::new()
+                    .set_time_format_str("%Y-%m-%dT%T%:z")
+                    .set_time_to_local(true)
+                    .build();
+
+                simplelog::WriteLogger::init(level, config, log_file)
+                    .expect("could not initialize logger");
+            }
+            Err(_) => {
+                // Silently defaulting to use stdout logger in case of any error.
```
[the remark this answers is not in the document]
Comment (dheeraj-coding) [reply crates/zed/src/main.rs]: I agree. I have added the log::error with error msg.

File: crates/zed/src/main.rs [hunk 5]
```diff
@@ -521,21 +498,55 @@ fn init_logger() {
...
 
+fn init_stdout_logger() {
+    Builder::new()
+        .parse_default_env()
+        .format(|buf, record| {
+            use env_logger::fmt::Color;
+
+            let subtle = buf
+                .style()
+                .set_color(Color::White)
```
[the remark this answers is not in the document]
Comment (dheeraj-coding) [reply crates/zed/src/main.rs]: That was a mistake. I was just testing and accidentally committed it. Reverted it.

File: crates/zed/src/zed.rs [hunk 6]
```diff
@@ -477,25 +477,42 @@ fn open_log_file(workspace: &mut Workspace, cx: &mut ViewContext<Workspace>) {
...
-                    .collect::<String>();
+                };
 
                 workspace
                     .update(&mut cx, |workspace, cx| {
+                        let Some(log) = log else {
+                            workspace.show_notification(29, cx, |cx| {
+                                cx.new_view(|_| {
+                                    MessageNotification::new(format!(
+                                        "Unable to access/open log file. \n Log Path: {}",
```
Comment (SomeoneToIgnore) [inline crates/zed/src/zed.rs:509]:
```suggestion
                                        "Unable to access/open log file at path {:?}",
```

File: crates/zed/src/zed.rs [hunk 7]
```diff
@@ -477,25 +477,42 @@ fn open_log_file(workspace: &mut Workspace, cx: &mut ViewContext<Workspace>) {
...
+                                        &paths::LOG.to_string_lossy()
```
Comment (SomeoneToIgnore) [inline crates/zed/src/zed.rs:510]:
```suggestion
                                        &paths::LOG
```

File: crates/zed/src/main.rs [hunk 8]
```diff
@@ -521,21 +498,58 @@ fn init_logger() {
...
+                    .set_time_to_local(true)
+                    .build();
+
+                simplelog::WriteLogger::init(level, config, log_file)
+                    .expect("could not initialize logger");
+            }
+            Err(err) => {
+                init_stdout_logger();
+                log::error!(
+                    "could not open log file: {}. defaulting to stdout logging.",
```
Comment (SomeoneToIgnore) [inline crates/zed/src/main.rs:518]:
```suggestion
                    "could not open log file, defaulting to stdout logging: {}",
```

**Review by SomeoneToIgnore — APPROVED** [review]
Great, pushed some wording nits, let's see if I can commit then via GH UI.

File: crates/zed/src/zed.rs [hunk 9]
```diff
@@ -477,25 +477,42 @@ fn open_log_file(workspace: &mut Workspace, cx: &mut ViewContext<Workspace>) {
...
+                };
 
                 workspace
                     .update(&mut cx, |workspace, cx| {
+                        let Some(log) = log else {
+                            workspace.show_notification(29, cx, |cx| {
+                                cx.new_view(|_| {
+                                    MessageNotification::new(format!(
+                                        "Unable to access/open log file at path {:?}",
+                                        &paths::LOG
```
Comment (SomeoneToIgnore) [inline crates/zed/src/zed.rs:510]:
```suggestion
                                        paths::LOG.as_path()
```
