### PR TITLE
editor: Limit `CopyHighlightJson` to selection

### LINKED ISSUE #36618: Hightlighting text to copy into the Linux primary clipboard truncates or includes too many characters
### Summary

When I drag highlight text in Zed to copy text into my Primary clipboard it cuts off text or adds too much text in the primary clipboard buffer.

### Description

Steps to reproduce:
1. Use Linux with Wayland (not sure if it happens on X11) 
2. Hightlight some text to copy it into the primary clipboard
3. Observe the text selects more or less than what was highlighted in your Primary clipboard.

**Expected Behavior**:

The exact text that I highlight goes into the primary clipboard.

**Actual Behavior**:

I highlighted this line left to right drag:
Image

It cut off the highlighted texxt on the first try and on the second it grabbed too much: 
Image

Double click clicking to highlight or using olde trusty highlight text and  `ctrl + c` works as expected.

Maybe this is related to previous primary clipboard issues? https://github.com/zed-industries/zed/issues/14362

### Zed Version and System Specs

Zed: v0.199.10 (Zed) 
OS: Linux Wayland fedora 42
Memory: 251.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 5090 || NVIDIA || 575.64.05

### PR DESCRIPTION
**Pull request by ian-h-chamberlain**
Closes https://github.com/zed-industries/zed/issues/36618

I'm not sure if there is a specific issue for this, but I noticed it while working on some other PRs, as have some other people: https://github.com/zed-industries/zed/issues/20525#issuecomment-2469507157

Cause: when running `copy highlight JSON` from the command palette, input was disabled due to the modal, and the selection method call always returns `None`. This most likely works as expected when bound to a keyboard shortcut, but since there is no default shortcut most people probably don't execute this action that way.

Fix: just grab the selection directly; I don't think this command needs to be IME-aware, so it doesn't need to use `selected_text_range`.

NOTE: There still seems to be an issue where `VISUAL LINE` mode doesn't select anything, even when I called `selections.newest_adjusted`, so I opted to try and keep the implementation closest to what it was doing before. (edit: actually this might just be the same as #45799?).

Release Notes:

- Fixed `editor: copy highlight JSON` not limiting to the current selection

### CODE REVIEW

**Comment by ian-h-chamberlain** [comment]
> Passing by and noticing that this lacks any testing at all which most probably does not help to get this reviewed.

Good point, it took me a while to figure out the best way to write tests against this feature but I think what I've got now should help!

File: crates/editor/src/editor.rs [hunk 1]
```diff
@@ -25025,23 +25025,23 @@ impl Editor {
...
-            .unwrap_or_else(|| MultiBufferOffset(0)..snapshot.len());
+        let mut selection = self.selections.newest::<Point>(&self.display_snapshot(cx));
+        let max_point = snapshot.max_point();
+
+        let range = if selection.is_empty() {
+            Point::new(0, 0)..max_point
+        } else if self.selections.line_mode() {
+            selection.start = Point::new(selection.start.row, 0);
+            if !selection.is_empty() && selection.end.column == 0 {
+                selection.end = cmp::min(max_point, selection.end);
```
Comment (SomeoneToIgnore) [inline crates/editor/src/editor.rs]: That `selection.end` confuses me: if I understand correctly, `line_mode` forces the selection of entire only, but here for a non-empty selection on the same line, haven't we just set the start column to 0 with `selection.start = Point::new(selection.start.row, 0);` and set the end column to zero too with this line?

Presumably, adding a test with the selections on a single line could help exposing the issue?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, looks really nice overall, one small thing to clear and we're ready to merge.

File: crates/editor/src/editor.rs (hunk 1 above)
Comment (ian-h-chamberlain) [reply crates/editor/src/editor.rs]: Good callout, I wrote this a while back and I think my understanding at the time was slightly mistaken. 

I made the original change in response to a quirk of Vim mode (and `vim` itself), which I think is actually working as intended: <kbd>V $</kbd> selects the line, then moves the cursor *past* the end of the line, which results in two lines' highlights being copied. `editor: copy` has the same behavior, so I think there's no need to do anything different here.

I simplified the logic a bit and added another test for "no selection" in line-selection mode (where one line should be copied). Thanks for reviewing closely!

**Review by SomeoneToIgnore — APPROVED** [review]
Nice, thank you for the simplification!
