### PR TITLE
Fix folder expand when dropped on itself in project_panel

### LINKED ISSUE #13093: Folder change to expanded state after drag drop in File explorer
### Check for existing issues

- [X] Completed

### Expected behavior

Drag drop a folder shouldn't change it state.

### Actual behavior

After drag drop folder in File Explorer, it change state to expanded but doesn't show the content.
I can drag drop another folder and it become expanded too.
Click on the last expanded folder, it change to closed state while other folders are expanded. You can see in the attached video, when I click on the playground folder, it change to closed state and the other 3 folders are expanded.

https://github.com/zed-industries/zed/assets/1020347/a01c977d-bf3c-4c40-963a-90c0f21b8d98

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by matubu**
Closes #13093

Release Notes:

- Fixed folder expand when dropped on itself in project_panel

### CODE REVIEW

File: crates/project_panel/src/project_panel.rs [hunk 1]
```diff
@@ -1546,6 +1546,11 @@ impl ProjectPanel {
         destination_is_file: bool,
         cx: &mut ViewContext<Self>,
     ) {
+        // dropping on itself, fix #13093
```
Comment (osiewicz) [inline crates/project_panel/src/project_panel.rs:1549]: I don't think we need this comment, there's always `git blame` that we can use.
```suggestion
```

**Review by osiewicz — CHANGES_REQUESTED** [review]
LGTM sans that comment. =)

File: crates/project_panel/src/project_panel.rs (hunk 1 above)
Comment (matubu) [reply crates/project_panel/src/project_panel.rs]: Makes sense, I removed the comment.
