### PR TITLE
Fix `OpenFiles` action not respecting `use_system_path_prompts` setting

### LINKED ISSUE #46386: Setting: "use_system_path_prompts"  is ignored
### Reproduction steps

Try to open a file with the keybind "workspace: open files" while having the settings "**use_system_path_prompts**" set to **false**

The issue was not present yesterday (I was using the version 0.217.x, I don't remember the minor)

### Current vs. Expected behavior

Current: Open the system prompts
Expected: Open the integrated to zed prompt

### Zed version and system specs

Zed: v0.218.6+stable (Zed) 
OS: Linux Wayland endeavouros unknown
Memory: 30.5 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6700 XT (RADV NAVI22) || radv || Mesa 25.3.3-arch1.1

### Attach Zed log file

<details><summary>Zed.log</summary>

```log
2026-01-08T18:55:41+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 20
}
2026-01-08T18:55:42+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 15
}
2026-01-08T18:55:42+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 19
}
2026-01-08T18:56:25+01:00 INFO  [project::prettier_store] Starting prettier at path "/home/thomas/.local/share/zed/prettier"
2026-01-08T18:56:25+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/.local/share/zed/prettier", args: ["/home/thomas/.local/share/zed/prettier/prettier_server.js", "/home/thomas/.local/share/zed/prettier"]
2026-01-08T18:56:25+01:00 INFO  [project::prettier_store] Started default prettier in "/home/thomas/.local/share/zed/prettier"
2026-01-08T18:56:25+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:56:25+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 33
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 54
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 58
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 46
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 59
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 72
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 77
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 88
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 82
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 30
}
2026-01-08T18:56:25+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 18
}
2026-01-08T18:56:32+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T18:56:32+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T18:56:37+01:00 INFO  [project::lsp_store] stopping language server json-language-server
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 34
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 46
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 57
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 59
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 67
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 103
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 109
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 119
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 101
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 33
}
2026-01-08T18:56:37+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 20
}
2026-01-08T18:56:41+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T18:56:41+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T18:56:52+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:56:52+01:00 INFO  [project::lsp_store] stopping language server package-version-server
2026-01-08T18:56:52+01:00 ERROR [lsp] Shutdown request failure, server package-version-server (id 2): Unexpected params: null
2026-01-08T18:56:53+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 22
}
2026-01-08T18:56:53+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 7
}
2026-01-08T18:56:53+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T18:56:53+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 32
}
2026-01-08T18:56:58+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:56:59+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:56:59+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 18
}
2026-01-08T18:56:59+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 6
}
2026-01-08T18:56:59+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 22
}
2026-01-08T18:56:59+01:00 INFO  [lsp] Language server with id 5 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T18:57:02+01:00 WARN  [lsp::input_handler] failed to deserialize LSP message:
{"jsonrpc":"2.0","result":{}}
2026-01-08T18:57:02+01:00 ERROR [lsp] Shutdown request failure, server prettier (id 7): Error: Unknown method: shutdown
While handling prettier request: {"jsonrpc":"2.0","id":4,"method":"shutdown","params":null}
2026-01-08T18:57:03+01:00 INFO  [zed] ========== starting zed version 0.218.6+stable, sha unknown ==========
2026-01-08T18:57:03+01:00 INFO  [crashes] spawning crash handler process
2026-01-08T18:57:03+01:00 WARN  [zed::reliability] Minidump endpoint not set
2026-01-08T18:57:03+01:00 INFO  [extension_host] extensions updated. loading 14, reloading 0, unloading 0
2026-01-08T18:57:03+01:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2026-01-08T18:57:03+01:00 INFO  [util] set environment variables from shell:/usr/bin/zsh, path:/home/thomas/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/thomas/.local/bin:/usr/lib/emscripten:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/usr/lib/rustup/bin:/usr/lib/emscripten:/home/thomas/.local/bin:/usr/lib/emscripten
2026-01-08T18:57:03+01:00 ERROR [crates/client/src/client.rs:357] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
2026-01-08T18:57:03+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T18:57:03+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T18:57:03+01:00 INFO  [workspace] Rendered first frame
2026-01-08T18:57:03+01:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon RX 6700 XT (RADV NAVI22)", driver_name: "radv", driver_info: "Mesa 25.3.3-arch1.1" }
2026-01-08T18:57:03+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:57:03+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:57:03+01:00 INFO  [crashes] connected to crash handler process after 100ms
2026-01-08T18:57:03+01:00 INFO  [crashes] crash handler registered
2026-01-08T18:57:04+01:00 INFO  [node_runtime] using Node.js found on PATH: SystemNodeRuntime { node: "/usr/bin/node", npm: "/usr/bin/npm", global_node_modules: "/usr/lib/node_modules\n", scratch_dir: "/home/thomas/.local/share/zed/node" }
2026-01-08T18:57:04+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["--max-old-space-size=8192", "/home/thomas/.local/share/zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2026-01-08T18:57:04+01:00 INFO  [lsp] starting language server process. binary path: "/home/thomas/.local/share/zed/languages/package-version-server/package-version-server-v0.0.10", working directory: "/home/thomas/Projects/RolePlay/atoria", args: []
2026-01-08T18:57:04+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T18:57:04+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/.config/zed", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T18:57:04+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 410
}
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 455
}
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 61
}
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 19
}
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 37
}
2026-01-08T18:57:04+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 57
}
2026-01-08T18:57:05+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2026-01-08T18:57:10+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T18:57:10+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T18:57:14+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 37
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 54
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 35
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 42
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 50
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 64
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 83
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 97
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 107
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 119
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 108
}
2026-01-08T18:57:14+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 13
}
2026-01-08T18:57:19+01:00 INFO  [project::prettier_store] Starting prettier at path "/home/thomas/.local/share/zed/prettier"
2026-01-08T18:57:19+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/.local/share/zed/prettier", args: ["/home/thomas/.local/share/zed/prettier/prettier_server.js", "/home/thomas/.local/share/zed/prettier"]
2026-01-08T18:57:19+01:00 INFO  [project::prettier_store] Started default prettier in "/home/thomas/.local/share/zed/prettier"
2026-01-08T18:57:19+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:57:19+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:57:19+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 26
}
2026-01-08T18:57:19+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 43
}
2026-01-08T18:57:19+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 50
}
2026-01-08T18:57:19+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 32
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 26
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 46
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 63
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 73
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 79
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 92
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 6
}
2026-01-08T18:57:20+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 16
}
2026-01-08T18:58:05+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:05+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 35
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 56
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 64
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 52
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 57
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 33
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 49
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 63
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 69
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 79
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 64
}
2026-01-08T18:58:05+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 23
}
2026-01-08T18:58:07+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:07+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 30
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 51
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 55
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 47
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 26
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 37
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 61
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 74
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 79
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 77
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 5
}
2026-01-08T18:58:07+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 17
}
2026-01-08T18:58:13+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:13+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 57
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 64
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 57
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 26
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 37
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 51
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 66
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 71
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 66
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 16
}
2026-01-08T18:58:13+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 21
}
2026-01-08T19:01:30+01:00 ERROR [lsp] Shutdown request failure, server package-version-server (id 3): Unexpected params: null
2026-01-08T19:01:30+01:00 WARN  [lsp::input_handler] failed to deserialize LSP message:
{"jsonrpc":"2.0","result":{}}
2026-01-08T19:01:30+01:00 ERROR [lsp] Shutdown request failure, server prettier (id 7): Error: Unknown method: shutdown
While handling prettier request: {"jsonrpc":"2.0","id":6,"method":"shutdown","params":null}
2026-01-08T19:01:33+01:00 INFO  [zed] ========== starting zed version 0.218.6+stable, sha unknown ==========
2026-01-08T19:01:33+01:00 INFO  [crashes] spawning crash handler process
2026-01-08T19:01:33+01:00 WARN  [zed::reliability] Minidump endpoint not set
2026-01-08T19:01:33+01:00 INFO  [extension_host] extensions updated. loading 14, reloading 0, unloading 0
2026-01-08T19:01:33+01:00 INFO  [util] set environment variables from shell:/usr/bin/zsh, path:/home/thomas/.cargo/bin:/home/thomas/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/thomas/.local/bin:/usr/lib/emscripten:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/usr/lib/rustup/bin:/usr/lib/emscripten:/home/thomas/.local/bin:/home/thomas/.local/bin:/usr/lib/emscripten
2026-01-08T19:01:33+01:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2026-01-08T19:01:33+01:00 ERROR [crates/client/src/client.rs:357] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
2026-01-08T19:01:33+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T19:01:33+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T19:01:33+01:00 INFO  [workspace] Rendered first frame
2026-01-08T19:01:33+01:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon RX 6700 XT (RADV NAVI22)", driver_name: "radv", driver_info: "Mesa 25.3.3-arch1.1" }
2026-01-08T19:01:33+01:00 INFO  [crashes] connected to crash handler process after 100ms
2026-01-08T19:01:33+01:00 INFO  [crashes] crash handler registered
2026-01-08T19:01:33+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T19:01:33+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T19:01:33+01:00 INFO  [node_runtime] using Node.js found on PATH: SystemNodeRuntime { node: "/usr/bin/node", npm: "/usr/bin/npm", global_node_modules: "/usr/lib/node_modules\n", scratch_dir: "/home/thomas/.local/share/zed/node" }
2026-01-08T19:01:33+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["--max-old-space-size=8192", "/home/thomas/.local/share/zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2026-01-08T19:01:34+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T19:01:34+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/.config/zed", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T19:01:34+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2026-01-08T19:01:34+01:00 INFO  [lsp] starting language server process. binary path: "/home/thomas/.local/share/zed/languages/package-version-server/package-version-server-v0.0.10", working directory: "/home/thomas/Projects/RolePlay/atoria", args: []
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 413
}
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 460
}
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 61
}
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 25
}
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 41
}
2026-01-08T19:01:34+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 53
}
2026-01-08T19:01:34+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2026-01-08T19:01:37+01:00 ERROR [lsp] Shutdown request failure, server package-version-server (id 3): Unexpected params: null
2026-01-08T19:02:27+01:00 INFO  [zed] ========== starting zed version 0.218.6+stable, sha unknown ==========
2026-01-08T19:02:27+01:00 INFO  [crashes] spawning crash handler process
2026-01-08T19:02:27+01:00 WARN  [zed::reliability] Minidump endpoint not set
2026-01-08T19:02:27+01:00 INFO  [extension_host] extensions updated. loading 14, reloading 0, unloading 0
2026-01-08T19:02:27+01:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2026-01-08T19:02:27+01:00 INFO  [util] set environment variables from shell:/usr/bin/zsh, path:/home/thomas/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/thomas/.local/bin:/usr/lib/emscripten:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/usr/lib/rustup/bin:/usr/lib/emscripten:/home/thomas/.local/bin:/usr/lib/emscripten
2026-01-08T19:02:27+01:00 ERROR [crates/client/src/client.rs:357] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
2026-01-08T19:02:27+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2026-01-08T19:02:27+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2026-01-08T19:02:27+01:00 INFO  [workspace] Rendered first frame
2026-01-08T19:02:27+01:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon RX 6700 XT (RADV NAVI22)", driver_name: "radv", driver_info: "Mesa 25.3.3-arch1.1" }
2026-01-08T19:02:27+01:00 INFO  [crashes] connected to crash handler process after 100ms
2026-01-08T19:02:27+01:00 INFO  [crashes] crash handler registered
2026-01-08T19:02:27+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T19:02:27+01:00 INFO  [worktree] inserting parent git repo for this worktree: "zed/settings.json"
2026-01-08T19:02:27+01:00 INFO  [node_runtime] using Node.js found on PATH: SystemNodeRuntime { node: "/usr/bin/node", npm: "/usr/bin/npm", global_node_modules: "/usr/lib/node_modules\n", scratch_dir: "/home/thomas/.local/share/zed/node" }
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["--max-old-space-size=8192", "/home/thomas/.local/share/zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/.config/zed", args: ["/home/thomas/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/home/thomas/.local/share/zed/languages/package-version-server/package-version-server-v0.0.10", working directory: "/home/thomas/Projects/RolePlay/atoria", args: []
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 402
}
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 453
}
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 62
}
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 18
}
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 51
}
2026-01-08T19:02:28+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 67
}
2026-01-08T19:02:28+01:00 INFO  [lsp] starting language server process. binary path: "/usr/bin/node", working directory: "/home/thomas/Projects/RolePlay/atoria", args: ["/home/thomas/.local/share/zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2026-01-08T19:02:41+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 19
}
2026-01-08T19:02:41+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 50
}
2026-01-08T19:02:41+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 27
}
2026-01-08T19:02:41+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 61
}
2026-01-08T19:02:41+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 75
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 76
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 82
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 98
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 112
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 132
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 153
}
2026-01-08T19:02:42+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 7
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 34
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 65
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 101
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 88
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 107
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 68
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 76
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 95
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 127
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 148
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 107
}
2026-01-08T19:05:36+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 24
}
2026-01-08T19:07:17+01:00 ERROR [crates/fs/src/fs_watcher.rs:216] Error { kind: WatchNotFound, paths: ["/home/thomas/.cache/zed/.tmpCYr8nc"] }
2026-01-08T19:07:17+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 18
}
2026-01-08T19:07:17+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 36
}
2026-01-08T19:07:17+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 71
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 66
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 79
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 43
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/atoria.mjs",
  "state": 1,
  "validationTime": 52
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/items/item-sheet-v2.mjs",
  "state": 1,
  "validationTime": 71
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/utils/ruleset.mjs",
  "state": 1,
  "validationTime": 91
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/sheets/dialogs/roll-item-dialog.mjs",
  "state": 1,
  "validationTime": 112
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/documents/item.mjs",
  "state": 1,
  "validationTime": 98
}
2026-01-08T19:07:18+01:00 INFO  [lsp] Language server with id 6 sent unhandled notification eslint/status:
{
  "uri": "file:///home/thomas/Projects/RolePlay/atoria/module/models/items/inventory-items/weapon-item.mjs",
  "state": 1,
  "validationTime": 22
}

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "languages": {
    "Plain Text": {
      "ensure_final_newline_on_save": false,
      "remove_trailing_whitespace_on_save": false,
      "format_on_save": "off",
    },
  },
  "window_decorations": "server",
  "auto_signature_help": false,
  "hover_popover_enabled": true,
  "outline_panel": {
    "indent_size": 15.0,
  },
  "project_panel": {
    "hide_root": false,
    "indent_size": 15.0,
    "entry_spacing": "comfortable",
  },
  "tabs": {
    "show_close_button": "hidden",
    "file_icons": false,
    "git_status": false,
  },
  "inlay_hints": {
    "enabled": false,
  },
  "format_on_save": "on",
  "toolbar": {
    "code_actions": false,
  },
  "show_signature_help_after_edits": false,
  "collaboration_panel": {
    "dock": "right",
  },
  "git_panel": {
    "collapse_untracked_diff": false,
    "sort_by_path": true,
  },
  "disable_ai": true,
  "base_keymap": "VSCode",
  "ui_font_size": 16,
  "buffer_font_size": null,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "One Dark",
  },
  "show_edit_predictions": false,
  "features": {
    "edit_prediction_provider": "none",
  },
  "git": {
    "git_gutter": "tracked_files",
    "inline_blame": {
      "enabled": false,
    },
  },
  "scrollbar": {
    "git_diff": false,
  },
  "title_bar": {
    "show_branch_name": true,
    "show_project_items": true,
    "show_onboarding_banner": true,
    "show_user_picture": true,
    "show_sign_in": false,
    "show_menus": false,
    "show_branch_icon": true,
  },
  "agent": {
    "enabled": false,
    "button": false,
  },
  "enable_language_server": true,
  "use_system_path_prompts": false,
  "lsp": {
    "rust-analyzer": {
      "enable_lsp_tasks": true,
      "initialization_options": {
        "check": {
          "command": "clippy",
          "arguments": ["--no-deps"],
          "workspace": false,
        },
        "checkOnSave": true,
        "cargo": {
          "allTargets": false,
        },
      },
    },
  },
  "terminal": {
    "font_family": "MesloLGS NF",
    "font_size": 14,
  },
}

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "bindings": {
      "ctrl-q": null
    }
  },
  {
    "context": "Workspace",
    "bindings": {}
  },
  {
    "context": "Editor",
    "bindings": {
      "ctrl-shift-e": "project_panel::ToggleFocus"
    }
  },
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w": "pane::CloseActiveItem", // Don't pass ctrl-w to terminal, let Zed handle it.
      "ctrl-`": "workspace::ToggleBottomDock" // match vscode behavior
    }
  }
]

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by austincummings**
The OpenFiles action was always using the system file picker dialog, ignoring the use_system_path_prompts setting. This adds a workspace-level handler that calls prompt_for_open_path, which respects the setting, instead of falling through to the global handler.

Closes #46386

Release Notes:

- Fixed "workspace: open files" not respecting "use_system_path_prompts" setting

### CODE REVIEW

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
Great idea, but why keep the other action handler at all, with this approach?

Also, it seems `prompt_and_open_paths` is used on `CloseWindow` — this is also a wrong place to keep the native prompt.

Maybe, the answer is to alter `fn prompt_and_open_paths` entirely (or remove it and use whatever one works instead)?

File: crates/workspace/src/workspace.rs [hunk 1]
```diff
@@ -584,79 +584,14 @@ impl From<WorkspaceId> for i64 {
...
     component::init();
     theme_preview::init(cx);
     toast_layer::init(cx);
     history_manager::init(cx);
 
     cx.on_action(|_: &CloseWindow, cx| Workspace::close_global(cx))
-        .on_action(|_: &Reload, cx| reload(cx))
-        .on_action({
-            let app_state = Arc::downgrade(&app_state);
-            move |_: &Open, cx: &mut App| {
```
Comment (SomeoneToIgnore) [inline crates/workspace/src/workspace.rs:657]: That handler was just removed without any counterpart added???

**Review by SomeoneToIgnore — COMMENTED** [review]
> Hm, I'm not seeing where this is.

Right, that part is either gone or I was wrong, sorry — either way it's nothing to worry about now.

--------

Really sorry for confusing you here: the global handler is actually very important for macOs as there, the app can be alive without any UI present onscreen, hence certain commands like "open a file" are expected to work there.

With `.register_action` only we cannot achieve that, as this way the listener is registered on a particular `workspace` which is a `Window` at the same time in Zed, which won't exist at the moment described above.

So, we need a global listener, after all — for that, it should be simple to move the `register_action` code there.
That presumably now will invoke the code with the modal, right?

The next question is whether that's enough — you mention that the global is not called on Linux at all and that makes sense as on that OS the app exists after its last window is closed.
But, that global handler was shadowed by the local one before — hence, when we remove the local and leave the global only, it presumably should start running?

Otherwise, looks good, we're seem to be close.

**Comment by SomeoneToIgnore** [comment]
Well, I wish you can think on something yourself instead of forcing me to — this is the whole point of contributions I have thought 🙂 

My words are not what you have stated: I think that it's enough to have a global handler only.
But I am only guessing, I hope someone can verify the combination(s) and find the minimal one...

**Comment by austincummings** [comment]
After playing around with implementing the single global handler - I do believe the two handler approach to be the correct one and most consistent with how the other (`workspace::Open`) handler works. It makes sense to me to have the global handler dedicated to when there is no window open, and so it will always use the system picker. And keep the workspace level handler so it can show the built-in picker in that window.

The two global handlers will never be called on Linux or Windows though AFAIK, so it's essentially macOS only (at least until Zed can run in the background on Linux or Windows). I messed around with wrapping that in `#[cfg(target_os = "macos")]` but it was a bit ugly, and unfortunately I don't have a Mac to test it with.

I rebased and dropped the last few commits and am sticking with just the initial commit I made for this.

**Review by SomeoneToIgnore — APPROVED** [review]
I have deduplicated the logic as asked in https://github.com/zed-industries/zed/pull/47027#pullrequestreview-3693443833 and tested on mac (both with and without the window) and Linux — both cases seem to work.

Thank you for spotting, and congrats with the first contribution.
