### PR TITLE
Git activity indicator

### LINKED ISSUE #26182: Missing loading state during branch switch
### Summary

The ui is missing a state when we are switching branches and it takes a long time. 

Steps to trigger the problem:
1. Open a repository where switching branches takes a long time. I can't give you one cause the one I have is closed source. 
2. While switching branches the selector remains open, we can click on another branch, while we are still switching to the previous selected one. If we close it, and we click again to switch to another branch, no branch is shown and we get this error: 

Image

We need a in between state, where when we switch branches we get some loader animation somewhere. 
The question is also if we should be able to switch to another branch, while we are already in the status of switching already. 

### Zed Version and System Specs

Zed: v0.178.0 (Zed Dev d3c68650c079917e873eb3347f7b04d0277c99dc) (Taylor's Version)
OS: macOS 15.3.1
Memory: 48 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by P1n3appl3**
Closes #26182

Release Notes:

- Added an activity indicator for long-running git commands.

### CODE REVIEW

File: crates/project/src/git_store.rs [hunk 1]
```diff
@@ -2643,36 +2647,56 @@ impl Repository {
...
                     cx.spawn(async move |_| {
+                        if let Some(s) = status.clone() {
+                            let mut current = current_job.lock();
+                            *current = Some((s.clone(), Instant::now()));
+                        }
                         let result = job.await;
+                        if let Some(s) = status {
+                            let mut current = current_job.lock();
+                            let old = current.take();
+                            debug_assert_eq!(
```
Comment (P1n3appl3) [inline crates/project/src/git_store.rs:2694]: @mikayla-maki this was the only part I wasn't 100% sure about so I left a debug assert in there.

If there's some way for the git worker to drop or cancel a job, or if it doesn't serialize the jobs, then you could end up in a situation where two jobs clobber each other when trying to set/clear `current_job`. afaik neither are possible today, but I assume it's fine to leave this in in-case a future change invalidates the invariant.

Comment (mikayla-maki) [reply crates/project/src/git_store.rs:2694]: I think I'd rather we structure this code so that this case is handled automatically. No need to depend on the serialization property for this feature.

**Comment by mikayla-maki** [comment]
Note that a lot of this PR is changing the git store methods from taking an `&` to an `&mut`
