### PR TITLE
Fix parenthesis matching for file links in terminal

### LINKED ISSUE #17391: URL's with `(` parenthesis should be clickable in the terminal
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

image

Currently, URLs with parenthesis `(` `)` are not clickable in the terminal.

SvelteKit uses theses types of file routes to create layout groups. So this is quite annoying.

### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by saahityaedams**
Closes #17391 

Release Notes:

- Fixed parenthesis matching for file links in terminal ([#17391](https://github.com/zed-industries/zed/issues/17391))

### CODE REVIEW

**Comment by saahityaedams** [comment]
@cla-bot check

File: crates/terminal/src/terminal.rs [hunk 1]
```diff
@@ -425,7 +425,7 @@ impl TerminalBuilder {
         // Optional suffix matches MSBuild diagnostic suffixes for path parsing in PathLikeWithPosition
         // https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-diagnostic-format-for-tasks
         let word_regex =
-            RegexSearch::new(r#"[\$\+\w.\[\]:/\\@\-~]+(?:\((?:\d+|\d+,\d+)\))?"#).unwrap();
+            RegexSearch::new(r#"[\$\+\w.\[\]:/\\@\-~()]+(?:\((?:\d+|\d+,\d+)\))?"#).unwrap();
```
Comment (maxdeviant) [inline crates/terminal/src/terminal.rs:428]: Don't we need to escape these so they're not treated as a capture group?

```suggestion
            RegexSearch::new(r#"[\$\+\w.\[\]:/\\@\-~\(\)]+(?:\((?:\d+|\d+,\d+)\))?"#).unwrap();
```

Comment (saahityaedams) [reply crates/terminal/src/terminal.rs:428]: We don't need to escape parentheses **inside a character class** because parentheses in this context are treated as literal characters, not as special regex constructs like capture groups.

I was able to repro the issue and the confirm that this change fixed it.
Screenshot 2024-09-07 at 7 55 32 AM

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you for confirming that it works.

**Comment by AlbertMarashi** [comment]
Great job
