### PR TITLE
markdown preview: Fix panic when parsing empty image tag

### LINKED ISSUE #21534: Markdown preview image rendering crashes with empty alt text / title
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Add `` or `` (doesn't matter if there is an image link or not, depends solely on the alt text presence as far as I can tell) to a markdown file.
2. Open the markdown preview panel, and then focus back on the text/buffer (this is important, it does't crash until you do this).

Crashes with the following error:
```
Thread "main" panicked with "index out of bounds: the len is 0 but the index is 0" at crates/markdown_preview/src/markdown_elements.rs:28:49
```

Which is this line here:
https://github.com/zed-industries/zed/blob/3019960f83e6852a5b9ce3706f88addce3aa2983/crates/markdown_preview/src/markdown_elements.rs#L28

Looks like it doesn't account for the length of the vec of the parsed elements being zero. Is the inside of the alt text area being parsed as markdown text? I would assume you can only use plaintext inside the brackets there.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by bennetbo**
Closes #21534

While investigating the panic, I noticed that the code was pretty complicated and decided to refactor parts of it to reduce redundancy.

Release Notes:

- Fixed an issue where the app could crash when opening the markdown preview with a malformed image tag

### CODE REVIEW

File: crates/markdown_preview/src/markdown_elements.rs [hunk 1]
```diff
@@ -18,21 +18,18 @@ pub enum ParsedMarkdownElement {
...
-            Self::Table(table) => table.source_range.clone(),
-            Self::BlockQuote(block_quote) => block_quote.source_range.clone(),
-            Self::CodeBlock(code_block) => code_block.source_range.clone(),
-            Self::Paragraph(text) => match &text[0] {
-                MarkdownParagraphChunk::Text(t) => t.source_range.clone(),
-                MarkdownParagraphChunk::Image(image) => match image {
-                    Image::Web { source_range, .. } => source_range.clone(),
-                    Image::Path { source_range, .. } => source_range.clone(),
-                },
+            Self::Heading(heading) => Some(heading.source_range.clone()),
```
Comment (mgsloan) [inline crates/markdown_preview/src/markdown_elements.rs:23]: Can pull one `Some(` out to wrap the whole match.

Comment (bennetbo) [reply crates/markdown_preview/src/markdown_elements.rs:23]: Good point!
