### PR TITLE
project: Send LSP metadata to remote ServerInfo

### LINKED ISSUE #39582: Remote servers' LSP ServerInfo shows "Unknown" for Binary and Configuration
### Summary

LSP ServerInfo shows "Unknown" for Binary/Configuration and empty workspace folders in WSL remote development, despite LSPs working correctly.

### Description
I'm experiencing a issue with LSP debugging information in WSL remote development. While the LSPs are functioning (mostly) correctly, the ServerInfo shows missing metadata for all language servers.

### Related Issues
https://github.com/zed-industries/zed/issues/27328
https://github.com/zed-industries/zed/issues/28557
Note: I'm not sure about the current status of this issue or if it's still being actively investigated, but I wanted to share my findings in case they help with debugging or provide additional context.

### Environment
Zed Nightly 0.208.0 
bcd2d269e22540c9a8f710331d82aab7af90d897
WSL: openSUSE Tumbleweed
Connection: Via ZED's native WSL integration

All LSPs work (autocomplete, hover, diagnostics), but ServerInfo shows incomplete information e.g.:
```
* Server: vtsls (id 0)
* Binary: Unknown
* Configuration: Unknown
* Registered workspace folders: 
* Capabilities: { ... }  // These are populated correctly
```
### Evidence that LSPs are running
```bash
ps aux | grep -E "(language-server|lsp)"
tom  7316  /home/_/.asdf/installs/nodejs/lts/bin/node --max-old-space-size=8092 /home/_/dev/repos/_/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic ...
tom  7318  /home/_/.asdf/installs/nodejs/lts/bin/node --max-old-space-size=8092 /home/tom/dev/repos/_/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot ...
tom  7364  /home/_/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node /home/_/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server --stdio
```

### ZED-LOG
```bash
2025-10-06T09:47:42+02:00 INFO  [zed] ========== starting zed version 0.208.0, sha bcd2d26 ==========
2025-10-06T09:47:42+02:00 INFO  [gpui::platform::windows::directx_devices] Using GPU: Intel(R) UHD Graphics
2025-10-06T09:47:42+02:00 INFO  [gpui::platform::windows::directx_devices] Created device with Direct3D 11.1 feature level.
2025-10-06T09:47:42+02:00 INFO  [gpui::platform::windows::direct_write] Use Segoe UI as UI font.
2025-10-06T09:47:42+02:00 INFO  [zed] Using git binary path: None
2025-10-06T09:47:42+02:00 INFO  [extension_host] extensions updated. loading 4, reloading 0, unloading 0
2025-10-06T09:47:42+02:00 INFO  [gpui::platform::windows::vsync] DirectComposition is supported for VSync, interval: 16.714ms
2025-10-06T09:47:42+02:00 INFO  [auto_update] Auto Update: checking for updates
2025-10-06T09:47:42+02:00 ERROR [client] Element nicht gefunden. (0x80070490)
2025-10-06T09:47:42+02:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics", driver_name: "Intel Corporation", driver_info: "32.0.101.6881" }
2025-10-06T09:47:47+02:00 ERROR [agent2::agent] Failed to authenticate provider: Amazon Bedrock: Element nicht gefunden. (0x80070490)
2025-10-06T09:47:47+02:00 INFO  [crashes] spawning crash handler process
2025-10-06T09:47:47+02:00 INFO  [crashes] connected to crash handler process after 100ms
2025-10-06T09:47:47+02:00 INFO  [crashes] crash handler registered
2025-10-06T09:48:08+02:00 INFO  [remote::transport::wsl] Connecting to WSL distro openSUSE-Tumbleweed with user None
2025-10-06T09:48:11+02:00 ERROR [remote::remote_client] client:unhandled ssh message name:UpdateProject
2025-10-06T09:48:11+02:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics", driver_name: "Intel Corporation", driver_info: "32.0.101.6881" }
2025-10-06T09:48:11+02:00 INFO  [terminal] Using wsl.exe as shell
2025-10-06T09:48:11+02:00 INFO  [alacritty_terminal::tty::windows::conpty] Using conpty.dll for pseudoconsole
2025-10-06T09:48:11+02:00 ERROR [agent2::agent] Failed to authenticate provider: Amazon Bedrock: Element nicht gefunden. (0x80070490)
2025-10-06T09:48:11+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 64 to 128
2025-10-06T09:48:11+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating polychrome_sprite_pipeline buffer size from 16 to 32
2025-10-06T09:48:11+02:00 INFO  [gpui::platform::windows::directx_renderer] Updating monochrome_sprite_pipeline buffer size from 512 to 1024
2025-10-06T09:48:21+02:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics", driver_name: "Intel Corporation", driver_info: "32.0.101.6881" }
2025-10-06T09:48:21+02:00 ERROR [agent2::agent] Failed to authenticate provider: Amazon Bedrock: Element nicht gefunden. (0x80070490)
```

I'm happy to provide additional debugging information or test potential fixes if that would be helpful for resolving this issue.

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly bcd2d269e22540c9a8f710331d82aab7af90d897) 
OS: Windows 10.0.26100
Memory: 31.2 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics || Intel Corporation || 32.0.101.6881

### PR DESCRIPTION
**Pull request by errmayank**
Closes #39582

Release Notes:

- Fixed language server info not available in remote projects

Here's the before/after:

https://github.com/user-attachments/assets/1057faa5-82af-4975-abad-5e10e139fac1

### CODE REVIEW

File: crates/project/src/lsp_store.rs [hunk 1]
```diff
@@ -3534,6 +3535,19 @@ fn notify_server_capabilities_updated(server: &LanguageServer, cx: &mut Context<
             message: proto::update_language_server::Variant::MetadataUpdated(
                 proto::ServerMetadataUpdated {
                     capabilities: Some(capabilities),
+                    binary_path: Some(server.binary().path.to_string_lossy().to_string()),
+                    binary_args: server
+                        .binary()
+                        .arguments
+                        .iter()
+                        .map(|arg| arg.to_string_lossy().to_string())
```
Comment (osiewicz) [inline crates/project/src/lsp_store.rs]:
```suggestion
                        .map(|arg| arg.to_string_lossy().into_owned())
```

File: crates/lsp/src/lsp.rs [hunk 2]
```diff
@@ -62,7 +62,7 @@ pub enum IoKind {
 
 /// Represents a launchable language server. This can either be a standalone binary or the path
 /// to a runtime with arguments to instruct it to launch the actual language server file.
-#[derive(Clone)]
+#[derive(Clone, Serialize)]
```
Comment (osiewicz) [inline crates/lsp/src/lsp.rs]: I worry a bit about serializing `PathBuf`/`OsStrings` to JSON that way. Feels brittle with e.g. macOS host and Windows remote.

Comment (errmayank) [reply crates/lsp/src/lsp.rs]: Makes sense, I've updated it to use a separate `LanguageServerBinaryInfo` struct for `ServerInfo`. Does that look okay?

File: crates/language_tools/src/lsp_log_view.rs [hunk 3]
```diff
@@ -338,10 +341,11 @@ impl LspLogView {
...
             NAME = info.name,
             ID = info.id,
-            BINARY = info
-                .binary
-                .as_ref()
-                .map_or_else(|| "Unknown".to_string(), |binary| format!("{binary:#?}")),
+            BINARY = info.binary.as_ref().map_or_else(
+                || "Unknown".to_string(),
+                |binary| serde_json::to_string_pretty(binary)
+                    .unwrap_or_else(|e| format!("Failed to serialize binary info: {e}"))
```
Comment (SomeoneToIgnore) [inline crates/language_tools/src/lsp_log_view.rs]:
```suggestion
                    .unwrap_or_else(|e| format!("Failed to serialize binary info: {e:#}"))
```

Unless there's a specific reason to not have it, this way we'll get a trace of errors that lead to the final one, which is usually useful.

File: crates/proto/proto/lsp.proto [hunk 4]
```diff
@@ -615,8 +615,17 @@ message RegisteredForBuffer {
     uint64 buffer_id = 2;
 }
 
+message LanguageServerBinaryInfo {
+    string path = 1;
+    repeated string arguments = 2;
+    map<string, string> env = 3;
```
Comment (SomeoneToIgnore) [inline crates/proto/proto/lsp.proto]: Let's remove this data from the message entirely: if needed, this can be done later same as this PR deals with the rest.

It's relatively risky already to have this displayed, as any `GITHUB_AUTH_KEY` or similar can leak in, and last thing we need is that to go over the wire for nothing but to be displayed in the UI 😄 

Alternatively, we can add `util::redact::should_redact` usage to both local and remote versions.

File: crates/language_tools/src/lsp_log_view.rs [hunk 5]
```diff
@@ -632,17 +636,24 @@ impl LspLogView {
...
+                            lsp_store.language_server_statuses.get(&server_id)?;
+
                         Some(ServerInfo {
                             id: server_id,
                             capabilities,
-                            binary: None,
-                            name,
-                            workspace_folders: Vec::new(),
-                            configuration: None,
+                            name: language_server_status.name.clone(),
```
Comment (SomeoneToIgnore) [inline crates/language_tools/src/lsp_log_view.rs]: I know `LanguageServerStatus` stores a bit more info, but code-wise, it seems simpler to store that one struct as one field?

Should we try that?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, looks good overall.

I've added a few style-related, minor comments and one very important about `env`.

File: crates/language_tools/src/lsp_log_view.rs (hunk 5 above)
Comment (errmayank) [reply crates/language_tools/src/lsp_log_view.rs]: Sounds good, updated.

**Comment by errmayank** [comment]
Here's the diff:

<details>
<summary>Local Server Info</summary>

```diff
-* Server: basedpyright (id 20)
+* Server: basedpyright (id 7)
 
-* Binary: LanguageServerBinary {
-    path: "/Users/mayank/.nvm/versions/node/v24.11.1/bin/node",
-    arguments: [
-        "/Users/mayank/Library/Application Support/Zed/languages/basedpyright/node_modules/basedpyright/langserver.index.js",
-        "--stdio",
-    ],
-    env: Some(
-        {
-            "COMMAND_MODE": "unix2003",
-            "CPPFLAGS": "-I/opt/homebrew/opt/sqlite/include",
-            "GOPATH": "/Users/mayank/go",
-            "GPG_TTY": "not a tty",
-            "HOME": "/Users/mayank",
-            "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
-            "HOMEBREW_PREFIX": "/opt/homebrew",
-            "HOMEBREW_REPOSITORY": "/opt/homebrew",
-            "INFOPATH": "/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:",
-            "LANG": "C.UTF-8",
-            "LDFLAGS": "-L/opt/homebrew/opt/sqlite/lib",
-            "LESS": "-R",
-            "LOGNAME": "mayank",
-            "LSCOLORS": "Gxfxcxdxbxegedabagacad",
-            "NVM_BIN": "/Users/mayank/.nvm/versions/node/v24.11.1/bin",
-            "NVM_CD_FLAGS": "-q",
-            "NVM_DIR": "/Users/mayank/.nvm",
-            "NVM_INC": "/Users/mayank/.nvm/versions/node/v24.11.1/include/node",
-            "OLDPWD": "/",
-            "OSLogRateLimit": "64",
-            "PAGER": "less",
-            "PATH": "/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/opt/sqlite/bin:/Users/mayank/Library/pnpm:/Users/mayank/.nvm/versions/node/v24.11.1/bin:/Users/mayank/go/bin:/Users/mayank/google-cloud-sdk/bin:/Users/mayank/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/opt/sqlite/bin:/Users/mayank/Library/pnpm:/Users/mayank/.nvm/versions/node/v24.11.1/bin:/Users/mayank/go/bin:/Users/mayank/google-cloud-sdk/bin:/Users/mayank/bin:/Users/mayank/.cargo/bin:/Users/mayank/Library/Application Support/JetBrains/Toolbox/scripts:/Users/mayank/.local/bin:/Users/mayank/Library/Application Support/JetBrains/Toolbox/scripts:/Users/mayank/.local/bin:/Users/mayank/.local/bin",
-            "PNPM_HOME": "/Users/mayank/Library/pnpm",
-            "PWD": "/Users/mayank/github.com/tests/zed/remote-py",
-            "SHELL": "/bin/zsh",
-            "SHLVL": "1",
-            "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.sOWzbdILfl/Listeners",
-            "STARSHIP_SESSION_KEY": "REDACTED",
-            "STARSHIP_SHELL": "zsh",
-            "TMPDIR": "/var/folders/3r/dttkkzhj4hn710_kbt3jrqgc0000gn/T/",
-            "USER": "mayank",
-            "XPC_FLAGS": "0x0",
-            "XPC_SERVICE_NAME": "0",
-            "ZED_ENVIRONMENT": "worktree-shell",
-            "ZSH": "/Users/mayank/.oh-my-zsh",
-            "_": "/Applications/Zed.app/Contents/MacOS/zed",
-            "__CFBundleIdentifier": "dev.zed.Zed",
-            "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
-        },
-    ),
+* Binary: {
+  "path": "/Users/mayank/.nvm/versions/node/v24.11.1/bin/node",
+  "arguments": [
+    "/Users/mayank/Library/Application Support/Zed/languages/basedpyright/node_modules/basedpyright/langserver.index.js",
+    "--stdio"
+  ],
+  "env": {
+    "CARGO_PKG_VERSION_MINOR": "214",
+    "HOMEBREW_REPOSITORY": "/opt/homebrew",
+    "NVM_CD_FLAGS": "-q",
+    "OSLogRateLimit": "64",
+    "CARGO_PKG_NAME": "zed",
+    "__CFBundleIdentifier": "com.mitchellh.ghostty",
+    "GOPATH": "/Users/mayank/go",
+    "CARGO_PKG_VERSION": "0.214.0",
+    "_": "/Users/mayank/github.com/clones/zed/target/debug/zed",
+    "CARGO_PKG_LICENSE": "GPL-3.0-or-later",
+    "GHOSTTY_SHELL_FEATURES": "path,title",
+    "CARGO_PKG_LICENSE_FILE": "",
+    "CARGO_MANIFEST_PATH": "/Users/mayank/github.com/clones/zed/crates/zed/Cargo.toml",
+    "CARGO_PKG_AUTHORS": "Zed Team <hi@zed.dev>",
+    "LDFLAGS": "-L/opt/homebrew/opt/sqlite/lib",
+    "NVM_BIN": "/Users/mayank/.nvm/versions/node/v24.11.1/bin",
+    "NVM_DIR": "/Users/mayank/.nvm",
+    "OLDPWD": "/Users/mayank/github.com/clones/zed/",
+    "SHELL": "/bin/zsh",
+    "ZSH": "/Users/mayank/.oh-my-zsh",
+    "GPG_TTY": "not a tty",
+    "PAGER": "less",
+    "MACOSX_DEPLOYMENT_TARGET": "10.15.7",
+    "LESS": "-R",
+    "STARSHIP_SHELL": "zsh",
+    "CARGO_PKG_RUST_VERSION": "",
+    "LOGNAME": "mayank",
+    "MANPATH": "/Users/mayank/.nvm/versions/node/v24.11.1/share/man::/usr/share/man:/usr/local/share/man:/Users/mayank/.nvm/versions/node/v24.11.1/share/man:/Applications/Ghostty.app/Contents/Resources/ghostty/../man:",
+    "RUSTUP_TOOLCHAIN": "1.91.1-aarch64-apple-darwin",
+    "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
+    "HOMEBREW_PREFIX": "/opt/homebrew",
+    "CARGO_HOME": "/Users/mayank/.cargo",
+    "CARGO_PKG_VERSION_PATCH": "0",
+    "XPC_SERVICE_NAME": "0",
+    "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
+    "TERM_PROGRAM_VERSION": "1.2.3",
+    "RUSTUP_HOME": "/Users/mayank/.rustup",
+    "PNPM_HOME": "/Users/mayank/Library/pnpm",
+    "LSCOLORS": "Gxfxcxdxbxegedabagacad",
+    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.sOWzbdILfl/Listeners",
+    "CARGO_PKG_DESCRIPTION": "The fast, collaborative code editor.",
+    "ZED_ENVIRONMENT": "worktree-shell",
+    "TMPDIR": "/var/folders/3r/dttkkzhj4hn710_kbt3jrqgc0000gn/T/",
+    "TERMINFO": "/Applications/Ghostty.app/Contents/Resources/terminfo",
+    "STARSHIP_SESSION_KEY": "1272419429263353",
+    "XDG_DATA_DIRS": "/usr/local/share:/usr/share:/Applications/Ghostty.app/Contents/Resources/ghostty/..",
+    "CARGO_MANIFEST_DIR": "/Users/mayank/github.com/clones/zed/crates/zed",
+    "CARGO_PKG_HOMEPAGE": "",
+    "CARGO_PKG_VERSION_PRE": "",
+    "COLORTERM": "truecolor",
+    "INFOPATH": "/opt/homebrew/share/info:/opt/homebrew/share/info:",
+    "SHLVL": "1",
+    "RUST_RECURSION_COUNT": "1",
+    "XPC_FLAGS": "0x0",
+    "USER": "mayank",
+    "GHOSTTY_RESOURCES_DIR": "/Applications/Ghostty.app/Contents/Resources/ghostty",
+    "NVM_INC": "/Users/mayank/.nvm/versions/node/v24.11.1/include/node",
+    "PATH": "/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/opt/sqlite/bin:/Users/mayank/Library/pnpm:/Users/mayank/.nvm/versions/node/v24.11.1/bin:/Users/mayank/go/bin:/Users/mayank/google-cloud-sdk/bin:/Users/mayank/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/opt/sqlite/bin:/Users/mayank/Library/pnpm:/Users/mayank/.nvm/versions/node/v24.11.1/bin:/Users/mayank/go/bin:/Users/mayank/google-cloud-sdk/bin:/Users/mayank/bin:/Users/mayank/.cargo/bin:/Applications/Ghostty.app/Contents/MacOS:/Users/mayank/Library/Application Support/JetBrains/Toolbox/scripts:/Users/mayank/.local/bin:/Users/mayank/Library/Application Support/JetBrains/Toolbox/scripts:/Users/mayank/.local/bin:/Users/mayank/.local/bin",
+    "TARGET": "aarch64-apple-darwin",
+    "TERM": "xterm-ghostty",
+    "CARGO": "/Users/mayank/.rustup/toolchains/1.91.1-aarch64-apple-darwin/bin/cargo",
+    "GHOSTTY_BIN_DIR": "/Applications/Ghostty.app/Contents/MacOS",
+    "ZED_COMMIT_SHA": "389e6b7af5a29606346f20ebae81dc47c6f4f92f",
+    "CARGO_PKG_README": "",
+    "OUT_DIR": "/Users/mayank/github.com/clones/zed/target/debug/build/zed-29c69e54e52fda63/out",
+    "HOME": "/Users/mayank",
+    "COMMAND_MODE": "unix2003",
+    "CARGO_PKG_VERSION_MAJOR": "0",
+    "PWD": "/Users/mayank/github.com/tests/zed/remote-py",
+    "CPPFLAGS": "-I/opt/homebrew/opt/sqlite/include",
+    "LANG": "en_US.UTF-8",
+    "TERM_PROGRAM": "ghostty",
+    "CARGO_PKG_REPOSITORY": ""
+  }
 }
 
 * Registered workspace folders:
 /Users/mayank/github.com/tests/zed/remote-py
 
 * Capabilities: {
   "textDocumentSync": {
     "openClose": true,
     "change": 2,
     "willSave": true
   },
   "hoverProvider": {
     "workDoneProgress": true
   },
   "completionProvider": {
     "resolveProvider": true,
     "triggerCharacters": [
       ".",
       "[",
       "\"",
       "'"
     ],
     "workDoneProgress": true,
     "completionItem": {
       "labelDetailsSupport": true
     }
   },
   "signatureHelpProvider": {
     "triggerCharacters": [
       "(",
       ",",
       ")"
     ],
     "workDoneProgress": true
   },
   "definitionProvider": {
     "workDoneProgress": true
   },
   "typeDefinitionProvider": {
     "documentSelector": null
   },
   "implementationProvider": {
     "documentSelector": null
   },
   "referencesProvider": {
     "workDoneProgress": true
   },
   "documentHighlightProvider": {
     "workDoneProgress": true
   },
   "documentSymbolProvider": {
     "workDoneProgress": true
   },
   "workspaceSymbolProvider": {
     "workDoneProgress": true
   },
   "codeActionProvider": {
     "codeActionKinds": [
       "quickfix",
       "source.organizeImports"
     ],
     "workDoneProgress": true
   },
   "documentOnTypeFormattingProvider": {
     "firstTriggerCharacter": "{"
   },
   "renameProvider": {
     "prepareProvider": true,
     "workDoneProgress": true
   },
   "declarationProvider": {
     "workDoneProgress": true,
     "documentSelector": null
   },
   "executeCommandProvider": {
     "commands": [
       "basedpyright.createtypestub",
       "basedpyright.restartserver",
       "basedpyright.writeBaseline"
     ],
     "workDoneProgress": true
   },
   "workspace": {
     "workspaceFolders": {
       "supported": true,
       "changeNotifications": true
     },
     "fileOperations": {
       "willRename": {
         "filters": [
           {
             "scheme": null,
             "pattern": {
               "glob": "**/*"
             }
           }
         ]
       }
     }
   },
   "callHierarchyProvider": true,
   "semanticTokensProvider": {
     "legend": {
       "tokenTypes": [
         "namespace",
         "type",
         "class",
         "enum",
         "typeParameter",
         "parameter",
         "variable",
         "property",
         "enumMember",
         "function",
         "method",
         "keyword",
         "decorator",
         "selfParameter",
         "clsParameter"
       ],
       "tokenModifiers": [
         "declaration",
         "definition",
         "readonly",
         "static",
         "async",
         "defaultLibrary",
         "builtin",
         "classMember",
         "parameter"
       ]
     },
     "full": true
   },
   "inlayHintProvider": true,
   "diagnosticProvider": {
     "identifier": "basedpyright",
     "interFileDependencies": true,
     "workspaceDiagnostics": true
   }
 }
 
 * Configuration: {
   "basedpyright.analysis": {
     "diagnosticMode": "workspace",
     "inlayHints": {
       "callArgumentNames": false
     },
     "typeCheckingMode": "standard"
   },
   "python": {
     "pythonPath": "/opt/homebrew/bin/python3",
     "defaultInterpreterPath": "/opt/homebrew/bin/python3"
   }
 }
```
</details>

<details>
<summary>Remote Server Info</summary>

```diff
 * Server: basedpyright (id 0)
 
-* Binary: Unknown
+* Binary: {
+  "path": "/home/zed/.local/share/zed/node/node-v24.11.0-linux-arm64/bin/node",
+  "arguments": [
+    "/home/zed/.local/share/zed/languages/basedpyright/node_modules/basedpyright/langserver.index.js",
+    "--stdio"
+  ],
+  "env": null
+}
 
 * Registered workspace folders:
-
+/home/zed/remote-py
 
 * Capabilities: {
   "textDocumentSync": {
     "openClose": true,
     "change": 2,
     "willSave": true
   },
   "hoverProvider": {
     "workDoneProgress": true
   },
   "completionProvider": {
     "resolveProvider": true,
     "triggerCharacters": [
       ".",
       "[",
       "\"",
       "'"
     ],
     "workDoneProgress": true,
     "completionItem": {
       "labelDetailsSupport": true
     }
   },
   "signatureHelpProvider": {
     "triggerCharacters": [
       "(",
       ",",
       ")"
     ],
     "workDoneProgress": true
   },
   "definitionProvider": {
     "workDoneProgress": true
   },
   "typeDefinitionProvider": {
     "documentSelector": null
   },
   "implementationProvider": {
     "documentSelector": null
   },
   "referencesProvider": {
     "workDoneProgress": true
   },
   "documentHighlightProvider": {
     "workDoneProgress": true
   },
   "documentSymbolProvider": {
     "workDoneProgress": true
   },
   "workspaceSymbolProvider": {
     "workDoneProgress": true
   },
   "codeActionProvider": {
     "codeActionKinds": [
       "quickfix",
       "source.organizeImports"
     ],
     "workDoneProgress": true
   },
   "documentOnTypeFormattingProvider": {
     "firstTriggerCharacter": "{"
   },
   "renameProvider": {
     "prepareProvider": true,
     "workDoneProgress": true
   },
   "declarationProvider": {
     "workDoneProgress": true,
     "documentSelector": null
   },
   "executeCommandProvider": {
     "commands": [
       "basedpyright.createtypestub",
       "basedpyright.restartserver",
       "basedpyright.writeBaseline"
     ],
     "workDoneProgress": true
   },
   "workspace": {
     "workspaceFolders": {
       "supported": true,
       "changeNotifications": true
     },
     "fileOperations": {
       "willRename": {
         "filters": [
           {
             "scheme": null,
             "pattern": {
               "glob": "**/*"
             }
           }
         ]
       }
     }
   },
   "callHierarchyProvider": true,
   "semanticTokensProvider": {
     "legend": {
       "tokenTypes": [
         "namespace",
         "type",
         "class",
         "enum",
         "typeParameter",
         "parameter",
         "variable",
         "property",
         "enumMember",
         "function",
         "method",
         "keyword",
         "decorator",
         "selfParameter",
         "clsParameter"
       ],
       "tokenModifiers": [
         "declaration",
         "definition",
         "readonly",
         "static",
         "async",
         "defaultLibrary",
         "builtin",
         "classMember",
         "parameter"
       ]
     },
     "full": true
   },
   "inlayHintProvider": true,
   "diagnosticProvider": {
     "identifier": "basedpyright",
     "interFileDependencies": true,
     "workspaceDiagnostics": true
   }
 }
 
-* Configuration: Unknown
+* Configuration: {
+  "basedpyright.analysis": {
+    "diagnosticMode": "workspace",
+    "inlayHints": {
+      "callArgumentNames": false
+    },
+    "typeCheckingMode": "standard"
+  },
+  "venvPath": "/",
+  "venv": "usr",
+  "python": {
+    "pythonPath": "/bin/python3",
+    "defaultInterpreterPath": "/bin/python3"
+  }
+}

```
</details>

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!

**Comment by notpeter** [comment]
@errmayank This introduced a regression in local redaction of environments.

You can see it in your Local Server Info diff above: https://github.com/zed-industries/zed/pull/42831#issuecomment-3572106206 `STARSHIP_SESSION_KEY` is no longer redacted.

Potential fix in: 
- https://github.com/zed-industries/zed/pull/43480

**Comment by errmayank** [comment]
@notpeter - Totally missed that, my bad! I've added a comment on your PR.
