### PR TITLE
windows: Fix `eslint` installation

### LINKED ISSUE #13786: Windows: Tailwind CSS and LUA Language Server not working
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Tailwind Server along with the LUA Server doesn't start at all.

### Environment

Zed: v0.143.0 (Zed Dev)
OS: Windows 10.0.26244
Memory: 31.9 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T17:56:01+02:00 [INFO] add connection to peer
2024-07-03T17:56:01+02:00 [INFO] add_connection;
2024-07-03T17:56:01+02:00 [INFO] waiting for server hello
2024-07-03T17:56:01+02:00 [INFO] fetching latest version of language server "package-version-server"
2024-07-03T17:56:01+02:00 [INFO] fetching latest version of language server "vtsls"
2024-07-03T17:56:01+02:00 [INFO] got server hello
2024-07-03T17:56:01+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 451, id: 519823 })
2024-07-03T17:56:01+02:00 [INFO] set status on client 179875: Connected { peer_id: PeerId { owner_id: 451, id: 519823 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-03T17:56:01+02:00 [INFO] fetching latest version of language server "eslint"
2024-07-03T17:56:01+02:00 [INFO] downloading language server "eslint"
2024-07-03T17:56:01+02:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-07-03T17:56:01+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T17:56:01+02:00 [INFO] Creating texture 0x1e34b0ac520 of size 1024x1024x1 and format R8Unorm, name 'atlas', handle 0
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3404bdba0 of size 65536, name 'chunk-0', handle 1
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e34049cb20 of size 4096, name 'chunk-0', handle 2
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e34049ccb0 of size 29008, name 'chunk-1', handle 3
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e34049ce40 of size 9568, name 'chunk-2', handle 4
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e34049cfd0 of size 143920, name 'chunk-3', handle 5
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: 
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T17:56:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 6
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T17:56:01+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3d0dc6820 of size 110880, name 'chunk-4', handle 6
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3d0dc5d30 of size 64176, name 'chunk-5', handle 7
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3d0dc5ba0 of size 7904, name 'chunk-6', handle 8
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3d0dc69b0 of size 33040, name 'chunk-7', handle 9
2024-07-03T17:56:01+02:00 [INFO] Creating buffer 0x1e3d0dc5ec0 of size 110880, name 'chunk-8', handle 10
2024-07-03T17:56:01+02:00 [INFO] downloading language server "package-version-server"
2024-07-03T17:56:01+02:00 [INFO] Creating texture 0x1e34b0af750 of size 1024x1024x1 and format Bgra8UnormSrgb, name 'atlas', handle 11
2024-07-03T17:56:02+02:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-07-03T17:56:02+02:00 [INFO] failed to fetch newest version of language server LanguageServerName("package-version-server"). falling back to using "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp"
2024-07-03T17:56:02+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:02+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:02+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:02+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T17:56:02+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T17:56:02+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:02+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T17:56:03+02:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-07-03T17:56:03+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:03+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:03+02:00 [WARN] test binary check failed
2024-07-03T17:56:03+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:03+02:00 [INFO] deleting server container
2024-07-03T17:56:03+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 7
2024-07-03T17:56:03+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:03+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:03+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:03+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T17:56:03+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:03+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:03+02:00 [WARN] test binary check failed
2024-07-03T17:56:03+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:03+02:00 [INFO] deleting server container
2024-07-03T17:56:03+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:03+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 8
2024-07-03T17:56:03+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T17:56:03+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:03+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T17:56:04+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:04+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:04+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:04+02:00 [WARN] test binary check failed
2024-07-03T17:56:04+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:04+02:00 [INFO] deleting server container
2024-07-03T17:56:04+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:04+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 9
2024-07-03T17:56:04+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:04+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:04+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:04+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T17:56:04+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:04+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:04+02:00 [WARN] test binary check failed
2024-07-03T17:56:04+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:04+02:00 [INFO] deleting server container
2024-07-03T17:56:04+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:04+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 10
2024-07-03T17:56:04+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T17:56:04+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:04+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T17:56:05+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:05+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:05+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:05+02:00 [WARN] test binary check failed
2024-07-03T17:56:05+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:05+02:00 [INFO] deleting server container
2024-07-03T17:56:05+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:05+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 11
2024-07-03T17:56:05+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:05+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:05+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:05+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T17:56:05+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:05+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:05+02:00 [WARN] test binary check failed
2024-07-03T17:56:05+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:05+02:00 [INFO] deleting server container
2024-07-03T17:56:05+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:05+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 12
2024-07-03T17:56:05+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T17:56:05+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:05+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T17:56:06+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:06+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:06+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:06+02:00 [WARN] test binary check failed
2024-07-03T17:56:06+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:06+02:00 [INFO] deleting server container
2024-07-03T17:56:06+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:06+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 13
2024-07-03T17:56:06+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:06+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T17:56:06+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:06+02:00 [ERROR] Hit 4 reinstallation attempts for "package-version-server"
2024-07-03T17:56:06+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:06+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:06+02:00 [WARN] test binary check failed
2024-07-03T17:56:06+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:06+02:00 [INFO] deleting server container
2024-07-03T17:56:06+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:06+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 14
2024-07-03T17:56:06+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T17:56:06+02:00 [ERROR] server stderr: Some("")
2024-07-03T17:56:06+02:00 [ERROR] Hit 4 reinstallation attempts for "lua-language-server"
2024-07-03T17:56:08+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:09+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:09+02:00 [INFO] downloading language server "json-language-server"
2024-07-03T17:56:10+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:10+02:00 [INFO] failed to fetch newest version of language server LanguageServerName("eslint"). falling back to using "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe"
2024-07-03T17:56:10+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T17:56:10+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:10+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:10+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T17:56:10+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:10+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T17:56:10+02:00 [ERROR] server shut down
2024-07-03T17:56:11+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\json-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-07-03T17:56:11+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:11+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:11+02:00 [INFO] downloading language server "tailwindcss-language-server"
2024-07-03T17:56:12+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:12+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:12+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:12+02:00 [WARN] test binary check failed
2024-07-03T17:56:12+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:12+02:00 [INFO] deleting server container
2024-07-03T17:56:12+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 15
2024-07-03T17:56:12+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T17:56:12+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:12+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T17:56:12+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:12+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T17:56:12+02:00 [ERROR] server shut down
2024-07-03T17:56:13+02:00 [INFO] downloading language server "vtsls"
2024-07-03T17:56:13+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:13+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:13+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:13+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:13+02:00 [WARN] test binary check failed
2024-07-03T17:56:13+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:13+02:00 [INFO] deleting server container
2024-07-03T17:56:13+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:13+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 16
2024-07-03T17:56:13+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T17:56:13+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:13+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T17:56:13+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:13+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T17:56:13+02:00 [ERROR] server shut down
2024-07-03T17:56:13+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\vtsls\\node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2024-07-03T17:56:14+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:14+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:14+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:14+02:00 [WARN] test binary check failed
2024-07-03T17:56:14+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:14+02:00 [INFO] deleting server container
2024-07-03T17:56:14+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:14+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 17
2024-07-03T17:56:14+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T17:56:14+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:14+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T17:56:14+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:14+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T17:56:14+02:00 [ERROR] server shut down
2024-07-03T17:56:15+02:00 [INFO] Node runtime install_if_needed
2024-07-03T17:56:15+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:15+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:15+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:15+02:00 [WARN] test binary check failed
2024-07-03T17:56:15+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:15+02:00 [INFO] deleting server container
2024-07-03T17:56:15+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:15+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 18
2024-07-03T17:56:15+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T17:56:15+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:15+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T17:56:15+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n")
2024-07-03T17:56:15+02:00 [ERROR] Hit 4 reinstallation attempts for "eslint"
2024-07-03T17:56:15+02:00 [ERROR] server shut down
2024-07-03T17:56:15+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T17:56:15+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:15+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T17:56:15+02:00 [ERROR] server stderr: Some("C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server:2\r\nbasedir=$(dirname \"$(echo \"$0\" | sed -e 's,\\\\,/,g')\")\r\n          ^^^^^^^\r\n\r\nSyntaxError: missing ) after argument list\r\n    at internalCompileFunction (node:internal/vm:73:18)\r\n    at wrapSafe (node:internal/modules/cjs/loader:1176:20)\r\n    at Module._compile (node:internal/modules/cjs/loader:1218:27)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\r\n    at Module._load (node:internal/modules/cjs/loader:958:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:15+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T17:56:15+02:00 [ERROR] The pipe is being closed. (os error 232)
2024-07-03T17:56:15+02:00 [ERROR] server shut down
2024-07-03T17:56:16+02:00 [ERROR] missing executable in directory "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules"
2024-07-03T17:56:16+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:16+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:16+02:00 [WARN] test binary check failed
2024-07-03T17:56:16+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:16+02:00 [INFO] deleting server container
2024-07-03T17:56:16+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 19
2024-07-03T17:56:16+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T17:56:16+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:16+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T17:56:16+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:16+02:00 [ERROR] server shut down
2024-07-03T17:56:16+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T17:56:17+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:17+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:17+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:17+02:00 [WARN] test binary check failed
2024-07-03T17:56:17+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:17+02:00 [INFO] deleting server container
2024-07-03T17:56:17+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:17+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 20
2024-07-03T17:56:17+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T17:56:17+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:17+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T17:56:17+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:17+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T17:56:17+02:00 [ERROR] server shut down
2024-07-03T17:56:18+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:18+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:18+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:18+02:00 [WARN] test binary check failed
2024-07-03T17:56:18+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:18+02:00 [INFO] deleting server container
2024-07-03T17:56:18+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:18+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 21
2024-07-03T17:56:18+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T17:56:18+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:18+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T17:56:18+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T17:56:18+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T17:56:18+02:00 [ERROR] server shut down
2024-07-03T17:56:19+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T17:56:19+02:00 [INFO] About to spawn test binary
2024-07-03T17:56:19+02:00 [WARN] test binary failed to launch
2024-07-03T17:56:19+02:00 [WARN] test binary check failed
2024-07-03T17:56:19+02:00 [INFO] beginning to reinstall server
2024-07-03T17:56:19+02:00 [INFO] deleting server container
2024-07-03T17:56:19+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T17:56:19+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 22
2024-07-03T17:56:19+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T17:56:19+02:00 [ERROR] cannot read LSP message headers
2024-07-03T17:56:19+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T17:56:19+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n")
2024-07-03T17:56:19+02:00 [ERROR] Hit 4 reinstallation attempts for "tailwindcss-language-server"
2024-07-03T17:56:19+02:00 [ERROR] server shut down
2024-07-03T17:57:19+02:00 [INFO] Creating buffer 0x1e340cf1a80 of size 112336, name 'chunk-9', handle 12
2024-07-03T17:57:20+02:00 [INFO] Creating texture 0x1e34b0af2c0 of size 1024x1024x1 and format R16Float, name 'atlas', handle 13
2024-07-03T17:57:21+02:00 [INFO] Creating buffer 0x1e3cc8115a0 of size 126896, name 'chunk-10', handle 14
2024-07-03T17:57:23+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T17:57:23+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T17:57:23+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-03T17:57:23+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-03T17:57:28+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T17:57:28+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T17:58:51+02:00 [INFO] Creating buffer 0x1e3cc2c4340 of size 146720, name 'chunk-11', handle 15
2024-07-03T17:58:51+02:00 [INFO] Creating buffer 0x1e3d0e7d500 of size 146720, name 'chunk-12', handle 16
2024-07-03T17:58:51+02:00 [INFO] Creating buffer 0x1e3cc6156e0 of size 171920, name 'chunk-13', handle 17
2024-07-03T17:58:51+02:00 [INFO] Creating buffer 0x1e3cc6153c0 of size 171920, name 'chunk-14', handle 18
2024-07-03T17:58:52+02:00 [INFO] Creating buffer 0x1e3cc5f7600 of size 176176, name 'chunk-15', handle 19
2024-07-03T17:58:52+02:00 [INFO] Creating buffer 0x1e3cc5f7150 of size 178080, name 'chunk-16', handle 20
2024-07-03T17:58:52+02:00 [INFO] Creating buffer 0x1e3cc5f72e0 of size 183568, name 'chunk-17', handle 21
2024-07-03T17:58:52+02:00 [INFO] Creating buffer 0x1e34057d7e0 of size 185360, name 'chunk-18', handle 22
2024-07-03T18:02:40+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-07-03T18:02:42+02:00 [INFO] Creating texture 0x1e3cc2e4340 of size 1630x1024x1 and format R16Float, name 'atlas', handle 23
2024-07-03T18:05:29+02:00 [INFO] Destroying texture 0x1e34b0ac520, handle 0
2024-07-03T18:05:29+02:00 [INFO] Destroying texture 0x1e34b0af750, handle 11
2024-07-03T18:05:29+02:00 [INFO] Destroying texture 0x1e34b0af2c0, handle 13
2024-07-03T18:05:29+02:00 [INFO] Destroying texture 0x1e3cc2e4340, handle 23
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3404bdba0, handle 1
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e34049cb20, handle 2
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e340cf1a80, handle 12
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e34049ce40, handle 4
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc8115a0, handle 14
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc6153c0, handle 18
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0dc5ec0, handle 10
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0dc5ba0, handle 8
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0dc5d30, handle 7
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc5f7600, handle 19
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0dc6820, handle 6
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e34049ccb0, handle 3
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e34057d7e0, handle 22
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc5f72e0, handle 21
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc5f7150, handle 20
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e34049cfd0, handle 5
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc2c4340, handle 15
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0dc69b0, handle 9
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3d0e7d500, handle 16
2024-07-03T18:05:29+02:00 [INFO] Destroying buffer 0x1e3cc6156e0, handle 17
2024-07-03T18:05:29+02:00 [ERROR] window not found
2024-07-03T18:05:29+02:00 [ERROR] error upgrading view
2024-07-03T18:05:29+02:00 [ERROR] error upgrading view
2024-07-03T18:05:29+02:00 2024-07-03T18:05:31+02:00 [INFO] ========== starting zed ==========
2024-07-03T18:05:31+02:00 [INFO] Use Segoe UI as UI font.
2024-07-03T18:05:31+02:00 [INFO] Using direct write text system.
2024-07-03T18:05:31+02:00 [INFO] Opening main db
2024-07-03T18:05:31+02:00 [INFO] Using git binary path: None
2024-07-03T18:05:31+02:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-07-03T18:05:31+02:00 [ERROR] SHELL environment variable is not assigned so we can't source login environment variables

Caused by:
    environment variable not found
2024-07-03T18:05:32+02:00 [ERROR] theme not found: macOS Classic Dark
2024-07-03T18:05:32+02:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-07-03T18:05:32+02:00 [INFO] Opening main db
2024-07-03T18:05:32+02:00 [INFO] set status on client 0: Authenticating
2024-07-03T18:05:32+02:00 [INFO] set status on client 179875: Connecting
2024-07-03T18:05:32+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-07-03T18:05:32+02:00 [WARN] Theme "macOS Classic Light" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "macOS Classic Dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "macOS Classic Dark2" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [INFO] Enabling Vulkan Portability
2024-07-03T18:05:32+02:00 [INFO] Enabling color space support
2024-07-03T18:05:32+02:00 [INFO] Adapter "NVIDIA GeForce GTX 1650"
2024-07-03T18:05:32+02:00 [INFO] No ray tracing extensions are supported
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark-6000k" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark-6000k-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark-twilight" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Theme "msun-dark-twilight-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:32+02:00 [WARN] Requested size 1x1 is outside of surface capabilities
2024-07-03T18:05:32+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:32+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:05:32+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:05:32+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position_impl")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position_transformed")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("blend_color")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position_impl")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_device_position_transformed")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:32+02:00 [INFO] Skip function Some("blend_color")
2024-07-03T18:05:32+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:32+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:32+02:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-07-03T18:05:32+02:00 [INFO] Opening main db
2024-07-03T18:05:32+02:00 [INFO] Opening main db
2024-07-03T18:05:32+02:00 [INFO] Using Windows API for pseudoconsole
2024-07-03T18:05:32+02:00 [INFO] Using Windows API for pseudoconsole
2024-07-03T18:05:32+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:32+02:00 [INFO] Creating texture 0x1d5cfdcc170 of size 1024x1024x1 and format R8Unorm, name 'atlas', handle 0
2024-07-03T18:05:32+02:00 [INFO] Creating buffer 0x1d5d025cb90 of size 65536, name 'chunk-0', handle 1
2024-07-03T18:05:32+02:00 [INFO] Creating buffer 0x1d5d025ca00 of size 4096, name 'chunk-0', handle 2
2024-07-03T18:05:32+02:00 [INFO] Creating buffer 0x1d5d025e170 of size 23856, name 'chunk-1', handle 3
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] starting language server "json-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 1
2024-07-03T18:05:32+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 2
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] fetching latest version of language server "json-language-server"
2024-07-03T18:05:32+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:32+02:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-03T18:05:32+02:00 [INFO] fetching latest version of language server "package-version-server"
2024-07-03T18:05:32+02:00 [INFO] Creating buffer 0x1d5d025b420 of size 31360, name 'chunk-2', handle 4
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language server "vtsls", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 3
2024-07-03T18:05:32+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 4
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] fetching latest version of language server "vtsls"
2024-07-03T18:05:32+02:00 [INFO] add connection to peer
2024-07-03T18:05:32+02:00 [INFO] add_connection;
2024-07-03T18:05:32+02:00 [INFO] waiting for server hello
2024-07-03T18:05:32+02:00 [INFO] fetching latest version of language server "eslint"
2024-07-03T18:05:32+02:00 [INFO] downloading language server "eslint"
2024-07-03T18:05:32+02:00 [INFO] got server hello
2024-07-03T18:05:32+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 451, id: 524648 })
2024-07-03T18:05:32+02:00 [INFO] set status on client 179875: Connected { peer_id: PeerId { owner_id: 451, id: 524648 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:32+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 5
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] downloading language server "package-version-server"
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 6
2024-07-03T18:05:32+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:32+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:32+02:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for JSON: json-language-server, package-version-server
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for TypeScript: vtsls, eslint
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] Creating texture 0x1d54bf3a780 of size 1024x1024x1 and format Bgra8UnormSrgb, name 'atlas', handle 5
2024-07-03T18:05:33+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T18:05:33+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:33+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T18:05:33+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:05:33+02:00 [INFO] starting language servers for Lua: lua-language-server
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407acaa0 of size 32704, name 'chunk-3', handle 6
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ad720 of size 134736, name 'chunk-4', handle 7
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407abe20 of size 4096, name 'chunk-5', handle 8
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ad0e0 of size 32704, name 'chunk-6', handle 9
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ab650 of size 8632, name 'chunk-7', handle 10
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ae3a0 of size 27440, name 'chunk-8', handle 11
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ab330 of size 134736, name 'chunk-9', handle 12
2024-07-03T18:05:33+02:00 [INFO] Creating buffer 0x1d5407ae210 of size 162176, name 'chunk-10', handle 13
2024-07-03T18:05:33+02:00 [INFO] failed to fetch newest version of language server LanguageServerName("package-version-server"). falling back to using "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp"
2024-07-03T18:05:33+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:33+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:33+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:33+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T18:05:34+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:34+02:00 [INFO] Creating buffer 0x1d5407ac780 of size 162176, name 'chunk-11', handle 14
2024-07-03T18:05:34+02:00 [INFO] Creating buffer 0x1d5407aae80 of size 162288, name 'chunk-12', handle 15
2024-07-03T18:05:34+02:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-07-03T18:05:34+02:00 [INFO] downloading language server "json-language-server"
2024-07-03T18:05:34+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:34+02:00 [INFO] About to spawn test binary
2024-07-03T18:05:34+02:00 [WARN] test binary failed to launch
2024-07-03T18:05:34+02:00 [WARN] test binary check failed
2024-07-03T18:05:34+02:00 [INFO] beginning to reinstall server
2024-07-03T18:05:34+02:00 [INFO] deleting server container
2024-07-03T18:05:34+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:05:34+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 7
2024-07-03T18:05:34+02:00 [INFO] Creating texture 0x1d54bf41500 of size 1024x1024x1 and format R16Float, name 'atlas', handle 16
2024-07-03T18:05:34+02:00 [INFO] About to spawn test binary
2024-07-03T18:05:34+02:00 [WARN] test binary failed to launch
2024-07-03T18:05:34+02:00 [WARN] test binary check failed
2024-07-03T18:05:34+02:00 [INFO] beginning to reinstall server
2024-07-03T18:05:34+02:00 [INFO] deleting server container
2024-07-03T18:05:34+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 8
2024-07-03T18:05:34+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:34+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:34+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:34+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T18:05:35+02:00 [INFO] failed to fetch newest version of language server LanguageServerName("eslint"). falling back to using "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe"
2024-07-03T18:05:35+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:05:35+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:35+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T18:05:35+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:35+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T18:05:35+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:05:35+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:05:35+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:05:35+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T18:05:35+02:00 [ERROR] server shut down
2024-07-03T18:05:35+02:00 [INFO] downloading language server "tailwindcss-language-server"
2024-07-03T18:05:35+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\json-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-07-03T18:05:35+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:36+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:05:36+02:00 [INFO] About to spawn test binary
2024-07-03T18:05:36+02:00 [WARN] test binary failed to launch
2024-07-03T18:05:36+02:00 [WARN] test binary check failed
2024-07-03T18:05:36+02:00 [INFO] beginning to reinstall server
2024-07-03T18:05:36+02:00 [INFO] deleting server container
2024-07-03T18:05:36+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:05:36+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 9
2024-07-03T18:05:36+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:36+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:36+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:36+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T18:05:36+02:00 [INFO] Creating buffer 0x1d5407aacf0 of size 174160, name 'chunk-13', handle 17
2024-07-03T18:05:36+02:00 [INFO] About to spawn test binary
2024-07-03T18:05:36+02:00 [WARN] test binary failed to launch
2024-07-03T18:05:36+02:00 [WARN] test binary check failed
2024-07-03T18:05:36+02:00 [INFO] beginning to reinstall server
2024-07-03T18:05:36+02:00 [INFO] deleting server container
2024-07-03T18:05:36+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:05:36+02:00 [INFO] starting language server "lua-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 10
2024-07-03T18:05:36+02:00 [ERROR] failed to start language server "lua-language-server": no asset found matching "lua-language-server-3.9.3-win32-x64.tar.gz"
2024-07-03T18:05:36+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:36+02:00 [INFO] retrying installation of language server "lua-language-server" in 1s
2024-07-03T18:05:36+02:00 [INFO] Creating buffer 0x1d5407ad270 of size 163968, name 'chunk-14', handle 18
2024-07-03T18:05:36+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:05:37+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:05:37+02:00 [INFO] About to spawn test binary
2024-07-03T18:05:37+02:00 [WARN] test binary failed to launch
2024-07-03T18:05:37+02:00 [WARN] test binary check failed
2024-07-03T18:05:37+02:00 [INFO] beginning to reinstall server
2024-07-03T18:05:37+02:00 [INFO] deleting server container
2024-07-03T18:05:37+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:05:37+02:00 [INFO] starting language server "package-version-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 11
2024-07-03T18:05:37+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:37+02:00 [ERROR] failed to start language server "package-version-server": failed to spawn command. path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\package-version-server\\package-version-server-v0.0.1-tmp", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: []
2024-07-03T18:05:37+02:00 [ERROR] server stderr: Some("")
2024-07-03T18:05:37+02:00 [INFO] retrying installation of language server "package-version-server" in 1s
2024-07-03T18:05:37+02:00 [INFO] Destroying texture 0x1d5cfdcc170, handle 0
2024-07-03T18:05:37+02:00 [INFO] Destroying texture 0x1d54bf3a780, handle 5
2024-07-03T18:05:37+02:00 [INFO] Destroying texture 0x1d54bf41500, handle 16
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5d025cb90, handle 1
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5d025ca00, handle 2
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407acaa0, handle 6
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407aae80, handle 15
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5d025e170, handle 3
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ae210, handle 13
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5d025b420, handle 4
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ad720, handle 7
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407abe20, handle 8
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ac780, handle 14
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ab650, handle 10
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407aacf0, handle 17
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ad0e0, handle 9
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ab330, handle 12
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ae3a0, handle 11
2024-07-03T18:05:37+02:00 [INFO] Destroying buffer 0x1d5407ad270, handle 18
2024-07-03T18:05:37+02:00 [ERROR] window not found
2024-07-03T18:05:37+02:00 [ERROR] oneshot canceled
2024-07-03T18:05:37+02:00 [ERROR] timed out waiting on app_will_quit
2024-07-03T18:05:37+02:00 [ERROR] 2024-07-03T18:05:38+02:00 [INFO] ========== starting zed ==========
2024-07-03T18:05:39+02:00 [INFO] Use Segoe UI as UI font.
2024-07-03T18:05:39+02:00 [INFO] Using direct write text system.
2024-07-03T18:05:39+02:00 [INFO] Opening main db
2024-07-03T18:05:39+02:00 [INFO] Using git binary path: None
2024-07-03T18:05:39+02:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-07-03T18:05:39+02:00 [ERROR] SHELL environment variable is not assigned so we can't source login environment variables

Caused by:
    environment variable not found
2024-07-03T18:05:39+02:00 [ERROR] theme not found: macOS Classic Dark
2024-07-03T18:05:39+02:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-07-03T18:05:39+02:00 [INFO] Opening main db
2024-07-03T18:05:39+02:00 [INFO] set status on client 0: Authenticating
2024-07-03T18:05:39+02:00 [INFO] set status on client 179875: Connecting
2024-07-03T18:05:39+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-07-03T18:05:39+02:00 [WARN] Theme "macOS Classic Light" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "macOS Classic Dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "macOS Classic Dark2" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [INFO] Enabling Vulkan Portability
2024-07-03T18:05:39+02:00 [INFO] Enabling color space support
2024-07-03T18:05:39+02:00 [INFO] Adapter "NVIDIA GeForce GTX 1650"
2024-07-03T18:05:39+02:00 [INFO] No ray tracing extensions are supported
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark-6000k" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark-6000k-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark-twilight" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Theme "msun-dark-twilight-nobold" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-07-03T18:05:39+02:00 [WARN] Requested size 1x1 is outside of surface capabilities
2024-07-03T18:05:39+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:39+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:05:39+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:05:39+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position_impl")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position_transformed")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("blend_color")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position_impl")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_device_position_transformed")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("to_tile_position")
2024-07-03T18:05:39+02:00 [INFO] Skip function Some("blend_color")
2024-07-03T18:05:39+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:39+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:39+02:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-07-03T18:05:39+02:00 [INFO] Using surface present mode MAILBOX
2024-07-03T18:05:39+02:00 [INFO] Creating texture 0x21997b5b750 of size 1024x1024x1 and format R8Unorm, name 'atlas', handle 0
2024-07-03T18:05:39+02:00 [INFO] Creating buffer 0x21a5b5b09a0 of size 65536, name 'chunk-0', handle 1
2024-07-03T18:05:39+02:00 [INFO] Creating buffer 0x21a5b5b0b30 of size 4096, name 'chunk-0', handle 2
2024-07-03T18:05:39+02:00 [INFO] Creating buffer 0x21a5b5b0cc0 of size 4096, name 'chunk-1', handle 3
2024-07-03T18:05:39+02:00 [INFO] Opening main db
2024-07-03T18:05:39+02:00 [INFO] Using Windows API for pseudoconsole
2024-07-03T18:05:39+02:00 [INFO] Using Windows API for pseudoconsole
2024-07-03T18:05:39+02:00 [INFO] Creating buffer 0x21993024770 of size 23856, name 'chunk-2', handle 4
2024-07-03T18:05:39+02:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-03T18:05:39+02:00 [INFO] add connection to peer
2024-07-03T18:05:39+02:00 [INFO] add_connection;
2024-07-03T18:05:39+02:00 [INFO] waiting for server hello
2024-07-03T18:05:39+02:00 [INFO] got server hello
2024-07-03T18:05:39+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 451, id: 524699 })
2024-07-03T18:05:39+02:00 [INFO] set status on client 179875: Connected { peer_id: PeerId { owner_id: 451, id: 524699 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-03T18:05:40+02:00 [INFO] Creating texture 0x21997b5c500 of size 1024x1024x1 and format Bgra8UnormSrgb, name 'atlas', handle 5
2024-07-03T18:05:59+02:00 [INFO] Creating buffer 0x21a5b9b89a0 of size 23184, name 'chunk-3', handle 6
2024-07-03T18:06:00+02:00 [INFO] Creating buffer 0x21a5bcc9f40 of size 29344, name 'chunk-4', handle 7
2024-07-03T18:06:01+02:00 [INFO] Creating buffer 0x21a5bc0b3a0 of size 50624, name 'chunk-5', handle 8
2024-07-03T18:06:02+02:00 [INFO] Creating buffer 0x21a5b561c50 of size 53536, name 'chunk-6', handle 9
2024-07-03T18:06:04+02:00 [INFO] Opening main db
2024-07-03T18:06:04+02:00 [INFO] Creating buffer 0x21997c960e0 of size 55552, name 'chunk-7', handle 10
2024-07-03T18:06:04+02:00 [INFO] Creating buffer 0x21997c95f50 of size 76720, name 'chunk-8', handle 11
2024-07-03T18:06:04+02:00 [INFO] Creating buffer 0x21a5b9a37c0 of size 77504, name 'chunk-9', handle 12
2024-07-03T18:06:04+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:06:04+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:06:04+02:00 [INFO] starting language server "vtsls", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 1
2024-07-03T18:06:04+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 2
2024-07-03T18:06:04+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 3
2024-07-03T18:06:04+02:00 [INFO] Initializing default prettier with plugins {}
2024-07-03T18:06:04+02:00 [INFO] starting language servers for TSX: vtsls, tailwindcss-language-server, eslint
2024-07-03T18:06:04+02:00 [INFO] fetching latest version of language server "vtsls"
2024-07-03T18:06:04+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:04+02:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-07-03T18:06:04+02:00 [INFO] fetching latest version of language server "eslint"
2024-07-03T18:06:04+02:00 [INFO] downloading language server "eslint"
2024-07-03T18:06:04+02:00 [INFO] Creating buffer 0x21980630dd0 of size 60480, name 'chunk-10', handle 13
2024-07-03T18:06:04+02:00 [INFO] Creating buffer 0x21980630470 of size 76720, name 'chunk-11', handle 14
2024-07-03T18:06:04+02:00 [INFO] Creating texture 0x21997b5e4f0 of size 1024x1024x1 and format R16Float, name 'atlas', handle 15
2024-07-03T18:06:04+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:06:04+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-03T18:06:04+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-03T18:06:04+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-03T18:06:05+02:00 [INFO] Creating buffer 0x21a5b488160 of size 76608, name 'chunk-12', handle 16
2024-07-03T18:06:05+02:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-07-03T18:06:05+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:05+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:06+02:00 [INFO] failed to fetch newest version of language server LanguageServerName("eslint"). falling back to using "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe"
2024-07-03T18:06:06+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:06:06+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:06+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:06+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:06:06+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:06+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T18:06:06+02:00 [ERROR] server shut down
2024-07-03T18:06:06+02:00 [INFO] downloading language server "tailwindcss-language-server"
2024-07-03T18:06:06+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:07+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:07+02:00 [INFO] downloading language server "vtsls"
2024-07-03T18:06:08+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:08+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:08+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:08+02:00 [WARN] test binary check failed
2024-07-03T18:06:08+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:08+02:00 [INFO] deleting server container
2024-07-03T18:06:08+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 4
2024-07-03T18:06:08+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:06:08+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:08+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:06:08+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:08+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T18:06:08+02:00 [ERROR] server shut down
2024-07-03T18:06:08+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\vtsls\\node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]
2024-07-03T18:06:09+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:09+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:09+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:09+02:00 [WARN] test binary check failed
2024-07-03T18:06:09+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:09+02:00 [INFO] deleting server container
2024-07-03T18:06:09+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:09+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 5
2024-07-03T18:06:09+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:06:09+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:09+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:06:09+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:09+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T18:06:09+02:00 [ERROR] The pipe is being closed. (os error 232)
2024-07-03T18:06:09+02:00 [ERROR] server shut down
2024-07-03T18:06:09+02:00 [INFO] Node runtime install_if_needed
2024-07-03T18:06:10+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:10+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:10+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:10+02:00 [WARN] test binary check failed
2024-07-03T18:06:10+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:10+02:00 [INFO] deleting server container
2024-07-03T18:06:10+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:10+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 6
2024-07-03T18:06:10+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:06:10+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:10+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:06:10+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint\\server\\out\\eslintServer.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:10+02:00 [INFO] retrying installation of language server "eslint" in 1s
2024-07-03T18:06:10+02:00 [ERROR] server shut down
2024-07-03T18:06:10+02:00 [ERROR] The pipe is being closed. (os error 232)
2024-07-03T18:06:10+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T18:06:10+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:10+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T18:06:10+02:00 [ERROR] server stderr: Some("C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server:2\r\nbasedir=$(dirname \"$(echo \"$0\" | sed -e 's,\\\\,/,g')\")\r\n          ^^^^^^^\r\n\r\nSyntaxError: missing ) after argument list\r\n    at internalCompileFunction (node:internal/vm:73:18)\r\n    at wrapSafe (node:internal/modules/cjs/loader:1176:20)\r\n    at Module._compile (node:internal/modules/cjs/loader:1218:27)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\r\n    at Module._load (node:internal/modules/cjs/loader:958:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:10+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T18:06:10+02:00 [ERROR] server shut down
2024-07-03T18:06:11+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:11+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:11+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:11+02:00 [WARN] test binary check failed
2024-07-03T18:06:11+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:11+02:00 [INFO] deleting server container
2024-07-03T18:06:11+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:11+02:00 [INFO] starting language server "eslint", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 7
2024-07-03T18:06:11+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\eslint\\vscode-eslint-release\\vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-07-03T18:06:11+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:11+02:00 [ERROR] failed to start language server "eslint": oneshot canceled
2024-07-03T18:06:11+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n")
2024-07-03T18:06:11+02:00 [ERROR] Hit 4 reinstallation attempts for "eslint"
2024-07-03T18:06:11+02:00 [ERROR] server shut down
2024-07-03T18:06:11+02:00 [ERROR] missing executable in directory "C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules"
2024-07-03T18:06:11+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:11+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:11+02:00 [WARN] test binary check failed
2024-07-03T18:06:11+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:11+02:00 [INFO] deleting server container
2024-07-03T18:06:11+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 8
2024-07-03T18:06:11+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T18:06:11+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:11+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T18:06:11+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:11+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T18:06:11+02:00 [ERROR] server shut down
2024-07-03T18:06:12+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:12+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:12+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:12+02:00 [WARN] test binary check failed
2024-07-03T18:06:12+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:12+02:00 [INFO] deleting server container
2024-07-03T18:06:12+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:12+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 9
2024-07-03T18:06:12+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T18:06:12+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:12+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T18:06:12+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:12+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T18:06:12+02:00 [ERROR] server shut down
2024-07-03T18:06:13+02:00 [INFO] Creating buffer 0x21a5b135b10 of size 83440, name 'chunk-13', handle 17
2024-07-03T18:06:13+02:00 [INFO] Creating buffer 0x21a5b135ca0 of size 83440, name 'chunk-14', handle 18
2024-07-03T18:06:13+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:13+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:13+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:13+02:00 [WARN] test binary check failed
2024-07-03T18:06:13+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:13+02:00 [INFO] deleting server container
2024-07-03T18:06:13+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:13+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 10
2024-07-03T18:06:13+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T18:06:13+02:00 [INFO] Creating buffer 0x21a5b487fd0 of size 83552, name 'chunk-15', handle 19
2024-07-03T18:06:13+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:13+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T18:06:13+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:13+02:00 [INFO] retrying installation of language server "tailwindcss-language-server" in 1s
2024-07-03T18:06:13+02:00 [ERROR] server shut down
2024-07-03T18:06:14+02:00 [ERROR] The system cannot find the path specified. (os error 3)
2024-07-03T18:06:14+02:00 [INFO] About to spawn test binary
2024-07-03T18:06:14+02:00 [WARN] test binary failed to launch
2024-07-03T18:06:14+02:00 [WARN] test binary check failed
2024-07-03T18:06:14+02:00 [INFO] beginning to reinstall server
2024-07-03T18:06:14+02:00 [INFO] deleting server container
2024-07-03T18:06:14+02:00 [ERROR] server container removal

Caused by:
    The system cannot find the file specified. (os error 2)
2024-07-03T18:06:14+02:00 [INFO] starting language server "tailwindcss-language-server", path: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", id: 11
2024-07-03T18:06:14+02:00 [INFO] starting language server. binary path: "C:\\Users\\vipex\\AppData\\Local\\Zed\\node\\node-v18.15.0-win-x64\\node.exe", working directory: "C:\\Users\\vipex\\Desktop\\testserver-esx\\data\\resources\\[core]\\esx_multicharacter", args: ["C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-07-03T18:06:14+02:00 [INFO] Creating buffer 0x21a5b30e430 of size 83552, name 'chunk-16', handle 20
2024-07-03T18:06:14+02:00 [ERROR] cannot read LSP message headers
2024-07-03T18:06:14+02:00 [ERROR] failed to start language server "tailwindcss-language-server": oneshot canceled
2024-07-03T18:06:14+02:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1078\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\Users\\vipex\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules\\.bin\\tailwindcss-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\r\n    at Module._load (node:internal/modules/cjs/loader:920:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.15.0\r\n")
2024-07-03T18:06:14+02:00 [ERROR] Hit 4 reinstallation attempts for "tailwindcss-language-server"
2024-07-03T18:06:14+02:00 [ERROR] server shut down
</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Close #13786. To make `eslint` running on Windows, I made the following changes:

1. Ensure that `zed` downloads the `.zip` file.
2. Handle the `$shared` symbolic link by copying files to the link location.
3. In #13891, I mentioned that the `npm` `post-install` script was always failing. After debugging, I found it was due to missing environment variables. This has been fixed, and I will submit a new PR to address the changes in #13891.

With this PR, `eslint` can now successfully run on Windows. Video:

https://github.com/user-attachments/assets/e85451b8-0388-490a-8a75-01c12d744f7c

Release Notes:

- Fixed `eslint` not running on Windows ([#13786](https://github.com/zed-industries/zed/issues/13786)).

### CODE REVIEW

File: crates/http_client/src/github.rs [hunk 1]
```diff
@@ -123,7 +124,10 @@ pub fn build_tarball_url(repo_name_with_owner: &str, tag: &str) -> Result<String
     ))?;
     // We're pushing this here, because tags may contain `/` and other characters
     // that need to be escaped.
+    #[cfg(not(target_os = "windows"))]
     let tarball_filename = format!("{}.tar.gz", tag);
+    #[cfg(target_os = "windows")]
+    let tarball_filename = format!("{}.zip", tag);
```
Comment (maxdeviant) [inline crates/http_client/src/github.rs:130]: With this change the name of the function is no longer accurate, as `.zip` files are not tarballs.

Comment (JunkuiZhang) [reply crates/http_client/src/github.rs:130]: Since my poor English skills, do you have any suggestions for a better name?

Comment (JunkuiZhang) [reply crates/http_client/src/github.rs]: I see you are handling this, thanks!

**Review by maxdeviant — APPROVED** [review]
Thanks!
