### PR TITLE
editor: Refactor scrollbar-related code

### LINKED ISSUE #22610: Scrollbar disappears in large files
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Create a large test file (like 100k lines) for example width:
```bash
python3 -c "print('flofriday\n' * (10**5)) " > 100k.txt
```
and open it in Zed.

While you can still click the scrollbar and the track is still shown, the thumb is no longer visible. 
I assume this is because the thumb gets smaller as the files get larger and at some point it becomes so small that it is below 1px in height.

With rapid scrolling I could sometimes see the thumb flickering in and out of existence (visible in a flashing 1px line).

### Zed Version and System Specs

Zed: v0.167.1 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

**Scrollbar with 100 and 100k lines**
Both files are scrolled torwards the middle of the document, but you would never know it from just looking at the larger one.
Screenshot 2025-01-03 at 12 49 48

**Scrollbar thumb flickering**
https://github.com/user-attachments/assets/c8f35e41-738a-465e-b560-8ca5084e3b6a

**Scrollbar with 100k and custom theme**
Some custom themes, like the GitHub dimmed in this example don't draw the border between the editor and the scrollbar track, making it even harder to know where to click when the thumb is missing.
Screenshot 2025-01-03 at 12 52 11

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by MrSubidubi**
This PR is primarily an implementation of @osiewicz [comment](https://github.com/zed-industries/zed/pull/19495#pullrequestreview-2488877957) in an effort to increase maintainability after the horizontal editor scrollbar was added in #19495 . I also want to build on these changes in future PRs to adress some other small bugs.

This primarily does the following:
1. Uses `along` wherever possible
2. Fixes the amount of mouse event listeners attached to the editor when scrollbars are displayed to 2 instead of 2-4 in case both scrollbars are displayed.

This can be done since only one scrollbar can be dragged by the cursor at any given time, so the event listeners now account for that. The state reflecting the scrollbar dragging state was also updated accordingly.

It does not change any functionality besides the aforementioned event listener code as well as some minor bugs which where present after #19495 , namely: 
- One missing `cx.stop_propagation()` (see [here](https://github.com/zed-industries/zed/blob/a8741dc3107a205ba5a28aa8c3e18747ceed2ba3/crates/editor/src/element.rs#L4684) and [here](https://github.com/zed-industries/zed/blob/a8741dc3107a205ba5a28aa8c3e18747ceed2ba3/crates/editor/src/element.rs#L4838) respectively).
- The horizontal scrollbar thumb having a small border on the left side, which seems to be unintended for the horizontal scrollbar whilst intended for the vertical one. Since this is a minimal change, I figured it could be already included in this PR.

This PR admittetly grew quite large over time, however, much of the diff is just renames to account for the code now working for both axes as well as moved code. The logic remains (or should at least be) unaffected. If I should split this into two PRs or remove some of the changes, please let me know.

Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
> Net negative 200 lines of code

Nice!

File: crates/editor/src/element.rs [hunk 1]
```diff
@@ -7818,46 +7554,174 @@ struct ColoredRange<T> {
...
+
+    fn along(&self, axis: ScrollbarAxis) -> Self::Unit {
+        match axis {
+            ScrollbarAxis::Horizontal => self.horizontal,
+            ScrollbarAxis::Vertical => self.vertical,
+        }
+    }
+
+    fn apply_along(&self, _axis: ScrollbarAxis, _f: impl FnOnce(Self::Unit) -> Self::Unit) -> Self {
+        unimplemented!()
```
Comment (osiewicz) [inline crates/editor/src/element.rs:7568]: This should probably be implemented, even if we don't end up using it.

Comment (MrSubidubi) [reply crates/editor/src/element.rs]: Done 👍

**Review by osiewicz — APPROVED** [review]
Sorry for the late review; LGTM (sans the conflicts)

**Comment by MrSubidubi** [comment]
No worries, thank you for your time and review! (And sorry for what was probably a nightmare to review 😅  )
