### PR TITLE
remote: Don’t pass `--method=GET` to `wget`

### LINKED ISSUE #38712: BusyBox's wget can't download Zed's Remote Development server
### Summary

Cannot download Zed's Remote Development server due to BusyBox's Wget not supporting the `--method` argument.

### Description

DESCRIPTION_HERE

Steps to reproduce:
1. Set up an ssh server in an alpine Linux environment (a podman container in my case), including all the auxiliary bells and whistles like `gcompat`, just in case
2. Attempt to use Zed's Remote Development feature

**Expected Behavior**: Zed editor connects to the environment via `ssh`, download the zed-server, extract & run it.
**Actual Behavior**: Zed editor connects to the environment via `ssh`, attempts to download the zed-server and fails with a _Failed to open project: failed to upload server binary_ messages. Checking the log (attached), it seems that the `wget` which comes with `busybox` haven't a clue what `--method=GET` is supposed to do.

Installing the actual, full-fat `wget` solves the issues but I feel like we could have gotten away with just the `busybox` version had we get rid of `--method=GET` argument, which seems to be specified here:

https://github.com/zed-industries/zed/blob/15e75bdf04bfb2c4c22e2e42a354df38ec564b06/crates/remote/src/transport/ssh.rs#L540-L551

The other arguments seems to be supported.

<details><summary>Logs</summary>

```log
[...]
2025-09-23T19:21:45+07:00 INFO  [remote::transport::ssh] uploading remote development server to RemotePathBuf { inner: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz", style: Posix, string: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz" } (26869kb)
2025-09-23T19:21:45+07:00 ERROR [recent_projects::remote_connections] Failed to open project: failed to upload server binary
2025-09-23T19:21:48+07:00 INFO  [remote::transport::ssh] uploading remote development server to RemotePathBuf { inner: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz", style: Posix, string: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz" } (26869kb)
2025-09-23T19:21:48+07:00 ERROR [recent_projects::remote_connections] Failed to open project: failed to upload server binary
2025-09-23T19:21:48+07:00 INFO  [remote::transport::ssh] uploading remote development server to RemotePathBuf { inner: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz", style: Posix, string: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz" } (26869kb)
2025-09-23T19:21:48+07:00 ERROR [recent_projects::remote_connections] Failed to open project: failed to upload server binary
2025-09-23T19:22:10+07:00 ERROR [remote::transport::ssh] Failed to download binary on server, attempting to upload server: failed to run command: wget: unrecognized option: method=GET
BusyBox v1.36.1 (2024-06-10 07:11:47 UTC) multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	--header STR	Add STR (of form 'header: value') to headers
	--post-data STR	Send STR using POST method
	--post-file FILE	Send FILE using POST method
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-o LOGFILE	Log messages to FILE
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy

2025-09-23T19:22:10+07:00 INFO  [remote::transport::ssh] uploading remote development server to RemotePathBuf { inner: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz", style: Posix, string: ".zed_server/zed-remote-server-stable-0.204.5-download-14957.gz" } (26869kb)
2025-09-23T19:22:10+07:00 ERROR [recent_projects::remote_connections] Failed to open project: failed to upload server binary
```
</details>

### Zed Version and System Specs

Zed: v0.204.5 (Zed) 
OS: Linux Wayland [redacted] 22.04
Memory: 7 GiB
Architecture: x86_64
GPU: AMD Radeon 660M (RADV REMBRANDT) || radv || Mesa 25.1.5-1[redacted]

### PR DESCRIPTION
**Pull request by qjtdsqqm94akkyysgjdqo3hx1jn6l17**
BusyBox's off brand `wget` does not have support for the `--method` argument, which makes `zed` incapable of downloading the remote server unless the _☙authentic❧_ one is installed. Removing this should fix the issue. Couldn't find much about guidelines on how the code is supposed to be formatted, so I opted for commenting the line out with an explanation.

Closes #38712

Release Notes:

- Fixed remote development on BusyBox

### CODE REVIEW

**Comment by qjtdsqqm94akkyysgjdqo3hx1jn6l17** [comment]
@cla-bot check

File: crates/remote/src/transport/ssh.rs [hunk 1]
```diff
@@ -548,7 +548,7 @@ impl SshRemoteConnection {
                     .run_command(
                         "wget",
                         &[
-                            "--method=GET",
+                            // "--method=GET", // BusyBox's version of wget does NOT have support for this option
```
Comment (maxdeviant) [inline crates/remote/src/transport/ssh.rs]: We shouldn’t leave commented-out code in the repo.

Comment (qjtdsqqm94akkyysgjdqo3hx1jn6l17) [reply crates/remote/src/transport/ssh.rs]: Understood, should I leave a note like so:
```rust
                        // BusyBox's version of wget does NOT have support for "--method=GET"
                        &[
                            "--header=Content-Type: application/json",
                            "--body-data",
                            // ...
```
or is it not needed?

Comment (ConradIrwin) [reply crates/remote/src/transport/ssh.rs]: Not needed. I assume GET is the default method?
