### PR TITLE
Fix file watching for symlinks

### LINKED ISSUE #17605: `RealFs::watch` doesn't report `settings.json` changes if file is a symlink
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`RealFs::watch` doesn't report `settings.json` (or any file) changes on Linux if the file is a symlink to another file. 

I have my actual settings on `~/gh/config/zed/settings.json` and I created a symlink using `ln -s ~/gh/config/zed/settings.json ~/.config/zed/settings.json`. 

This causes `RealFs::watch` to not see changes on the settings file, which causes toggle actions like `workspace::ToggleVimMode` to not refresh the settings when triggered unless you restart the entire workspace. 

Other problems I've noticed with this bug:  

- Toggling Copilot from the bottom bar doesn't take effect unless workspace is reloaded
- Changing the LLM provider on the Assistant Panel doesn't take effect unless the workspace is reloaded
- Docking panels to the right or to the left doesn't take effect (eg. docking Outline Panel to the right doesn't take effect unless reloading workspace)

Possible duplicate #17161 Not sure if it's the same issue. 

### Environment

Zed: v0.153.0 (Zed Dev 12dde176084c9950b78093c1e7fb13e5988292ba)
OS: Linux Wayland arch unknown
Memory: 6.7 GiB
Architecture: x86_64
GPU: AMD Radeon Vega 8 Graphics (RADV RAVEN) || radv || Mesa 24.2.2-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by AlvaroParker**
Closes #17605

Watches for target paths if file watched is a symlink in Linux. 
This will check if the generated `notify::Event` has any paths matching the `root_path` and if the file is a symlink it will also check if the path matches the `target_root_path` (the path that the symlink is pointing to) 

Release Notes:

- Added file watching for symlinks

### CODE REVIEW

File: crates/fs/src/fs.rs [hunk 1]
```diff
@@ -561,11 +564,14 @@ impl Fs for RealFs {
                 let mut paths = event
```
Comment (AlvaroParker) [inline crates/fs/src/fs.rs:564]: I don't know which one is more readable. Using `filter` and then `map` or using `filter_map`: 
```rust
let mut paths = event
    .paths
    .iter()
    .filter_map(|path| {
        if path.starts_with(&root_path)
            || (target_root_path.as_ref().is_ok()
                && path.starts_with(target_root_path.as_ref().unwrap()))
        {
            return Some(PathEvent {
                path: path.clone(),
                kind,
            });
        }
        None
    })
    .collect::<Vec<_>>();
```
In terms of performance I would think doing `filter_map` is faster since it does just one loop, but maybe the compiler optimizer `filter` followed by `map`.

File: crates/fs/src/fs.rs [hunk 2]
```diff
@@ -587,6 +596,14 @@ impl Fs for RealFs {
 
         watcher.add(path).ok(); // Ignore "file doesn't exist error" and rely on parent watcher.
 
+        // Check if path is a symlink and follow the target parent
+        if let Ok(target) = self.read_link(&path).await {
```
Comment (mikayla-maki) [inline crates/fs/src/fs.rs:600]: Can we re-use the read_link call above? It should be fine to clone the path into the watcher callback above.

File: crates/fs/src/fs.rs [hunk 3]
```diff
@@ -562,10 +565,16 @@ impl Fs for RealFs {
                     .paths
                     .iter()
                     .filter_map(|path| {
-                        path.starts_with(&root_path).then(|| PathEvent {
-                            path: path.clone(),
-                            kind,
-                        })
+                        if path.starts_with(&root_path)
+                            || (target_root_path.as_ref().is_ok()
```
Comment (mikayla-maki) [inline crates/fs/src/fs.rs:569]: We don't want to use an `is_ok()` / `unwrap()` pair if we can help it. Let's rewrite this to use an `if let Some(_) = _` :)

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
Just a few nits, thanks for the fix!

File: crates/fs/src/fs.rs [hunk 4]
```diff
@@ -548,6 +548,10 @@ impl Fs for RealFs {
         let pending_paths: Arc<Mutex<Vec<PathEvent>>> = Default::default();
         let root_path = path.to_path_buf();
 
+        // Check if root path is a symlink
+        let tr_path = self.read_link(&path).await.ok();
+        let tr_path_clone = tr_path.clone();
```
Comment (AlvaroParker) [inline crates/fs/src/fs.rs:553]: Using `.ok` here because the error type returned by `.read_link` doesn't implement `Clone` and we don't actually use the error so an `Option` does the job.

Comment (mikayla-maki) [inline crates/fs/src/fs.rs:553]: Rather than have this be `tr_path_clone`, let's use the block-clone-return style to capture the local variable, like this: https://github.com/zed-industries/zed/blob/main/crates/fs/src/fs.rs#L635-L637

Comment (mikayla-maki) [reply crates/fs/src/fs.rs:553]: And while we're at, let's call this variable `target_path`, maybe. We prefer not to have abbreviations :)

**Review by mikayla-maki — CHANGES_REQUESTED** [review]
