### PR TITLE
askpass: Fix cli path when executed in a remote server

### LINKED ISSUE #39438: Windows Beta: Cannot push to git
### Summary

Cannot push to git on Windows using WSL

### Description
I am on windows WSL and I cannot push to git with the zed VCS.

**Zed logs**:
2025-10-03T10:16:53+02:00 ERROR [remote::remote_client] (remote server) server:error handling message. type:Push, error:getting zed-cli path for askpass: could not find zed-cli from any of: ../bin/zed, ./cli
2025-10-03T10:16:53+02:00 ERROR [git_ui::git_panel] Error while pushing sending push request

Caused by:
    RPC request Push failed: getting zed-cli path for askpass: could not find zed-cli from any of: ../bin/zed, ./cli

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly e4f90b5da2b8a6d2b267edc02b333b7d7908d4d9) 
OS: Windows 10.0.26100
Memory: 31.1 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || 25.9.1 (25.10.25.10-250825a-418637C-AMD-Software-Adrenalin-Edition)

### LINKED ISSUE #39458: Windows Beta: Git pull/fetch in WSL workspace fails because helper can’t find zed-cli
### Summary

Triggering pull/fetch from the Git panel in a WSL-backed workspace fails with “git fetch failed” and the remote log reports it can’t locate zed-cli.

### Description

Steps to trigger the problem:

1. Install Zed Nightly 0.208.0 on Windows 11 (using the official Windows beta build) and enable the WSL integration (Ubuntu 22.04, WSL2).
2. From Zed on Windows, open a Git repository that lives inside WSL (\\wsl$\Ubuntu\home\devkit\projects\…).
3. In the Version Control panel, click the Fetch or Pull button.

Expected Behavior: Zed forwards the request to the WSL helper and runs a normal git fetch/git pull, leaving the repo up to date.

Actual Behavior: The UI immediately shows a toast git fetch failed, the “Output from git fetch” pane only prints sending fetch request, and the helper log (~/.local/share/zed/logs/server-nightly-workspace-9.log) records:

(remote server) server:error handling message. type:Fetch, error:getting zed-cli path for askpass: could not find zed-cli from any of: ../bin/zed, ./cli

Git works fine from a terminal in the same WSL session. Creating symlinks to the Windows-installed zed.exe in ~/.local/share/zed/bin, ~/.local/share/zed/server_state/bin, and ~/.zed_wsl_server/bin doesn’t change the behavior; the helper still bails out before invoking Git.

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly e4f90b5da2b8a6d2b267edc02b333b7d7908d4d9) 
OS: Windows 10.0.26100
Memory: 39.4 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || 25.8.1 (23.19.23.11-250701a-417877C-AMD-Software-Adrenalin-Edition)

### LINKED ISSUE #39469: Windows Beta: Git fails in WSL because zed-cli path not found
### Description
Git integration fails when pushing from WSL because Zed’s askpass helper can’t locate zed-cli.

Steps to trigger the problem:
1. Install Zed Nightly on Windows (Beta).
2. Open a repo that lives inside WSL.
3. Try to fetch/pull/push from the Git panel.

**Expected Behavior**:
Git should succeed, with Zed handling askpass correctly.

**Actual Behavior**:
Git fails with the following log:

```

2025-10-03T22:09:13+08:00 ERROR [remote::remote_client] (remote server) server:error handling message. type:Push, error:getting zed-cli path for askpass: could not find zed-cli from any of: ../bin/zed, ./cli
2025-10-03T22:09:13+08:00 ERROR [git_ui::git_panel] Error while pushing sending push request

Caused by:
RPC request Push failed: getting zed-cli path for askpass: could not find zed-cli from any of: ../bin/zed, ./cli

````

In this setup, Zed and Git is running under WSL (Linux), so Zed uses the Linux branch (`../bin/zed`, `./cli`).
But since Zed is installed on Windows, those paths don’t exist inside WSL, and askpass fails.

https://github.com/zed-industries/zed/blob/f71c9122cad322e8143317e4fadd2358e31b7c81/crates/askpass/src/askpass.rs#L81-L92
https://github.com/zed-industries/zed/blob/fd8bae9b72732a34bb9ad572a06371aa1a03e27d/crates/util/src/util.rs#L325-L327

Related issues:
- https://github.com/zed-industries/zed/issues/39438
- https://github.com/zed-industries/zed/issues/39458

### Zed Version and System Specs

Zed: v0.208.0 (Zed Nightly e4f90b5da2b8a6d2b267edc02b333b7d7908d4d9) 
OS: Windows 10.0.26100
Memory: 63.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA Corporation || 560.94 r560_88

### PR DESCRIPTION
**Pull request by marcocondrache**
Closes #39469
Closes #39438
Closes #39458

I'm not able to test it, i would appreciate if somebody could do it. I think this bug was present also for SSH remote projects

Release Notes:

- Fixed an issue where zed bin was not found in remote servers for askpass

### CODE REVIEW

**Comment by marcocondrache** [comment]
I just noticed that `get_shell_safe_zed_path` it's marked unix only

**Comment by ruri4** [comment]
lgtm

```
Zed: v0.208.0 (Zed Dev ed651ea3a0a9d2d7f298d7ea2d62ebc639e8711d) (Taylor's Version)
OS: Windows 10.0.26100
Architecture: x86_64
```

zed cli helper now works within WSL

**Review by maxbrunsfeld — DISMISSED** [review]
@marcocondrache Thanks so much for tracking this down. Nice work.

I would love to solve this in a way that doesn't rely on checking the filename of the current exe.

Here's one way to fix it that I think is cleaner. Let me know if this makes sense to you:

* We should put back the `--askpass` argument in the main editor on linux and macOS.
* There should be a static variable in `ask_pass.rs` called `ASKPASS_PROGRAM` (a `PathBuf`) - the path to the program that should be invoked for askpass. By default, `ASKPASS_PROGRAM` should be initialized to the `current_exe()`. On mac and Linux, and in the remote server, it should just be left that way.
* The `askpass` module should have a public setter function called `set_askpass_program` that can override the `ASKPASS_PROGRAM`. We should only call that function on Windows, in `zed::main` (passing in the path to the CLI).

**Comment by marcocondrache** [comment]
@maxbrunsfeld, thanks for the feedback! That makes perfect sense, and it's a cleaner approach. I will make the changes immediately

**Comment by marcocondrache** [comment]
@maxbrunsfeld I’ve updated the PR with the changes. I moved the logic for turning a path into a shell-safe string into the `PathExt` trait, since it felt generic enough to live there but if you think it makes more sense somewhere else, I’m happy to move it.

I’m also not too sure about the `get_zed_cli_path` function since it's called for `set_askpass_program`. Maybe it’d be simpler to inline that directly in `zed::main`, but I’ll let you guide what feels best here.

For testing, I can only try things out on macOS. I’ll give it a spin there, but unfortunately I won’t be much help on Linux or Windows 😞

File: crates/askpass/src/askpass.rs [hunk 1]
```diff
@@ -249,12 +262,18 @@ pub fn main(socket: &str) {
     }
 }
 
+pub fn set_askpass_program(path: std::path::PathBuf) {
```
Comment (osiewicz) [inline crates/askpass/src/askpass.rs:265]: nit: conventionally in Zed we use a `fn init()` function for initialization of globals related to a given module. That function also resides closer to the top of a file. 
```suggestion
pub fn init(path: std::path::PathBuf) {
```

File: crates/askpass/src/askpass.rs [hunk 2]
```diff
@@ -249,12 +262,18 @@ pub fn main(socket: &str) {
...
+    if ASKPASS_PROGRAM.set(path).is_err() {
+        panic!("askpass program has already been set");
```
Comment (osiewicz) [inline crates/askpass/src/askpass.rs]: That could prolly be a `debug_panic`. We don't want to bring the whole app down, because - while multiple distinct values for `ASKPASS_PROGRAM` don't make sense - panicking turns a benign bug into a hard crash, even if you don't end up using any remoting functionalities.

File: crates/util/src/paths.rs [hunk 3]
```diff
@@ -153,6 +154,29 @@ impl<T: AsRef<Path>> PathExt for T {
 
         Some(parts.into_iter().join("."))
     }
+
+    /// Try to make a shell-safe representation of the path.
+    ///
+    /// For Unix, the path is escaped to be safe for POSIX shells
```
Comment (osiewicz) [inline crates/util/src/paths.rs]: This could be a doc comment on the trait method itself, not on it's implementation.

File: crates/util/src/util.rs [hunk 4]
```diff
@@ -288,27 +290,21 @@ fn load_shell_from_passwd() -> Result<()> {
...
+        std::env::current_exe().context("Failed to determine current zed executable path.")?;
+
+    Ok(zed_path
+        .try_shell_safe()
+        .context("Failed to shell-escape Zed executable path.")?
+        .trim_end_matches(" (deleted)") // See https://github.com/rust-lang/rust/issues/69343
+        .to_string())
 }
 
 /// Returns a shell escaped path for the zed cli executable, this function
```
Comment (osiewicz) [inline crates/util/src/util.rs]: Nit: is this doc comment outdated? The returned path is no longer shell-escaped.

File: crates/askpass/src/askpass.rs [hunk 5]
```diff
@@ -249,12 +262,18 @@ pub fn main(socket: &str) {
...
+
 #[inline]
 #[cfg(not(target_os = "windows"))]
-fn generate_askpass_script(zed_cli_path: &str, askpass_socket: &std::path::Path) -> String {
+fn generate_askpass_script(askpass_program: &str, askpass_socket: &std::path::Path) -> String {
     format!(
-        "{shebang}\n{print_args} | {zed_cli} --askpass={askpass_socket} 2> /dev/null \n",
-        zed_cli = zed_cli_path,
+        "{shebang}\n{print_args} | {askpass_program} --askpass={askpass_socket} 2> /dev/null \n",
+        askpass_program = askpass_program,
```
Comment (osiewicz) [inline crates/askpass/src/askpass.rs]:
```suggestion
```

File: crates/askpass/src/askpass.rs [hunk 6]
```diff
@@ -263,13 +282,13 @@ fn generate_askpass_script(zed_cli_path: &str, askpass_socket: &std::path::Path)
...
-fn generate_askpass_script(zed_cli_path: &str, askpass_socket: &std::path::Path) -> String {
+fn generate_askpass_script(askpass_program: &str, askpass_socket: &std::path::Path) -> String {
     format!(
         r#"
         $ErrorActionPreference = 'Stop';
-        ($args -join [char]0) | & "{zed_cli}" --askpass={askpass_socket} 2> $null
+        ($args -join [char]0) | & "{askpass_program}" --askpass={askpass_socket} 2> $null
         "#,
-        zed_cli = zed_cli_path,
+        askpass_program = askpass_program,
```
Comment (osiewicz) [inline crates/askpass/src/askpass.rs]:
```suggestion
```

File: crates/util/src/paths.rs [hunk 7]
```diff
@@ -153,6 +154,29 @@ impl<T: AsRef<Path>> PathExt for T {
...
+        {
+            Ok(self.as_ref().to_string_lossy().to_string())
+        }
+
+        #[cfg(not(target_os = "windows"))]
+        {
+            let path_str = self
+                .as_ref()
+                .to_str()
+                .ok_or_else(|| anyhow::anyhow!("Path contains invalid UTF-8"))?;
```
Comment (osiewicz) [inline crates/util/src/paths.rs]:
```suggestion
                .with_context(|| "Path contains invalid UTF-8")?;
```

File: crates/util/src/paths.rs [hunk 8]
```diff
@@ -153,6 +154,29 @@ impl<T: AsRef<Path>> PathExt for T {
...
+
+            // As of writing, this can only be fail if the path contains a null byte, which shouldn't be possible
+            // but shlex has annotated the error as #[non_exhaustive] so we can't make it a compile error if other
+            // errors are introduced in the future :(
+            Ok(shlex::try_quote(path_str)?.to_string())
```
Comment (osiewicz) [inline crates/util/src/paths.rs]:
```suggestion
            Ok(shlex::try_quote(path_str)?.into())
```

I'm not sure if that'll compile from the get-go, but `to_string` can be slower than `String::from`. Not that it matters though, so feel free to disregard.

File: crates/util/src/paths.rs (hunk 3 above)
Comment (marcocondrache) [reply crates/util/src/paths.rs]: All the methods of this trait have the doc comment on the implementations. Should i move all of them?

File: crates/util/src/util.rs (hunk 4 above)
Comment (marcocondrache) [reply crates/util/src/util.rs]: Yep, i've missed that

File: crates/askpass/src/askpass.rs (hunk 5 above)
Comment (marcocondrache) [reply crates/askpass/src/askpass.rs]: Done

File: crates/askpass/src/askpass.rs (hunk 6 above)
Comment (marcocondrache) [reply crates/askpass/src/askpass.rs]: Done

File: crates/util/src/paths.rs (hunk 7 above)
Comment (marcocondrache) [reply crates/util/src/paths.rs]: Done

File: crates/util/src/paths.rs (hunk 8 above)
Comment (marcocondrache) [reply crates/util/src/paths.rs]: That's a good catch. The method returns `Cow`, so `into()` could indeed be faster. I've made the change

File: crates/askpass/src/askpass.rs (hunk 2 above)
Comment (marcocondrache) [reply crates/askpass/src/askpass.rs]: Yep that's super right. I missed the debug_panic macro

File: crates/askpass/src/askpass.rs (hunk 1 above)
Comment (marcocondrache) [reply crates/askpass/src/askpass.rs:265]: I think calling it `init` might be misleading in this case, since it only runs on Windows. Making it run unconditionally could also introduce security concerns - on Unix platforms, `current_exe` should be called right before use to avoid potential privilege escalation.

Comment (osiewicz) [reply crates/askpass/src/askpass.rs:265]: Fair, we can leave it as is then.

File: crates/util/src/paths.rs (hunk 3 above)
Comment (osiewicz) [reply crates/util/src/paths.rs]: Yeah, I think that'd be best.

File: crates/util/src/paths.rs (hunk 8 above)
Comment (osiewicz) [reply crates/util/src/paths.rs]: Ah, in that case you can even go the extra mile and use `into_owned`.

**Review by osiewicz — APPROVED** [review]
LGTM! Will give it a go with other platforms before merging.

**Comment by maxbrunsfeld** [comment]
Thanks so much for the follow ups @marcocondrache

File: crates/util/src/paths.rs (hunk 3 above)
Comment (marcocondrache) [reply crates/util/src/paths.rs]: I've moved the doc comments to the trait definition

File: crates/util/src/paths.rs (hunk 8 above)
Comment (marcocondrache) [reply crates/util/src/paths.rs]: That's right. Done

**Comment by marcocondrache** [comment]
@maxbrunsfeld @osiewicz thank you for the support!

**Comment by osiewicz** [comment]
I've tested this on Windows -> Linux and Mac -> Linux SSH scenarios. In both cases it fixed git usage.
