### PR TITLE
Fix PATH lookup to handle Windows case sensitivity

### LINKED ISSUE #40448: Windows Beta: go Language server start error
### Summary

SUMMARY_SENTENCE_HERE
go Language server start error
### Description

1. open a go project

**Expected Behavior**:
go Language server start success
**Actual Behavior**:
Image
log:
```
2025-10-17T09:43:00+08:00 ERROR [languages::go] no cached binary
2025-10-17T09:43:00+08:00 ERROR [project::lsp_store] Failed to start language server "gopls": cannot install gopls
2025-10-17T09:44:13+08:00 ERROR [editor::editor] persisting editor selections for editor 12884902129, workspace WorkspaceId(3)

Caused by:
    Sqlite call failed with code 787 and message: Some("FOREIGN KEY constraint failed")
```
go version:

Image

Image

### Zed Version and System Specs

Zed: v0.210.0 (Zed Nightly 04f0805502398657e967749a6e659d045d5fb549) 
OS: Windows 10.0.19045
Memory: 15.3 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || 23.19.12.02 (23.19.12.02-240618a-404740C-HP)

### PR DESCRIPTION
**Pull request by overstarry**
Closes #40448

On Windows, PATH might be "Path" instead of "PATH"

Release Notes:

- N/A *or* Added/Fixed/Improved ...

### CODE REVIEW

**Review by Veykril — APPROVED** [review]
Thanks!

File: crates/project/src/lsp_store.rs [hunk 1]
```diff
@@ -12760,7 +12760,15 @@ impl LspAdapterDelegate for LocalLspAdapterDelegate {
         if self.fs.is_file(&worktree_abs_path).await {
             worktree_abs_path.pop();
         }
-        let shell_path = self.shell_env().await.get("PATH").cloned();
+
+        let env = self.shell_env().await;
+
+        // On Windows, PATH might be "Path" instead of "PATH"
+        let shell_path = env.get("PATH")
```
Comment (Veykril) [inline crates/project/src/lsp_store.rs]:
```suggestion
        let shell_path = env
            .get("PATH")
```
