### PR TITLE
copilot: Fix config dir logic to support Flatpak environments

### LINKED ISSUE #30784: Agent Panel: Zed doesn't detect that I'm logged in to Github Copilot Chat
### Summary

Basically title

### Description

I'm logged into Github copilot chat, but can't see the copilot models in the model selection popover. Additionally, when I go to assistant settings, I get prompted to log into Github Copilot chat again, while I'm already logged in.

Clicking the Sign In button shows me that I'm logged in.

Edit predictions do work, I just can't select the Github copilot models in the agent panel.

More details are here: https://www.reddit.com/r/ZedEditor/comments/1kn4g9x/comment/msg8ati/?context=3

Image

Image

Image

### Zed Version and System Specs

Zed: v0.186.9 (Zed) 
OS: Linux Wayland org.freedesktop.platform 24.08
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 25.0.5 (git-a89e404408)

### PR DESCRIPTION
**Pull request by imumesh18**
Closes #30784

In github copilot we were not handling the config path correctly for FLATPAK.

* Only tested on mac don't have access to other platform. But this should work on other platform as well. It follows the similar pattern seen in zed config path resolution.
- [x] Macos
- [ ] Linux
- [ ] Linux with Flatpak
- [ ] Windows

Release Notes:

- Fix copilot config detection for flatpack

### CODE REVIEW

File: crates/copilot/src/copilot_chat.rs [hunk 1]
```diff
@@ -424,12 +423,14 @@ pub fn copilot_chat_config_dir() -> &'static PathBuf {
     static COPILOT_CHAT_CONFIG_DIR: OnceLock<PathBuf> = OnceLock::new();
 
     COPILOT_CHAT_CONFIG_DIR.get_or_init(|| {
-        if cfg!(target_os = "windows") {
-            home_dir().join("AppData").join("Local")
+        let config_dir = if cfg!(any(target_os = "linux", target_os = "freebsd")) {
+            std::env::var("FLATPAK_XDG_CONFIG_HOME")
```
Comment (vixalien) [inline crates/copilot/src/copilot_chat.rs]: I think you need to use `XDG_CONFIG_HOME`.

```
flatpak run --command=sh dev.zed.Zed
[📦 dev.zed.Zed ~]$ echo $XDG_CONFIG_HOME
/home/mona/.var/app/dev.zed.Zed/config
```

**Review by vixalien — CHANGES_REQUESTED** [review]

**Comment by vixalien** [comment]
I don't know why the builds are skipped, otherwise I can't really build Zed locally.

File: crates/copilot/src/copilot_chat.rs (hunk 1 above)
Comment (imumesh18) [reply crates/copilot/src/copilot_chat.rs]: It should fallback to that if this env is not set. dir::config_path takes care of it. Made sure we handle it in same zed does for it's own config might refactor later to see if that's redundant

Comment (vixalien) [reply crates/copilot/src/copilot_chat.rs]: The environment variable `FLATPAK_XDG_CONFIG_HOME` does not exist on Linux afaict, which is why I proposed `XDG_CONFIG_HOME`.

**Comment by imumesh18** [comment]
@vixalien builds are disabled by default someone from zed team needs to add run bundling tag to enable builds.

File: crates/copilot/src/copilot_chat.rs (hunk 1 above)
Comment (imumesh18) [reply crates/copilot/src/copilot_chat.rs]: Got it. I just made sure it's in inline with zed config: https://github.com/zed-industries/zed/blob/main/crates/paths/src/paths.rs#L75 resolution. Not sure why it exists or reason behind it for case of zed. But yes eventually it fallbacks to $XDG_CONFIG_HOME(which is handled by `dirs::config_dir()`) if it doesn't find FLATPAK_XDG_CONFIG_HOME env. So for now it should safely resolve and work. Will wait for some from zed to weigh in on whether or not we need.

Comment (vixalien) [reply crates/copilot/src/copilot_chat.rs]: I think that code is a bug, since there is no such thing as `FLATPAK_XDG_CONFIG_HOME`. Maybe @mkungla can explain more since they are on the blame.

So you're saying that if `FLATPAK_XDG_CONFIG_HOME` is not defined, it will be `XDG_CONFIG_HOME`

Comment (imumesh18) [reply crates/copilot/src/copilot_chat.rs]: Yes you are correct @vixalien we fallback to XDG_CONFIG_HOME.

**Comment by vixalien** [comment]
okie cool I'll test it when a build happens...

**Comment by imumesh18** [comment]
Hey @vixalien in case you want to test it you can also try building this on local. Here is the flatpack build instructions: https://zed.dev/docs/development/linux#flatpak

**Comment by bennetbo** [comment]
Hey, gonna start a build now so that people can test

**Comment by vixalien** [comment]
thanks !

**Comment by keramblock** [comment]
Macos build failed on some kind of upload

**Comment by bennetbo** [comment]
Linux x86_64: https://github.com/zed-industries/zed/actions/runs/15743017685/artifacts/3358369992 
Linux arm64: https://github.com/zed-industries/zed/actions/runs/15743017685/artifacts/3358452897

**Comment by vixalien** [comment]
Just built a flatpak with the build artifact, and sadly it does not work:

image

image

```
Zed: v0.193.0 (Zed Dev 80cf9ca8d208d3d6650ffdf4ec28ce4b64e93dc0) 
OS: Linux Wayland org.freedesktop.platform 24.08
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 25.1.3 (git-ba95e694fe)
```

**Comment by vixalien** [comment]
Also, it's a bit sad that Zed's CI doesn't automatically generate a flatpak, since it just needs to repackage the build artefacts from x86 and arm.

**Comment by vixalien** [comment]
Update: it seems to work **some of the time**, and after a delay.

See attached video.


https://github.com/user-attachments/assets/3b4ecb88-80eb-49df-858f-b76c72d10969

**Comment by imumesh18** [comment]
Hey @vixalien give it sometime as we are starting the lsp and then initialising and fetching the models using api it takes time.

File: crates/copilot/src/copilot_chat.rs (hunk 1 above)
Comment (mkungla) [reply crates/copilot/src/copilot_chat.rs]: @vixalien this was introduced way before I revamped  paths see e.g. https://github.com/zed-industries/zed/commit/81475ac4cde2d7481d620ef22e1d9c3148b38ec2

**Comment by vixalien** [comment]
Okay there's a 30s~ delay.

Maybe Zed can improve the UX a bit by showing a spinner somewhere

**Comment by imumesh18** [comment]
It shouldn't be that big, I am guessing could be caused due to local build. Nice to know at least the issue is resolved. Also agree zed can provide a better feedback in terms of any of the provider still in init phase, which I will leave it for later.

**Comment by imumesh18** [comment]
Hey @bennetbo I have updated the logic a bit more and simplified it. I checked the lsp js code and looked how they are storing the config so that we can better align with their path resolution and hence updated the logic to match that. It should now handle all the platform gracefully. Below is the detail breakdown.

| Platform | Condition | Directory Path | Example |
|----------|-----------|----------------|---------|
| **Windows** | Always | `%LOCALAPPDATA%\github-copilot` | `C:\Users\username\AppData\Local\github-copilot` |
| **Linux/FreeBSD** | `XDG_CONFIG_HOME` set | `${XDG_CONFIG_HOME}/github-copilot` | `/home/username/.local/config/github-copilot` |
| **Linux/FreeBSD** | `XDG_CONFIG_HOME` not set | `~/.config/github-copilot` | `/home/username/.config/github-copilot` |
| **macOS** | `XDG_CONFIG_HOME` set | `${XDG_CONFIG_HOME}/github-copilot` | `/Users/username/.local/config/github-copilot` |
| **macOS** | `XDG_CONFIG_HOME` not set | `~/.config/github-copilot` | `/Users/username/.config/github-copilot` |
| **Other Unix-like** | `XDG_CONFIG_HOME` set | `${XDG_CONFIG_HOME}/github-copilot` | `/home/username/.local/config/github-copilot` |
| **Other Unix-like** | `XDG_CONFIG_HOME` not set | `~/.config/github-copilot` | `/home/username/.config/github-copilot` |

File: crates/copilot/src/copilot_chat.rs (hunk 1 above)
Comment (imumesh18) [reply crates/copilot/src/copilot_chat.rs]: Removed this check as it's not relevant in case of GitHub copilot config resolution.

**Review by bennetbo — APPROVED** [review]
Thanks for investigating this 😄 Great work! Also thanks for testing to everyone involved

**Comment by imumesh18** [comment]
@bennetbo can you cherry pick this to preview please for next patch fix of preview.
