### PR TITLE
project_panel: Fix appending copy marker for directory at wrong position

### LINKED ISSUE #48765: Zed appends `copy` marker for copied file in the wrong position of filename
### Reproduction steps

open a project under WSL, copy a folder

### Current vs. Expected behavior

Image

It should be 1.20 copy

### Zed version and system specs

Zed: v0.222.4+stable.147.b385025df963c9e8c3f74cc4dadb1c4b29b3c6f0 (Zed) 
OS: Windows 10.0.26200
Memory: 63.8 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 || NVIDIA Corporation || 560.94 r560_88

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by pigletfly**
Closes #48765 

Release Notes:

- Fixed appends copy marker for copied file in the wrong position of filename

### CODE REVIEW

File: crates/project_panel/src/project_panel_tests.rs [hunk 1]
```diff
@@ -2843,6 +2843,60 @@ async fn test_rename_item_and_check_history(cx: &mut gpui::TestAppContext) {
...
+    assert!(
+        entries
+            .iter()
+            .any(|line| line.contains("[EDITOR: '1.20 copy']")),
+        "Expected duplicated directory to be named '1.20 copy', got: {entries:?}"
+    );
+    assert!(
+        !entries.iter().any(|line| line.contains("1 copy.20")),
+        "Did not expect directory name to be treated like a file extension, got: {entries:?}"
+    );
```
Comment (KuSh) [inline crates/project_panel/src/project_panel_tests.rs]: This could be more explicit, and on par with other tests:
```suggestion
    let panel = workspace.update(cx, ProjectPanel::new).unwrap();
    cx.run_until_parked();

    toggle_expand_dir(&panel, "src/static", cx);
    toggle_expand_dir(&panel, "src/static/nginx", cx);
    select_path(&panel, "src/static/nginx/1.20", cx);

    assert_eq!(
        visible_entries_as_strings(&panel, 0..50, cx),
        &[
            "v src",
            "    v static",
            "        v nginx",
            "            > 1.20  <== selected",
        ],
    );

    panel.update_in(cx, |panel, window, cx| {
        panel.duplicate(&Duplicate, window, cx);
    });
    cx.executor().run_until_parked();

    assert_eq!(
        visible_entries_as_strings(&panel, 0..50, cx),
        &[
            "v src",
            "    v static",
            "        v nginx",
            "            v 1.20",
            "                  default.conf",
            "            > [EDITOR: '1.20 copy']  <== selected",
        ],
        "File list should be different after duplication"
    );
```

**Review by KuSh — APPROVED** [review]

File: crates/project_panel/src/project_panel.rs [hunk 2]
```diff
@@ -2959,8 +2966,18 @@ impl ProjectPanel {
             .file_name()?
             .to_string();
         new_path.push(RelPath::unix(&clipboard_entry_file_name).unwrap());
-        let extension = new_path.extension().map(|s| s.to_string());
-        let file_name_without_extension = new_path.file_stem()?.to_string();
+
+        // For files, insert the disambiguation before the extension. For directories, always append
```
Comment (smitbarmase) [inline crates/project_panel/src/project_panel.rs]: Let's get rid of this comment.

File: crates/project_panel/src/project_panel_tests.rs [hunk 3]
```diff
@@ -2843,6 +2843,60 @@ async fn test_rename_item_and_check_history(cx: &mut gpui::TestAppContext) {
         .unwrap();
 }
 
+#[gpui::test]
+async fn test_duplicate_directory_name_with_dot(cx: &mut gpui::TestAppContext) {
```
Comment (smitbarmase) [inline crates/project_panel/src/project_panel_tests.rs]: As @KuSh suggested, we should make this test more explicit. I wonder, if we should make this part of existing test that handles this flow.

**Review by smitbarmase — CHANGES_REQUESTED** [review]
Thanks for fixing this, I added some comments.

**Review by smitbarmase — APPROVED** [review]
I updated it. Thanks!
