### PR TITLE
agent: Fix crash with pathological fetch output

### LINKED ISSUE #34029: Crashing when agent is fetching file
### Summary

AI Agent fetching file crashes without any error message.

### Description
Wanting AI Agent to fetch following file will crash whole app. Attaching snippet from trhead.

> ## Agent
> Nejprve provedu testovací stažení této nové "raw" URL, abych se ujistil, že je platná a vrací soubor JAR (ne HTML stránku 404).
> 
> **Use Tool: fetch (fetch-53)**
> ```json
> {
>   "url": "https://github.com/forcedotcom/salesforcedx-vscode/raw/main/packages/salesforcedx-vscode-apex/jars/apex-jorje-lsp.jar"
> }
> ```
> ## User
>  ---- CRASH -----
> try again
> 
> ## Agent
> 
> **Use Tool: fetch (fetch-0)**
> ```json
> {
>   "url": "https://github.com/forcedotcom/salesforcedx-vscode/raw/main/packages/salesforcedx-vscode-apex/jars/apex-jorje-lsp.jar"
> }
> ```
> ---- CRASH ----

Actual Behavior: Crash
Expected Behavior: No Crash

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: macOS 15.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by cole-miller**
Closes #34029

The crash is due to a stack overflow in our `html_to_markdown` conversion; I've added a maximum depth of 200 for the recursion in that crate to guard against this kind of thing.

Separately, we were treating all content-types other than `text/plain` and `application/json` as HTML; I've changed this to only treat `text/html` and `application/xhtml+xml` as HTML, and fall back to plaintext. (In the original crash, the content-type was `application/octet-stream`.)

Release Notes:

- agent: Fixed a potential crash when fetching large non-HTML files.

### CODE REVIEW

File: crates/assistant_tools/src/fetch_tool.rs [hunk 1]
```diff
@@ -69,10 +69,9 @@ impl FetchTool {
             .to_str()
             .context("invalid Content-Type header")?;
         let content_type = match content_type {
-            "text/html" => ContentType::Html,
-            "text/plain" => ContentType::Plaintext,
+            "text/html" | "application/xhtml+xml" => ContentType::Html,
             "application/json" => ContentType::Json,
-            _ => ContentType::Html,
```
Comment (cole-miller) [inline crates/assistant_tools/src/fetch_tool.rs:75]: @maxdeviant Figure I should check, is there a motivation for falling back to HTML instead of to plaintext?

Comment (maxdeviant) [reply crates/assistant_tools/src/fetch_tool.rs:75]: My original thinking is that the most likely content that would be fetched from the internet would be HTML, so we treat it as such if not otherwise categorized.

Comment (cole-miller) [reply crates/assistant_tools/src/fetch_tool.rs:75]: That makes sense! My motivation for changing it was that the plaintext branch deals more gracefully with binary files, and I'm a little worried about feeding non-HTML into the HTML parser and causing it to get into a bad state, as happened here.

Going to merge with the change to the fallback for now, but let me know if you feel strongly the other way and I can revert or find an alternative fix!
