### PR TITLE
git_graph: Fix pluralization of "Changed Files" in commit details

### LINKED ISSUE #54283: Incorrect pluralization — “1 Changed Files” in Git commit details
### Reproduction steps

1. Open Zed with a Git repository that has history (any workspace is fine).
2. Open the **Git** / **version control** view and the **commit log** (or equivalent) so you can select a commit.
3. Select a commit that changes **exactly one** file (e.g. a small fix commit with a single touched path).
4. Inspect the commit detail pane where changed files are summarized.

**Observed:** Copy such as **“1 Changed Files”** appears (singular count, plural noun).

### Current behavior

- The string uses the **plural** “Files” even when the count is **1**, which reads as a grammar error and looks unpolished compared to other tools.

Image

### Expected behavior

- **Count = 1:** `1 Changed File` (singular).
- **Count ≠ 1:** `N Changed Files` (plural), or use your product’s standard pattern, e.g.:
  - `"{count} Changed File(s)"` only if you intentionally use a compact non-pluralized form (less ideal for localization), or
  - Prefer **real pluralization** (including **i18n** / ICU-style plural rules if this string is translated elsewhere).

Image

### Zed version and system specs

Zed: v0.234.0+dev.554f5c6b65708e054ee34a12e0b8015cb9bed71f
OS: Windows
RAM: 32GB

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by galuis116**
Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #54283 

Release Notes:

- Fixed: Git graph commit detail header now uses “1 Changed File” when exactly one file changed, and “N Changed Files” otherwise, instead of always saying “Changed Files”.

### CODE REVIEW

File: crates/git_graph/src/git_graph.rs [hunk 1]
```diff
@@ -2100,7 +2106,7 @@ impl GitGraph {
                             .w_full()
                             .justify_between()
                             .child(
-                                Label::new(format!("{} Changed Files", changed_files_count))
+                                Label::new(changed_files_heading)
```
Comment (yeskunall) [inline crates/git_graph/src/git_graph.rs]:
```suggestion
Label::new(format!(
    "{} Changed {}",
    changed_files_count,
    if changed_files_count == 1 { "File" } else { "Files" }
))
```

File: crates/git_graph/src/git_graph.rs [hunk 2]
```diff
@@ -1872,6 +1872,12 @@ impl GitGraph {
             .map(|diff| diff.files.len())
             .unwrap_or(0);
 
+        let changed_files_heading = if changed_files_count == 1 {
+            "1 Changed File".to_string()
```
Comment (yeskunall) [inline crates/git_graph/src/git_graph.rs]: This allocation is unneeded.

Comment (galuis116) [reply crates/git_graph/src/git_graph.rs]: I have updated the git_graph.rs according to your feedback.

File: crates/git_graph/src/git_graph.rs (hunk 1 above)
Comment (galuis116) [reply crates/git_graph/src/git_graph.rs]: I got it, I have updated the like what you mentioned

**Review by yeskunall — APPROVED** [review]

**Comment by yeskunall** [comment]
Thanks @galuis116 -- much better (IMO). Someone else on the team will also review these changes and then merge them. Pre-firing this, tho: congratulations on your first contribution to Zed! 💖

**Review by danilo-leal — APPROVED** [review]
Thank you!!

**Comment by galuis116** [comment]
I am waiting for this pull request to merge as all tests have passed and @yeskunall mentioned this "Thanks @galuis116 -- much better (IMO). Someone else on the team will also review these changes and then merge them. Pre-firing this, tho: congratulations on your first contribution to Zed! 💖"
