### PR TITLE
languages: Correctly calculate ranges in `label_for_completion`

### LINKED ISSUE #44825: Zed crashes with Rust LSP when trying to autosuggest
### Reproduction steps

1. Create new rust cargo binary project
2. Paste [this](https://pastebin.com/rQNWsA86) into main.rs
3. Ensure Rust LSP has downloaded
4. Try to finish the function by writing 'result' as the last line of the function in Particles::new
5. Should crash
 
Noteworthy log lines:
```
2025-12-14T21:57:17+02:00 INFO  [zed::reliability] Uploaded minidump. event id: f3eee635-eb44-4ac8-9442-6c5b017b55e9
2025-12-14T21:57:18+02:00 INFO  [http_client::github_download] downloading github artifact from https://github.com/rust-lang/rust-analyzer/releases/download/2025-12-08/rust-analyzer-x86_64-unknown-linux-gnu.gz
2025-12-14T21:57:23+02:00 INFO  [lsp] starting language server process. binary path: "/home/whosethenerd/.local/share/zed/languages/rust-analyzer/rust-analyzer-2025-12-08", working directory: "/home/whosethenerd/dev/zed_reprod", args: []
2025-12-14T22:00:15+02:00 INFO  [sqlez::migrations] Found 18 foreign key relationships to check
2025-12-14T22:02:44+02:00 ERROR [crashes] thread 'main' panicked at crates/language/src/language.rs:2377:13:
invalid run range...
2025-12-14T22:02:44+02:00 ERROR [crashes] triggering a crash to generate a minidump...
```

### Zed version and system specs

Zed: v0.216.1+stable.95.81870d5cf77d61d40ec526a37141ebe3a74318ca (Zed) 
OS: Linux X11 linuxmint 22.2
Memory: 30.5 GiB
Architecture: x86_64
GPU: AMD Ryzen 7 9700X 8-Core Processor (RADV RAPHAEL_MENDOCINO) || radv || Mesa 25.0.7-0ubuntu0.24.04.2

### Attach Zed log file

[Zed.log](https://pastebin.com/iUCX69wi)

### PR DESCRIPTION
**Pull request by Nereuxofficial**
Closes #44825

Release Notes:

- Fixed a case where an incorrect match could be generated in label_for_completion

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, but cannot you add an [actual test](https://github.com/zed-industries/zed/issues/44825#issuecomment-3656080747) for this?

**Comment by MMaikov** [comment]
Thank you, while this fixes the issue I found a performance problem. After typing 'res' and getting the auto suggestion box to show up, scrolling through it is slow and zed logged a hangup. Repro is same as in #44825 
[hang-2025-12-16_09-03-17.miniprof.zip](https://github.com/user-attachments/files/24184908/hang-2025-12-16_09-03-17.miniprof.zip)

**Comment by Nereuxofficial** [comment]
> Thank you, but cannot you add an [actual test](https://github.com/zed-industries/zed/issues/44825#issuecomment-3656080747) for this?

Thanks for the review! I've now added a test which tests whether the ranges are correct for a string where "…" characters were inserted for empty tabstops. Let me know if i should make any further adjustments.

**Comment by Nereuxofficial** [comment]
> Thank you, while this fixes the issue I found a performance problem. After typing 'res' and getting the auto suggestion box to show up, scrolling through it is slow and zed logged a hangup. Repro is same as in #44825 [hang-2025-12-16_09-03-17.miniprof.zip](https://github.com/user-attachments/files/24184908/hang-2025-12-16_09-03-17.miniprof.zip)

I cannot reproduce this locally but from my interpretation this looks like not related to this code as it is not found in the trace. Could you try disabling your extensions temporarily and see whether that fixes the issue(as wasm_host.rs is consumes a lot of time in the statistics)?

File: crates/language/src/language.rs [hunk 1]
```diff
@@ -2425,7 +2425,10 @@ impl CodeLabel {
             "invalid filter range"
         );
         runs.iter().for_each(|(range, _)| {
-            assert!(text.get(range.clone()).is_some(), "invalid run range");
+            assert!(
+                text.get(range.clone()).is_some(),
+                "invalid run range with inputs. Requested range {range:?} in text {text}",
```
Comment (SomeoneToIgnore) [inline crates/language/src/language.rs]:
```suggestion
                "invalid run range with inputs. Requested range {range:?} in text '{text}'",
```

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you, will merge one nit on top, so that the text in the error is shown better.

**Comment by MMaikov** [comment]
> > Thank you, while this fixes the issue I found a performance problem. After typing 'res' and getting the auto suggestion box to show up, scrolling through it is slow and zed logged a hangup. Repro is same as in #44825 [hang-2025-12-16_09-03-17.miniprof.zip](https://github.com/user-attachments/files/24184908/hang-2025-12-16_09-03-17.miniprof.zip)
> 
> I cannot reproduce this locally but from my interpretation this looks like not related to this code as it is not found in the trace. Could you try disabling your extensions temporarily and see whether that fixes the issue(as wasm_host.rs is consumes a lot of time in the statistics)?

I build it again in release mode and the problem was gone. 

Note to self: always test performance in release mode.
