### PR TITLE
agent_server_store: Broaden Windows asset detection to all architectures

### LINKED ISSUE #50039: Zed fails to download Codex CLI ACP, gets perpetually stuck in the UI
### Reproduction steps

- Be on Windows ARM
- Agent Panel -> `+` -> Codex CLI

### Current vs. Expected behavior

```
2026-02-20T12:18:13+01:00 INFO  [http_client::github_download] downloading github artifact from https://github.com/zed-industries/codex-acp/releases/download/v0.9.4/codex-acp-0.9.4-aarch64-pc-windows-msvc.zip
2026-02-20T12:18:28+01:00 INFO  [http_client::github_download] downloading github artifact from https://github.com/zed-industries/codex-acp/releases/download/v0.9.4/codex-acp-0.9.4-aarch64-pc-windows-msvc.zip
2026-02-20T12:18:45+01:00 ERROR [project::agent_server_store] Failed to download Codex release v0.9.4: extracting downloaded asset for https://github.com/zed-industries/codex-acp/releases/download/v0.9.4/codex-acp-0.9.4-aarch64-pc-windows-msvc.zip into "C:\\Users\\user\\AppData\\Local\\Zed\\external_agents\\codex\\v0.9.4": extracting https://github.com/zed-industries/codex-acp/releases/download/v0.9.4/codex-acp-0.9.4-aarch64-pc-windows-msvc.zip to "C:\\Users\\user\\AppData\\Local\\Zed\\external_agents\\codex\\v0.9.4": failed to iterate over archive: Invalid gzip header
```
It tries to gunzip a zip file. After this, no matter how many times you restart Zed or upgrade it, Agent Panel is permanently stuck in "(openai logo) Loading..." title bar and blank panel contents.

### Zed version and system specs

Zed: v0.224.11+stable.175.e4cabf49a18ed03969d84ee15643e9ec81857e97 (Zed) 
OS: Windows 10.0.26100
Memory: 15.6 GiB
Architecture: aarch64
GPU: Qualcomm(R) Adreno(TM) X1-85 GPU || Unknown Vendor (ID: 0x4D4F4351) || 31.0.133.2

### Attach Zed log file

_No response_

### Relevant Zed settings

_No response_

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by yeskunall**
Previously only `x86_64` Windows used ZIP archives, but ARM64 Windows builds also use ZIP format.

Closes #50039.

> [!NOTE]
> The P1 is two-fold: the user cannot download the ZIP file on Windows ARM. BUT -- the Agent Panel is stalled because of that. This ONLY makes it so that the ZIP download doesn’t fail, but if for some reason the download fails, the panel is genuinely stuck with no recovery path. Every restart attempts the same download, hits the same GZIP error, and silently drops it again.

Before you mark this PR as ready for review, make sure that you have:
- [ ] Added a solid test coverage and/or screenshots from doing manual testing
- [x] Done a self-review taking into account security and performance aspects
- [x] Aligned any UI changes with the [UI checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)

Release Notes:

- Broaden Windows asset detection to all architectures

### CODE REVIEW

File: crates/project/src/agent_server_store.rs [hunk 1]
```diff
@@ -1615,7 +1615,7 @@ impl ExternalAgentServer for LocalCodex {
                                 &asset.browser_download_url,
                                 digest,
                                 &version_dir,
-                                if cfg!(target_os = "windows") && cfg!(target_arch = "x86_64") {
+                                if cfg!(target_os = "windows") {
```
Comment (yeskunall) [inline crates/project/src/agent_server_store.rs:1618]: Continuing from my note in my PR description, I think this can still be merged as-is.
