### PR TITLE
linux: Various X11 scroll improvements

### LINKED ISSUE #14089: Scroll completely broken (Linux Mint)
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a fresh install of Zed (Stable), when opening the editor, the scroll is not working at all.

Even clicking in the scrollbar does not work.

### Environment

Linux Mint

AMD Ryzen 7 4800H with Radeon Graphics
Geforce GTX 1650 Ti mobile

### PR DESCRIPTION
**Pull request by mgsloan**
Closes  #14089, #14416, #15970, #17230, #18485

Release Notes:

- Fixed some cases where Linux X11 mouse scrolling doesn't work at all  (#14089, ##15970, #17230)
- Fixed handling of switching between Linux X11 devices used for scrolling (#14416, #18485)

Change details:

Also includes the commit from PR #18317 so I don't have to deal with merge conflicts.

* Now uses valuator info from slave pointers rather than master. This
hopefully fixes remaining cases where scrolling is fully
broken. https://github.com/zed-industries/zed/issues/14089, https://github.com/zed-industries/zed/issues/15970, https://github.com/zed-industries/zed/issues/17230

* Per-device recording of "last scroll position" used to calculate
deltas. This meant that swithing scroll devices would cause a sudden
jump of scroll position, often to the beginning or end of the
file (https://github.com/zed-industries/zed/issues/14416).

* Re-queries device metadata when devices change, so that newly
plugged in devices will work, and re-use of device-ids don't use old
metadata with a new device.

* xinput 2 documentation describes support for multiple master
devices. I believe this implementation will support that, since now it
just uses `DeviceInfo` from slave devices. The concept of master
devices is only used in registering for events.

* Uses popcount+bit masking to resolve axis indexes, instead of
iterating bit indices.

### CODE REVIEW

**Comment by mrnugget** [comment]
Hey, thanks for this! I'm going to take a look, try this out, and review code. @apricotbucket28 I'd appreciate a second set of eyes, since you know this area pretty well — if you have the time :)

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 1]
```diff
@@ -1735,3 +1763,231 @@ fn xdnd_send_status(
...
+
+fn get_axis_scroll_delta_and_update_state(axis: &mut ScrollAxisState, new_scroll: f32) -> f32 {
+    let delta_scroll = axis.scroll_value.map_or(0.0, |old_scroll| {
+        (old_scroll - new_scroll) * axis.multiplier
+    });
+    axis.scroll_value = Some(new_scroll);
+    delta_scroll
+}
+
+fn get_valuator_axis_index(valuator_mask: &Vec<u32>, valuator_number: u16) -> Option<usize> {
```
Comment (mrnugget) [inline crates/gpui/src/platform/linux/x11/client.rs:1916]: This and the following 3-4 methods made me wonder whether we shouldn't introduce a `ValuatorMask` type (that might just wrap `Vec<u32>`) and define the methods on that type.

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 2]
```diff
@@ -1735,3 +1763,231 @@ fn xdnd_send_status(
...
+    modifiers: &Modifiers,
+) -> Option<Point<f32>> {
+    let horizontal_axis_index = pointer
+        .horizontal
+        .valuator_number
+        .and_then(|valuator_number| get_valuator_axis_index(&event.valuator_mask, valuator_number));
+    let vertical_axis_index = pointer
+        .vertical
+        .valuator_number
+        .and_then(|valuator_number| get_valuator_axis_index(&event.valuator_mask, valuator_number));
```
Comment (mrnugget) [inline crates/gpui/src/platform/linux/x11/client.rs:1865]: Nitpick, but is there value in having one of these and not the other? If not, I think you can add a `?` at the end here so that we now we have both indices.

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 3]
```diff
@@ -1735,3 +1763,231 @@ fn xdnd_send_status(
...
+            delta_x = Some(get_axis_scroll_delta_and_update_state(
+                &mut pointer.horizontal,
+                fp3232_to_f32(*value),
+            ));
+        } else {
+            log::error!(
+                "Encountered invalid XInput valuator_mask, scrolling may not work properly."
+            )
+        }
+    }
```
Comment (mrnugget) [inline crates/gpui/src/platform/linux/x11/client.rs:1881]: If the `?` change above is made, this can be simplified a lot by dropping the first condition. And since we always require a `delta_x`, that second `if let Some(value) = ` can also be turned into `let delta_x_value = event.axisvalues.get(horizontal_axis_index)?;` I think.

File: crates/gpui/src/platform/linux/x11/client.rs [hunk 4]
```diff
@@ -1735,3 +1763,231 @@ fn xdnd_send_status(
...
+
+    if let Some(vertical_axis_index) = vertical_axis_index {
+        if let Some(value) = event.axisvalues.get(vertical_axis_index) {
```
Comment (mrnugget) [inline crates/gpui/src/platform/linux/x11/client.rs:1884]: Same as above.

**Review by mrnugget — COMMENTED** [review]
Code looks good to me (left some improvement suggestions). Appreciate the tests and pulling out into functions.

I also tried it locally on my Linux/X11 machine, and it didn't break anything, but I also can't confirm/deny that it fixed anything. I trust you here.

So, let me know what you think about the suggested changes and then, pending input from @apricotbucket28, I think we can merge this.

**Review by apricotbucket28 — APPROVED** [review]
The code looks good and it seems to work well on my machine! Don't have a trackpad right now to retest it there, but I don't see why it would break.

The behavior also seems to be more stable than before, since I haven't had the mouse not work randomly.

Great work! 😄

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 2 above)
Comment (mgsloan) [reply crates/gpui/src/platform/linux/x11/client.rs:1865]: It's needed for both to be optional.  It's common for the smooth scrolling events to only have one bit set in the valuator_mask and one value in axisvalues.

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 3 above)
Comment (mgsloan) [reply crates/gpui/src/platform/linux/x11/client.rs:1881]: Good idea, done!

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 4 above)
Comment (mgsloan) [reply crates/gpui/src/platform/linux/x11/client.rs:1884]: Done

File: crates/gpui/src/platform/linux/x11/client.rs (hunk 1 above)
Comment (mgsloan) [reply crates/gpui/src/platform/linux/x11/client.rs:1916]: I moved these to `event.rs` since that seems to be where event-related utilities go.

Could do the `ValuatorMask` newtype thing (I'm a big fan of newtypes!), but I'm leaning towards not making that change.  Rationale is:

1. The other 2 methods aren't really specific to valuators, these are operations that are general bitmask operations on `Vec<u32>`.  It does seem weird to put them here, is there a better place to put them?

2. Would only be constructed in one spot and not passed around, so there are no type safety benefits

**Comment by mgsloan** [comment]
@mrnugget Thanks for reviewing!!  Made some changes based on your feedback.

@apricotbucket28 Thanks for taking a look, glad it's working well for you!!

**Comment by mrnugget** [comment]
Thank you! Hopped on the branch to fix a clippy issue

**Comment by codehd7** [comment]
Just grabbed 0.156.0 build with this fix... On my openSUSE 15.6 system it's working well, and it's *so nice* to scroll with my mouse wheel! Thx @mgsloan :smiley:

**Comment by istudyatuni** [comment]
2nd and 3rd issues from first line in description are not closed
