### PR TITLE
lsp: Fix `vtsls` `completeFunctionCalls` setting being ignored

### LINKED ISSUE #53275: vtsls setting "completeFunctionCalls" does nothing
### Reproduction steps

1. Enable "completeFunctionCalls" in settings
2. Trigger the autocompletion of a function in a ts file.

### Current vs. Expected behavior

Current behavior: function is autocompleted without parentheses
Expected behavior: function is autocompleted with parentheses

### Zed version and system specs

Zed: v0.230.2
OS: linux

### Attach Zed log file

_No response_

### Relevant Zed settings

<details><summary>settings.json</summary>

```"lsp": {
    "vtsls": {
      "settings": {
        "typescript": {
          "suggest": {
            "completeFunctionCalls": true,
            "enabled": true,
          },
        },
      },
    },
  }
```

</details>

### Relevant Keymap

_No response_

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by yeskunall**
Some language servers (notably `vtsls` with `completeFunctionCalls`) update `insertText/textEdit` during `completionItem/resolve` to add snippet content like function call parentheses. Previously, `Completion.new_text` was only set from the initial completion response and never re-derived after resolve, so the snippet text was silently discarded.

Re-derive `new_text` from the resolved `lsp_completion`. Only the text content is updated -- replace/insert ranges are left as anchors from the original response since the LSP ranges in the resolved text_edit are stale when completions are cached across keystrokes (re: #34094).

Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [ ] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Closes #53275.

Release Notes:

- Fixed the `vtsls` `completeFunctionCalls` setting being ignored

### CODE REVIEW

File: crates/project/src/lsp_store.rs [hunk 1]
```diff
@@ -6568,9 +6568,6 @@ impl LspStore {
             .into_response()
             .context("resolve completion")?;
 
-        // We must not use any data such as sortText, filterText, insertText and textEdit to edit `Completion` since they are not suppose change during resolve.
```
Comment (yeskunall) [inline crates/project/src/lsp_store.rs:6571]: Hmm -- on second thought. Smit’s comment should probably remain.

Comment (yeskunall) [reply crates/project/src/lsp_store.rs:6571]: If all else looks good, just ping me and I’ll reintroduce it.

**Review by smitbarmase — CHANGES_REQUESTED** [review]
Looks good overall. Since this still isn’t LSP-spec-correct, we should probably keep that comment.

> // We must not use any data such as sortText, filterText, insertText and textEdit to edit `Completion` since they are not suppose change during resolve.
> // Refer: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion


Also, let’s add a comment referencing the underlying resolve request in [typescript-language-features#L218](https://github.com/microsoft/vscode/blob/838b48504cd9a2338e2ca9e854da9cec990c4d57/extensions/typescript-language-features/src/languageFeatures/completions.ts#L218,) which `vtsls` simply wraps.

This fix should be treated as a workaround for this specific VSCode TypeScript extension case.

**Review by smitbarmase — APPROVED** [review]
