### PR TITLE
Make python's file, line output clickable in terminal

### LINKED ISSUE #16004: Make python's file, line output ctrl+clickable in terminal to jump to error
### Check for existing issues

- [X] Completed

### Describe the feature

In zed's terminal, run:

```
echo "# line 1\n\nprint(1/0)" > /tmp/fail.py
python3 /tmp/fail.py
```

The output is

```
Traceback (most recent call last):
  File "/tmp/fail.py", line 3, in <module>
    print(1/0)
ZeroDivisionError: division by zero
```

But Ctrl+Click on the filepath only takes you to line 1 of the file, not the correct line of the error.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by thorbenk**
Closes #16004.

image

Python formats file and line number references in the form `File "file.py", line 8"`
I'm not a CPython expert, but from a quick look, they appear to come from:
- https://github.com/python/cpython/blob/80e00ecc399db8aeaa9f3a1c87a2cfb34517d7be/Python/traceback.c#L613
- https://github.com/python/cpython/blob/80e00ecc399db8aeaa9f3a1c87a2cfb34517d7be/Python/traceback.c#L927
I am not aware of the possiblity to also encode the column information.

Release Notes:

- File, line references from Python, like 'File "file.py", line 8' are now clickable in the terminal

### CODE REVIEW

File: crates/terminal/src/terminal.rs [hunk 1]
```diff
@@ -926,6 +942,20 @@ impl Terminal {
...
                     let url = term.bounds_to_string(*url_match.start(), *url_match.end());
                     Some((url, true, url_match))
+                } else if let Some(python_match) =
+                    regex_match_at(term, point, &mut self.python_file_line_regex)
+                {
+                    let file_line =
+                        term.bounds_to_string(*python_match.start(), *python_match.end());
+
+                    let (file_path, line_number) = python_extract_path_and_line(file_line.as_str())
+                        .expect("Cannot parse python file line syntax");
```
Comment (SomeoneToIgnore) [inline crates/terminal/src/terminal.rs:952]: I understand that we did a python regex match and should not fail here, but the logic may have flaws (or gain, with later contributions) causing None to be returned here.

For the sake of less panics due to unwrap/expect's in "prod" code, let's replace it with `log_err()?` or, `debug_panic!` if you want to pay more attention to this in debug builds.

I also think we can avoid this entirely, and redo this `else if let` into `else`, then get the `let file_line` and use the regular Rust's regex (see how unit tests do that with `fn re_test` now) to match the rest of the cases, with capture values extractions?

**Review by SomeoneToIgnore — COMMENTED** [review]
Thank you, 
I think we can restructure the PR a bit and get it merged.

For a context, 
https://github.com/zed-industries/zed/issues/12338#issuecomment-2723211292
discussed a way to add some "clever" standard defaults to Zed's terminal parsing, and a list of extra regexes to set in the user config, to match cases like this.

This PR is a good exercise to prepare for this change with a small example, and later, that PR might want to extract this logic into just another regex in the list.

Given that perspective, we can approach the things a bit more generic than the PR does now.

**Comment by thorbenk** [comment]
@SomeoneToIgnore: Thank you very much for your quick and toughtful review. I'll work on improving the MR.

I have updated the issue description to include what I believe is the CPython source where that file, line formatting comes from.

**Comment by thorbenk** [comment]
@SomeoneToIgnore : My initial understanding was that `Terminal` can only use `RegexSearch`, which doesn't seem to support capturing parts of the match? (I don't know how I would use the `left_fdfa`, `right_rdfa` things?).
I've copied the approach from `word_regex` and `url_regex` which use `term.bounds_to_string()`.

I initially _did_ use the regex crate to re-match the found line found via alacritty's `RegexSearch` using the capture groups I provided. But then I saw that `regex` is not part of the crate (though it is a dev dependency for the tests).

If you don't mind me adding this dependency, I can remove the entire `python_extract_path_and_line` function again, and simplify?

**Comment by SomeoneToIgnore** [comment]
Yes, I think we should try using another regex library for this, as we can already ask Alacritty for text lines, and match them separately.

We would still need Alacritty's match, come to think of it more, as it returns its grid coordinates for future highlighting.

**Comment by thorbenk** [comment]
OK, I hope I have improved things, can you have another look @SomeoneToIgnore ?

I considered using `PathWithPosition`, but it doesn't fit here very well, and would probably need a bigger refactoring. Considering the changes that you mentioned (https://github.com/zed-industries/zed/issues/12338#issuecomment-2723211292 ), it's probably better to keep this as localized as possible for now?

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you, looks quite fitting now.

I've decided to omit the logging, the code looks a bit cleaner without it and we know that this case does not happen now — no unwraps either way which is great.
