### PR TITLE
Fix DeepSeek Reasoner tool-call handling and add reasoning_content support

### LINKED ISSUE #43887: DeepSeek Thinking API changes
### Reproduction steps

https://api-docs.deepseek.com/zh-cn/guides/thinking_mode

open zed, use any deepseek api

### Current vs. Expected behavior

thinking mode wont work because it requires reasoning content
~~none thinking mode will just simply stuck zed for some unknown reason~~ fixed

### Zed version and system specs

Zed: v0.216.0+nightly.1971.2e00f40c54e1e0c23af06587cefcfd06eae49a0e (Zed Nightly 2e00f40c54e1e0c23af06587cefcfd06eae49a0e) 
OS: Windows 10.0.26200
Memory: 15.3 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || 25.5.1 (23.19.23.01-250306a-415346C-AMD-Software-Adrenalin-Edition)

### Attach Zed log file

_No response_

### Relevant Zed settings

_No response_

### (for AI issues) Model provider details

DeepSeek official API (DeepSeek v3.2/thinking)

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by Peter-Koenig**
### Problem
DeepSeek's reasoning mode API requires `reasoning_content` to be included in assistant messages that precede tool calls. Without it, the API returns a 400 error:

```
Missing `reasoning_content` field in the assistant message at message index 2
```

### Added/Fixed/Improved
- Add `reasoning_content` field to `RequestMessage::Assistant` in `crates/deepseek/src/deepseek.rs`
- Accumulate thinking content from `MessageContent::Thinking` and attach it to the next assistant/tool-call message
- Wire reasoning content through the language model provider in `crates/language_models/src/provider/deepseek.rs`

### Testing
- Verified with DeepSeek Reasoner model using tool calls
- Confirmed reasoning content is properly included in API requests

Fixes tool-call errors when using DeepSeek's reasoning mode.

### CODE REVIEW

**Comment by Peter-Koenig** [comment]
@cla-bot check

**Comment by pandaligx** [comment]
Is the merge done?

**Comment by Peter-Koenig** [comment]
> Is the merge done?

I am not part of the zed team, no one knows me - and to be honest: It is my first contribution to a software of this level of quality. So they will probably look very carefully through the code I provided.

I would expect that the review and merge process will take at least few days.

**Comment by shenjackyuanjie** [comment]
image

PR tested, fix works

File: crates/language_models/src/provider/deepseek.rs [hunk 1]
```diff
@@ -343,10 +345,14 @@ pub fn into_deepseek(
...
                         content: Some(text),
                         tool_calls: Vec::new(),
+                        reasoning_content: current_reasoning.take(),
                     },
                     Role::System => deepseek::RequestMessage::System { content: text },
                 }),
-                MessageContent::Thinking { .. } => {}
+                MessageContent::Thinking { text, .. } => {
+                    // Accumulate reasoning content for next assistant message
+                    current_reasoning.get_or_insert_default().push_str(&text);
```
Comment (benbrandt) [inline crates/language_models/src/provider/deepseek.rs:354]: @Peter-Koenig I cleaned a lot up because there seemed to be a lot of unneeded changes... I assume by the AI you used.

I also made one change here. You were just replacing the text, but if for some reason there were two thinking texts I assume your comment of "accumulation" would imply needing to push this to the current string, not just replace it so none is lost. 

does this make sense to you? Do you want to try it out again with these changes and make sure it is still working for you in these use cases?

Comment (Peter-Koenig) [reply crates/language_models/src/provider/deepseek.rs:354]: Great, thank you! It builds and the reasoner mode works, too! :-)
