### PR TITLE
macOS: Fix IME action when deleting last char

### LINKED ISSUE #12862: IME delete misalignment after output
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems like it always removes an extra character at the end

```go
具 Go版本")
        // Input `nihao`
        // Remove `ihao`          
        // And Remove `n`
        // ^ It will be mistakenly deleted `)`
```
pinyin:

https://github.com/zed-industries/zed/assets/45585937/9909fe45-d6c1-45f1-a60b-89bd2102f827

sougou:

https://github.com/zed-industries/zed/assets/45585937/14213410-f1f6-4fb9-8255-10c73ce841a0

Demo of my actual usage 🙃:

https://github.com/zed-industries/zed/assets/45585937/857d285d-c9ef-4473-8a07-a6ea819d8388

### Environment

Zed: v0.140.0 (Zed Nightly 05b658114750e9b63717ec3d05b316a927d8378e)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #12862 

https://github.com/zed-industries/zed/assets/14981363/170b1206-5894-4b90-bd5c-79761073d8f2

Release Notes:

- Fixed deleting the last character during IME composition would mistakenly delete other characters.(#12862)

### CODE REVIEW

File: crates/gpui/src/platform/mac/window.rs [hunk 1]
```diff
@@ -1248,7 +1251,8 @@ extern "C" fn handle_key_event(this: &Object, native_event: id, key_equivalent:
         let is_composing =
             with_input_handler(this, |input_handler| input_handler.marked_text_range())
                 .flatten()
-                .is_some();
```
Comment (JunkuiZhang) [inline crates/gpui/src/platform/mac/window.rs:1251]: `is_composing` will be `false` when deleting the last char when IME composing, then `KeyDown("backspace")` is propagated, leads to mis-deleting other char.

**Comment by ConradIrwin** [comment]
THanks!
