### PR TITLE
gpui: Fix anchored element size calculation with negative coordinates

### LINKED ISSUE #53202: Right-click context menu spawns at the top of agent panel
### Reproduction steps

1. Start Zed
2. Open Agent Panel (Zed Agent or Claude Agent)
3. Ensure content (Open history or ask something)
4. Right-click somewhere

### Current

The context menu is spawned at the top of the panel, not at the cursor. This happens with selection and without.

Zed-Agent (1 = cursor right click position)

Image

Claude-Agent (1 = cursor right click position)

Image

### Expected

The context menu should be opening at the cursor.

### Notes

This has already been reported in #51282 and it was reported fixed for the reporter, however I still have the exact same issue as seen with the screenshots. The video attached in #51282 also shows exactly the behaviour I see.

### Zed version and system specs

```
Zed 0.230.1 
bf3a14350a4fa4b67747afe2e50128fb8fea4fa3

0.230.1+stable.210.bf3a14350a4fa4b67747afe2e50128fb8fea4fa3
```

```
OS: CachyOS x86_64
Kernel: Linux 6.19.11-1-cachyos
DE: KDE Plasma 6.6.3
WM: KWin (Wayland)
```

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by agu-z**
Closes #53202 

`Anchored::prepaint` computes the bounding box of its children to determine the size used for fitting the anchored element in the window.

Previously, this calculation manually tracked the minimum origin and maximum bottom-right point, initializing the maximum point to `(0, 0)`. If child bounds were in negative coordinates, the maximum point could be clamped to `(0, 0)`, inflating the computed size.

This replaces the manual min/max accumulation with `Bounds::union`, starting from the actual child bounds instead of sentinel values. This computes the child bounding box correctly regardless of coordinate sign.

---

Self-Review Checklist:

- [x] I've reviewed my own diff for quality, security, and reliability
- [x] Unsafe blocks (if any) have justifying comments
- [x] The content is consistent with the [UI/UX checklist](https://github.com/zed-industries/zed/blob/main/CONTRIBUTING.md#uiux-checklist)
- [x] Tests cover the new/changed behavior
- [x] Performance impact has been considered and is acceptable

Release Notes:

- Fixed a bug where the context menu in the agent panel (and other scrollable surfaces) would appear at the wrong location

### CODE REVIEW

File: crates/gpui/src/elements/anchored.rs [hunk 1]
```diff
@@ -132,19 +132,17 @@ impl Element for Anchored {
...
-            child_min = child_min.min(&child_bounds.origin);
-            child_max = child_max.max(&child_bounds.bottom_right());
-        }
-        let size: Size<Pixels> = (child_max - child_min).into();
+        let children_bounds = request_layout
+            .child_layout_ids
+            .iter()
+            .map(|id| window.layout_bounds(*id))
+            .reduce(|acc, bounds| acc.union(&bounds))
+            .unwrap();
```
Comment (MrSubidubi) [inline crates/gpui/src/elements/anchored.rs:140]:
```suggestion
            .unwrap_or_default();
```

I think we cannot safely assume that there are any children, no?

**Review by MrSubidubi — CHANGES_REQUESTED** [review]

File: crates/gpui/src/elements/anchored.rs (hunk 1 above)
Comment (agu-z) [reply crates/gpui/src/elements/anchored.rs:140]: This function returns early if there are no children

**Review by MrSubidubi — APPROVED** [review]
