### PR TITLE
collab: Fix project sharing between Windows and Unix

### LINKED ISSUE #14258: Zed does not divide Paths correctly when sharing from Windows to Linux
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm on Linux and my friend on Windows 10. When she shares her Code with me my whole sidebar gets spammed with single path entries.

image

### Environment

Me: Arch Linux & Linux 6.9.6-2-cachyos
Her: Windows 10.0.19045

If more is required (What i dont think is needed) just ask.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I mean its obvious lol

image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

### PR DESCRIPTION
**Pull request by JunkuiZhang**
Closes #14258

Windows user(host) sharing a project to a guest(using macOS), and host follows guest:

https://github.com/user-attachments/assets/ba306b6b-23f7-48b1-8ba8-fdc5992d8f00

macOS user(host) sharing a project to a guest(using Windows), and host follows guest:

https://github.com/user-attachments/assets/c5ee5e78-870d-49e5-907d-8565977a01ae

macOS user edits files in a windows project through collab:

https://github.com/user-attachments/assets/581057cf-e7df-4e56-a0ce-ced74339906a

Release Notes:

- N/A

### CODE REVIEW

**Comment by mikayla-maki** [comment]
> It's ZED_STATELESS causing this issue. If I set ZED_STATELESS="1", the host can't see the guest's actions when the host follows the guest. If I set ZED_STATELESS="", everything is just fine.

This seems very strange, ZED_STATELESS should only affect the sqlite db we use to save your application state. Any theories for why it's messing up the host?

**Comment by JunkuiZhang** [comment]
I can reproduce this with both A and B are on the same mac.

In a new terminal, set the following for A:
```bash
export ZED_IMPERSONATE="as-cii"
export ZED_SERVER_URL="http://127.0.0.1:3000"
export ZED_RPC_URL="http://192.168.0.107:8080/rpc"
export ZED_ADMIN_API_TOKEN="secret"
export ZED_CLIENT_CHECKSUM_SEED="development-checksum-seed"
export ZED_STATELESS="1"  // Key setting
```

Then `cargo run` to open an instance of zed for A.

In a new terminal:
```bash
export ZED_IMPERSONATE="nathansobo"
export ZED_SERVER_URL="http://127.0.0.1:3000"
export ZED_RPC_URL="http://192.168.0.107:8080/rpc"
export ZED_ADMIN_API_TOKEN="secret"
export ZED_CLIENT_CHECKSUM_SEED="development-checksum-seed"
export ZED_STATELESS=""  // Dose not matter
```

Then `cargo run` to open an instance of zed for B.

- A shares a project with B
- B accept, then cancel the following
- A (host) follows B (guest)
- B perform some actions
- A can not see the actions

File: crates/collab/src/db.rs [hunk 1]
```diff
@@ -688,6 +688,9 @@ impl RejoinedProject {
 #[derive(Debug)]
 pub struct RejoinedWorktree {
     pub id: u64,
+    /// NOTE:
+    /// Use PathBuf::to_proto() and PathBuf::from_proto() to convert between
```
Comment (mikayla-maki) [inline crates/collab/src/db.rs:692]: I think these comments are a good idea, but I don't think they provide much benefit in the end. Let's remove everything with `NOTE:` in this PR.

Comment (mikayla-maki) [reply crates/collab/src/db.rs:692]: As well as all of the `// path`, and other such comments.

**Review by mikayla-maki — CHANGES_REQUESTED** [review]

**Comment by mikayla-maki** [comment]
Also, it would be nice to figure out why `ZED_STATELESS` is breaking your collaboration. And we should make sure we're syncing the host's OS over the wire so that we can display paths properly. But I think that those can be in a separate PR :)

File: crates/collab/src/db.rs (hunk 1 above)
Comment (JunkuiZhang) [reply crates/collab/src/db.rs]: I have removed all the comments, but I'm not sure how we can ensure that other developers use the relevant functions correctly. After all, Zed is an open-source project, and some contributors may not be aware of this, potentially leading them to mistakenly use `to_string_lossy().to_string()`, which could result in hard-to-detect bugs.

**Comment by JunkuiZhang** [comment]
> Also, it would be nice to figure out why `ZED_STATELESS` is breaking your collaboration.

`ZED_STATELESS` may not be the issue in this PR, as I am able to reproduce the problem on the current main branch as well. This is very strange.

> And we should make sure we're syncing the host's OS over the wire so that we can display paths properly. But I think that those can be in a separate PR :)

Actually, my thinking is that this setup works quite well as it is. Currently, the Windows path `path\to\file.rs` is displayed as `path\to\file.rs` on Windows, but on macOS, it is displayed as `path/to/file.rs`, which feels like that the Windows project is running natively on macOS.

**Review by mikayla-maki — APPROVED** [review]
