### PR TITLE
git: Skip directories in git status output

### LINKED ISSUE #23133: Incorrect project panel highlighting with nested git repos
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce:

```
mkdir parent
cd parent
git init
echo foo >foo
git add foo
git commit -m Foo
mkdir child
cd child
git init
echo bar >bar
git add bar
git commit -m Bar
```

and then open Zed at `parent`. `parent` will be highlighted in green in the project panel, when it should be colorless.

### Zed Version and System Specs

Zed: v0.170.0 (Zed Nightly 1b3b825c7f646f2fb34e2bceb6be33f310dfeb59)
OS: macOS 15.1.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by cole-miller**
The output of `git status --porcelain=v1` includes untracked directories, i.e. directories that have no tracked files beneath. Since we have our own way of computing a "summary" status for each directory in a repo, this is not helpful for Zed; and it interferes with our handling of nested repos. So just skip these lines in the output.

Closes #23133 

Release Notes:

- Fix project panel colors when one git repository is nested beneath another

### CODE REVIEW

File: crates/git/src/status.rs [hunk 1]
```diff
@@ -440,6 +440,13 @@ impl GitStatus {
                     return None;
                 };
                 let path = &entry[3..];
+                // The git status output includes untracked directories as well as untracked files.
+                // We do our own processing to compute the "summary" status of each directory,
+                // so just skip any directories in the output, since they'll otherwise interfere
+                // with our handling of nested repositories.
+                if path.ends_with('/') {
+                    return None;
+                }
```
Comment (cole-miller) [inline crates/git/src/status.rs:449]: @JunkuiZhang do you know how I would phrase this check to make it work on Windows as well?

Comment (JunkuiZhang) [reply crates/git/src/status.rs:449]: It works fine on Windows. It seems that the path separator in Git’s output is always `/`.

```text
?? target/debug/deps/libwindows_result-ad6d65ada4f96792.rmeta?? target/debug/deps/libwindows_strings-26b57c01791bc538.rmeta?? target/debug/deps/libwindows_strings-6d7984612365129c.rmeta?? target/debug/deps/libwindows_targets-34036814e4386831.rmeta?? target/debug/deps/libwindows_targets-b9caf3436e4dc6e1.rmeta?? target/debug/deps/libwindows_x86_64_msvc-3932703755246f28.rmeta?? target/debug/deps/libwindows_x86_64_msvc-b6e1a25b755c6f60.rmeta?? target/debug/deps/proc_macro2-4ddf4cb61ac47cd8.d?? target/debug/deps/quote-43e14e347d452698.d?? target/debug/deps/syn-50b795667b2bc5f1.d?? target/debug/deps/unicode_ident-37752bbd18f54ca8.d?? target/debug/deps/windows-c26660cda881e485.d?? target/debug/deps/windows_core-a93dd48e81224fec.d?? target/debug/deps/windows_implement-89faa90c7f9ee176.d
```
