### PR TITLE
vim: Fix `insert before` in visual modes

### LINKED ISSUE #22536: VIM mode visual block shift-i behaviour incorrect
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In normal vim, when you do a visual block selection, you can then press shift-I or shift-A to add text to the beginning or end of the block selection respectively (as in, the left or right side of it on all the selected lines).

While this behaviour seems to be mostly there in zed, both of them place the editing cursor before and after the block cursors instead. 

### Zed Version and System Specs

Zed: v0.166.2 (Zed)
OS: Linux X11 arch unknown
Memory: 15.6 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1060 6GB || NVIDIA || 565.77

### If applicable, add screenshots or screencasts of the incorrect state / behavior

Example with shift-I going wrong:
image
image
Hard to tell because of the cursor shape, but the block selection is gone and the cursor was placed right before where the more opaque cursors were for a lack of a better word

Example wth shift-A going wrong (selecting a block then moving left):
image
image

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by 5brian**
Closes #22536

Changes:
- Visual and visual block: Cursor at start of selection.
- Visual line: Cursor at start on line.
  - Uses different handling since the selection does not actually change in vline.

Release Notes:

- vim: Fixed insert before (`shift-i`) in visual modes.

### CODE REVIEW

File: crates/vim/src/normal.rs [hunk 1]
```diff
@@ -281,16 +281,50 @@ impl Vim {
...
+                });
             });
-        });
+            self.switch_mode(Mode::Insert, false, window, cx);
+        } else {
+            self.switch_mode(Mode::Insert, false, window, cx);
+            self.update_editor(window, cx, |_, editor, window, cx| {
+                editor.change_selections(Some(Autoscroll::fit()), window, cx, |s| {
+                    s.move_cursors_with(|map, cursor, _| {
+                        (right(map, cursor, 1), SelectionGoal::None)
```
Comment (5brian) [inline crates/vim/src/normal.rs:304]: Can this be written in a more concise way?

**Comment by ConradIrwin** [comment]
Thanks! If you wanted another one,`shift-a` in line mode is still wrong.

**Comment by 5brian** [comment]
@ConradIrwin Thats what I thought as well, but when doing `shift-a` in both neovim and neovim clean, `shift-a` actually does not move the cursor to the end. 

Would you still want it to implement the `shift-a`?

**Comment by ConradIrwin** [comment]
Huh, you're totally right. Seems fine to leave as is
