### PR TITLE
Fix multiline regex

### LINKED ISSUE #45776: Replace empty lines with regex
### Reproduction steps

Replacing empty lines with this regular expression does not work: `^$\n`

sample file:
```
line 1


line 2
line 3


line 4
```

### Current vs. Expected behavior

```
line 1
line 2
line 3
line 4
```

### Zed version and system specs

Zed 0.217.3 
80433cb239e868271457ac376673a5f75bc4adb1

0.217.3+stable.105.80433cb239e868271457ac376673a5f75bc4adb1

macOS: 15.5 (24F74)

### Attach Zed log file

<details><summary>Zed.log</summary>

```log

```

</details>

### Relevant Zed settings

<details><summary>settings.json</summary>

```json

```

</details>

### Relevant Keymap

<details><summary>keymap.json</summary>

```json

```

</details>

### (for AI issues) Model provider details

_No response_

### If you are using WSL on Windows, what flavor of Linux are you using?

None

### PR DESCRIPTION
**Pull request by Zachiah**
Closes #45776

It didn't enable multiline mode before `¯\_(ツ)_/¯`. If there is a reason this fix won't work please let me know but it seems like this one was just an easy fix.

Release Notes:
- Improved multiline regex behavior

### CODE REVIEW

File: crates/project/src/search.rs [hunk 1]
```diff
@@ -180,6 +180,10 @@ impl SearchQuery {
         }
 
         let multiline = query.contains('\n') || query.contains("\\n");
+        if multiline {
+            query.insert_str(0, "(?m)");
```
Comment (SomeoneToIgnore) [inline crates/project/src/search.rs:184]: Can there be a situation when a query already contains this?
Then, we'll spoil it by doing so?

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
There is a way to add a test for this, is there not?

File: crates/project/src/search.rs (hunk 1 above)
Comment (Zachiah) [reply crates/project/src/search.rs:184]: That's a really good observation thanks! I just tested it and it works just the same as if you hadn't included it.

**Comment by Zachiah** [comment]
@SomeoneToIgnore Good catch. Just added a test. Thank you!

**Review by SomeoneToIgnore — APPROVED** [review]
Thank you!
