### PR TITLE
Publish theme json schema v0.2.0

### LINKED ISSUE #12319: Themes JSON schema is incomplete
### Check for existing issues

- [X] Completed

### Describe the feature

 The example scheme file is missing some attributes with the description, see some examples below. 

Link: https://zed.dev/schema/themes/v0.1.0.json

`conflict.background, conflict.border, created.background, created.border, deleted.background, ecc..`

For example for `syntax`, the description of all keys is missing.

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #21335: Missing field in themes JSON Schema
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

[Zed's json schema said](https://zed.dev/schema/themes/v0.1.0.json) that there's only three properties in `HighlightStyleContent`: `color`, `font_style` and `font_weight`. [in the code](https://github.com/zed-industries/zed/blob/69c761f5a5e8a33e86966fa59d2a58622b5cda62/crates/theme/src/schema.rs#L1362)  there's also a `background_color` that is really important for nice themes like [FlatWhite](https://github.com/biletskyy/flatwhite-syntax/issues/37).

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by notpeter**
- Closes: https://github.com/zed-industries/zed/issues/12319
- Closes: https://github.com/zed-industries/zed/issues/21335

Fix theme json schema so `./script/import-themes print-schema` works again
Update schema to reflect current structs ([diff](https://gist.github.com/notpeter/26e6d0939985f542e8492458442ac62a/revisions?diff=unified&w=))

Release Notes:

- Publish updated JSON Schema for themes [v0.2.0.json](https://zed.dev/schema/themes/v0.2.0.json)

### CODE REVIEW

File: crates/theme_importer/src/vscode/converter.rs [hunk 1]
```diff
@@ -11,6 +11,8 @@ use crate::ThemeMetadata;
 
 use super::ZedSyntaxToken;
 
+const ZED_THEME_SCHEMA_URL: &'static str = "https://zed.dev/schema/themes/v0.1.0.json";
```
Comment (maxdeviant) [inline crates/theme_importer/src/vscode/converter.rs:14]: We really shouldn’t be regenerating new versions of the same schema.

Each time we make changes to the schema that should be a new version.
