### PR TITLE
Fix permalink-to-line when Git repo root and worktree dir don't coincide

### LINKED ISSUE #21505: `Copy Permalink` doesnt keep the filepath if zed is used from outside of the git repo
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
~/
  Foo/    <- git repo
    a.txt
  Bar/    <- Zed open here
```
if you open `Foo/a.txt` from within `Bar` the copy permalink action doesnt copy the path and you just end up with `https://github.com/<org>/<repo>/blob/<hash>/#L1`

### Environment

Zed: v0.165.0 (Zed Dev e1c509e0de487d5ed6f0ad66e62be2063654f888)
OS: Linux Wayland alpine 3.21.0_alpha20240923
Memory: 15.6 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6950 XT (RADV NAVI21) || radv || Mesa 24.2.7

### If applicable, add mockups / screenshots to help explain present your vision of the feature

_No response_

### If applicable, attach your Zed.log file to this issue.

_No response_

### PR DESCRIPTION
**Pull request by cole-miller**
Closes #21505. This should work if the git dir is an ancestor of the worktree dir or vice versa.

Release Notes:

- Fixed GitHub permalink-to-line actions when worktree dir and Git dir aren't the same

### CODE REVIEW

File: crates/project/src/buffer_store.rs [hunk 1]
```diff
@@ -1236,6 +1237,18 @@ impl BufferStore {
                         parse_git_remote_url(provider_registry, &origin_url)
                             .ok_or_else(|| anyhow!("failed to parse Git remote URL"))?;
 
+                    let dot_git_dir = repo.path();
+                    let Some(git_dir) = dot_git_dir.parent() else {
+                        bail!("unexpected bare Git repository");
```
Comment (mgsloan) [inline crates/project/src/buffer_store.rs:1242]: I don't think this is a bare repository, those have `.git` but don't have worktree.  So maybe ""

I'm not sure how this would interact with Zed, but there is also a possibility the user might set `GIT_DIR` or configure some dir other than `.git`.  It's a bit atypical, but I use this on my home dir so that my whole config is in a git repo.  It's a pretty niche case, I even needed to hack magit to allow `GIT_DIR` to be set https://github.com/mgsloan/mgsloan-dotfiles/blob/master/env/home-dir-git.md

Comment (cole-miller) [reply crates/project/src/buffer_store.rs:1242]: Yes, good point, it's narrower than the current error message suggests. I agree that we shouldn't be able to have a bare repository here, probably makes more sense to just unwrap (I've been fixing panics so probably came into this PR with a prejudice in the other direction…)

**Comment by cole-miller** [comment]
This now has support for getting permalinks when viewing a Rust source file inside the local Cargo registry! Thanks @mgsloan for suggesting this.

**Comment by mgsloan** [comment]
@cole-miller That's awesome, thanks for making that work!!
